pkg/sources/gcppubsub/gcppubsub-serviceentry.yaml
Addresses #224 
*  Add ServiceEntry objects for accessing metadata service for getting the credentials.
* 
*
=> Add service entries so receive adapter can access metadata server

cmd/webhook/main.go, pkg/controller/channel/controller.go, pkg/controller/clusterbus/controller.go, pkg/system/names.go, pkg/webhook/certs.go, pkg/webhook/webhook.go, pkg/webhook/webhook_test.go
Moving eventing to be more in-line with Serving.
=> Use serving style system package for namespace.

pkg/apis/feeds/v1alpha1/cluster_event_source_types.go, pkg/apis/feeds/v1alpha1/event_type_types.go, pkg/apis/feeds/v1alpha1/feed_types.go, pkg/controller/feed/reconcile.go, pkg/webhook/cluster_event_type.go, pkg/webhook/event_type.go, pkg/webhook/feed.go, pkg/webhook/feed_test.go, pkg/webhook/webhook_channels_test.go, pkg/webhook/webhook_feeds_test.go, pkg/webhook/webhook_test.go
Replaces https://github.com/knative/eventing/pull/266
=> Add cluster scoped feed webhooks

pkg/apis/feeds/v1alpha1/feed_types.go, pkg/apis/flows/v1alpha1/flow_types.go, pkg/controller/flow/reconcile.go
Clarifies the relationship between these two types, since they have very similar specs.
=> Clarify relationship between Feeds and Flows

pkg/apis/channels/v1alpha1/subscription_defaults.go, pkg/apis/channels/v1alpha1/subscription_types.go, pkg/apis/channels/v1alpha1/subscription_validation.go, pkg/apis/channels/v1alpha1/subscription_validation_test.go, pkg/webhook/subscription.go, pkg/webhook/subscription_test.go
This is the continued effort to stage the required methods for integration with pkg/webhook.
=> Stage subscriptions to be validatable by new webhook.

pkg/apis/feeds/v1alpha1/feed_defaults.go, pkg/apis/feeds/v1alpha1/feed_validation.go, pkg/apis/feeds/v1alpha1/feed_validation_test.go, pkg/webhook/feed.go, pkg/webhook/feed_test.go
This is the continued effort to stage the required methods for integration with pkg/webhook.
=> Stage feeds to be validatable by new webhook.

.github/pull-request-template.md
=> Sync our pr template to match serving.

pkg/apis/channels/v1alpha1/subscription_validation.go, pkg/apis/feeds/v1alpha1/feed_types.go, pkg/apis/flows/v1alpha1/flow_types.go, pkg/buses/message_receiver.go, pkg/event/handler.go, pkg/event/handler_test.go
From: https://goreportcard.com/report/github.com/knative/eventing#misspell
```release-note
NONE
```
=> Fix misspellings of a few words in the code base.

pkg/apis/flows/v1alpha1/flow_types_test.go, pkg/controller/feed/resources/job.go, pkg/controller/util/subscription_util.go, pkg/event/handler.go, pkg/sources/container_event_source_job.go, pkg/sources/gcppubsub/watcher_pod.go, pkg/sources/k8sevents/watcher_pod.go
Based on the report from https://goreportcard.com/report/github.com/knative/eventing#gofmt, I ran the code through the format tool in simplify mode.
```release-note
NONE
```
Grant for LGTM:
/cc @grantr
Evan for Approval:
/assign @evankanderson
=> Ran gofmt -s  on the repo.

pkg/controller/channel/controller.go
Check and return the correct errors.
```release-note
NONE
```
=> Check and return the correct errors.

pkg/controller/flow/reconcile.go
Remove some dead code I happened across poking around the codebase. :)
=> Remove dead code.

README.md
Fixes #301
* Add a link to the README to point to working group document for Eventing.
```release-note
NONE
```
/assign @evankanderson
=> Link to working group document.

pkg/buses/stub/bus.go
The Channel and Subscription are interesting context to capture for
messages logged within stub bus.
Follow up to #386
```release-note
NONE
```
/assign @greghaynes
=> Add logger context for stubbus

OWNERS
From [ROLES.MD](https://github.com/knative/docs/blob/dfc53c67c8e80d30b8863353c9e9b4ad00c41fa0/community/ROLES.md#approver):
> Reviewer of the codebase for at least 3 months or 50% of project lifetime, whichever is shorter
- [First Issue](https://github.com/knative/eventing/issues/80). Opened 6/11
- [First PR](https://github.com/knative/eventing/pull/66). Opened 5/31
- [First Review](https://github.com/knative/eventing/pull/79#pullrequestreview-127722273) 6/11
> Primary reviewer for at least 10 substantial PRs to the codebase
- https://github.com/knative/eventing/pull/422#pullrequestreview-153941356
- https://github.com/knative/eventing/pull/414#pullrequestreview-152302026
- https://github.com/knative/eventing/pull/325#pullrequestreview-143676086
- …
=> Add scothis as an approver

pkg/apis/eventing/v1alpha1/cluster_provisioner_defaults_test.go, pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go, pkg/apis/eventing/v1alpha1/cluster_provisioner_types_test.go
Follow-up to https://github.com/knative/eventing/pull/423
* Adding more unit testing for `ClusterProvisioner`.
```release-note
NONE
```
=> Improve code coverage on cluster provisioner.

Gopkg.lock, Gopkg.toml, pkg/apis/eventing/v1alpha1/source_types.go, pkg/apis/eventing/v1alpha1/source_types_test.go, pkg/controller/eventing/subscription/reconcile.go, vendor/github.com/knative/pkg/apis/duck/cached.go, vendor/github.com/knative/pkg/apis/duck/enqueue.go, vendor/github.com/knative/pkg/apis/duck/interface.go, vendor/github.com/knative/pkg/apis/duck/typed.go, vendor/github.com/knative/pkg/apis/duck/unstructured.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go, vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
* No need to define Get/SetConditions 🎉 🎉 🎉 
```release-note
NONE
```
=> Updating pkg and including new reflection based Get/SetConditions. 🎉 

pkg/apis/eventing/v1alpha1/source_types.go
`ConditionManager.MarkFalse` is a variadic func
=> Fix passing args to variadic func

pkg/apis/eventing/v1alpha1/channel_types.go, pkg/apis/eventing/v1alpha1/channel_types_test.go, pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go, pkg/apis/eventing/v1alpha1/cluster_provisioner_types_test.go, pkg/apis/eventing/v1alpha1/subscription_types.go, pkg/apis/eventing/v1alpha1/subscription_types_test.go
* Leverage the json duck type to remove GetJSONSpec
* Leverage the new reflection based ConditionManager to remove Get/SetConditions
```release-note
None
```
=> Cleanup of methods now supported via ducktype.

pkg/controller/eventing/subscription/reconcile.go
* Use conversion from ref to kind from pkg, remove duplicate code.
* https://github.com/knative/pkg/pull/84
=> use KindToResource from knative/pkg now that it has been moved there

config/buses/kafka/README.md
Fixes #476 
* Added instruction for enabling kafka containers to run as root in OpenShift
```release-note
none
```
=> Added instruction for installing kafka broker on OpenShift.

test/e2e-tests.sh, test/upload-test-images.sh
Fixes #500
* Fix image tagging of test images.
=> List only images tagged with latest before tagging

config/buses/kafka/strimzi/kafka-ephemeral.yaml, config/buses/kafka/strimzi/kafka-persistent.yaml
Fixes #521
* removing unneeded content from the strimzi yaml files, for a simple install experience
Tested with latest Strimzi 0.8.0 release
=> Simplify Strimzi install for Kubernetes Kafka deployment

cmd/controller/main.go
This also allows the Controller to run outside of a K8s cluster. The following is the config I use to do so in GoLand:
```xml
<configuration name="EventingController" type="GoApplicationRunConfiguration" factoryName="Go Application">
<module name="eventing" />
<working_directory value="$PROJECT_DIR$/" />
<go_parameters value="-i" />
<parameters value="--hardcodedLoggingConfig --kubeconfig=$USER_HOME$/.kube/config --experimentalControllers=subscription.eventing.knative.dev" />
<kind value="DIRECTORY" />
<filePath value="$PROJECT_DIR$/|$PROJECT_DIR$/cmd/controller/" />
<package value="github.com/knative/eventing" />
<directory value="$PROJECT_DIR$/cmd/controller" />
<method v="2" />
</configuration>
```
* Use a single method to get the kubeconfig, rather than three different ones (two of …
=> Simplify the controller's main function.

pkg/controller/owner_references.go
* Add helpers for making owner refs.
```release-note
NONE
```
=> Add eventing owner ref helpers for new eventing

cmd/fanoutsidecar/kodata/VENDOR-LICENSE
=> Update VENDOR-LICENSE link.

hack/release.sh, hack/update-codegen.sh, hack/update-deps.sh, hack/verify-codegen.sh
* ./hack scripts will now work in mac without anything special if you have installed bash4 and set it as default bash.
```release-note
NONE
```
=> Ask env for preferred bash path.

pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go
* [Test only] Atomically write files in the file system test.
I've found Prow to flake on github.com/knative/eventing/pkg/sidecar/configmap/filesystem ([1](https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_eventing/555/pull-knative-eventing-unit-tests/1055147514296012800/), [2](https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_eventing/555/pull-knative-eventing-unit-tests/1055166137253236736/)). I believe this is caused by the test using `ioutil.WriteFile`, which internally opens the file with O_TRUNC. This means that there are actually two file updates that occur:
1. Truncate the file.
1. Write the new contents.
This creates a race condition, did the file system watcher notice and take action before or after 2? If it takes action before 2, then …
=> Atomically write the file, rather than opening with truncate.

docs/spec/overview.md
=> minor edits

config/provisioners/in-memory-channel/in-memory-channel.yaml
* Update in-memory-channel.yaml to conform to the changes made in https://github.com/knative/eventing/pull/562
```release-note
NONE
```
=> Update in-memory-channel.yaml to conform to the changes made in https://github.com/knative/eventing/pull/562

pkg/controller/eventing/inmemory/channel/reconcile_test.go
* Add a unit test to prevent regressions of https://github.com/knative/eventing/pull/568
```release-note
NONE
```
=> Add a unit test to prevent regressions of https://github.com/knative/eventing/pull/568

pkg/apis/eventing/v1alpha1/subscribable_channelable_validation_test.go
Fixes #591
* Add test cases for pkg/apis/eventing/v1alpha1/subscribable_channelable_validation_test.go
=> Add tests for pkg/apis/eventing/v1alpha1

config/provisioners/kafka/kafka-provisioner.yaml
following other resources, using listed notations
=> use listed notation

.gitignore, pkg/apis/eventing/v1alpha1/subscribable_channelable_validation.go, pkg/apis/eventing/v1alpha1/subscribable_channelable_validation_test.go
Remove old versions of methods related to the deleted subscribable interface.
=> Remove obsoleted code for subscribable interface

pkg/channeldefaulter/channel_defaulter_test.go, test/crd.go
Produced via: `github.com/client9/misspell`
=> Fix spelling errors

hack/release.md, hack/release.sh, test/e2e-tests.sh
=> Publish nightly knative/eventing releases to knative-nightly

.github/issue-template.md, .github/pull-request-template.md, DEVELOPMENT.md, README.md, config/provisioners/in-memory-channel/README.md, config/provisioners/kafka/README.md, config/provisioners/kafka/broker/README.md, docs/personas.md, docs/spec/interfaces.md, docs/spec/motivation.md, docs/spec/overview.md, hack/README.md, hack/release.md, roadmap.md, test/README.md, test/e2e/README.md
Produced via: `prettier --write $(find -name '*.md' | grep -v vendor)`
=> Format markdown

OWNERS
@Harwayne is on the path to approver but needs more reviews. This change makes Prow suggest him as a reviewer along with the existing approvers.
=> Add @Harwayne as reviewer

config/provisioners/in-memory-channel/in-memory-channel.yaml, config/provisioners/kafka/kafka.yaml, config/provisioners/natss/provisioner.yaml
- RBAC permission to update Services. Should have been part of #666.
```release-note
NONE
```
=> RBAC permission to update Services. Should have been part of #666.

pkg/provisioners/gcppubsub/controller/channel/reconcile_test.go, pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile_test.go
Produced via: `goimports -w $(find -name '*.go' | grep -v vendor)`
=> Run goimports

Gopkg.lock, config/500-controller.yaml, config/500-webhook.yaml, config/provisioners/gcppubsub/gcppubsub.yaml, config/provisioners/in-memory-channel/in-memory-channel.yaml, config/provisioners/kafka/broker/kafka-broker.yaml, config/provisioners/kafka/kafka.yaml, config/provisioners/natss/natss/natss.yaml, config/provisioners/natss/provisioner.yaml, test/crd.go, test/e2e/e2e.go
This PR updates api version for several types of objects which were recently graduated to GA
```release-note
None
```
=> api version cleanup

AUTHORS
ping @dewitt @mbehrendt
Signed-off-by: Doug Davis <dug@us.ibm.com>
=> Add IBM to Authors

cmd/controller/main.go
- remove unused constant - usage was removed in 111089f9a3ef7aad2c9f3e5080a0b1a0b47b1e94 
cc @scothis
=> Remove unused constant

OWNERS
- Add Scott Nichols aka n3wscott to code view selection.
```release-note
NONE
```
=> Adding myself to reviewers list.

test/crd.go
=> Fix spelling errors correctly

Gopkg.toml
We have a bunch of package overrides and constraints with no explanation for why they are pinned to particular revisions and versions. This makes it hard to know when an upgrade is safe. Comments and pointers to background issues are very helpful to future maintainers.
This PR adds explanations where I knew or could discover them and TODOs where I couldn't. It doesn't upgrade any dependencies or change any constraints/overrides, just adds comments on them.
=> Comment on each Gopkg constraint and override

config/500-controller.yaml, config/500-webhook.yaml, contrib/kafka/config/broker/kafka-broker.yaml, contrib/kafka/config/kafka.yaml, contrib/natss/config/broker/natss.yaml
* Replace repeated YAML lists with anchors and aliases.
- Forces `Deployment`s to match the labels that are generated.
```release-note
NONE
```
=> Replace repeated YAML lists with anchors and aliases.

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/release.sh
Addresses https://github.com/knative/test-infra/issues/433
=> Update test-infra to fix release script

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
- Update the test-infra package via dep ensure update
=> Update test infra dependency

contrib/kafka/pkg/dispatcher/dispatcher.go, contrib/kafka/pkg/dispatcher/dispatcher_test.go, contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go, contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go, pkg/provisioners/message.go, pkg/provisioners/message_dispatcher.go, pkg/provisioners/message_receiver.go, pkg/sidecar/fanout/fanout_handler.go
This is part of https://github.com/knative/serving/issues/3049.
I also cleaned up some tests, errors, message and linter errors, but this code definitely needs much more love and care.
But this is outside of the scope.
For https://github.com/knative/serving/issues/3049
/cc @Harwayne @vaikas-google
=> change the use of map[string]bool to use k8s string sets.

Gopkg.lock, contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go, contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go, pkg/provisioners/message.go, vendor/go.uber.org/zap/zaptest/observer/logged_entry.go, vendor/go.uber.org/zap/zaptest/observer/observer.go
Fixes #773 
```release-note
None
```
=> Adding header to the message being published

test/markdown-lint-config.rc
Fixes `mdl` fun :joy: 
See here: https://github.com/knative/test-infra/pull/416#issuecomment-457657074
@evankanderson @adrcunha
=> Customize markdown checks

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/scripts/release.sh
=> update dep for github.com/knative/test-infra along with fixes

test/README.md, test/e2e_flags.go, test/upload-test-images.sh
`DOCKER_REPO_OVERRIDE` replaced by `KO_DOCKER_REPO` in `test` folder
/cc @adrcunha
=> Replace DOCKER_REPO_OVERRIDE by KO_DOCKER_REPO in test folder

contrib/natss/config/broker/natss.yaml
- Add labels to the StatefulSet that were incorrectly removed in #768.
```release-note
NONE
```
=> Add labels to the stateful set.

OWNERS
(just rebased #808 )
Per [responsibilities and privileges](https://github.com/knative/docs/blob/master/community/ROLES.md#responsibilities-and-privileges-1) for approvers:
> Expected to be responsive to review requests as per community expectations
- * removes @scothis and @inlined as approvers
```release-note
```
=> remove inlined and scothis from reviewers and approvers

DEVELOPMENT.md
- Update invalid link for telemetry in DEVELEOPMENT.md.
```release-note
NONE
```
=> Update invalid docs link for telemetry

README.md
Fixes existing lint errors surfaced in #817 
- change list to conform to lint requirements
```release-note
```
=> fix lint problems

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/release.sh
=> Get the latest updates for automatic dot releases

pkg/reconciler/v1alpha1/channel/channel_test.go
- Increase unit test coverage of the Channel reconciler.
```release-note
NONE
```
=> Increase unit test coverage of the Channel reconciler

Gopkg.lock, test/cleanup.go, test/clients.go, test/crd.go, test/e2e/broker_trigger_test.go, test/e2e/e2e.go, test/e2e/single_event_test.go, test/e2e_flags.go
1. Delete some unused methods and flags
1. Use pkg/test methods wherever possible
1. Ran update-codegen that updated the lock file
=> Use common test components defined in pkg/test

contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go, pkg/reconciler/v1alpha1/broker/broker.go, pkg/reconciler/v1alpha1/broker/resources/filter.go, pkg/reconciler/v1alpha1/broker/resources/ingress.go, pkg/reconciler/v1alpha1/channel/channel.go, pkg/reconciler/v1alpha1/channel/channel_test.go, pkg/reconciler/v1alpha1/namespace/namespace.go, pkg/reconciler/v1alpha1/subscription/provider_test.go, pkg/reconciler/v1alpha1/subscription/subscription.go, pkg/reconciler/v1alpha1/subscription/subscription_test.go, pkg/reconciler/v1alpha1/trigger/trigger.go
- Remove a go vet issue. 
- Add comments to exported methods.
```release-note
NONE
```
=> Remove a go vet issue and add comments to exported methods.

pkg/reconciler/names/names.go, pkg/sidecar/configmap/filesystem/filesystem_watcher.go, pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go, pkg/sidecar/configmap/parse.go, pkg/sidecar/fanout/fanout_handler_test.go, pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go, pkg/sidecar/multichannelfanout/multi_channel_fanout_handler_test.go, pkg/sidecar/swappable/swappable.go, pkg/sidecar/swappable/swappable_test.go, pkg/utils/blocking_start.go, pkg/utils/resolve/subscriber.go
- Update comments and remove some test warnings.
```release-note
NONE
```
=> Update comments and remove some test warnings.

contrib/kafka/config/README.md, contrib/kafka/config/kafka.yaml, contrib/kafka/pkg/controller/util.go, contrib/kafka/pkg/controller/util_test.go
- This patch adds comment about consumer_mode in README and configmap.
```release-note
NONE
```
=> Document consumer_mode for kafka consumer mode

config/300-channel.yaml
- Add OpenAPI schema to Channels.
```release-note
NONE
```
=> Add OpenAPI schema to Channels.

config/300-subscription.yaml
- OpenAPI schema for Subscriptions.
```release-note
NONE
```
=> OpenAPI schema for Subscriptions.

config/300-broker.yaml
- Fix indentation of Broker schema YAML.
```release-note
NONE
```
=> Fix indentation of Broker schema YAML.

cmd/broker/ingress/main.go, pkg/broker/receiver.go
- Do not use the transport directly, use the client and you get defaulting.
```release-note
NONE.
```
/assign @Harwayne 
/cc @nachocano
=> Use the CloudEvent client to send.

pkg/apis/eventing/logkey/constants.go, pkg/apis/eventing/v1alpha1/channel_validation.go, pkg/apis/eventing/v1alpha1/subscription_validation.go, pkg/provisioners/channel_util_test.go, pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile_test.go, pkg/reconciler/v1alpha1/subscription/subscription.go, pkg/sidecar/configmap/filesystem/filesystem_watcher.go, pkg/sidecar/multichannelfanout/parse.go
Address multiple lint errors
- Internal refactor, no functionality change
```release-note
NONE
```
=> Address multiple lint errors.

config/200-controller-clusterrole.yaml, config/200-webhook-clusterrole.yaml
- Reformat the permission lists to make them easier to read.
```release-note
NONE
```
=> Reformat the permission lists to make them easier to read.

cmd/pong/main.go, cmd/sendevent/main.go, pkg/reconciler/v1alpha1/trigger/resources/virtual_service.go, pkg/reconciler/v1alpha1/trigger/trigger.go, pkg/reconciler/v1alpha1/trigger/trigger_test.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`
=> golang format tools

docs/broker/README.md
- Update Trigger docs to match #1045.
```release-note
NONE
```
=> Update Trigger docs to match #1045.

test/e2e/e2e.go
After we create a new namespace, the `kube-controller-manager` will create a `default` ServiceAccount in this namespace. If we create a `pod` before the `default` ServiceAccount is created, we will get an error. 
Details can be found through [this link](https://github.com/kubernetes/kubernetes/issues/66689).
This fix can help avoid the error shown in [testgrid](https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-eventing-continuous/1120711642976358400).
=> Reduce test flakiness by checking default ServiceAccount creation

config/200-webhook-clusterrole.yaml
follow up for #1086  - as requested by @n3wscott
=> keeping the original deployments as they were, just more on finalizers

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
https://github.com/knative/test-infra/pull/708
=> update test-infra: skip e2e tests for non-code changes

pkg/reconciler/trigger/trigger_test.go
Just run through the NewController unit test.
=> Unit test that NewController doesn't return nil

cmd/controller/main.go, cmd/sources-controller/main.go
[BUG] eventing controller and source-controller fall off main() on shutdown signal
=> Fix for https://github.com/knative/eventing/issues/1109

test/test_images/sendevent/main.go
- Fix typo (contining -> continuing).
```release-note
NONE
```
=> Fix typo (contining -> continuing).

pkg/apis/sources/v1alpha1/apiserver_lifecycle.go, pkg/apis/sources/v1alpha1/apiserver_types.go, pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go
- Set owner reference on apiserver receive adapter so that it gets deleted when the apiserver source is deleted.
=> set owner reference on apiserver receive adapter

config/300-apiserversource.yaml
=> add APIserver source spec description

pkg/apis/eventing/v1alpha1/trigger_types.go, pkg/reconciler/trigger/resources/subscription.go
Fixes https://github.com/knative/eventing/issues/1159
-
-
-
```release-note
```
=> Use kmeta.newControllerRef for Trigger

pkg/apis/eventing/v1alpha1/trigger_types_test.go
Following https://github.com/knative/eventing/pull/1173
-
-
-
```release-note
```
=> Add unit test to GetGroupVersionKind for Trigger

pkg/apis/eventing/v1alpha1/channel_types.go, pkg/apis/eventing/v1alpha1/channel_types_test.go, pkg/provisioners/channel_util.go
Follow up https://github.com/knative/eventing/issues/1159
-
-
-
```release-note
```
=> Use kmeta.NewControllerRef for Channel

pkg/apis/sources/v1alpha1/cron_job_types_test.go, pkg/reconciler/cronjobsource/resources/eventtype.go
Follow up https://github.com/knative/eventing/issues/1159
-
-
-
```release-note
```
=> Use kmeta.NewControllerRef for CronJobSource

pkg/apis/eventing/v1alpha1/broker_types.go, pkg/apis/eventing/v1alpha1/broker_types_test.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/resources/filter.go, pkg/reconciler/broker/resources/ingress.go
Follow up https://github.com/knative/eventing/issues/1159
-
-
-
```release-note
```
=> Use kmeta.NewControllerRef for Broker

pkg/apis/eventing/v1alpha1/broker_types.go, pkg/apis/eventing/v1alpha1/channel_types.go, pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go, pkg/apis/eventing/v1alpha1/trigger_types.go, pkg/apis/sources/v1alpha1/containersource_types.go, pkg/apis/sources/v1alpha1/cron_job_types.go
For the types miss `OwnerRefable` check, add them, for the types already have it, format them.
-
-
-
```release-note
```
=> Add and format OwnerRefable check

Gopkg.lock, Gopkg.toml, vendor/github.com/cloudevents/sdk-go/alias.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/jsoncodec.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_data.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_interface.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_reader.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01_reader.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02_reader.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03_reader.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v02.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v03.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/options.go, vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
- See [0.7.0](https://github.com/cloudevents/sdk-go/releases/tag/0.7.0) release notes.
```release-note
NONE
```
/assign @Harwayne
=> Update to CloudEvents Golang SDK 0.7.0

pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go
- Fix unit tests.
```release-note
NONE
```
=> Fix unit tests.

Gopkg.lock, Gopkg.toml, pkg/reconciler/inmemorychannel/inmemorychannel.go, pkg/reconciler/inmemorychannel/inmemorychannel_test.go, vendor/github.com/knative/pkg/controller/controller.go
- use controller.FilterWithNameAndNamespace which got hoisted there.
=> bump pkg & use FilterWithNameAndNamespace from pkg

Gopkg.lock, pkg/apis/eventing/register.go, pkg/apis/eventing/v1alpha1/broker_defaults.go, pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go, pkg/apis/eventing/v1alpha1/channel_defaults.go, pkg/apis/eventing/v1alpha1/channel_lifecycle_test.go, pkg/apis/eventing/v1alpha1/subscription_defaults.go, pkg/apis/eventing/v1alpha1/subscription_lifecycle_test.go, pkg/apis/eventing/v1alpha1/trigger_defaults.go, pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
Fixes https://github.com/knative/eventing/issues/1063
=> Add user info annotations to Broker/Trigger/Channel/Subscription

Gopkg.lock, Gopkg.toml, vendor/github.com/knative/pkg/configmap/informed_watcher.go, vendor/github.com/knative/pkg/configmap/manual_watcher.go, vendor/github.com/knative/pkg/configmap/store.go, vendor/github.com/knative/pkg/configmap/watcher.go, vendor/github.com/knative/pkg/controller/controller.go, vendor/github.com/knative/pkg/logging/logkey/constants.go
Helps with #704.
- Upgrade knative/pkg dependency.
```release-note
NONE
```
=> Update knative/pkg dependency.

config/provisioners/in-memory-channel/README.md
adding note on the provisioners doc, for usage of the CRD instead
=> Adding note for usage of CRD instead

Gopkg.lock, vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-and-episodic-pr-contributors.json, vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-contributors-table.json, vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-companies-histogram.json, vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-histogram.json, vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors.json, vendor/github.com/knative/test-infra/devstats/metrics/shared/episodic_contributors.sql, vendor/github.com/knative/test-infra/devstats/metrics/shared/hist_pr_authors.sql, vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors.sql, vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors_data.sql, vendor/github.com/knative/test-infra/devstats/metrics/shared/prs_authors.sql, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh
Fixes #https://github.com/knative/test-infra/issues/829
- update test-infra
```release-note
NONE
```
=> update test-infra in vendor

OWNERS_ALIASES, hack/OWNERS, test/OWNERS
Part of knative/test-infra#579
=> Use OWNERS_ALIASES for productivity approvers/reviewers

cmd/broker/filter/main.go, cmd/broker/ingress/main.go, cmd/controller/main.go, cmd/in_memory_channel_controller/main.go, contrib/gcppubsub/pkg/controller/cmd/main.go
Fixes #1291
Replace getRequiredEnv with envconfig.
=> Use envconfig instead of getRequiredEnv

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh
Part of https://github.com/knative/test-infra/issues/844
Fixing the forbidden images in the nightly release. 
```release-note
NONE
```
=> Update test-infra to the latest version

docs/spec/spec.md
change `TriggerFilterSourceAndTpe` to `TriggerFilterSourceAndType` in spec.md
=> Fix typo in spec.md

config/500-controller.yaml, config/500-webhook.yaml
- Disabled sidecar injection for eventing-controller.
=> Add resource requests and disabled istio sidecar

cmd/in_memory/channel_dispatcher/main.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel.go, pkg/reconciler/reconciler.go, pkg/reconciler/stats_reporter.go
Helps with #1215
- Adding back tracing to inmemory channel dispatcher.  
- Adding stats as well
```release-note
NONE
```
=> InMemoryChannel tracing

cmd/controller/main.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/controller.go
Helps with #1383 
- Watch created channels using a Tracker and reconcile Broker once they change.
```release-note
```
=> track ingress/trigger channels

test/config/100-strimzi-cluster-operator-0.11.4.yaml, test/e2e-tests.sh
latest version, @Fredy-Z @adrcunha
=> Strimzi version update

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/README.md, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/tools/dep-collector/README.md
Produced via:
`dep ensure -update github.com/knative/test-infra`
/assign @adrcunha
=> Update github.com/knative/test-infra dependency

Gopkg.lock, vendor/github.com/knative/pkg/Gopkg.lock, vendor/github.com/knative/pkg/kmeta/names.go, vendor/github.com/knative/pkg/test/helpers/name.go, vendor/github.com/knative/pkg/test/logstream/doc.go, vendor/github.com/knative/pkg/test/logstream/interface.go, vendor/github.com/knative/pkg/test/logstream/kubelogs.go, vendor/github.com/knative/pkg/test/logstream/null.go, vendor/github.com/knative/pkg/test/request.go
- Prepping for 0.7 release. Update knative/pkg to latest.
```release-note
NONE
```
=> Updating pkg to latest for 0.7 release.

Gopkg.lock, vendor/github.com/knative/test-infra/scripts/e2e-tests.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/shared/gcs/gcs.go
Produced via:
`dep ensure -update github.com/knative/test-infra github.com/knative/pkg`
=> Auto-update dependencies

Gopkg.lock, hack/update-deps.sh, vendor/github.com/knative/test-infra/scripts/library.sh, vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh, vendor/github.com/knative/test-infra/shared/testgrid/yaml.go
=> Remove /devstats hack from update-deps.sh

Gopkg.lock, test/base/resources/kube.go, test/test_images/latency/helpers_test.go, test/test_images/latency/main.go
The current test result shown on [testgrid](https://testgrid.knative.dev/eventing#performance) clearly has some error. This PR fixed a couple of remaining issues in the [previous PR](https://github.com/knative/eventing/pull/1411), and made the wait time longer before sending events, which might also be one cause for the test error.
I have tried running it a couple of times on my own cluster, and the results looked correct.
```release-note
NONE
```
/cc @grantr
=> Fix a couple of perf test issues

cmd/broker/ingress/main.go, pkg/broker/receiver_test.go, pkg/broker/ttl.go
- Make the TTL attribute private.
- Follow up from https://github.com/knative/eventing/pull/1466#discussion_r297291997
```release-note
NONE
```
=> Make the TTL attribute private.

Gopkg.lock, vendor/github.com/knative/test-infra/shared/gcs/gcs.go
Redo of #1465. Updates knative/test-infra to latest.
=> Manual-update dependencies

config/300-apiserversource.yaml, config/300-containersource.yaml, config/300-cronjobsource.yaml
- adding an `importer` category to make those "importers" easier to find, by category
=> Adding importer category

cmd/cronjob_receive_adapter/main.go
=> fix tracing service name

config/200-controller-clusterrole.yaml
patching 0.7 branch w/ fix from #1495 
/cc @vaikas-google
=> applying finalizer subresource for 0.7.x patch

docs/spec/channel.md
=> fix indentation

pkg/apis/messaging/v1alpha1/register.go
=> fix SequenceList registration

pkg/reconciler/sequence/resources/channel.go
- Named field initialization.
```release-note
NONE
```
=> Named field initialization.

test/base/resource_getters.go
Fixes #1558 
- don't use the TypedInformerFactory just for getting/listing objects
- list/get objects in the namespace scope, not the cluster scope
NONE
=> fixes #1558 list/get resources in namespace scope only

pkg/apis/eventing/v1alpha1/test_helper.go, pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go, pkg/reconciler/trigger/trigger_test.go
- Increase code coverage of trigger_lifecycle.go.
Found because #1563 started failing due to low coverage of this file.
```release-note
NONE
```
=> Increase code coverage of trigger_lifecycle.go.

pkg/broker/ttl.go
Fixes #1471 
- Change one 0.2 -> 0.3 that was pointed out in #1535 pr.
-
-
```release-note
```
=> followup to 1535

pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/controller.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/channel/channel_test.go, pkg/reconciler/sequence/sequence_test.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/mock_resource_tracker.go, pkg/reconciler/trigger/trigger_test.go
- ApiServerSource tracks its receive adapter.
```release-note
NONE
```
=> ApiServerSource tracks its receive adapter.

pkg/apis/messaging/v1alpha1/choice_types.go
- Better choice.spec.channelTemplate API documentation
=> fix Choice ChannelTemplate doc

config/200-addressable-resolvers-clusterrole.yaml, config/channels/in-memory-channel/200-addressable-resolver-clusterrole.yaml
- Add InMemoryChannel and Channel.messaging,knative.dev to the addressable-resolver ClusterRole.
```release-note
NONE
```
=> Add InMemoryChannel and Channel.messaging,knative.dev to the addressable-resolver ClusterRole.

config/200-addressable-resolvers-clusterrole.yaml
- add sequence and choice in the addressable resolver
=> add sequences and choices in the list of addressable

pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
- Use CreateChannelServiceName, rather than the same format string in two places.
```release-note
NONE
```
=> Use CreateChannelServiceName, rather than the same format string in two places.

pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/containersource/containersource.go, pkg/reconciler/containersource/containersource_test.go
- Small changes to fix warnings in ContainerSource.
```release-note
NONE
```
=> Small changes to fix warnings in ContainerSource.

Gopkg.toml
=> Clarify override comments

cmd/broker/ingress/main.go, pkg/broker/ingress/ingress_handler.go, pkg/broker/ingress/ingress_handler_test.go, pkg/broker/ingress/metrics.go
Fixes #897 
-Move Broker's Ingress Handler and metrics to pkg
```release-note
Still working on the unit test, WIP
```
=> move broker's ingress handler and metrics to pkg

Gopkg.lock, test/README.md, test/common/test_runner.go, test/upload-test-images.sh, vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
- Allow running e2e test on existing oidc clusters
=> enable running e2e test on oidc clusters and dockerhub

docs/spec/channel.md
- Channel spec updates.
```release-note
NONE
```
=> Channel spec updates.

pkg/reconciler/trigger/trigger.go
- Tracking broker changes before retrieving it in the Trigger reconciler. Previously, if the broker was deleted, the Trigger wasn't able to properly reconcile the broker status when it was recreated.
```release-note
NONE
```
=> Fixing Trigger reconciler upon Broker changes

pkg/channel/message_receiver.go
- adding back function that has been accidentally in PR #1717 
/assign @Harwayne
=> Adding back function that is actually used by Natss/Kafka channels

Gopkg.lock, cmd/webhook/main.go, vendor/knative.dev/pkg/webhook/resource_admission_controller.go, vendor/knative.dev/pkg/webhook/webhook.go
/lint
/hold while reviewing knative/pkg#622
use the new AdmissionController interface to add webhooks.
=> use the amdission controller interface for webhook

test/test_images/sendevents/main.go
Fixes https://github.com/knative/eventing/issues/1807
=> Add check for event extensions sending

cmd/apiserver_receive_adapter/main.go
Fixes #
- Remove spaces
```release-note
NONE
```
=> Remove spaces

pkg/broker/filter/filter_handler.go
- Do not trace readiness requests.
```release-note
NONE
```
=> Do not trace readiness requests.

test/performance/tools/common.sh
This is failing the update-scripts - https://prow.knative.dev/log?job=ci-knative-eventing-update-clusters&id=1171515149010341888
=> Use the correct path to install in-memory-channel

Gopkg.lock, cmd/webhook/main.go, vendor/knative.dev/pkg/Gopkg.lock, vendor/knative.dev/pkg/controller/controller.go, vendor/knative.dev/pkg/controller/stats_reporter.go, vendor/knative.dev/pkg/logging/config.go, vendor/knative.dev/pkg/metrics/config.go, vendor/knative.dev/pkg/metrics/metricskey/constants.go, vendor/knative.dev/pkg/metrics/source_stats_reporter.go, vendor/knative.dev/pkg/metrics/utils.go, vendor/knative.dev/pkg/webhook/resource_admission_controller.go, vendor/knative.dev/pkg/webhook/stats_reporter.go, vendor/knative.dev/pkg/webhook/webhook.go
/lint
/hold
while reviewing https://github.com/knative/pkg/pull/653 
this is to fix the breaking change in the PR above to  https://github.com/knative/pkg
=> rename the variable for resource validation webhook

test/common/cloudevents_vegeta_targeter.go, test/test_images/latencymako/sender_receiver.go
* Modified attack code to run GC between paces
* Removed upper bound to workers
* Targeter no longer uses CE Sdk to encode messages
\assign antoineco
=> Latencymako test image fixes

Gopkg.lock, Gopkg.toml, vendor/knative.dev/pkg/apis/field_error.go, vendor/knative.dev/pkg/source/source_stats_reporter.go, vendor/knative.dev/pkg/test/spoof/spoof.go, vendor/knative.dev/pkg/test/webhook-apicoverage/view/README.md, vendor/knative.dev/pkg/test/zipkin/util.go, vendor/knative.dev/pkg/testutils/clustermanager/boskos/boskos.go, vendor/knative.dev/pkg/testutils/clustermanager/boskos/fake/fake.go, vendor/knative.dev/pkg/testutils/clustermanager/gke.go, vendor/knative.dev/pkg/tracing/opencensus.go
- Prepping for 0.9 release. Update knative.dev/pkg to latest from branch release-0.9.
```release-note
NONE
```
/cc @mattmoor
=> Updating pkg to latest for 0.9 release.

test/test_images/eventdetails/pod.yaml, test/test_images/filterevents/pod.yaml, test/test_images/heartbeats/pod.yaml, test/test_images/helloworld/pod.yaml, test/test_images/latency/pod.yaml, test/test_images/latencymako/pod.yaml, test/test_images/logevents/kodata/pod.yaml, test/test_images/logevents/pod.yaml, test/test_images/sendevents/pod.yaml, test/test_images/sequencestepper/pod.yaml, test/test_images/transformevents/pod.yaml, test/upload-test-images.sh
- Upload all the test images in parallel.
```release-note
NONE
```
=> Upload all the test images in parallel.

pkg/reconciler/cronjobsource/resources/receive_adapter.go
Fixes #1923
- Fix CronJobSource deployment resource requirements configuration
=> Properly configure the CronJobSource deployment resource requirements

pkg/reconciler/apiserversource/controller_test.go, pkg/reconciler/broker/controller_test.go, pkg/reconciler/channel/controller_test.go, pkg/reconciler/containersource/controller_test.go, pkg/reconciler/eventtype/controller_test.go, pkg/reconciler/inmemorychannel/controller/controller_test.go, pkg/reconciler/namespace/controller_test.go, pkg/reconciler/parallel/controller_test.go, pkg/reconciler/sequence/controller_test.go, pkg/reconciler/subscription/controller_test.go, pkg/reconciler/testing/factory.go, pkg/reconciler/trigger/controller_test.go
- replace deprecated method with the newer `NewStaticWatcher`
=> Remove deprecated NewFixedWatcher

test/test_images/performance/aggregator.go, test/test_images/performance/main.go
=> Make  broker-imc perf test accept additional tags

test/conformance/README.md
- adding a note on building images.....
=> adding note on building images

pkg/reconciler/sequence/sequence.go, pkg/reconciler/sequence/sequence_test.go
Fixes #1950
- Reconcile subscription when sequence is updated
```release-note
NONE
```
=> Update subscription upon sequence update

hack/set-span-id.patch, pkg/tracing/traceparent_test.go, vendor/go.opencensus.io/trace/trace.go
Fixes #1986
- nil check in SetSpanID
```release-note
NONE
```
=> nil check in SetSpanID

test/test_images/performance/dev.config
- Adding nacho to mako dev.config
```release-note
NONE
```
=> Mako dev.config update

pkg/reconciler/parallel/parallel.go, pkg/reconciler/parallel/parallel_test.go
Helps #2002
- redeploy subscription created by Parallel when its spec changes
=> redeploy subscription if spec changes

test/base/resources/kube.go, test/common/creation.go, test/e2e/source_api_server_test.go
in TestApiServerSource
Fixes #1996
- add kind parameter to test/base/resource RoleBinding to allow binding to Roles (not just ClusterRoles)
- don't create ClusterRole in TestApiServerSource (use just Role in the test namespace)
NONE
=> fixes #1996 , use Role in the test namespace instead of ClusterRole

pkg/apis/eventing/v1alpha1/broker_validation.go, pkg/apis/eventing/v1alpha1/broker_validation_test.go
Fixes #1707
Make broker's channelTemplate immutable.
=> Make broker.spec.channelTempalte immutable

config/200-addressable-resolvers-clusterrole.yaml
/assign @Harwayne 
we do not have channels anymore in the `eventing` apiGroup
=> we have only channels in messaging.knative.dev

OWNERS
From [ROLES.md](https://github.com/knative/community/blob/master/ROLES.md#approver)
> Reviewer of the codebase for at least 3 months.
First review: October 2018 
* https://github.com/knative/eventing/pull/482
47 PRs:
https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+-author%3Amatzew+reviewed-by%3Amatzew+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM
Examples:
* https://github.com/knative/eventing/pull/1949
* https://github.com/knative/eventing/pull/1933
* https://github.com/knative/eventing/pull/1864
* https://github.com/knative/eventing/pull/1695
* https://github.com/knative/eventing/pull/1490
* https://github.com/knative/eventing/pull/1359
* https://github.com/knative/eventing/pull/1316
* …
=> Adding matzew to approvers

DEVELOPMENT.md
- use real contribution guide references to `knative.dev` website
- add a section on `KO_DOCKER_REPO` setup, for pushing images to developer accounts w/ `ko`
=> updating development guide

DEVELOPMENT.md
- adding notes on `ko` and how it can actually push images, by requiring an auth against a container registry
=> adding notes that for KO u need to auth against a container registry

pkg/apis/sources/v1alpha1/cron_job_lifecycle.go, pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/controller.go, pkg/reconciler/apiserversource/controller_test.go, pkg/reconciler/cronjobsource/controller.go, pkg/reconciler/cronjobsource/cronjobsource.go, pkg/reconciler/cronjobsource/cronjobsource_test.go
Helping #2019
- Make CronJobSource and ApiServerSource controllers more consistent
=> make cronjobsource and apiserversource controllers more consistent

cmd/webhook/main.go
- we should not use the `log` package here, and code blocks befre/after use the `logger`
```release-note
```
=> minor update to logger obj

cmd/broker/filter/main.go, cmd/broker/ingress/main.go
Fixes #
- aliging code w/ other `main`s and clean up 
```release-note
```
=> cleaning up broker code and align w/ other components

Gopkg.lock, pkg/apis/duck/v1alpha1/channelable_types.go, pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go, pkg/apis/eventing/v1alpha1/broker_types.go, pkg/apis/eventing/v1alpha1/eventtype_lifecycle_test.go, pkg/apis/eventing/v1alpha1/eventtype_types.go, pkg/apis/eventing/v1alpha1/test_helper.go, pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go, pkg/apis/eventing/v1alpha1/trigger_types.go, pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go, pkg/apis/messaging/v1alpha1/channel_types.go, pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle_test.go, pkg/apis/messaging/v1alpha1/in_memory_channel_types.go, pkg/apis/messaging/v1alpha1/parallel_lifecycle_test.go, pkg/apis/messaging/v1alpha1/parallel_types.go, pkg/apis/messaging/v1alpha1/sequence_lifecycle_test.go, pkg/apis/messaging/v1alpha1/sequence_types.go, pkg/apis/messaging/v1alpha1/subscription_lifecycle_test.go, pkg/apis/messaging/v1alpha1/subscription_types.go, pkg/apis/sources/v1alpha1/apiserver_types.go, pkg/apis/sources/v1alpha1/containersource_types.go, pkg/apis/sources/v1alpha1/cron_job_types.go
Fixes #
- Change all the duckv1beta1.Status to duckv1.Status
- No user visible changes as they are json compatible
```release-note
NONE
```
=> duckv1beta1.Status -> duckv1.Status

config/300-apiserversource.yaml, config/300-cronjobsource.yaml
Fixes #2113
- add ready and age columns
=> add ready and age columns

docs/spec/interfaces.md
=> chore(spec): Clarify that a a Callable returns 0 or 1 event

OWNERS
=> Add vaikas to OWNERS via new account

test/performance/benchmarks/broker-imc/dev.config, test/performance/benchmarks/channel-imc/dev.config
=> Whitelist cshou for running perf tests

test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml, test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml
Change pace for imc-channel and imc-broker performance testing: at most 1500 and 1200.
Example:
https://mako.dev/run?run_key=6735381902917632&~pl=1&~pe=1&~st=1&~dl=1&~de=1&~dt=1&~ft=1
https://mako.dev/run?run_key=6220963435773952&~pl=1&~pe=1&~st=1&~dl=1&~de=1&~dt=1&~ft=1
```release-note
NONE
```
/cc @grantr
=> Change pace for performance testing

Gopkg.lock, vendor/knative.dev/test-infra/scripts/e2e-tests.sh, vendor/knative.dev/test-infra/scripts/performance-tests.sh
There is a bug making e2e tests blindly retry 3 times on any test error, this change introduces fix for it
=> update test-infra with fix for retry on any e2e test failures

config/channels/in-memory-channel/README.md
- Better documentation
- Remove `should not be used in production` since there are usecases where persistence, and ordering is not needed.
=> add dead letter sink doc

Gopkg.lock, pkg/adapter/main.go
Fixes #2148, depends on https://github.com/knative/pkg/pull/852
=> Added profiling to Adapter.Main

Gopkg.lock, cmd/broker/filter/main.go, cmd/broker/ingress/main.go, docs/metrics.md, pkg/broker/filter/filter_handler.go, pkg/broker/filter/stats_reporter.go, pkg/broker/filter/stats_reporter_test.go, pkg/broker/ingress/ingress_handler.go, pkg/broker/ingress/stats_reporter.go, pkg/broker/ingress/stats_reporter_test.go, pkg/broker/metrics.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/resources/filter.go, pkg/reconciler/broker/resources/ingress.go, vendor/knative.dev/pkg/metrics/metricskey/constants_eventing.go, vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
- Original PR in master #2145
```release-note
NONE
```
=> Backport Broker/Trigger StackDriver internal metrics for 0.10

pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
Followup to #2162 review.
- Fix variable name for consistency.
```release-note
NONE
```
=> fix a nit variable naming

pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
- cherry-pick pr2166(https://github.com/knative/eventing/pull/2166)
-
-
```release-note
```
=> fix a nit variable naming 

test/base/resources/eventing.go, test/e2e/channel_dls_test.go, test/e2e/helpers/channel_dls_test_helper.go
- add e2e deadlettersink test
-
-
```release-note
```
=> add e2e deadlettersink test

Gopkg.lock, test/common/performance/aggregator/aggregator.go, test/common/performance/image_helpers.go, test/performance/README.md, test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml, test/performance/benchmarks/broker-imc/dev.config, test/performance/benchmarks/broker-imc/prod.config, test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml, test/performance/benchmarks/channel-imc/dev.config, test/performance/benchmarks/channel-imc/prod.config, test/performance/config/config-mako.yaml, test/performance/performance-tests.sh, vendor/knative.dev/pkg/test/mako/config/benchmark.go, vendor/knative.dev/pkg/test/mako/sidecar.go, vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go, vendor/knative.dev/pkg/test/mako/stub-sidecar/read_results.sh
Update performance tests code to use the latest change in pkg, and also organize the current file structures a bit.
```release-note
NONE
```
/cc @grantr
=> Update performance tests code to use the latest change in pkg

OWNERS_ALIASES
Fixes #
- remove outdated alias for channels
```release-note
```
=> Remove channel owners, since channel live in contrib

test/common/performance/aggregator/aggregator.go, test/common/performance/sender/sender.go
- Add more info to the error logs for performance tests, as described in https://github.com/knative/eventing/pull/2226#pullrequestreview-323854819
```release-note
NONE
```
/cc @grantr
=> Add more info to the error logs for performance tests

test/base/resource_inspectors.go, test/base/resources/kube.go, test/common/client.go, test/common/creation.go, test/common/operation.go, test/common/performance/aggregator/aggregator.go, test/common/performance/image_helpers.go, test/e2e/helpers/performance_image_test_helper.go, test/test_images/performance/pod.yaml
Required to solve https://github.com/knative/eventing-contrib/issues/272
=> Add utilities for E2E testing with Performance image

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go
Backport of #2160 to release-0.10.
=> Backport #2160

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/broker/ingress/ingress_handler.go, pkg/broker/ttl.go
Backport #2244 to release-0.10 branch.
=> Backport ttl fix to release-0.10

docs/spec/spec.md
Fixes #2276 
- Update spec to match code / docs.
```release-note
NONE
```
=> Fix trigger spec

pkg/broker/filter/filter_handler_test.go, pkg/broker/ingress/ingress_handler_test.go
Fixes #
- more CE 1.0, now on tests inside the broker
```release-note
```
=> Broker tests w/ CE 1.0

AUTHORS
- VMware now contributes to Knative Eventing.
```release-note
NONE
```
=> Adding VMware to AUTHORS.

docs/spec/channel.md
Fixes #
-
-
-
```release-note
```
=> Spec was finalized before

docs/spec/spec.md
Fixes #
- remove provisioner, we have only Channels
-
-
```release-note
```
=> Fixing typo in the spec, for broker, as we no longer have CCPs

config/300-parallel.yaml, config/300-sequence.yaml, config/300-subscription.yaml
Addresses #2298 
- Update the CRD open api.
```release-note
* Remove unused fields from the CRD files.
```
=> remove now unused fields from crds

OWNERS
From [ROLES.md](https://github.com/knative/community/blob/master/ROLES.md#approver)
> Reviewer of the codebase for at least 3 months.
First review: May 2019
- https://github.com/knative/eventing/pull/1108
26 PRs:
https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+-author%3Alionelvillard+commenter%3Alionelvillard+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM+
Examples:
- https://github.com/knative/eventing/pull/1175
- https://github.com/knative/eventing/pull/1239
- https://github.com/knative/eventing/pull/1420
- https://github.com/knative/eventing/pull/1560
- https://github.com/knative/eventing/pull/1576
- https://github.com/knative/eventing/pull/2027
- …
=> adding lionelvillard to approvers

pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go
- Add more unit tests to increase test coverage.
```release-note
NONE
```
=> add more coverage

OWNERS_ALIASES
From [ROLES.md](https://github.com/knative/community/blob/master/ROLES.md#approver)
> Reviewer of the codebase for at least 3 months.
First review: April 2019
* #976 
28 PRs:
https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+-author%3Alionelvillard+commenter%3Alionelvillard+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM+
> Merged at least 30 PRs to the codebase.
62 PRs:
https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Achizhg+is%3Amerged
> Nominated by an area lead with no objections from other leads
/cc @adrcunha 
/cc @grantr 
/cc @nachocano
=> Add chizhg to eventing productivity approvers

cmd/sources_controller/main.go, cmd/webhook/main.go, pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/cfg_host.go, pkg/reconciler/apiserversource/controller.go, pkg/reconciler/apiserversource/controller_test.go, pkg/reconciler/apiserversource/doc.go, pkg/reconciler/apiserversource/resources/eventtype.go, pkg/reconciler/apiserversource/resources/labels.go, pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go, pkg/reconciler/testing/legacyapiserversource.go, pkg/reconciler/testing/listers.go, test/base/resources/constants.go, test/common/creation.go, test/common/typemeta.go, test/e2e/legacy_source_api_server_test.go
Related to #1500
- Add in a controller for the new ApiServerSource under sources.knative.dev
```release-note
New resource added: ApiServerSource under sources.knative.dev
```
=> Adding ApiServerSource.sources.knative.dev

cmd/webhook/main.go, config/200-webhook-clusterrole.yaml, config/500-webhook-configuration.yaml, pkg/reconciler/legacyapiserversource/controller.go, pkg/reconciler/sinkbinding/controller.go, pkg/reconciler/testing/containersource.go, test/common/creation.go, test/e2e/legacysinkbinding_test.go
Related to #1500
- Add in a controller for the new SinkBinding under sources.knative.dev
```release-note
New resource added: SinkBinding under sources.knative.dev
```
=> Add SinkBinding to sources.knative.dev

test/performance/README.md
=> Fixed the performance README.md

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go
Fixes #2398
- Currently the filter handler discards HTTP error status codes that may be returned when delivering an event to a trigger sink. This changes passes that status codes back to the CloudEvents SDK for further propagation.
```release-note
NONE
```
=> Propagate status codes when returned on a filter sendEvent

config/300-broker.yaml, config/300-channel.yaml, config/300-eventtype.yaml, config/300-subscription.yaml, config/300-trigger.yaml
=> Add more descriptions to openapi spec fields

pkg/channel/event_receiver.go, pkg/channel/event_receiver_test.go
=> Update the signature of ResolveChannelFromHostFunc to take in a URL instead of a string.

hack/release.sh
Add a release yaml that installs the eventing CRDs.
=> Add a release yaml for the eventing CRDs

test/performance/benchmarks/broker-imc/100-broker-perf-setup.yaml, test/performance/benchmarks/broker-imc/continuous/100-broker-imc-setup.yaml
- Change `configmappropagation` api group name in perf test.
-
-
```release-note
```
=> Change api group name in perf test

.github/pull-request-template.md
- currrent --> current
- behaviour -> behavior
- adding missing `-->`
=> Fix spelling and close the comment bracket for new PR template.

docs/spec/sources.md
Related to https://github.com/knative/eventing/pull/2481
- Document the augmentation of the container runtime contract from SinkBinding.
```release-note
NONE
```
=> document the sink binding runtime contract.

test/e2e/configmappropagation_default_test.go, test/lib/creation.go, test/lib/operation.go, test/lib/resources/eventing.go, test/lib/validation.go
Fixes #2399
- E2E test for ConfigMapPropagation
-
-
```release-note
```
=> E2E test for ConfigMapPropagation

README.md
=> Make the release number and slack show in README.

Gopkg.lock, vendor/knative.dev/pkg/Gopkg.lock, vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go, vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go, vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go, vendor/knative.dev/pkg/test/mako/sidecar.go, vendor/knative.dev/test-infra/scripts/README.md, vendor/knative.dev/test-infra/scripts/release.sh
Produced via:
`dep ensure -update knative.dev/test-infra knative.dev/pkg`
=> Update test-infra,pkg to latest

config/core/configmaps/observability.yaml, test/performance/README.md
- Add documentation on how to enable profiling.
```release-note
NONE
```
cc @grantr
=> Add documentation on how to enable profiling.

Gopkg.lock, pkg/apis/duck/v1alpha1/delivery_conversion.go, pkg/apis/duck/v1alpha1/delivery_conversion_test.go, pkg/apis/duck/v1beta1/delivery_conversion.go, pkg/apis/duck/v1beta1/delivery_conversion_test.go
- Implement conversion for delivery ducks.
```release-note
NONE
```
=> Adding delivery spec and status conversion methods.

OWNERS
- Add @liu-cong to reviewer list. I'd like to get PRs assigned to me and contribute to reviewing them!
```release-note
NONE
```
cc @grantr
=> Add liu-cong to reviewer list.

OWNERS
=> Add yolocs (cshou) to the reviewers

pkg/reconciler/subscription/subscription_test.go
follow up from https://github.com/knative/eventing/pull/2543#pullrequestreview-357583547
/assign @n3wscott 
/assign @yolocs
=> Remove commented out test code

docs/delivery/README.md
Fixes #
- updating spec types, to match code
=> Updating DeliverySpec/Status to latest types

docs/delivery/README.md
- adding ref. to Source/Channel delivery / data plane aspects
/assign @lionelvillard 
/assign @aslom 
=> Adding references on Source/Channel delivery

pkg/apis/flows/v1beta1/parallel_types_test.go, pkg/apis/sources/v1alpha1/apiserver_types_test.go, pkg/apis/sources/v1alpha1/ping_types_test.go, pkg/apis/sources/v1alpha1/sinkbinding_types_test.go
Fixes #
- adding missing types_test files
=> Adding types tests

pkg/reconciler/broker/trigger.go
Fixes #2575 
- Set up the tracker to reconcile broker instead of trigger when dependency changes.
```release-note
- 🐛 Fix bug #2575
```
=> reconcile broker instead of trigger when dep changes

OWNERS
Add @aslom to reviewer list. I'd like to get PRs assigned to me and contribute to reviewing them! Together we do more - let spread the load.
Fixes #
-
-
-
```release-note
```
=> add Alek (aslom) to list of reviewers

pkg/apis/eventing/register.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/resources/filter.go, pkg/reconciler/broker/resources/ingress.go, pkg/reconciler/broker/resources/subscription.go, pkg/reconciler/broker/resources/subscription_test.go
Follow up to #2585 PR comments.
- use consts for the label / annotations used to indicate broker and broker class.
```release-note
```
=> follow up to 2585. introduce a const for broker label/class

docs/spec/sources.md
Fixes #
- instead of alpha1, let's use duckV1 ? 
=> Using duckv1 for Destination API

cmd/webhook/main.go, config/core/resources/channel.yaml, pkg/apis/duck/v1alpha1/subscribable_types.go, pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go, pkg/apis/messaging/register.go, pkg/apis/messaging/v1alpha1/channel_conversion.go, pkg/apis/messaging/v1alpha1/channel_conversion_test.go, pkg/apis/messaging/v1alpha1/channel_types.go, pkg/apis/messaging/v1alpha1/subscription_conversion_test.go, pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go, pkg/apis/messaging/v1beta1/channel_conversion.go, pkg/apis/messaging/v1beta1/channel_conversion_test.go, test/e2e-tests.sh, test/e2e/helpers/channel_defaulter_test_helper.go, test/lib/config.go
- Add support for v1alpha1<->v1beta1 for channels
-
-
```release-note
* Add support for Channel v1alpha1<->v1beta1
```
=> Add v1alpha<->v1beta1 for channels

CONTRIBUTING.md
Ref https://github.com/knative/eventing/issues/2603
Fixes #
-
-
-
```release-note
```
=> Contribution guidelines for user facing PRs

DEVELOPMENT.md
Added to avoid missing contribution that is only mentioned in "Getting started".
Fixes #2603
-
-
-
```release-note
```
=> Added link to contribution guidelines after tests

README.md
- Use an image badge for godoc ref.
```release-note
NONE
```
=> use go.dev image from sheilds.io

cmd/webhook/main.go, config/channels/in-memory-channel/300-in-memory-channel.yaml, pkg/apis/messaging/register.go, pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go, pkg/apis/messaging/v1alpha1/in_memory_channel_conversion_test.go, pkg/apis/messaging/v1alpha1/in_memory_channel_types.go, pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go, pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go, pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go
- Introduce v1beta1 <-> v1alpha1 conversions for InMemoryChannel
-
-
```release-note
Add support for InMemoryChannel v1beta1.
```
**Docs**
=> imc v1alpha1 <=> v1beta1

cmd/webhook/main.go
- add v1beta1 types for eventing, flows, messaging so we get the right defaults (v1beta1, not v1alpha1)
-
-
```release-note
```
**Docs**
=> add our types for v1beta1 so we get defaults

config/core/resources/pingsource.yaml, pkg/reconciler/pingsource/pingsource_test.go, pkg/reconciler/testing/pingsource.go, test/e2e/source_ping_test.go, test/e2e/trigger_dependency_annotation_test.go, test/lib/creation.go
Fixes https://github.com/knative/eventing/issues/2647
- Adding e2e test for pingsource pushed at v1alpha2
```release-note
- 🎁PingSource sources.knative.dev/v1alpha2 is now served.
```
Docs tracker: knative/docs#2247
=> E2e tests pingsource v1a2

pkg/reconciler/subscription/subscription.go
- apply patch on v1alpha1 resource.
-
-
```release-note
```
**Docs**
=> add support for referencing v1beta1 channels in subscription

config/core/resources/eventtype.yaml
- Drop schema of handrolled EventType schema.
```release-note
NONE
```
**Docs**
=> EventType reconciler was unable to make a status at v1alpha1

docs/spec/channel.md
Fixes #2689 
- Add documentation about v1beta1 changes and requirements.
```release-note
- 🎁 Add new feature Document v1beta1 channel requirements.
```
**Docs**
=> Update channel.md (spec) for v1beta specific details

test/e2e/trigger_dependency_annotation_test.go, test/lib/resources/eventing.go
Fixes #
- fixes typo (`Annotaion`)
- goes with V1Beta1 trigger
- adds new `WithDependencyAnnotationTriggerV1Beta1` func
```release-note
```
**Docs**
=> Updates to test without filter

config/brokers/channel-broker/deployments/controller.yaml, config/channels/in-memory-channel/500-controller.yaml, config/channels/in-memory-channel/500-dispatcher.yaml, config/core/deployments/controller.yaml, config/core/deployments/webhook.yaml, hack/release.sh, test/e2e-common.sh
- 🧽 Adopt ko's strict mode for a better on-boarding experience
=> Use ko's strict mode for better errors messages

test/performance/benchmarks/broker-imc/200-broker-perf.yaml, test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml, test/performance/benchmarks/channel-imc/200-channel-perf.yaml, test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml, test/performance/direct/200-direct-perf.yaml, test/test_images/eventdetails/pod.yaml, test/test_images/filterevents/pod.yaml, test/test_images/heartbeats/pod.yaml, test/test_images/logevents/pod.yaml, test/test_images/performance/pod.yaml, test/test_images/print/pod.yaml, test/test_images/recordevents/pod.yaml, test/test_images/sendevents/pod.yaml, test/test_images/sequencestepper/pod.yaml, test/test_images/transformevents/pod.yaml
My initial grep missed these.
cc @grantr @n3wscott
=> Switch test images to strict mode

hack/release.sh
- For now, disable --strict mode for release
/cc @grantr
=> For now, disable --strict mode for release

test/e2e/trigger_dependency_annotation_test.go
- updating test to use latest APIs
=> update trigger dependency test to use latest ping source

pkg/adapter/main_message_adapter.go, pkg/adapter/main_message_adapter_test.go, pkg/channel/event_dispatcher_test.go, pkg/channel/message_dispatcher_test.go, pkg/channel/message_receiver_test.go
* `knative.dev/eventing/pkg/adapter`: `Main` -> `MainMessageAdapter`
plus some nits from a previous PR
Fixes #2672
=> Port adapter/Main to bindings 

test/lib/resources/constants.go, test/lib/resources/eventing.go
=> Removed unused code

hack/release.sh
Fixes #
- Release mt-channel-broker as a separate component.
```release-note
Add a releasable multi tenant channel based broker component.
```
**Docs**
https://github.com/knative/docs/issues/2320
=> release mt-channel-broker pieces

pkg/reconciler/mtnamespace/namespace_test.go
Fixes #
- remove leftover cruft
-
-
```release-note
```
**Docs**
=> remove unused cruft

config/brokers/mt-channel-broker/hpa.yaml
Fixes #
- Add a basic HPA for ingress / filter deployments that we can use for testing tuning the parameters necessary.
```release-note
```
**Docs**
=> add simple hpa for filter/ingress deployments

config/brokers/mt-channel-broker/400-config-br-defaults.yaml, test/e2e-common.sh, test/e2e-tests.sh, test/e2e/broker_channel_flow_test.go, test/e2e/broker_config_test.go, test/e2e/broker_dls_test.go, test/e2e/broker_event_transformation_test.go, test/e2e/channel_defaulter_test.go, test/e2e/configmappropagation_default_test.go, test/e2e/helpers/broker_channel_flow_test_helper.go, test/e2e/helpers/broker_dls_test_helper.go, test/e2e/helpers/broker_event_transformation_test_helper.go, test/e2e/helpers/broker_with_config_helper.go, test/e2e/helpers/channel_defaulter_test_helper.go, test/e2e/main_test.go, test/e2e/trigger_dependency_annotation_test.go, test/e2e_flags.go, test/lib/resources/eventing.go
Fixes #
- Add e2e tests for MT channel based broker.
- exclude conformance tests for MT channel based broker while we sort out the tracing related issues.
```release-note
```
**Docs**
=> first cut of surgically inserting mt e2e tests

pkg/reconciler/sequence/controller.go, pkg/reconciler/sequence/sequence.go, pkg/reconciler/sequence/sequence_test.go
- migrate sequence off reconciler.Base
```release-note
NONE
```
=> migrate sequence off reconciler.Base

pkg/reconciler/parallel/controller.go, pkg/reconciler/parallel/parallel.go, pkg/reconciler/parallel/parallel_test.go
- Migrate off reconciler.Base.
```release-note
NONE
```
=> Migrate parallel off reconciler.Base

pkg/reconciler/mtbroker/broker.go, pkg/reconciler/mtbroker/broker_test.go, pkg/reconciler/mtbroker/controller.go, pkg/reconciler/mtbroker/trigger.go
- migrate mtbroker off reconciler.Base
```release-note
NONE
```
/assign @vaikas
=> migrate mtbroker off reconciler.Base

pkg/reconciler/subscription/controller.go, pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go
- migrate subscription off reconciler.Base
```release-note
NONE
```
=> migrate subscription off reconciler.Base

pkg/reconciler/pingsource/controller/controller.go, pkg/reconciler/pingsource/controller/pingsource.go, pkg/reconciler/pingsource/controller/pingsource_test.go, pkg/reconciler/pingsource/jobrunner/controller.go, pkg/reconciler/pingsource/jobrunner/pingsource.go, pkg/reconciler/pingsource/jobrunner/pingsource_test.go
Fixes #
- migrate pingsource off reconciler.Base
```release-note
NONE
```
=> migrate pingsource off reconciler.Base

config/monitoring/metrics/grafana/100-grafana-dash-eventing.yaml, config/monitoring/metrics/prometheus/100-prometheus-scrape-kn-eventing.yaml
- Fix pingsource scrape job
- Add JobRunner Grafana dashboard
-
```release-note
A new Grafana dashboard is provided to monitor PingSources backed by JobRunner
```
**Docs**
=> fix pingsource label and add jobrunner grafana dashboard

Gopkg.lock, third_party/VENDOR-LICENSE, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/compare.go, vendor/github.com/google/go-cmp/cmp/export_panic.go, vendor/github.com/google/go-cmp/cmp/export_unsafe.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/internal/value/zero.go, vendor/github.com/google/go-cmp/cmp/options.go, vendor/github.com/google/go-cmp/cmp/path.go, vendor/github.com/google/go-cmp/cmp/report_compare.go, vendor/github.com/google/go-cmp/cmp/report_reflect.go, vendor/github.com/google/go-cmp/cmp/report_slices.go, vendor/github.com/google/go-cmp/cmp/report_text.go, vendor/golang.org/x/xerrors/LICENSE, vendor/golang.org/x/xerrors/PATENTS, vendor/golang.org/x/xerrors/adaptor.go, vendor/golang.org/x/xerrors/doc.go, vendor/golang.org/x/xerrors/errors.go, vendor/golang.org/x/xerrors/fmt.go, vendor/golang.org/x/xerrors/format.go, vendor/golang.org/x/xerrors/frame.go, vendor/golang.org/x/xerrors/internal/internal.go, vendor/golang.org/x/xerrors/wrap.go, vendor/knative.dev/pkg/Gopkg.lock, vendor/knative.dev/pkg/Gopkg.toml, vendor/knative.dev/pkg/test/cmd/command.go, vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
=> [master] Auto-update dependencies

pkg/reconciler/subscription/subscription_test.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -type f -name '*.go' -print)`
`goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party)`
=> [master] golang format tools

pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/controller.go
- migrate apiserversource off reconciler.Base
```release-note
NONE
```
=> migrate apiserversource off reconciler.Base

pkg/reconciler/mtnamespace/controller.go, pkg/reconciler/mtnamespace/controller_test.go, pkg/reconciler/mtnamespace/namespace.go, pkg/reconciler/mtnamespace/namespace_test.go
- migrate mtnamespace off reconciler.Base
```release-note
NONE
```
=> migrate mtnamespace off reconciler.Base

pkg/reconciler/namespace/controller.go, pkg/reconciler/namespace/namespace.go, pkg/reconciler/namespace/namespace_test.go
- migrate namespace controller off reconciler.Base
```release-note
NONE
```
=> migrate namespace controller off reconciler.Base

pkg/apis/eventing/v1alpha1/trigger_lifecycle.go, pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go, pkg/apis/eventing/v1beta1/trigger_lifecycle.go, pkg/apis/eventing/v1beta1/trigger_lifecycle_test.go
Fixes #2735
- Rename Trigger condition Subscribed to SubscriptionReady
=> Rename Trigger condition Subscribed to SubscriptionReady

pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/trigger.go, pkg/reconciler/mtbroker/trigger.go
- migrate broker off reconciler.Base
```release-note
NONE
```
=> migrate broker off reconciler.Base

test/conformance/helpers/tracing/zipkin.go, test/e2e/helpers/channel_defaulter_test_helper.go
Fixes #2807
- Reduce sleeps from 1 minute to 5 seconds.
-
-
```release-note
```
**Docs**
=> Reduce sleep time from minute to 5 seconds 

pkg/reconciler/channel/channel_test.go, pkg/reconciler/eventtype/eventtype_test.go, pkg/reconciler/reconciler.go
- Mark reconciler.Base deprecated
```release-note
NONE
```
=> Mark reconciler.Base deprecated

Gopkg.lock, cmd/ping/adapter/main.go, pkg/adapter/ping/adapter.go, pkg/adapter/ping/adapter_test.go, pkg/adapter/v2/cloudevents.go, pkg/adapter/v2/cloudevents_test.go, pkg/adapter/v2/config.go, pkg/adapter/v2/config_test.go, pkg/adapter/v2/main.go, pkg/adapter/v2/main_test.go, pkg/adapter/v2/test/test_client.go
- Use CloudEvents v2
- Auto-metrics
- Auto-ceOverrides.
- Applied to PingSource RA as a demo.
```release-note
NONE
```
=> Implement Source Adapter v2

docs/broker/README.md, pkg/reconciler/broker/broker.go
Fixes #
- Update the docs for left over cruft for ingress channel that was removed a while ago.
- Add a section for Multi Tenant Channel Based Broker
- Add a section for installing / uninstalling different broker impls 
-
```release-note
```
**Docs**
=> update broker impl docs

pkg/broker/filter/filter_handler.go, pkg/broker/filter/stats_reporter.go, pkg/broker/filter/stats_reporter_test.go, pkg/broker/ingress/ingress_handler.go, pkg/broker/ingress/stats_reporter.go, pkg/broker/ingress/stats_reporter_test.go
- Make broker stats reporter args public so that it can be used by other broker implementations.
-
-
```release-note
```
**Docs**
cc @grantr
=> Make broker stats reporter args public.

pkg/mtbroker/ingress/ingress_handler.go
Fixes #
- do not hard code the cluster domain suffix.
-
-
```release-note
```
**Docs**
=> oops, use the cluster domain name

Gopkg.lock, vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
=> [release-0.13] Auto-update dependencies

config/core/configmaps/leader-election.yaml, pkg/leaderelection/leader_election.go, pkg/leaderelection/leader_election_test.go, pkg/leaderelection/testdata/config-leader-election.yaml
- raise coverage
- add default/example config parsing and verification
- clean up the style, etc.
This came out from https://github.com/knative/serving/issues/3492 
/assign @vaikas mattmoor
=> Improve leader election CM handling.

pkg/channel/message_dispatcher.go, pkg/channel/message_dispatcher_test.go
Billion dollars mistake strikes again...
=> Fix nil in MessageDispatcher

config/core/roles/addressable-resolvers-clusterrole.yaml
Related to similar like #1450 
=> RBAC: Adding 'update' for the channel/finalizer, like on IMC

DEVELOPMENT.md
Fixes #
- In the DEVELOPMENT.md instructions, use the https based auth instead of ssh. This is apparently less error prone.
```release-note
```
**Docs**
=> change to https based auth

config/upgrade/v0.14.0/README.md
Fixes #
- Point to the release yaml artifcat instead of using ko apply -f
```release-note
```
**Docs**
=> point to release

docs/spec/data-plane.md
Ref: https://github.com/knative/eventing/issues/2614
- document contract for eventing data-plane components in one place
=> Document version of common data plane contract for eventing

config/upgrade/v0.14.0/upgrade.yaml
Fixes #
- yaml contained a trailing slash in ko image and it was causing failure to build.
-
-
```release-note
```
**Docs**
=> remove trailing slash

pkg/inmemorychannel/message_dispatcher.go, pkg/inmemorychannel/message_dispatcher_test.go, pkg/kncloudevents/message_receiver.go, pkg/kncloudevents/message_sender.go
This test helped me a lot to diagnose issues with dispatcher and receiver code
Also cleaned out the timeout code for closing the server from `InMemoryChannelDispatcher`. This is already done by `HttpMessageReceiver`
=> Added a test to check if IMC dispatcher works

Gopkg.lock, Gopkg.toml, vendor/knative.dev/pkg/Gopkg.lock, vendor/knative.dev/pkg/Gopkg.toml, vendor/knative.dev/pkg/RELEASING.md, vendor/knative.dev/pkg/configmap/testing/configmap.go, vendor/knative.dev/pkg/controller/controller.go, vendor/knative.dev/pkg/logging/config, vendor/knative.dev/pkg/metrics/config_observability.go, vendor/knative.dev/pkg/tracing/config/tracing.go, vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
- Move pkg/test-infra back to master post 0.14 release.
- Update to latest from branch master.
```release-note
NONE
```
/cc mattmoor
=> Updating pkg to master post 0.14 release.

pkg/reconciler/pingsource/jobrunner/controller.go, pkg/reconciler/pingsource/jobrunner/pingsource.go, pkg/reconciler/pingsource/jobrunner/pingsource_test.go
- Fix a map read-write race issue
=> fix map read-write race bug

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Authored-By: Ville Aikas <vaikas@vmware.com>
Fixes #
-
-
-
```release-note
```
**Docs**
=> [release-0.14] do not specify replicas (#3022)

pkg/channel/message_dispatcher.go, pkg/channel/swappable/swappable_message_handler.go, pkg/inmemorychannel/message_dispatcher_benchmark_test.go
- Add a microbenchmark for the IMC dispatcher without network operations (mocks the client and server)
=> IMC Dispatcher microbenchmark

docs/spec/spec.md, docs/spec/spec_v1alpha1.md, pkg/apis/duck/v1beta1/delivery_types.go
Fixes #
- starts to update spec parts for `v1beta1
=> spec update for v1beta

docs/spec/spec.md
Produced via:
`prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github | grep -v docs/cmd/)`
=> [master] Format markdown

config/core/roles/webhook-clusterrole.yaml
=> Allow the webhook to patch namespaces (rbac)

pkg/reconciler/testing/listers.go
Fixes #
- Add PodListers so it can be used in unit tests
-
-
```release-note
NONE
```
**Docs**
=> Add PodLister to reconciler test listers

pkg/reconciler/testing/listers.go
This reverts commit 300722fdaf406ff52dd33a043837fe84e76914ad.
- Just realized this is not needed.
-
-
```release-note
NONE
```
**Docs**
=> Revert "Add PodLister to reconciler test listers"

config/core/roles/controller-clusterroles.yaml
Fixes #3056
- add missing RBAC cluster role
-
-
=> allow the eventing controller to set Deployment owner ref

config/channels/in-memory-channel/500-dispatcher.yaml
Fixes #3036
- remove resources
=> remove resources (issue 3036)

pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go, pkg/apis/messaging/v1alpha1/in_memory_channel_conversion_test.go, pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go, pkg/reconciler/subscription/subscription.go, test/e2e/channel_single_event_test.go, test/e2e/helpers/channel_single_event_helper.go, test/lib/duck/resource_checks.go
Fixes #3014
- backport of Ville's change from master to here
```release-note
- 🐛 Fix bug: PhysicalChannelSyncFailed when mixing v1alpha1 and v1beta1 Subscriptions
```
**Docs**
=> fix issue 3014 (#3049)

go.mod, go.sum, hack/tools.go, hack/update-deps.sh, third_party/VENDOR-LICENSE, vendor/knative.dev/test-infra/scripts/library.sh, vendor/knative.dev/test-infra/scripts/presubmit-tests.sh, vendor/modules.txt
- Add `update-licenses` back
- Add floating versions in the `--upgrade` command
/cc @vaikas 
/cc @n3wscott
=> fix go modules issues

docs/spec/channel.md
- forgotten API bumps
/assign @Harwayne
=> Forgot yaml API bumps

config/channels/in-memory-channel/README.md
Update examples to follow latest versions
=> Update imc readme examples to v1beta1

pkg/adapter/v2/main_message.go, pkg/adapter/v2/main_message_test.go
- Now adapter/v2 uses the new envconfig
=> Moved MainMessageAdaoter under adapter/v2 directory

hack/verify-codegen.sh
Verifies if go.mod is up to date in build tests
=> Check go.mod in codegen verification

pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/controller.go, pkg/reconciler/source/config_watcher.go, pkg/reconciler/source/config_watcher_test.go, pkg/reconciler/testing/factory.go
Fixes #3100
- Added a ConfigWatcher specific for sources that retrieves config-observability, config-tracing and config-logging
=> Created a config watcher specific for sources

pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/source/config_watcher.go, pkg/reconciler/source/config_watcher_test.go
Just a little correction to #3101 to remove even more copy-pasted code
=> Added a method to simplify usage of source.ConfigWatcher

config/core/deployments/webhook.yaml, go.mod, go.sum, pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go, pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go, pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/reconciler.go, pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go, pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go, pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go, pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go, pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go, pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go, pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/reconciler.go, pkg/client/injection/reconciler/sources/v1alpha1/pingsource/reconciler.go, pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go, pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go, pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go, vendor/knative.dev/pkg/apis/volatile_time.go, vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go, vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go, vendor/knative.dev/pkg/injection/README.md, vendor/knative.dev/pkg/network/network.go, vendor/knative.dev/pkg/webhook/webhook.go, vendor/modules.txt
See: https://github.com/knative/pkg/pull/1318
=> Pull in pkg and add probes

config/core/deployments/controller.yaml, pkg/reconciler/pingsource/controller.go, pkg/reconciler/pingsource/controller_test.go, pkg/reconciler/pingsource/resources/mt_receive_adapter.go, pkg/reconciler/pingsource/resources/mt_receive_adapter_test.go
=> Revert "add owner ref to mtping deployment"

test/e2e/broker_default_test.go, test/e2e/helpers/broker_test_helper.go, test/lib/resources/eventing.go
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
Fixes #2352 
- Test broker with many triggers with any channel
- Allow testing non-channel based brokers
=> Test broker with many triggers

pkg/apis/flows/v1alpha1/parallel_types.go, pkg/apis/flows/v1alpha1/zz_generated.deepcopy.go, pkg/apis/flows/v1beta1/parallel_types.go, pkg/apis/flows/v1beta1/zz_generated.deepcopy.go, pkg/reconciler/parallel/parallel_test.go, pkg/reconciler/parallel/resources/subscription.go
Fixes #3145
- Add Delivery to parallel for DLQ
-
-
```release-note
Add Delivery to parallel branches.
```
**Docs**
=> Add Delivery to Parallel API

pkg/reconciler/apiserversource/controller.go, pkg/reconciler/broker/controller.go, pkg/reconciler/containersource/controller.go, pkg/reconciler/mtbroker/controller.go, pkg/reconciler/mtnamespace/controller.go, pkg/reconciler/namespace/controller.go, pkg/reconciler/parallel/controller.go, pkg/reconciler/pingsource/controller.go, pkg/reconciler/sequence/controller.go, pkg/reconciler/source/duck/controller.go
Cleaning up deprecations. The new names read much better.
=> Replace deprecated filter methods with their new names.

pkg/apis/config/defaults.go, pkg/apis/messaging/config/channel_defaults.go, pkg/apis/messaging/v1alpha1/channel_conversion.go, pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go, pkg/channel/fanout/fanout_message_handler.go, pkg/reconciler/broker/broker.go, test/conformance/helpers/channel_header_single_event_helper.go, test/conformance/helpers/tracing/traces.go, test/conformance/helpers/uri.go, test/e2e/helpers/broker_test_helper.go, test/e2e/helpers/channel_defaulter_test_helper.go, test/e2e/helpers/trigger_no_broker_test_helper.go, test/lib/checkevents_test.go, test/lib/creation.go, test/performance/infra/receiver/receiver.go
- Removed unused code where appropriate.
- Simplified statements (copy instead of loops, channel reads).
- Preallocate slices where appropriate.
- Remove unnecessary conversions.
=> Assorted linting fixes.

test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml, test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml
- Use Mako sidecar image from knative-tests so we can have a central place to maintain it
/cc @grantr
=> Use Mako sidecar image from knative-tests

test/upgrade/prober/prober.go
Produced via:
`github.com/client9/misspell`
=> [master] Fix spelling errors

test/e2e/helpers/channel_defaulter_test_helper.go
Fixes #3195
- Wrap the update of configmap in retry block (to deal with conflicts).
```release-note
```
**Docs**
=> wrap update config map in retry for conflicts

pkg/reconciler/broker/controller.go
Fixes #
- remove reference for defaulting to `ChannelBasedBroker`
-
-
```release-note
- 🧽 MTChannelBasedBroker is the default - reflecting setting in code 
```
**Docs**
=> Remove reference for defaulting to ChannelBasedBroker

cmd/sendevent/main.go
=> Ported cmd/sendevent to sdk-go v2

cmd/pong/main.go
=> Ported cmd/pong to sdk-go v2

test/lib/creation.go
Fixes #3152 
- Add a retry on conflict for pod creations.
```release-note
```
**Docs**
=> add retry loop for conflicts on pod creation

test/performance/benchmarks/broker-imc/100-broker-perf-setup.yaml, test/performance/benchmarks/broker-imc/continuous/100-broker-imc-setup.yaml
- updates to latest
/assign @chizhg
=> Using MTChannelBasedBroker and v1beta1 APIs

go.mod, vendor/modules.txt
Fixes #
- Use 1.14 in go mod file. 
-
-
```release-note
```
**Docs**
=> move to 1.14 in go.mod

pkg/apis/messaging/config/store.go
- Fix typo 'chnanel' -> 'channel'.
```release-note
NONE
```
=> Fix typo 'chnanel' -> 'channel'.

pkg/apis/sources/v1alpha2/ping_types_test.go
=> Add ping_types_test.go for GetStatus

config/brokers/mt-channel-broker/deployments/hpa.yaml
Fixes #
- This PR added the label eventing.knative.dev/release to the resources missing it
```release-note
```
**Docs**
=> Add the label eventing.knative.dev/release to the resources missing it

pkg/apis/sources/v1alpha2/apiserver_types.go, pkg/apis/sources/v1alpha2/container_types.go, pkg/apis/sources/v1alpha2/ping_types.go, pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go, pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go, pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go, pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/containersource/containersource.go, pkg/reconciler/containersource/containersource_test.go, pkg/reconciler/pingsource/pingsource.go, pkg/reconciler/testing/containersource.go
Issue #3099
- Generate logic to automatically bump generation for /api/sources types
```release-note
```
**Docs**
=> Automatic generation bump for apis/sources

pkg/apis/flows/v1beta1/parallel_lifecycle.go, pkg/apis/flows/v1beta1/parallel_lifecycle_test.go, pkg/apis/flows/v1beta1/parallel_types.go, pkg/apis/flows/v1beta1/parallel_types_test.go, pkg/apis/flows/v1beta1/sequence_lifecycle.go, pkg/apis/flows/v1beta1/sequence_lifecycle_test.go, pkg/apis/flows/v1beta1/sequence_types.go, pkg/apis/flows/v1beta1/sequence_types_test.go
Issue #3221
- Implement krshaped for flow types
```release-note
```
**Docs**
=> Implement krshaped for flow types

test/lib/await.go, test/test_images/wathola-forwarder/main_test.go, test/test_images/wathola-receiver/main_test.go, test/upgrade/prober/wathola/receiver/services_test.go
Fixes #3222 
- Better wait for readiness
- Adding additional checks to remove flakiness
=> Fix flake for TestReceiverReceive

test/microbenchmarks-compare.sh, test/microbenchmarks-run.sh
Look at https://github.com/knative/test-infra/issues/1906
- Added a script to run microbenchmarks
- Added a script to compare the actual revision and a previous revision and output an html report
/assign @chizhg
=> Microbenchmarks script

test/performance/infra/receiver/id_extractor.go, test/performance/infra/receiver/receiver.go, test/performance/infra/receiver/type_extractor.go, test/performance/infra/sender/http_load_generator.go
Fixes #3105
- Ported performance/infra code to sdk-go v2
=> Performance image code porting to sdk-go v2

test/test_images/wathola-forwarder/main_test.go, test/test_images/wathola-receiver/main_test.go, test/upgrade/prober/wathola/forwarder/services.go, test/upgrade/prober/wathola/receiver/services.go
Fixes #3255 
Fixes #3270 
- Flakeiness of TestForwarderMain and TestReceiverMain removed
=> Flakeiness of TestForwarderMain and TestReceiverMain removed

test/e2e/helpers/parallel_test_helper.go
Part of #3267
- parallel event e2e test now uses new event sender and event record
cc @slinkydeveloper
=> Port parallel event e2e test to new test facilities

hack/release.sh
Fixes #
- remove obsolete upgrade jobs
- Add pre-install release artifact. 
-
```release-note
Add release artifact of PRE upgrade to v0.16 that must be run before upgrading to v0.16.
action required: must run pre-install job before upgrading to v0.16.
```
**Docs**
https://github.com/knative/docs/issues/2543
=> update release scripts

DEVELOPMENT.md
- Added a new guide to do packet sniffing. This guide is meant to be used only by Eventing contributors
=> Guide for Packet Sniffing

pkg/adapter/mtping/pingsource.go, pkg/adapter/mtping/runner.go, pkg/adapter/mtping/runner_test.go
Pingsource fix
https://github.com/knative/eventing/issues/3253
Fixes #
-
-
-
```release-note
```
**Docs**
=> ceOverride #3253

test/conformance/helpers/channel.go
=> Use some existing label

config/core/resources/channel.yaml
- Add missing YAML desc for channel template's spec field
=> YAML desc for channel template spec

pkg/mtbroker/filter/stats_reporter.go, pkg/mtbroker/ingress/stats_reporter.go
Fixes #
This is the follow up of https://github.com/knative/pkg/pull/1410, to prepare for https://github.com/knative/pkg/pull/1392.
Without this change the stackdriver metrics will be broken once https://github.com/knative/pkg/pull/1392 is merged.
Corresponding PR in serving: https://github.com/knative/serving/pull/8360
-
-
-
None.
```release-note
```
**Docs**
=> Change view.Register to RegisterResourceView

test/conformance/helpers/channel_crd_metadata_test_helper.go, test/conformance/helpers/source_crd_metadata_test_helper.go
Fixes #3321
- using constants
```release-note
```
**Docs**
=> Using constants

hack/release.sh
Fixes #3386
- Added a new artifact called eventing-upgrade.yaml, as the entry to retrieve all upgrade related resources.
=> Add an artifact eventing-upgrade.yaml to host all the upgrade resources

cmd/webhook/main.go
Part of #3337
- Add eventing v1 types to webhook config for defaulting, validation and conversion
=> Add eventing v1 types to webhook config

test/lib/operation.go, test/lib/recordevents/event_info_store.go
=> Wanna fix recent CI flakyness

pkg/reconciler/source/crd/crd.go
Fixes #3404 
- Address alerts described in https://lgtm.com/projects/g/knative/eventing/snapshot/946effc77e1847b610a7161f209d02a2b62c40e1/files/pkg/reconciler/source/crd/crd.go?sort=name&dir=ASC&mode=heatmap w.r.t unused variables
```release-note
```
=> Fix Alerts from LGTM

cmd/webhook/main.go, pkg/apis/messaging/v1beta1/channel_conversion.go, pkg/apis/messaging/v1beta1/channel_conversion_test.go, pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go
Part of  #3336
- Add conversions for messaging/channel v1beta1 -> v1 (and backwards) + conversion tests
-
=> Messaging/channel v1beta1 -> v1 conversions

test/e2e-upgrade-tests.sh, test/e2e_flags.go, test/flags/eventing_environment.go, test/upgrade/probe_test.go
Fixes #3419
- Probe tests can pick up temp files from the params.
=> Add configuration options to the temp files for Probe tests

test/e2e-common.sh
Unblocks: https://github.com/knative/eventing/pull/3409
=> use the latest point release for upgrades tests

go.mod, go.sum, vendor/github.com/cloudevents/sdk-go/v2/alias.go, vendor/github.com/cloudevents/sdk-go/v2/client/http_receiver.go, vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go, vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go, vendor/modules.txt
- Update to the latest release of the CloudEvents SDK - 2.1.0
```release-note
NONE
```
=> Update to the latest release of the CloudEvents SDK - 2.1

cmd/webhook/main.go
Part of #3336
- Adds webhooks for messaging v1 now that conversions are set up in #3421, #3427
-
fyi @lionelvillard
=> add missing webhooks for messaging v1

pkg/apis/eventing/v1beta1/broker_conversion.go, pkg/apis/eventing/v1beta1/broker_conversion_test.go, pkg/apis/eventing/v1beta1/trigger_conversion.go, pkg/apis/eventing/v1beta1/trigger_conversion_test.go, pkg/apis/flows/v1beta1/parallel_conversion.go
- fix go format
- 
-
```release-note
```
**Docs**
=> fix go format

pkg/apis/eventing/v1/test_helper.go
- now that messaging v1 is out, use it as discussed in the #3372 comments:
https://github.com/knative/eventing/pull/3372#discussion_r444012080
@aliok 
```release-note
```
**Docs**
=> use messaging.v1 in test_helper. Follow up to 3372 comment.

pkg/reconciler/sinkbinding/controller.go
Unlike our `// +genreconciler` friends, the `psbinding.BaseReconciler` needs consumers to implement the `PromoteFunc` method to properly resync when they are promoted to leader of a particular bucket.
=> Add missing PromoteFunc for SinkBinding

config/post-install/v0.15.0/storage-version-migration.yaml, config/pre-install/v0.16.0/storage-version-migration.yaml
- use eventing as label instead of serving
```release-note
```
**Docs**
=> use eventing as label instead of serving

config/pre-install/v0.16.0/broker.yaml, config/pre-install/v0.16.0/pingsource.yaml
- Do not bump the pre-install conversionreviewversions because v1 is not there yet.
```release-note
```
**Docs**
=> only v1beta1 conversions please

OWNERS
I want to help out more with reviews!
similar to https://github.com/knative/eventing/pull/2771
fyi @grantr @lionelvillard
=> Add nlopezgi to reviewers list

test/e2e-upgrade-tests.sh, test/e2e_flags.go, test/upgrade/probe_test.go
Fixes #
- This PR is a cherry-pic of b756e15b404236fcbc6c96b7c5fbbfafdb5e8fd1.
```release-note
```
**Docs**
=> [release-0.15] Add configuration options to the temp files for Probe tests (#3420)

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Fixes #
- Same as 3162, but for mt broker.
-
-
```release-note
```
**Docs**
=> mt bits for 3162

pkg/reconciler/testing/v1/parallel.go, pkg/reconciler/testing/v1/sequence.go, test/e2e/helpers/parallel_test_helper.go, test/e2e/helpers/sequence_test_helper.go, test/e2e/parallel_test.go, test/e2e/sequence_test.go, test/lib/creation.go
- Add flows v1 e2e tests
-
-
```release-note
```
**Docs**
=> flows v1 e2e tests

hack/release.sh
- Do not create a combined eventing-upgrade.yaml. The pre/post install need to run separately, and having a combined file makes it easier to make mistakes.
-
-
```release-note
```
**Docs**
=> do not create a combined upgrade.yaml file

pkg/apis/duck/v1/subscribable_types.go, pkg/apis/duck/v1/subscribable_types_conversion.go, pkg/apis/duck/v1/subscribable_types_conversion_test.go, pkg/apis/duck/v1alpha1/subscribable_types.go, pkg/apis/duck/v1alpha1/subscribable_types_conversion.go, pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go, pkg/apis/duck/v1beta1/subscribable_types.go, pkg/apis/duck/v1beta1/subscribable_types_conversion.go, pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go, pkg/apis/messaging/v1beta1/channel_conversion.go, pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
- Make SubscribableStatus implement apis.Convertible
=> Make SubscribableStatus implement apis.Convertible

test/e2e-common.sh, test/e2e/trigger_dependency_annotation_test.go, test/lib/client.go, test/lib/resources/constants.go, test/lib/resources/variables.go
Fixes #3462 
This PR used a generated uuid as the random namespace to install eventing and test eventing.
=> Randomize the ns to install and test eventing

OWNERS
=> Add aliok to reviewers list

hack/release.sh
extra `)` in the release file.
=> fix bad merge

pkg/reconciler/sugar/resources/broker.go
Fixes #3512
- Using Constant values for annotation key and value
=> Use string consts for annotation key/values

test/e2e-upgrade-tests.sh
Fixes #
- When downgrading from .16 to .15 we needed to patch subscription object. This is no longer necessary.
-
-
```release-note
```
**Docs**
=> remove unnecessary patch

config/post-install/v0.15.0/storage-version-migration.yaml
Fixes #3532 
backport #3534
* Fixing issue where jobs do not complete on istio enabled cluster
```release-note
Fixes issue where migration jobs would fail on Istio cluster with auto-inject enabled
```
=> adding istio annotation

config/core/roles/controller-clusterroles.yaml, config/core/roles/webhook-clusterrole.yaml
- 🐛 Fix bug
```release-note
Add missing "leases" RBAC to controller and webhook to support leader election.
```
=> Without this RBAC, leaderelection cannot be enabled.

config/core/configmaps/leader-election.yaml, config/core/configmaps/observability.yaml, config/core/configmaps/tracing.yaml
- Remove duplicate label (these are anotations, not labels)
- Include double quotes to ensure string parsability
- knative/pkg#1472 should default to this
- knative/serving#8582 shows where numerical parsing can fail
=> Fix checksums

config/core/configmaps/observability.yaml, pkg/adapter/mtping/controller.go, pkg/adapter/mtping/pingsource.go, pkg/adapter/mtping/pingsource_test.go, pkg/adapter/mtping/runner.go, pkg/adapter/mtping/runner_test.go, pkg/adapter/v2/cloudevents.go, pkg/adapter/v2/main.go, pkg/adapter/v2/util/crstatusevent/eventsstatus.go, pkg/adapter/v2/util/crstatusevent/eventsstatus_test.go
Send Kube Event when failure on sending to sink
https://github.com/knative/eventing/issues/3281
Fixes #3281
Provide a context that sends Kube events to the Sinks'CR when there's a failure sending cloud events to the target sink.
-
-
=> Showing eventing errors to user

pkg/reconciler/mtbroker/broker.go, pkg/reconciler/mtbroker/broker_test.go, pkg/reconciler/mtbroker/controller.go, pkg/reconciler/mtbroker/trigger.go
=> Make the mtbroker use the recorder off context.

pkg/reconciler/mtbroker/broker.go, pkg/reconciler/mtbroker/broker_test.go, pkg/reconciler/mtbroker/controller.go
With genreconciler this Lister is vestigial.
=> Drop vestigial lister

test/e2e-tests.sh
- don't force using /bin/bash
-
-
```release-note
```
**Docs**
=> don't force using /bin/bash

test/lib/operation.go
When resources are created that might be side effects, for example, sugar creates Brokers, or such, we don't see the state of the resource if things fail. This dumps the state of the resource when it fails to get ready.
- when WaitForResourceReadyOrFail times out, dump the failed object instead of just the stacktrace.
-
-
```release-note
```
**Docs**
=> dump failed objects to aid in debugging

hack/k8s-client-go.patch, hack/update-deps.sh
- git apply patch
-
-
```release-note
```
**Docs**
@mattmoor
=> use git apply instead of patch

cmd/webhook/main.go, config/core/resources/containersource.yaml, pkg/apis/sources/v1alpha2/container_conversion.go, pkg/apis/sources/v1alpha2/container_conversion_test.go, pkg/apis/sources/v1beta1/container_conversion.go, pkg/apis/sources/v1beta1/container_conversion_test.go
Part of #3426
- Add ContainerSources v1beta1 defaults & conversion
=> Conversion webhook for ContainerSources v1beta1

go.mod, go.sum, vendor/knative.dev/pkg/controller/two_lane_queue.go, vendor/knative.dev/pkg/injection/sharedmain/main.go, vendor/knative.dev/pkg/leaderelection/context.go, vendor/knative.dev/pkg/network/error_handler.go, vendor/knative.dev/pkg/network/handlers/doc.go, vendor/knative.dev/pkg/network/handlers/drain.go, vendor/knative.dev/pkg/network/handlers/error.go, vendor/knative.dev/pkg/webhook/webhook.go, vendor/knative.dev/test-infra/scripts/e2e-tests.sh, vendor/knative.dev/test-infra/scripts/library.sh, vendor/modules.txt
This is attempting to try and combat the webhook Post EOF errors we have been seeing intermittently: https://github.com/knative/pkg/issues/1509
- 🐛 Fix bug
=> Pull in the new fancier webhook drain from knative/pkg.

pkg/apis/eventing/register.go, pkg/apis/eventing/v1beta1/broker_conversion_test.go, pkg/mtbroker/ingress/ingress_handler.go, pkg/mtbroker/ingress/ingress_handler_test.go, pkg/reconciler/mtbroker/broker.go, pkg/reconciler/testing/v1/broker.go
Fixes #3626
- Add const for broker channel address status annotation key
- Prefix this key with knative.dev/
=> Prefix channelAddress annotation with knative.dev/

pkg/adapter/v2/config.go
Fixes https://github.com/knative/eventing/issues/3714
- Make environment variables NAMESPACE, K_LOGGING_CONFIG, K_METRICS_CONFIG optional, 
- K_LOGGING_CONFIG, K_METRICS_CONFIG has "" as default value
=> Make easier to run knative code locally for testing and development

pkg/adapter/mtping/adapter.go, pkg/adapter/mtping/runner.go, pkg/adapter/mtping/runner_test.go, pkg/adapter/v2/test/test_client.go
Wait for all crontick jobs to complete
Fixes #3664
<!--
If this change has user-visible impact, follow the instructions below.
Examples include:
- 🐛 Fix bug
=> Delay ending pod to give cron jobs time to send.#3664

test/conformance/broker_control_plane_test.go, test/conformance/helpers/broker_control_plane_test_helper.go
- Broker control plane conformance test can run with any Broker
=> Broker control plane conformance test can run with any Broker

docs/source/README.md, docs/source/receive-adapter.md
- Provide devel receive adapter doc.
-
-
```release-note
```
**Docs**
=> devel receive adapter doc

pkg/leaderelection/leader_election_test.go
The quoting of error strings changed, so to run with go 1.15 this change is needed.
/assign @vaikas @grantr @n3wscott
=> Fix the test for go 1.15

pkg/reconciler/inmemorychannel/controller/controller.go, pkg/reconciler/inmemorychannel/controller/controller_test.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go, pkg/reconciler/inmemorychannel/controller/resources/service.go, pkg/reconciler/inmemorychannel/controller/resources/service_test.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/inmemorychannel/dispatcher/controller_test.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go, pkg/reconciler/testing/v1/inmemorychannel.go
Part of #3584
- Migrate inmemorychannel reconciler to use messaging.* v1 resources
-
=> Migrate inmemorychannel reconciler to use messaging.* v1 resources

pkg/reconciler/sequence/controller.go, pkg/reconciler/sequence/controller_test.go, pkg/reconciler/sequence/resources/channel.go, pkg/reconciler/sequence/resources/subscription.go, pkg/reconciler/sequence/sequence.go, pkg/reconciler/sequence/sequence_test.go
Part of #3584
- Migrate sequence reconciler to use messaging.* v1 resources
-
=> Migrate sequence reconciler to use messaging.* v1 resources

pkg/apis/sources/v1beta1/ping_types.go
=> fix: spell error

config/core/roles/clusterrole-namespaced.yaml
- adding bindings to the view role
- relates to https://github.com/knative/eventing/pull/3465
-
```release-note
```
**Docs**
/cc @itsmurugappan
=> Adding permission to view binding APIs

test/conformance/helpers/broker_control_plane_test_helper.go
After updating the Trigger we need to wait to become ready again.
- Wait Trigger ready in broker control plane conformance test
- Remove time.Sleep hack
=> Wait Trigger ready in broker control plane conformance test

pkg/adapter/v2/main.go, pkg/adapter/v2/main_test.go
- fix bad disabledHA context key 
-
-
```release-note
```
**Docs**
=> fix bad context key in v2/adapter

support/COMMUNITY_CONTACTS.md
Part of https://github.com/knative/serving/issues/8005 .  More details in https://docs.google.com/document/d/1woxDpdw6TrwwF-Y987OYVUFrSgGpyBiR3U8ehf0BX9o/edit# .
- Seed a community contact rotation using Eventing approvers and https://www.random.org/lists/
- Add some initial instruction for community contact.
```release-note
NONE
```
**Docs**
=> Add community contact rotation for Eventing.

config/brokers/mt-channel-broker/deployments/hpa.yaml
- adding CP header
-
-
```release-note
```
**Docs**
=> Adding Copyright headers for the hpa file

pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/controller.go
- Remove unused variables from ApiServerSource Reconciler
```release-note
NONE
```
=> Remove unused variables from ApiServerSource Reconciler

config/core/resources/pingsource.yaml
Add content in CRDs to generate kubectl explain content for PingSource ONLY
🐛 partial fix for bug #3054
=> kubectl explain for PingSource

config/core/resources/broker.yaml
Fixes #3854 
- Remove required `broker.status.address.url`
```release-note
None
```
=> Remove required broker.status.address.url

config/core/resources/apiserversource.yaml
Add content in CRDs to generate kubectl explain content for APIServerSource ONLY
🐛 partial fix for bug #3054
=> kubectl explain for APIServerSource

config/core/resources/eventtype.yaml, pkg/apis/eventing/v1beta1/eventtype_types.go
Part of #3054
- Add content in CRDs to generate kubectl explain content for EventType
=> kubectl explain for EventType

pkg/apis/eventing/v1/trigger_types.go, pkg/apis/eventing/v1/trigger_validation.go, pkg/apis/eventing/v1/trigger_validation_test.go, pkg/apis/eventing/v1beta1/trigger_types.go, pkg/apis/eventing/v1beta1/trigger_validation.go, pkg/apis/eventing/v1beta1/trigger_validation_test.go, pkg/reconciler/sugar/filters_test.go, pkg/reconciler/sugar/labels.go, pkg/reconciler/sugar/trigger/trigger_test.go
Fixes #3874
- remove deprecated code
```release-note
```
**Docs**
=> Remove deprecated  and have only the fqn for injection

pkg/adapter/v2/config.go, pkg/reconciler/pingsource/controller.go, pkg/reconciler/pingsource/controller_test.go, pkg/reconciler/pingsource/pingsource.go
- Leverage source config watcher.
-
-
```release-note
```
**Docs**
=> leverage source config watcher in PingSource controller

config/core/configmaps/default-broker-channel.yaml, config/core/configmaps/default-channel.yaml
- updates to actual `v1` api shapre for IMC, as default channel impl
```release-note
```
**Docs**
=> Setting IMC/v1 as default

config/core/resources/parallel.yaml
Part of #3054
- Add content in CRDs to generate kubectl explain content for Parallel
=> kubectl explain for parallel

test/conformance/helpers/broker_data_plane_test_helper.go
Fixes #3791 
- add wait on service for transformer pod
- 🐛 Fix bug
=> broker conformance: Add wait for service endpoint (transformer pod)

pkg/adapter/mtping/runner.go
https://github.com/knative/eventing/issues/3913
Fixes #
Pingsource crontick log source and target for the event.
Pingsouce crontick set event ID
Pingsource provide small time delay for many events at top of minute.
<!--
If this change has user-visible impact, follow the instructions below.
Examples include:
-
=> Pingsource crontick minor enhancements #3913

hack/release.sh
Fixes #
- Release preinstall yaml too
=> Release preinstall job yaml too

config/pre-install/v0.18.0/clusterrole.yaml
Quick cleanup of the clusterroles
=> Alias clusterrole verbs for 0.18.0 pre-install

cmd/mtping/main.go, config/core/roles/pingsource-mt-adapter-clusterrole.yaml, pkg/adapter/mtping/adapter.go, pkg/adapter/mtping/controller.go, pkg/adapter/mtping/controller_test.go, pkg/adapter/mtping/pingsource.go, pkg/adapter/mtping/pingsource_test.go, pkg/reconciler/pingsource/controller.go
- Backporting #3935
-
-
```release-note
```
**Docs**
=> revert change to get PingSource specs from ConfigMaps

pkg/adapter/mtping/runner.go
https://github.com/knative/eventing/issues/3913
(cherry picked from commit 3eb844f73308d9b6f4018518ff1c27cafc0f8c3b)
Fixes #
#
=> Pingsource crontick minor enhancements #3913 (#3914)

test/lib/creation.go
Fixes #3949 
- If the Create fails with already exists, do not use the returned value, but instead fetch it again (again in a retry loop, argh).
```release-note
```
**Docs**
=> Fix another flake: If resource fails with alreadyexists, fetch it

test/e2e/broker_redelivery_test.go
Fixes #
- porting 3956 to 0.17 branch
-
-
```release-note
```
**Docs**
=> Updating broker to be v1

cmd/mtbroker/ingress/main.go
Fixes #3524
- Add a MAX_TTL variable that allows one to configure the TTL used.
-
-
```release-note
Allow MTChannelBroker TTL to be configured via ENV variable.
```
**Docs**
=> introduce a MAX_TTL env variable. fix 3524

pkg/reconciler/mtbroker/trigger/controller.go, pkg/reconciler/mtbroker/trigger/trigger.go
- Enqueue Triggers on Broker changes
=> [release-0.17] Enqueue Triggers on Broker changes (#3966)

test/conformance/helpers/channel_spec_test_helper.go
Fixes #3959
- Retry channel update in channel spec conformance tests
=> Retry channel spec update in conformance tests
