pkg/controller/channel/controller.go

The Istio validator was rejecting VirtualServices created for Channels.
Adding the PortSelector made the validator happy again.
Fixes #302

Update VirtualSerivce to pass Istio validation

---

pkg/buses/monitor.go

For a namespaces bus, if there is a cluster bus installed with the same
name, the cluster bus will be captured in the monitor and used to check
if a channel is for that bus. This effectively causes channels to be
provisioned by the wrong bus, or not at all.
Before replacing the bus reference for the monitor, we need to check the
kind, name and namespace. Previously, only the name and namespace where
checked.

Avoid replacing the monitor's bus with the wrong bus

---

pkg/controller/feed/reconcile.go

When there are multiple places a Feed can be updated, resourceVersion conflicts become more likely. This PR splits `Reconcile` into two functions:
- an inner function `reconcile` that reconciles the state of a Feed without updating it
- an outer function `Reconcile` that loads the Feed, calls the inner function if the
Feed exists, then updates the Feed.
This separation of responsibilities reduces the likelihood that a Feed will be updated more than once per reconcile.
@adamharwayne this might fix the problem you were having yesterday with Feeds not getting a status when EventSource and/or EventType were missing.

Only update the feed in one place

---

config/100-namespace.yaml
config/500-controller.yaml
config/500-webhook.yaml
pkg/controller/feed/reconcile_test.go
pkg/controller/feed/resources/job.go
pkg/sources/container_event_source_job.go
test/e2e/k8sevents/e2etestfnnamespace.yaml
test/e2e/k8sevents/e2etestnamespace.yaml

Istio 1.0 allows deployments/pods to opt-in to istio sidecar injection
without the namespace being explicity labled to support injection. This
mean that namespace can drop the label and deployments/pod that should
not be istio injected no longer need to explicitly opt-out.
Follow up to #203 and #205. Refs knative/serving#1300
/assign @tcnghia 
/assign @evankanderson

Opt-in to istio sidecar injection

---

config/buses/gcppubsub/README.md
config/buses/kafka/README.md
config/buses/stub/README.md
pkg/controller/names.go

Fixes #283
* Add '-dispatcher' suffix to bus dispatcher deployment creating symmetry with the provisioner deployment, which uses the '-provisioner' suffix

Add '-dispatcher' suffix to bus dispatcher deployment

---

pkg/controller/feed/reconcile.go
pkg/controller/feed/reconcile_test.go

Adds a test exercising the `ParametersFrom` secret key reference. Also removes a superfluous helper method that was only used in one place and didn't make that place more terse or more clear.

Test ParametersFrom feature

---

pkg/controller/feed/reconcile_test.go
pkg/controller/feed/resources/job.go

This allows local images to be used, e.g. for minikube.
Fixes #284.
*  Change feedlet pod PullPolicy to `IfNotPresent`.

Pull feedlet image only if not present

---

config/300-bus.yaml
config/300-channel.yaml
config/300-clusterbus.yaml
config/300-clustereventsource.yaml
config/300-clustereventtype.yaml
config/300-eventsource.yaml
config/300-eventtype.yaml
config/300-feed.yaml
config/300-flow.yaml
config/300-subscription.yaml

Relates to https://github.com/knative/serving/pull/1723
- Channel: `chan`
- ClusterBus: `cbus`
- Subscription: `sub`
- `kbus`: Bus, ClusterBus
- `keventsource`: EventSource, ClusterEventSource
- `keventtype`: EventType, ClusterEventType

Adding short names to eventing resources.

---

pkg/buses/monitor.go

Unprovision and unsubscribe events are triggered by the deletion of the
respective Channel and Subscription resource. Because the resource has
been deleted, any attempt to update status for that resource will fail,
creating noise in the log.
Fixes #300

Don't update status for deleted resources

---

pkg/controller/flow/reconcile.go
pkg/controller/flow/resources/channel.go
pkg/controller/flow/resources/feed.go
pkg/controller/flow/resources/subscription.go
pkg/controller/owner_references.go

Taking the good parts of https://github.com/knative/eventing/pull/281.
Using the type inspection for owner ref and the pattern for using resources dir to create the resources.

Flow resource creation comes from the resource dir.

---

config/400-flow-controller-config.yaml
pkg/controller/flow/provider.go
pkg/controller/flow/reconcile.go
pkg/controller/flow/reconcile_test.go

Add configmap for flow controller

---

config/config-logging.yaml
pkg/logconfig/config.go
test/e2e-tests.sh

I saw an issue in the e2e test run where the script fails because it can't find the pod with the "controller-manager" name. We removed that in https://github.com/knative/eventing/pull/313

Fix e2e test after removal of controller manager.

---

pkg/sources/github/README.md
pkg/sources/github/events.go
pkg/sources/github/eventsource.yaml
pkg/sources/github/eventtype.yaml
pkg/sources/github/feedlet/feedlet.go
pkg/sources/github/receive_adapter/receive_adapter.go
sample/github/legit.go

This is a followup to #276. The focus is to migrate the Source and Sample to use the cloudevent naming style and the eventing framework.
Fixes https://github.com/knative/eventing/issues/334
Fixes https://github.com/knative/eventing/issues/332

Convert github source to cloud events.

---

pkg/apis/feeds/v1alpha1/cluster_event_source_defaults.go
pkg/apis/feeds/v1alpha1/cluster_event_source_types.go
pkg/apis/feeds/v1alpha1/cluster_event_source_validation.go
pkg/apis/feeds/v1alpha1/cluster_event_type_defaults.go
pkg/apis/feeds/v1alpha1/cluster_event_type_types.go
pkg/apis/feeds/v1alpha1/cluster_event_type_validation.go
pkg/apis/feeds/v1alpha1/common_event_source_defaults.go
pkg/apis/feeds/v1alpha1/common_event_source_types.go
pkg/apis/feeds/v1alpha1/common_event_source_validation.go
pkg/apis/feeds/v1alpha1/common_event_type_defaults.go
pkg/apis/feeds/v1alpha1/common_event_type_types.go
pkg/apis/feeds/v1alpha1/common_event_type_validation.go
pkg/apis/feeds/v1alpha1/event_source_defaults.go
pkg/apis/feeds/v1alpha1/event_source_types.go
pkg/apis/feeds/v1alpha1/event_source_validation.go
pkg/apis/feeds/v1alpha1/event_type_defaults.go
pkg/apis/feeds/v1alpha1/event_type_types.go
pkg/apis/feeds/v1alpha1/event_type_validation.go

This is the continued effort to stage the required methods for integration with pkg/webhook.
Note all these are REALLY just shells, there was no impl to copy over from the original webhook side.

Adding shell _default and _validation files for event type and source.

---

pkg/apis/channels/v1alpha1/subscription_types.go
pkg/buses/gcppubsub/bus.go
pkg/buses/kafka/dispatcher/dispatcher.go
pkg/buses/message.go
pkg/buses/message_dispatcher.go
pkg/buses/stub/main.go

Fixes #216
* Subscription now accepts an optional "replyTo" property
* Bus implementations pass the Subscription's replyTo property when delegating to the common dispatcher
* the dispatcher will forward a non-empty response body as a new request to the destination specified by the replyTo if present
* headers will be propagated, including a correlation ID header if provided in the request

add support for Subsciption.replyTo property

---

pkg/controller/feed/reconcile.go

This is a WIP update of the feed controller that adds `context.Context` parameters everywhere in preparation for #303. [EDIT: and #303 is in, yay!]
Still unclear is how the logger will get from `main` to the reconciler (possibly via `ProvideController`).
/cc @n3wscott

Reconcile with context

---

config/200-serviceaccount.yaml
config/201-clusterrolebinding.yaml
config/buses/gcppubsub/README.md
config/buses/kafka/README.md
config/buses/stub/README.md
pkg/controller/bus/controller.go
pkg/controller/channel/controller.go
pkg/controller/clusterbus/controller.go
pkg/controller/names.go

Buses can create dispatcher and provision deployments. Previously, these
deployments were created in the same namespace as the Bus resource,
which required RBAC rules to be configured to enable the deployments to
read and update Bus, Channel and Subscription resources.
By moving these deployments into the knative-eventing system namespace,
we can use a pre-determined service account and RBAC configuration.
Since the bus-controller no longer needs to create service accounts and
role bindings, the controller can run with reduced privillage (follow
#207 for that change).
Fixes #349
```release-note
Bus provisioner and dispatcher deployments are now created in the knative-eventing namespace instead of the Bus's namespace. ClusterBuses are not impacted as they already run in …
```

Move bus deployments to knative-eventing

---

pkg/sources/gcppubsub/gcp_pubsub.go
pkg/sources/k8sevents/k8s_events.go

Cleaning up based on https://goreportcard.com/report/github.com/knative/eventing#ineffassign
```release-note
NONE
```

We never used the err from uuid.NewRandom.

---

test/e2e-tests.sh

The changes will allow it to run on MacOS X which has an older bash

Update e2e-test.sh to be portable

---

pkg/sources/gcppubsub/eventsource.yaml
pkg/sources/k8sevents/eventsource.yaml

The validation webhooks are now doing strict json mapping and the current sources for k8s events and gcp pub/sub have an extra field called "type" on source that does not map into the real resource.
```release-note
Updated sources k8sevents and gcppubsub to be a valid source yaml.
```

Type is not a field on source. Removed.

---

pkg/sources/github/feedlet/feedlet.go

The logic is inverted when we are checking for existence of
FEED_NAMESPACE and other env vars in the gihub source feedlet - we are
asserting len != 0 rather than len == 0.
```release-note
```

Fix env var len check in gh feedlet

---

pkg/sources/github/feedlet/feedlet.go

Github webhooks are requires to be named "web" or the name of a valid
service:
https://developer.github.com/v3/repos/hooks/#create-a-hook
```release-note
```

Fix github source to use valid webhook name

---

pkg/sources/github/receive_adapter/receive_adapter.go

Stop editing the `logtostderr` flag.
```release-note
NONE
```

Found panic on missing flag modification. glog no longer used.

---

pkg/controller/feed/reconcile_test.go
pkg/controller/feed/resources/job.go

Istio needs to be told not to inject the sidecar for feedlet jobs.
```release-note
Feedlet jobs are now annotated with istio `sidecar.istio.io/inject:false`.
```

Don't inject the istio sidecar and fix the tests related.

---

OWNERS

At her request.
EDIT: This change is intended to stop Prow from auto-suggesting her as an approver, rather than imply a lack of approval rights.
/cc @ultrasaurus @evankanderson @vaikas-google @inlined @n3wscott

Remove ultrasaurus from approvers

---

cmd/controller/main.go
pkg/buses/gcppubsub/dispatcher/main.go
pkg/buses/gcppubsub/provisioner/main.go
pkg/buses/kafka/provisioner/provisioner.go
pkg/buses/monitor.go
pkg/buses/stub/main.go
pkg/controller/bus/controller.go
pkg/controller/channel/controller.go
pkg/controller/clusterbus/controller.go
pkg/sources/gcppubsub/gcp_pubsub.go
pkg/sources/k8sevents/k8s_events.go
pkg/sources/k8sevents/receive_adapter/receive_adapter.go

Fixes #331
* Refactor error logging and printing to use `"%v", err`
```release-note
NONE
```

prefer %v err over %s err.Erorr()

---

OWNERS

From [ROLES.md](https://github.com/knative/docs/blob/1b52510c44168a99efe6179c523cd68bdac1e07b/community/ROLES.md):
> Reviewer of the codebase for at least 3 months or 50% of project lifetime, whichever is shorter
Total project lifetime: 182 days (2018-03-12 to 2018-08-21)
50% of project lifetime: 91 days
**Earliest review: 2018-05-29, 84 days ago**
https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Agrantr+sort%3Acreated-asc
> Primary reviewer for at least 10 substantial PRs to the codebase
**Reviewed 23 L, XL, or XXL PRs**
https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Agrantr+label%3Asize%2FL
https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Agrantr+label%3Asize%2FXL …

Add grantr to list of approvers

---

pkg/apis/flows/v1alpha1/flow_defaults.go
pkg/apis/flows/v1alpha1/flow_types.go
pkg/apis/flows/v1alpha1/flow_validation.go
pkg/apis/flows/v1alpha1/flow_validation_test.go

Follow-up to https://github.com/knative/eventing/pull/352
* Follow the comments provided in FlowSpec, checking fields and throwing errors as needed.
```release-note
Flows are validated on create and modify.
```

Validate flow as told in the flow spec comments.

---

pkg/apis/feeds/v1alpha1/cluster_event_source_defaults.go
pkg/apis/feeds/v1alpha1/cluster_event_source_types.go
pkg/apis/feeds/v1alpha1/cluster_event_source_validation.go
pkg/apis/feeds/v1alpha1/common_event_source_defaults.go
pkg/apis/feeds/v1alpha1/common_event_source_validation.go
pkg/apis/feeds/v1alpha1/event_source_defaults.go
pkg/apis/feeds/v1alpha1/event_source_types.go
pkg/apis/feeds/v1alpha1/event_source_validation.go

Follow-up to: #352
* Remove TODOs for [Cluster]EventSource validation, nothing to do.
```release-note
NONE
```

Nothing to validate with event sources. Removing todos.

---

pkg/buses/stub/bus.go

If we encounter an error when dispatching an event in the stub bus we
silently ignore it. Lets log the error instead.
```release-note
NONE
```

Log dispatch errors in stub bus

---

Gopkg.lock
vendor/github.com/knative/test-infra/scripts/library.sh
vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh

Includes:
* fixes to `library.sh` in order to have some `hack` scripts working again;
* better checking of PRs where presubmit tests are unnecessary;

Update test-infra dependency

---

config/buses/kafka/broker/kafka-broker.yaml

* Removes the node port number specified in the `kafka-broker.yaml`
Specifying the node port number can result in port collisions.
```release-note
```

Do not specify node port number for kafka broker

---

config/buses/gcppubsub/README.md
config/buses/kafka/README.md

Addresses concern in #424 but this warrants a better fix as mentioned in the issue.
* Update Kafka/GCP PubSub docs to create config-map/secrets in the knative-eventing namespace
```release-note
```

Update Bus README's with correct namespace

---

pkg/buses/cache.go
pkg/buses/cache_test.go
pkg/buses/reconciler.go

Fixes #392
*  When parameters for a bus are updated we need to reprovision and
resubscribe all channels for that bus.
```release-note
NONE
```

Reprovision channels and resubscrube when a bus params are updated

---

pkg/buses/message_dispatcher.go

If a subscriber or reply request returns a non-2xx status code, the
message dispatcher should treat that response as an error. This allows
the bus to Nack delivery of the message for the subscribtion so that it
can be retried, assuming the bus is durable.
This behavior is important for message durability as right now messages
are dropped if the Subscriber returns an error. It's not uncommon to 
receive an error from Knative Serving when a function is scaling from zero
to one, and a retried request will succeed.
Fixes #432 
* all non HTTP 2xx responses from the message dispatcher will result in error
```release-note
NONE
```

Reject non-successful (2xx) dispatch responses

---

pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go
pkg/apis/eventing/v1alpha1/subscription_types.go

Relates to https://github.com/knative/eventing/pull/434
* Adding GetCondition on ClusterProvisionerStatus
* Adding `patchStrategy:"merge"` to `ClusterProvisionerStatus.Conditions`
```release-note
None
```

Adding GetCondition and patch merge to ClusterProvisionerStatus

---

OWNERS

This repo has sufficient OWNERS coverage now that I am generally not needed for `/approve`s.  Trying to reduce the noise :)

Remove mattmoor from eventing OWNERS.

---

pkg/apis/eventing/v1alpha1/subscription_types.go
pkg/apis/eventing/v1alpha1/subscription_types_test.go
pkg/controller/eventing/subscription/reconcile.go
pkg/controller/eventing/subscription/reconcile_test.go
pkg/controller/testing/table.go

Followup tweaks to #437 as suggested by @n3wscott:
- Add `IsReady` and `Mark*` functions to manage conditions easily
- Remove `GetSpecJSON` and use `duck.Generation` instead

Subscription controller tweaks

---

config/300-source.yaml

A typo here makes sources impossible to create because the webhook
expects them to be called Source.

Source kind should be singular in CRD spec

---

Gopkg.lock
Gopkg.toml
pkg/apis/eventing/v1alpha1/channel_types.go
pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go
pkg/apis/eventing/v1alpha1/implements_test.go
pkg/apis/eventing/v1alpha1/subscription_types.go
vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
vendor/github.com/knative/pkg/apis/duck/v1alpha1/targetable_types.go
vendor/github.com/knative/pkg/apis/duck/verify.go
vendor/github.com/knative/pkg/webhook/webhook.go

This is part of knative/pkg#97 (not closing it as there will be PRs on `serving`, `eventing` and `build` to follow :wink:)
Those calls to `duck.VerifyType` are done at runtime and thus could be
costly at program startup. Putting them under tests ensure we still
assert those types but during unit testing.
This bumps `knative/pkg` to today's master 
cc @dprotaso @mattmoor

Move the use of `VerifyType` in tests

---

config/buses/gcppubsub/README.md
config/buses/kafka/README.md

* Minor fix to instructions for installing Kafka Cluster Bus. Edits ConfigMap to set default Cluster Bus to Kafka
```release-note
NONE
```

Added instructions for setting default cluster-bus

---

sample/README.md

Fixes #506
* remove unneeded instructions for samples, those have been moved out
* just link to the actual sample on the `docs` repo

Just point to the docs repo for being the best sample source

---

pkg/apis/eventing/v1alpha1/channel_types.go
pkg/apis/eventing/v1alpha1/channel_types_test.go

Add Channel Status methods `InitializeConditions`, `IsReady` and `MarkProvisioned`
Based on feedback in https://github.com/knative/eventing/pull/515#issuecomment-428976684

Add channelstatus methods

---

test/cleanup.go
test/clients.go
test/e2e/e2e.go

Fixes #431
* Use a generic version of Cleanup that deletes resources in reverse order and can wait for the deletion before deleting the next resource
* This will be re-usable by knative/serving as well (removing Delete method from Clients)
* The next step would be to push the cleanup.go file to knative/pkg repo and when it's integrated, re-use that by knative/eventing and knative/serving test suites

Re-useable cleaner of test resources

---

pkg/apis/eventing/v1alpha1/subscribable_channelable_validation.go
pkg/apis/eventing/v1alpha1/subscription_validation_test.go
pkg/controller/eventing/subscription/reconcile_test.go

* Do not allow Source in Subscription.From
```release-note
Disallow Source references in Subscription.From, as per meeting today to move forward with the Strict Channels model.
```

Strict channels subscription

---

CONTRIBUTING.md

`/hold` did not work because of the text after.

Folllow-up to change wording of contrib text.

---

test/e2e-tests.sh

* Log `Tagging my-image:tag@sha256:xxx` instead of `Tagging my-image:tag:sha256:xxx` (which is invalid)
The test does the right thing, it just logs that it's doing a wrong thing.
```release-note
NONE
```

Fix logging typo in e2e-tests.sh

---

hack/verify-codegen.sh

`verify-codegen.sh` now ensures `third_party/VENDOR-LICENSE`, `Gopkg.lock` and the `/vendor` folder don't change

check the VENDOR-LICENSE, Gopkg.lock and vendor as part of verification

---

config/provisioners/in-memory-channel/README.md

s/providers/provisioners/
remove extra ref in the spec in the example.

fix typo in the path name

---

pkg/controller/eventing/inmemory/channel/reconcile.go

If a channel has no subscribers, it should still be in the configmap. This allows the dispatcher to respond with a 202 to a publish request (then drop the published event).
```release-note
In-memory channels with no subscribers now respond to publishes with the same status code.
```
/cc @adamharwayne

Add Channels with no subscribers to config map

---

pkg/apis/eventing/v1alpha1/subscription_types.go
pkg/apis/eventing/v1alpha1/subscription_validation.go
pkg/apis/eventing/v1alpha1/subscription_validation_test.go

* Change the json name from target to channel, to match the Go struct name modified in #563.
```release-note
NONE
```

target -> channel

---

pkg/apis/eventing/v1alpha1/subscription_types.go
pkg/apis/eventing/v1alpha1/subscription_types_test.go
pkg/controller/eventing/subscription/reconcile.go

* Rename `Subscription`'s `fromReady` status condition to `channelReady`, to reflect the change in field name in #563.
```release-note
NONE
```

Rename fromReady to channelReady, to reflect the change in field name in #563

---

pkg/controller/eventing/subscription/reconcile.go
pkg/controller/eventing/subscription/reconcile_test.go

* Only operate on non-nil _and_ _non-empty_ `subscriber` and `reply` fields.
- Only checking non-nil allows panics (which is how I found #574).
```release-note
NONE
```

Make the subscription controller resilient to empty subscriber and reply fields

---

.gitattributes

Fixes #587 
* Exclude /test and /vendor from test coverage
*
*
```release-note
Exclude /test and /vendor from test coverage.
```

Exclude test and vendor from coverage. now matches serving

---

pkg/apis/eventing/v1alpha1/register_test.go

Addresses #591 
* Add unit tests for pkg/eventing/v1alpha1/register.go

Add tests for eventing/v1alpha1/register.go

---

config/provisioners/in-memory-channel/in-memory-channel.yaml

The in-memory channel controller is not able to provision a channel without this role:
```
{"level":"info","ts":"2018-11-09T08:08:58.209Z","logger":"bus","caller":"channel/reconcile.go:142","msg":"Error creating the Channel's K8s Service","eventing.knative.dev/clusterChannelProvisioner":"in-memory-channel","eventing.knative.dev/clusterChannelProvisionerComponent":"Controller","channel":{"metadata":{"name":"foo","namespace":"myproject","selfLink":"/apis/eventing.knative.dev/v1alpha1/namespaces/myproject/channels/foo","uid":"a516c9c5-e3f6-11e8-a78f-52540061a142","resourceVersion":"140036","generation":1,"creationTimestamp":"2018-11-09T08:08:30Z","finalizers":["in-memory-channel-controller"]},"spec":{"generation":1,"provisioner":{"kind":"ClusterChannelProvisioner","name":"in-memory-channel"," …
```

Fix in-memory channel RBAC role

---

hack/release.sh

Expand the array of yaml files into a single string, not separate strings.
Fixes #610

Fix passing yamls to hub tool

---

hack/release.sh

Without this change, running the release multiple times causes the content to be duplicated in the release yaml.
Fixes #612
* Echo the empty string to each release yaml before appending to it
```release-note
NONE
```
/cc @matzew @scothis @adrcunha

Clear release yaml before appending to it

---

.gitattributes

Mirrors the exclusion in knative/serving (which was last updated in https://github.com/knative/serving/pull/1779).
See #591 
* Exclude `pkg/**/testing/**` from coverage. Current includes `pkg/controller/testing/mock_client.go` and `pkg/controller/testing/table.go`.
```release-note
NONE
```

Exclude code in testing/ dirs from coverage

---

pkg/controller/eventing/subscription/provider_test.go
pkg/provisioners/kafka/controller/channel/provider_test.go
pkg/provisioners/kafka/controller/provider_test.go

Adds some tests for `Inject*` methods. `ProvideController` methods can't be tested without a fake manager.
See #591 
/cc @Harwayne

Provider tests

---

pkg/controller/eventing/subscription/reconcile.go

* Subscription controller should only update the channel with the list of subscribers in the same namespace. 
* Also fixes an issue when a subscription could not be deleted if the channel is already deleted (stumbled upon this while testing the above issue)
```release-note
```

Update channel only with subscribers in the same namespace

---

config/300-clusterchannelprovisioner.yaml

Minor change
* adding a `provisioner` category for the ClustrChannelProvisioners (see #571) 
/cc @scothis

Adding provisioner category for the ccp

---

config/provisioners/kafka/README.md
config/provisioners/kafka/kafka.yaml
hack/release.sh
pkg/provisioners/kafka/controller/channel/reconcile_test.go
pkg/provisioners/kafka/controller/reconcile.go
pkg/provisioners/kafka/controller/reconcile_test.go

Fixes not that great naming :-) for Kafka
* remove the `-channel` part of out the `kafka` ClusterChannelProvisioner, just name it `kafka`
cc @Harwayne @neosab @grantr 
NOTE: Kafka was not released, so a rename here is safe ...

Removing the -channel from the kafka ccp

---

pkg/provisioners/kafka/controller/channel/reconcile.go
pkg/provisioners/kafka/controller/channel/reconcile_test.go
pkg/provisioners/kafka/controller/util.go
pkg/provisioners/kafka/dispatcher/dispatcher.go
pkg/provisioners/kafka/dispatcher/dispatcher_test.go
pkg/provisioners/provisioner_util.go
pkg/provisioners/utils/topic_names.go
pkg/provisioners/utils/topic_names_test.go

* create `TopicName` util and remove duplicated code
* adding some better prefix of the actual kafka topics
//cc @Harwayne @neosab 
This is a bit inspired by a discussion on the GCP PUB/SUB PR:
* https://github.com/knative/eventing/pull/618/files#r235173725
* https://github.com/knative/eventing/pull/618/files#r235173995
This also adds better, identified topic names, IMO.
Also, if merged , I think the PR on PUB/SUB from @Harwayne can reuse this

extracting TopicName as util function

---

Gopkg.lock
vendor/github.com/knative/test-infra/scripts/README.md
vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
vendor/github.com/knative/test-infra/scripts/library.sh
vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
vendor/github.com/knative/test-infra/scripts/release.sh
vendor/github.com/knative/test-infra/tools/dep-collector/imports.go

Old images cleanup is no longer part of e2e test, this functionality will be moved to a separate job runs periodically.
* This part is done in knative/test-infra, updating dependencies in this repo to include this update.
Link to the issue in test-infra: knative/test-infra#276

Remove images deletion step from e2e test

---

test/crd.go
test/e2e-tests.sh

Fixes Istio sidecar injection into the test pod on OpenShift.
* Make Istio sidcar injection explicit. Similar to main knative components which declare the annotation.

Explicit Istio sidecar injection for the nginx test pod

---

pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile.go
pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile_test.go
pkg/provisioners/kafka/controller/reconcile.go
pkg/provisioners/kafka/controller/reconcile_test.go

Fixes #649
* Sets the reconcile request's namespace to an empty string as in a certain case it contains the namespace of the owned object. More details in the issue #649.
```release-note
```

Fix CCP reconcile issue with owned objects

---

pkg/controller/eventing/subscription/reconcile_test.go
pkg/controller/testing/builder.go
pkg/controller/testing/table.go

The existing fixture builders in the Subscription reconciler tests aren't terrible, but they don't compose well. Every case needs its own fixture method like `getNewSubscriptionWithReferencesResolvedAndPhysicalReplyAndNoSubscriber`.
@dprotaso experimented with builders in https://github.com/knative/serving/pull/1762 and https://github.com/knative/serving/pull/1924, but apparently moved on to other things before getting to a satisfactory state.
This is my attempt at a builder interface satisfying the following:
- minimal code for both framework and test authors to write and understand
- Flexible for test authors to define their own builder function signatures
- No runtime typing (more than what's already used by the controller-runtime client)
- As clear (or clearer) to read as the existing …

Fixture builders for Subscription reconcile tests

---

pkg/provisioners/channel_util.go
pkg/provisioners/channel_util_test.go
pkg/provisioners/kafka/controller/channel/reconcile.go
pkg/provisioners/kafka/controller/channel/reconcile_test.go

A possible fix for #643 (for the Kafka provisioner anyway).
* util.AddFinalizer returns whether or not a finalizer was added.
* The Kafka provisioner's first reconcile loop will only add the finalizer, _not_ manipulate Kafka. It returns result with `Requeue: true`, which causes the next reconcile to occur immediately and that reconcile manipulates Kafka.
```release-note
NONE
```

Kafka provisioner persists its finalizer before manipulating Kafka

---

CODE_OF_CONDUCT.md
DEVELOPMENT.md
README.md
config/provisioners/gcppubsub/README.md
config/provisioners/in-memory-channel/README.md
config/provisioners/kafka/README.md
config/provisioners/kafka/broker/README.md
docs/personas.md
docs/spec/README.md
docs/spec/interfaces.md
docs/spec/motivation.md
docs/spec/overview.md
docs/spec/spec.md
hack/README.md
hack/release.md
roadmap.md
sample/README.md
test/README.md
test/e2e/README.md

Produced via: `prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`

Format markdown

---

pkg/provisioners/gcppubsub/controller/channel/reconcile.go
pkg/provisioners/gcppubsub/controller/channel/reconcile_test.go
pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile.go
pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile_test.go

Working on #643.
- Persist the finalizer before manipulating GCP PubSub.
```release-note
NONE
```

GCP PubSub controller persists its finalizer before manipulating anything outside of the cluster

---

config/provisioners/gcppubsub/gcppubsub.yaml
pkg/provisioners/channel_util.go
pkg/provisioners/channel_util_test.go
pkg/provisioners/provisioner_util.go

This is a follow up of sorts on #626, which did this for `VirtualServices` and the Dispatcher's K8s `Service`.
- `CreateK8sService` diffs against any found K8s `Service` and updates it if the spec is different than expected.
```release-note
When updating the provisioner controllers, you will also need to update the RBAC for their Service Accounts.
```

CreateK8sService diffs its expected spec against the actual spec and updates the K8s Service appropriately

---

test/e2e-tests.sh

Trying to unblock tests while we track down the failure in sources.

Pin sources release to last known good

---

pkg/provisioners/natss/controller/channel/reconcile_test.go
pkg/provisioners/natss/dispatcher/dispatcher/dispatcher.go
pkg/provisioners/natss/dispatcher/main.go
pkg/provisioners/natss/stanutil/stanutil.go

Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`

golang format tools

---

pkg/controller/eventing/subscription/reconcile.go
pkg/controller/eventing/subscription/reconcile_test.go

Fixes #673
-Adds an additional fallback in target resolution
```release-note
* Fixes Subscription compatibility between and knative 0.2.0 and earlier (fixed in 0.2.1).
```

Fallback to `status.domainInternal` if not `Addressable`

---

config/201-clusterrolebinding.yaml
config/provisioners/gcppubsub/gcppubsub.yaml
config/provisioners/in-memory-channel/in-memory-channel.yaml
config/provisioners/kafka/kafka.yaml
config/provisioners/natss/provisioner.yaml

Since RBAC went into GA in 1.8 and we are in 1.13 now, it makes sense to start using v1 for `ClusterRoleBinding` object in yaml files.
```release-note
None
```

Switching rbac from betav1 to v1

---

pkg/controller/eventing/inmemory/channel/reconcile_test.go
pkg/provisioners/channel_util.go
pkg/provisioners/channel_util_test.go

Consistent labels for channel and provisioner

---

config/300-channel.yaml
config/300-clusterchannelprovisioner.yaml
config/300-subscription.yaml
config/provisioners/gcppubsub/gcppubsub.yaml
config/provisioners/in-memory-channel/in-memory-channel.yaml
config/provisioners/kafka/kafka.yaml
config/provisioners/natss/provisioner.yaml
pkg/apis/eventing/v1alpha1/channel_types.go
pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
pkg/apis/eventing/v1alpha1/subscription_types.go
pkg/client/clientset/versioned/typed/eventing/v1alpha1/channel.go
pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_channel.go
pkg/controller/eventing/inmemory/channel/reconcile_test.go
pkg/controller/eventing/subscription/reconcile.go
pkg/controller/testing/mock_client.go
pkg/provisioners/channel_util.go
pkg/provisioners/gcppubsub/controller/channel/reconcile_test.go
pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile_test.go

I've enabled it on all CRDs so that the metadata.generation will start to be
incremented by the Kubernetes API server
Fixes #697 
```release-note
Status Subresource has been enabled on the eventing CRDs. Thus if you're a contributor creating custom channels you'll need to use the appropriate /status endpoint when updating a channel's status
```

Enable status subresource eventing CRDs

---

pkg/provisioners/message.go
pkg/provisioners/message_receiver.go
pkg/provisioners/message_receiver_test.go
pkg/provisioners/message_test.go

Fixes #638 
- Added a Knative-Message-History header containing information about the channels traversed by the message
History is made of composite objects, so I've not found a way to serialize it into a header better than JSON (open for discussion). For possible future enhancements, I've used Kubernetes ObjectReference as base type for a history item.
```release-note
Messages contain information about the history of traversed channels in a header
```

Fix #638: add message history into header

---

pkg/apis/eventing/v1alpha1/channel_types.go
pkg/controller/names.go
pkg/provisioners/channel_util.go
pkg/provisioners/message_dispatcher.go
pkg/provisioners/natss/controller/clusterchannelprovisioner/controller.go
pkg/provisioners/natss/dispatcher/main.go
pkg/utils/utils.go
pkg/utils/utils_test.go

Fixes #714
```release-note
removes hardcoded cluster.local, the search of dns resolver should be able to figure out actual dns name.
```

replacing references to cluster.local with actual cluster's domain name

---

pkg/controller/eventing/subscription/reconcile.go
pkg/controller/eventing/subscription/reconcile_test.go

- Subscription controller removes subscriber and reply from the status if they are removed from the spec
```release-note
NONE
```

Subscription controller removes subscriber and reply from the status if they are removed from the spec

---

hack/release.sh

Adding the natss cluster channel provisioners (and staging gcp-pubsub)
to the release script as components. This will publish images and yaml
for the CCP with each nightly and tagged release.
This will not include the provisioners in the release.yaml, which only
includes the in-memory-channel CCP.
- publish natss CCP as a component, but leave out of release.yaml
- stage publishing of gap-pubsub CPP as a component
```release-note
The NATSS ClusterChannelProvisioner is available in the natss.yaml file, it is not included in the release.yaml and must be applied independently.
```

Publish components for channel provisioners

---

config/300-channel.yaml
config/300-clusterchannelprovisioner.yaml
config/300-subscription.yaml

Fixes #642 
- Adding additional printer columns (Ready and Reason) to CustomResourceDefinitions
```release-note
NONE
```

Add custom columns for eventing resources

---

config/provisioners/gcppubsub/gcppubsub.yaml
pkg/apis/eventing/v1alpha1/channel_types.go
pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
pkg/provisioners/gcppubsub/controller/channel/names.go
pkg/provisioners/gcppubsub/controller/channel/names_test.go
pkg/provisioners/gcppubsub/controller/channel/reconcile.go
pkg/provisioners/gcppubsub/controller/channel/reconcile_test.go
pkg/provisioners/gcppubsub/controller/clusterchannelprovisioner/reconcile.go
pkg/provisioners/gcppubsub/dispatcher/cmd/main.go
pkg/provisioners/gcppubsub/dispatcher/dispatcher/controller.go
pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile.go
pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile_test.go
pkg/provisioners/gcppubsub/dispatcher/receiver/receiver.go
pkg/provisioners/gcppubsub/dispatcher/receiver/receiver_test.go
pkg/provisioners/gcppubsub/util/creds.go
pkg/provisioners/gcppubsub/util/creds_test.go
pkg/provisioners/gcppubsub/util/logging/logging.go
pkg/provisioners/gcppubsub/util/pubsub_wrapper.go
pkg/provisioners/gcppubsub/util/status.go
pkg/provisioners/gcppubsub/util/status_test.go
pkg/provisioners/provisioner_util_test.go
pkg/provisioners/utils/topic_names.go
pkg/provisioners/utils/topic_names_test.go

Fixes #253 
- Add `status.internal` to Channels that allows each `ClusterChannelProvisioner` to store unique information. This is analogous to Channel's `spec.arguments`.
- GCP PubSub channel uses this raw status to save the Subscription and Topic names. The controller generates the names, creates the GCP resources, and saves the names to `status.internal`. Then the dispatcher uses the names from the status.
```release-note
Redeploy the Channel CRD to add the new field.
```

Add status.internal to Channels

---

test/upload-test-images.sh

Follow https://github.com/knative/serving/issues/2715
- Push test-images using just their basepath (that is: The folder they're located in, for example timeout). That makes the upload script compatible with Dockerhub.
- Actually default --dockerrepo to DOCKER_REPO_OVERRIDE as the readmes say.

update upload-test-images.sh to compatible with docker hub

---

config/provisioners/gcppubsub/README.md
config/provisioners/gcppubsub/gcppubsub.yaml
config/provisioners/in-memory-channel/in-memory-channel.yaml
contrib/kafka/config/README.md
contrib/kafka/config/kafka.yaml
contrib/natss/config/provisioner.yaml
pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile_test.go
pkg/provisioners/gcppubsub/controller/clusterchannelprovisioner/reconcile_test.go
pkg/provisioners/provisioner_util.go

Fixes #760 
- As of #699 ClusterChannelProvisioner's status is a subresource. This commit updates the system to write the status via client.Status().Update(...).
```release-note
The RBAC for ClusterChannelProvisioner Controllers will need to be updated.
```

Write CCP status via client.Status().Update

---

test/e2e/single_event_test.go
test/e2e_flags.go

Fixes #769 
- Add a flag to the e2e tests to use a custom ClusterChannelProvisioner.
Note: To use this locally I did the following:
```shell
export CLUSTER=<entry from ~/.kube/config file>
export NAMESPACE=<something random>
test/upload-test-images.sh e2e
go test -v -tags=e2e -count=1 ./test/e2e -dockerrepo=gcr.io/$PROJECT_ID -cluster=$CLUSTER -namespace=$NAMESPACE -clusterChannelProvisioner=kafka
```
```release-note
NONE
```

Add a flag to the e2e tests to use a custom ClusterChannelProvisioner.

---

README.md

I feel that the roadmap document is a bit hidden.  Therefore adding a more present link to the landing page of this repo
cc @evankanderson

adding link to roadmap

---

config/provisioners/in-memory-channel/in-memory-channel.yaml
pkg/controller/eventing/inmemory/channel/reconcile.go
pkg/controller/eventing/inmemory/channel/reconcile_test.go
pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile.go
pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile_test.go
pkg/controller/eventing/inmemory/controller/main.go
pkg/sidecar/fanout/fanout_handler.go
pkg/sidecar/fanout/fanout_handler_test.go
test/e2e-tests.sh

```release-note
This PR add support of async way of calling fanout handler and refactors in-memory-channel to support for both types, sync(old) and async(new)
```

refactor in-memory channel to support sync and async handlers

---

DEVELOPMENT.md

Someone installing Eventing from source doesn't get a
`ClusterChannelProvisioner` out of the box. So, add a note about
installing one in DEVELOPMENT.md.

Mention Channel provisioners in DEVELOPMENT.md

---

contrib/kafka/config/README.md

@Harwayne I think that this commit:
https://github.com/knative/eventing/commit/968e82fbf7843e95dc3ac425563e4d49276ab1cd#diff-b213c6bece8dad882117f26c39d41758L12
made the config part less readable.

make config snippet more readable

---

contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile_test.go
contrib/gcppubsub/pkg/dispatcher/receiver/receiver_test.go
contrib/kafka/pkg/controller/channel/reconcile_test.go
contrib/natss/pkg/controller/channel/reconcile_test.go
pkg/provisioners/channel_util_test.go
pkg/provisioners/inmemory/channel/reconcile_test.go
pkg/provisioners/message_receiver_test.go
pkg/reconciler/names/names_test.go
pkg/reconciler/v1alpha1/subscription/subscription_test.go
pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go
pkg/sidecar/configmap/parse_test.go
pkg/sidecar/multichannelfanout/parse_test.go

Some unit tests were using hard coded `cluster.local` domain name, this PR switches them to use `utils.GetClusterDomainName() instead`
```release-note
None
```

Clean up unit tests to use actual domain name

---

contrib/gcppubsub/config/gcppubsub.yaml
contrib/gcppubsub/pkg/controller/channel/reconcile.go
contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
contrib/gcppubsub/pkg/controller/clusterchannelprovisioner/reconcile.go
contrib/gcppubsub/pkg/controller/clusterchannelprovisioner/reconcile_test.go
contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile.go
contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile_test.go

Contributes to fix #724 
- Adding corev1.Events to GCP PubSub channel in order to make debugging easier.
- Adding verbs to create/update/patch events to the gcppubsub default configuration
- Here is the list of the events emitted:
Name | Type | Description
-- | -- | --
ChannelReadStatusFailed | Warning | When there was an error trying to get the internal status of the channel. Includes the go error string.
SubscriptionSyncFailed | Warning | When the Channel's subscription couldn't be synced. Includes the go error string.
SubscriptionDeleteFailed | Warning | When the old Channel's subscriptions couldn't be deleted. Includes the go error string.
GcpCredentialsReadFailed | Warning | When the GCP credentials couldn't be generated. Includes the go error string.
GcpResourcesPlanFailed | Warning …

Adding corev1.Events to GCP PubSub channel for easier debugging

---

test/e2e_flags.go

PR #725 removed paths from test image names, but the e2e tests were still generating image URLs using the previous longer paths. This updates them to be consistent.
Tests might still have passed if the older images were still compatible, but I doubt they got the most recent builds.
- Update test image URLs used in E2E tests.
```release-note
NONE
```
/cc @zxDiscovery

Use new test image names in E2E tests

---

contrib/gcppubsub/config/gcppubsub.yaml

- Adding create/update/patch verbs to emit v1 events.
- This was a bug introduced with a previous [PR](https://github.com/knative/eventing/pull/795)
```release-note
NONE
```

Adding verbs to emit corev1.Events to gcp-pubsub dispatcher.

---

Gopkg.lock
vendor/github.com/knative/test-infra/scripts/library.sh

continous and presubmit tests are failing due to release/yaml not found error, this is fixed in test-infra repo, update it here
Fixes #804

update deps:test-infra for fixing release.yaml not found error

---

config/100-namespace.yaml

- Opt `knative-eventing` into Istio injection (for those whose Istio is defaulted to opt-out).
```release-note
NONE
```

Opt knative-eventing into Istio injection 

---

config/400-default-channel-config.yaml

- Switch the default channel provisioner from 'in-memory-channel' to 'in-memory'
```release-note
NONE
```

Switch the default channel provisioner from 'in-memory-channel' to 'in-memory'

---

contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
contrib/natss/pkg/dispatcher/main.go
contrib/natss/pkg/stanutil/stanutil.go

xref #781 
```release-note
None
```

Restart dispatcher on connection loss

---

contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go

This PR switches to a non-blocking send over the re-connect channel.

Switch to a non blocking send

---

contrib/gcppubsub/config/gcppubsub.yaml
contrib/natss/config/provisioner.yaml

Fixes #711 
- Fix `env` indentation for `gcppubsub` and `natss` ClusterChannelProvisioners.
```release-note
* Allow `gcp-pubsub.yaml` and `natss.yaml` to be built and released. 
```

Fix `env` var indentation and grouping in contrib yamls

---

OWNERS

Note that I switched GitHub users from [adamharwayne](https://github.com/adamharwayne) to [Harwayne](https://github.com/Harwayne) and am counting contributions from both.
From [ROLES.md](https://github.com/knative/docs/blob/1b52510c44168a99efe6179c523cd68bdac1e07b/community/ROLES.md#approver):
> Reviewer of the codebase for at least 3 months or 50% of project lifetime, whichever is shorter
**Earliest review: 2018-08-02, more than 3 months ago**
https://github.com/knative/eventing/pull/308
> Primary reviewer for at least 10 substantial PRs to the codebase
**Reviewed 21 L, XL, or XXL PRs**
[adamharwayne size/L](https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+-author%3Aadamharwayne+reviewed-by%3Aadamharwayne+label%3Asize%2FL)
[adamharwayne …

Add Harwayne as an approver.

---

Gopkg.lock
cmd/fanoutsidecar/main.go
config/provisioners/in-memory-channel/in-memory-channel.yaml
contrib/kafka/cmd/dispatcher/main.go
contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
contrib/natss/pkg/dispatcher/main.go
pkg/utils/blocking_start.go
pkg/utils/blocking_start_test.go
test/cleanup.go
test/e2e/single_event_test.go

- `ConfigMapWatcher.Start()` blocks, rather than eagerly returning `nil`.
- This is needed before we can upgrade our version of Controller Runtime, because in the newer version any returns from `Start()`, including `nil`, will stop all the controllers added to that manager.
```release-note
NONE
```

ConfigMapWatcher.Start() blocks, rather than eagerly returning nil

---

contrib/kafka/pkg/controller/channel/reconcile.go
pkg/provisioners/channel_util.go
pkg/provisioners/inmemory/channel/reconcile.go
pkg/reconciler/v1alpha1/subscription/subscription.go

- Remove the fake ListOptions that were used exclusively for limitations in the fake client. #833 updated the fake client to remove the need for these options.
```release-note
NONE
```

Remove fake ListOptions

---

cmd/controller/main.go

Currently metrics starting log is not correctly formatted as:
```
$ kubectl  -n knative-eventing logs eventing-controller-756d56fc7-g64cd
...
{..snip.. msg":"Starting metrics listener at %s:9090","knative.dev/controller":"controller"}
```
(Please find `%s` in the message.)
This patch makes a tiny change to fix it by replacing `logger.Info`
with `logger.Infof`.
```release-note
NONE
```

Fix invalid log message format

---

config/500-controller.yaml

Although event controller opens 9090 port for metrics, there are
no information about the port except for start logs.
This patch clarify the port in Deployment to be easily noticed by
users.
```release-note
NONE
```

Inform controller's metrics port is 9090

---

contrib/kafka/config/README.md

- Fix invalid configmap name in REAME.md for kafka.
```release-note
NONE
```

Fix config map name for kafka channel dispatcher in README

---

contrib/kafka/cmd/dispatcher/main.go

Currently kafka-channel-dispatcher outputs `ERROR: logging before
flag.Parse` messages.
This patch changes to calls flag.Parse() when program started to fix
the issue.
- c.f.  currently channel dispatcher keeps producing following log messages.
```
$ kubectl  -n knative-eventing logs kafka-channel-dispatcher-0  -c dispatcher  -f
{"level":"info","ts":1551770419.020345,"caller":"provisioners/message_receiver.go:73","msg":"Starting web server"}
{"level":"info","ts":1551770578.578232,"caller":"dispatcher/dispatcher.go:93","msg":"Updating config (-old +new)","diff":"{*multichannelfanout.Config}.ChannelConfigs:\n\t-: []multichannelfanout.ChannelConfig(nil)\n\t+: []multichannelfanout.ChannelConfig{{Namespace: \"default\", Name: \"my-kafka-channel\"}}\n"}
ERROR: logging before flag.Parse: W0305 …
```

Fix flag parse error by calling flag.Parse from kafka channel dispatcher

---

config/provisioners/in-memory-channel/in-memory-channel.yaml

Surprised this passes kubectl's validation.

Remove namespace from cluster-scoped resources

---

README.md

People need to join knative-users to view the roadmap doc
Added note in README to make that clear

add instructions on how to view roadmap

---

pkg/reconciler/v1alpha1/subscription/subscription.go

This patch refactors by stop using `meta.Accessor()` as subscription has
`DeletionTimestamp` field.
Current code gets `deletionTimeStamp` via
`accessor.GetDeletionTimestamp()`, but the result is used just for log
outputs.
This patch refactors it.
```release-note
NONE
```

Use DeletionTimestamp field in subscription struct

---

contrib/kafka/pkg/controller/channel/reconcile.go
contrib/kafka/pkg/controller/reconcile.go

This patch refactors by stop using meta.Accessor as channel struct has
DeletionTimestamp field.
This PR is same refactoring with https://github.com/knative/eventing/pull/855, but for Kafka.
```release-note
NONE
```

Use DeletionTimestamp field in channel struct

---

cmd/controller/main.go
pkg/apis/eventing/v1alpha1/channel_types.go
pkg/apis/eventing/v1alpha1/channel_types_test.go
pkg/reconciler/v1alpha1/channel/channel.go
pkg/reconciler/v1alpha1/channel/channel_test.go

Fixes #779 
- Created a default channel controller. This controller will watch every Channel and set its ProvisionerInstalled condition to false if there is no provisioner that watches the channel
- This condition will be set to true by individual controllers when they start watching the Channel
- There were concerns about multiple controllers trying to update the status of the same object. However this is not a concern with the current implementation and it seems there are multiple cases in kubernetes where this is done.
The API server Update API support optimistic concurrency based on resource version. When using controller client to update, if the object on server side changes after reading the object and before updating it in the controller, then the update api will fail with CONFLICT …

Defaultcontroller

---

cmd/controller/main.go
cmd/webhook/main.go
config/500-controller.yaml
config/500-webhook.yaml
config/config-logging.yaml
pkg/logconfig/config.go

Fixes https://github.com/knative/serving/issues/3321
Just want use the unique `config-logging` name. So change the configmap `config-logging` to `eventing-config-logging`.

Distinguish config-logging

---

test/README.md

Fixes typo in `test/README.md`.

Fix typo in doc

---

pkg/provisioners/channel_util.go

- Allow {Add,Remove}Finalizers to work on all Objects, not just Channels.
This is being used in #788. Moving to a separate PR for ease of review.
```release-note
NONE
```

Allow {Add,Remove}Finalizers to work on all Objects, not just Channels.

---

pkg/reconciler/v1alpha1/subscription/subscription.go

- Make ResolveSubscriberSpec a public method, so that it can be called by other Controllers that need to do the same resolution logic.
This is being used in #788. Moving to a separate PR for ease of review.
```release-note
NONE
```

Make ResolveSubscriberSpec a public method

---

contrib/kafka/pkg/controller/channel/reconcile.go
contrib/kafka/pkg/controller/channel/reconcile_test.go

Fixes #863
- adding config for replica, instead hard coded to 1

Add replica config

---

contrib/kafka/config/kafka.yaml
contrib/kafka/pkg/controller/channel/reconcile.go
contrib/kafka/pkg/controller/channel/reconcile_test.go

Currently kafka channel controller keeps restarting if fails to build
admin client. Controller should try to reconcile without restart.
Having said that, users would like to notice the error easily. Hence
this patch introduces event logs for reconciler failures as well.
Fixes https://github.com/knative/eventing/issues/870
- Replace Fatal log inside reconcile with Error log.
- Produce event message from kafka channel controller
```release-note
NONE
```

Do not call Fatal log during reconciling of kafka channel controller

---

contrib/kafka/pkg/controller/channel/reconcile.go

This patch makes a tiny change by removing unnecessary printing
format `%s`.
- BFORE:
```
... msg":"successfully deleted topic %s","topic":"knative-eventing-channel.test-namespace.test-channel"}
```
- AFTER:
```
... "msg":"successfully deleted topic","topic":"knative-eventing-channel.test-namespace.test-channel"}
```
```release-note
NONE
```

Remove unnecessary printing format

---

contrib/kafka/cmd/controller/main.go

Since Kafka controller exits suddenly, program can not call
`logger.Sync()` and so it could lost log message sometimes.
This patch returns exit code to call `defer logger.Sync()` for sure.
Rref: https://godoc.org/go.uber.org/zap#Logger.Sync
> Sync calls the underlying Core's Sync method, flushing any buffered log entries. Applications should take care to call Sync before exiting. 
```release-note
NONE
```

Return exit code in kafka controller to call logger.Sync()

---

contrib/kafka/pkg/dispatcher/dispatcher.go

Fixes #620 
- unsubscribe/resubscribe for existing consumers upon fanout config update is quite discruptive for real time event processing and do not see a reason why this is needed
- propose to reuse the consumer and only subscribe when subscriber is not in the channel-subscriptions map  
```release-note
Changed old behavior for kafka channel that existing kafka consumers are stopped and resubscribed when fanout configs are updated, now kafka consumers are reused until corresponding subscription gets deleted.
```

do not unsubscribe for existing consumers upon config map update

---

pkg/reconciler/testing/mock_dynamic_client.go
pkg/reconciler/testing/table.go

- Table tests can mock dynamic client responses.
This functionality is needed for #788, after #883 got merged.
```release-note
NONE
```

Create a mock dynamic client.

---

test/presubmit-tests.sh

- Removes markdown linting in favor of the sockpuppet. #862 has hard tabs in the go code (as is appropriate for go code) referenced in the markdown file. prettier.io is fine with this and formats correctly. The linter does not. I see three ways forward:
- Replace tabs with spaces in the go code, requiring reformatting it when copy-pasting.
- Add MD10 to the set of exceptions, allowing a mix of tabs and spaces *everywhere* in markdown.
- Remove the linter that randomly breaks submits, where the error reporting is not clear about the problem, and adds extra human toil to comply (vs sockpuppet, which just adds toil to approve the fixups, which are very easy to review).

Remove markdown lint presubmit check in favor of the sockpuppet.

---

config/500-controller.yaml
config/500-webhook.yaml

We're seeing OOM issues at the Node level when we don't set the limit on some pods. This will allow the pod to restart gracefully w/o taking down the entire node.
I'm not stuck on the specific value so we can pick a different one.
See https://github.com/knative/serving/pull/3332 for the serving equivalent.
Signed-off-by: Doug Davis <dug@us.ibm.com>
```release-note
NONE
```

Set memory limits

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
DEVELOPMENT.md
README.md
docs/spec/README.md

Recent commits in the docs repo, https://github.com/knative/docs/commit/2205ab84e67955391f8ff7728ae97210240a9289 and https://github.com/knative/docs/commit/3c04f86ad7b7f937ae552a1b93eca97a5d312449, have resulted in broken links.

Fix broken links to docs repo

---

cmd/webhook/main.go
config/500-webhook.yaml
pkg/logconfig/config.go

Fixes #
User can specify webhook deployment name

User can specify webhook deployment name

---

DEVELOPMENT.md

`ko` is now at https://github.com/google/ko

Point to new ko repo

---

cmd/broker/ingress/main.go
pkg/broker/receiver.go

Some things that golint and govet caught in the new broker code:
- vet complained that `cancel()` wasn't being called properly for all return paths. I fixed the defer that was calling `ctx.Done()` instead of `cancel()`.
- lint complained about returning an unexported type from an exported function. I removed the function.
- link complained about `ceHttp` instead of `ceHTTP`. I renamed those fields.
/cc @Harwayne

Fix some broker vet and lint issues

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
DEVELOPMENT.md
README.md
docs/spec/README.md
sample/README.md

Work towards fixing https://github.com/knative/docs/issues/1038
* Updates all links in the Eventing repo that began with github.com/knative/docs
* Most links updated to point to the content on knative.dev, but kept the link to the samples pointing to the new location of the samples folder on Github

Updating links to docs repo

---

pkg/broker/context.go
pkg/broker/receiver_test.go

- Passthrough the header `b3` to match https://github.com/openzipkin/b3-propagation#single-header.
```release-note
NONE
```

Passthrough the header 'b3'

---

docs/broker/README.md

- Update docs to reflect #917.
```release-note
NONE
```

Update docs to reflect #917.

---

contrib/natss/config/README.md
contrib/natss/pkg/controller/clusterchannelprovisioner/controller.go
contrib/natss/pkg/controller/main.go
contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
contrib/natss/pkg/dispatcher/main.go
contrib/natss/pkg/util/util.go

- Optionally configure the natss url and cluster id using the environment variables `DEFAULT_NATSS_URL` and `DEFAULT_CLUSTER_ID`.
- Update README.md to include documentation on new options as well as properties of the channel.
Note that the environment variables are named similarly to the gcp provisioner. I assume they're named with the prefix `DEFAULT` in case channels can be optionally configured with arguments in the future.
Test Plan: `go test ./...`
```release-note
Add DEFAULT_NATSS_URL and DEFAULT_CLUSTER_ID configuration to NATS provisioner
```

Configure natss url and cluster id via the environment

---

pkg/apis/eventing/v1alpha1/broker_types.go
pkg/apis/eventing/v1alpha1/trigger_types.go

Fixes #938 
- Remove DeprecatedGeneration from Broker / Trigger. This unnecessarily adds future tech debt because no releases have been made with these, so let's remove them asap.
```release-note
Remove DeprecatedGeneration from Broker / Trigger
```

remove the DeprecatedGeneration from Trigger/Broker

---

contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go

- Log event headers instead of data in natss dispatcher as a security mitigation
```release-note
NONE
```

Log event headers instead of data

---

config/201-clusterrolebinding.yaml

- Rename the ClusterRoleBindings, as they no longer give admin privileges.
```release-note
Manually delete the old `eventing-controller-admin` ClusterRoleBinding.
```

Rename the ClusterRoleBindings, as they no longer give admin privileges.

---

docs/broker/README.md
docs/broker/example_triggers.yaml
pkg/apis/eventing/v1alpha1/trigger_types.go
pkg/broker/receiver_test.go
test/e2e/broker_trigger_test.go

Fixes #968.
- Change the special value representing 'allow all events' from 'Any' to the empty string
```release-note
Any existing Triggers with 'Any' will need to be updated to the empty string instead.
```

Change the special value representing 'allow all events' from 'Any' to the empty string

---

Gopkg.lock
Gopkg.toml
config/200-webhook-clusterrole.yaml
vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
vendor/github.com/knative/pkg/apis/field_error.go
vendor/github.com/knative/pkg/test/ingress/ingress.go
vendor/github.com/knative/pkg/test/kube_checks.go
vendor/github.com/knative/pkg/test/spoof/spoof.go
vendor/github.com/knative/pkg/webhook/webhook.go

Fixes #984 
- We changed the knative/pkg/webhook to use apps.deployments instead extensions.deployments, so change the rbac rule to talk about that.
- remove create verb for knative/eventing resources
```release-note
knative-eventing-webhook uses apps.deployment
knative-eventing-webhook does not have create rule anymore for eventing.knative.dev resources.
```

Change webhook rbac permission to use apps.deployments instead of extensions.deployments. Remove create for eventing.knative.dev resources

---

config/300-broker.yaml
config/300-trigger.yaml

Fixes #894
- Add OpenAPI schema to Broker and Trigger.
```release-note
NONE
```

Add OpenAPI schema to Broker and Trigger.

---

pkg/apis/eventing/v1alpha1/channel_validation_test.go
pkg/apis/eventing/v1alpha1/subscription_types.go
pkg/apis/eventing/v1alpha1/subscription_validation.go
pkg/apis/eventing/v1alpha1/subscription_validation_test.go
pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
pkg/reconciler/v1alpha1/broker/broker_test.go
pkg/utils/resolve/subscriber.go
pkg/utils/resolve/subscriber_test.go

Fixes #991
- Create `subscriber.uri` and deprecate `subscriber.dnsName`.
- The fields have identical semantics, both are used as a URI. We are simply giving the field the proper name. 
- #993 - In the following release, we will remove the deprecated `subscriber.dnsName` field.
```release-note
Switch from using subscriber.dnsName to subscriber.uri. subscriber.dnsName will be removed in the next release.
```

Create subscriber.uri and deprecate subscriber.dnsName

---

config/300-trigger.yaml

- Add subscriber.uri to Trigger's OpenAPI schema, to match #994.
```release-note
NONE
```

Add subscriber.uri to Trigger's OpenAPI schema, to match #994.

---

config/300-broker.yaml
config/300-channel.yaml
config/300-clusterchannelprovisioner.yaml
config/300-subscription.yaml
config/300-trigger.yaml

- Label CRDs so that they can be installed first with `kubectl -l knative.dev/crd-install=true YAML_FILE`
```release-note
- CRDs are now labelled with knative.dev/crd-install=true to allow installing without race conditions or kubectl errors.
```

Add a label knative.dev/crd-install to CRDs to allow installing CRDs in a separate pass.

---

pkg/reconciler/v1alpha1/trigger/resources/labels.go
pkg/reconciler/v1alpha1/trigger/resources/service.go
pkg/reconciler/v1alpha1/trigger/resources/subscription.go
pkg/reconciler/v1alpha1/trigger/resources/virtual_service.go
pkg/reconciler/v1alpha1/trigger/trigger.go
pkg/reconciler/v1alpha1/trigger/trigger_test.go

No code change, just refactor.
Fixes https://github.com/knative/eventing/issues/1012
- Use _reconciler_/resources to show clearly the resources that this controller can produce.
```release-note
NONE.
```

Refactor trigger reconciler to use resource subdir.

---

cmd/broker/ingress/main.go

- TTL was blocking me to make a cool app. Bumping TTL to a large number until we make it configurable.
Related to: #1011 
```release-note
Increase TTL from 10 to 255.
```

Using a larger default TTL until we make it settable.

---

hack/release.md

We have automatic releases now, so here's some new docs about how to create a major and minor release.

Update release docs with new automated procedures

---

contrib/natss/pkg/controller/clusterchannelprovisioner/reconcile_test.go

Fixes #
Fix #1019
- Avoid multiple generation of "DeletionTimestamp" during the tests
```release-note
```

Fix NATSS CCP flaky test "deleted_clusterChannelProvisioner"

---

test/README.md

There are several errors in the `README` file for test, which is misleading when people try to run the tests locally.

Fix errors in test readme

---

pkg/apis/eventing/v1alpha1/channel_lifecycle.go
pkg/apis/eventing/v1alpha1/channel_lifecycle_test.go
pkg/provisioners/inmemory/channel/reconcile.go
pkg/provisioners/inmemory/channel/reconcile_test.go

Deprecation notice for #787.
- Add a `Deprecated` condition to Channels. It does not affect `Ready`.
- Add a deprecation notice for `in-memory-channel`, which will be removed in 0.7.
Example:
```
status:
conditions:
- lastTransitionTime: 2019-04-17T20:40:05Z
message: The `in-memory-channel` ClusterChannelProvisioner is deprecated and will
be removed in 0.7. Recommended replacement is `in-memory`.
reason: ClusterChannelProvisionerDeprecated
severity: Warning
status: "True"
type: Deprecated
```
```release-note
The `in-memory-channel` ClusterChannelProvisioner will be deleted in the 0.7. Please migrate all Channels to a different provisioner.
```

Add a Deprecated condition on 'in-memory-channel' Channels.

---

pkg/apis/eventing/v1alpha1/broker_lifecycle.go
pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
pkg/reconciler/v1alpha1/broker/broker.go
pkg/reconciler/v1alpha1/broker/broker_test.go

Fixes #915
- Broker is not ready until its constituent pieces are ready.
- Emit Kubernetes events on every reconcile failure and when the Broker's readiness changes.
```release-note
NONE
```

Broker is not ready until its constituent pieces are ready.

---

test/builders.go
test/cleanup.go
test/clients.go
test/constants.go
test/crd.go
test/crd_checks.go
test/e2e-tests.sh
test/e2e/broker_trigger_test.go
test/e2e/channel_chain_test.go
test/e2e/e2e.go
test/e2e/event_transformation_test.go
test/e2e/main_test.go
test/e2e/single_event_test.go
test/e2e_flags.go
test/states.go
test/test_images/logevents/main.go
test/test_images/sendevent/main.go
test/test_images/transformevents/main.go

Fixes #1041 
Proposed changes:
1. Add e2e testing support for gcp-pubsub CCP;
2. Refactor some constants to `constants.go`

Add e2e testing support for gcp-pubsub CCP

---

test/e2e/broker_trigger_test.go
test/e2e/channel_chain_test.go
test/e2e/e2e.go
test/e2e/event_transformation_test.go
test/e2e/single_event_test.go

A couple of current E2E tests are flaky and fail intermittently.
This PR is adding more logs to collect more information when the test fails.

Add more logs, try to find the reason for e2e test flakiness

---

config/200-webhook-clusterrole.yaml

Running on Openshift and injecting the namespace with `kubectl label namespace someNameSpace knative-eventing-injection=enabled` (for the broker), give the error below due to missing RBAC policy.
From the logs:
```
{
"level": "error",
"ts": "2019-04-19T10:15:04.327Z",
"logger": "webhook",
"caller": "webhook/webhook.go:322",
"msg": "failed to register webhook",
"knative.dev/controller": "webhook",
"error": "failed to create a webhook: mutatingwebhookconfigurations.admissionregistration.k8s.io \"webhook.eventing.knative.dev\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>",
"stacktrace": "github.com/knative/eventing/vendor/github.com/knative/pkg/webhook.(*AdmissionController).Run\n\t/go/src/gith …
```

Fix webhook controller RBAC policy

---

test/e2e-tests.sh

Since the current tests for GCP PubSub provisioner are quite flaky, we disable the tests for now until we fix them.
/cc @grantr

Disable gcp pubsub e2e tests until we fix the flaky tests

---

Gopkg.lock
Gopkg.toml
vendor/github.com/spf13/pflag/bytes.go
vendor/github.com/spf13/pflag/flag.go
vendor/github.com/spf13/pflag/string_to_int.go
vendor/github.com/spf13/pflag/string_to_string.go

These overrides are (probably) not necessary anymore.
- `cobra` isn't used anywhere in the project
- `pflag` override was removed from serving and build-pipeline
- `protobuf` and `oauth2` overrides were added in #57, almost certainly no longer relevant (but @vaikas-google may remember a good reason to keep them).
I updated `pflag` to 1.0.3, same as serving.
/cc @vdemeester 
This is not _just_ cleanup: CEL requires protobuf 1.3.0 (for #1047), so we need to remove the 1.1.0 override first.

Remove a few obsolete overrides

---

pkg/reconciler/trigger/trigger.go
pkg/reconciler/trigger/trigger_test.go

Just adding more comprehensive unit tests for trigger reconciler.

add more unit tests for trigger reconcile.

---

contrib/kafka/config/README.md
contrib/kafka/config/kafka.yaml

The broker itself needs to be a stateful set, but the dispatcher is just a client/consumer.
hence a deployment is good.
@grantr  I guess we need some release notes :smile: 
locally tested w/ a 0.4.0 installation and this branch (and Strimzi 0.11 release). messages are distributed from the dispatcher

Kafka dispatcher no need for a statefulset

---

config/300-broker.yaml
config/300-channel.yaml

with `additionalProperties:true`, I am getting the following error:
```
cannot unmarshal bool into Go struct field JSONSchemaProps.AdditionalProperties of type apiextensions.JSONSchemaPropsOrBool
```
Since k8s forces it (defaults) to be `true`, we don't need to explicitly set it to true!

k8s forces additionalProperties to true, hence no need to set it ourselves

---

OWNERS_ALIASES
contrib/gcppubsub/OWNERS
contrib/kafka/OWNERS
contrib/natss/OWNERS

- Add OWNERS for the Channel implementations, based on those who volunteered during the WG call.
This will only be submitted once all of the following people have LGTM'ed it:
```release-note
NONE
```

Add OWNERS for the Channel implementations

---

config/200-broker-clusterrole.yaml

the other 200- files are using quotes (`"..."`) for groups, verbs and rules.  Doing the same for the broker-clusterrole

Consistency is king, use "" for the filter

---

pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go

- Update subscription error when reply strategy does not contain address
Fixes #1081 
cc @n3wscott

Add data validation for subscription in reconciler

---

cmd/controller/main.go
cmd/sources-controller/main.go

Replace a runtime check with a compile-time assert in two controller mainlines
Sister PR in serving https://github.com/knative/serving/pull/3923

compile-time assert numControllers == len(controllersArray)

---

cmd/controller/main.go
pkg/reconciler/channel/channel.go
pkg/reconciler/eventtype/eventtype.go
pkg/reconciler/namespace/namespace.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/trigger/trigger.go
pkg/reconciler/v1alpha1/broker/broker.go

knative.dev/controller is set by pkg/reconciler just before calling our reconciler, so adding a second one in main is redundant and produced entries with:
{
"knative.dev/controller": "controller",
"knative.dev/controller": "trigger-controller",
}
Fixes #
- Remove unneeded log keys.
- knative.dev/controller is set by pkg/reconciler just before calling our reconciler, so adding a second one in main is redundant and produced entries with:
```json
{
"knative.dev/controller": "controller",
"knative.dev/controller": "trigger-controller",
}
```
- The reconcile key is already saved as 'knative.dev/key' by pkg/reconciler, so we don't need to add 'key' as well.
```release-note
NONE
```

Remove unneeded log keys.

---

test/e2e/e2e.go

Add hacky sleep trying to mitigate the test flakiness for now

---

config/500-controller.yaml

- Remove receive adapter images that are only relevant for the eventing-sources controller, not the eventing controller.
```release-note
NONE
```

Remove receive adapter images that are not needed

---

test/e2e-tests.sh

We do not need to install Knative Serving for the e2e tests anymore after completely getting rid of Istio dependency.

Remove Knative Serving installation step

---

pkg/reconciler/namespace/namespace.go
pkg/reconciler/namespace/namespace_test.go
pkg/reconciler/namespace/resources/labels.go

Addressed few issues mentioned in #1080 
- produces reconciliation successs/failure events
- unit test for cleaning up resources and default broker in namespace
cc @n3wscott

Fixing namespace reconciler bugs

---

contrib/kafka/config/kafka.yaml

Fixes #
- deprecated kafka statefulset for the dispatcher
- temporarily scaling down to 0 replicas
```release-note
The `StatefulSet` is now **deprecated** and will go away in 0.7.0 release. In this release it's replaced by a `Deployment` and the `StatefulSet` is scaled down to 0 replicas
Action Required: It is recommended to delete your old dispatcher
```

Adding back statefulSet w/ 0 replicas

---

contrib/kafka/config/kafka.yaml

Adding clarification on why the `StatefulSet` is present with zero `replicas`
/cc @grantr @akashrv

Adding comment for reason behind replicas:0

---

Gopkg.lock
test/e2e-tests.sh
vendor/github.com/knative/test-infra/scripts/README.md
vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
vendor/github.com/knative/test-infra/scripts/library.sh

Update vendor: knative/test-infra. 
- fix for retrying different GCP regions when e2e test failed due to stock out
- Istio install from GKE Addon

Update test-infra: some fixes

---

cmd/fanoutsidecar/main.go
pkg/channelwatcher/channel_watcher.go
pkg/channelwatcher/channel_watcher_test.go
pkg/sidecar/multichannelfanout/config.go
pkg/sidecar/multichannelfanout/config_test.go

- `in-memory` Channels are asynchronous.
```release-note
NONE
```

in-memory Channels are asynchronous

---

config/200-controller-clusterrole.yaml
config/provisioners/in-memory-channel/in-memory-channel.yaml

At least on OpenShift, which has fairly restrictive RBAC out of the box, a few rules are missing for `/finalizers` sub-resource

Adding finalizers for a more constraint RBAC

---

pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
pkg/provisioners/provisioner_util.go

Fix [1160](https://github.com/knative/eventing/issues/1160)
- Add function `GetGroupVersionKind()` for struct `ClusterChannelProvisioner`
```release-note
None
```

Use kmeta.NewControllerRef 

---

docs/broker/filtering.md

[**Rendered**](https://github.com/grantr/eventing/blob/filtering-proposal/docs/broker/filtering.md)
This document proposes a design for advanced trigger filtering to complete #930.
/cc @bbrowning @Harwayne since I believe you've expressed interest in this topic.
/kind proposal

Advanced Trigger Filtering Design Proposal

---

pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go

Follow [1168](https://github.com/knative/eventing/pull/1168)
```release-note
None
```

Check that ClusterChannelProvisioner is OwnerRefable

---

pkg/apis/eventing/v1alpha1/broker_types.go
pkg/apis/eventing/v1alpha1/channel_types.go
pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
pkg/apis/eventing/v1alpha1/trigger_types.go

Use `SchemeGroupVersion.WithKind()` to implement `GetGroupVersionKind`.
-
-
-
```release-note
```

Polish GetGroupVersionKind for Broker/Channel/ClusterChannelProvisioner/Trigger

---

config/300-eventtype.yaml
pkg/apis/eventing/v1alpha1/eventtype_types.go

- the json tag needs internal double quotes. Added them.
```release-note
NONE
```
/assign @nachocano

fix minor quote issue for json tag.

---

pkg/broker/receiver.go
pkg/broker/receiver_test.go
pkg/reconciler/testing/trigger.go
pkg/reconciler/trigger/path/path.go
pkg/reconciler/trigger/trigger_test.go

Fixes #1153
- Include the Trigger's UID in the Trigger's path, to make sure the filter Deployment doesn't accidentally use an old, now deleted, Trigger's spec.
```release-note
NONE
```

Include the Trigger's UID in the Trigger's path

---

cmd/apiserver_receive_adapter/main.go
cmd/controller/main.go
cmd/in_memory/controller/main.go
cmd/in_memory/dispatcher/main.go
cmd/sources_controller/main.go
contrib/kafka/cmd/controller/main.go
pkg/metrics/config.go

Follow-up to #1200 
- Cleanup the gke import lines. Used for off cluster gke connections. (Clean up the nits added to #1200)
```release-note
NONE
```

Cleanup the gke import lines. Used for off cluster gke connections.

---

cmd/cronjob_receive_adapter/main.go
pkg/adapter/cronjobevents/adapter.go
pkg/apis/sources/v1alpha1/cron_job_types.go
pkg/reconciler/cronjobsource/cronjobsource_test.go
pkg/reconciler/cronjobsource/resources/eventtype.go
pkg/reconciler/cronjobsource/resources/receive_adapter.go
pkg/reconciler/cronjobsource/resources/receive_adapter_test.go

Helps fixing https://github.com/knative/eventing/issues/929
- Change the CloudEvent source we are currently setting in CronJobSource. 
- /CronJob is somewhat useless to have as source, given that we have the CloudEvent type that indicates that. 
- As we are probably not going to include advanced filtering in 0.6 to, for example, filter on subject, then we should be more careful of what we put in source.
- Setting it to be:  /apis/v1/namespaces/<namespace>/cronjobsources/<cronjobname>
```release-note
Upon instantiation of a CronJobSource, it will register its EventType. This a breaking change in the sense that we were previously populating the CloudEvent source attribute with "/CronJob". Now we use "/apis/v1/namespaces/<namespace>/cronjobsources/<cronjobname>". If Triggers …
```

Changing Source in CronJob

---

contrib/natss/config/provisioner.yaml
contrib/natss/pkg/dispatcher/main.go

Helps with #704.
- Add Zipkin tracing support to the NATSS Channel dispatcher.
```release-note
An additional RBAC permission is needed by the `natss-dispatcher`. You need to apply `contrib/natss/config/provisioner.yaml` to grant it.
```

Add tracing to NATSS Channels, by watching the config-tracing ConfigMap.

---

docs/broker/filtering.md

There is a prettier.io comment to prevent reformatting of something that should be formatted the way it is. Giving these to the filter spec to prevent https://github.com/knative/eventing/pull/1208

Get sockpuppet off our backs and stop breaking the format.

---

docs/personas.md

- Add System Integrator persona. Quite often I find myself thinking of a person that's creating a new Channel type, or a new Event source and they feel like a distinct personal that's currently missing from the personal document. So, here's one proposal to fix that.
```release-note
Add 'System Integrator' as a persona.
```

add system integrator persona

---

test/e2e-tests.sh

- Quick fix to remove istio injection in namespace that has the natss instance. This was fixed as part of removing istio dependency in Eventing, and documentation was updated. But I guess it slipped into tests around the same time
-
-
```release-note
```

Natss broker doesn't require istio injectin enabled

---

pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/cronjobsource/cronjobsource.go
pkg/reconciler/cronjobsource/cronjobsource_test.go

- Bug found while editing the ApiServerSource or a CronJobSource source. E.g., changing its broker.
- Properly reconcile its EventTypes upon Event Source change, and also upon EventType change.
- Pending: if the Source sink changes to a non-Broker one, we are not properly removing the EventTypes. Will do in a follow up PR.
```release-note
NONE
```

Reconcile EventType upon Source change

---

pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/cronjobsource/cronjobsource.go
pkg/reconciler/cronjobsource/cronjobsource_test.go

- By changing the sink of ApiServerSources or CronJobSources to be non-sink ones, we should delete its EventTypes. This decision might be revised in https://github.com/knative/eventing/issues/1202, but the previous implementation had a bug.
```release-note
NONE
```

Removing eventTypes if we change the sink to be a non-broker one.

---

pkg/apis/eventing/v1alpha1/trigger_defaults_test.go
pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go

- Fix race conditions in `TestTriggerAnnotateUserInfo`.
- Flakiness was seen in https://github.com/knative/eventing/pull/1238#issuecomment-493139848
Earlier race problems could be seen with `go test ./pkg/apis/eventing/v1alpha1 -run TestTriggerAnnotateUserInfo -race -count 10`
```release-note
NONE
```

Fix race conditions in TestTriggerAnnotateUserInfo

---

cmd/in_memory/dispatcher/main.go
config/provisioners/in-memory-channel/README.md
config/provisioners/in-memory-channel/in-memory-channel.yaml
pkg/provisioners/inmemory/channel/controller.go
pkg/provisioners/inmemory/channel/reconcile.go
pkg/provisioners/inmemory/channel/reconcile_test.go
pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile.go
pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile_test.go
pkg/provisioners/multichannelfanout/config.go
pkg/provisioners/multichannelfanout/config_test.go
test/README.md
test/constants.go
test/e2e-tests.sh
test/e2e/main_test.go

Fixes #787
- Remove the deprecated 'in-memory-channel' ClusterChannelProvisioner.
```release-note
The `in-memory-channel` ClusterChannelProvisioner has been removed. The recommended replacement is `in-memory`.
```

Remove the deprecated 'in-memory-channel' ClusterChannelProvisioner.

---

config/200-broker-clusterrole.yaml
config/500-controller.yaml
docs/broker/README.md
pkg/reconciler/namespace/namespace.go
pkg/reconciler/namespace/namespace_test.go
pkg/reconciler/namespace/resources/names.go
pkg/reconciler/namespace/resources/role_binding.go
pkg/reconciler/namespace/resources/service_account.go
test/e2e/broker_event_transformation_test.go

Helps with #704, as this SA will be needed to get ConfigMap reading permissions.
- Use the Service Account `eventing-broker-ingress`, rather than `default` on Broker Ingress Pods.
- Create the Service Account via the namespace annotation.
- Add the instructions to create the Service Account manually for those that don't use the annotation.
```release-note
If you are using a Broker in a namespace not annotated with eventing injection, then you will need to follow the [manual setup instructions](https://github.com/knative/eventing/tree/master/docs/broker#manual-setup) to create the required ServiceAccount and RoleBinding. 
Note that failing to do so will not cause immediately noticable failures. Only after a subsequent PR starts watching ConfigMaps will the failure begin to …
```

Create a ServiceAccount for Broker Ingress

---

Gopkg.lock
test/e2e-tests.sh
vendor/github.com/knative/test-infra/scripts/README.md
vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
vendor/github.com/knative/test-infra/scripts/library.sh
vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
vendor/github.com/knative/test-infra/scripts/release.sh

Fixes https://github.com/knative/test-infra/issues/723
Eventing 0.5 can only work with `Serving 0.5 + Istio 0.5 shipped by Serving`, but not `Serving 0.5 + GKE Istio Addon`, so we'll have to install `Istio 0.5` here.
Since `Istio 0.5` is only used by Eventing 0.5, and Serving release has stopped shipping Istio, I think it's better to add the function directly here instead of adding extra complexity to the test-infra. Please LMK if there's any other suggestion.
/cc @adrcunha 
/cc @chaodaiG 
```release-note
NONE
```

Fix CI flow error for Eventing-0.5

---

cmd/controller/main.go
pkg/apis/eventing/v1alpha1/subscription_lifecycle.go
pkg/apis/eventing/v1alpha1/subscription_types.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go
pkg/reconciler/testing/subscription.go

Found this while investigation the changes for Channel CRDs
- Marking subscription as not ready in the different failure conditions that can occur.
- Updated UTs.
- Still not entirely sure if we can remove the channel informer. Will further discuss with @Harwayne 
```release-note
NONE
```

Updating Subscription Ready status on Failed conditions

---

pkg/apis/eventing/v1alpha1/broker_types.go
pkg/apis/eventing/v1alpha1/trigger_types.go

I noticed while combing through the API that `Broker` and `Trigger` don't have type-level godoc for what they are.

Add type godoc for Broker and Trigger

---

Gopkg.lock
Gopkg.toml
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/containersource/containersource_test.go
pkg/reconciler/cronjobsource/cronjobsource_test.go
pkg/reconciler/inmemorychannel/inmemorychannel_test.go
pkg/reconciler/namespace/namespace_test.go
pkg/reconciler/trigger/trigger_test.go
vendor/github.com/knative/pkg/reconciler/testing/table.go

We allow a more permissive type for WantCreates, which requires a change to most existing table tests which use a different slice type.

Pickup runtime.Object change

---

test/base/generics.go
test/base/resource_checks.go
test/base/resource_inspectors.go
test/base/resources.go
test/common/operation.go
test/e2e/broker_channel_flow_test.go
test/e2e/broker_default_test.go
test/e2e/broker_event_transformation_test.go

Fixes #1273 
The PR involves the following changes:
1. Split generic methods for operating on duck-type into three files: `generics.go` provides function to get the raw object for a given duck-type; `resource_checks.go` contains functions to check the duck resource status; `resource_inspectors.go` contains functions that can return status of a duck resource.
2. Add one E2E test case to test the scenario that uses both `Broker` and `Channel`.
```release-note
NONE
```

Add one E2E test case that uses both broker and channel

---

hack/release.sh

- adding In-Mem channel CRD to a separate yaml file
- including it in the `release.yaml` file
- renaming the current one to `-provisioner`
```release-note
the in-memory-channel.yaml is replaced by the in-memory-channel-provisioner.yaml, and there is an new in-memory-channel-crd.yaml file that contains the new CRD for the in-mem channel
```

Adding CRD to the yaml artifacts, and release

---

cmd/webhook/main.go
config/400-webhook-service.yaml
config/500-webhook.yaml

Fixes #1260
- rename `webhook` to be `eventing-webhook`
- keep old `webhook` deployment, but with `replicas: 0`
```release-note
the webhook has been renamed to eventing-webhook, and the old webhook will scale to 0
```

rename webhook to be eventing-webhook to avoid potential clash

---

config/300-eventtype.yaml

Fixes #1285 
While installing the Eventing 0.6.0 CRD by '--selector knative.dev/crd-install=true', the `EventType` will not be installed.
- Add the `knative.dev/crd-install=true` label in `config/300-eventtype.yaml` .
```release-note
```

Add the knative.dev/crd-install=true label in eventtype.yaml

---

config/300-eventtype.yaml

Fixes #1307 
- Add openAPIV3Schema to EventType CRD
```release-note
N/A
```

Add openAPIV3Schema to EventType CRD

---

cmd/broker/filter/main.go
contrib/gcppubsub/pkg/controller/cmd/main.go

- Fix envconfig tags by removing spaces.
- Spaces were accidentally added in #1305, leading to envconfig not working as expected.
```release-note
GCP PubSub dispatcher will need to redeployed, if it was released between #1305 and this PR.
```

Fix envconfig tags by removing spaces

---

test/README.md
test/common/client.go
test/common/creation.go
test/common/operation.go
test/e2e/broker_channel_flow_test.go
test/e2e/broker_default_test.go
test/e2e/broker_event_transformation_test.go
test/e2e/channel_chain_test.go
test/e2e/channel_event_transformation_test.go
test/e2e/channel_single_event_test.go
test/e2e/test_runner.go

- As discussed with Adam, it makes the code quite verbose if we handle every error in the test cases. So I changed all creation functions to `CreateXXOrFail` to make the test cases cleaner.
- Fix the example in `README` as `TestSingleBinaryEvents` doesn't exist anymore.
```release-note
NONE
```
/cc @Harwayne 
/cc @adrcunha

Enable fail fast for resource creation functions used in E2E tests

---

contrib/kafka/cmd/webhook/main.go
contrib/kafka/config/200-webhook-clusterrole.yaml
contrib/kafka/config/201-clusterrolebinding.yaml
contrib/kafka/config/400-webhook-service.yaml
contrib/kafka/config/500-webhook.yaml
contrib/kafka/config/README.md
contrib/kafka/config/provisioner/README.md

Fixes #1216
- Adding a kafka admission webhook to set proper default values to KafkaChannel COs and do validations.
- Adding new README with documentation
```release-note
NONE
```

Kafka Webhook and Documentation

---

contrib/kafka/pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle.go
contrib/kafka/pkg/apis/messaging/v1alpha1/kafka_channel_lifecycle_test.go
contrib/kafka/pkg/apis/messaging/v1alpha1/kafka_channel_types.go
contrib/kafka/pkg/reconciler/controller/kafkachannel.go

- Moving to duckv1beta1.Status in KafkaChannel CRD
- The Kafka PR got merged after the changes to move to the beta ducks, therefore missed the refactor.
```release-note
NONE
```

Using duckv1beta1 Status for KafkaChannel

---

pkg/apis/eventing/v1alpha1/broker_defaults.go
pkg/apis/eventing/v1alpha1/broker_types.go
pkg/apis/eventing/v1alpha1/channel_defaults.go
pkg/apis/eventing/v1alpha1/channel_types.go
pkg/apis/eventing/v1alpha1/subscription_defaults.go
pkg/apis/eventing/v1alpha1/subscription_types.go
pkg/apis/eventing/v1alpha1/trigger_defaults.go
pkg/apis/eventing/v1alpha1/trigger_types.go
pkg/apis/eventing/v1alpha1/user_info.go

Fixes https://github.com/knative/eventing/issues/1251
- Reduce multiple implementations of code that adds user info annotations
```release-note
NONE
```
I think this task can be done in a proper way when some of the changes are moved to <https://github.com/knative/pkg>.
Some notes:
* The interface I introduced (`HasSpec`) could/should be defined in <https://github.com/knative/pkg> so that it is used in other modules as well.
* Also, if it was defined in <https://github.com/knative/pkg>, we would be able to call `setUserInfoAnnotations` directly for a resource within the webhook [here](https://github.com/knative/pkg/blob/365d80ec5bf8ec9fc0f6be429e1969f368a942c3/webhook/webhook.go#L551) like this:
```golang
oldObj = oldObj.DeepCopyObject().(GenericCRD) …
```

#1251 Duck type user info annotation logic

---

test/base/generics.go
test/base/resources.go
test/common/creation.go
test/common/operation.go
test/common/validation.go
test/e2e/source_cron_job_test.go

I revisited the [samples of eventing sources](https://github.com/knative/docs/tree/master/docs/eventing/samples), and I think there is no need to have a separate testing framework for eventing sources now. We can just create the EventSource resource, add a Kubernetes Service sink for it (we can just use the existed logger pod), and check if the Service can receive the events.
Probably in the future when we have an eventing sources framework, we can design a corresponding testing framework. But for now since we have decided to put `CronJobSource` under eventing repo, I think it would be good to have E2E test coverage for it.
```release-note
NONE
```
/cc @adrcunha

Add E2E test case for cron job source

---

cmd/in_memory/channel_dispatcher/main.go
config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml
pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle.go
pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle_test.go
pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
pkg/reconciler/testing/inmemorychannel.go

References #1189 
- Change InMemoryChannel to conform to the new subscribable status.
- Namely now have these fields:
duckv1alpha1.AddressStatus `json:",inline"`
eventingduck.SubscribableTypeStatus `json:",inline"`
- Modeled after #1330
```release-note
Change the Status.Addressable to inlined: duckv1alpha1.AddressStatus
Add inlined: eventingduck.SubscribableTypeStatus
```

In memory subscribable status (fix fallout from #1330)

---

cmd/in_memory/channel_dispatcher/main.go
contrib/gcppubsub/pkg/controller/channel/reconcile.go
contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
contrib/kafka/pkg/controller/channel/reconcile.go
contrib/kafka/pkg/controller/channel/reconcile_test.go
contrib/natss/pkg/controller/channel/reconcile.go
contrib/natss/pkg/controller/channel/reconcile_test.go
pkg/provisioners/inmemory/channel/reconcile.go

Helps with Channel CRDs
- Adding a condition to the Channel provisioners saying that we are deprecating them, and that they will be removed in 0.8.
```release-note
Channel provisioners (kafka, natss, gcp-pubsub and in-memory) are deprecated in 0.7. Will be removed in 0.8
```

Channel Deprecation Condition

---

contrib/kafka/cmd/channel_controller/main.go
contrib/kafka/cmd/channel_dispatcher/main.go
contrib/kafka/pkg/reconciler/controller/kafkachannel.go
contrib/kafka/pkg/reconciler/controller/kafkachannel_test.go
contrib/kafka/pkg/reconciler/dispatcher/kafkachannel.go
contrib/kafka/pkg/reconciler/reconciler.go
contrib/kafka/pkg/reconciler/stats_reporter.go
contrib/kafka/pkg/reconciler/testing/factory.go
contrib/kafka/pkg/reconciler/testing/kafkachannel.go
contrib/kafka/pkg/reconciler/testing/listers.go

- Adding UTs to the new Kafka CRD controller.
- Needed a refactor to have our own reconciler, options, statsreporter, test factory, etc.
- Adding Zipkin tracing
```release-note
NONE
```

Kafka CRD Controller UT + Dispatcher tracing

---

config/200-addressable-resolvers-clusterrole.yaml

- Add K8s Services to the addressable resolver role.
```release-note
The addressable-resolver role now includes Kubernetes Services.
```

Add K8s Services to the addressable resolver role.

---

cmd/broker/filter/main.go
config/200-broker-clusterrole.yaml
pkg/broker/receiver.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/resources/filter.go
pkg/tracing/names.go
pkg/tracing/names_test.go

Helps with #704.
- Add dynamic Zipkin Tracing to the Broker Filter component (e.g. triggers).
```release-note
The `eventing-broker-filter` ClusterRole in `200-broker-clusterrole.yaml` needs to be re-applied.
```

Broker Filter tracing

---

contrib/kafka/config/provisioner/kafka.yaml

Running on Openshift 4.1, getting:
```
{"level":"info","ts":"2019-06-07T13:01:47.237Z","logger":"provisioner","caller":"controller/reconcile.go:43","msg":"reconciling ClusterChannelProvisioner","request":"/kafka"}
{"level":"info","ts":"2019-06-07T13:01:47.255Z","logger":"provisioner","caller":"controller/reconcile.go:100","msg":"error creating the ClusterProvisioner's K8s Service","error":"services \"kafka-dispatcher\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
{"level":"info","ts":"2019-06-07T13:01:47.255Z","logger":"provisioner","caller":"controller/reconcile.go:76","msg":"error reconciling ClusterProvisioner","error":"services \"kafka-dispatcher\" is forbidden: cannot set blockOwnerDeletion if an …
```

fixing RBAC for finalizers sub-resource

---

contrib/kafka/config/400-kafka-config.yaml
contrib/kafka/config/README.md
contrib/kafka/config/provisioner/README.md
contrib/kafka/config/provisioner/kafka.yaml
contrib/kafka/pkg/utils/util.go
contrib/kafka/pkg/utils/util_test.go

Similar to the source (in contrib repo) we going with camelCase for kafka channel cfg.
the changes apply to the new CRD (new in 0.7.0), as well to the old/deprecated CCP for Kafka.
Since users anyways have to change the config on the "channel", to point to the accessible Kafka cluster, it's not that of a harm if the argument is now called `bootstrapServers`, instead of `bootstrap_servers`, I think...
```release-note
the configuration for the kafka CCP is now camel case
```

Using CamelCase syntax for the Kafka Channels

---

cmd/controller/main.go
pkg/reconciler/broker/controller.go

Fixes #1383
- Instead of using the shared AddressInformer from the main controller, create one for us
```release-note
```

create a new own addressinformer for broker

---

config/500-controller.yaml
config/500-sources-controller.yaml
config/500-webhook.yaml

Related to https://github.com/knative/eventing-contrib/issues/457 
- remove resource limits, since they were initial guesses ...
```release-note
Removing the resource limits (which is a hard maximum) for eventing-controller, eventing-webhook and sources-controller
```

Removing limits

---

config/channels/in-memory-channel/300-in-memory-channel.yaml
contrib/kafka/config/300-kafka-channel.yaml
contrib/natss/config/300-natss-channel.yaml

Currently you have to `k get XyZChannel` to get the `channel`, like:
```
k get InMemoryChannel
matzew-pipeline-kn-pipeline-0   True             matzew-pipeline-kn-pipeline-0-kn-channel.default.svc.cluster.local   27m
matzew-pipeline-kn-pipeline-1   True             matzew-pipeline-kn-pipeline-1-kn-channel.default.svc.cluster.local   27m
```
@grantr did suggest adding `channel` to the `categories` section of the different CRDs

Adding channel category

---

config/200-controller-clusterrole.yaml
config/channels/in-memory-channel/200-channelable-manipulator-clusterrole.yaml
contrib/kafka/config/200-channelable-manipulator-clusterrole.yaml
contrib/natss/config/200-channelable-manipulator-clusterrole.yaml

Fixes #1402 
- Add 'create' verb to each '*-channelable-manipulator'
- Remove explicit permissions on the eventing controller for 'inmemorychannel'
```release-note
- each *-channel-manipulator has added 'create' verb.
```

remove imc permissions from controller, add create to channelable

---

test/base/resources/eventing.go
test/common/creation.go
test/e2e/broker_channel_flow_test.go
test/e2e/broker_event_transformation_test.go

Fixes #1380 
- Add e2e test case to test `Broker` that uses the new `ChannelTemplate`.
```release-note
NONE
```
/cc @vaikas-google

Add e2e test for Broker using Channel CRDs

---

config/300-sequence.yaml
pkg/apis/messaging/v1alpha1/sequence_lifecycle.go
pkg/apis/messaging/v1alpha1/sequence_lifecycle_test.go
pkg/apis/messaging/v1alpha1/sequence_types.go
pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go

After the pipeline (now Sequence) was checked in, the Status was changed from Addressable => AddressStatus, so just making changes to be compliant with that change.
Also, print out the Status.Address (just like for channels).
Now prints out IMC / Sequence consistently:
kubectl -n foobar get sequence
NAME              READY   REASON   HOSTNAME                                                            AGE
vaikas-sequence   True             vaikas-sequence-kn-sequence-0-kn-channel.foobar.svc.cluster.local   8m
kubectl -n foobar get imc
NAME                            READY   REASON   HOSTNAME                                                            AGE
vaikas-sequence-kn-sequence-0   True             vaikas-sequence-kn-sequence-0-kn-channel.foobar.svc.cluster.local   8m …

use AddressStatus instead of Addressable

---

pkg/duck/addressable.go
pkg/reconciler/broker/broker.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/controller.go
pkg/reconciler/sequence/controller.go
pkg/reconciler/sequence/sequence.go
pkg/reconciler/sequence/sequence_test.go
pkg/reconciler/subscription/controller.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go
pkg/reconciler/trigger/controller.go
pkg/reconciler/trigger/trigger.go
pkg/reconciler/trigger/trigger_test.go

AddressableTracker is a tracker which supports registering callbacks
with an AddressableInformer and which can be created using an
AddressableInformer factory method. Previously TrackInNamespace could
be called directly on an AddressableInformer with an external
tracker but this method would only register callbacks for the first
tracker which attempted to track an addressables in each GVR.
Fixes #1383

Add AddressableTracker type.

---

Gopkg.lock
Gopkg.toml
hack/update-deps.sh
vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/breaking-change.md
vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/bug-fix.md
vendor/github.com/knative/pkg/.github/PULL_REQUEST_TEMPLATE/normal-change.md
vendor/github.com/knative/pkg/.github/pull-request-template.md
vendor/github.com/knative/pkg/Gopkg.lock
vendor/github.com/knative/pkg/apis/duck/typed.go
vendor/github.com/knative/pkg/hack/update-deps.sh
vendor/github.com/knative/pkg/injection/informers/kubeinformers/batchv1/job/fake/fake.go
vendor/github.com/knative/pkg/injection/informers/kubeinformers/batchv1/job/job.go
vendor/github.com/knative/pkg/injection/sharedmain/main.go

This form should be more hospitable to running things to auto-update `knative/pkg` and `knative/test-infra`.
I canaried this change in `knative/sample-controller`, and was able to produce: https://github.com/knative/sample-controller/pull/11

Make a small adjustment to hack/update-deps.sh

---

cmd/broker/filter/main.go
cmd/broker/ingress/main.go
config/200-broker-clusterrole.yaml
docs/broker/README.md
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/resources/filter.go
pkg/reconciler/broker/resources/ingress.go
pkg/reconciler/namespace/namespace.go
pkg/reconciler/namespace/namespace_test.go
pkg/reconciler/namespace/resources/names.go
pkg/reconciler/namespace/resources/role_binding.go

Fixes #1416
- Update ingress and filter pods to watch for observability ConfigMaps in the system namespace (normally `knative-eventing`) instead of the Broker's namespace. This removes the ability to create per-namespace configs, but we think that use case is much less likely than the cluster-wide config case.
- Add the `SYSTEM_NAMESPACE` env var to ingress and filter podspecs to inform knative/pkg where the system namespace is.
- When creating a default Broker via injection, add a RoleBinding in the system namespace allowing ConfigMap read from the ingress and filter service accounts in the Broker's namespace. Users creating non-injected Brokers will need to create this RoleBinding manually (and all other RBAC objects).
```release-note
All Broker ingress and filter pods …
```

Use shared observability config in broker data plane

---

cmd/webhook/main.go
pkg/apis/messaging/v1alpha1/sequence_types.go
pkg/apis/messaging/v1alpha1/sequence_validation_test.go
pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
pkg/reconciler/sequence/sequence_test.go

Fixes #1427 
- Actually use webhook to validate messaging resources.
```release-note
```

use webhook to validate messaging.v1alpha1 resources

---

docs/broker/example_brokers.yaml

Adding Broker w/ Kafka as example

---

test/performance-tests.sh

As suggested in another PR, overwrite the cluster node number to 1 for performance testing jobs.
```release-note
NONE
```
/cc @adrcunha

Overwrite the cluster node number to 1 for perf testing jobs

---

contrib/gcppubsub/pkg/controller/channel/reconcile.go

- Name is wrong in message, CRD is `Channel.events.cloud.run`.
```release-note
NONE
```

fix PubSub Channel CRD name.

---

pkg/broker/receiver.go
pkg/broker/receiver_test.go
pkg/broker/ttl.go

Fixes #1392
Fixes #1444
Change casing on constant due to the way go http libraries use canonical mime encoding for http headers, this causes issues with using binary encoding for CloudEvents.
```release-note
Fixes issue where the broker may drop messages with a "no TTL" error.
```

Fix issue with broker dropping messages with "No TTL Seen"

---

pkg/utils/runnable_server_test.go

This test has flaked a few times recently. Hopefully extending the timeout reduces timing flakes on heavily loaded CI nodes.
/cc @Fredy-Z

Extend RunnableServer shutdown cutoff

---

pkg/reconciler/namespace/namespace_test.go
pkg/reconciler/namespace/resources/names.go

If the RoleBinding name were too long, the APIServer would always reject it and the namespace injection would fail forever. `kmeta.ChildName` truncates the RoleBinding name to ensure it's never too long for Kubernetes to accept.
Thanks @n3wscott for pulling this in with #1433.
- Use `kmeta.ChildName` to ensure RoleBinding name is always less than 64 characters.
```release-note
```

Ensure RoleBinding name is never too long

---

pkg/broker/receiver.go
pkg/broker/ttl.go

Backport #1452 by @mikehelmick into 0.6.
* Fix issue with broker dropping messages with "No TTL Seen"
* Treat the broker TTL attribute as case insensitive, in line with how cloudevents attributes should be handled. See https://github.com/cloudevents/spec/pull/321 for context.
* Remove unnecessary test change.
```release-note
Fixed an issue with the Broker TTL attribute that could cause events to be incorrectly dropped.
```

Backport #1452

---

config/100-namespace.yaml
config/200-addressable-resolvers-clusterrole.yaml
config/200-broker-clusterrole.yaml
config/200-channelable-manipulator-clusterrole.yaml
config/200-controller-clusterrole.yaml
config/200-serviceaccount.yaml
config/200-webhook-clusterrole.yaml
config/201-clusterrolebinding.yaml
config/300-apiserversource.yaml
config/300-broker.yaml
config/300-channel.yaml
config/300-clusterchannelprovisioner.yaml
config/300-containersource.yaml
config/300-cronjobsource.yaml
config/300-eventtype.yaml
config/300-sequence.yaml
config/300-subscription.yaml
config/300-trigger.yaml
config/400-source-controller-service.yaml
config/400-webhook-service.yaml
config/500-webhook.yaml
config/config-observability.yaml

Follows the serving strategy of labeling all resources with release names except configmaps (since we expect users will modify those).
These need to be updated to the correct release number in the release branch before the release is cut. I'll do that for today's 0.7 release.

Add release label to all objects

---

config/channels/in-memory-channel/200-channelable-manipulator-clusterrole.yaml
config/channels/in-memory-channel/200-controller-clusterrole.yaml
config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml
config/channels/in-memory-channel/200-dispatcher-service.yaml
config/channels/in-memory-channel/200-serviceaccount.yaml
config/channels/in-memory-channel/201-clusterrolebinding.yaml
config/channels/in-memory-channel/300-in-memory-channel.yaml
config/provisioners/in-memory-channel/in-memory-channel.yaml

Everything is labeled with `eventing.knative.dev`, even though some of these objects are in the `messaging.knative.dev group`, because for now there's only one release.

Add release label to channel and provisioner yamls

---

pkg/utils/runnable_server_test.go

Should help 0.6 CI be less flaky.

Backport #1460 to 0.6

---

hack/release.sh

Fixes #1485
- patch to release branch, to have the `kafka-ccp.yaml` file ... since the `kafka.yaml` now contains the CRD, only
```release-note
adding back Kafka CCP yaml
```

Adding the cfg for the (deprecated) Kafka CCP

---

hack/release.sh

Similar to #1486, but for NATSS CCP.
- Add a `natss-ccp.yaml` artifact to the 0.7 release branch since the `natss.yaml` file now contains only the NatssChannel CRD.
```release-note
Adding back NATSS CCP yaml.
```

Adding the cfg for the (deprecated) NATSS CCP

---

test/base/resources/cloud_event.go
test/base/resources/constants.go
test/base/resources/eventing.go
test/base/resources/kube.go
test/base/resources/messaging.go
test/base/resources/sources.go
test/common/creation.go
test/common/operation.go
test/common/typemeta.go
test/e2e/channel_chain_test.go
test/e2e/channel_event_transformation_test.go
test/e2e/sequence_test.go
test/test_images/sequencestepper/main.go
test/test_images/transformevents/main.go

Fixes #1388 
- This test only uses `InMemoryChannel` as the `ChannelTemplate`, I think since the underlying code is generic, and we have E2E test coverage for other `Channels`, there is no need to test with other `ChannelTemplates`. Please correct me if I'm wrong.
- This test case only tests against the first scenario documented in https://github.com/knative/docs/blob/master/docs/eventing/sequence.md, after it goes in, I'll add test cases for the other two scenarios.
```release-note
NONE
```
/cc @vaikas-google 
/cc @grantr

Add e2e test for sequence

---

config/200-controller-clusterrole.yaml

Related to #1450, on Openshift 4.1, I getting:
```
{"level":"error","ts":"2019-07-02T08:48:43.619Z","logger":"controller.sequence-controller","caller":"sequence/sequence.go:96","msg":"Error reconciling Sequence","knative.dev/controller":"sequence-controller","knative.dev/traceid":"194327ce-a8a6-4740-a49b-f9fed810c62f","knative.dev/key":"default/sequence","error":"inmemorychannels.messaging.knative.dev \"sequence-kn-sequence-0\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/knative/eventing/pkg/reconciler/sequence.(*Reconciler).Reconcile\n\t/home/prow/go/src/github.com/knative/eventing/pkg/reconciler/sequence/sequence.go:96\ngithub.com/knative/eventing/vendor/github.com/knative/pkg/control …
```

Fixing RBAC for finalizers sub-resource of Sequences

---

pkg/apis/messaging/v1alpha1/sequence_types.go

- add json tags to sequence status.

add missing json tags

---

contrib/gcppubsub/pkg/dispatcher/receiver/cache/cache_test.go
pkg/provisioners/fanout/fanout_handler_test.go
pkg/utils/runnable_server_test.go

These tests have failed 2+ of the last 10 continuous runs. Skip leaves them in while noting that they're flaky.
- Skip flaky cache test
- Skip flaky fanout handler test
- Skip flaky RunnableServer test

Skip flaky tests

---

docs/spec/README.md
docs/spec/channel.md
docs/spec/channel_060.md

Fixes #1213
- adding 0.6.0 (historic) status
- adding 0.7.0raw spec
what do we want in the conformance test section ? 
Let's mention it requires 
* controller
* dispatcher
* ServiceAccounts and ClusterRoles (for both)
* presence of labels:
* "channable:true" on the channelable-manipulator ClusterRole
* "subscribable:true" on the CRD definition file
* usage of CloudEvents (version 0.2?) for in/out
Some of this is already in the spec doc... but perhaps worth to explicitly add it to some conformance section?
I'd think we word these out, and have a clear, human-readable section. From there we can easily create some TCK / test-conformance-kit ?
Please have a look:
@lberk @aslom @alanconway @n3wscott @Harwayne @nachocano

Channel spec: iteration 1

---

test/e2e-common.sh
test/upload-test-images.sh

Fixes #1507
Create a no-op alias for gcloud if not available in test scripts.

Make gcloud a no-op if not available for test scripts

---

test/e2e-common.sh

Fixes #1536
https://github.com/knative/eventing/blob/1bfb3465ae0946e15b151ab9226203ff7ab66251/test/e2e-common.sh#L106
The above statement is called when all the test resources are uninstalled. But knative-eventing namespace is still present and will be present untill https://github.com/knative/eventing/blob/1bfb3465ae0946e15b151ab9226203ff7ab66251/test/e2e-common.sh#L80 is invoked, as a result e2e-test script waits until ```wait_until_object_does_not_exist ``` function times out and then deletes the knative-eventing namespace based on the ```--skip-knative-setup``` parameter
- Semantically rearranging statement  ``` wait_until_object_does_not_exist namespaces knative-eventing ``` and making it part of knative-teardown function as :
```shell
function knative_teardown() {
echo ">> Stopping …
```

Fixing knative eventing namespace teardown step

---

config/400-source-controller-service.yaml
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/resources/filter.go
pkg/reconciler/broker/resources/ingress.go
pkg/reconciler/testing/service.go

Partially address #1225 
- Add prometheus scrape annotation to services that export metrics. So those metrics can be scraped by prometheus
```release-note
None
```

Add scrape annotation to services exporting metrics

---

config/300-apiserversource.yaml
config/300-broker.yaml
config/300-channel.yaml
config/300-clusterchannelprovisioner.yaml
config/300-containersource.yaml
config/300-cronjobsource.yaml
config/300-eventtype.yaml
config/300-sequence.yaml
config/300-subscription.yaml
config/300-trigger.yaml
config/channels/in-memory-channel/300-in-memory-channel.yaml

Fixes #1546 
- Change CustomResourceDefinition.spec.version to versions.
```release-note
CRD definitions use versions instead of version.
```

issue 1546: change version->versions for CRD definitions

---

config/200-clusterrole-namespaced.yaml

Mirroring the changes in knative/serving PR4358 this patch adds
knative-eventing-namespaced-admin role so that way admin users
can access knative eventing resources.  This is helpful/important in
multi-tenant clusters, otherwise we have to add the rbac rule manually.

Similar to serving, add permissions to admin default roles

---

contrib/natss/pkg/dispatcher/dispatcher.go

Fixes https://github.com/knative/eventing/issues/1551
- Changing log level for headers in natss dispatcher to debug
```release-note
NONE
```

Disable logging headers in nats dispatcher

---

docs/spec/channel.md

Adding some of the feedback from #1420 to the channels spec

Channel spec revisions iterations

---

pkg/reconciler/broker/resources/channel.go
pkg/reconciler/broker/resources/channel_test.go
pkg/reconciler/broker/resources/subscription.go
pkg/reconciler/broker/resources/subscription_test.go

- Increase code coverage of broker/resources/{channel,subscription}.go.
Found because #1563 started failing due to low coverage of this file.
```release-note
NONE
```

Add unit tests for Broker's Channel and Subscription resources.

---

pkg/utils/utils_test.go

- Increase code coverage of utils.go.
Found because #1563 started failing due to low coverage of this file.
```release-note
NONE
```

Add code coverage for utils.go.

---

Gopkg.lock
pkg/adapter/apiserver/events/events.go
pkg/adapter/apiserver/events/events_test.go
pkg/adapter/cronjobevents/adapter.go
pkg/broker/receiver.go
pkg/broker/receiver_test.go
pkg/broker/ttl.go
test/test_images/heartbeats/main.go
test/test_images/sequencestepper/main.go
test/test_images/transformevents/main.go
vendor/github.com/knative/test-infra/scripts/e2e-tests.sh

Fixes #1471 
-  Update references of EventContext to V03
```release-note
NONE
```

Migrate to use v0.3 of CloudEvents Spec

---

pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/apiserversource/apiserversource_test.go

- ApiServerSource updates its receive adapter, if needed.
```release-note
ApiServerSources will update existing receive adapters if their arguments have 
changed. This may cause changes made in the past to suddenly take effect. 
```

ApiServerSource updates its receive adapter, if needed.

---

config/monitoring/metrics/grafana/100-grafana-dash-eventing.yaml
docs/metrics.md

Fixes #1225 
- Add an eventing dashboard to Grafana
- Add instructions to metrics.md to access metrics with Grafana and Prometheus
```release-note
Accessing metrics with Grafana and Prometheus is enabled. Follow the guidance in [metrics.md](https://github.com/knative/eventing/blob/master/docs/metrics.md) to understand details.
```

Add Grafana dashboard configuration

---

contrib/kafka/config/200-addressable-resolver-clusterrole.yaml
contrib/natss/config/200-addressable-resolver-clusterrole.yaml

- Add KafkaChannel and NatssChannel to the addressable-resolver ClusterRole.
```release-note
NONE
```

Add KafkaChannel and NatssChannel to the addressable-resolver ClusterRole.

---

cmd/webhook/main.go
config/500-webhook.yaml

Fixes https://github.com/knative/pkg/issues/417
Expose the RegistrationDelay so that user can set this env `REG_DELAY_TIME` in [500-webhook.yaml](https://github.com/knative/eventing/blob/master/config/500-webhook.yaml).

Expose the RegistrationDelay for webhook deployment

---

pkg/apis/messaging/v1alpha1/choice_lifecycle.go

- fix the propagation of Choice address

fix the propagation of Choice address

---

docs/spec/channel.md

- Channel retry recommendation 
@matzew @harwayne @alanconway @aslom comments?

Propose retry channel behavior

---

pkg/provisioners/channel_util.go
pkg/provisioners/channel_util_test.go
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/apiserversource/resources/receive_adapter_test.go
pkg/reconciler/broker/resources/subscription.go
pkg/reconciler/testing/apiserversource.go
pkg/reconciler/trigger/resources/subscription.go
pkg/utils/utils.go
pkg/utils/utils_test.go

- GenerateName ensures there is a dash between the prefix and the UID.
- As noticed by @lionelvillard in https://github.com/knative/eventing/pull/1602#issuecomment-517491978
```release-note
NONE
```

GenerateName ensures there is a dash between the prefix and the UID.

---

config/300-apiserversource.yaml
config/300-cronjobsource.yaml

Helps with #1550
- Adding a `registry` property in CronJobSource and ApiServerSource CRDs, with the `eventTypes` they can produce.
- Removing unnecessary apiVersion, kind and metadata.
```release-note
CronJobSource and ApiServerSource are discoverable. By describing their CRDs, you can identify what are the event types they can produce.
```

Add eventTypes to CronJobSource and ApiServerSource CRDs

---

hack/README.md

Fixes #830.
**[Rendered](https://github.com/grantr/eventing/blob/release-process/hack/README.md)**
As an eventing contributor, I want a concise ordered list of commands to run, but the docs in test-infra don't have those. 
These steps were previously documented in #1020 but removed in #1548, replaced with a (less discoverable) comment in `hack/release.sh` linking to https://github.com/knative/test-infra/tree/master/ci.
/cc @adrcunha

Document steps to create a release

---

test/e2e-common.sh

- The current `e2e-tests.sh` will fail on MAC because of the implementation difference for `sed` command on MAC and Linux. This PR will make it use `gsed` if the current operating system is MAC OS.
Reference:
https://github.com/GoogleCloudPlatform/cloud-run-events/blob/f7e9e75106d256f9a3c6f94f5b6e77a7a7a23c80/hack/update-codegen.sh#L21
```release-note
NONE
```
/cc @grantr 
/cc @Harwayne

Make e2e-tests.sh work on MAC

---

pkg/reconciler/containersource/containersource.go
pkg/reconciler/containersource/containersource_test.go
pkg/reconciler/containersource/resources/deployment.go
pkg/reconciler/containersource/resources/deployment_test.go

Helps with #1250
- ContainerSource uses fixed names for its receive adapter Deployment.
```release-note
ContainerSource will delete its old receive adapter Deployment only if the ContainerSource
is Ready=True. If the ContainerSource never reaches Ready=True, then a subsequent 
release will ignore any old GenerateName based receive adapter Deployments. They
will be garbage collected when the ContainerSource itself is deleted. 
```

ContainerSource uses fixed names, rather than GenerateName

---

config/200-clusterrole-namespaced.yaml
contrib/kafka/config/200-channelable-manipulator-clusterrole.yaml
contrib/kafka/config/200-controller-clusterrole.yaml
contrib/kafka/config/200-dispatcher-clusterrole.yaml
contrib/kafka/config/200-dispatcher-service.yaml
contrib/kafka/config/200-serviceaccount.yaml
contrib/kafka/config/200-webhook-clusterrole.yaml
contrib/kafka/config/201-clusterrolebinding.yaml
contrib/kafka/config/300-kafka-channel.yaml
contrib/kafka/config/400-webhook-service.yaml
contrib/kafka/config/500-controller.yaml
contrib/kafka/config/500-dispatcher.yaml
contrib/kafka/config/500-webhook.yaml
contrib/kafka/config/provisioner/kafka.yaml
contrib/natss/config/200-channelable-manipulator-clusterrole.yaml
contrib/natss/config/200-controller-clusterrole.yaml
contrib/natss/config/200-dispatcher-clusterrole.yaml
contrib/natss/config/200-dispatcher-service.yaml
contrib/natss/config/200-serviceaccount.yaml
contrib/natss/config/201-clusterrolebinding.yaml
contrib/natss/config/300-natss-channel.yaml
contrib/natss/config/500-controller.yaml
contrib/natss/config/500-dispatcher.yaml
contrib/natss/config/provisioner/provisioner.yaml
hack/release.sh

- Automatically update version labels in release artifacts when a tagged release is generated
- Add release labels to non-ConfigMap objects that don't have them, mainly Kafka and NATSS channels.
/cc @n3wscott

Automatic release version labels

---

test/base/resources/constants.go
test/base/resources/kube.go
test/common/creation.go
test/common/typemeta.go
test/e2e/choice_test.go
test/test_images/filterevents/main.go

Fixes #1590 
- Add one Choice e2e test
Not perfect as it misses an assertion about not having a message in the log.

Add e2e test for Choice

---

contrib/gcppubsub/config/gcppubsub.yaml

- Adding release label to gcppubsub channel provisioner
```release-note
NONE
```

Adding release label to GCPPubSub

---

pkg/broker/ingress/ingress_handler.go
pkg/broker/metrics.go
pkg/broker/receiver.go

This measures the time from when an event is received by the broker
ingress until it is delivered to the trigger function.
Closes #1371
- Measure time from when an event is received by broker ingress until it is delivered to the trigger function
```release-note
Adds `broker_to_function_delivery_time` metric to measure the time from when an event is received by broker ingress until it is delivered to the trigger function.
```

Measure time from arrival at ingress to delivery

---

docs/metrics.md

Fixes #1635 
- Documents the new metric that measures time between ingress at broker to delivery to trigger function
```release-note
NONE
```

Add new broker-to-trigger delivery time metric to docs

---

docs/decisions/discovery-and-faas-support.md

Fixes #1381
Records user model direction detailed in 1381 as a plan of record for solving the user scenarios detailed in the issue.
No release note, since implementation won't land until 0.9.0
```release-note
NONE
```

Decision for #1381

---

config/300-trigger.yaml

- Adding attributes field inside filter in Trigger CRD yaml file.
```release-note
NONE
```

Adding missing attributes field in Trigger CRD yaml

---

pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go

- Sort the subscriptions by UID to ensure we don't churn just by changing the order.
```release-note
NONE
```

Sort the subscriptions by UID

---

cmd/broker/ingress/main.go
pkg/broker/receiver.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/resources/filter.go
pkg/reconciler/broker/resources/ingress.go
pkg/reconciler/testing/deployment.go

Fixes #1656 
- add liveness check for the Broker Ingress
- add liveness and readiness check for the Broker filter
- add liveness and readiness probe spec for broker reconciler 
```release-note
```

Issue 1656: Liveness and Readiness Checks for the Broker Ingress and Filter

---

Gopkg.lock
vendor/knative.dev/test-infra/scripts/e2e-tests.sh

catch another cluster creation failure in e2e tests

Update test-infra to the latest version

---

Gopkg.lock
cmd/webhook/main.go
config/500-webhook.yaml
third_party/VENDOR-LICENSE
vendor/github.com/rogpeppe/go-internal/LICENSE
vendor/github.com/rogpeppe/go-internal/semver/semver.go

- Update to serving style webhook starter.
- Use strict webhook.
```release-note
Strict is enable. Which means random junk in a spec will be rejected by the webhook.
```
/cc @mattmoor

Update to use serving style webhook constructor. Use strict webhook.

---

pkg/logconfig/config.go
pkg/logging/logging.go
pkg/metrics/config.go
pkg/provisioners/message_receiver.go

While looking for more dead code, especially regarding our old CCP library (here and in `eventing-contrib`), I found more (generally) unused code bits
- removing code, not used (some of these are not used b/c counter parts in `knative/pkg` repo)
```release-note
```

Removing code that's not used at all

---

test/performance/broker-latency/dev.config

This is a benchmark config for the Broker latency test. You can see more configs at https://github.com/knative/serving/tree/master/test/performance.
This benchmark has been created in Mako [here](https://mako.dev/benchmark?benchmark_key=5903682180743168). Unfortunately Mako benchmark create, update, and data point create are limited to Googlers currently (https://github.com/google/mako/issues/2). We're trying to find solutions and workarounds to this with the Mako team.
Fixes #1696.
- Add a dev Mako config for the broker latency test.

Add a dev Mako config for broker latency test

---

cmd/broker/filter/main.go
pkg/broker/context.go
pkg/broker/filter/filter_handler.go
pkg/broker/filter/filter_handler_test.go
pkg/broker/filter/metrics.go
pkg/broker/ingress/ingress_handler.go
pkg/broker/ingress/metrics.go
pkg/broker/metrics.go
pkg/broker/ttl.go

Helps with #1693
- Creating a `filter` package within `pkg/broker`, to match our `cmd` structure, as well as `pkg/broker/ingress`. 
- This will make easier to have separate statsReporters for metrics (to be done in a follow up PR)
```release-note
NONE
```

Refactoring Broker Filter

---

pkg/broker/ingress/ingress_handler.go
pkg/broker/ingress/ingress_handler_test.go
pkg/broker/metrics.go
vendor/knative.dev/pkg/tracing/opencensus.go

Fixes #
- Inject trace into HTTP header
- Set extension attribute (traceparent) into CloudEvent
-
```release-note
```NONE

Broker preserves TraceIDs from incoming requests

---

pkg/broker/filter/filter_handler.go
pkg/channel/fanout/fanout_handler.go
pkg/reconciler/inmemorychannel/dispatcher/controller.go

Fixes all of @mattmoor 's problems.
- Don't use a 1 minute timeout when the runtime contracts for serving say at least 15 minutes.
```release-note
channel/broker timeouts are now longer: 15 minutes (use to be 1 minute).
```

1 minute timeout is too short.

---

DEVELOPMENT.md

- Installation of channels should be after installation of eventing controller which includes the creation of the namespace `knative-eventing`.
- Right now, installation of channels fails as `knative-eventing` namespace does not exist yet.
```release-note
NONE
```

Fixed development doc

---

pkg/apis/eventing/v1alpha1/trigger_defaults.go
pkg/apis/eventing/v1alpha1/trigger_defaults_test.go
pkg/broker/filter/filter_handler.go

Helps with #1693
- Setting a broker label to triggers in the webhook. This will allow stackdriver to call us and list triggers with a broker selector. The trigger.spec.broker is immutable, so it's safe to set it once here.
- This won't be added to existing Triggers. For doing so, we should do changes in the reconciler.
- Fixing bug in the report of event processing time (my bad!)
```release-note
NONE
```

Setting Broker label to Triggers in the Webhook

---

pkg/defaultchannel/channel_defaulter.go
pkg/defaultchannel/channel_defaulter_test.go
test/base/resources/constants.go
test/common/creation.go
test/common/typemeta.go
test/e2e/channel_defaulter_test.go
test/e2e/helpers/channel_defaulter_test_helper.go
test/performance/latency_test.go

Fixes #1711
- Add E2E test for default `Channel`. The E2E test covers the cluster-wide and namespace-wide defaulters.
```release-note
NONE
```
/cc @nachocano

Add E2E test for default channel

---

test/e2e_flags.go

Test would fail with go1.13 as it changed where testing flags are registered, fixing it by deleting explicit flag parsing like in https://github.com/knative/serving/pull/5398
/cc @mattmoor 
/cc @n3wscott 
/cc @adrcunha

eventing test work with go1.13

---

test/test_images/latencymako_sender_receiver/main.go

- Ce-Time is written by the Broker ingress, not by the receiver, so it's wrong to read that timestamp here.
```release-note
NONE
```
/assign grantr
/assign Fredy-Z
ping @slinkydeveloper

Fix wrong received timestamp in latency test

---

OWNERS_ALIASES

Dushyanth is no longer on this team and I do not have any expertise to help at this time.

Remove dushyanthsc and coryrc as productivity-reviewers

---

test/performance/tools/README.md
test/performance/tools/common.sh
test/performance/tools/recreate_clusters.sh
test/performance/tools/update_clusters.sh

This PR sets up scripts that we can call at a schedule to recycle the clusters for performing eventing benchmarking.
/cc @grantr 
/cc @Fredy-Z

Add scripts to recreate and update clusters for bechmarking eventing

---

Gopkg.toml

All Mako-dependent code moved to pkg, so we don't need this constraint anymore.
Fixes this message on running `hack/update-deps.sh`:
```
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:
✗  github.com/google/mako
However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.
Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.
```

Remove unnecessary mako constraint

---

DEVELOPMENT.md

Fixes #
Currently the ko apply -f config/ will result in Pods failing to pull images due to image path missmatch.
-
-
-
```release-note
```

Fix knative path to match the image paths

---

test/performance/README.md
test/performance/tools/README.md
test/performance/tools/common.sh
test/performance/tools/update_clusters.sh

- Fix typo in test/performance/tools/README.md
- Fix some bugs in perf tools scripts and refactor a bit
- Add a README in test/performance explaining how to create the `config-mako` ConfigMap
/area test/performance

Fix bugs in perf tools scripts and add docs for Mako ConfigMap

---

test/test_images/latencymako/request_interceptor.go
test/test_images/latencymako/request_interceptor_test.go
test/test_images/latencymako/sender_receiver.go

Due to a dependency of #1831 on #1829, the latter was merged despite some minor [pending comments](https://github.com/knative/eventing/pull/1829#pullrequestreview-285738742). This PR addresses them.
- Move `requestInterceptor` type to its own file and add a unit test for it
- Pass parent context to subroutines (CloudEvents receiver, etc.) instead of using `Background()`
```release-note
NONE
```
/assign grantr
/assign slinkydeveloper

Address review comments for broker-latency perf test

---

test/performance/broker-latency/prod.config

I have updated the benchmark in mako to allow the owner. This PR updates the config in the repo.

Allow the service account to be a benchmark owner

---

cmd/apiserver_receive_adapter/main.go
cmd/cronjob_receive_adapter/main.go
config/300-apiserversource.yaml
config/300-containersource.yaml
config/300-cronjobsource.yaml
docs/decisions/discovery-and-faas-support.md
docs/decisions/reverted-sources-to-importers.md
docs/mission.md
pkg/adapter/apiserver/adapter_test.go
pkg/apis/duck/v1alpha1/resource_types.go

Fixes https://github.com/knative/eventing/issues/1857
- Revert Revert Source to Importer decision.
- Remove importer tags.
```release-note
NONE.
```

Revert Source to Importer decision.

---

test/e2e/helpers/channel_defaulter_test_helper.go

The e2e test for `NatssChannel` is flaky, see https://testgrid.knative.dev/eventing-contrib#continuous.
The reason is in the test for `DefaultChannel`, after we update the configmap, the change is not immediately synced to the `channeldefaulter` singleton. Since the resync time is set to 0 in `configMapWatcher`, adding 5 seconds sleep should be enough to fix this issue.
```release-note
NONE
```
/cc @grantr

Add arbitrary sleep after updating configmap in e2e test for defaultchannel

---

config/config-observability.yaml
docs/metrics.md

Helps with #1693
- Removing unused logging configs.
- Updating current metrics documentation with stackdriver configuration and updated metric names
- Should be moved to knative/docs --> See https://github.com/knative/docs/issues/1792
```release-note
NONE
```

Updating metrics documentation

---

pkg/reconciler/testing/factory.go

This is broken by the K8s test libs starting in 1.14, and to work properly we would need to patch vendor to partially revert the library change.
The intent of this is to remove the logic to avoid having someone unknowingly start to depend on this functionality, which keeps eventing from having to carry this patch.

Stop using PrependGenerateNameReactor.

---

Gopkg.lock
test/common/test_runner.go
third_party/VENDOR-LICENSE
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/k8s.io/apiserver/LICENSE
vendor/k8s.io/apiserver/pkg/storage/names/generate.go

Fixes #1824 
- Use the GenerateName function from K8s to make the namespace names unique.
```release-note
NONE
```

Tests effectively use GenerateName for their Namespace

---

cmd/apiserver_receive_adapter/main.go
config/300-apiserversource.yaml
pkg/adapter/apiserver/adapter.go
pkg/adapter/apiserver/adapter_test.go
pkg/adapter/apiserver/controller.go
pkg/adapter/apiserver/controller_test.go
pkg/adapter/apiserver/resource.go
pkg/apis/sources/v1alpha1/apiserver_types.go
pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
pkg/reconciler/apiserversource/resources/receive_adapter.go
pkg/reconciler/apiserversource/resources/receive_adapter_test.go
test/e2e/source_api_server_test.go

Fixes #1262 
- APIServerSource supports filtering objects by their controller apiVersion and kind

APIServerSource now supports filtering by controller apiVersion and kind

---

cmd/webhook/main.go
pkg/apis/sources/v1alpha1/apiserver_defaults.go
pkg/apis/sources/v1alpha1/apiserver_defaults_test.go
pkg/apis/sources/v1alpha1/apiserver_validation.go
pkg/apis/sources/v1alpha1/apiserver_validation_test.go
pkg/apis/sources/v1alpha1/containersource_defaults.go
pkg/apis/sources/v1alpha1/containersource_defaults_test.go
pkg/apis/sources/v1alpha1/containersource_validation.go
pkg/apis/sources/v1alpha1/containersource_validation_test.go
pkg/apis/sources/v1alpha1/cron_job_defaults.go
pkg/apis/sources/v1alpha1/cron_job_defaults_test.go
pkg/apis/sources/v1alpha1/cron_job_validation.go
pkg/apis/sources/v1alpha1/cron_job_validation_test.go
pkg/reconciler/containersource/containersource_test.go
pkg/reconciler/cronjobsource/cronjobsource_test.go

Fixes #1196
- Add validation for all source API
```release-note
NONE
```

Add validation for sources API

---

test/README.md
test/common/creation.go
test/common/test_runner.go

Signed-off-by: Doug Davis <dug@us.ibm.com>
While trying to get the e2e tests to work with a private registry I had to make some "interesting"
choices. This PR isn't all of them, but they're most of the ones I can share at this time. They include:
- when creating the various "cluster roles", if the role already exists then we just ignore the error. TBH, I'm not sure why other people are not seeing this, perhaps my env already has them by default, or perhaps they're left around from a previous run and never got cleaned up, but either way, I don't think this should be a test-stopping error condition.
- I added code to look for a secret in the `default` namespace called
`kn-eventing-test-pull-secret` when creating new namespaces and service accounts. And
if it exists, we will now inject that …

tweaks to get tests to work with private registry

---

pkg/reconciler/trigger/trigger.go
pkg/reconciler/trigger/trigger_test.go

Fixes #1911 
- Mark Dependency status as Unknown when the dependency object’s ObjectMetadata.Generation and Status.ObservedGeneration are not equal during the trigger reconcile process 
- Added unit tests
-
```release-note
None
```

Mark Dependency status as Unknown when the dependency object's generation is not equal

---

pkg/reconciler/broker/broker_test.go

- clean up function, removing unused argument, was forgotten in #1177:
See https://github.com/knative/eventing/pull/1177/files#diff-f3fabcf3d904609f4ca155fc0d3648cfL1729-L1730  
/assign @grantr

Remove the unused containerName string

---

pkg/inmemorychannel/dispatcher_test.go
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/apiserversource/controller_test.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/controller_test.go
pkg/reconciler/channel/channel_test.go
pkg/reconciler/channel/controller_test.go
pkg/reconciler/containersource/containersource_test.go
pkg/reconciler/containersource/controller_test.go
pkg/reconciler/cronjobsource/controller_test.go
pkg/reconciler/cronjobsource/cronjobsource_test.go
pkg/reconciler/eventtype/controller_test.go
pkg/reconciler/eventtype/eventtype_test.go
pkg/reconciler/inmemorychannel/controller/controller_test.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
pkg/reconciler/namespace/controller_test.go
pkg/reconciler/namespace/namespace_test.go
pkg/reconciler/parallel/controller_test.go
pkg/reconciler/parallel/parallel_test.go
pkg/reconciler/sequence/controller_test.go
pkg/reconciler/sequence/sequence_test.go
pkg/reconciler/subscription/controller_test.go
pkg/reconciler/subscription/subscription_test.go
pkg/reconciler/testing/factory.go
pkg/reconciler/trigger/controller_test.go
pkg/reconciler/trigger/trigger_test.go
vendor/knative.dev/pkg/logging/testing/util.go
vendor/knative.dev/pkg/reconciler/testing/context.go

/lint
Part of https://github.com/knative/pkg/issues/643
- Remove logger cache cleanup
```release-note
NONE
```
/cc @vagababov

Remove test logger cache cleanup, and create one logger per test

---

Gopkg.lock
pkg/channel/message.go
pkg/channel/message_dispatcher.go
pkg/channel/message_receiver.go
pkg/channel/message_receiver_test.go
test/conformance/helpers/channel_tracing_test_helper.go
test/conformance/helpers/tracing/traces.go

Helps with #1765.
- Improve InMemoryChannel tracing, likely the other Channel implementations too.
- Increase the scope of the TestChannelTracing E2E test to actually assert things about the trace being generated.
```release-note
NONE
```

Improve InMemoryChannel tracing

---

Gopkg.lock
cmd/apiserver_receive_adapter/main.go
cmd/broker/filter/main.go
cmd/broker/ingress/main.go
cmd/cronjob_receive_adapter/main.go
cmd/webhook/main.go
vendor/knative.dev/pkg/controller/controller.go
vendor/knative.dev/pkg/injection/sharedmain/main.go
vendor/knative.dev/pkg/logging/testing/util.go
vendor/knative.dev/pkg/metrics/memstats.go
vendor/knative.dev/pkg/signals/signal_posix.go

```release-note
Expose Go's runtime.MemStats as opencensus metrics.
```
See: https://github.com/knative/pkg/pull/711

Ensure all of the Eventing binaries expose the new Go memstats.

---

pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/resources/channel.go
pkg/reconciler/broker/resources/channel_test.go

- renaming the `kn2` to `kne`, since we really just have one channel option (CRD, as CCP is dead)
created a broker from 0.9.0 release, and and did `ko apply` this change.
Two new channels were created:
```
...
inmemorychannel.messaging.knative.dev/default-kne-ingress   True             default-kne-ingress-kn-chan
nel.default.svc.cluster.local   2m45s
inmemorychannel.messaging.knative.dev/default-kne-trigger   True             default-kne-trigger-kn-chan
nel.default.svc.cluster.local   2m45s
...
```
The subscription went to READY:
```
internal-ingress-default-eb08e7c9-dddd-11e9-a185-ec2a10221838   True             3m10s
```
```release-note
This change has the potential to lose a few events right around the transition to the new (renamed) subscription
```

Rename kn2 to kne

---

config/300-apiserversource.yaml
config/300-cronjobsource.yaml

Helps with #1550
- Moving source registry information to CRDs annotations
```release-note
NONE
```

Source Registry

---

test/performance/tools/common.sh

The RBAC rules for configmap read need to be created in a different namespace, so we can't restrict the namespace here or kubectl will error out.
- Don't set a namespace when ko applying perf test config
/cc @chizhg

Don't restrict namespace for perf test objects

---

test/test_images/performance/dev.config

Fixes #
- adding @grac3gao and @capri-xiyue's email and service accounts to the dev mako configs
-
-
```release-note
```

adding email and service accounts to dev mako configs

---

cmd/webhook/main.go

Fatalw needs either a zap.Field or `key, value` pair in the variadic args.
Related to https://github.com/knative/serving/issues/5746
- Update Fatalw to correct syntax in webhook

Use the correct zap sugared logger syntax

---

config/200-clusterrole-namespaced.yaml

Similar changes to knative/serving#5683, allow a user to edit, view
eventing APIs

Add permissions for eventing APIs to k8s's default view and edit role

---

test/performance/tools/common.sh

We recycle the cluster for the benchmark every midnight, in a new cluster, there will not be any benchmark resources, so `ko delete` command will fail, see https://prow.knative.dev/?job=ci-knative-eventing-update-clusters. 
We should not abort the job if the deletion fails.
```release-note
NONE
```
/cc @grantr

Do not fail the performance cluster job if there's error in deletion

---

cmd/apiserver_receive_adapter/main.go
cmd/cronjob_receive_adapter/main.go

Helps with #1889
knative/pkg#741 tracks a more desirable fix.
- ApiServerSource and CronJobSource use their host name for traces.
```release-note
NONE
```

Remove incorrect host names from tracing setup.

---

config/200-source-observer-clusterrole.yaml
config/300-apiserversource.yaml
config/300-containersource.yaml
config/300-cronjobsource.yaml
docs/spec/README.md
docs/spec/sources.md
docs/spec/spec.md
test/performance/broker-latency/event_state/event_state.pb.go

Related to https://github.com/knative/eventing/issues/1554
- Add a first draft of a sources spec.
```release-note
Adding source-observer account and cluster roles to get and watch sources using aggregated RBAC roles.
```

Adding Source Spec.

---

test/performance/broker-imc/continuous/200-broker-imc.yaml
test/performance/broker-imc/dev.config
test/test_images/performance/aggregator.go
test/test_images/performance/dev.config
test/test_images/performance/kodata/dev.config
test/test_images/performance/main.go

- Replace `mako.Setup()` with `mako.SetupWithBenchmarkConfig()`, which allow passing benchmark key and benchmark name to it
- Instead of including benchmark key and benchmark name in the *.config, these two values will be stored in aggregator container's spec.args
- Only support dev environment currently, need to support prod later 
```release-note
```

Passing benchmark ids to mako setup 

---

test/common/cloudevents_vegeta_targeter.go

Fixes #2009 
- change content-type of performance tests to application/json
-
-
```release-note
None
```

change content-type of performance tests to application/json

---

test/common/client.go
test/common/creation.go
test/common/operation.go

Fixes #
- Tests only wait for Pods that they explicitly create.
```release-note
NONE
```

Tests only wait for Pods that they explicitly create.

---

pkg/apis/duck/v1alpha1/subscribable_types_test.go

fix testcases, duplicated if conditions in subscribe_types_test.go

---

test/conformance/broker_tracing_test.go
test/conformance/channel_tracing_test.go
test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_tracing_test_helper.go

- Refactor tracing tests to make it easier to use in other repos.
- `ChannelTracingTestHelper` will be used by most repos, as most will only have a single Channel to test.
- `ChannelTracingTestHelperWithChannelTestRunner` will be used by repos that have multiple Channels to test.
```release-note
NONE
```

Refactor tracing tests to make it easier to use in other repos.

---

test/base/resource_inspectors.go
test/common/operation.go

- `GetAddressableURI` supports status.addressable.url, in addition to status.addressable.hostname.
- `GetAddressableURI` will return an error if the host name is empty.
```release-note
NONE
```

GetAddressableURI supports status.addressable.url

---

config/300-broker.yaml
config/300-sequence.yaml
config/channels/in-memory-channel/300-in-memory-channel.yaml

Setting the URL of the broker instead of the hostname as additional column.
```release-note
NONE
```

Broker URL additional column

---

pkg/apis/eventing/v1alpha1/broker_types.go
pkg/apis/eventing/v1alpha1/eventtype_types.go
pkg/apis/eventing/v1alpha1/eventtype_types_test.go
pkg/apis/eventing/v1alpha1/trigger_types.go
pkg/apis/messaging/v1alpha1/channel_types.go
pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
pkg/apis/messaging/v1alpha1/parallel_types.go
pkg/apis/messaging/v1alpha1/sequence_types.go
pkg/apis/messaging/v1alpha1/subscription_types.go
pkg/apis/sources/v1alpha1/apiserver_types.go
pkg/apis/sources/v1alpha1/containersource_types.go
pkg/apis/sources/v1alpha1/cron_job_types.go
pkg/apis/sources/v1alpha1/cron_job_types_test.go

Fixes #1980 
- Make the resource types implement `HasUntypedSpec` so that the admission webhook extended from Knative/pkg will add the user info annotations (`xx.knative.dev/creator` and `xx.knative.dev/lastModifier`)
- Similar to https://github.com/knative/eventing/pull/1479, the business logic to add the annotations are tested in Knative/pkg. Thus, no tests here!
```release-note
NONE
```

Add missing user info annotations on resources (#1980)

---

test/conformance/helpers/tracing/zipkin.go

Might help with #2040.
- E2E tracing tests does not set sampling to 100%.
```release-note
NONE
```

E2E tracing tests does not set sampling to 100%.

---

pkg/apis/sources/v1alpha1/apiserver_types.go

ref. knative/pkg#775
- Remove `openapi-gen` annotations from types definitions. `openapi-gen` is not used anymore in Knative.
```release-note
NONE
```

Remove openapi-gen annotations

---

config/300-broker.yaml

CRD still used old channelTemplate/provisioner code
- update to channelTemplateSpec and apiVetrsion/kind
```release-note
```

Fixing outdated broker crd file

---

Gopkg.lock
Gopkg.toml
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/error.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go

- Add support for parsing v1.0 formatted cloudevents.
```release-note
BREAKING CHANGE: the new version of the cloudevents sdk no longer defaults content type to application/json if blank. Please set content type if required.
```
Cloudevents Golang SDK release: https://github.com/cloudevents/sdk-go/releases/tag/v0.10.0

Update to cloudevents golang sdk v0.10.0, adding v1.0 spec support.

---

test/e2e_flags.go

Might help with #2040
I just realized the e2e tests are only flaky for the continuous runs, but not for the presubmit tests. And the only difference between them is the continuous runs set `--emit-metrics` to be true, it seems to be something legacy and have conflict with the trace setting in eventing e2e test. And we should be able to safely remove it.
```release-note
NONE
```

Do not emit metrics in e2e test

---

config/200-controller-clusterrole.yaml

Running on Openshift 4.2 and setting the `KafkaChannel` as the default `Channel`, creating a channel does not work, and the status of the generic `Channel` says:
```
Channel reconcile error: problem reconciling the backing channel: kafkachannels.messaging.knative.dev "greetings-channel" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```
related to:
* #1450
* #1495

fixing RBAC for finalizers sub-resource of Channel

---

config/300-broker.yaml
config/300-channel.yaml
config/300-parallel.yaml
config/300-sequence.yaml
config/channels/in-memory-channel/300-in-memory-channel.yaml

- Label Broker, Channel, Parallel, Sequence CRDs with `duck.knative.dev/addressable: "true"`
```release-note
Broker, Channel, Parallel, Sequence CRDs are now labeled with duck.knative.dev/addressable: "true"
```

Adding standard duck label on CRD to signal this resource adheres to Addressable

---

Gopkg.lock
cmd/webhook/main.go
config/500-webhook-configuration.yaml
config/500-webhook.yaml
vendor/knative.dev/pkg/apis/duck/README.md
vendor/knative.dev/pkg/webhook/config_validation_controller.go
vendor/knative.dev/pkg/webhook/resource_admission_controller.go
vendor/knative.dev/pkg/webhook/webhook.go

This imports knative/pkg#802 and explicitly creates the
webhook configurations that updates, and handles the breaking struct changes.
Related: knative/serving#5845
/hold
Until upstream PR lands

Add yaml to explicitly create our webhook configs.

---

Gopkg.lock
test/performance/performance-tests.sh
vendor/knative.dev/test-infra/scripts/performance-tests.sh

- All performance test infra shares one single service account, which is `mako-job@knative-performance.iam.gserviceaccount.com`
```release-note
NONE
```
/cc @grantr 
/cc @nachocano

All performance test infra shares one single service account

---

pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/testing/apiserversource.go

Related to #1918
Relates to #2089
- Update ApiServerSource to warn on setting deprecated ref.
```release-note
Adding deprecated warning message when using old spec.sink.[ref] fields for ApiServerSource.
```

Update ApiServerSource to warn on setting deprecated ref.

---

pkg/reconciler/subscription/subscription.go
pkg/reconciler/testing/subscription.go

- Fix typo in conditions warning message. Use consistent message with other deprecation warnings.
```release-note
NONE
```

use consistent deprecation warning message

---

config/300-containersource.yaml
pkg/apis/sources/v1alpha1/containersource_lifecycle.go
pkg/apis/sources/v1alpha1/containersource_types.go
pkg/apis/sources/v1alpha1/containersource_validation.go
pkg/apis/sources/v1alpha1/containersource_validation_test.go
pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
pkg/reconciler/containersource/containersource.go
pkg/reconciler/containersource/containersource_test.go
pkg/reconciler/containersource/controller.go
test/e2e/source_container_test.go

Related to #1918 
- Update type of `spec.sink` field in ContainerSource to Destination. This adds `spec.uri` and `spec.ref` fields.
- Destination includes deprecated ObjectReference fields for backward compatibility.
```release-note
ContainerSource now uses the Destination API for `spec.sink`, with properties `ref` (an
ObjectReference) and `uri` (an absolute URL or URI reference). The previous `sink`
properties `apiVersion`, `kind`, and `name` have been deprecated and will be removed
in a future release. To preserve existing behavior, move those fields under
`spec.sink.ref`.
```

Update ContainerSource to use Destination

---

pkg/adapter/apiserver/events/events.go
pkg/adapter/apiserver/events/events_test.go
pkg/adapter/cronjobevents/adapter.go

Fixes #2124 
- Set the application/json in cronjob / apiserver sources.
-
-
```release-note
- cronjob / apiserver sources now set application/json when emitting events.
```

add application/json encoding

---

test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml

- Fix the channel-imc benchmark configuration file due to the change in https://github.com/knative/eventing/pull/1979
```release-note
NONE
```
/cc @grantr

Fix channel imc benchmark

---

OWNERS

- remove vaikas-google (since vaikas was added in earlier PR).
```release-note
NONE
```

remove vaikas-google from OWNERS

---

Gopkg.lock
config/200-sourcecontroller-clusterrole.yaml
pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
pkg/apis/sources/v1alpha1/apiserver_lifecycle_test.go
pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/apiserversource/controller.go
pkg/reconciler/testing/apiserversource.go

Fixes #2112 
- add SufficientPermission condition on APIServerSource
```release-note
The APIServer source now reports whether there is enough permission to get/watch/list configured resources 
```

add SufficientPermission condition on APIServerSource

---

test/e2e/helpers/channel_defaulter_test_helper.go

- Test does not panic if the default channel config has nil values.
```release-note
NONE
```

Test does not panic if the default channel config has nil values

---

test/e2e/helpers/channel_defaulter_test_helper.go

Cherry pick of #2164 into release-0.10.
- Test does not panic if the default channel config has nil values.
```release-note
NONE
```

Test does not panic if the default channel config has nil values 

---

cmd/controller/main.go
cmd/webhook/main.go
config/200-addressable-resolvers-clusterrole.yaml
config/200-controller-clusterrole.yaml
config/300-flows-parallel.yaml
config/300-flows-sequence.yaml
test/base/resources/constants.go
test/common/creation.go
test/common/typemeta.go
test/e2e/flows_parallel_test.go
test/e2e/flows_sequence_test.go

Fixes #1913 
- Wire up the controllers, webhooks + e2e tests
```release-note
* Introduce parallels.flows.knative.dev and sequences.flows.knative.dev
```

wire up controllers / webhooks and add e2e tests

---

pkg/reconciler/parallel/parallel_test.go
pkg/reconciler/parallel/resources/subscription.go
pkg/reconciler/sequence/resources/subscription.go
pkg/reconciler/sequence/sequence_test.go

- move resource creation for Subscription from eventing.knative.dev to messaging.knative.dev where it lives.
- I think this worked "in real life" because we use typed clients in the reconcilers and hence they
didn't use this type. But, in any case it's wrong.
```release-note
NONE
```

subscription lives in messaging

---

test/performance/benchmarks/broker-imc/cluster.yaml
test/performance/benchmarks/channel-imc/cluster.yaml

The current performance benchmarks does not require much resource. The following is the peak usage:
```
chizhg@chizhg-macbookpro:~/Downloads$ ku top node
NAME                                                  CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
gke-eventing--broker-imc-default-pool-49ebcbe4-dlnv   102m         2%     730Mi           5%
gke-eventing--broker-imc-default-pool-49ebcbe4-m4x7   871m         22%    997Mi           8%
gke-eventing--broker-imc-default-pool-49ebcbe4-nzc1   1587m        40%    1081Mi          8%
gke-eventing--broker-imc-default-pool-76ee586b-3q2z   51m          1%     857Mi           6%
gke-eventing--broker-imc-default-pool-76ee586b-nfnx   592m         15%    905Mi           7%
gke-eventing--broker-imc-default-pool-76ee586b-vhgd   971m         24%    866Mi …
```

Make the cluster smaller for performance testing

---

pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
pkg/apis/sources/v1alpha1/containersource_lifecycle.go
pkg/apis/sources/v1alpha1/cron_job_lifecycle.go
pkg/reconciler/parallel/parallel.go
pkg/reconciler/sequence/sequence.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/testing/parallel.go
pkg/reconciler/testing/sequence.go
pkg/reconciler/testing/subscription.go

- Previously some of the deprecation messages explicitly stated that they will be removed in 0.11, change that to just say future instead.
```release-note
```

Change deprecation warning from 0.11 to say future instead

---

test/common/config.go
test/common/test_runner.go
test/common/typemeta.go
test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_header_single_event_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/conformance/main_test.go
test/e2e/flows_parallel_test.go
test/e2e/flows_sequence_test.go
test/e2e/helpers/broker_channel_flow_test_helper.go
test/e2e/helpers/broker_event_transformation_test_helper.go
test/e2e/helpers/channel_chain_test_helper.go
test/e2e/helpers/channel_defaulter_test_helper.go
test/e2e/helpers/channel_event_tranformation_test_helper.go
test/e2e/helpers/channel_single_event_helper.go
test/e2e/main_test.go
test/e2e/parallel_test.go
test/e2e/sequence_test.go
test/e2e_flags.go

Fixes #2175 
- Channel tests key off of a full TypeMeta, not just a Kind that assumes messaging.knative.dev/v1alpha1.
```release-note
NONE
```

Channel tests key off of a full TypeMeta

---

test/common/config.go
test/common/test_runner.go
test/common/typemeta.go
test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_header_single_event_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/conformance/main_test.go
test/e2e/helpers/broker_channel_flow_test_helper.go
test/e2e/helpers/broker_event_transformation_test_helper.go
test/e2e/helpers/channel_chain_test_helper.go
test/e2e/helpers/channel_defaulter_test_helper.go
test/e2e/helpers/channel_event_tranformation_test_helper.go
test/e2e/helpers/channel_single_event_helper.go
test/e2e/main_test.go
test/e2e/parallel_test.go
test/e2e/sequence_test.go
test/e2e_flags.go

Cherry-picked https://github.com/knative/eventing/pull/2176
```release-note
NONE
```

Backport fix to e2e tests infra - Cherry-pick #2176

---

docs/spec/channel.md

- Switch the spec to require Binary HTTP mode, rather than Structured HTTP mode.
- Changing to structured HTTP mode was considered aspirational. It is clear that none of the implementations are doing so. Therefore, make the spec match the de facto standard.
```release-note
NONE
```

Switch the spec to require Binary HTTP mode, rather than Structured HTTP mode.

---

contrib/natss/pkg/reconciler/dispatcher/natsschannel.go

Restarting the natss dispatcher rendered channels unready if the connection to nats cannot be established before the reconciliation starts
- Rerun reconciliation in case of an error during the previous reconciliation

Trigger natschannel reconciliation if previous fails

---

Gopkg.lock
test/e2e-common.sh
vendor/knative.dev/test-infra/scripts/library.sh

- Use the common function to install Knative monitoring for eventing e2e tests - step3 of https://github.com/knative/serving/issues/5971
```release-note
NONE
```
/cc @adrcunha

Use the common function to install Knative monitoring

---

config/400-webhook-service.yaml
config/channels/in-memory-channel/200-dispatcher-service.yaml
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/resources/filter.go
pkg/reconciler/broker/resources/ingress.go

To be on safer side when using hand in hand with Istio, we follow service port naming convention as stated here ->https://istio.io/docs/setup/kubernetes/additional-setup/requirements/
Serving part already merged.
We have seen issue with istio as been discussed over here -> https://github.com/istio/istio/issues/14520
Fixes #
- Service port name should follow the istio naming convention based on this link:
https://istio.io/docs/setup/kubernetes/additional-setup/requirements/
```release-note
* Service port name should follow the istio naming convention based on this link:
https://istio.io/docs/setup/kubernetes/additional-setup/requirements/
```

Update service port's name based on istio naming convention

---

pkg/adapter/apiserver/adapter_test.go

Fixes #2045
If ListAndWatch is interrupted too early, the initialization goroutine clashed with the rest of the code. See https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L228
- Give some time for the reflectors to fully initialized. 
```release-note
```

attempt to fix race condition

---

test/performance/performance-tests.sh
test/test_images/performance/kodata/prod.config

- Remove the redundant patch command
- Remove the symbolic link for `prod.config` in kodata, as the file has been deleted
```release-note
NONE
```
/cc @grantr

Fix performance tests setup

---

test/common/performance/aggregator/aggregator.go
test/common/performance/receiver/receiver.go
test/common/performance/sender/http_load_generator.go
test/common/performance/sender/sender.go

This reverts PR #2218
Excludes from revert changes to pace in channel imc and broker-imc continuous configs

Revert "Record the throughput only once per second on Mako (#2218)"

---

pkg/broker/filter/filter_handler.go
pkg/broker/filter/filter_handler_test.go

I noticed that knative eventing brokers are (somewhere) accepting my CloudEvent 1.0 events and delivering 0.3.0 events on the other side of the broker. I trust this is not an intentional downgrade? I *think* this code is the cause. (I plan to verify soon)
```release-note
- Fix downgrade of CloudEvents to 0.3.0
```

fix downgrade to CE 0.3.0

---

OWNERS_ALIASES
test/common/performance/OWNERS
test/test_images/performance/OWNERS

based on thread/discussions here:
https://github.com/knative/eventing/pull/2218#issuecomment-558508392
I generally think that for `perf` (like productivity) we could have some more fine grain approvers for submodules.
- adding group for perf.
- adding @slinkydeveloper  to that too
```release-note
```

Adding group for PERF owners, based on perf WG/taskforce

---

test/common/performance/aggregator/aggregator.go

https://github.com/knative/eventing/pull/2229 broke performance test continuous runs, this PR fixes it.
```release-note
NONE
```
/cc @slinkydeveloper 
/cc @grantr

Fix performance tests by passing the publishResults flag value

---

cmd/webhook/main.go
config/500-webhook-configuration.yaml

This should address an issue that came up in slack where a breaking change was inadvertently introduced to the Eventing webhook when upgrading from 0.10 (it was renamed, and nothing cleans up the old one).  This basically ports over what we did in knative/serving to fix issues with both upgrade and downgrade.
Contributors running HEAD will unfortunately be broken (again) and need to run:
```shell
kubectl delete mutatingwebhookconfigurations defaulting.webhook.eventing.knative.dev
```
cc @grantr @akashrv 
/hold
Want to confirm that this fixes upgrade for @akashrv

Make upgrades from 0.10 (and downgrades) smoother.

---

pkg/channel/event_dispatcher.go
pkg/kncloudevents/good_client.go

- Similar as https://github.com/knative/eventing/pull/2054, we need to set `defaultMaxIdleConnections` and `defaultMaxIdleConnectionsPerHost` as higher values to get better performance
```release-note
NONE
```
/cc @grantr 
This is related to part of https://github.com/knative/eventing/issues/2238.

Set defaultMaxIdleConnections and defaultMaxIdleConnectionsPerHost for channel event dispatcher

---

pkg/apis/duck/v1alpha1/channelable_types.go
pkg/apis/duck/v1alpha1/channelable_types_test.go
pkg/apis/duck/v1alpha1/subscribable_types.go
pkg/apis/duck/v1alpha1/subscribable_types_test.go
pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
pkg/apis/messaging/v1alpha1/channel_validation.go
pkg/apis/messaging/v1alpha1/channel_validation_test.go
pkg/apis/messaging/v1alpha1/in_memory_channel_validation.go
pkg/apis/messaging/v1alpha1/in_memory_channel_validation_test.go
pkg/channel/fanout/fanout_handler.go
pkg/channel/fanout/fanout_handler_test.go
pkg/channel/multichannelfanout/multi_channel_fanout_handler_test.go
pkg/channel/multichannelfanout/parse_test.go
pkg/channel/swappable/swappable_test.go
pkg/reconciler/channel/channel_test.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go
pkg/reconciler/testing/subscription.go

- Change URIs that were strings to apis.URL objects.
- Wire compatible, so no user visible changes
```release-note
NONE
```

Change the remaining uri strings to apis.url

---

test/README.md

This commit changes `imagePulLSecret` field to `imagePullSecret`

Correct minor typo in test/README.md

---

pkg/adapter/apiserver/events/events.go
pkg/adapter/apiserver/events/events_test.go
pkg/adapter/cronjobevents/adapter.go

Fixes #
- make the soruces produce CE 1.0
```release-note
ApiServersource and CronjobSource produce CE 1.0 payload
```

Cloudevent 1.0 - Part1: Updating source to produce 1.0 payload

---

pkg/broker/filter/filter_handler.go
pkg/broker/ingress/ingress_handler.go

- As a comment in https://github.com/knative/eventing/pull/2244, change the log level to debug as it prints out a log for every event, which shadows other useful logs
- Fix #2246 , mostly because I don't want to submit such a small PR 😅 , but if you don't want this change, I can revert it 
```release-note
NONE
```
/cc @grantr 
/cc @akashrv

Followup for 2244 - Ttl fix

---

test/common/performance/aggregator/aggregator.go

If there is no sample point added for error throughput metric, plots in the aggregate chart will be disconnected and unintuitive, examples can be seen in https://mako.dev/benchmark?benchmark_key=4926580618952704&tseconds=604800 (the pink and blue plots)
This PR makes the change to at least add one sample point for error throughput metric, so the plots in aggregate chart will not break in the middle.
```release-note
NONE
```
/cc @slinkydeveloper

Add at least one sample point for error throughput

---

pkg/reconciler/cronjobsource/cronjobsource.go
pkg/reconciler/cronjobsource/cronjobsource_test.go

- Fix a nil pointer with cronjobsource when only specifying a URI.
```release-note
Fix a nil pointer with cronjobsource if using only URI.
```

fix nil pointer when using only uri to specify sink

---

pkg/reconciler/trigger/resources/subscription_test.go

- Add unit test for subscription resource generation for triggers.
```release-note
NONE
```

Adding unit test on subscription generation.

---

pkg/reconciler/broker/resources/filter_test.go

- Add new unit tests for resources created for the broker filter.
```release-note
none
```

Adding broker filter resource unit tests for more coverage.

---

pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/containersource/containersource_test.go

- Follow on to #2279 to make sure we don't regress. Add unit tests for only specifying the sink.URI.
```release-note
NONE
```

add only uri as sink for tests

---

pkg/reconciler/containersource/containersource.go
pkg/reconciler/containersource/containersource_test.go

Fixes #2267
- Fix nil ref in containersource if using deprecated fields and sink is not resolvable.
```release-note
* Fix nil ref in containersource if using deprecated fields and sink is not resolvable.
```

Fix the nil ref for when using deprecated fields

---

pkg/apis/eventing/v1alpha1/broker_validation.go

Fixes #
- provisioner is no longer a thing...
```release-note
```

nit: remove old provisioner/ccp reference

---

test/common/performance/sender/http_load_generator.go

- The Mako benchmarks are broken (all events failed to deliver) since https://github.com/google/knative-gcp/pull/437, send 1.0 cloudevents for perf tests to fix
```release-note
NONE
```
/cc @grantr 
/hold
Let me test it first.

Send 1.0 cloudevents for perf tests

---

cmd/webhook/main.go

/hold
I want to make sure the serving upgrade test is actually happy first (https://github.com/knative/serving/pull/6215), since this repo lacks coverage 😬 
Related to: https://github.com/knative/serving/issues/6037

Move webhooks to separate paths.

---

pkg/apis/eventing/v1alpha1/broker_lifecycle.go
pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
pkg/apis/eventing/v1alpha1/broker_types.go
pkg/apis/eventing/v1alpha1/test_helper.go
pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
pkg/reconciler/broker/broker.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/testing/broker.go
pkg/reconciler/trigger/resources/subscription.go
pkg/reconciler/trigger/trigger.go
pkg/reconciler/trigger/trigger_test.go
test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/uri.go

Fixes https://github.com/knative/eventing/issues/2254
Broker ingress channel is fully removed. Trigger `ReplyURL` is changed to the broker ingress directly.
A very brief testing shows a roughly 2-5ms roundtrip (from an event got replied until the same event got received) latency improvements with IMC backed broker.

Remove broker ingress channel

---

config/channels/in-memory-channel/500-dispatcher.yaml

Based on the benchmarking results in https://github.com/knative/eventing/issues/2311#issuecomment-565311345:
- set CPU request and limit to 1000m ~ 2200m
- set memory request and limit to 150Mi ~ 300Mi
```release-note
NONE
```
/cc @grantr 
/cc @nachocano

Set resource requests and limits for imc-dispatcher

---

pkg/reconciler/trigger/trigger.go
pkg/reconciler/trigger/trigger_test.go

- Log the correct error in the k8s Event emitted when Status Update fails.
```release-note
* Fix incorrect error message in Trigger.UpdateStatus.
```

fix incorrect error tacked to event when status fails

---

config/500-controller.yaml
pkg/reconciler/namespace/controller.go
pkg/reconciler/namespace/namespace.go
pkg/reconciler/namespace/namespace_test.go
pkg/reconciler/namespace/resources/secret.go
pkg/utils/secret.go
pkg/utils/secret_test.go
test/common/creation.go
test/common/test_runner.go

Fixes #1862 
- Check for a pull secret named broker-image-pull-secret in default namespace
- Copy broker-image-pull-secret into eventing-broker-ingress & eventing-broker-filter namespaces to be used when pulling from private registry.
```release-note
NONE
```

Fix for missing pull secrets in auto created namespaces

---

pkg/reconciler/namespace/namespace.go
pkg/reconciler/namespace/namespace_test.go

- When trying to copy a secret and it fails, emit Warning event.
- Follow up to #2245 
```release-note
NONE
```

when secret copy fails, emit warning event

---

Gopkg.lock
Gopkg.toml
test/common/performance/sender/http_load_generator.go
test/e2e/broker_default_test.go
test/test_images/filterevents/main.go
test/test_images/heartbeats/main.go
test/test_images/sendevents/main.go
test/test_images/sequencestepper/main.go
test/test_images/transformevents/main.go
vendor/github.com/cloudevents/sdk-go/alias.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go

1. Use cloudevents V01 in all eventing tests
2. Update cloudevents sdk to master, similar as https://github.com/google/knative-gcp/pull/448
```release-note
NONE
```
/cc @nachocano

Use cloudevents V01 in eventing tests

---

test/common/performance/aggregator/aggregator.go
test/common/performance/common/pace.go
test/common/performance/receiver/receiver.go
test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml
test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml

This PR contains a couple of optimizations, and has been proven to be able to provide more consistent results in the continuous benchmarking runs, see https://mako.dev/benchmark?benchmark_key=5683818216292352&tseconds=604800
- Run sender and receiver in two different containers, so there will be fewer race conditions for resources (I initially thought about using two pods, but since the two pods can be scheduled on two different nodes, the delivery latency will be inaccurate due to clock skews)
- When the number of events grows, the speed we read events from the channel sometimes cannot catch up with the speed we write, so the events in the channel will be quickly piled up, which makes the receive operation be blocking. This PR aggressively set the queue length so enqueue operation won't …

Performance test infra issue fixes and improvements

---

Gopkg.lock
Gopkg.toml

- update to cloudevents sdk 0.10.2
```release-note
NONE
```

update to cloudevents sdk 0.10.2

---

pkg/reconciler/namespace/namespace.go
pkg/reconciler/namespace/namespace_test.go

- If we fail to copy the secret return an error because broker should not be marked as ready in that case.
-
-
```release-note
When copying secrets to new namespace for broker, treat that as reconcile failure.
```

secret copy is a failure, return error

---

pkg/reconciler/broker/broker.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/flowsparallel/parallel.go
pkg/reconciler/flowsparallel/parallel_test.go
pkg/reconciler/flowssequence/sequence.go
pkg/reconciler/flowssequence/sequence_test.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go
pkg/reconciler/testing/broker.go
pkg/reconciler/testing/flowsparallel.go
pkg/reconciler/testing/flowssequence.go
pkg/reconciler/testing/inmemorychannel.go
pkg/reconciler/testing/subscription.go
pkg/reconciler/testing/trigger.go
pkg/reconciler/trigger/trigger.go
pkg/reconciler/trigger/trigger_test.go

- After reconcile loop (regardless of the result), set the ObservedGeneration to the original.Generation.
```release-note
ObservedGeneration now reflects reality for: Broker, Trigger, InMemoryChannel, Subscription, Parallel/Sequence (in flows apigroup).
```

Consistent observed generation

---

config/config-logging.yaml
config/config-observability.yaml
config/config-tracing.yaml

- Set the `eventing.knative.dev/release` label on all eventing ConfigMaps (logging, observability, tracing)
It makes those particular ConfigMaps easier to filter in informer factories, and keeps them consistent with Serving, which ConfigMaps already include a `serving.knative.dev/release` label.
```release-note
NONE
```

Set release label on ConfigMaps

---

config/200-controller-clusterrole.yaml

Related to #1495
Openshift we see
```
cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on
```
for the `Sequence`/`Parallel`, that is in the `flows.knative` APIgroup.
Hence applying the previous change to the new API group

Updating RBAC for new flows API group

---

pkg/apis/eventing/v1alpha1/trigger_lifecycle.go

Fixes #2260
Update trigger's status type 
- `Broker` -> `BrokerReady`
- `Dependency` -> `DependencyReady`
```release-note
Trigger's "Broker" status type is updated to "BrokerReady"; Trigger's "Dependency" status type is updated to "DependencyReady".
```

Update names of trigger status types to be more accurate.

---

config/channels/in-memory-channel/500-dispatcher.yaml

Fixes #2186
- Remove configmap volume mount from imc dispatcher deployment. SharedMain will read it.
**Testing** 
Manually modified config-logging and verified that new config reflected in imc dispatcher logs.
```release-note
None
```

Remove config-logging volume mount from imc dispatcher YAML.

---

test/conformance/broker_tracing_test.go
test/conformance/channel_tracing_test.go
test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_header_single_event_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/e2e/helpers/broker_channel_flow_test_helper.go
test/e2e/helpers/broker_event_transformation_test_helper.go
test/e2e/helpers/channel_chain_test_helper.go
test/e2e/helpers/channel_defaulter_test_helper.go
test/e2e/helpers/channel_dls_test_helper.go
test/e2e/helpers/channel_event_tranformation_test_helper.go
test/e2e/helpers/channel_single_event_helper.go
test/lib/test_runner.go

1. To run the e2e tests in eventing, sometimes it's not enough to run the tests directly, like for `Channel` in knative-gcp, which needs to duplicate a secret to the test namespace before running the tests.  This PR enables passing options to further configure the test client.
2. Now each time we run the tests, we create namespaces with random names for each tests, it would be fine to break the tests in the middle, as there will be no conflicts if the user wants to run the tests again after a short time. So remove the logic to disallow people break the tests in the middle.
```release-note
NONE
```
/cc @nachocano

Enable further setups for test client in e2e and conformance tests

---

test/e2e/helpers/broker_dls_test_helper.go

- I missed one test in https://github.com/knative/eventing/pull/2383
```release-note
NONE
```

Followup on "Enable further setups for test client in e2e and conformance tests"

---

Gopkg.lock
Gopkg.toml
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_marshal.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v1.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/extensions.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/value.go

- Update cloudevents SDK to 0.11.0
```release-note
CloudEvents SDK is updated to 0.11.0
```

Update cloudevents SDK to 0.11.0

---

hack/release.sh

Fixes https://github.com/knative/eventing/issues/1987
Docs PR: https://github.com/knative/docs/pull/2103
```release-note
Renamed eventing release artifact release.yaml => eventing.yaml
```

Rename eventing release artifact release.yaml => eventing.yaml

---

docs/spec/channel.md

Fixes #2392
Conformance doc changes for status usage requirements and subscriptions
```release-note
NONE
```

Adding status and subscriber info to channel conformance doc

---

config/500-webhook-configuration.yaml

`admissionregistration.k8s.io/v1` webhooks require `sideEffects` to be explicitly set to `None` or `NoneOnDryRun` otherwise will be rejected

webhooks need to specify sideEffects

---

pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go

Helps towards scaling down in-memory dispatcher to zero.
- The in-mem channel subscriblableStatus is now set by the imc controller
This is part of a multi-steps plan to make the imc-dispatcher a Deployment or a KService installed in the user-namespace. 
step 1: this commit
step 2: install the dispatcher in the user-ns, dispatcher still read global configmaps
step 3: disaptcher is a receive adapter, controller set configmaps 
step 4: controller deploys the dispatcher as a Kservice.

update subscriblestatus in imc controller instead of imc dispatcher

---

test/performance/infra/image_helpers.go
test/performance/infra/sender/http_load_generator.go
test/performance/infra/sender/http_load_generator_test.go
test/performance/infra/sender/load_generator.go
test/performance/infra/sender/sender.go

Fixes #2208
- Add flag --generate-payload-on-each-request (default true) that allows
selection of whether the load generator should create new body data for
each message or reuse the body data across all messages.
NONE

Allow the load generator to optionally reuse body data

---

pkg/apis/eventing/v1alpha1/trigger_validation.go
pkg/apis/eventing/v1alpha1/trigger_validation_test.go

- Validate labels created by trigger in webhook
A broker internally creates a subscription. The labels for the subscription are:
1. the trigger name
1. the broker name
Check code [here](https://github.com/knative/eventing/blob/27a00f551413988364f5804f0ca8dde3d7c290b1/pkg/reconciler/trigger/resources/subscription.go#L76).
There is a [restriction](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) on the format of a k8s label value. This PR introduces a check in the webook for the labels in order to provide fast user feedback.
```bash
$ k apply -f trigger_length_nok.yaml
Error from server (BadRequest): error when creating "trigger_length_nok.yaml": admission webhook "validation.webhook.eventing.knative.dev" denied the request: validation …
```

Validate labels created by trigger in webhook

---

test/performance/benchmarks/broker-imc/200-broker-perf.yaml

Fixes #
- Mount `config-mako` volume for mako stub sidercar container. 
Otherwise the container gives an error: `unable to determine benchmark info: lstat /etc/config-mako: no such file or directory`
```release-note
NONE
```
cc @grac3gao Did you run into this error?

Mount config-mako volume for mako stub sidercar container.

---

docs/broker/example_brokers.yaml

Fixes https://github.com/knative/eventing/issues/1912
- Remove ClusterChannelProvisioner naming from code
- Only file where I can still find it is <https://github.com/knative/eventing/blob/cce73feedf0770a06799cf637096f4edbe00299a/docs/spec/channel_060.md#L58> which describes the channel at version 0.6 which is fine because it used CCP.
```release-note
NONE
```

Remove ClusterChannelProvisioner leftover

---

test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml

In broker-imc/continuous, the sink url was `--sink=http://imc-broker`, it works for service. But when did perf test for ksvc, it failed. Changed to `--sink=http://imc-broker.default.svc.cluster.local`, which is consistent with manual perf test's sink format under broker-imc/ and is both working for svc and ksvc.
- Changed from `--sink=http://imc-broker `to `--sink=http://imc-broker.default.svc.cluster.local`
-
-
```release-note
```

Modify sender-receiver sink url for broker-imc perf test

---

cmd/broker/filter/main.go
cmd/broker/ingress/main.go
pkg/broker/filter/stats_reporter.go
pkg/broker/filter/stats_reporter_test.go
pkg/broker/ingress/stats_reporter.go
pkg/broker/ingress/stats_reporter_test.go
pkg/broker/metrics.go

Fixes https://github.com/knative/eventing/issues/2405
Also related to: https://github.com/knative/eventing/pull/2425
The pod name was used to only keep the labels unique when working with stackdriver. Replace it with random unique id so that downward API (ksvc doesn't support downward API at the moment) is not needed in the podspec to reference the pod name.
```release-note
Replace pod name label in broker stats_reporter with random unique name
```

Replace pod name label in broker stats_reporter with random unique name

---

config/monitoring/metrics/grafana/100-grafana-dash-eventing.yaml

Fixes #
- I hadn't actually attempted it, but it seems implausible that Grafana would have imported the dashboards separated by a comma with or without an enclosing array. This PR puts each dashboard into a separate ConfigMap key.
```release-note
```

individual configmap keys for grafana dashboards

---

.github/pull-request-template.md

To prepare for a future release notes compilation bot/process, here's an update to the PR template clarifying how people should write their own release notes.
The list of change types came from the [PR template used in knative/client](https://raw.githubusercontent.com/knative/client/master/.github/pull-request-template.md). I removed the requirement to edit the changelog file directly because I think that would cause merge conflicts. We can use automated processes to update that file instead. 
I added some words about focusing on user-visible impact, since IMO users don't care about `updated some internal Go interface` and having too many notes make the release harder to understand. 
/cc @vaikas

Add clearer release notes guidance to PR template

---

Gopkg.lock
Gopkg.toml
pkg/tracing/traceparent_test.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_interface.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_writer.go
vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go

- Dep on cloudevents/sdk-go v1.0.0
- Fix a test that was using != on an event.
<!--
In the following cases, write a brief release note describing the
user-visible impact of this change in the release-note block:
- 🐛 Fix bug
- 🧽 Update or clean up currrent behaviour
Include the string "action required" if additional action is required of
users switching to the new release, for example in case of a breaking change.
Write as if you are speaking to users, not other Knative contributors. If this
change has no user-visible impact, no release-note is needed.
```release-note
NONE
```

Use cloudevents goland sdk 1.0.0

---

test/performance/benchmarks/broker-imc/cluster.yaml
test/performance/benchmarks/channel-imc/cluster.yaml

It's more efficient on Google Cloud.

Use e2 VMs instead of n1 for for performance tests

---

.gitignore
pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
pkg/apis/sources/v1alpha1/sinkbinding_lifecycle_test.go
pkg/reconciler/testing/containersource.go
test/e2e/source_sinkbinding_test.go
test/test_images/heartbeats/main.go
test/test_images/logevents/main.go

- Propagate the CloudEvent Overrides to the subject for SinkBinding.
```release-note
SinkBinding now propagates the `sinkBinding.spec.ceOverrides` values as json into an env var called `K_CE_OVERRIDES`. See the Source ducktype to unmarshal this value.
```
/assign @mattmoor

Adding CloudEvents Overrides to SinkBinding.

---

pkg/tracing/traceparent.go

- Improve the performance of trace parent parsing by caching the compiled regexp.
When profiling the imc-dispatcher I found that it was spending approximately 7.5% of CPU time compiling this regexp, representing nearly 40% of the CPU time spent in the fanout dispatch function . After making the regexp global, parseTraceparent uses only 0.67% of total CPU time.

Cache compiled trace parent regexp in global variable.

---

pkg/apis/eventing/v1alpha1/trigger_conversion.go
pkg/apis/eventing/v1alpha1/trigger_conversion_test.go
pkg/apis/eventing/v1alpha1/trigger_types.go
pkg/apis/eventing/v1beta1/broker_lifecycle.go
pkg/apis/eventing/v1beta1/test_helper.go
pkg/apis/eventing/v1beta1/trigger_conversion.go
pkg/apis/eventing/v1beta1/trigger_conversion_test.go
pkg/apis/eventing/v1beta1/trigger_lifecycle.go
pkg/apis/eventing/v1beta1/trigger_lifecycle_test.go

Addresses #1869 
- Add conversion functions for Trigger (v1alpha1 <-> v1beta1)
- Decouple (clean-up) broker v1beta1 / v1alpha1 dependency
```release-note
```

Trigger conversion function (v1alpha1 <-> v1beta1)

---

docs/spec/channel.md

- our channels are all addressable, and use these label

SPEC: Adding duck/addressable label to channel CRD 

---

pkg/reconciler/configmappropagation/configmappropagation.go
pkg/reconciler/configmappropagation/configmappropagation_test.go
pkg/reconciler/testing/configmap.go
pkg/reconciler/testing/configmappropagation.go

Fixes #2437
- ConfigMapPropagation controller only deletes the CMP owner reference from the ConfigMap, and keeps other owner references (if any)
- A unit test
-
```release-note
```

ConfigMapPropagation should keep other owner references when abandoning a copy configmap

---

README.md
docs/spec/sources.md

Looks like the few places we have for docs, are currently not working. since godoc seems deprecated.
See
> Pkg.go.dev is a new destination for Go discovery & docs. Check it out at pkg.go.dev/knative.dev/pkg/apis/duck/v1 and share your feedback.
warning on their site 
Hence an update 🧽  to reflect the new `pkg.go.dev` site :scream_cat:

Godoc seem deprecated

---

config/core/roles/clusterrole-namespaced.yaml

- namespeaced CR for `flows.knative.dev`
Related to this this:
* https://github.com/knative/eventing/pull/1993
and see https://github.com/knative/eventing/commit/052bd9e178aefd0b14fc9dc9014d59aa532396ed#diff-bc901b9d7f4a101d28344eca9f094d84R36-R72  as well, where the one for the new `sources.knative.dev` was added

Knative flows namespaced admin

---

docs/spec/sources.md

Adding a small section on "event delivery" to the sources spec.
Question: should we talk about things like _retry_?

Adding section on event delivery

---

pkg/adapter/ping/adapter.go

Not sure if that's really an issue - but, I found it confusing.
testing the `PingSource`, I am getting these Cloudevents:
```
☁️  cloudevents.Event
Validation: valid
Context Attributes,
specversion: 1.0
type: dev.knative.cronjob.event
source: /apis/v1/namespaces/default/cronjobsources/test-ping-source
id: b3393cbd-ab61-4835-a2c3-31f58f06ddf4
time: 2020-02-11T19:34:00.000876652Z
datacontenttype: application/json
Data,
{
"message": "Hello world!"
}
```
- remove `legacysource` usage, and use actual sources v1alpha1, to update the `type` and `source` to be more consistent
<!--
In the following cases, write a brief release note describing the
user-visible impact of this change in the release-note block:

ping used 'legacysources'

---

docs/spec/channel.md

* updates to allow future updates of different protocols
* be (more) explicit that we support input of several CE versions and that output has to match the incomming version
/assign @lionelvillard 
/assign @vaikas

Channel spec: Data Plane updates

---

docs/spec/sources.md

Came up on the channel spec doc, and there we now do recommend usage of 1.0, while still allowing the usage of 0.x 
/assign @n3wscott 
Scott, do you agree with this recommendation ?

Adding a recommendation to use 1.0 for source implementors

---

pkg/reconciler/broker/controller.go

Fixes #
- Requeue broker when subscriptions to its triggers change. This will transitively then
reconcile the triggers.
```release-note
- 🐛 Fix bug
WIthout this, the Triggers can in some cases stay in the 'Subscription not reconciled state'
```

requeue broker when subscriptions to its triggers change

---

test/lib/test_runner.go

- When tearing down the namespace, dump the k8s events there to aid in debugging
```release-note
no user-visible impact. For testing, will dump the k8s events emitted in the namespace during teardown.
```

dump events in a namespace when tearing down

---

pkg/reconciler/configmappropagation/configmappropagation_test.go
pkg/reconciler/configmappropagation/resources/configmap.go
pkg/reconciler/configmappropagation/resources/configmap_test.go

This label is used to identify the original ConfigMap, so the namespace used should be the namespace of the original ConfigMap instead of the namespace of the CMP.
This should fix the test failure in #2570 because the names won't be too long anymore: current usage of CMP will only create copies with certain names (e.g. `knative-eventing-config-tracing`) in test and other environments.
A fix for names that are too long is still needed, but that can be deferred to a future PR.
Fixes #2570.
- Correct the copy ConfigMap label to use the namespace of the original ConfigMap.
/cc @n3wscott @vaikas @grac3gao

Use original namespace in label on copy ConfigMap

---

cmd/webhook/main.go
config/core/resources/subscription.yaml
pkg/apis/messaging/v1alpha1/subscription_conversion.go
pkg/apis/messaging/v1alpha1/subscription_conversion_test.go
pkg/apis/messaging/v1beta1/subscription_conversion.go
pkg/apis/messaging/v1beta1/subscription_conversion_test.go
pkg/reconciler/broker/trigger.go
pkg/reconciler/subscription/subscription.go
test/e2e/channel_single_event_test.go
test/e2e/helpers/channel_single_event_helper.go
test/lib/creation.go
test/lib/resources/eventing.go

Fixes #
- Add conversion and conversion webhook for Subscription v1alpha1 <-> v1beta1
```release-note
Add support for Subscription v1alpha1 <-> v1beta1 conversions.
```

Subscription v1alpha1<->v1beta1

---

.github/pull-request-template.md

As requested in today's eventing WG, this adds a reminder to link to a docs issue/PR when making a user-visible change.
/cc @vaikas @lionelvillard

Add docs link to PR template

---

cmd/webhook/main.go
config/core/resources/eventtype.yaml
pkg/apis/eventing/register.go
pkg/apis/eventing/v1alpha1/eventtype_conversion.go
pkg/apis/eventing/v1alpha1/eventtype_conversion_test.go
pkg/apis/eventing/v1beta1/eventtype_conversion.go
pkg/apis/eventing/v1beta1/eventtype_conversion_test.go

- adding conversion webhook support for eventtype
- wire up eventtype into the webhook conversion
```release-note
Added v1beta1 support for EventType.eventing.knative.dev.
```

EventType conversion v1alpha1 <--> v1beta1

---

config/core/deployments/sources-controller.yaml

- Sources controller was merged into eventing controller, but I deleted the deployment file. This adds back the deployment file (trimmed) and scales it to zero.
```release-note
- 🧽 Sources controller (sources-controller deployment) has been scaled to zero. Safe to delete.
```

 Adding temp file to scale old sources controller to zero.

---

Gopkg.lock
cmd/webhook/main.go
vendor/knative.dev/pkg/injection/sharedmain/main.go

Related to knative/pkg#1007, migrates webhook processes onto new WebhookMain methods in the `sharedmain` package that will retain the existing behavior for now while we decide how to scale webhooks horizontally.
* Move webhook main onto `WebHookMain` methods from knative/pkg#1084
```release-note
NONE
```

Move webhooks onto new sharedmain methods

---

pkg/reconciler/namespace/controller.go
test/e2e/broker_default_test.go

Fixes #2624
- Change informer handler logic
- Add e2e test
-
```release-note
```
**Docs**

make namespace reconciler work for broker recreation

---

Gopkg.lock
Gopkg.toml

- Prepping for `v0.13` release.
- Point `knative.dev/pkg` to branch `release-0.13`.
```release-note
NONE
```
/cc @mattmoor

Preparing for v0.13 release, point pkg to release-0.13.

---

pkg/duck/listable.go
pkg/duck/sinks.go
pkg/reconciler/subscription/controller.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go
test/e2e-common.sh

Fixes https://github.com/knative/eventing/issues/2641
- Add controller logs to prow e2e test output artifacts.
- Track `Channels.messaging.knative.dev` in Subscription's `reconciler.getChannel` method.
- Minor migrations off deprecated `tracker.Track` method.
```release-note
NONE
```

Subscription controller needs to track Channels directly, when used.

---

cmd/webhook/main.go
config/core/deployments/webhook.yaml

Fixes #2350
- Depending on PR in pkg: https://github.com/knative/pkg/pull/1123
- Add a `SINK_BINDING_OPT_OUT_SELECTOR` env var in webhook main
- You can override the selector by providing the env var in `500-webhook.yaml`
- 🎁 Add new feature to specify OptIn or OptOut selector for sinkbinding webhook via a env var.
```release-note
Add new feature to specify OptIn or OptOut selector for sinkbinding webhook via a env var.
```
**Docs**
Opened an issue to follow up on: https://github.com/knative/docs/issues/2246
Update `500-webhook.yaml` with `SINK_BINDING_OPT_OUT_SELECTOR` set to `true`.  Observed that the `sinkbinding` and `legacysindbinding` webhook selectors are updated.
@vaikas @patrickshan @matzew @grantr

Add an option to specify sinkbinding webhook selector.

---

config/brokers/channel-broker/roles/controller-clusterroles.yaml

Fixes #2642 
- adding `namespaces/finalizers` for ConfigMapPropagation
See the `OwnerReference` of it:
https://github.com/openshift/knative-eventing/blob/release-next/pkg/reconciler/namespace/resources/configmappropagation.go#L32-L35

Adding namespace and configmappropagations finalizers for the configmappropagations

---

test/performance/benchmarks/broker-imc/dev.config
test/performance/benchmarks/broker-imc/prod.config
test/performance/benchmarks/channel-imc/dev.config
test/performance/benchmarks/channel-imc/prod.config
test/performance/config/config-mako.yaml

Add myself to mako config owners in order to be able to run performance tests from my dev env.

add ngiraldo to mako configs

---

cmd/webhook/main.go
config/core/deployments/webhook.yaml

Fixes https://github.com/knative/eventing/pull/2634#discussion_r384777104
- `SINK_BINDING_OPT_OUT_SELECTOR` -> `SINK_BINDING_SELECTION_MODE`
- Instead of specifying `true` or `false`, just pick the selector type `inclusion` or `exclusion`
-
```release-note
Specify sinkbinding webhook selector by `SINK_BINDING_SELECTION_MODE` environment variable.
```
**Docs**
/assign @n3wscott @matzew 
cc @vaikas

Pick a better name for the sinkbinding selector env var.

---

Gopkg.lock
cmd/channel_broker/main.go
cmd/in_memory/channel_controller/main.go
cmd/in_memory/channel_dispatcher/main.go
cmd/webhook/main.go
config/brokers/channel-broker/roles/controller-clusterroles.yaml
config/channels/in-memory-channel/200-controller-clusterrole.yaml
config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml
config/config-leader-election.yaml
config/core/configmaps/leader-election.yaml
pkg/apis/configs/validation/leader_election.go
pkg/apis/configs/validation/leader_election_test.go
vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
vendor/k8s.io/client-go/tools/leaderelection/metrics.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
vendor/knative.dev/pkg/Gopkg.lock
vendor/knative.dev/pkg/injection/sharedmain/main.go
vendor/knative.dev/pkg/leaderelection/config.go

Fixes knative/pkg#1007
- depends on knative/pkg#1019 for changes to `sharedmain`, which is used by:
- controller
- webhook
- `/config` is changed so that it is simple to enable leader election, but it is not enabled by default
```release-note
Add support for leader election
```

Add leader election

---

test/performance/performance-tests.sh

- Started from Feb 21st, `ko delete` failed for the channel-imc benchmark with hanging forever, see https://prow.knative.dev/?job=ci-knative-eventing-update-clusters. Add `--wait=false` option to skip waiting. 
Note:
The error should be due to some changes on Feb 21st in https://github.com/knative/eventing/commits/master but I'm not sure which one can cause it. It also might be a bug as customers may also get stuck in deleting resources (in this case subscription).
/cc @nachocano

No wait in ko delete for performance tests

---

cmd/webhook/main.go
pkg/leaderelection/leader_election.go
pkg/leaderelection/leader_election_test.go

Renames the former weirdly named packages to `pkg/leaderelection`, to have parity with what I was asked to do in serving.
```release-note
None
```

Rename leader election config package/methods

---

config/core/configmaps/default-imc.yaml
pkg/apis/eventing/v1alpha1/broker_validation_test.go
pkg/reconciler/broker/config.go
pkg/reconciler/broker/config_test.go
pkg/reconciler/broker/testdata/config-broker.yaml
test/lib/creation.go

An oversight in config map formatting made broker and channel configs have very different format. Moving to yaml strings over json strings.
- Migrate Broker Config to look like Default Channel Config.
```release-note
NONE
```
**Docs**
Already a docs issue for broker config: https://github.com/knative/docs/issues/2227

migrate broker config to look like channel config

---

pkg/apis/messaging/v1alpha1/subscription_lifecycle.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go
pkg/reconciler/testing/subscription.go

Fixes https://github.com/knative/eventing/issues/2633
- 🐛 Updated the Subscription's finalizer method. If the channel does not longer exists (i.e., was deleted first), then we remove the Subscription's finalizer and let it be gc'ed. Also, check whether the subscription was actually added to the channel before attempting to remove it from its list. Added UT and fixed wrong ones
```release-note
NONE
```
**Docs**

Remove Subscription's finalizer if the Channel was deleted first

---

config/core/resources/eventtype.yaml

Fixes #2661.
Seems like EventType was just missed when it was upgraded to v1beta1.
Why should this go in before the release: fixes log spamming from the webhook whenever an EventType is reconciled. Could cost money for customers doing log archival.
- Add conversion webhook config to EventType
/cc @dprotaso

Add webhook and validation config to EventType

---

docs/spec/broker.md

Add the Broker conformance spec to `docs/spec`. This is copied from the working document https://docs.google.com/document/d/1zjkaO_Nu6Zt4OmzBEmCMTBPj2JtGCSyYgGG5pVyLlBU.
Fixes #2306.
- Add Broker conformance spec.
Not a user-visible change.

Add Broker conformance spec

---

pkg/apis/eventing/v1alpha1/trigger_conversion.go

Previously we made the map size zero by default, lets make it match
the existing length of attributes by default.
----
#

Similar to PR2700: make trigger conversion attribute length variable

---

pkg/reconciler/namespace/controller.go
pkg/reconciler/namespace/controller_test.go
pkg/reconciler/namespace/namespace.go
pkg/reconciler/namespace/namespace_test.go
pkg/reconciler/testing/listers.go

Fixes #2396
Uses the shared informer cache instead of the API server to list resources that should be inspected in the Namespace Reconciler.

Use Listers in Namespace Reconciler

---

Gopkg.lock
test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/lib/checkevents.go
test/lib/checkevents_test.go
test/lib/requests.go
test/lib/resources/kube.go
test/lib/validation.go
test/test_images/eventdetails/main.go
test/test_images/recordevents/README.md
test/test_images/recordevents/eventstore.go
test/test_images/recordevents/eventstore_test.go
test/test_images/recordevents/main.go
test/test_images/recordevents/pod.yaml
third_party/VENDOR-LICENSE

Fixes #2390
- Add a recordevents event consumer pod with a REST API to retrieve events it has seen
- Add e2e test support for accessing this API via kubectl portforward
- Add Find and WaitAtLeastNMatch functions that take a function that looks at event contents and http headers to check results
- Convert a first few e2e users of eventlogging and eventdetails pods to the new model

E2E event receiver pod with REST endpoint

---

test/performance/infra/aggregator/aggregator.go

- the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
```release-note
NONE
```

avoid leaking ctx 

---

pkg/apis/flows/v1alpha1/parallel_lifecycle_test.go

- fix: composite literal uses unkeyed fields on parellel tests.
```release-note
NONE
```

fix: composite literal uses unkeyed fields

---

pkg/apis/eventing/v1alpha1/broker_defaults.go
pkg/apis/flows/v1alpha1/parallel_defaults.go
pkg/apis/flows/v1alpha1/sequence_defaults.go
pkg/apis/flows/v1beta1/parallel_defaults.go
pkg/apis/flows/v1beta1/sequence_defaults.go
pkg/apis/messaging/v1alpha1/channel_defaults.go

- fix: composite literal uses unkeyed fields, for seq, parallel defaults 
- same for broker, channel
```release-note
NONE
```

fix: composite literal uses unkeyed fields, defaults

---

Gopkg.lock
vendor/knative.dev/pkg/injection/sharedmain/main.go
vendor/knative.dev/pkg/metrics/exporter.go

Brings in knative/pkg#1142 and knative/pkg#1145:
- correct behavior when leader election config doesn't exist
- fix problem with invalid prometheus metrics names with some controllers
```release-note
- correct behavior when leader election config doesn't exist
- fix problem with invalid prometheus metrics names with some controller names
```

Update to latest pkg 0.13

---

docs/spec/sources.md

Fixes #2706
- Remove 0.2 as supported Cloud Event version.
-
-
```release-note
- 🧽 Update or clean up current behavior : Cloud Events 0.2 is not supported by sources.
```
**Docs**

remove 0.2 from the sources spec

---

docs/spec/broker.md

Adds an outline of all the test steps needed to verify conformance to (most of) the spec. Some parts of the spec that are difficult to verify are listed as exceptions. I'm hoping this clarifies the concrete work needed for #2704 and #2705.
- Add conformance test outline to Broker spec
/cc @liu-cong @yolocs

Add conformance test outline to Broker spec

---

config/core/configmaps/default-broker.yaml
pkg/apis/config/defaults_test.go
pkg/apis/eventing/defaults.go
pkg/apis/eventing/v1alpha1/broker_defaults.go
pkg/apis/eventing/v1alpha1/broker_defaults_test.go
pkg/apis/eventing/v1alpha1/broker_types.go
pkg/client/injection/reconciler/eventing/v1alpha1/broker/controller.go
pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go
pkg/client/injection/reconciler/eventing/v1alpha1/broker/stub/controller.go
pkg/reconciler/broker/broker.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/controller.go
pkg/reconciler/testing/broker.go

The existing filter function only applies when the default controller has a non-empty BrokerClass. This has an issue: If the incoming broker is specified with `BrokerClass: Foo-Class`, the default controller with `BrokerClass:""` will happily pick it up even thought the broker doesn't belong to it. 
This change ensures that any broker object, as well as the default broker controller,  will have a non-empty BrokerClass to match against.
- Add default BrokerClass in cluster default. This allows the broker Defaulter to apply the default BrokerClass annotation if not set.
- Add default BrokerClass in broker controller env var.
- Modify the filter func to do exact match of given broker and the controller based on broker class.
```release-note
```
**Docs**
* Tested new brokers …

Apply defaults to BrokerClass and only filter brokers that match BrokerClass.

---

test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/conformance/helpers/tracing/traces.go
test/conformance/helpers/tracing/traces_test.go

Fixes #2046.
- Allow conformant broker and channel implementations to emit extra spans as long as the required test span tree remains a sub-tree of actual span tree. This is necessary since since libraries, sidecars, and other components will often create new spans. This also allows for broker and channel architectures which are more complex than the shape captured by the test span trees.

Relax Tracing Conformance Tests to Allow Trace Trees With Matching Subtrees

---

config/core/configmaps/default-channel.yaml

- use beta1 instead of alpha for default channel
```release-note
- 🧽 using the beta API of IMC for default channel
```
**Docs**

stash for the latest version

---

pkg/channel/fanout/fanout_handler_binding.go
pkg/channel/fanout/fanout_handler_binding_test.go
pkg/channel/multichannelfanout/multi_channel_fanout_handler_binding.go
pkg/channel/multichannelfanout/multi_channel_fanout_handler_binding_test.go
pkg/channel/swappable/swappable_binding.go
pkg/channel/swappable/swappable_binding_test.go

Fixes #2671, makes obsolete the #2680
Ported:
* `knative.dev/eventing/pkg/channel/fanout`: `Handler` -> `MessageHandler`
* `knative.dev/eventing/pkg/channel/multichannelfanout`: `Handler` -> `MessageHandler`
* `knative.dev/eventing/pkg/channel/swappable`: `Handler` -> `MessageHandler`

Port channel fanout code to bindings

---

pkg/reconciler/mtbroker/broker.go
pkg/reconciler/mtbroker/controller.go

There was a superfluous Endpoints event registered, which is leftover from the single-tenant Broker.
There was a missing global resync due to changes in the shared Endpoints, which prevents Brokers from becoming ready if they are reconciled before the shared deployment have become ready.
Note: this logic is copied from similar logic in the Serving SKS controller, where we global resync on changes to the activator service.

Adjust the Endpoints Informer events.

---

test/e2e/trigger_dependency_annotation_test.go

This test was failing consistently, apparently because it wasn't waiting for the subscriber pod to become ready.
/cc @vaikas

Wait for dependency annotation test subscriber to become ready

---

pkg/reconciler/mtnamespace/controller.go
pkg/reconciler/mtnamespace/controller_test.go
pkg/reconciler/mtnamespace/namespace.go
pkg/reconciler/mtnamespace/namespace_test.go
pkg/reconciler/mtnamespace/resources/broker.go
pkg/reconciler/mtnamespace/resources/labels.go

This adds a namespace controller that creates brokers per namespace without the additional components that are only needed by the single-tenant brokers (ConfigMapProp, RoleBindings, ServiceAccounts).
Since the footprint of the MT Broker is effectively nothing, I've made this version of the controller opt-out vs. opt-in.
/assign @vaikas 
/hold

Add a namespace controller for the MT Broker.

---

pkg/broker/filter/filter_handler.go
pkg/mtbroker/filter/filter_handler.go

- 🐛 Fix bug
The Broker filter libraries were discarding the signal-aware context they were passed in, which meant that when the Broker is run in a deployment with a long `terminationGracePeriodSeconds` pods take an extremely long time to tear down.
This is because the K8s lifecycle first sends a SIGTERM, which is a warning shot to tell the application to tear down gracefully, after which it is given `terminationGracePeriodSeconds` to exit before it is sent `SIGKILL`.  I ran this in a pod with a `terminationGracePeriodSeconds` of several minutes and pods took forever to tear down, but with this fix it takes roughly the 60s of the sleep below this logic.
/assign @vaikas @grantr

Fix context threading for Broker signal handling.

---

pkg/reconciler/source/crd/controller.go
pkg/reconciler/source/crd/crd.go
pkg/reconciler/source/duck/controller.go
pkg/reconciler/source/duck/duck.go

- Migrate source duck and crd controller off reconciler.Base
```release-note
NONE
```
**Docs**

Migrate source duck and crd controller off reconciler.Base

---

pkg/reconciler/source/crd/crd.go

prevent a panic when we have old CRDs installed in the cluster that are labeled Source but are not correctly installed.
- fixes a panic seen in local cluster.
```release-note
NONE
```

prevent a panic when we have CRDS labeled as sources without correct RBAC.

---

pkg/reconciler/inmemorychannel/controller/controller.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
pkg/reconciler/inmemorychannel/dispatcher/controller.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go

- migrate imc dispatcher to recgen
- move imc off reconciler.Base
```release-note
NONE
```

migrate imc dispatcher to recgen, move imc off reconciler.Base

---

cmd/mtbroker/filter/main.go
cmd/mtbroker/ingress/main.go
pkg/reconciler/mtbroker/broker.go
pkg/reconciler/mtbroker/controller.go
pkg/reconciler/names/mtbroker.go

Uses the broker-filter and broker-ingress service names that were
previously exported by the mtbroker reconciler. Moves the service
names to the names package since importing the reconciler package
causes the injector to inject the informers used by the mtbroker
reconciler.
Fixes #2809

Fix mtbroker trace exporting by fixing service names.

---

pkg/utils/utils.go
pkg/utils/utils_test.go

Fixes #2753
Regarding the original issue kubernetes names are DNS-1123 compliant so are Trigger names, no need to add extra validation.
This PR removes any dot that will be prefixing to the `dash + UID` string to avoid the issue.
Although double dashes are DNS-1123 compliant they do not look pretty; the PR also avoids adding a dash to the concatenation when the prefix already begins with one.
```release-note
- Fix generated names not being DNS1123 compliant when based on strings that contain dots.
```

GeneratedNames: fix generated names not being RFC 1123 compliant

---

pkg/channel/event_receiver.go
pkg/channel/fanout/fanout_handler_test.go
pkg/channel/fanout/fanout_message_handler.go
pkg/channel/fanout/fanout_message_handler_test.go
pkg/channel/message_dispatcher.go
pkg/channel/message_dispatcher_test.go
pkg/channel/message_receiver.go
pkg/channel/message_receiver_test.go

This PR should settle all FanoutMessageHandler flakyness
* Fix the flakyness of `FanoutMessageHandler`
* Fix to `MessageDispatcher` (now all messages are correctly `Finish`ed)
* A refactoring of `MessageDispatcher` API and implementation to reduce cognitive complexity
* Fix `ResolveChannelFromHost` 404

Fixed FanoutMessageHandler and improved coverage

---

config/core/resources/broker.yaml

Fixes #
- Relax the validation of the fields allowed in the Broker to allow for different Broker Class implementations that might have additional fields.
```release-note
```
**Docs**

relax the validation logic to allow for more broker classes

---

pkg/apis/messaging/v1alpha1/subscription_lifecycle.go
pkg/apis/messaging/v1beta1/subscription_lifecycle.go

Fixes #2736
- Rename Subscription condition when references are resolved from `Resolved` to `ReferencesResolved`
Note: instead of using the suggested singular reference [here](https://github.com/knative/eventing/issues/2163#issuecomment-596630353) I have turned it into plural since it is resolving subscriber and maybe reply and dead letter sink.

rename subscription condition reference to references resolved

---

test/performance/performance-tests.sh

- Now eventing requires installing broker with a separate command, add it in `performance-tests.sh` to fix the broker benchmark
```release-note
NONE
```
/cc @grantr

Fix performance tests by installing broker

---

pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/apiserversource/resources/receive_adapter.go
pkg/reconciler/apiserversource/resources/receive_adapter_test.go
pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/resources/subscription.go
pkg/reconciler/broker/resources/subscription_test.go
pkg/reconciler/broker/trigger.go
pkg/reconciler/mtbroker/broker_test.go
pkg/reconciler/mtbroker/resources/subscription.go
pkg/reconciler/mtbroker/trigger.go
pkg/reconciler/pingsource/controller/pingsource.go
pkg/reconciler/pingsource/controller/pingsource_test.go
pkg/reconciler/pingsource/controller/resources/receive_adapter.go
pkg/reconciler/testing/apiserversource.go
pkg/utils/utils.go

Fixes https://github.com/knative/eventing/issues/2842
**Description**
- There are 2 functions used to generate names for child objects. The one we should stick to is `kmeta.ChildName` while the one we should no longer use is `util.GenerateFixedName`
- For short generated names we can make both functions return the same name, but for long ones they do not.
- We can't be backwards compatible if we want to use only one function. This PR implements [this candidate solution](https://github.com/knative/eventing/pull/2800#discussion_r397909782) that will:
- If the resource with the new name is found, behave as usual
- If the resource with the new name is not found, look for the resource with the old name
- If the resource with the old name is found, delete it
- Create the resource with the new …

Generate names with kmeta.ChildName. Delete deprecated named resources

---

Gopkg.lock
pkg/broker/filter/filter_handler_test.go
pkg/broker/ingress/ingress_handler_test.go
pkg/channel/event_dispatcher_test.go
pkg/channel/event_receiver_test.go
pkg/channel/fanout/fanout_handler_test.go
pkg/channel/fanout/fanout_message_handler_test.go
pkg/channel/message_dispatcher_test.go
pkg/channel/message_receiver_test.go
pkg/channel/multichannelfanout/multi_channel_fanout_handler_test.go
pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
pkg/channel/multichannelfanout/parse_test.go
pkg/channel/swappable/swappable_message_handler_test.go
pkg/channel/swappable/swappable_test.go
pkg/mtbroker/filter/filter_handler_test.go
pkg/mtbroker/ingress/ingress_handler_test.go

This makes test output more useful by printing zap log messages on
test failure.

Always pass zaptest logger with AddCaller to SUT in unit tests

---

pkg/apis/duck/v1alpha1/subscribable_types.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
pkg/apis/duck/v1beta1/subscribable_types.go
pkg/apis/duck/v1beta1/subscribable_types_conversion.go
pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
pkg/channel/fanout/fanout_handler.go
pkg/channel/fanout/fanout_handler_test.go
pkg/channel/fanout/fanout_message_handler.go
pkg/channel/fanout/fanout_message_handler_test.go
pkg/channel/multichannelfanout/multi_channel_fanout_handler_test.go
pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
pkg/channel/multichannelfanout/parse_test.go
pkg/channel/swappable/swappable_message_handler_test.go
pkg/channel/swappable/swappable_test.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go

Fixes #2868
- `v1beta1.Subscribable` & `v1alpha1.SubscribableType` implements `Convertible`
- Ported the `fanout.Config` to use `v1beta1.Subscribable`

 Port fanout.Config to SubscriberSpec v1beta1 

---

config/brokers/channel-broker/resources/configmappropagation.yaml

- move cmp to just `knative-internal` category, like done on serving

Move CMP to knative-internal category

---

pkg/channel/fanout/fanout_message_handler.go
pkg/channel/fanout/fanout_message_handler_test.go
pkg/channel/message_dispatcher.go
pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
pkg/kncloudevents/message_client.go

Also enabled logging on `FanoutMessageHandler`, in order to detect future flakyness on that test

Addressing tracing issues in FanoutMessageHandler & MessageReceiver

---

config/brokers/mt-channel-broker/deployments/controller.yaml
pkg/reconciler/mtnamespace/controller.go
pkg/reconciler/mtnamespace/namespace.go
pkg/reconciler/mtnamespace/namespace_test.go

This adds a way to revert the `mtnamespace` controller to opt-in (similar to the `namespace` controller), but by default the setting is "enabled" due to the trivial per-Broker cost.
See also the conversation here: https://github.com/knative/docs/pull/2325
cc @grantr @matzew @lionelvillard @vaikas 
I'd be happy to add the same logic to the `namespace` controller's `envconfig` (but off by default) so that it is similarly configurable, if that symmetry is interesting to folks?

Add a way to make the `mtnamespace` controller behave like `namespace`.

---

pkg/apis/eventing/v1alpha1/broker_validation_test.go
pkg/apis/eventing/v1alpha1/eventtype_validation_test.go
pkg/apis/eventing/v1alpha1/trigger_validation_test.go

I noticed the unused types in the CRDTest "framework". Upon closer look it seems like such a framework is sometimes used, sometimes not. Is there a general guidance on this? I'm happy to help make it all consistent throughout.

Rewrite eventing/v1alpha1 validation tests using unused CRDTest framework.

---

cmd/upgrade/v0.14.0/main.go
config/upgrade/v0.14.0/README.md
config/upgrade/v0.14.0/upgrade.yaml
hack/release.sh
pkg/upgrader/broker/v0.14.0/upgrader.go
pkg/upgrader/broker/v0.14.0/upgrader_test.go

Fixes #2840
- Introduce a script that runs as a job that will patch all Brokers without BrokerClass annotation to ChannelBasedBroker
-
-
```release-note
- 🐛 Fix bug
* action required * You have to run the provided upgrade script, or something like this to update all the Brokers with the proper BrokerClass or they will not continue to be reconciled after 0.14 cuts.
Details for the script are in:
config/upgrade/v0.14.0/README.md
Release artifact is:
https://github.com/knative/eventing/releases
```
**Docs**

Upgrade script for patching broker annotation

---

pkg/channel/message_dispatcher.go
pkg/channel/message_receiver.go
pkg/channel/message_receiver_test.go

Tracing fix for MessageDispatcher

---

DEVELOPMENT.md

Because a Broker implementation is not included by default anymore, this addition to the DEV guide instructs how to deploy one.

Add Broker installation instructions to DEV doc

---

DEVELOPMENT.md

The current DEVELOPMENT document gives newcomers the impression they _must_ install Serving in order to work with Eventing.
- Soften the requirement, mention the cases where running Serving is actually necessary
- Pimp `Notes` for cosmetic and consistency

Soften requirement on Serving in DEV doc

---

pkg/reconciler/broker/controller.go
pkg/reconciler/eventtype/controller.go
pkg/reconciler/inmemorychannel/controller/controller.go
pkg/reconciler/inmemorychannel/dispatcher/controller.go
pkg/reconciler/mtbroker/controller.go
pkg/reconciler/mtnamespace/controller.go
pkg/reconciler/pingsource/controller/controller.go

Just a small code cleanup.
- Remove unused ReconcilerName const from reconcilers.
The reconciler name (actually work queue name) is set in the injection code for reconcilers that use `NewImpl` from injection-gen.
Note: `reconciler/source/duck` and `reconciler/source/crd` are still using `controller.NewImpl`.

Remove unused ReconcilerName const from reconcilers

---

cmd/webhook/main.go

Include an empty list of validating callbacks in eventing
Once all consumers of /pkg include an empty parameter we can remove the variadic argument without breaking anything (which we have abused to make this a nonbreaking change).

Include empty list of validating callbacks

---

pkg/adapter/v2/cloudevents.go

Minor glitch: renaming metrictag variable retrieved from context
- was: `logger`
- should b: `metrictag`

Adapter V2: Typo var rename. logger --> metrictag

---

config/brokers/mt-channel-broker/deployments/controller.yaml
pkg/reconciler/mtnamespace/controller.go
test/e2e-common.sh

Let's please DISABLE the "auto MT broker injection" for the 0.14 release.
**Potential issues** 
1. both (channel and mt) "default brokers" are called `default`:
I understand the name should have no impact. That's good, but let's than not auto generate all MT brokers, if we are NOT explicitly enable it. See 2)
2. Currently the "channel broker" is default, however, regardless the MT-broker still generates a lot of brokers (for all namespaces), with the name `default`. This prevents the `kubectl label namespace default knative-eventing-injection=enabled` to create a "channel broker" for my namespace. because the MT broker was already there :disappointed: 
3. Because it still generates all these brokers, but they are not functioning, see:
```
k get brokers --all-namespaces
NAMESPACE …
```

Disable the autogenerated 'default' mt broker

---

config/core/configmaps/default-broker-channel.yaml
config/core/configmaps/default-broker.yaml
config/core/configmaps/default-channel.yaml

Fixes #2950
- This PR adds the missing label `eventing.knative.dev/release` to the ConfigMaps.
```release-note
```
**Docs**

Add the missing label eventing.knative.dev/release to the ConfigMaps

---

test/conformance/helpers/channel_tracing_test_helper.go

Tracing tests would occasionally timeout with the 2 minute timeout causing test flakiness.
Fixes #2857

Bump zipkin polling timeout to 5 minutes in tracing tests

---

config/core/roles/podspecable-binding-clusterrole.yaml

- 🐛 Fix bug
This works fine for SinkBinding because it gets Addressable, but other bindings aren't so fortunate.

Fixes the aggregated cluster roles for PodSpecable.

---

config/core/resources/trigger.yaml

Fixes #2972
- Add the missing `namespace` attribute under `.spec.subscriber.ref` (Trigger CRD)

Add namespace to Trigger's structural schema

---

Gopkg.toml

Fixes #2355
- Removing dep overrides that are not required. `hack/update-deps.sh` is happy without them.

Remove unneeded dep overrides

---

test/conformance/channel_crd_name_test.go
test/conformance/helpers/channel_crd_name_test_helper.go

Fixes #1850
- Channel name conformance tests (only 1 at the moment)
As noted in https://github.com/knative/eventing/issues/1850#issuecomment-612805497, I don't think it is necessary to fetch the CRD. Channel `GVK` is already passed to test runner and we already know the `Kind` of the channel.
```release-note
NONE
```

Channel name suffix conformance test

---

pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go

Fixes #2985, https://github.com/google/knative-gcp/issues/806
- added missing logic (accidentaly became unused after https://github.com/knative/eventing/pull/2682 and removed by https://github.com/knative/eventing/pull/2906)
- updated related test cases
🐛 Fix bug with channel subscribers not being patched properly (#2985)

Fix channel subscribers patching

---

test/conformance/channel_status_test.go
test/conformance/helpers/channel.go
test/conformance/helpers/channel_status_test_helper.go

Fixes #2992
- Conformance tests for Channel status
- Does not include tests for https://github.com/knative/eventing/issues/2993 nor https://github.com/knative/eventing/issues/1958
**Verification happy case**:
```
go test -v -timeout 30s -tags e2e knative.dev/eventing/test/conformance -run ^TestChannelStatus$ -channels="messaging.knative.dev/v1alpha1:InMemoryChannel,messaging.knative.dev/v1alpha1:Channel,messaging.knative.dev/v1beta1:InMemoryChannel"
```
**Verification unhappy case**:
To make the test fail for a non-compliant channel: 
- create a CRD like following
```
cat <<EOS |kubectl apply -f -
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
name: foochannels.example.com
spec:
group: example.com
versions:
- name: v1
served: true
storage: true …
```

Status conformance tests for channels

---

config/core/configmaps/default-broker-channel.yaml

Fixes: knative/eventing#3002
----
#

Use imc v1beta1 for default broker channel (not v1alpha1)

---

pkg/reconciler/pingsource/jobrunner/controller.go
pkg/reconciler/pingsource/jobrunner/pingsource.go
pkg/reconciler/pingsource/jobrunner/pingsource_test.go

Backporting https://github.com/knative/eventing/pull/3001
```release-note
Fix a map read-write race when reconciling PingSources.
```
**Docs**

fix map read-write race bug (#3001)

---

config/core/resources/trigger.yaml

Fixes #3012
- Correcting the jsonpath in `triggers.eventing.knative.dev` CRD: (notice the different case of `subscriberURI` vs `subscriberUri `)
-->
```release-note
- 🐛 Fix bug SUBSCRIBER_URI was not printed on for triggers
```
**Docs**

Fixing subscriberUri path in additionalPrinterColumns

---

config/core/resources/trigger.yaml

porting #3013 to `release-0.14` branch
```release-note
- 🐛 Fix bug SUBSCRIBER_URI was not printed on for triggers
```

0.14 patch: Fixing subscriberUri path in additionalPrinterColumns

---

config/upgrade/v0.14.0/upgrade.yaml

Fixes #3009
- Add `sidecar.istio.io/inject: "false"` to upgrade job
- 🐛 Fix bug
```release-note
Fixes issue where v0.14.0-upgrade would fail when istio auto-injection is enabled
```

Fixing upgrade job so it will work with istio auto-injection

---

config/brokers/mt-channel-broker/deployments/broker-filter.yaml
config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
config/brokers/mt-channel-broker/deployments/controller.yaml

Fixes #3019 
-
-
-
```release-note
```
**Docs**

do not specify replicas

---

pkg/channel/fanout/fanout_message_handler.go
pkg/channel/fanout/fanout_message_handler_test.go
pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
pkg/channel/swappable/swappable_message_handler.go
pkg/channel/swappable/swappable_message_handler_test.go
pkg/inmemorychannel/message_dispatcher.go
pkg/inmemorychannel/message_dispatcher_test.go
pkg/reconciler/inmemorychannel/dispatcher/controller.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go

With this patch one `channel.MessageDispatcher` is created for one `multichannelfanout.MessageHandler`, which means one http client. This should reduce memory usage/resource allocations (although i didn't tested it) and it's useful for mocking (followup PR will use this change to mock the dispatcher for micro benchmarks).
```
Now the MaxIdleConnections setting configured via config-imc-event-dispatcher applies to all channels registered in the dispatcher instance at the same time, because the dispatcher now uses the same http client instance for all channels 
```

Moved MessageDispatcher initialization and configuration

---

pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go

Backports #2986 (fix for #2985) to 0.14.
- added missing logic (accidentaly became unused after #2682 and removed by #2906)
- updated related test cases
```release-note
Fix bug with channel subscribers not being patched properly (#2985)
```

[release-0.13] Fix channel subscribers patching for v1alpha1 channels. (#2986)

---

pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go

Backports #2986 (fix for #2985) to 0.14.
- added missing logic (accidentaly became unused after #2682 and removed by #2906)
- updated related test cases
```release-note
Fix bug with channel subscribers not being patched properly (#2985)
```

[release-0.14] Fix channel subscribers patching for v1alpha1 channels. (#2986)

---

test/conformance/helpers/tracing/zipkin.go
test/conformance/testdata/config-tracing.yaml

Fixes #2044
- Conditionally update the ConfigMap for zipkin namespace if one is not already set.
- Provides support for running tests in alternate environments with zipkin installed in a different namespace
Checked e2e tests pass and behavior matches previous behavior. I'm not super familiar with how to properly verify the exit criteria for  #2044 (tests pass with zipkin in an alternate namespace). If there is a simple way to run tests with an alternate namespace please let me know and I will verify.

only update ConfigMap namespace for zipkin if not already set

---

Gopkg.lock
config/core/roles/channelable-manipulator-clusterrole.yaml
test/conformance/channel_channelable_manipulator_cluster_role_test.go
test/conformance/helpers/channel_channelable_manipulator_cluster_role_test_helper.go

Fixes #1846
- Conformance tests for channelable-manipulator ClusterRole
- channelable-manipulator ClusterRole for meta `Channel`. see the comment https://github.com/knative/eventing/pull/3038#pullrequestreview-398213011
**Verification:**
```
go test -v -timeout 30s -tags e2e knative.dev/eventing/test/conformance -run ^TestChannelChannelableManipulatorClusterRoleTest$
```

Conformance test for channelable-manipulator ClusterRole

---

config/core/deployments/controller.yaml
pkg/reconciler/pingsource/controller.go
pkg/reconciler/pingsource/controller_test.go
pkg/reconciler/pingsource/resources/mt_receive_adapter.go
pkg/reconciler/pingsource/resources/mt_receive_adapter_test.go

Fixes #3035 
- add owner ref to mtping deployment
-
-
```release-note
```
**Docs**

add owner ref to mtping deployment

---

pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
pkg/apis/messaging/v1alpha1/in_memory_channel_conversion_test.go
pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
pkg/reconciler/subscription/subscription.go
test/e2e/channel_single_event_test.go
test/e2e/helpers/channel_single_event_helper.go
test/lib/duck/resource_checks.go

Fixes #3014
- Return the correct duck shape for IMC. Before this, it would get defaulted to v1beta1 which means that even when read through the v1alpha1 API, it would lie and say it's a v1beta1 duck, which it's not. So, default to _lowest_ version of the duck that we know, which is the same as the stored one, since when that is read through the API server no conversion hooks are invoked and hence we can't modify it. For up conversion to v1beta1, change the duck annotation to the one that it actually supports.
- Also reduce the test timeouts from 4 minutes to 2 minutes.
-
```release-note
- 🐛 Fix bug - Fix issue #3014 
```
**Docs**

fix issue 3014

---

config/brokers/channel-broker/deployments/controller.yaml
config/brokers/mt-channel-broker/deployments/controller.yaml

the containers on the different brokers are not the `eventing-controller`. They are broker-controllers...

Use correct names for the containers

---

pkg/adapter/config.go
pkg/adapter/config_test.go
pkg/adapter/main.go
pkg/adapter/main_message_adapter.go
pkg/adapter/v2/config.go
pkg/adapter/v2/config_test.go
pkg/adapter/v2/main.go
pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/apiserversource/controller.go
pkg/reconciler/apiserversource/controller_test.go
pkg/reconciler/apiserversource/resources/receive_adapter.go
pkg/reconciler/apiserversource/resources/receive_adapter_test.go

Fixes #2978, depends on https://github.com/knative/pkg/pull/1228
- 🧽 Now `adapter.Main` (we have 3 of these) has a new tracing config getter. Controllers of sources should populate the tracing environment variable with the contents of `config-tracing` config map. By default the tracing configuration is no-op.
- Configured tracing via config map for `ApiServerSource`, follow-up PRs will fix it for other sources
```release-note
- Configuration of tracing for sources does not default anymore to the zipkin included in istio
- Configuration of tracing for sources now uses config-tracing config map
```

Configuration for tracing in sources

---

config/core/resources/eventtype.yaml

Fixes #2999 and porting to 0.14
- Adding webhook details to eventtypes CRD 
-
-
Got now:
```
{"level":"info","ts":"2020-04-29T08:22:58.949Z","logger":"eventing-webhook","caller":"conversion/reconciler.go:104","msg":"CRD is up to date","commit":"b17b158","knative.dev/traceid":"f02aacc1-e080-4e2b-ad15-65741f0858e6","knative.dev/key":"eventtypes.eventing.knative.dev"}
```
```release-note
- 🐛 Fix bug adding webhook details to eventypes CRD for conversion
```
**Docs**

Backport: Adding webhook details to eventtypes CRD

---

config/core/resources/eventtype.yaml

Fixes #2999
- Adding webhook details to eventtypes CRD 
-
-
Got now:
```
{"level":"info","ts":"2020-04-29T08:22:58.949Z","logger":"eventing-webhook","caller":"conversion/reconciler.go:104","msg":"CRD is up to date","commit":"b17b158","knative.dev/traceid":"f02aacc1-e080-4e2b-ad15-65741f0858e6","knative.dev/key":"eventtypes.eventing.knative.dev"}
```
```release-note
- 🐛 Fix bug adding webhook details to eventypes CRD for conversion
```
**Docs**

Adding webhook details to eventtypes CRD

---

hack/release.sh

- Remove GO111MODULE=on in release.sh, which is the reason that dot release 0.14.2 failed - https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-eventing-dot-release/1255936911541800960
/cc @Harwayne

remove GO111MODULE=on in release.sh

---

pkg/kncloudevents/utils.go

Fixes #
nil check before range is unnecessary in golang, this pr remove the if check.

cleanup: remove unnecessary nil check before range

---

config/core/configmaps/leader-election.yaml
pkg/leaderelection/leader_election_test.go

This is analogous to https://github.com/knative/serving/pull/7843
Removing the explicit default, since in 0.14 we added feature to LE to have a standard default.
/assign @n3wscott @vaikas 

Remove the explicit default, since 0.14 knows how to deal with it.

---

pkg/apis/eventing/v1alpha1/broker_validation.go
pkg/apis/eventing/v1alpha1/broker_validation_test.go
test/conformance/helpers/broker_tracing_test_helper.go
test/e2e/broker_config_test.go
test/e2e/helpers/broker_channel_flow_test_helper.go
test/e2e/helpers/broker_dls_test_helper.go
test/e2e/helpers/broker_event_transformation_test_helper.go
test/e2e/helpers/broker_with_config_helper.go
test/lib/resources/eventing.go

Fixes #3066 
- Do not allow creation of new Brokers with ChannelTemplateSpec anymore
```release-note
- 🗑️ Remove feature or internal logic.
Creation of new Brokers using Spec.ChannelTemplate is now disallowed.
action required: Change broker creation workflow to use Spec.Config instead. While doing that, also switch to using v1beta1 Broker API.
```
**Docs**

do not allow brokers to be created with channeltemplatespec

---

go.mod

Fixes #
- removing unnecessary dependency? At least in `goland` this line is always removed (which is a bit annoying)

removing unneeded dependency

---

test/performance/benchmarks/broker-imc/continuous/100-broker-imc-setup.yaml
test/performance/benchmarks/channel-imc/continuous/100-channel-imc-setup.yaml

- Use v1beta1 broker and channel spec for perf tests as per the changes in https://github.com/knative/eventing/pull/3083
```release-note
NONE
```

Use v1beta1 broker and channel spec for perf tests

---

OWNERS

From [ROLES.md](https://github.com/knative/community/blob/master/ROLES.md#approver):
> Reviewer of the codebase for at least 3 months.
First review [September 2019](https://github.com/knative/eventing/pull/1969)
12 in eventing: https://github.com/knative/eventing/pulls?q=is%3Apr+-author%3Aslinkydeveloper+reviewed-by%3Aslinkydeveloper+-label%3Asize%2FS+-label%3Asize%2FXS
9 in eventing-contrib: https://github.com/knative/eventing-contrib/pulls?q=is%3Apr+-author%3Aslinkydeveloper+reviewed-by%3Aslinkydeveloper+-label%3Asize%2FS+-label%3Asize%2FXS
Examples:
* https://github.com/knative/eventing/pull/2813
* https://github.com/knative/eventing/pull/2867
* https://github.com/knative/eventing/pull/2257
* …

Added slinkydeveloper as approver

---

config/brokers/channel-broker/deployments/dummy.go
config/brokers/channel-broker/dummy.go
config/brokers/channel-broker/resources/dummy.go
config/brokers/channel-broker/roles/dummy.go
config/brokers/mt-channel-broker/deployments/dummy.go
config/brokers/mt-channel-broker/dummy.go
config/brokers/mt-channel-broker/roles/dummy.go
config/channels/in-memory-channel/dummy.go
config/core/configmaps/dummy.go
config/core/deployments/dummy.go
config/core/dummy.go
config/core/resources/dummy.go
config/core/roles/dummy.go
config/core/webhooks/dummy.go

This lets tools vendor our config files with `go mod` vendoring.

Add dummy.go files to enable vendoring our configs

---

test/conformance/channel_status_subscriber_test.go
test/conformance/helpers/channel.go
test/conformance/helpers/channel_status_subscriber_test_helper.go
test/conformance/helpers/channel_status_test_helper.go
test/lib/creation.go

Fixes #2993
- Conformance tests for Channel `status.subscriber` field

Channel status subscriber conformance test

---

pkg/adapter/apiserver/adapter.go
pkg/adapter/apiserver/adapter_injection.go
pkg/adapter/apiserver/adapter_test.go

Fixes #2892
```release-note
- 🐛 Fix bug: API Server source supports now non-namespaced resources.
```

API Server Source: support non namespaced resources

---

pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/apiserversource/apiserversource_test.go
pkg/reconciler/apiserversource/controller.go
pkg/reconciler/apiserversource/resources/receive_adapter.go
pkg/reconciler/apiserversource/resources/receive_adapter_test.go
pkg/reconciler/source/config_watcher.go
pkg/reconciler/source/config_watcher_test.go

* Allow `source.ConfigWatcher`'s constructor to accept options for watching selected configs instead of all of them. `ToEnv()` will only return enabled configurations.
* Rename constructor from `StartWatchingSourceConfigurations` to `WatchConfigurations` (the former is kept as an alias).
* Improve tests.
* Document methods.
Examples:
watch logging, metrics and tracing configs (default when no option is passed)
```golang
WatchConfigurations(ctx, component, cmw)
```
watch logging and metrics configs, exclude tracing
```golang
WatchConfigurations(ctx, component, cmw,
WithLogging,
WithMetrics,
)
```

Allow config opt-in in source.ConfigWatcher

---

pkg/reconciler/channel/channel.go
pkg/reconciler/channel/channel_test.go
pkg/reconciler/testing/inmemorychannel.go

Fix Channel assuming v1alpha1 backing channel if no duck annotation

---

docs/spec/broker.md
pkg/broker/filter/filter_handler.go
pkg/broker/ingress/ingress_handler.go
pkg/mtbroker/filter/filter_handler.go
pkg/mtbroker/ingress/ingress_handler.go
pkg/tracing/attributes.go
pkg/tracing/attributes_test.go
test/conformance/helpers/broker_tracing_test_helper.go

Fixes #2958 #1766 #1763
- Define conventions for ingress and trigger spans and for setting messaging span attributes.

Broker tracing conventions

---

go.mod
go.sum
vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go
vendor/github.com/cloudevents/sdk-go/v2/binding/format/format.go
vendor/github.com/cloudevents/sdk-go/v2/binding/message.go
vendor/github.com/cloudevents/sdk-go/v2/client/client.go
vendor/github.com/cloudevents/sdk-go/v2/client/invoker.go
vendor/github.com/cloudevents/sdk-go/v2/client/options.go
vendor/github.com/cloudevents/sdk-go/v2/client/receiver.go
vendor/github.com/cloudevents/sdk-go/v2/event/event.go
vendor/github.com/cloudevents/sdk-go/v2/event/event_marshal.go
vendor/github.com/cloudevents/sdk-go/v2/event/event_validation.go
vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext.go
vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
vendor/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go
vendor/github.com/cloudevents/sdk-go/v2/go.mod
vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
vendor/modules.txt

```release-note
Updated sdk-go to v2.0.0-RC4
```

Updated to sdk-go 2.0.0-RC4

---

config/core/webhooks/config-validation.yaml
config/core/webhooks/defaulting.yaml
config/core/webhooks/resource-validation.yaml
config/core/webhooks/sinkbindings.yaml

Sets admission webhook timeout explicitly to 2s (the default is 30). This is to avoid blocking the control plane if the webhooks are down or unresponsive.
```release-note
Set admission webhook timeouts = 2s
```

Set timeout on admission webhooks

---

config/core/configmaps/default-broker.yaml
test/config/st-channel-broker.yaml
test/e2e-common.sh

This is the first step of #3139, which sets MT as default:
- MT the default
```release-note- 🧽 Update or clean up current behavior
the Single tenant broker is now DEPRECATED and no longer the default configuration. The "config-br-defaults" ConfigMap in the "knative-eventing" namespace is updated to reflect the new default choice for the `MTChannelBasedBroker` broker class. 
```

Set MT based broker the default choice

---

docs/spec/channel.md

The spec.subscription fields shouldn't be set directly, rather
it should be set via the subscriptions themselves and then the status
should be propogated via the channel.
Related to:
#3050
#3051

Add note to channel spec regarding channel subscription spec

---

test/conformance/channel_spec_test.go
test/conformance/helpers/channel.go
test/conformance/helpers/channel_spec_test_helper.go

Fixes #2988
- Conformance tests for channels' `spec.subscriber` (or `spec.subscribable.subscriber on v1alpha1 channel duck type support`
- This test is not run for generic `Channel` see spec change here: https://github.com/knative/eventing/pull/3132/files

Channel conformance tests for spec.subscriber

---

cmd/controller/main.go
pkg/reconciler/trigger/trigger.go
pkg/reconciler/trigger/trigger_test.go
test/e2e/helpers/trigger_no_broker_test_helper.go
test/e2e/trigger_no_broker_test.go

Fixes #2996 
- If trigger points to non-existent Broker, set status to failed with error message.
```release-note
If Trigger points to a non-existent Broker, mark status as failed.
```
**Docs**

set trigger status appropriately if they do not have broker

---

pkg/broker/ingress/ingress_handler_test.go
pkg/inmemorychannel/message_dispatcher_test.go
pkg/mtbroker/ingress/ingress_handler_test.go

Fixes #3164
t.Fatal[f] must not be called in a goroutine different from the test itself: https://golang.org/pkg/testing/#T

Remove t.Fatal calls from goroutines.

---

OWNERS
OWNERS_ALIASES

Making TOC members approvers in every repository for consistency. An alias keeps this separate from repo-native approvers.
Also added @slinkydeveloper as reviewer in addition to approver, since all the other approvers are also listed as reviewers.
@markusthoemmes

Add TOC as approvers

---

test/upgrade/probe_test.go
test/upgrade/prober/prober.go

Fixes #3178 
- Upgrade test status set to skip if errors found and `FailOnMissingEvents` is false
- Rename `TestProbe` to more meaningful `TestContinuousEventsPropagationWithProber`
follow up to #2388

Upgrade test status set to skip if errors found

---

config/channels/in-memory-channel/300-in-memory-channel.yaml
config/core/resources/channel.yaml
config/core/resources/eventtype.yaml
config/core/resources/parallel.yaml
config/core/resources/sequence.yaml
config/core/resources/subscription.yaml
config/core/resources/trigger.yaml
pkg/apis/messaging/v1alpha1/in_memory_channel_defaults.go
pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go

Addresses #3095
- Change storage version from v1alpha1 to v1beta1:
```
- "parallels.flows.knative.dev"
- "sequences.flows.knative.dev"
- "eventtypes.eventing.knative.dev"
- "triggers.eventing.knative.dev"
- "channels.messaging.knative.dev"
- "inmemorychannels.messaging.knative.dev"
- "subscriptions.messaging.knative.dev"
```
```release-note
Change storage versions from v1alpha1 to v1beta1:
- "parallels.flows.knative.dev"
- "sequences.flows.knative.dev"
- "eventtypes.eventing.knative.dev"
- "triggers.eventing.knative.dev"
- "channels.messaging.knative.dev"
- "inmemorychannels.messaging.knative.dev"
- "subscriptions.messaging.knative.dev"
```
**Docs**

change storage versions to v1beta1

---

test/upgrade/probe_test.go
test/upgrade/prober/prober.go

Fixes #3191 
- Rename FailOnMissingEvents flag to FailOnErrors for upgrade tests

Rename FailOnMissingEvents flag to FailOnErrors for upgrade tests

---

test/upgrade/prober/config.toml
test/upgrade/prober/configuration.go

Fixes #3174 
- Fetches the broker URL at runtime
follow up to #2388

Fetch broker URL at runtime for upgrade tests

---

pkg/reconciler/broker/broker_test.go
pkg/reconciler/broker/resources/filter.go
pkg/reconciler/broker/resources/filter_test.go
pkg/reconciler/broker/resources/ingress.go

- Switch the metrics port of the Channel Based Broker components to 9092
- The change to using this port was in #2406.
```release-note
NONE
```

Switch the metrics port of the Channel Based Broker components to 9092

---

cmd/webhook/main.go
config/core/deployments/webhook.yaml

Users can use env var WEBHOOK_PORT to configure the webhook port. If the env var is not set, the default port will be used.
```release-note
NONE
```

Use env var WEBHOOK_PORT to configure the webhook port

---

test/conformance/broker_control_plane_test.go
test/conformance/helpers/broker_control_plane_test_helper.go

Fixes: #2704
Tests if the broker control plane:
- Trigger can be created before Broker (with attributes filter)
- Broker can be created and progresses to Ready
- Ready Broker is Addressable
- Trigger with Ready broker progresses to Ready
- Ready Trigger includes status.subscriberUri

Add Broker control plane tests for Broker v1beta1

---

test/conformance/channel_addressable_resolver_cluster_role_test.go
test/conformance/helpers/channel_addressable_resolver_cluster_role_test_helper.go
test/conformance/helpers/rbac.go

Fixes #1959
- Conformance tests for control plane aggregated addressable resolver ClusterRole
- Extracted some functionality in similar conformance tests into a common place

Conformance tests for channel control plane aggregated addressable resolver ClusterRole

---

pkg/apis/sources/v1alpha2/apiserver_lifecycle.go
pkg/apis/sources/v1alpha2/apiserver_lifecycle_test.go
pkg/apis/sources/v1alpha2/apiserver_types.go
pkg/apis/sources/v1alpha2/apiserver_types_test.go
pkg/apis/sources/v1alpha2/container_lifecycle.go
pkg/apis/sources/v1alpha2/container_lifecycle_test.go
pkg/apis/sources/v1alpha2/container_types.go
pkg/apis/sources/v1alpha2/ping_lifecycle.go
pkg/apis/sources/v1alpha2/ping_lifecycle_test.go
pkg/apis/sources/v1alpha2/ping_types.go
pkg/apis/sources/v1alpha2/sinkbinding_lifecycle.go
pkg/apis/sources/v1alpha2/sinkbinding_lifecycle_test.go
pkg/apis/sources/v1alpha2/sinkbinding_types.go
pkg/apis/sources/v1alpha2/sinkbinding_types_test.go

Issue #3221
- implement krshaped for sources types
```release-note
```
**Docs**

Implement krshaped for sources types

---

test/lib/resources/constants.go

These are used in various places in eventing tests and should keep pace with our latest API versions.
I noticed one constant still uses v1alpha1 of serving. I don't know if that version is even served anymore but I updated it anyway.
- Use v1beta1 versions of eventing, messaging, and flows groups by default in tests

Update default API versions in tests to v1beta1

---

pkg/apis/eventing/v1beta1/broker_types.go
pkg/apis/eventing/v1beta1/eventtype_types.go
pkg/apis/eventing/v1beta1/trigger_types.go
pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go

Issue #3099
- Update eventing resources to use genreconciler common logic
- Automatically ensures ObserveGeneration is bumped
```release-note
```
**Docs**

Update krshaped resources to common logic

---

pkg/adapter/apiserver/adapter.go
pkg/adapter/apiserver/adapter_test.go
pkg/adapter/ping/adapter.go
pkg/adapter/ping/adapter_test.go
pkg/adapter/v2/main.go
pkg/adapter/v2/main_message.go
pkg/adapter/v2/main_message_test.go
pkg/adapter/v2/main_test.go

- receive adapter now starts in a context
-
-
```release-note
```
**Docs**
/hold need similar PR for eventing-contrib

Run adapter in a context

---

test/lib/event_sender.go
test/lib/operation.go
test/lib/resources/kube.go
test/lib/resources/sender/sender.go
test/test_images/event-sender/main.go
test/test_images/event-sender/pod.yaml

This image is meant to replace the old `sendevents`, helping transitioning the tests to sdk-go v2 #3034 
After we get this one in and #3229 we can slowly start porting the test code to use only sdk-go v2 and remove the internal `Cloudevent` representation
- New image has exactly the same functionalities as before, but it uses sdk-go v2 and doesn't use the internal lib/cloudevents. This image doesn't replace the previous one and introduces new apis to use it.

New event-sender image

---

pkg/apis/flows/v1beta1/parallel_types.go
pkg/apis/flows/v1beta1/sequence_types.go
pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go
pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go
pkg/reconciler/parallel/parallel.go
pkg/reconciler/sequence/sequence.go

Issue #3099
- Generate logic to automatically bump generation for /api/flows types
```release-note
```
**Docs**

Automatically handle observed generation for apis/flow resources

---

pkg/apis/messaging/v1beta1/channel_types.go
pkg/apis/messaging/v1beta1/in_memory_channel_types.go
pkg/apis/messaging/v1beta1/subscription_types.go
pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go
pkg/reconciler/channel/channel.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
pkg/reconciler/subscription/subscription.go

Issue #3099
- Generate logic to automatically bump generation for /api/messaging types
```release-note
```
**Docs**

Automatic generation bump for apis/messaging

---

test/conformance/helpers/broker_tracing_test_helper.go

Use `utils.GetClusterDomainName() ` -- which either uses the same default `cluster.local` or gets the actual domain

Broker Tracing Test: Get actual cluster domain name

---

pkg/reconciler/mtnamespace/namespace.go

Namespace events created during reconciliation end up in `default` namespace. This gives a bad and unexpected UX for Eventing users since in our case, the user is interacting with Triggers and Brokers that are in a specific namespace and expects Events being there.
Fixes #3084 
- Enforcing namespace for namespace reconciliation events with regards to broker creation. 
```release-note
When default broker is created via namespace reconciler, the Kubernetes events will be created in the correct namespace instead of some of them getting created in default namespace.
```

Set correct namespace for namespace reconciliation events

---

config/pre-install/v0.16.0/clusterrole.yaml
config/pre-install/v0.16.0/dummy.go
config/pre-install/v0.16.0/serviceaccount.yaml
config/pre-install/v0.16.0/storage-version-migration.yaml

Fixes #3261 
- Add a Preinstall job that migrates Brokers from v1alpha1 to v1beta1.
-
-
```release-note
Eventing v1alpha1 API is removed.
action required: You must run pre-install job prior to upgrading to get Brokers to v1beta1 API.
```
**Docs**
https://github.com/knative/docs/issues/2543

add a job for migrating broker storage versions to v1beta1

---

test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/e2e/source_api_server_test.go
test/e2e/source_container_test.go
test/e2e/source_ping_test.go
test/e2e/source_sinkbinding_v1alpha1_test.go
test/e2e/source_sinkbinding_v1alpha2_test.go
test/e2e/trigger_dependency_annotation_test.go
test/lib/checkevents.go
test/lib/checkevents_test.go
test/lib/requests.go
test/test_images/recordevents/eventstore.go
test/test_images/recordevents/eventstore_test.go
test/test_images/recordevents/main.go

Moves more of the e2e tests from log parsing to recordevents.  In addition to allowing more specific tests, this makes us more resilient to changes in log formatting.  This is particularly important for cloudevents v2 migration.
This also move test_images/recordevents and the test client side helpers to cloudevents v2.

Move more e2e test log parsing to recordevents

---

test/e2e/channel_single_event_test.go
test/e2e/helpers/channel_single_event_helper.go
test/lib/checkevents.go
test/lib/cloudevents.go
test/upgrade/smoke_test.go

- Channel single event e2e test now uses new event sender and event record 
cc @ericlem @n3wscott @nlopezgi

Port channel single event e2e test to new test facilities

---

test/e2e/helpers/channel_chain_test_helper.go
test/test_images/transformevents/main.go

Part of #3267
- Ported `ChannelChainTestHelper` to new test images

Port Channel Chain Test to new test images

---

config/pre-install/v0.16.0/broker.yaml

Fixes #
- Add a Broker crd that has storage switched from v1alpha1 to v1beta1
- We will use this while running the storage migration.
```release-note
```
**Docs**

add an intermediate broker CRD for moving storage to v1beta1

---

test/e2e/helpers/sequence_test_helper.go
test/test_images/sequencestepper/main.go

Part of #3267
- Ported `SequenceTestHelper` to new test images
fyi @slinkydeveloper @n3wscott

Port Sequence Test to new test images

---

test/e2e/helpers/channel_defaulter_test_helper.go

Part of #3267
- Port `ChannelDefaulterTestHelper` to new test images
fyi @slinkydeveloper @vaikas

Port Default channel Test to new test images

---

test/e2e/helpers/channel_dls_test_helper.go

Part of #3267
- Port `ChannelDLSTestHelper` to new test images
fyi @slinkydeveloper @vaikas

Port dead letter sink Test to new test images

---

test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/e2e/helpers/broker_channel_flow_test_helper.go
test/e2e/helpers/broker_event_transformation_test_helper.go
test/e2e/helpers/broker_with_config_helper.go
test/e2e/helpers/channel_event_tranformation_test_helper.go
test/lib/resources/kube.go

Part of #3267
- Port `ChannelEventTranformationTestHelper` to new test images
fyi @slinkydeveloper @vaikas

Port Channel event transformation Test to new test images

---

pkg/reconciler/trigger/controller.go

Fixes #
- Trigger controller watches brokers to update trigger status immediately. Without this, if a broker is deleted while its triggers still exist, the trigger READY status will still be True.
-
-
```release-note
NONE
```
**Docs**

Trigger controller watches brokers to update trigger status immediately

---

config/core/deployments/controller.yaml

Fixes #
As per https://github.com/knative/operator/issues/73, indicate the HA deployments (the only one is `eventing-controller` deployment)
- Indicate the HA deployments (the only one is `eventing-controller` deployment)
Operator PR that will allow the operator to read the label is on its way

Indicate HA deployment for eventing-controller

---

test/performance/infra/receiver/receiver.go
test/test_images/filterevents/main.go
test/test_images/heartbeats/main.go

Ported heartbeats and filterevents to sdk-go v2

---

test/lib/recordevents/event_info_store.go

Part of #3267
- Now errors throw by Assert* includes the stacktrace, printing it

Added stacktraces to recordevents Assert*

---

test/conformance/header_test.go
test/conformance/helpers/channel_header_single_event_helper.go
test/lib/recordevents/event_info_matchers.go
test/lib/resources/sender/sender.go
test/test_images/event-sender/main.go

Part of #3267
- Channel header single event helper port to new test images
- Also changed the test header (testing the tracing header was pointless, given we already have tests for tracing which correctly test the trace tree creation)

Channel header single event helper port to new test images

---

test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/conformance/helpers/tracing_test_helper.go

Part of #3267 
- Ported `TestBrokerTracing` to new test images
- Reorganized a bit the tracing tests

Port Broker conformance tests to new test images

---

config/brokers/channel-broker/deployments/controller.yaml
config/channels/in-memory-channel/500-controller.yaml
config/channels/in-memory-channel/500-dispatcher.yaml

Found more leader-elected components and HA deployments, on top of https://github.com/knative/eventing/pull/3311
Ref: https://github.com/knative/eventing/blame/master/config/core/configmaps/leader-election.yaml#L62

Cont'd: indicate HA deployment for eventing-controller

---

pkg/reconciler/apiserversource/resources/receive_adapter.go
pkg/reconciler/apiserversource/resources/receive_adapter_test.go

PingSource and ApiServerSource doesn't set extension headers for ceOverride #3253
ApiServer 
Fixes #3253 
-
-
-
<!--
- 🐛 Fix bug
**Docs**
none

PingSource and ApiServerSource doesn't set extension headers for ceOverride #3253

---

pkg/reconciler/apiserversource/apiserversource.go
pkg/reconciler/channel/channel.go
pkg/reconciler/containersource/containersource.go
pkg/reconciler/eventtype/eventtype.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
pkg/reconciler/mtbroker/broker.go
pkg/reconciler/parallel/parallel.go
pkg/reconciler/pingsource/pingsource.go
pkg/reconciler/sequence/sequence.go
pkg/reconciler/subscription/subscription.go

- The gen-reconciler code should now handle setting ObservedGeneration and initializing conditions. This change simplifies by letting the upstream code handle it.

Allow the Generated reconciler code to handle init

---

test/conformance/channel_message_modes_specversion_test.go
test/conformance/helpers/channel_message_modes_specversion_helper.go
test/lib/recordevents/event_info_matchers.go
test/lib/recordevents/event_info_store.go

Added conformance test for Specversion/Message modes matrix

---

test/conformance/helpers/source_crd_metadata_test_helper.go
test/conformance/main_test.go
test/conformance/source_crd_metadata_test.go
test/e2e-tests.sh
test/e2e_flags.go
test/flags/channels.go
test/flags/eventing_environment.go
test/flags/parsing.go
test/flags/sources.go

Fixes #3116 
- Add initial source conformance test for source label
- Add `-sources` e2e testing flag
```release-note
- Add Eventing sources conformance test for validating required labels on Eventing source CRDs
```

Add sources metadata conformance test

---

docs/spec/channel.md

* Removed DTE specification to force the trace propagation. https://github.com/cloudevents/spec/pull/607 tl;dr there were changes in the CE spec lately, now in channels we use only the w3c tracecontext.
* Specified that the channel internally may use the mechanism it wants to propagate trace from sender to receiver, as soon the output receiver then sends it using w3c tracecontext.
* Added `knativehistory` extension
* Specified that the channel may change the http message mode from sender to subscribers

Fix Channel Data plane spec

---

pkg/apis/eventing/v1/broker_conversion_test.go
pkg/apis/eventing/v1/trigger_conversion_test.go
pkg/apis/eventing/v1beta1/broker_conversion.go
pkg/apis/eventing/v1beta1/broker_conversion_test.go
pkg/apis/eventing/v1beta1/eventtype_conversion_test.go
pkg/apis/eventing/v1beta1/trigger_conversion.go
pkg/apis/eventing/v1beta1/trigger_conversion_test.go

- Improve eventing v1beta1 conversion tests as noted in https://github.com/knative/eventing/pull/3372#discussion_r444028257
I can improve conversion tests for other types after seeing how this PR goes.
UPDATE:  I now realize in other conversion tests there was a test like v1->v1beta1->v1. (nothing on the current state of the source tree, but saw some stuff from Git history)
I will do that in a separate PR. let's merge this one anyway

Improve eventing v1beta1 conversion tests

---

pkg/apis/eventing/v1beta1/broker_conversion.go
pkg/apis/eventing/v1beta1/broker_conversion_test.go
pkg/apis/eventing/v1beta1/trigger_conversion.go
pkg/apis/eventing/v1beta1/trigger_conversion_test.go

Part of  #3337
- Conversion from/to v1 <--> v1beta1 types
- v1->v1beta1->v1 and v1beta1->v1->v1beta1 tests

Eventing conversion v1 <> v1beta1

---

pkg/adapter/v2/config.go
pkg/adapter/v2/config_test.go
pkg/adapter/v2/main.go
pkg/adapter/v2/main_message.go
pkg/adapter/v2/main_message_test.go
pkg/adapter/v2/main_test.go

For #3157
- Receive adapter can now run in leader elected mode
-
-
```release-note
```
**Docs**

receive adapters can now run in leader elected mode

---

test/e2e-common.sh
test/e2e-upgrade-tests.sh

Fixes #
- adding pre_16 
- remove post_15
-
```release-note
```
**Docs**

Reorg some test runs

---

cmd/mtping/main.go
pkg/adapter/mtping/adapter.go
pkg/adapter/mtping/adapter_test.go
pkg/adapter/mtping/controller.go
pkg/adapter/mtping/controller_test.go
pkg/reconciler/pingsource/pingsource.go
pkg/reconciler/pingsource/resources/mt_receive_adapter.go
pkg/reconciler/pingsource/resources/mt_receive_adapter_test.go

For #3157
- Top-level cmd uses shared main adapter instead of shared main controller
- No more hot config files reloading
-
```release-note
```
**Docs**
Depends on https://github.com/knative/eventing/pull/3370.

mtping now uses shared main adapter

---

go.mod
go.sum
vendor/knative.dev/pkg/webhook/admission.go
vendor/knative.dev/pkg/webhook/conversion.go
vendor/modules.txt

This should unblock https://github.com/knative/eventing/pull/3409
- This includes webhook fixes that should make upgrading from 0.15 to 0.16 smooth
```release-note
Webhook responses now return TypeMeta which would interrupt serving upgrades 
```

[release-0.15] update knative.dev/pkg which includes webhook fixes

---

pkg/apis/messaging/v1beta1/subscription_conversion.go
pkg/apis/messaging/v1beta1/subscription_conversion_test.go

Part of https://github.com/knative/eventing/issues/3336
- Conversion for subscription v1<>v1beta1
-
-
```release-note
```
**Docs**

Subscription v1<>v1beta conversion

---

test/e2e/helpers/broker_test_helper.go

(I hope) fixes #2913
- Modified code that creates recordevents pod. This code has a wait logic that should prevent errors like this: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-eventing-continuous/1276287322534449152#1:build-log.txt%3A12077

Wanna fix e2e test flakyness

---

cmd/webhook/main.go
pkg/apis/duck/v1beta1/delivery_conversion.go
pkg/apis/flows/v1beta1/parallel_conversion.go
pkg/apis/flows/v1beta1/parallel_conversion_test.go
pkg/apis/flows/v1beta1/sequence_conversion.go
pkg/apis/flows/v1beta1/sequence_conversion_test.go

For #3335
- Add flow conversion webhook v1 <-> v1beta1
- Add flow v1 defaulting
-
```release-note
```
**Docs**

Flow v1 conversion

---

go.mod
go.sum
pkg/channel/message_receiver.go
test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_message_modes_specversion_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/e2e/helpers/broker_channel_flow_helper.go
test/e2e/helpers/parallel_test_helper.go
test/e2e/helpers/sequence_test_helper.go
test/e2e/source_api_server_test.go
test/lib/operation.go
test/lib/recordevents/event_info_matchers.go
test/lib/recordevents/event_info_store.go
test/lib/send_event.go
test/test_images/event-sender/main.go
vendor/github.com/cloudevents/sdk-go/v2/client/http_receiver.go
vendor/github.com/cloudevents/sdk-go/v2/test/event_matchers.go
vendor/modules.txt

Part of #1845
- Now it tests the equality of the events received
- Removed some assertions from recordevents because https://github.com/cloudevents/sdk-go/pull/538 adds them to sdk-go 
- Increase verbosity in test failures (now it prints the stack)
Let's wait https://github.com/cloudevents/sdk-go/pull/538 first.

Expanded the Channel data plane conformance test

---

pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go

Part of #3336 
- Conversions for in-memory-channel v1beta1<->v1
- No webhooks in this PR (will be added in upcoming PR)
-
fyi @vaikas @lionelvillard @aliok

conversions for imc v1beta1 <->v1

---

DEVELOPMENT.md

Fixes
E2E tests fail without the installation of the MT Channel Based Broker. Development.md is a bit vague and says the user might want to install other brokers, instead of specifying which brokers need to be installed other than the default.
- Modify DEVELOPMENT.md to include the instruction for installing the mt-channel-broker

[master] Updated Development.md to include installing mt-channel-broker

---

cmd/mtping/main.go
config/core/configmaps/leader-election.yaml
config/core/roles/pingsource-mt-adapter-clusterrole.yaml
pkg/adapter/mtping/adapter.go
pkg/leaderelection/leader_election.go
pkg/leaderelection/leader_election_test.go
pkg/reconciler/pingsource/controller.go
pkg/reconciler/pingsource/pingsource.go
pkg/reconciler/pingsource/resources/mt_receive_adapter.go
pkg/reconciler/pingsource/resources/mt_receive_adapter_test.go

For #3157
- PingSource controller passes the leader election config down to the mtping adapter
-
-
```release-note
```
**Docs**
Depends on https://github.com/knative/eventing/pull/3371

pass leader election config to mtping

---

config/channels/in-memory-channel/300-in-memory-channel.yaml
config/core/resources/apiserversource.yaml
config/core/resources/broker.yaml
config/core/resources/channel.yaml
config/core/resources/containersource.yaml
config/core/resources/eventtype.yaml
config/core/resources/parallel.yaml
config/core/resources/pingsource.yaml
config/core/resources/sequence.yaml
config/core/resources/sinkbindings.yaml
config/core/resources/subscription.yaml
config/core/resources/trigger.yaml
config/pre-install/v0.16.0/broker.yaml
config/pre-install/v0.16.0/pingsource.yaml

Fixes #3349
- using `v1` of the CRD type
```release-note
Our CustomResourceDefinitions now use apiextensions.k8s.io/v1 APIs
```
**Docs**

Use CRD & Webhook v1 APIs

---

go.mod
go.sum
test/conformance/helpers/broker_tracing_test_helper.go
test/conformance/helpers/channel_header_single_event_helper.go
test/conformance/helpers/channel_message_modes_specversion_helper.go
test/conformance/helpers/channel_tracing_test_helper.go
test/e2e/helpers/channel_single_event_helper.go
test/lib/creation.go
test/lib/recordevents/event_info_store.go
test/lib/send_event.go
test/lib/sender/events.go
test/lib/sender/matchers.go
test/lib/sender/resources.go
test/test_images/event-sender/main.go
test/test_images/transformevents/main.go
vendor/github.com/cloudevents/sdk-go/v2/client/client.go
vendor/github.com/cloudevents/sdk-go/v2/test/event_mocks.go
vendor/modules.txt

Part of #1845
- This change introduces a way to perform asserts of event-sender result (eg status code)
- Added 202 status code assert to channel data plane conformance test

Asserts on event-sender

---

config/core/resources/trigger.yaml

Addresses #3411
- openapi schema matches reality
-
-
```release-note
```
**Docs**

fix trigger openapi

---

test/conformance/channel_data_plane_test.go
test/conformance/helpers/channel_data_plane_helper.go
test/lib/client.go
test/lib/send_event.go
test/lib/sender/events.go
test/lib/sender/resources.go
test/test_images/event-sender/main.go
test/test_images/recordevents/main.go
test/test_images/request-sender/main.go
test/test_images/request-sender/pod.yaml
test/test_images/transformevents/main.go
test/test_images/utils.go

Fixes #1845
- Added a new test image to send raw http requests (mainly useful to send bad event requests)
- Added status code checks for 405 and 400 to channel data plane conformance tests
- Rename TestChannelEventModesAndSpecVersions to TestChannelDataPlaneSuccess

Added conformance tests for failing status code in channel data plane

---

docs/spec/broker.md
pkg/mtbroker/filter/filter_handler.go
pkg/mtbroker/filter/filter_handler_test.go

Fixes #3438 
- Change the spec of what happens if event delivery succeeds but the function returns a malformed event.
- Do not silently ignore malformed events coming from the functions.
- Fix a bunch of tests that were not doing anything to actually do something.
```release-note
- 🐛 Fix bug - If a function returns a malformed event, treat that the same as a failed event delivery.
```
**Docs**

deal with malformed events as errors

---

pkg/apis/messaging/v1/subscription_lifecycle.go
pkg/apis/messaging/v1beta1/subscription_lifecycle.go

- Expand variadic args.
Without this, we see:
```
"message": "Subscription marked by Channel as False%!(EXTRA []interface {}=[])"
```
```release-note
NONE
```

Expand the variadic args.

---

test/e2e-common.sh

Fixes #3469 
- create knative-monitoring namespace in the tests because somehow it's gone missing from the release.
-
-
```release-note
```
**Docs**

add a hack to work around knative-monitoring ns missing

---

config/core/resources/trigger.yaml
pkg/apis/eventing/v1/trigger_defaults.go
pkg/apis/eventing/v1/trigger_defaults_test.go

Addresses #3138 
- Do not default v1 Trigger.spec.broker anymore
```release-note
For v1 Trigger you must always specify a spec.broker, it is no longer defaulted to "default" 
```
**Docs**

Do not default trigger.spec.broker for v1.Trigger

---

config/core/roles/clusterrole-namespaced.yaml

Fixes #3464
- Add cluster role which will give namespace admin to manage bindings.knative.dev
- As this is a common Cluster Role creating here instead of eventing contrib

add cluster role for bindings

---

config/channels/in-memory-channel/300-in-memory-channel.yaml
config/core/resources/channel.yaml
config/core/resources/subscription.yaml
pkg/apis/duck/v1beta1/subscribable_types_conversion.go
pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
pkg/apis/messaging/v1/channel_types.go
pkg/apis/messaging/v1beta1/channel_conversion.go
pkg/apis/messaging/v1beta1/channel_conversion_test.go
pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go
pkg/reconciler/subscription/subscription.go
test/conformance/helpers/channel.go
test/conformance/helpers/channel_spec_test_helper.go
test/conformance/helpers/channel_status_subscriber_test_helper.go
test/conformance/helpers/channel_status_test_helper.go
test/e2e-tests.sh
test/e2e-upgrade-tests.sh
test/e2e/channel_chain_test.go
test/e2e/channel_dls_test.go
test/e2e/channel_event_transformation_test.go
test/e2e/channel_single_event_test.go
test/e2e/helpers/channel_chain_test_helper.go
test/e2e/helpers/channel_dls_test_helper.go
test/e2e/helpers/channel_event_tranformation_test_helper.go
test/e2e/helpers/channel_single_event_helper.go
test/lib/creation.go
test/lib/resources/eventing.go

Addresses #3446 
- Add v1 types for crds: channel,inmemorychannel,subscription
- add e2e tests
-
```release-note
- 🎁 Add new feature bump channel, subscription, inmemorychannel to v1.
After upgrading to this version if you downgrade to .15 you must first manually patch (or edit) subscriptions.messaging.knative.dev CRD like so:
kubectl patch crd subscriptions.messaging.knative.dev --type='json' -p '[{"op" : "remove", "path" : "/spec/conversion/webhook"},{"op":"replace", "path":"/spec/conversion/strategy","value" : "None"}]'
```
**Docs**
https://github.com/knative/docs/pull/2630

bump channel,imc,subscription to v1, add e2e tests

---

pkg/reconciler/subscription/subscription.go

When tracking Channels, use consistent v1beta1 since that's the lister we use. Otherwise, there will be flakiness. 
- We first saw this in: https://github.com/knative/eventing/issues/2641
- 
```release-note
```
**Docs**

use consistent version with tracker/lister

---

pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go

Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print)`
`goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party | grep -v .pb.go | grep -v wire_gen.go)`

[master] golang format tools

---

config/core/configmaps/leader-election.yaml
pkg/adapter/v2/main.go
pkg/adapter/v2/main_message.go
pkg/leaderelection/context.go
pkg/leaderelection/context_test.go

For #3157
- Allow for various leader election strategies. 
-
-
```release-note
```
**Docs**
Since the implementation provided by k8s is buggy and not optimal (pull only) we need a way to replace it.
Depends on https://github.com/knative/eventing/pull/3384

pluggable leader election strategy

---

pkg/apis/duck/v1/subscribable_types.go
pkg/apis/duck/v1/subscribable_types_conversion.go
pkg/apis/duck/v1/subscribable_types_conversion_test.go
pkg/apis/duck/v1alpha1/subscribable_types.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
pkg/apis/duck/v1beta1/subscribable_types.go
pkg/apis/duck/v1beta1/subscribable_types_conversion.go
pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
pkg/apis/messaging/v1beta1/channel_conversion.go
pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go

Same story with that https://github.com/knative/eventing/pull/3471, but for `SubscribableSpec`

Make SubscribableSpec implement apis.Convertible

---

pkg/apis/eventing/v1/broker_validation.go
pkg/apis/eventing/v1/broker_validation_test.go
pkg/apis/eventing/v1beta1/broker_validation.go
pkg/apis/eventing/v1beta1/broker_validation_test.go
pkg/reconciler/mtnamespace/resources/broker.go

Validate that BrokerClass annotation is there and non-empty
- validate that BrokerClass annotation exists and is non-empty.
```release-note
Can not create brokers without BrokerClassAnnotation.
```
**Docs**

Validate brokerclass exists

---

pkg/apis/duck/v1/subscribable_types.go
pkg/apis/duck/v1/subscribable_types_conversion.go
pkg/apis/duck/v1/subscribable_types_conversion_test.go
pkg/apis/duck/v1alpha1/subscribable_types.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
pkg/apis/duck/v1beta1/subscribable_types.go
pkg/apis/duck/v1beta1/subscribable_types_conversion.go
pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go

Same story with https://github.com/knative/eventing/pull/3471 , but for `SubscriberSpec`

Make SubscriberSpec implement apis.Convertible

---

config/core/configmaps/leader-election.yaml
pkg/leaderelection/leader_election_test.go

- knative.dev/pkg only supports lease locks given our minimum K8s now has the v1 coordination API
```release-note
Leader election config only supports lease locks
```

drop use of unsupported resource locks from the leaderelection example config

---

pkg/apis/duck/v1/subscribable_types.go
pkg/apis/duck/v1/subscribable_types_conversion.go
pkg/apis/duck/v1/subscribable_types_conversion_test.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
pkg/apis/duck/v1beta1/subscribable_types.go
pkg/apis/duck/v1beta1/subscribable_types_conversion.go
pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go

Same story with https://github.com/knative/eventing/pull/3471, but for `SubscriberStatus`

Make SubscriberStatus implement apis.Convertible

---

pkg/apis/messaging/v1/subscription_validation.go
pkg/apis/messaging/v1/subscription_validation_test.go

Fixes #3521
- subscription.spec.channel should be immutable, wire the checks through as they should be.
-
-
```release-note
- 🐛 Fix bug
Subscription.spec.channel should be immutable, it's even being tested but not actually wired through.
```
**Docs**

actually make subscription.spec.channel immutable

---

pkg/apis/messaging/v1/channel_validation.go
pkg/apis/messaging/v1/channel_validation_test.go

Fixes #3518 
- Actually wire through the immutable checks. 
- Remove the test which is invalid, because subscribers are not allowed to be set (changed a long time ago...)
-
```release-note
- 🐛 Fix bug
Make channel.spec.channeltemplate immutable as it should be.
```
**Docs**

actually make channel.spec.channelspec immutable

---

pkg/apis/eventing/v1/broker_validation.go
pkg/apis/eventing/v1/broker_validation_test.go

Fixes #3516
- Make BrokerClass immutable as it was intended.
-
-
```release-note
- 🐛 Fix bug
BrokerClass annotation is supposed to be immutable but was not properly wired through, make it so.
```
**Docs**

actually make brokerclass immutable

---

pkg/apis/eventing/v1/trigger_validation.go
pkg/apis/eventing/v1/trigger_validation_test.go

Fixes #3515  
- Actually wire the CheckImmutableFields to be called for Trigger.
-
-
```release-note
- 🐛 Fix bug
The code that was ensuring that trigger.spec.broker field was immutable was never called. Well, except in the unit tests...
```
**Docs**

actually make trigger.spec.broker immutable

---

pkg/adapter/v2/config_test.go
pkg/adapter/v2/main.go
pkg/adapter/v2/main_message.go
pkg/adapter/v2/main_message_test.go
pkg/adapter/v2/main_test.go

Fixes #
- Adapter main now inject standard elector builder when leader election is turned on 
for the given component
-
-
```release-note
```
**Docs**

Adapter main now inject standard elector builder 

---

hack/k8s-client-go.patch
hack/update-deps.sh
vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go

For #3157
- Patch the k8s leader election code fixing graceful release
-
-
```release-note
```
**Docs**
More information: https://github.com/kubernetes/kubernetes/pull/91942

apply k8s leader election graceful release fix in vendor

---

config/core/resources/trigger.yaml

Fixes #
I made a mistake making broker a required field in the v1beta1 schema making broker a required field when it is only required in the v1. 
- v1beta1 version of trigger.spec.broker is not required.
-
-
```release-note
```
**Docs**

v1beta1 still defaults broker

---

pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
pkg/apis/duck/v1beta1/subscribable_types_conversion.go

- Adds error handling for Subscribable related subtype conversions

Improve error handling at conversion of Subscribable subtypes

---

test/upgrade/prober/configuration.go
test/upgrade/prober/prober.go

Address #3538 
- Use the creation.*OrFail methods and dump resources via tracker.
- Create the Broker directly without using the sugar annotations.
-
```release-note
```
**Docs**

Use the standard resource creation libs for upgrade tests.

---

test/lib/duck/resource_inspectors.go

Fixes #3540
- Check that the status.Addressable is non nil before using it and failing if not there.
-
-
```release-note
```
**Docs**

nil check on addressable

---

hack/release.sh

Fixes #3535
```
- Rename pre and post install scripts.
```

Rename the migration yaml names into eventing-pre- and eventing-post-install-jobs

---

config/channels/in-memory-channel/300-in-memory-channel.yaml
config/core/resources/broker.yaml
config/core/resources/channel.yaml
config/core/resources/parallel.yaml
config/core/resources/sequence.yaml
config/core/resources/subscription.yaml
config/core/resources/trigger.yaml

The presence of the fields is causing noise in the webhook logs for some reason.
- Remove all the v1alpha1 versions from the CRD (was served=false, stored=false).
-
-
```release-note
Remove the v1alpha1 CRD api versions.
```
**Docs**

remove the v1alpha1 api versions all together

---

config/pre-install/v0.16.0/storage-version-migration.yaml

- This PR updated the job name and its label into storage-version-migration-eventing. The purpose is to avoid naming conflict with the job in knative serving.

Update the job name and label into storage-version-migration-eventing

---

test/e2e-common.sh
test/performance/performance-tests.sh

Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
Part of https://github.com/knative/eventing/pull/3547
`ChannelBasedBroker` doesn't exist anymore.
- Remove channel-broker from tests

Remove channel-broker from tests

---

config/post-install/v0.15.0/storage-version-migration.yaml
config/pre-install/v0.16.0/storage-version-migration.yaml

Fixes #3532 
* Fixing issue where jobs do not complete on istio enabled cluster
```release-note
Fixes issue where migration jobs would fail on Istio cluster with auto-inject enabled
```

Adding istio annotation

---

pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go

Final step of https://github.com/knative/eventing/issues/3474

Subscribable types and subtypes v1<>v1alpha1 conversion

---

pkg/apis/eventing/v1/broker_lifecycle.go
pkg/apis/eventing/v1/broker_lifecycle_mt.go
pkg/apis/eventing/v1/broker_lifecycle_test.go
pkg/apis/eventing/v1beta1/broker_lifecycle.go
pkg/apis/eventing/v1beta1/broker_lifecycle_mt.go
pkg/apis/eventing/v1beta1/broker_lifecycle_test.go
pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
pkg/reconciler/mtbroker/controller.go

Fixes #3094 
- Allow registering custom conditions for the Broker

Allow registering custom conditions for the Broker

---

config/post-install/v0.15.0/storage-version-migration.yaml
config/pre-install/v0.16.0/storage-version-migration.yaml
test/lib/duck/resource_inspectors.go
test/upgrade/prober/configuration.go
test/upgrade/prober/prober.go

Fixes #3532 
backport #3534
backport #3542
backport #3543
backport #3539 
* Fixing issue where jobs do not complete on istio enabled cluster
```release-note
Fixes issue where migration jobs would fail on Istio cluster with auto-inject enabled
```

adding istion annotation (#3534)

---

pkg/apis/flows/v1/parallel_types.go
pkg/apis/flows/v1/sequence_types.go
pkg/client/injection/reconciler/flows/v1/parallel/controller.go
pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
pkg/client/injection/reconciler/flows/v1/sequence/controller.go
pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go

Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
Fixes #3585
-  adding `// +genreconciler` marker to `flows.* v1` types, so reconcilers are generated

generate reconcilers for flows.* v1 resources

---

pkg/apis/duck/v1/register.go
pkg/apis/duck/v1/register_test.go
pkg/reconciler/mtbroker/broker.go
pkg/reconciler/mtbroker/broker_test.go
pkg/reconciler/mtbroker/config.go
pkg/reconciler/mtbroker/config_test.go
pkg/reconciler/mtbroker/controller.go
pkg/reconciler/mtbroker/controller_test.go
pkg/reconciler/mtbroker/resources/channel.go
pkg/reconciler/mtbroker/resources/channel_test.go
pkg/reconciler/mtbroker/resources/subscription.go
pkg/reconciler/mtbroker/resources/subscription_test.go
pkg/reconciler/mtbroker/trigger.go
pkg/reconciler/sugar/trigger/path/path.go
pkg/reconciler/testing/v1/broker.go
pkg/reconciler/testing/v1/configmap.go
pkg/reconciler/testing/v1/endpoints.go
pkg/reconciler/testing/v1/factory.go
pkg/reconciler/testing/v1/listers.go
pkg/reconciler/testing/v1/trigger.go
pkg/reconciler/testing/v1/unstructured.go

Fixes #3580
- Reconcile eventing.{Broker, Trigger} with v1 shape
- Generate / operate on dependent resources using v1 shapes (Subscriptions, channels, etc.)
-
```release-note
Reconcile eventing.{Broker,Trigger} using v1 api shape. Operate on dependent resources (Subscriptions, etc.) using their v1 shapes.
```
**Docs**

reconcile eventing with v1 resources, generate v1 dependent resources

---

config/core/deployments/webhook.yaml

When our webhook drains, it sleeps for `network.DefaultDrainTimeout` after failing readiness probes before exiting, see [here](https://github.com/knative/pkg/blob/4419e613c133505ea5109380102765a7699b9bf8/webhook/webhook.go#L229-L234) which is configured to [this value](https://github.com/knative/pkg/blob/4419e613c133505ea5109380102765a7699b9bf8/network/network.go#L39-L43).
I suspect that the default `terminationGracePeriodSeconds` (of `30`) is clipping this sleep already (due to the coordination involved), but I am also thinking about raising this value due to seeing a non-zero number of EOF messages running chaos during our e2e testing.
Related PR in serving: https://github.com/knative/serving/pull/8640
Example of the sort of failure that I'm …

Set a high terminationGracePeriodSeconds on webhook

---

go.mod
pkg/apis/duck/v1/fuzzer.go
pkg/apis/duck/v1beta1/delivery_conversion.go
pkg/apis/duck/v1beta1/delivery_conversion_test.go
pkg/apis/eventing/v1/fuzzer.go
pkg/apis/eventing/v1/roundtrip_test.go
pkg/apis/eventing/v1beta1/roundtrip_test.go
pkg/apis/flows/v1/fuzzer.go
pkg/apis/flows/v1/roundtrip_test.go
pkg/apis/flows/v1beta1/roundtrip_test.go
pkg/apis/messaging/v1/fuzzer.go
pkg/apis/messaging/v1/roundtrip_test.go
pkg/apis/messaging/v1beta1/channel_conversion.go
pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
pkg/apis/messaging/v1beta1/roundtrip_test.go
vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/compatibility.go
vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
vendor/modules.txt

Add RoundTrip tests for eventing.*, messaging.*, and flows.* resources.
- Add round trip tests and fuzzer for eventing.*, messaging.*, and flows.* resources.
-
-
```release-note
- 🐛 Fix bug
DeadLetterChannel was being dropped when converting between v1beta1<->v1
Not all the conditions were being properly converted between v1beta1<->v1. Basically only the Ready was.
```
**Docs**

add roundtrip tests

---

pkg/reconciler/pingsource/pingsource.go

Similar to #3599 use listers instead of apiclient.
- use deploymentlister instead of the api client to prevent unnecessary api calls.
-
-
```release-note
```
**Docs**

use configmaplister

---

pkg/reconciler/mtbroker/broker.go
pkg/reconciler/mtbroker/broker_test.go
pkg/reconciler/mtbroker/controller.go
pkg/reconciler/mtbroker/controller_test.go
pkg/reconciler/mtbroker/trigger.go

Addresses #3591
As part of debugging the #3591 there were couple of things we could do better to reduce the churn on the API server, namely use configmap lister instead of hitting the API server. Also use the same logic for deciding whether to update Trigger Status just like we would do if we were using genreconciler. 
- use configmap lister
- reduce trigger status churn
-
```release-note
```
**Docs**

configmaplister, reduce trigger status churn

---

test/lib/client.go

Was leading to errors within the tests themselves of invalid pod
EnvVars (blank) when the config wasn't available.
----
#

Return an error if the test client cannot getTracingConfig

---

docs/delivery/README.md
go.mod
go.sum
pkg/apis/duck/v1/delivery_types.go
pkg/apis/duck/v1/delivery_types_test.go
pkg/apis/duck/v1beta1/delivery_types.go
pkg/apis/duck/v1beta1/delivery_types_test.go
third_party/VENDOR-LICENSE/github.com/rickb777/date/period/LICENSE
third_party/VENDOR-LICENSE/github.com/rickb777/plural/LICENSE
vendor/github.com/rickb777/date/LICENSE
vendor/github.com/rickb777/date/period/doc.go
vendor/github.com/rickb777/date/period/format.go
vendor/github.com/rickb777/date/period/marshal.go
vendor/github.com/rickb777/date/period/parse.go
vendor/github.com/rickb777/date/period/period.go
vendor/github.com/rickb777/plural/.gitignore
vendor/github.com/rickb777/plural/.travis.yml
vendor/github.com/rickb777/plural/LICENSE
vendor/github.com/rickb777/plural/README.md
vendor/github.com/rickb777/plural/build+test.sh
vendor/github.com/rickb777/plural/doc.go
vendor/github.com/rickb777/plural/go.mod
vendor/github.com/rickb777/plural/plural.go
vendor/modules.txt

Fixes #3555
- `DeliverySpec.BackoffDelay` accept ISO8601 duration
- Update DeliverySpec.BackoffDelay documentation
```release-note
- 🐛 Fix bug 
`v1` and `v1beta1` DeliverySpec.BackoffDelay accept ISO8601 duration
```

DeliverySpec.BackoffDelay accept ISO8601 duration

---

pkg/reconciler/mtbroker/broker.go
pkg/reconciler/mtbroker/broker_test.go
pkg/reconciler/mtbroker/controller.go

After vaikas switched to the configmap lister, this is no longer needed.

Drop vestigial kubeclient.

---

cmd/mtchannel_broker/main.go

Addresses #3591 
- Add flags for configuring the client qps / burst rates.
```release-note
Add two flags to broker to control rest client QPS / Burst. Defaults to same as before.
```
**Docs**

add knobs for overriding qps / burst

---

pkg/reconciler/mtbroker/broker.go
pkg/reconciler/mtbroker/broker_test.go

Addresses #https://github.com/knative/pkg/issues/1520
While Matt and I were debugging things related to chaos, and in particular what happens to 'nop' controllers, we started looking at places were we are doing unnecessary api server calls. This is removing one of them.
Overarching issue tracking in /pkg
https://github.com/knative/pkg/issues/1520
- Do no emit trigger reconciled successfully event 
-
-
```release-note
When Trigger is reconciled, do not emit an event for it
```
**Docs**

remove event emit for normal trigger reconcile

---

test/e2e/broker_event_transformation_test.go
test/e2e/broker_with_many_triggers_test.go
test/e2e/helpers/broker_event_transformation_test_helper.go
test/e2e/helpers/broker_test_helper.go
test/e2e/helpers/trigger_no_broker_test_helper.go

- Allow running EventTrasformationForTriggerTest test with any Broker

EventTrasformationForTriggerTest can run with any Broker

---

config/core/resources/apiserversource.yaml
config/core/resources/containersource.yaml
config/core/resources/parallel.yaml
config/core/resources/pingsource.yaml
config/core/resources/sequence.yaml
config/core/resources/sinkbindings.yaml
config/core/resources/subscription.yaml

Validate the categories for CRDs

---

pkg/reconciler/containersource/containersource.go
pkg/reconciler/containersource/containersource_test.go
pkg/reconciler/containersource/controller.go
pkg/reconciler/containersource/controller_test.go
pkg/reconciler/containersource/resources/deployment.go
pkg/reconciler/containersource/resources/deployment_test.go
pkg/reconciler/containersource/resources/names.go
pkg/reconciler/containersource/resources/sinkbinding.go
pkg/reconciler/containersource/resources/sinkbinding_test.go
pkg/reconciler/testing/containersource.go
pkg/reconciler/testing/listers.go
test/e2e/source_container_v1alpha2_test.go
test/e2e/source_container_v1beta1_test.go
test/lib/creation.go

Part of https://github.com/knative/eventing/issues/3426
- ContainerSource reconciler and e2e tests for v1beta1
```release-note
ContainerSource is now in v1beta1
```

Reconciler and e2e tests for ContainerSource V1Beta1

---

test/conformance/broker_data_plane_test.go
test/conformance/helpers/broker_data_plane_test_helper.go
test/conformance/main_test.go
test/e2e_flags.go
test/flags/eventing_environment.go

Adding Data plane conformance tests for ingress and consumer as reported in #2705

Add Broker Data Plane Conformance tests for the Ingress and Consumer

---

DEVELOPMENT.md

Since E2E tests rely for some tests on sugar controller, we should document it in our development. One of our users ran into this.
- Document that sugar is opttional component, but if you're running e2e tests you need to install it.
-
-
```release-note
```
**Docs**

add step for installing sugar for e2e

---

docs/personas.md

Add Broker developer as an example of a System Integrator. We currently list only new Event Source, Channel implementors as System Integrators, with the addition of Broker Classes, we should add a Broker implementor as this type as well.
- Add Broker implementor as System Integrator persona.
-
-
```release-note
Add Broker implementor as a System Integrator persona.
```
**Docs**

add broker developers as system integrator personas

---

pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go

Addresses #https://github.com/knative/pkg/issues/1520
Do not emit events for every reconcile. Add logging
- Do not emit normal events for every reconcile
- Add logging
-
```release-note
Do not emit k8s events for every successful reconcile of IMC
```
**Docs**

Drop the event emission on every reconcile

---

test/lib/creation.go

Works around #https://github.com/knative/pkg/issues/1509
- Add retries to work around webhook chaos failures.
-
-
```release-note
```
**Docs**

retry on webhook failures

---

test/lib/creation.go

Fixes #
During the retry loop, the resource that we were trying to create would get set to nil and while the retry loop works, the resource on subsequent retries is nil, hence failing the subsequent retries. Yeah, so don't do that.
```
creation.go:284: Failed to create v1beta1 trigger "e2e-brokerchannel-trigger3": Internal error occurred: failed calling webhook "webhook.eventing.knative.dev": Post https://eventing-webhook.knative-eventing-ludhkv7ixq.svc:443/defaulting?timeout=2s: EOF
creation.go:279: Creating v1beta1 trigger e2e-brokerchannel-trigger3
creation.go:284: Failed to create v1beta1 trigger "e2e-brokerchannel-trigger3": Trigger.eventing.knative.dev "" is invalid: metadata.name: Required value: name or generateName is required
creation.go:290: Failed to create v1beta1 trigger …
```

dont overwrite the resource we are trying to create during retry.

---

test/conformance/main_test.go
test/conformance/source_crd_metadata_test.go
test/e2e/main_test.go
test/lib/config.go
test/lib/logexporter.go

Exporting logs from `knative-eventing` namespace at the end of `e2e` and `conformance` test suites can help to debug failed test runs.
- Export logs from `knative-eventing` namespace at the end of `e2e` and `conformance` test suites.

Export logs from knative-eventing namespace

---

pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go

```release-note
For Subscription, the Kubernetes event "SubscriptionReconciled" is no longer produced for clean runs of the ReconcileKind method.
```

remove reconciled normal event from subscriptions

---

pkg/reconciler/parallel/parallel.go
pkg/reconciler/parallel/parallel_test.go

```release-note
For Parallel, the Kubernetes event "ParallelReconciled" is no longer produced for clean runs of the ReconcileKind method.
```

remove reconciled normal event from parallel

---

pkg/reconciler/mtbroker/broker.go
pkg/reconciler/mtbroker/broker_test.go

```release-note
For MTBroker, the Kubernetes event "BrokerReconciled" is no longer produced for clean runs of the FinalizeKind method.
```

remove reconciled normal event from mtbroker

---

pkg/reconciler/eventtype/eventtype.go
pkg/reconciler/eventtype/eventtype_test.go

```release-note
For EventType, the Kubernetes event "EventTypeReconciled" is no longer produced for clean runs of the ReconcileKind method.
```

remove reconciled normal event from eventtypes

---

pkg/reconciler/channel/channel.go
pkg/reconciler/channel/channel_test.go

```release-note
For Channel, the Kubernetes event "ChannelReconciled" is no longer produced for clean runs of the ReconcileKind method.
```

Remove reconciled normal event from channel

---

pkg/reconciler/pingsource/pingsource.go
pkg/reconciler/pingsource/pingsource_test.go
pkg/reconciler/sequence/sequence.go
pkg/reconciler/sequence/sequence_test.go
pkg/reconciler/sugar/namespace/namespace.go
pkg/reconciler/sugar/trigger/trigger.go

- Use returned events in sugar controllers to produce events.
```release-note
For PingSource, the Kubernetes event "PingSourceReconciled" is no longer produced for clean runs of the ReconcileKind method.
For Sequence, the Kubernetes event "SequenceReconciled" is no longer produced for clean runs of the ReconcileKind method.
```

Do not produce reconciled-normal events always. - PingSource and Sequence

---

test/conformance/helpers/sources/source_status_test_helper.go
test/conformance/main_test.go
test/conformance/source_status_test.go
test/lib/config.go
test/lib/resources/constants.go
test/lib/setupclientoptions/sources.go
test/lib/test_runner.go

- Add PingSource conformance initialization code
- Configure PingSource properly to be picked up by SourceStatus conformance tests
- Explicitly skip the test in ComponentTestRunner.RunTestsWithComponentOptions when in strict mode and tests are not run
This PR is based on #3605

Add PingSource conformance tests initialization

---

pkg/channel/fanout/fanout_message_handler.go
pkg/channel/fanout/fanout_message_handler_test.go
pkg/channel/multichannelfanout/config.go
pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
pkg/channel/swappable/swappable_message_handler_test.go
pkg/inmemorychannel/message_dispatcher_benchmark_test.go
pkg/inmemorychannel/message_dispatcher_test.go
pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go

Fixes #3702
- Decoupled fanout config from ducktypes, so now that code doesn't need to be aware of type conversions and so on
- Provided a function to easily convert a `duckv1.SubscriberSpec` to `fanout.Config`
- Pruned remaining config json conversion code after https://github.com/knative/eventing/pull/3713

Decoupled fanout config from ducktypes

---

test/conformance/helpers/broker_control_plane_test_helper.go

Fixes #3730 
- Use retry loop when updating triggers in case there are conflicts.
-
-
```release-note
```
**Docs**

Retry in case of update conflicts

---

test/lib/creation.go

I had neglected to change a few Fatalf calls to Errorf in the retry loops. Hence no retry, hence test failures due to webhook failing.
-
-
-
```release-note
```
**Docs**

replace fatalf with logf in retry loop

---

cmd/mtping/main.go
pkg/adapter/v2/main.go
pkg/adapter/v2/main_message.go

Fixes #3571 
- Enable HA for mtping
- Provide a way to disable HA using `--disable-ha` flag. 
-
```release-note
```
**Docs**

reenable HA for mtping

---

cmd/webhook/main.go
config/core/resources/pingsource.yaml
pkg/apis/sources/v1alpha2/ping_conversion.go
pkg/apis/sources/v1alpha2/ping_conversion_test.go

Part of #3606
- Add conversion webhook
- Add v1beta1 to CRD.
-
```release-note
```
**Docs**

PingSource conversion v1beta1, and crd.

---

test/conformance/main_test.go
test/lib/setupclientoptions/sources.go

We only currently have setupclientoption functions for latest
sources API versions to run the conformance tests against.
It should be visible in the test that we are initializing
a specific API version of the source
- Reflect created sources API versions in setupclientoptions

Reflect created sources API versions in setupclientoptions

---

test/lib/operation.go

Fixes #3750
- Put the test code that waits for resources in a retry loop to work around webhook failures.
-
-
```release-note
```
**Docs**

put the waiting of kresources in a retry loop for webhook failures

---

pkg/adapter/mtping/adapter.go
pkg/adapter/mtping/runner.go
pkg/reconciler/pingsource/pingsource.go

- Add --with-seconds flags to mtping. When set it enables parsing schedule with an optional seconds field
- Only use deepDerivative when comparing old vs new adapter deployments
- To enable: patch the pingsource-mt-adapter deployment with `args: ["--with-seconds"]`
-
```release-note
```
**Docs**

add support for seconds in pingsource - for running tests only!

---

test/conformance/helpers/channel_spec_test_helper.go

Recent flaky tests show errors like this:
```
Error updating <Channel> with subscribers in spec: Operation cannot
be fulfilled on <Channel> "channel-spec-subscribers-n7zb8": the
object has been modified;
please apply your changes to the latest version and try again.
```
So, retrying on conflict might mitigate the issue.
Addresses #3766
- Retry on conflict in TestChannelSpec

Retry on conflict in TestChannelSpec

---

test/lib/creation.go

Recently, we added a workaround for EOF errors: 
#3681 and some tests seem to be flaky because
we try to create a subscription multiple times when 
it already exists.
Some test runs show errors like this:
```
creation.go:175: Creating v1 subscription
creation.go:180: Failed to create subscription "<name>": conversion webhook for messaging.knative.dev/v1beta1, Kind=Subscription failed: Post https://eventing-webhook.knative-eventing-aw90d392a6.svc:443/resource-conversion?timeout=30s: EOF
creation.go:175: Creating v1 subscription <name> for channel &TypeMeta{Kind:InMemoryChannel,APIVersion:messaging.knative.dev/v1,}-e2e-singleevent-channel-structured
creation.go:180: Failed to create subscription "<name>": subscriptions.messaging.knative.dev "e2e-singleevent-subscription-structured" already …
```

Do not fail when subscription already exists

---

test/conformance/helpers/broker_data_plane_test_helper.go
test/conformance/helpers/channel_header_single_event_helper.go
test/conformance/helpers/tracing_test_helper.go
test/e2e/helpers/broker_channel_flow_helper.go
test/e2e/helpers/broker_event_transformation_test_helper.go
test/e2e/helpers/broker_redelivery_helper.go
test/e2e/helpers/broker_test_helper.go
test/e2e/helpers/channel_chain_test_helper.go
test/e2e/helpers/channel_defaulter_test_helper.go
test/e2e/helpers/channel_dls_test_helper.go
test/e2e/helpers/channel_event_tranformation_test_helper.go
test/e2e/helpers/channel_single_event_helper.go
test/e2e/helpers/parallel_test_helper.go
test/e2e/helpers/sequence_test_helper.go
test/e2e/helpers/trigger_no_broker_test_helper.go
test/e2e/source_api_server_v1alpha2_test.go
test/e2e/source_api_server_v1beta1_test.go
test/e2e/source_container_v1alpha2_test.go
test/e2e/source_container_v1beta1_test.go
test/e2e/source_ping_test.go
test/e2e/source_sinkbinding_v1alpha1_test.go
test/e2e/source_sinkbinding_v1alpha2_test.go
test/e2e/source_sinkbinding_v1beta1_test.go
test/e2e/trigger_dependency_annotation_test.go
test/lib/recordevents/event_info.go
test/lib/recordevents/event_info_store.go
test/lib/recordevents/event_info_store_test.go

- Some tests were not properly cleaning the event info store (and the port forward process behind the hood). With this change the cleanup is done during the test tear down https://github.com/knative/eventing/pull/3780/files#diff-719035a5ad84fc383e0dea6ef4c67e32R96

Now eventTracker.Cleanup() is invoked behind the hood

---

test/conformance/main_test.go
test/e2e-conformance-tests.sh
test/lib/test_runner.go

- ComponentsTestRunner now creates a subtests for the component in all cases, then later decides on skipping it if the component doesn't match (better visibility)

Skip the subtests in strict mode for ComponentsTestRunner

---

pkg/reconciler/parallel/controller.go
pkg/reconciler/parallel/controller_test.go
pkg/reconciler/parallel/parallel.go
pkg/reconciler/parallel/parallel_test.go
pkg/reconciler/parallel/resources/channel.go
pkg/reconciler/parallel/resources/subscription.go

Part of #3584
- Migrate parallel reconciler to use messaging.* v1 resources
-

Migrate parallel reconciler to use messaging.* v1 resources

---

config/brokers/mt-channel-broker/deployments/controller.yaml
config/core/deployments/controller.yaml
config/core/deployments/webhook.yaml

Related: knative/pkg#1269
```release-note
Control plane components now specify anti-affinity so that replicas will not be colocated.
```

Add anti-affinity to our control plane deployments

---

pkg/apis/duck/v1alpha1/channelable_combined_types.go
pkg/apis/duck/v1alpha1/channelable_combined_types_test.go
pkg/apis/duck/v1alpha1/subscribable_types.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
pkg/apis/duck/v1alpha1/subscribable_types_test.go
pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go

Fixes #3802 
- ChannelableCombined: Add SubscribableSpec, DeliverySpecs and SubscribableStatus for v1 similar to existing ones for v1beta1
- SubscribableTypes: Add Delivery and Subscribers  for v1 similar to existing ones for v1beta1
-
fyi @n3wscott

Fix ChannelableCombined and SubscribableTypes for v1 migration

---

config/channels/in-memory-channel/300-in-memory-channel.yaml
config/core/resources/apiserversource.yaml
config/core/resources/broker.yaml
config/core/resources/channel.yaml
config/core/resources/containersource.yaml
config/core/resources/parallel.yaml
config/core/resources/pingsource.yaml
config/core/resources/sequence.yaml
config/core/resources/sinkbindings.yaml
config/core/resources/subscription.yaml
config/core/resources/trigger.yaml
docs/spec/sources.md

- Put `READY` and `REASON` columns at the right most position

Regroup additional printer columns

---

config/core/roles/clusterrole-namespaced.yaml

- Adding `sources.knative.dev` back to the `edit` aggregation role. Looking here, it was removed: https://github.com/knative/eventing/commit/4d1c20b9c3a9c0d4987cba8ce8db4f6547bf631d#diff-bc901b9d7f4a101d28344eca9f094d84
- adding bindings to edit as well
```release-note
```
**Docs**

Add sources and bindings to edit view aggregation

---

pkg/apis/sources/v1beta1/ping_lifecycle.go
pkg/apis/sources/v1beta1/register.go
pkg/apis/sources/v1beta1/register_test.go
pkg/reconciler/testing/pingsource.go
test/e2e/source_ping_v1beta1_test.go
test/lib/creation.go

For https://github.com/knative/eventing/issues/3606
- add PingSource v1beta1 e2e tests
-
-
```release-note
```
**Docs**

pingsource v1beta1 e2e tests

---

test/lib/client.go
test/lib/recordevents/event_info_store.go
test/lib/test_runner.go

Fixes #
- Client now has a Cleanup method to hook the lifecycle of the event tracker to the client. This should avoid the tracker to continue working after the test is finished (and hopefully fix related flakyness)

Test Client now has a Cleanup method

---

config/core/resources/broker.yaml

Part of #3054
- Add content in CRDs to generate kubectl explain content for Broker ONLY
- Splitting off #3832 to fix issues iteratively

kubectl explain for Broker

---

cmd/mtping/main.go
go.mod
pkg/adapter/mtping/adapter.go
pkg/adapter/mtping/context.go
pkg/adapter/mtping/context_test.go
pkg/adapter/mtping/runner.go
pkg/reconciler/pingsource/pingsource.go
pkg/reconciler/pingsource/pingsource_test.go
pkg/reconciler/pingsource/resources/mt_receive_adapter.go
pkg/reconciler/pingsource/resources/mt_receive_adapter_test.go
vendor/modules.txt

- Make sure not to stop the mtping adapter to close to the minute during a graceful shutdown.
-
-
```release-note
- 🐛 Fix bug
PingSource does not lose events anymore when being shutdown close to the minute
```
**Docs**

delay when to shutdown the mtping adapter

---

cmd/v0.17/pingsource-cleanup/README.md
cmd/v0.17/pingsource-cleanup/injection.go
cmd/v0.17/pingsource-cleanup/main.go
config/post-install/v0.17.0/dummy.go
config/post-install/v0.17.0/pingsource-cleanup.yaml
hack/release.sh

Fixes #3588
- Add job to remove pingsource finalizers
-
-
```release-note
```
**Docs**
@houshengbo

add post 017 job to remove pingsource finalizer

---

config/core/resources/sinkbindings.yaml

Part of #3054
- Add content in CRDs to generate kubectl explain content for sinkbindings ONLY
- Splitting off #3835 to fix issues iteratively
-

kubectl explain for sinkbindings

---

config/core/resources/subscription.yaml

Part of #3054
- Add content in CRDs to generate kubectl explain content for Subscription ONLY
- Splitting off #3835 to fix issues iteratively
- I had to remove some generated `required` statements from yaml as tests were failing. My hypothesis is the status is not set fully at some point and that leads to the error. Without the `required` statements tests pass.

kubectl explain for Subscription

---

docs/spec/channel.md

Add v1 channelable to the spec.
- Add v1 channelable to the spec.
```release-note
Update the spec to include v1 of the channelable.
```
**Docs**

add channel v1 duck type to spec

---

hack/release.sh

This should fix #3873, but we'll leave that issue open until a release with `eventing.yaml` has been created.
- Remove the old release-0.16 pre- and post- install jobs.
```release-note
NONE
```

Remove the old release-0.16 pre- and post- install jobs.

---

test/e2e-common.sh

- Use `v0.16.1` as the 'latest release'.
- v0.17.0 is a bad release, see https://github.com/knative/eventing/issues/3873. It is blocking any new PRs and is blocking the creation of a new release because the bad release is being used in the upgrade test, causing it to fail.
Once release `v0.17.1` is created and is shown to work, revert this PR.
```release-note
NONE
```

Force the latest version to be v0.16.1.

---

pkg/utils/headers_test.go

Fixes #
- adding test
```release-note
```
**Docs**

Adding small test for util

---

test/conformance/README.md
test/conformance/broker_data_plane_test.go
test/conformance/helpers/broker_data_plane_test_helper.go
test/lib/resources/eventing.go

Also, fix being able to run conf tests against existing broker :facepalm:
Fixes #3667
----
#

Add docs on how to run conf tests against preexisting broker

---

pkg/apis/duck/v1alpha1/channelable_combined_types.go
pkg/apis/duck/v1alpha1/channelable_combined_types_test.go
pkg/apis/duck/v1alpha1/subscribable_types.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
pkg/apis/duck/v1alpha1/subscribable_types_test.go
pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
pkg/reconciler/channel/channel.go
pkg/reconciler/channel/channel_test.go
pkg/reconciler/channel/controller.go
pkg/reconciler/channel/controller_test.go
pkg/reconciler/channel/resources/channel.go
pkg/reconciler/testing/v1/channel.go
test/conformance/helpers/channel.go
test/conformance/helpers/channel_status_subscriber_test_helper.go

Part of #3584
- Migrate sequence reconciler to use messaging.* v1 resources
- New stab at https://github.com/knative/eventing/pull/3789
Implementing changes according to https://github.com/knative/eventing/pull/3789#discussion_r472280959

Migrate channel reconciler to use messaging.* v1 resources

---

pkg/mtbroker/filter/filter_handler.go

Addresses #3791
When send fails or response is nil, set the response code to 0.
- Seen while debugging 3791, does not fix the flakiness though.
-
-
```release-note
- 🐛 Fix bug
In cases where Filter sends a message and it fails or response is nil, it will panic because it uses it.
```
**Docs**

do not use resp if it fails, use 0 instead

---

test/conformance/helpers/broker_data_plane_test_helper.go

Just fixing a typo in the test pod name. No functional changes.
- s/tranformer-pod/transformer-pod/
-
-
```release-note
```
**Docs**

fix typo in the transformer-pod name

---

config/core/resources/channel.yaml

Part of #3054
- Add content in CRDs to generate kubectl explain content for Channel
- Similarly to #3869 and #3892 lastTransitionTime is not defined in the spec as tests are setting it to null, preserve-unknown-fields is used instead. See the last commit of either  #3869 and #3892 for more details.

kubectl explain for Channel

---

config/core/resources/sequence.yaml

Part of #3054
- Add content in CRDs to generate kubectl explain content for Sequence
- Note use of placeholders to avoid duplication of content via &referentProperties (fyi @aavarghese )

kubectl explain for sequence

---

config/pre-install/v0.18.0/clusterrole.yaml
config/pre-install/v0.18.0/containersource.yaml
config/pre-install/v0.18.0/dummy.go
config/pre-install/v0.18.0/serviceaccount.yaml
config/pre-install/v0.18.0/sinkbindings.yaml
config/pre-install/v0.18.0/storage-version-migration.yaml

Fixes #3674, #3615
- 
- Add a Preinstall job that migrates sinkbindings from v1alpha1 to v1beta1.
- Add a Preinstall job that migrates containersource from v1alpha1 to v1beta1.
- Similar to https://github.com/knative/eventing/pull/3262
-
Eventing v1alpha1 API is removed.
action required: You must run pre-install job prior to upgrading to get sinkbindings and containersource to v1beta1 API.

Add a job for migrating sinkbindings and containersource storage versions to v1beta1

---

cmd/mtping/main.go
config/core/roles/pingsource-mt-adapter-clusterrole.yaml
pkg/adapter/mtping/adapter.go
pkg/adapter/mtping/controller.go
pkg/adapter/mtping/controller_test.go
pkg/adapter/mtping/pingsource.go
pkg/adapter/mtping/pingsource_test.go
pkg/reconciler/pingsource/controller.go

- Partially reverting https://github.com/knative/eventing/pull/3451 causing a regression on the max number PingSources the adapter can handle.
- 
-
```release-note
```
**Docs**
This PR needs to be backported to 17.

revert change to get PingSource specs from ConfigMaps

---

test/conformance/helpers/broker_data_plane_test_helper.go

Refactor the tests to have the test resources setup first, and then
just use them in the following tests.  Hopefully this increases the
stability of the broker tests
Related: #3791

Refactor broker data plane consumer tests conf tests

---

pkg/reconciler/subscription/controller.go
pkg/reconciler/subscription/controller_test.go
pkg/reconciler/subscription/subscription.go
pkg/reconciler/subscription/subscription_test.go
pkg/reconciler/testing/v1/service.go
pkg/reconciler/testing/v1/subscription.go

Part of #3584
- Migrate Subscription reconciler to use messaging.* v1 resources
Removing tests that deal with v1alpha1 subscription (according to https://github.com/knative/eventing/pull/3789#discussion_r472280959 - see also https://github.com/knative/eventing/pull/3871)

Migrate Subscription reconciler to use messaging.* v1 resources

---

config/pre-install/v0.18.0/storage-version-migration.yaml
test/e2e-common.sh
test/e2e-upgrade-tests.sh

Fixes #
- Use preinstall 0.18 script in upgrade tests
- So, the migration job actually runs (from 0.17 to 0.18) for resources that have a storage version change
- Some storage version change PRs are already merged without testing
- Some are still open (like https://github.com/knative/eventing/pull/3936) and merging this PR will make sure the storage change PRs are tested properly

Use preinstall 0.18 in upgrade tests

---

pkg/apis/eventing/v1/trigger_types.go
pkg/apis/eventing/v1/trigger_validation.go
pkg/apis/eventing/v1/trigger_validation_test.go
pkg/apis/eventing/v1beta1/trigger_types.go
pkg/apis/eventing/v1beta1/trigger_validation.go
pkg/apis/eventing/v1beta1/trigger_validation_test.go
pkg/reconciler/sugar/filters_test.go
pkg/reconciler/sugar/labels.go
pkg/reconciler/sugar/trigger/trigger_test.go

This reverts commit 899d715f57cbe7aea6a13192a3ffa732577970a0.
Fixes #
- essentially reverting PR #3880 
```release-note
The `knative-eventing-injection` annotation is now deprecated in fav. of the fully qualified name `eventing.knative.dev/injection`
NOTE: this will be removed for 0.19 of knative eventing
```
**Docs**

Revert "Remove deprecated  and have only the fqn for injection (#3880)"

---

pkg/apis/flows/v1/parallel_lifecycle.go
pkg/apis/flows/v1/parallel_lifecycle_test.go

Backport #3945 to .16 release.
- Check the length of the branches and if they change, realloc the array of BranchStatuses. Otherwise, if branches are added, panic happens.
-
-
```release-note
- 🐛 Fix bug
If you create a Parallel, then later add branches to it, caused a panic.
```
**Docs**

backport 3945 to .16

---

config/core/resources/containersource.yaml
config/core/resources/sinkbindings.yaml

Fixes #3674, #3615
- Switch storage for containersource and sinkbinding to v1beta1

switch storage for containersource and sinkbinding to v1beta1

---

pkg/apis/flows/v1/parallel_lifecycle.go
pkg/apis/flows/v1/parallel_lifecycle_test.go

Fixes #3945
- Check the length of the branches and if they change, realloc the array of BranchStatuses. Otherwise, if branches are added, panic happens.
-
-
```release-note
- 🐛 Fix bug
If you create a Parallel, then later add branches to it, caused a panic.
```
**Docs**

fix issue 3945

---

pkg/apis/flows/v1/parallel_lifecycle.go
pkg/apis/flows/v1/parallel_lifecycle_test.go
test/conformance/helpers/broker_data_plane_test_helper.go

Backport #3945 to .17 release.
Also backport 3918, 3900. (helps with test flakes)
- Check the length of the branches and if they change, realloc the array of BranchStatuses. Otherwise, if branches are added, panic happens.
-
-
```release-note
- 🐛 Fix bug
If you create a Parallel, then later add branches to it, caused a panic.
```
**Docs**

backport issue 3945 to .17

---

test/conformance/helpers/broker_data_plane_test_helper.go

Realted: #3791
For broker data plane conformance tests, when observing some of the
errors in pod sender logs, the following message was seen:
"Got response from http://broker-ingress.knative-eventing-28b9ei2f23.svc.cluster.local/test-broker-v1-beta1-data-plane-consumer-wzjjv/br
failed to convert response into event: unknown Message encoding"
Add a `sender.WithEncoding(ce.EncodingStructured)` option to the event
sender in an attempt to make the conformance tests more robust.
---

Add explicit content encoding to event-senders in broker conf test

---

test/e2e/broker_redelivery_test.go

Fixes #
- Update BrokerRedelivery test
```release-note
```
**Docs**

Updating broker to be v1

---

test/e2e-common.sh

This reverts commit b174462d0466c88e42aa1f6ade1fe6bf1f981637.
- Revert #3887. There are other changes that will trigger the point release anyway.
```release-note
NONE
```

Revert "Force the latest version to be v0.16.1. (#3887)"

---

pkg/test/observer/doc.go
pkg/test/observer/eventlog.go
pkg/test/observer/http-vent/doc.go
pkg/test/observer/http-vent/http.go
pkg/test/observer/observation.go
pkg/test/observer/observer.go
pkg/test/observer/recorder-collector/collector.go
pkg/test/observer/recorder-collector/doc.go
pkg/test/observer/recorder-vent/constructor.go
pkg/test/observer/recorder-vent/doc.go
pkg/test/observer/recorder-vent/recorder.go
pkg/test/observer/writer-vent/doc.go
pkg/test/observer/writer-vent/writer.go

Related to #3570
- Adding an event observer to start to replace the in-memory event store for integration testing.
```release-note
NONE
```
**Docs**
This is intended for testing only.

introducing the test observer

---

test/conformance/broker_control_plane_test.go
test/conformance/broker_data_plane_test.go
test/conformance/helpers/broker_data_plane_test_helper.go
test/conformance/main_test.go
test/e2e-conformance-tests.sh
test/e2e_flags.go
test/flags/brokers.go
test/flags/eventing_environment.go
test/lib/config.go
test/lib/test_runner.go

Add a broker test runner, move individual tests into a
subtest (hopefully this will reduce testgrid marking these tests as
flaky)

Refactor broker conformance tests to use brokerTestRunner

---

pkg/reconciler/mtbroker/trigger/controller.go
pkg/reconciler/mtbroker/trigger/trigger.go

Addresses https://github.com/knative/eventing-contrib/issues/1424 and subtests.
- Enqueue Triggers on Broker changes without Tracker

Enqueue Triggers on Broker changes without Tracker
