knative/eventing

docs/source/receive-adapter.md
- First attempt to explain how config works  in receive adapters. Not meant to be too extensive yet
-
-
```release-note
```
**Docs**
=> First attempt to explain how config works in receive adapters

pkg/reconciler/mtbroker/trigger/trigger_test.go, pkg/reconciler/parallel/parallel_test.go, pkg/reconciler/sequence/sequence_test.go, pkg/reconciler/source/duck/duck_test.go
This is necessary for the future table test improvements, which are going to verify more stuff.
/assign @vaikas @n3wscott 
=> Harden delete tests to verify more things

config/core/resources/pingsource.yaml, config/pre-install/v0.18.0/clusterrole.yaml, config/pre-install/v0.18.0/pingsource.yaml, config/pre-install/v0.18.0/storage-version-migration.yaml, pkg/adapter/mtping/config.go, pkg/adapter/mtping/config_test.go, pkg/adapter/mtping/controller.go, pkg/adapter/mtping/controller_test.go, pkg/adapter/mtping/pingsource.go, pkg/adapter/mtping/pingsource_test.go, pkg/adapter/mtping/runner.go, pkg/reconciler/mtbroker/broker_test.go, pkg/reconciler/mtbroker/trigger/trigger_test.go, pkg/reconciler/pingsource/controller.go, pkg/reconciler/pingsource/controller_test.go, pkg/reconciler/pingsource/pingsource.go, pkg/reconciler/pingsource/pingsource_test.go, pkg/reconciler/pingsource/resources/receive_adapter_test.go, pkg/reconciler/resources/service_account_test.go, pkg/reconciler/testing/listers.go, pkg/reconciler/testing/pingsource.go, pkg/reconciler/testing/v1beta1/listers.go, test/conformance/main_test.go, test/e2e-conformance-tests.sh, test/e2e/trigger_dependency_annotation_test.go, test/lib/setupclientoptions/sources.go
https://github.com/knative/eventing/issues/3886
=> Make PingSource v1beta1 the stored version and add a migration tool

OWNERS
Criteria from https://github.com/knative/community/blob/master/ROLES.md#approver
Reviewer of the codebase for at least 3 months:
First reviews:
[Eventing] https://github.com/knative/eventing/pull/1601 July 30, 2019
Primary reviewer for at least 10 substantial PRs to the codebase [11].
#3924
#3954
#2759
#3447
#3964
#3313
#3226
#3224
#3070
#3050
#3016
Reviewed at least 30 PRs to the codebase [30]
eventing:
#3964
#3958
#3955
#3954
#3947
#3924
#3902
#3897
#3762
#3742
#3447
#3395
#3361
#3251
#3243
#3226
#3224
#3223
#3221
#3202
#3184
#3180
#3070
#3050
#3016
#3070
#2759
#2700
#2258
#1601
Nominated by an area lead with no objections from other leads:
@matzew
Proposals Authored & Submitted:
[Eventing contrib vs Sandbox](https://docs.google.com/document/d/1UcMNGKTjKdxLY_IVI7Xv5ZSOXAiO9DUrcuw2gkt74qY …
=> Add lberk to approvers

.github/workflows/knative-downstream.yaml, pkg/leaderelection/context_test.go
Integrate the `knative-sandbox/downstream-test-go` action that takes two repos that are checked out and upgrades the downstream with an upstream module, and then runs the standard knative repo update-codegen and runs the unit tests.
This PR makes it an FYI that any future PR will test on the following:
- Eventing Contrib
- Sample Source
=> adding downstream tests for sample source and eventing-contrib

pkg/reconciler/mtbroker/broker.go, pkg/reconciler/mtbroker/broker_test.go, pkg/reconciler/mtbroker/controller.go
Remove now unused triggerlister that was being wired into the reconciler but not used.
-
-
-
```release-note
```
**Docs**
=> remove unused triggerlister

config/500-pingsource-mt-adapter.yaml, config/core/deployments/controller.yaml, config/core/deployments/pingsource-mt-adapter.yaml, pkg/reconciler/pingsource/controller.go, pkg/reconciler/pingsource/controller_test.go, pkg/reconciler/pingsource/pingsource.go, pkg/reconciler/pingsource/pingsource_test.go, pkg/reconciler/pingsource/resources/receive_adapter.go, pkg/reconciler/pingsource/resources/receive_adapter_test.go
Fixes #3035
- the mtping adapter is now created at installation time, replicas = 0
- the pingSource controller only updates environment variables
- the pingSource controller sets replicas to 1 (if set to 0) when first PingSource is created
```release-note
```
**Docs**
=> Eager pingsource adapter creation

cmd/mtbroker/filter/main.go, cmd/mtbroker/ingress/main.go
This drops code duplication in that we're reusing the flags as defined in knative/pkg.
=> Refactor main functions to reuse helpers from package.

pkg/reconciler/mtbroker/trigger/trigger.go
Fix the incorrect message, would print %s/%s instead of t.ns/t.name
- fix the log message
-
-
```release-note
- 🐛 Fix bug
When not reconciling triggers not owned by my brokerclass, would print incorrect msg, logic was correct however, just wrong log message.
```
**Docs**
=> fix log message

pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go
The subscription reconciler didn't propagate the entire `deliverySpec`
to the channel, only the `deadLetterSink` was propagated.
- Propagate the entire delivery spec to the Channel
```release-note
- 🐛 Fix bug
The subscription reconciler correctly propagates delivery configurations to the channel (`retry`, `backoffDelay`, `backoffPolicy`).
```
=> Propagate the entire delivery spec to the Channel

pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go
The subscription reconciler didn't propagate the entire `deliverySpec`
to the channel, only the `deadLetterSink` was propagated.
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
- Propagate the entire delivery spec to the Channel (#4042)
```release-note
- 🐛 Fix bug
The subscription reconciler correctly propagates delivery configurations to the channel (`retry`, `backoffDelay`, `backoffPolicy`).
```
=> [release-0.17] Propagate the entire delivery spec to the Channel (#4042)

test/conformance/helpers/broker_control_plane_test_helper.go, test/conformance/helpers/broker_data_plane_test_helper.go
Fixes #3952
- Add retries for webhook fails at conformance tests
- Only for conformance test helpers are checked
```release-note
```
**Docs**
=> Add retries for webhook fails at conformance tests

test/e2e/channel_dls_test.go
Fixes #
- fix V1 test invoke ...
-
-
```release-note
```
**Docs**
=> The V1 test should actually use V1 APIs

docs/source/receive-adapter.md
Unblock https://github.com/knative/eventing/pull/3898 per comment https://github.com/knative/eventing/pull/3898#issuecomment-694205465.
- Change link to GitHubSource
=> Change link to GitHubSource

docs/source/receive-adapter.md
Produced via:
`prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github | grep -v docs/cmd/)`
/assign grantr matzew n3wscott
/cc grantr matzew n3wscott
=> [master] Format markdown

cmd/mtchannel_broker/main.go
Burst and QPS flags were added for debugging chaos testing
failures, see https://github.com/knative/eventing/issues/3591.
Also, those configurations should probably be in the `sharedmain`
package, so that we standardize the way of configuring them
for all controllers.
- Switch back to `sharedmain.Main` for MT Broker controller
=> Switch back to sharedmain.Main for MT Broker controller

config/brokers/mt-channel-broker/deployments/controller.yaml, config/channels/in-memory-channel/deployments/controller.yaml, config/channels/in-memory-channel/deployments/dispatcher.yaml, config/core/deployments/controller.yaml, config/core/deployments/pingsource-mt-adapter.yaml, config/core/deployments/webhook.yaml, config/sugar/500-controller.yaml
- https://github.com/knative/pkg/pull/1714
- Project pod name as env var in our deployments
=> Project pod name as env var in our deployments

pkg/mtbroker/filter/filter_handler.go
Fixes #4071
- Proper logging to explain when the user replies with a malformed response to the filter handler
=> Proper logging for filter handler malformed response

docs/source/receive-adapter.md
-
-
-
```release-note
```
**Docs**
=> remove reference to persisted store

pkg/adapter/mtping/controller.go, pkg/adapter/mtping/pingsource.go
Fixes #4028
- The adapter controller does not attempt to update the CR status
- Revert to previous behavior when the source is not ready. When a pod is deleted, a source becomes temporarily not ready, leading to lost events.
-
```release-note
```
**Docs**
=> make pingsource adapter controller read-only

.golangci.yaml, cmd/v0.16/broker-cleanup/main.go, cmd/v0.17/pingsource-cleanup/main.go, pkg/adapter/mtping/runner.go, pkg/adapter/v2/cloudevents.go, pkg/apis/duck/v1/fuzzer.go, pkg/apis/duck/v1alpha1/subscribable_types_conversion.go, pkg/apis/duck/v1beta1/subscribable_types_conversion.go, pkg/apis/sources/v1alpha2/container_validation.go, pkg/apis/sources/v1beta1/container_validation.go, pkg/mtbroker/filter/filter_handler.go, pkg/reconciler/eventtype/eventtype.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel.go, pkg/reconciler/mtbroker/broker.go, pkg/reconciler/mtbroker/trigger/trigger.go, pkg/reconciler/source/crd/crd.go, pkg/reconciler/source/duck/duck.go, pkg/reconciler/source/duck/resources/eventtype.go, pkg/reconciler/subscription/subscription.go, pkg/tracing/setup.go
We've added these to the serving codebase as means to point out potential simplifications (see for example the ability to drop some error returns in the diff) and to point out potential security concerns to make us think and at least document why we've chosen to ignore them.
=> Apply gosec and unparam to the codebase

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
- Fix metrics port mismatch between svc and deployment in broker manifests
It isn't clear from the manifests whether 9090 or 9092 is preferred, but the correct port is **9092**:
https://github.com/knative/eventing/blob/af999217845dc50de712fb88afdd898f5ebd081e/cmd/mtbroker/filter/main.go#L48-L51
See also #3181
=> Fix metrics port mismatch between svc and deployment in broker manifests

pkg/kncloudevents/message_sender.go, pkg/kncloudevents/message_sender_test.go
Fixes #4113 
Rework the exponential backoff calculation to match the advertised algorithm.
```release-note
The default exponential backoff duration now matches the advertised algorithm in the DeliverySpec.BackoffDelay comments.  User action required to evaluate if DeliverySpec.BackoffDelay settings in `Subscription.spec.delivery` remain appropriate.
```
=> fix exponential backoff bug in RetryConfigFromDeliverySpec()

pkg/kncloudevents/message_sender.go, pkg/kncloudevents/message_sender_test.go
Fixes #4113 
Rework the exponential backoff calculation to match the advertised algorithm. (backporting changes in #4115 PR)
```release-note
The default exponential backoff duration now matches the advertised algorithm in the DeliverySpec.BackoffDelay comments.  User action required to evaluate if DeliverySpec.BackoffDelay settings in `Subscription.spec.delivery` remain appropriate.
```
=> backporting fix for default exponential backoff calculation

pkg/kncloudevents/message_sender.go, pkg/kncloudevents/message_sender_test.go, test/e2e/helpers/broker_redelivery_helper.go
Part of #4111 
This PR sets the` CheckRetry` function and add some unit tests.
- Set check retry function
```release-note
- 🐛 Fix bug
Channels and Brokers correctly retry on non 2xx HTTP status codes
```
=> Set check retry function

pkg/kncloudevents/message_sender.go, pkg/kncloudevents/message_sender_test.go, test/e2e/helpers/broker_redelivery_helper.go
Part of #4111
This PR sets the` CheckRetry` function and add some unit tests.
- Set check retry function
- backport: https://github.com/knative/eventing/pull/4112
```release-note
- 🐛 Fix bug
Channels and Brokers correctly retry on non 2xx HTTP status codes
```
=> [release-0.17] Set check retry function

docs/decisions/broker-trigger.md
Reflect the moved github source, and remove document that seems to have disappeared from drive.
=> Fix broken markdown links

config/core/deployments/webhook.yaml, docs/decisions/broker-trigger.md, docs/planning/bug_triage.md, test/e2e-common.sh
Produced via:
```shell
export FILES=( $(find . -type f -not -path './vendor/*' -not -path './third_party/*' -not -path './.git/*') )
misspell -w "${FILES[@]}"
```
/cc n3wscott grantr matzew
/assign n3wscott grantr matzew
=> [Automated] Fix misspellings

config/core/deployments/webhook.yaml
Fixes #4165
- Add 20 second initial delay to the liveness probe in order to give the webhook sufficient time to acquire leadership and
reconcile eventing-webhook-certs when the leader lease duration is set to 15 seconds.
```release-note
- 🐛 Fix a bug which could cause eventing-webhook to crashloop on initial creation.
```
=> Set initialDelaySeconds to 20 on webhook livenessProbe

pkg/adapter/v2/util/crstatusevent/eventsstatus_test.go, pkg/duck/listable_test.go
The RT will panic on itself anyway.
Also other nits and fixes in the neighbouring lines
- formatting
- got before want
- drop test name (t.Run already specifies quite precisely what failes)
- etc
/assign @vaikas @n3wscott
=> Just alias the interface and drop unimplemented methods.

pkg/apis/eventing/v1/trigger_types.go, pkg/apis/eventing/v1/trigger_validation.go, pkg/apis/eventing/v1/trigger_validation_test.go, pkg/apis/eventing/v1beta1/trigger_types.go, pkg/apis/eventing/v1beta1/trigger_validation.go, pkg/apis/eventing/v1beta1/trigger_validation_test.go, pkg/reconciler/sugar/filters_test.go, pkg/reconciler/sugar/labels.go, pkg/reconciler/sugar/trigger/trigger_test.go
Fixes #3874
- remove deprecated code
```release-note
The deprecated `knative-eventing-injection` annotation is now removed. Make sure to use the `eventing.knative.dev/injection` annotation instead
```
**Docs**
=> Revert the "Revert "Remove deprecated annotation"" PR 

pkg/reconciler/source/crd/crd_test.go, pkg/reconciler/testing/customresourcedefinition.go, pkg/reconciler/testing/factory.go
Signed-off-by: runzexia <root@junwuhui.cn>
ref https://github.com/knative/eventing/issues/3868
=> enable source crd test

pkg/apis/duck/v1/delivery_types.go, pkg/apis/duck/v1/delivery_types_test.go, pkg/apis/duck/v1beta1/delivery_types.go, pkg/apis/duck/v1beta1/delivery_types_test.go
A user can specify a negative number of retries without getting any
validation error. This PR adds a check to validate that
`deliverySpec.retry` is a non negative integer.
- Reject negative Retry config
```release-note
DeliverySpec validation rejects a negative retry config.
```
=> Reject negative Retry config

pkg/apis/sources/constants.go, pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/mtbroker/trigger/trigger.go, pkg/reconciler/testing/v1/apiserversouce.go, test/e2e/source_api_server_v1_test.go, test/e2e/source_api_server_v1alpha2_test.go, test/e2e/source_api_server_v1beta1_test.go
Fixes #4180 
- 🐛ApiServerSource set Status.Ce Attributes based on the mode
=> ApiServerSource set Status.Ce Attributes based on the mode

test/lib/recordevents/event_info_store.go
This simplifies a bit the diagnostic of completed and failed assertions
- Added a log line to identify succeeded assertions
```
event_info_store.go:327: Assert passed: SingleEventForChannelTestHelper.func1 at channel_single_event_helper.go:123
```
=> Added log on completed assertions in EventInfoStore

test/performance/infra/sender/http_load_generator.go, test/test_images/performance/main.go
Go lang is pretty strict about naming and HTTP (unless http) is a prescribed spelling.
There are a lot of those in Eventing, but I am not sure if they used outside the eventing repo itself.
In fact, after finishing, I noticed that LG can be local so it became http.
/assign @grantr @n3wscott
=> Http -> HTTP conversion

test/test_images/performance/mako.config
On `eventing-kafka`, some lint, reported:
```
reviewdog: This is Pull-Request from forked repository.
reviewdog: found at least one result in diff
GitHub token doesn't have write permission of Check API, so reviewdog will
report results via logging command [1].
[1]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
reviewdog: Reporting results for "woke"
Error: [woke] reported by reviewdog 🐶
Error:  `dummy` may be insensitive, use `placeholder`, `sample` instead
Raw Output:
Error: knative.dev/eventing/test/test_images/performance/mako.config:5:25: [error] `dummy` may be insensitive, use `placeholder`, `sample` instead
Error: Process completed with …
```
=> Fixing some wording

config/core/deployments/pingsource-mt-adapter.yaml, pkg/adapter/v2/config.go, pkg/adapter/v2/config_test.go
=> fix crash when pingsource adapter is scaled up without any sources

test/e2e/trigger_dependency_annotation_test.go
Experimenting with Eventing's e2e and a non-standard cluster suffix, I noticed that this test failed.
Once my change to support KinD for Eventing e2e lands, we can make that pseudo-randomize this to prevent bugs like this in the future.
- 🐛 Fix test bug
/cc @vaikas 
/assign @vaikas 
This was introduced in the initial MT broker change, I believe.  Perhaps we should replace this with proper Addressable resolution via the source, but this seemed like the smallest change to unblock the scenario I'm chasing.  LMK which you prefer.
=> Drop the hardcoded cluster.local

pkg/reconciler/inmemorychannel/dispatcher/controller.go
Addresses #3686 
- Make the InMemoryChannel dispatcher reconciler read only.
- Our Dispatcher looks at the IMC spec to construct the dispatching logic, but there's no reason it should ever update status.
-
```release-note
- 🐛 Fix bug
Dispatcher was incorrectly behaving like a normal reconciler instead of skipping status updates. I wonder if this was causing grief battling the normal reconciler.
```
**Docs**
=> dispatcher should be readonly

test/e2e/trigger_dependency_annotation_test.go
- Follow up to discussion in #4277 
```release-note
Point to Broker ref instead of using a hard coded path. Also makes things little easier to reuse against other brokers.
```
**Docs**
=> do not hardcode the URI, use ref instead

.github/workflows/kind-e2e.yaml
Run Eventing e2e on Github Actions with KinD to get coverage of supported version range: 1.17 - 1.19
TODO: It might be worth parallelizing on `-channel` and `-source`, if those make sense as dimensions to test in parallel to speed things up.
```release-note
Eventing now tests the supported Kubernetes version range pre-submit.
```
**Docs**
N/A
=> Test eventing on KinD 1.17-1.19

pkg/apis/eventing/v1/trigger_lifecycle.go, pkg/reconciler/mtbroker/trigger/controller.go, pkg/reconciler/mtbroker/trigger/controller_test.go, pkg/reconciler/mtbroker/trigger/trigger.go, pkg/reconciler/mtbroker/trigger/trigger_test.go
Fixes #4294 
- Use source informer instead of conditions. Mismatch in informer / lister being used in the trigger reconciler..
-
-
```release-note
- 🐛 Fix bug
Dependency readiness could sometimes be missed because mismatched informer/lister was being used in the trigger reconciler.
```
**Docs**
=> use Source informer instead of conditions

pkg/reconciler/inmemorychannel/dispatcher/controller.go
Addresses #3686 
- Make the InMemoryChannel dispatcher reconciler read only.
- Our Dispatcher looks at the IMC spec to construct the dispatching logic, but there's no reason it should ever update status.
-
```release-note
- 🐛 Fix bug
Dispatcher was incorrectly behaving like a normal reconciler instead of skipping status updates. I wonder if this was causing grief battling the normal reconciler.
```
**Docs**
=> [0.18] backport 4280

pkg/reconciler/inmemorychannel/dispatcher/controller.go
Addresses #3686 
- Make the InMemoryChannel dispatcher reconciler read only.
- Our Dispatcher looks at the IMC spec to construct the dispatching logic, but there's no reason it should ever update status.
-
```release-note
- 🐛 Fix bug
Dispatcher was incorrectly behaving like a normal reconciler instead of skipping status updates. I wonder if this was causing grief battling the normal reconciler.
```
**Docs**
=> [0.17] backport 4280

pkg/reconciler/inmemorychannel/dispatcher/controller.go
Addresses #3686 
- Make the InMemoryChannel dispatcher reconciler read only.
- Our Dispatcher looks at the IMC spec to construct the dispatching logic, but there's no reason it should ever update status.
-
```release-note
- 🐛 Fix bug
Dispatcher was incorrectly behaving like a normal reconciler instead of skipping status updates. I wonder if this was causing grief battling the normal reconciler.
```
**Docs**
=> [0.16] backport 4280

pkg/apis/eventing/v1/trigger_lifecycle.go, pkg/reconciler/mtbroker/trigger/controller.go, pkg/reconciler/mtbroker/trigger/controller_test.go, pkg/reconciler/mtbroker/trigger/trigger.go, pkg/reconciler/mtbroker/trigger/trigger_test.go
* use Source informer instead of conditions
* remove now unused broker variable
Fixes #
-
-
-
```release-note
- 🐛 Fix bug
Dependency readiness could sometimes be missed because mismatched informer/lister was being used in the trigger reconciler.
```
**Docs**
=> [0.18] use Source informer instead of conditions (#4296)

cmd/webhook/main.go, config/core/resources/containersource.yaml, pkg/apis/sources/v1/container_conversion.go, pkg/apis/sources/v1/container_conversion_test.go, pkg/apis/sources/v1alpha2/container_conversion.go, pkg/apis/sources/v1alpha2/container_conversion_test.go, pkg/apis/sources/v1beta1/container_conversion.go, pkg/apis/sources/v1beta1/container_conversion_test.go
Part of https://github.com/knative/eventing/issues/4175 , follow-up of https://github.com/knative/eventing/pull/4257
- 🧽   Changed v1beta1, v1alpha2 container_conversion to allow conversion to/from v1
- 🎁   Add v1 to ContainterSource CRD
- 🎁   Configure conversion webhook for ContainerSource
```release-note
```
**Docs**
=> Add conversion webhook, CRD for ContainerSource v1

go.mod, test/e2e/helpers/channel_event_tranformation_test_helper.go, test/lib/recordevents/event_info_store.go, test/lib/recordevents/observer/observer.go, test/lib/recordevents/observer/reply.go, test/lib/recordevents/recorder_vent/constructor.go, test/lib/recordevents/resources.go, test/test_images/recordevents/main.go, vendor/modules.txt
This simplifies the debugging of the tests, since recordevents sends the events to k8s logs
In the followup PRs I'll remove transformevents and sequence-stepper because they're not longer useful with this PR
- Now recordevents has a configurable reply function to behave like transformevents
=> Reuse recordevents as transformevents

.github/workflows/kind-e2e.yaml
Set ARTIFACTS and add several post-job steps to dump assorted logs on failures.
=> Add post-build diagnostics.

test/e2e/helpers/sequence_test_helper.go, test/lib/recordevents/observer/observer.go, test/lib/recordevents/observer/reply.go, test/lib/recordevents/resources.go
This enables recordevents to act as sequencestepper. For more info on why: https://github.com/knative/eventing/pull/4291
- Now recordevents can act as sequencestepper
=> Using recordevents as sequencestepper

pkg/reconciler/mtbroker/broker.go, pkg/reconciler/mtbroker/broker_test.go, pkg/reconciler/mtbroker/controller.go, pkg/reconciler/mtbroker/controller_test.go
- When we split the broker reconciler into broker / trigger, some cruft was left over. My bad, removing...
-
-
```release-note
Just clean up some unused fields from the mtbroker reconciler struct.
```
**Docs**
=> remove unused cruft from reconciler split

pkg/reconciler/apiserversource/controller_test.go, pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go, pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go, pkg/reconciler/pingsource/controller_test.go, test/lib/client.go
=> Use well known config map names, rather than bespoke constants

pkg/channel/message_receiver_test.go, pkg/inmemorychannel/message_dispatcher_test.go
Use the zipkin namespace in the tests just for cosmetics.
=> change the test namespace to zipkin

test/e2e/helpers/parallel_test_helper.go, test/lib/resources/kube.go
Followup of https://github.com/knative/eventing/pull/4313
- Removed sequencestepper image usage in parallel tests
- Removed sequencestepper helper
=> Removed sequence stepper usages

config/core/resources/pingsource.yaml
Fixes #
Add ```EventsSchedule``` Information for Knative Eventing PingSource.
As of knative/eventing v0.17.0, Pingsource configured in particular namespace does not show schedule information for events.
Additional Print Columns added for including ```EventsSchedule``` information.
=> Add schedule information in retrieval output for Knative Eventing PingSource

config/channels/in-memory-channel/configmaps/dummy.go, config/channels/in-memory-channel/deployments/dummy.go, config/channels/in-memory-channel/dummy.go, config/channels/in-memory-channel/resources/dummy.go, config/channels/in-memory-channel/roles/dummy.go
This was missed in the restructure.
=> Add dummy.go files for restructured IMC.

test/lib/test_runner.go
This makes more readable the e2e test logs. This code was took from the original `Event.String()` generated code and made more readable with newlines. This also removes that noisy numbers when we use the `%v` format
=> Better k8s events log in e2e/conformance tests

go.sum, pkg/apis/sources/v1/sinkbinding_context.go, pkg/apis/sources/v1/sinkbinding_context_test.go, pkg/apis/sources/v1/sinkbinding_lifecycle.go, pkg/apis/sources/v1/sinkbinding_lifecycle_test.go, pkg/apis/sources/v1/sinkbinding_types.go, pkg/apis/sources/v1beta1/sinkbinding_context.go, pkg/apis/sources/v1beta1/sinkbinding_context_test.go, pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go, pkg/apis/sources/v1beta1/sinkbinding_lifecycle_test.go, pkg/apis/sources/v1beta1/sinkbinding_types.go, pkg/reconciler/sinkbinding/controller.go
By moving this call to the sinkbinding lifecycle, we avoid an error condition where WithContext cannot fetch the sinkURI (for whatever reason).  Moving that instead to the Do method where we can properly catch these kinds of errors
=> Move sinkbinding WithContext resolver call to Do() function

go.mod, test/conformance/helpers/broker_data_plane_test_helper.go, test/conformance/helpers/broker_tracing_test_helper.go, test/conformance/helpers/channel_tracing_test_helper.go, test/e2e/helpers/broker_channel_flow_helper.go, test/e2e/helpers/broker_event_transformation_test_helper.go, test/e2e/helpers/channel_event_tranformation_test_helper.go, test/e2e/helpers/parallel_test_helper.go, test/e2e/helpers/sequence_test_helper.go, test/lib/recordevents/event_info_store.go, test/lib/recordevents/observer/observer.go, test/lib/recordevents/observer/reply.go, test/lib/recordevents/recorder_vent/constructor.go, test/lib/recordevents/resources.go, test/lib/resources/kube.go, test/test_images/recordevents/main.go, vendor/modules.txt
Like https://github.com/knative/eventing/pull/4355 but for 0.18 branch
=> [0.18] Port recordevents updates

test/lib/recordevents/recorder_vent/constructor.go, test/lib/recordevents/resources.go
`EventBroadcaster` imposes the usage of an "anti spam" event correlator. This potentially introduces issues in our tests where 2 similar events are sent to the event broadcaster but one of them is not published. 
This change removes the usage of the code path with the event correlator and manually publishes the k8s events.
For more info https://github.com/kubernetes/client-go/issues/885
=> Publish manually events to avoid event correlator

pkg/apis/sources/v1/sinkbinding_lifecycle.go
Follow up on #4161 
This is really nit though, I hope the panic wont happen again.
- Return when URIResolver is not set to avoid nil pointer reference.
```release-note
NONE
```
**Docs**
/cc lberk n3scott
=> Return when URIResolver is not set to avoid nil pointer reference.

test/lib/recordevents/event_info.go, test/lib/recordevents/observer/observer.go, test/lib/recordevents/resources.go, test/lib/test_runner.go
- k8s events printed at the end of the test now are reordered before being printed
- Set the observer name in recordevents
- Include the host header in recordevents
- Proper logging of event info
=> Some nits in our test-infra I've found during a burning debugging session

pkg/adapter/v2/cloudevents.go
If result is nil due to Unwrap() or when passed to reportError, the code
would panic on `err.Error()`.
Fixes: #4378
Signed-off-by: Michael Gasch <mgasch@vmware.com>
-
-
-
```release-note
```
**Docs**
=> Fix nil-pointer panic on reportError

test/lib/client.go, test/lib/creation.go, test/test_images/recordevents/main.go, test/test_images/utils.go
- The config-logging is propagated to recordevents (and potentially, to any pod brought up by tests)
=> Propagate config-logging in test images

test/config/config-logging.yaml
This simplifies reading the logs in the CI artifacts
- config-logging for tests uses console encoding
=> config-logging uses console encoding in tests

test/lib/dropevents/receiver.go, test/lib/recordevents/observer/observer.go, test/test_images/recordevents/main.go
Signed-off-by: Ville Aikas <vaikas@vmware.com>
When dropping events for test purposes, we did so silently. Emit an event for those that will not be counted towards tests because we change the type of the event to dropped-<type>.
-
-
-
```release-note
```
**Docs**
=> emit a k8s event when dropping events

.github/workflows/kind-e2e.yaml, test/config/config-tracing.yaml
1. Drop the `cluster.local` in test/config/config-tracing.yaml and rely on ndots instead.
2. Drop the `sed` in the actions that mitigated the above (no longer needed)
3. Drop `--platform=all` during actions, this is now 4 architectures, which can get really slow.
```release-note
None
```
=> A few adjustments for actions.

test/lib/dropevents/receiver.go, test/lib/recordevents/event_info.go, test/lib/recordevents/logger_vent/logger.go, test/lib/recordevents/observer/observer.go, test/lib/recordevents/recorder_vent/constructor.go, test/lib/recordevents/recorder_vent/recorder.go, test/lib/test_runner.go, test/test_images/recordevents/main.go
Ported:
- https://github.com/knative/eventing/pull/4393
- https://github.com/knative/eventing/pull/4389
- https://github.com/knative/eventing/pull/4385
=> [0.17] Ported recent test infra improvements

pkg/apis/sources/v1beta1/sinkbinding_context.go, pkg/apis/sources/v1beta1/sinkbinding_context_test.go, pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go, pkg/apis/sources/v1beta1/sinkbinding_lifecycle_test.go, pkg/apis/sources/v1beta1/sinkbinding_types.go, pkg/reconciler/sinkbinding/controller.go
related: #4161
related: #4374
related: #4377
- backport changes of `sinkURI` -> `URIresolver` and related sinkbinding status updates
-
-
```release-note
By moving the SinkURI resolution tol to the sinkbinding lifecycle, we avoid an error condition where WithContext cannot fetch the sinkURI (for whatever reason, including if it just hasn't been created yet). Moving that instead to the Do method where we can properly catch these kinds of errors
```
**Docs**
=> backport sinkbinding resolver fix

test/lib/client.go, test/test_images/utils.go
Something is wrong with my grepping it seems :/
For posterity :)
```
>rg "JsonTo" *
vendor/knative.dev/pkg/logging/config.go:241:// JsonToLoggingConfig converts a JSON string of a Config.
vendor/knative.dev/pkg/logging/config.go:244:func JsonToLoggingConfig(jsonCfg string) (*Config, error) { //nolint No rename due to backwards incompatibility.
vendor/knative.dev/pkg/tracing/config/tracing.go:137:// JsonToTracingConfig converts a json string of a Config.
vendor/knative.dev/pkg/tracing/config/tracing.go:139:func JsonToTracingConfig(jsonCfg string) (*Config, error) { //nolint // for backcompat.
```
All in vendor :)
=> Remove last (again) Json items.

pkg/reconciler/source/config_watcher.go
No need to implement empty methods that are never called.
/assign @n3wscott @vaikas
=> Simplify the fake by embedding the interface

.github/workflows/kind-e2e.yaml
- Run periodic (every 4 hours) kind e2e tests. On failure, post to slack.
```release-note
Run kind e2e tests every 4 hours on Github actions.
```
**Docs**
=> add periodic e2e tests that post to slack on failure

pkg/channel/fanout/fanout_message_handler_test.go, pkg/kncloudevents/message_sender.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Signed-off-by: Ville Aikas <vaikas@vmware.com>
Fixes #4375
- Reconcile changes to delivery specs properly.
-
-
```release-note
- 🐛 Fix bug
Fix issue #4375 where we would not reconcile changes to reconcile policy or duration.
```
**Docs**
=> fix issue 4375

test/upgrade/probe_test.go, test/upgrade/prober/config.toml, test/upgrade/prober/configuration.go, test/upgrade/prober/forwarder.go, test/upgrade/prober/prober.go, test/upgrade/prober/prober_test.go, test/upgrade/prober/receiver.go, test/upgrade/prober/sender.go
Fixes #4420
- Makes Eventing upgrade tests prober fully configurable by environment variables
- Moving configuration stuff to `configuration.go` file
=> Eventing upgrade tests prober fully configurable

.github/workflows/kind-e2e.yaml
Related: https://github.com/knative/eventing/issues/4276
=> Drop TEST_EVENTING_NAMESPACE

pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
Fixes #4367
- Removing the usage of the test logger because the (graceful) shutdown of the in memory dispatcher happens way after the end of the test
=> Fix data race in dispatcher.TestNew

config/channels/in-memory-channel/roles/dispatcher-clusterrole.yaml, pkg/reconciler/inmemorychannel/controller/inmemorychannel.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/inmemorychannel/dispatcher/controller_test.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Signed-off-by: Ville Aikas <vaikas@vmware.com>
Fixes #
- Do not update subscriber statuses from the control plane, do it from the dispatcher by using patch to only modify the subscriber statuses
```release-note
- 🐛 Fix bug
Only update the subscriber statuses in IMC after they have been added to handlers. Reduces failures where the
subscribers have been marked before the dataplane has been actually configured.
```
**Docs**
=> Dispatcher updates subscriber statuses

test/upgrade/probe_test.go
Fixes #4441
Descriptive method names are good, but too long isn't good either.
- Reduce the name of prober test method
=> Reduce a prober test name length to prevent DNS label too long error

test/upgrade/prober/receiver.go, test/upgrade/prober/sender.go
Fixes #4444
- Avoid using bare pods for wathola components
=> Migrate wathola components to use deployment

pkg/channel/fanout/fanout_message_handler.go
Fixes #4376
- Remove the reference to an issue since verified Subscription reconciler resolves the dead letter sink URIl.
-
-
```release-note
```
**Docs**
=> checks out

pkg/kncloudevents/message_sender.go, pkg/kncloudevents/message_sender_test.go
Fixes #4453
- Retry on network failures
```release-note
- 🐛 Fix bug
Retry on network failures
```
Test execution logs:
```
2020/11/03 13:25:27 [DEBUG] POST http://127.0.0.1:21697
2020/11/03 13:25:27 [ERR] POST http://127.0.0.1:21697 request failed: Post "http://127.0.0.1:21697": dial tcp 127.0.0.1:21697: connect: connection refused
2020/11/03 13:25:27 [DEBUG] POST http://127.0.0.1:21697: retrying in 0s (10 left)
2020/11/03 13:25:27 [ERR] POST http://127.0.0.1:21697 request failed: Post "http://127.0.0.1:21697": dial tcp 127.0.0.1:21697: connect: connection refused
2020/11/03 13:25:27 [DEBUG] POST http://127.0.0.1:21697: retrying in 100ms (9 left)
2020/11/03 13:25:27 [ERR] POST http://127.0.0.1:21697 request failed: Post "http://127.0.0.1:21697": dial tcp 127.0.0.1:21697: …
```
=> Retry on network failures

pkg/kncloudevents/message_sender.go, pkg/kncloudevents/message_sender_test.go
- Backport #4454
```release-note
- 🐛 Fix bug
Retry on network failures
```
=> [release-0.18] Retry on network failures (#4454)

pkg/mtbroker/filter/filter_handler.go, pkg/mtbroker/filter/filter_handler_test.go
Fixes #4464
- Removed double invocations to responseWriter.WriteHeader in filter handler
- Testing in filter_handler_test.go if `WriteHeader` is invoked more than once
=> Remove double invocations to responseWriter.WriteHeader in filter handler

pkg/mtbroker/filter/filter_handler.go, pkg/mtbroker/filter/filter_handler_test.go
=> [0.18] Backport #4466

pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Fixes #4475 
-  🐛fixed wrong marshall in apiserversouece which will fix the missing ceOverrides extension 
-
-
```release-note
```
**Docs**
=> fixed wrong marshall in apiserversouece which will fix the missing ceOverrides extension 

config/core/deployments/pingsource-mt-adapter.yaml
- Fixes this error:
`The Deployment "pingsource-mt-adapter" is invalid: spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when "value` is not empty`
when upgrading from 0.17 to 0.18
```release-note
```
**Docs**
/cc @aliok @cr22rc 
Note that in 0.17 the adapter is managed by the controller. When applying 0.18, the mtping adapter configuration might be overridden by the 0.17 eventing controller that hasn't been rolled out yet to the new version. The fix is to wait a bit and then apply the mtping adapter configuration a second  time. That should do it.
Needs to be backported.
=> fix error during upgrade from 0.17 to 0.18

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Fixes #4473
- adding readynessProble
```release-note
```
**Docs**
=> Adding readynessProbe

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml, pkg/mtbroker/ingress/ingress_handler.go
Fixes #4473
- Start readiness probe in code
- Yaml stuff
=> [0.18] Readyness probe in broker ingress

test/e2e-conformance-tests.sh, test/e2e-tests.sh
Fixes #
- adding more source cfgs
```release-note
```
**Docs**
=> Enable more sources on e2e test cfg

config/core/resources/channel.yaml, config/pre-install/v0.18.0/channel.yaml, pkg/apis/messaging/config/channel_defaults_test.go, test/e2e/namespace_default_channel_test.go
Fixes #4491
Test output without the fix:
```
namespace_default_channel_test.go:87: CM updated - new values: |
clusterDefault:
apiVersion: messaging.knative.dev/v1
kind: InMemoryChannel
namespaceDefaults:
test-channel-namespace-defaulting-pzx9q:
apiVersion: messaging.knative.dev/v1
kind: InMemoryChannel
spec:
delivery:
backoffDelay: PT0.5S
backoffPolicy: exponential
retry: 5
namespace_default_channel_test.go:110: 
Error Trace:	namespace_default_channel_test.go:110
Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Channel.messaging.knative.dev \"xyz\" is invalid: …
```
=> Change Channel.spec.channelTemplate.spec type from string to object in OpenAPI schema

pkg/eventfilter/attributes/filter.go, pkg/eventfilter/attributes/filter_test.go, pkg/eventfilter/filter.go, pkg/eventfilter/filter_test.go, pkg/mtbroker/filter/filter_handler.go
This PR reorganizes the filtering code to be a little bit more extensible, although it doesn't add, nor modify, any current behaviour of the code. It just makes it simpler to contribute to extend it :smile: I did it to use as a base to enable people experiment new filters (play nice with #3771 and #4279). I have a couple of ideas I'm gonna show in next PRs on filtering, and this serves as a good base. Took from https://github.com/knative/eventing/pull/3771
=> Reorg of trigger filtering code

pkg/reconciler/source/config_watcher_test.go
Allows an empty logging config to represented by an empty
K_LOGGING_CONFIG value rather than requiring the population of default values.
Needed to allow changes in how logging configuration is handled in https://github.com/knative/pkg/pull/1773.
=> Relax empty logging config tests

pkg/eventfilter/benchmarks/attributes_benchmark_test.go, pkg/eventfilter/benchmarks/common_benchmark_test.go
This adds microbenchmarks to test implementations of `eventfilter.Filter`.
Note: although it doesn't make sense to test for the attributes filter the creation of the filter instance, it makes sense for more complex filters like in the context of #3359 and #4495, where creating the filter means transforming the user input in some middle representation (like an AST or a schema instance) which is not trivial to create
- Add generic microbenchmark to test creation and run of the filter implementation
- Add attributes microbenchmark tests
=> Microbenchmark for Trigger Filter

test/e2e/helpers/broker_redelivery_helper.go, test/e2e/helpers/channel_single_event_helper.go, test/lib/recordevents/event_info.go, test/lib/recordevents/event_info_matchers.go, test/lib/recordevents/event_info_store.go, test/lib/recordevents/event_log.go, test/lib/recordevents/receiver/receiver.go, test/lib/recordevents/receiver/reply.go, test/lib/recordevents/recorder_vent/constructor.go, test/lib/recordevents/recorder_vent/recorder.go, test/lib/recordevents/resources.go, test/lib/recordevents/sender/sender.go, test/lib/sender/resources.go, test/test_images/recordevents/main.go
Yeah, it sounds weird, look at #4368 for more details
Fixes #4368
- Refactored recordevents code to host the send events. 
- Using recordevents to send events in `SingleEventForChannelTestHelper`
In a followup PR I'm going to replace the implementation of `Client.SendEvent` to use recordevents, so we won't need to rewrite all tests.
=> Recordevent now sends events too

pkg/adapter/v2/main.go
- Log the error returned by `adapter.Start` at the "error" level instead of "warn"
- Fix the format of the logged error
Context: I was a bit surprised to see runtime failures being logged at the "warn" level when this kind of error means the application is shutting down due to a problem.
Besides, the format of the `msg` is broken due to the usage of `Warn` instead of `Warnw`:
```jsonc
// expected
{
"level": "warn",
// ...
"msg": "Start returned an error",
"err": "no stream associated with table \"debug\""
}
// got
{
"level": "warn",
// ...
"msg": "Start returned an error{error 26 0  no stream associated with table \"debug\"}"
}
```
```release-note
:broom: Log runtime errors of sources' adapters at the "error" level instead of "warn"
```
=> Log error returned by adapter.Start at error level

pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Fixes #4509
- Do not use finalizer for IMC dispatcher
```release-note
Do not set the finalizer for InMemoryChannel for dispatcher, just deal with it in reconcilekind
```
**Docs**
=> fix 4509, remove finalizer

config/core/resources/pingsource.yaml, pkg/adapter/mtping/runner.go, pkg/apis/sources/v1beta1/ping_conversion.go, pkg/apis/sources/v1beta2/ping_types.go, pkg/apis/sources/v1beta2/ping_validation.go
Follow-up to https://github.com/knative/eventing/pull/4474 
- :bug: Fixes unaddressed nits in https://github.com/knative/eventing/pull/4474
-
-
```release-note
```
**Docs**
=> Fix nits in PingSource v1beta2

test/e2e-common.sh
The function is part of the hack repository, see https://github.com/knative/hack/blob/d3cb354f49ffe4a15f1f509413efbd05bfd2ca21/library.sh#L749-L755
- Remove latest_version function
/kind cleanup
=> Remove latest_version function

pkg/reconciler/inmemorychannel/controller/resources/service.go, pkg/reconciler/mtbroker/resources/channel.go
- Fix naming for MTBroker Channels
- Fix naming for IMC Channel Services.
/kind bugfix
```release-note
:bug: - Fix naming for MTBroker Channels for length issues.If Broker name was long enough (~40 chars) would not become ready.
:bug:  - Fix naming for IMC Channel Services for length issues. If IMC Channel name was long enough (~40 chars) would not become ready.
```
=> [Release 0.18] Fix MTBroker Channel and IMC Channel Services length issue.

pkg/reconciler/inmemorychannel/controller/resources/service.go, pkg/reconciler/mtbroker/resources/channel.go
- Fix naming for MTBroker Channels
- Fix naming for IMC Channel Services.
/kind bugfix
```release-note
:bug: - Fix naming for MTBroker Channels for length issues.If Broker name was long enough (~40 chars) would not become ready.
:bug:  - Fix naming for IMC Channel Services for length issues. If IMC Channel name was long enough (~40 chars) would not become ready.
```
=> [Release 0.19] Fix MTBroker Channel and IMC Channel Services length issue.

config/core/resources/channel.yaml, config/pre-install/v0.18.0/channel.yaml, pkg/apis/messaging/config/channel_defaults_test.go, test/e2e/namespace_default_channel_test.go
Fixes #4491
- Backport https://github.com/knative/eventing/pull/4492
- Backport https://github.com/knative/eventing/pull/4500
```release-note
:bug: Fix bug
spec.channelTemplate.spec can be specified in default-ch-webhook.
```
/cc @vaikas
=> [0.18] Change Channel.spec.channelTemplate.spec type to object in OpenAPI schema

docs/spec/channel.md
This came out while i was working on #1845.
The _Channel not found_ behaviour is implementation dependant, so the sentence 
> the Channel MUST respond with `404 Not Found`.
may be incorrect. E.g. if you have a channel implementation that spawns one deployment per channel, then there is no endpoint to send the event, so you'll probably get a DNS or an i/o timeout error, nor a 404 response. With IMC channel, if the channel does not exists, then the `ExternalName` service does not exists. The user could invoke directly the imc-dispatcher svc and configure the `Host` header and in that case he will get a 404 back, but that's a behaviour depending on the specific IMC dispatcher implementation.
My proposal here is to make that …
=> Channel spec clarification about Channel not found behaviour

hack/update-codegen.sh
- Use GOPATH hacks to codegen anywhere.
=> integrate the gopath hacks to allow for codegen anywhere

test/lib/duck/resource_getters.go
Related: #4634 
- Add a newline at the end of the `GetGenericObject()` error message that may be causing a variety of our flakey tests
=> Add newline to GetGenericObject log line in testing

test/performance/README.md, test/performance/benchmarks/broker-imc/200-broker-perf.yaml, test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml, test/performance/benchmarks/broker-imc/dev.config, test/performance/benchmarks/broker-imc/prod.config, test/performance/benchmarks/channel-imc/dev.config, test/performance/benchmarks/channel-imc/prod.config
Fixes #4599 
- Update README to use `perf-eventing` namespace
- Update benchmark configuration
=> feat/perf-test: update README and broker-imc benchmark

config/channels/in-memory-channel/deployments/dispatcher.yaml
- Add soft Pod anti-affinity to IMC dispatchers
Dispatchers consume a fair amount of CPU and may starve on CPU time under load, as observed in the graph below (load-test at 24K then 27K events/sec against 5 replicas). Defining requests and limits would be too opinionated because we don't know where Knative is being deployed, but we can at least _try_ to ensure dispatchers are spread across nodes.
```release-note
```
**Docs**
=> Add soft Pod anti-affinity to IMC dispatchers

.github/workflows/kind-e2e.yaml
Reverts knative/eventing#4647
This seems to be failing with a `go test` timeout, and it is flooding slack with notifications.
=> Revert "add tests using k8s 1.20"

go.mod, go.sum, vendor/knative.dev/pkg/metrics/config.go, vendor/knative.dev/pkg/metrics/exporter.go, vendor/knative.dev/pkg/metrics/prometheus_exporter.go, vendor/modules.txt
Used `go get -u knative.dev/pkg@release-0.19` to bring the backport in.
=> [0.19] Backport https://github.com/knative/pkg/pull/1963 

pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Fixes #4638
- Implement `ReadOnlyInterface` in the IMC dispatcher.
Ensures any running dispatcher can handle events for _all_ InMemoryChannels, and not only the ones in the bucket it is leading.
After scaling the dispatcher to 5 replicas, I sent 100 events/s for 1 min to a Channel using `vegeta` and got a 100% success rate, versus ~20% before this change:
```
Requests      [total, rate, throughput]         6000, 100.02, 100.00
Duration      [total, attack, wait]             59.999s, 59.99s, 8.99ms
Latencies     [min, mean, 50, 90, 95, 99, max]  2.123ms, 6.119ms, 4.795ms, 10.404ms, 13.405ms, 27.218ms, 70.894ms
Bytes In      [total, mean]                     0, 0.00
Bytes Out     [total, mean]                     12288000, 2048.00
Success       [ratio]                           100.00% …
```
=> Implement ReadOnlyInterface in IMC dispatcher

docs/spec/spec.md
The <numberOfRetries> field wasn't being rendered in the duck.DeliverySpec
Add escape character to render the field
=> Update spec.md fix render typo on DeliverySpec

test/README.md
Running a e2e test such as,
```
go test -v -tags=e2e -count=1 ./test/e2e -run ^TestBrokerNamespaceDefaulting$
```
fails due to missing dependencies
```
=== RUN   TestBrokerNamespaceDefaulting
test_runner.go:153: namespace is : "test-broker-namespace-defaulting-g8ndg"
test_runner.go:160: Couldn't initialize clients: error while retrieving the config-tracing config map: configmaps "config-tracing" not found
knative.dev/eventing/test/lib.getTracingConfig
/Users/svohra/go/src/knative.dev/eventing/test/lib/client.go:145
knative.dev/eventing/test/lib.NewClient
```
- :broom: Update README to include env variable required to run the tests
Similar to https://github.com/knative/eventing/pull/4663
=> Update test README.md for go test commands

config/core/deployments/webhook.yaml
Kubernets adds additional env vars for each service with name
*_SERVICE_PORT, *_SERVICE_HOST and *_PORT, this causes trouble
in the webhook as it is using WEBHOOK_PORT to configure the
webhook port. Disabling it will enable using a default port.
Fixes #4671
=> Add enableServiceLinks:false to webhook yaml

config/200-webhook-role.yaml, config/core/200-webhook-serviceaccount.yaml, config/core/roles/webhook-clusterrole.yaml, config/core/roles/webhook-role.yaml
- Webhook has only namespaced Secret permissions, rather than cluster-wide.
```release-note
:broom: Webhook no longer has Cluster-wide Secret permissions. Now the Webhook's Secret permissions are restricted to the `knative-eventing` namespace.
```
=> Webhook has only namespaced Secret permissions, rather than cluster-wide.

config/core/resources/apiserversource.yaml, config/post-install/clusterrole.yaml, config/post-install/placeholder.go, config/post-install/serviceaccount.yaml, config/post-install/storage-version-migrator.yaml, hack/generate-yamls.sh
Fixes #4189
-  ApiServerSource stored version v1 
- Add migration tool
```release-note
Action Required: You need to run the storage migration tool after the upgrade to migrate from v1beta1 to v1 `apiserversources.sources.knative.dev` resources.
```
=> ApiServerSource stored version v1 and migration tool

config/core/resources/containersource.yaml, config/post-install/clusterrole.yaml, config/post-install/storage-version-migrator.yaml
Fixes #4325 
-  ContainerSource stored version v1 
- Add migration tool
```release-note
Action Required: You need to run the storage migration tool after the upgrade to migrate from v1beta1 to v1 `containersources.sources.knative.dev` resources.
```
=> ContainerSource stored version v1 and migration tool

config/core/resources/sinkbindings.yaml, config/post-install/clusterrole.yaml, config/post-install/storage-version-migrator.yaml
Fixes #4264 
- SinkBinding stored version v1 
- Add migration tool
```release-note
Action Required: You need to run the storage migration tool after the upgrade to migrate from v1beta1 to v1 `sinkbindings.sources.knative.dev` resources.
```
=> SinkBinding stored version v1 and migration tool

test/e2e/broker_defaults_webhook_test.go
Fixes #4506
:broom:  assert namespace defaults for broker class & delivery are set by the webhook controller
=> [#4506] Add e2e test for broker webhook defaults

test/e2e/broker_defaults_webhook_test.go
Error was:
```
knative.dev/eventing/test/e2e.webhookObservedBrokerUpdateFromDeliverySpec(...)
/home/runner/work/eventing/eventing/src/knative.dev/eventing/test/e2e/broker_defaults_webhook_test.go:179
```
Fixes #4710
- Fix panic in the TestBrokerNamespaceDefaulting
=> Fix panic in the TestBrokerNamespaceDefaulting

test/e2e/broker_defaults_webhook_test.go
Fixes #https://github.com/knative/eventing/issues/4715
For example here:
https://github.com/knative/eventing/runs/1677836817?check_suite_focus=true
```
broker_defaults_webhook_test.go:132: 
Error Trace:	broker_defaults_webhook_test.go:132
util.go:51
wait.go:211
wait.go:399
util.go:50
broker_defaults_webhook_test.go:112
Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"brokers.eventing.knative.dev \"xyz-0\" already exists", Reason:"AlreadyExists", Details:(*v1.StatusDetails)(0xc0021758c0), Code:409}}
```
- When re-trying to create a Broker the name must not be the same or it will fail …
=> bump the name of the broker on each iter

go.mod, go.sum, pkg/kncloudevents/message_receiver.go, vendor/knative.dev/hack/library.sh, vendor/knative.dev/pkg/network/handlers/drain.go, vendor/modules.txt
Fixes #
Message receiver uses Drainer to run liveness and readiness check. Previously, when the Pod is not in draining status, Drainer directly writes statusOK to kube probe request, without going through the inner handler logic. This makes any customized health check in inner handler useless. 
Now that Drainer supports customized check, let message receiver support it as well. This would help users who want to use kn event message receiver and in the time want to configure their own check.
```release-note
message receiver supports customized liveness and readiness check 
```
**Docs**
=> message receiver supports customized liveness and readiness check

test/e2e/broker_defaults_webhook_test.go
Fixes #4721
- :broom: update broker config map so broker status is true and doesn't fail due to missing channel template
```
$ SYSTEM_NAMESPACE=knative-eventing go test -v -tags=e2e -count=1 ./test/e2e -run ^TestBrokerNamespaceDefaulting$
=== RUN   TestBrokerNamespaceDefaulting
test_runner.go:153: namespace is : "test-broker-namespace-defaulting-lbkqf"
=== PAUSE TestBrokerNamespaceDefaulting
=== CONT  TestBrokerNamespaceDefaulting
broker_defaults_webhook_test.go:53: Updating defaulting ConfigMap attempt: 0
broker_defaults_webhook_test.go:94: CM updated - new values: |
clusterDefault:
apiVersion: v1
brokerClass: MTChannelBasedBroker
kind: ConfigMap
name: config-br-default-channel
namespace: knative-eventing
namespaceDefaults:
test-broker-namespace-defaulting-lbkqf:
apiVersion: v1 …
```
=> [#4721] Update e2e broker default webhook test

go.mod, go.sum, pkg/kncloudevents/message_receiver.go, vendor/knative.dev/pkg/network/handlers/drain.go, vendor/modules.txt
Fixes #
- With alignment problem, 4707 was revert. Re-submit it. 
-
-
```release-note
message receiver supports customized liveness and readiness check 
```
**Docs**
=> Re-submit #4707

test/e2e/broker_defaults_webhook_test.go
Fixes #4717
:broom: 
use "require.Nil" instead of "assert.Equal" for test setup. The latter
notes a failure but doesn't fail immediately. This resulted in panics
in subsequent sections of the test and made it hard to pin point the
reason. "require.Nil" will output the error and fail immediately
making it easier to debug issues with test setup.
=> [#4717] Update e2e broker defaults webhook test

.github/workflows/kind-e2e.yaml
Fixes #4725
- Use ./hack scripts instead of simple kubectl wait.
-
-
```release-note
- :bug: Fix bug where sometimes the pods were not deemed up during setup. #4725
```
**Docs**
=> Use wait_for_pods instead of kubectl wait for pods. Fix #4725

docs/spec/channel.md, pkg/channel/message_dispatcher.go, pkg/tracing/populate_span_transformer.go, pkg/tracing/populate_span_transformer_test.go, test/conformance/helpers/channel_tracing_test_helper.go, test/conformance/helpers/tracing/traces.go
Fixes #4578
- imc dispatcher adds the following attributes to trace span to make it consistent with broker ingress and filter spans
```
messaging.destination
messaging.message_id
messaging.protocol
messaging.system
```
- update channel spec observability section to reference the Open Telemetry Spec attributes
- update channel spec for readability
```release-note
The  `imc-dispatcher` service adds new trace span attributes to be consistent with `broker-ingress.knative-eventing` & `broker-filter.knative-eventing` services. The new attributes are messaging.destination,  messaging.message_id, messaging.protocol and messaging.system
```
=> Add Open Telemetry Spec attributes to IMC Dispatcher span

docs/spec/data-plane.md
This is one of the steps to solve #4127. 
This is a follow up of the discussion in the [event reply proposal](https://docs.google.com/document/d/1ELQtKOMz6T5vTXbWp30E8r6oLYOXPjWacv4AVRi36-w) to add the contract to the spec.
- Add event reply header to the spec
```release-note
- :gift: Add event reply header contract to the spec
```
=> Add event reply header to spec

test/config/monitoring/monitoring.yaml
- :broom: Bump zipkin version to the latest available as the currently referenced one is ~2 yrs old. The motivation for this change is to reduce the probability that the older version of zipkin was contributing to test flakiness observed in https://github.com/knative/eventing/issues/4744.
=> [#4744] Bump test zipkin version

test/conformance/helpers/tracing/traces.go
- :broom: fail with an explicit message if a trace doesn't have a root span.
This scenario was being caught subsequently in the helper and failing
with `left over spans after generating the SpanTree` which is more
generic and a catch all.
The idea is to make it clearer if the missing root span is a common
failure scenario.
Ref - https://github.com/knative/eventing/issues/4744
=> [#4744] Update conformance test helper

config/core/resources/pingsource.yaml, config/post-install/clusterrole.yaml, config/post-install/storage-version-migrator.yaml
Fixes https://github.com/knative/eventing/issues/4539
- 🧹 flip storage version to v1beta2 in PingSource CRD
- 🎁 add post-install job to migrate existing PingSource objects to v1beta2
-
```release-note
Action Required: You need to run the storage migration tool after the upgrade to migrate from v1beta1 to v1 `pingsources.sources.knative.dev` resources.
```
**Docs**
=> use v1beta2 as the storage version of PingSource

hack/generate-yamls.sh
Since acf65cf started using hack/generate-yamls.sh, the `KO_FLAGS` option
was not used correctly so `--platform=all` option was missed in release
manifest.
This patch fixes it.
Thank you @VIjayHP for reporting the issue.
```release-note
NONE
```
/cc @runzexia @n3wscott @slinkydeveloper
=> Use KO_YAML_FLAGS for multi-platform build

test/upgrade/upgrade.go, test/upgrade/upgrade_test.go
- This PR exposes the function `RunMainTest`, so that test cases in other packages can call the main tests for eventing upgrade.
=> Expose the function RunMainTest

test/e2e/channel_defaults_webhook_test.go
Fixes #4739 
- :broom: use "require.Nil" instead of "assert.Equal" for test setup and where
we don't wish to retry. The latter notes a failure but doesn't fail
immediately. This resulted in panics in subsequent sections of the
broker defaults webhook test [#4717] and made it hard to pin point
the reason. "require.Nil" will output the error and fail immediately
making it easier to debug issues with test setup.
=> [#4739] Update e2e channel defaults webhook test

config/core/deployments/webhook-hpa.yaml, config/hpa-webhook.yaml
- Set up HPA for eventing-webhook:
- Scale Webhook based on CPU
- Add initial PodDisruptionBudget
Similar to this PR on the serving component from September 2020: https://github.com/knative/serving/pull/9444
```release-note
Adding HorizontalPodAutoscaler and PodDisruptionBudget for the eventing webhook
```
=> Adding HPA for eventing-webhook

config/core/webhooks/config-validation.yaml
Fixes #3244
- Set failure policy to ignore for webhook
- This allows setup to get out of failure loop described in #3244 
-
-
- :bug: Fix #3244 - webhook creation fails under certain race condition
=> Set failure policy to ignore for webhook

.github/workflows/kind-e2e.yaml, go.mod
Fixes #
- Use go 1.15 in go.mod file
- Drop testing of k8s 1.17 in kind e2e tests
-
```release-note
```
**Docs**
=> go 1.15 in go.mod, drop k8s 1.17 e2e tests

support/COMMUNITY_CONTACTS.md
- :broom: replace link that appears to be deprecated `https://testgrid.knative.dev/eventing` with the functional one `https://testgrid.k8s.io/knative-eventing
=> Update COMMUNITY_CONTACTS.md test grid link

test/e2e-common.sh
Eventing webhook HPA config sets MinReplicas to 1 and while chaosduck
kills the webhook we get 0 replicas available during E2E tests.
Fixes recent flaky tests.
- Patch HPA eventing-webhook min replicas
=> Patch HPA eventing-webhook min replicas

.github/workflows/knative-style.yaml
Ref #4796 
- :broom: Bump golangci-lint to v1.35 and set a timeout of 10s. The workflow has been [failing](https://github.com/knative/eventing/actions?query=workflow%3A%22Code+Style%22+is%3Afailure) with a higher frequency recently. 
- The [golangci-lint](https://golangci-lint.run/usage/configuration/) has a default timeout of 1m. The [golangci-lint action](https://github.com/golangci/golangci-lint-action) doesn't seem to have a configured timeout so its weird that most of the timeouts  > ~300s not 60s. Setting the value to 10m to be conservative and validate if this resolves the failure.
=> Bump golang linter version and timeout

config/core/resources/broker.yaml, config/core/resources/trigger.yaml, docs/spec/broker.md, pkg/apis/eventing/v1/broker_types.go, pkg/apis/eventing/v1/trigger_types.go, pkg/apis/eventing/v1/trigger_validation.go, pkg/apis/eventing/v1/zz_generated.deepcopy.go, pkg/apis/eventing/v1beta1/trigger_conversion.go, pkg/apis/eventing/v1beta1/trigger_types.go, pkg/apis/eventing/v1beta1/trigger_validation.go, pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
PR to modify the spec according to #4515
- :gift: Add the Trigger.Delivery field
- :broom: Now Broker.Delivery defaults the Trigger.Delivery field. Note: **this is a breaking change** for mtbroker users that are using the Broker.Delivery field, because this field, even if it remains the same, will change meaning for them (in a followup I'll perform the actual change)
```release-note
:gift: Add Trigger.Delivery field which allows configuration of Delivery per Trigger.
```
**Docs**
=> Fix spec #4515

pkg/apis/eventing/v1/trigger_validation_test.go, pkg/apis/eventing/v1beta1/trigger_conversion.go, pkg/apis/eventing/v1beta1/trigger_types.go, pkg/apis/eventing/v1beta1/trigger_validation_test.go, pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
Fixes #
- :broom: Followup to #4654 and change the trigger.Spec.DeliverySpec from v1beta1 duck to v1. Add UT.
-
-
```release-note
```
**Docs**
=> v1beta1.Trigger delivery should be v1.DeliverySpec

support/COMMUNITY_CONTACTS.md
@zhongduo as discussed on the slack. Changing the link to point to head.
- Fix the link to Eventing Triage to be head instead of an older branch which is confusing.
-
-
```release-note
```
**Docs**
=> fix the link to head

.golangci.yaml
Fixes #4796
- :broom: Update golangci linter timeout to 10m as the workflow has been [failing](https://github.com/knative/eventing/actions?query=workflow%3A%22Code+Style%22+is%3Afailure) due to a timeout with a higher frequency recently.
=> [#4796] Bump golang lint timeout to 10m

docs/spec/broker.md
Fixes #4837 
This is to keep compatibility with brokers that cannot support per trigger delivery.
=> Use SHOULD for TriggerSpec to keep compatibility

pkg/adapter/apiserver/delegate.go, pkg/adapter/apiserver/events/events.go, pkg/adapter/apiserver/events/events_test.go
Fixes #
Currently the APIServerSource only shows up a log on a failure of event delivery, this commit would output a log whenever an event is sucessfully routed as well.
- Simply marshalling the event.Extensions map to []bytes and then printing it for Add(), Update() and Delete() scenarios.
EDIT:
- Instead of using marshalling the extensions, the code now uses the cloudevent source+subject as identifier. Mostly making reuse of the pingsource code. 
- Since context is now shared, I added `ContextWithMetricTag` in here as well, to fix https://github.com/knative/eventing/issues/4709
=> Adding Logline for when a cloudevent has been successfully sent from APIServerSource to the sink

docs/spec/broker.md
Fixes #
- This is to clarify whether the broker of a trigger is allowed to be changed 
- This is originated from the discussion [here](https://github.com/knative/eventing/pull/4816#issuecomment-771014943) where it's found that the current **v1beta1** trigger allows broker to be changed and some conformance tests are modifying the broker of a trigger. If it's decided here the assigned broker should be immutable, a followup PR need to fix the conformance tests and the validation code.
```release-note
```
**Docs**
=> Change trigger spec to indicate assigned broker should be immutable

DEVELOPMENT.md, docs/decisions/broker-trigger.md, docs/spec/overview.md, test/e2e/helpers/README.md
Fixes #
- found a few references to "contrib" repo... replaced/removed them as needed
```release-note
```
**Docs**
=> Remvoing contrib refs

config/core/resources/pingsource.yaml, pkg/adapter/mtping/runner.go, pkg/adapter/mtping/runner_test.go, pkg/apis/sources/v1beta2/ping_types.go
Fixes: https://github.com/knative/eventing/issues/4852
- :bug: BREAKING CHANGE: PingSource binary mode now sends the actual binary data in event body instead of base64-encoded form.
-
-
```release-note
BREAKING CHANGE: PingSource binary mode now sends the actual binary data in event body instead of base64-encoded form.
```
**Docs**
=> fix(PingSource): event consumer should receive base64-decoded dataBase64

pkg/apis/eventing/v1/broker_validation_test.go, pkg/apis/eventing/v1/trigger_validation_test.go, pkg/apis/eventing/v1beta1/broker_validation_test.go, pkg/apis/eventing/v1beta1/trigger_validation.go, pkg/apis/eventing/v1beta1/trigger_validation_test.go, test/conformance/helpers/broker_control_plane_test_helper.go
- While we have tests for CheckImmutableFields, we did not have UT for running through the actual update, so added those for v1/v1beta1 broker/trigger.
```release-note
:bug: Fix bug where v1beta1 would allow mutations to immutable fields. v1beta1 trigger.spec.broker is immutable.
```
**Docs**
=> ut for trigger/broker updates check immutable

pkg/channel/message_receiver.go, pkg/channel/message_receiver_test.go
Fixes #3069 
- Make the ChannelReference in UnknownChannelError public so that Channel implementations can populate it.
**Note:**  The distributed KafkaChannel "Receiver" was trying to populate this data in order to be a good citizen, but upon further review it seems it's never really used/logged (since receiving events for non-existent channels might be frequent and not considered "log-worthy" : )   So, this change will make it possible to identify the specific ChannelReference which was not found (or "Unknown") in case it's useful in a IDE/Debug scenario or is later logged somewhere, but otherwise shouldn't have any effect.
=> expose ChannelReference in UnknownChannelError

pkg/adapter/v2/config.go
Fixes #
https://github.com/knative/eventing/issues/1889
- just replicating an older fix mentioned in the issue, which was somehow lost while refactoring the code. 
more: https://github.com/knative/eventing/pull/1990
```release-note
Fix availability of zipkin traces for APIServerSource
```
=> tracing fixed for apiserversource

pkg/reconciler/pingsource/pingsource.go, pkg/reconciler/pingsource/resources/receive_adapter.go, pkg/reconciler/pingsource/resources/receive_adapter_test.go
Fixes 
https://github.com/knative/eventing/issues/4757
- reading config-tracing cm and setting it for the pingsource adapter
```release-note
Cloudevent traces available for PingSource
```
**Docs**
https://github.com/knative/docs/pull/3249
=> Setting tracing config for PingSource

pkg/reconciler/pingsource/controller.go, pkg/reconciler/pingsource/controller_test.go, pkg/reconciler/pingsource/pingsource.go, pkg/reconciler/pingsource/pingsource_test.go, pkg/reconciler/pingsource/resources/receive_adapter.go, pkg/reconciler/pingsource/resources/receive_adapter_test.go
Follow up to #4877
- Refactor code to invoke the ConfigAccessor's `ToEnvVars()` method instead of accessing each env var individually
/assign lionelvillard
cc @Shashankft9
=> Use ConfigAccessor's ToEnvVars method in PingSource

cmd/webhook/main.go, config/400-config-ping-defaults.yaml, config/core/configmaps/default-pingsource.yaml, pkg/apis/sources/config/ping_defaults.go, pkg/apis/sources/config/store.go, pkg/apis/sources/v1alpha2/ping_validation.go, pkg/apis/sources/v1alpha2/ping_validation_test.go, pkg/apis/sources/v1beta1/ping_validation.go, pkg/apis/sources/v1beta1/ping_validation_test.go, pkg/apis/sources/v1beta2/ping_validation.go, pkg/apis/sources/v1beta2/ping_validation_test.go
Fixes #
see https://github.com/knative/eventing/issues/4055
Provide configmap with jsonData max bytes enforce in validating webhook.
By default jsonData max bytes is 4096 bytes.
=> jsonDataLimit#4055

config/core/configmaps/default-pingsource.yaml, pkg/apis/sources/config/ping_defaults.go, pkg/apis/sources/config/ping_defaults_test.go, pkg/apis/sources/config/store.go, pkg/apis/sources/config/testdata/config-ping-defaults.yaml, pkg/apis/sources/v1alpha2/ping_validation.go, pkg/apis/sources/v1beta1/ping_validation.go, pkg/apis/sources/v1beta2/ping_validation.go
- Configmap should be basic key/value pair, not a string for a yaml struct
- Provide example dataMaxSize configmap config
- Correct example-checksum annotation
- No mashalling from yaml needed, strconv directly to int64
- Add unit testing for ConfigMap reading
- Remove erroneous broker parsing comments/function from copied implementation
- Rename configmap to match naming conventions
- update bsize len assignment to match int64 size
- :broom: Cleanup ping dataMaxSize configmap implemenation
=> Fixup ping source dataMaxSize configmap

pkg/kncloudevents/message_sender.go, pkg/kncloudevents/message_sender_test.go
Fixes #
- Adding a try if the statusCode is `-1`, similar to the new alternative/approach 
```release-note
We now do a retry if we have a -1 statusCode
```
**Docs**
=> Adding check for -1 status code for the default retry impl

docs/roadmap-2021.md
Fixes #2426 
- Add roadmap for 2021 for Eventing, Eventing Sources and Event Delivery WGs
/cc @vaikas @grantr @lionelvillard @n3wscott @matzew @slinkydeveloper
=> Add roadmap for 2021 for Eventing, Eventing Sources and Event Delivery WGs

config/core/resources/apiserversource.yaml, config/core/resources/containersource.yaml, config/core/resources/pingsource.yaml, config/core/resources/sinkbindings.yaml
- Add missing explicit singular names for some CRDs that were missing them (no behaviour change since these get filled by default with lowercased kind value)
=> Add missing singular resource names to sources/sinkbinding crds

pkg/adapter/mtping/adapter.go, pkg/adapter/mtping/controller.go, pkg/adapter/mtping/controller_test.go, pkg/client/injection/reconciler/sources/v1beta2/pingsource/demote.go
Backport #4908 
Manual edit: provide a way to set the demote function without having to regenerate the code.
=> Backport 4908

pkg/reconciler/mtbroker/trigger/controller_test.go, pkg/reconciler/mtbroker/trigger/trigger.go, pkg/reconciler/mtbroker/trigger/trigger_test.go
Fixes #4968
- Get them coverage numbers up for trigger / controller
```release-note
```
**Docs**
=> add more coverage

config/channels/in-memory-channel/roles/controller-clusterrole.yaml, pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go, pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go
Fixes #4844
- Fix privilege escalation error
- Fix missing env vars in namespace-scoped in-mem dispatcher. 
-
```release-note
:bug: Fix bug preventing the namespace-scoped in-memory channel to become ready. 
```
**Docs**
=> fix broken in-mem channel namespace mode

config/core/configmaps/leader-election.yaml
Leader election supports specifying the number of buckets to use
for leader election.
The documentation is copied from serving.
- Add buckets example to config-leader-election CM
=> Add buckets example to config-leader-election CM

pkg/reconciler/mtbroker/trigger/trigger.go, pkg/reconciler/mtbroker/trigger/trigger_test.go
Fixes #4994 #4628
- :bug: Fix bug #4994 #4628, Allow `Trigger` users to set another namespace's `Subscriber`, And when `Subscriber`'s namespace not been set, it will be set to  `Trigger`'s namespace 
```release-note
Allow Trigger users to set another namespace's Subscriber, And when Subscriber's namespace not been set, it will be set to  Trigger's namespace 
```
**Docs**
=> fix #4994 use trigger's namespace only when subscriber's namespace is nil

pkg/reconciler/sugar/namespace/controller.go, pkg/reconciler/sugar/namespace/controller_test.go, pkg/reconciler/sugar/namespace/namespace.go, pkg/reconciler/sugar/namespace/namespace_test.go, pkg/reconciler/sugar/resources/broker_test.go, pkg/reconciler/sugar/trigger/controller.go, pkg/reconciler/sugar/trigger/controller_test.go, pkg/reconciler/sugar/trigger/trigger.go, pkg/reconciler/sugar/trigger/trigger_test.go, pkg/reconciler/testing/v1/namespace.go
Addresses #4836 
- :broom: Have sugar controller use v1 resources instead of v1beta1.
-
-
```release-note
```
**Docs**
=> sugar uses v1 versions of broker / trigger

test/e2e-rekt-tests.sh
the flakes on e2e and rekt tests come from these taking too much time on prow. Break them apart.
=> break apart rekt tests from e2e tests

test/rekt/README.md, test/rekt/features/pingsource/readyness.go, test/rekt/resources/pingsource/pingsource.go, test/rekt/resources/pingsource/pingsource.yaml, test/rekt/resources/pingsource/pingsource_test.go, test/rekt/smoke_test.go
Related to https://github.com/knative/eventing/issues/4952
Adds a simple smoke test in the reconciler testing framework for PingSource v1beta2
=> adding ping source smoke test

docs/spec/README.md, docs/spec/broker.md, docs/spec/channel.md, docs/spec/data-plane.md, docs/spec/helper.md, docs/spec/interfaces.md, docs/spec/motivation.md, docs/spec/overview.md, docs/spec/sources.md, docs/spec/spec.md
Fixes #
Adds a  line that was missing from https://github.com/knative/eventing/pull/5057
-
-
-
```release-note
```
**Docs**
=> Add redirect link to spec docs

test/e2e-common.sh
KO_FLAGS env variable is used for `ko apply` in almost all eventing parts except chaosduck.
Usage of this variable will unblock chaosduck installation during tests for non-amd64 architectures (`--platform` ko parameter specification is required for non-amd64).
=> Add KO_FLAGS usage to chaosduck build

test/rekt/broker_test.go, test/rekt/features/broker/control_plane.go, test/rekt/main_test.go, test/rekt/resources/broker/broker.go
Relates to #4934
Downstream conformance testers need just configure the env flags and produce new brokers.
=> broker changes come from the env.

docs/spec/README.md, docs/spec/broker.md, docs/spec/channel.md, docs/spec/data-plane.md, docs/spec/helper.md, docs/spec/interfaces.md, docs/spec/motivation.md, docs/spec/overview.md, docs/spec/sources.md, docs/spec/spec.md
Fixes #https://github.com/knative/specs/issues/4
- Github UI doesn't follow redirects. So changing the spec files to follow convention used by docs by keeping the title of the document with a link to the new location.
- Serving example: https://github.com/knative/serving/blob/main/docs/spec/errors.md
```release-note
```
**Docs**
=> Change spec redirects to template used by docs and serving

test/e2e-common.sh, test/e2e-rekt-tests.sh, test/rekt/features/broker/control_plane.go
Related to #4944
Testing that filters can not be make with invalid filters.
=> Broker/Trigger Conformance Tests, invalid trigger.spec.filters

pkg/apis/messaging/v1/subscription_defaults.go, pkg/apis/messaging/v1/subscription_validation.go, pkg/apis/messaging/v1/subscription_validation_test.go, pkg/apis/messaging/v1beta1/subscription_defaults.go, pkg/apis/messaging/v1beta1/subscription_validation.go, pkg/apis/messaging/v1beta1/subscription_validation_test.go, pkg/reconciler/subscription/subscription.go
For more details https://github.com/knative-sandbox/eventing-kafka/issues/426#issuecomment-800873603
/hold
=> KafkaChannel hack to upgrade

docs/roadmap-2021.md
With work starting on getting the Eventing v1.0 out, it only makes sense to have it as the top priority item on our roadmap
- Add Eventing 1.0 to the roadmap
=> Add Eventing 1.0 to the roadmap

config/core/deployments/webhook.yaml
Fixes #4987
- Adjust resources.requests of eventing-webhook
- Respond to the fact that the eventing-webhook is set to HorizontalPodAutoscaler, which may scale the pod extra if CPU requests are too low.
- Memory resources were also adjusted, as their usage is clearly higher than the current Requests.
(Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz)
```release-note
Fix excessive number of Replicas for eventing-webhook
```
**Docs**
=> Adjust resources.requests of eventing-webhook

.github/workflows/kind-e2e.yaml, hack/create-kind-cluster.sh
Every downstream eventing repo inline the creation of the KinD cluster.
- [Eventing Kafka Broker](https://github.com/knative-sandbox/eventing-kafka-broker/blob/a2ee4608aa26e6564399fe0903a0b423b9c6ef41/.github/workflows/kind-e2e.yaml#L106-L140)
- [Eventing Kafka](https://github.com/knative-sandbox/eventing-kafka/blob/12679c8ec25aa43d67493c2b71e1f0221d7d45ed/.github/workflows/kind-e2e.yaml#L95-L132)
- [Eventing RabbitMQ](https://github.com/knative-sandbox/eventing-rabbitmq/blob/454e9e34a866b492630b6dfa9e06092dabe6a56f/.github/workflows/kind-e2e.yaml#L91-L122)
- ...
Note: [Serving needs a container config patch](https://github.com/knative/serving/blob/9ee92b15428fff5db0f15dc2f50756ab1e23e311/.github/workflows/kind-e2e.yaml#L113-L114), so this isn't suitable for a repository like `pkg` or …
=> Add create KinD cluster script

test/conformance/helpers/sources/source_crd_rbac_test_helper.go
Fixes #3119 
Continuation from earlier PR https://github.com/knative/eventing/pull/4787
=> Changing cluster role's name check to check only suffix for source spec conformance testing

test/rekt/features/broker/data_plane.go
Fixes #
- As per: https://github.com/knative/specs/pull/13 relax the allowed response codes when a CE is malformed.
-
-
```release-note
```
**Docs**
=> relax malformed ce response code to 4xx

pkg/kncloudevents/message_receiver.go, pkg/kncloudevents/message_receiver_test.go, pkg/kncloudevents/utils_test.go
Fixes #4962 
- :broom: Increase test coverage > 80%
```
$ go test -cover .
ok  	knative.dev/eventing/pkg/kncloudevents	(cached)	coverage: 91.0% of statements
```
=> 4962 test coverage kncloudevents

go.mod, go.sum, vendor/knative.dev/pkg/metrics/resource_view.go, vendor/modules.txt
I noticed that broker ingress on 0.20 was failing due to https://github.com/knative/serving/issues/10421 and since this has been fixed as a [side-effect of the oom fix](https://github.com/knative/serving/issues/10421#issuecomment-787621560) I am adding it here as an update from the knative/pkg.
Run:
```
$ go get knative.dev/pkg@release-0.20
$ ./hack/update-deps.sh
```
=> [Update 0.20] Add fix for oom

go.mod, go.sum, test/rekt/features/broker/data_plane.go, test/rekt/features/knconf/data_plane.go, vendor/knative.dev/pkg/injection/config.go, vendor/knative.dev/pkg/reconciler/testing/context.go, vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go, vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go, vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go, vendor/modules.txt
We had to make a breaking change in https://github.com/knative-sandbox/reconciler-test/pull/164, this PR lets us import that change.
=> add t to Assert helpers from rekt

pkg/apis/sources/v1beta1/ping_conversion.go, pkg/apis/sources/v1beta1/ping_conversion_test.go
Fixes https://github.com/knative/eventing/issues/5137
- :broom: v1beta1 will not always be roundtrip-able (in the case that jsonData cannot be marshalled into json, e.g. jsonData="hello"), but the cloudevent on the wire stays the same.
- :bug: duckv1.SourceSpec, TimeZone, Schedule will be populated when called by v1beta1 clients
- :broom: object with v1beta2-specific features (dataBase64, contentType beyond `application/json`) will not populate jsonData field when converted to v1beta1.
```release-note
:bug: duckv1.SourceSpec, TimeZone, Schedule will be populated when called by v1beta1/v1alpha2 clients
```
**Docs**
=> fix(PingSource): remove annotation based conversion logic

test/upgrade/prober/prober.go, test/upgrade/prober/verify.go
Fixes #5264
- Prober in upgrade tests calls t.Fatal instead of Panic
```release-note
```
**Docs**
=> Do not panic prober if report fetched too early (#5264)

pkg/reconciler/broker/trigger/trigger.go, pkg/reconciler/broker/trigger/trigger_test.go, pkg/reconciler/testing/v1/trigger.go
Fixes https://github.com/knative/eventing/issues/5266
- :bug: Propagate trigger.spec.delivery to subscriptions for MTChannelBasedBroker.
```release-note
Bug fix: Propagate trigger.spec.delivery to subscriptions for MTChannelBasedBroker.
```
=> make sure the mtchannelbasedbroker uses trigger.spec.delivery

pkg/apis/messaging/v1/subscription_defaults.go, pkg/apis/messaging/v1/subscription_validation.go, pkg/apis/messaging/v1/subscription_validation_test.go
Reverts https://github.com/knative/eventing/pull/5085, which was required in 0.22 release to upgrade kafka channel
=> Remove KafkaChannel upgrade hack

pkg/eventfilter/attributes/filter.go, pkg/eventfilter/attributes/filter_test.go
Fixes https://github.com/knative/eventing/issues/4847
- setting `dataschema` - an optional attribute in v1.0 CE spec
- added check if empty string value is used in filter for optional attributes and extensions. 
- added specific test cases for extensions and optional attribute - `subject`. Let me know if its better without some of them, I'll remove.
```release-note
```
**Docs**
=> Filtering fix for consistency in handling empty string as value

test/rekt/broker_test.go, test/rekt/features/broker/control_plane.go, test/rekt/resources/trigger/trigger_test.go
=> test trigger delivery specs fully

test/rekt/features/channel/control_plane.go, test/rekt/features/channel/data_plane.go
Fixing some more race conditions. It is a bit too easy to write tests that fail based on racing. We will look into how to fix this more generally.
=> [Rekt] adding more polling for channel tests

pkg/eventfilter/attributes/filter.go, pkg/eventfilter/attributes/filter_test.go
Only do event field lookups as needed, don't pre-emptively cache them into a map
Fixes #5277 
Previous:
```
$ go test -benchtime 10s -bench=. ./pkg/eventfilter/benchmarks/
goos: linux
goarch: amd64
pkg: knative.dev/eventing/pkg/eventfilter/benchmarks
cpu: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
BenchmarkAttributesFilter/Creation:_Pass_with_exact_match_of_id-12              1000000000               2.699 ns/op
BenchmarkAttributesFilter/Run:_Pass_with_exact_match_of_id-12                    1675917              7419 ns/op
BenchmarkAttributesFilter/Creation:_Pass_with_exact_match_of_all_context_attributes_(except_time)-12            1000000000               2.697 ns/op
BenchmarkAttributesFilter/Run:_Pass_with_exact_match_of_all_context_attributes_(except_time)-12                  1697353 …
```
=> Improve performance of eventfilter lookups

pkg/broker/ingress/ingress_handler.go, pkg/broker/ingress/ingress_handler_test.go
Fixes #5143
- running validation of the extracted cloudevent.
```release-note
Runnng validation for event ingress on mt broker 
```
**Docs**
=> Running validation for events on broker ingress

go.mod, go.sum, test/rekt/broker_test.go, test/rekt/features/broker/control_plane.go, vendor/knative.dev/reconciler-test/pkg/environment/magic.go, vendor/knative.dev/reconciler-test/pkg/feature/context.go, vendor/knative.dev/reconciler-test/pkg/feature/feature.go, vendor/knative.dev/reconciler-test/pkg/manifest/installer.go, vendor/modules.txt
Fixes #
- :gift: Delete k8s resources created in Features. Important for some environments where we create many resources and the footprint may not be light.
- Utilizes https://github.com/knative-sandbox/reconciler-test/pull/183
-
-
```release-note
```
**Docs**
=> Clean up resources created by Feature tests

test/e2e-common.sh
As per title. Since https://github.com/google/ko/commit/6586a72f8a458b6b2139fd8b97d4412afab91f03 this has been the default and we recently updated `ko` in CI.
/assign @matzew @slinkydeveloper
=> Drop --strict flag on ko

pkg/apis/messaging/config/channel_defaults_test.go, pkg/apis/messaging/config/testdata/default-ch-webhook.yaml
Fixes #
- :broom: lifting some apis to more recent level
-
-
```release-note
```
**Docs**
=> [v1] Lifting some apis to more recent level

pkg/apis/messaging/v1/subscription_validation_test.go
Part of #4931
- :broom: Increase test coverage for Subscription validation
-
-
```release-note
```
**Docs**
=> Increase Subscription validation test coverage

test/README.md, test/e2e-common.sh
Fixes #5292 
- If an environment variable (e.g. `SCALE_CHAOSDUCK_TO_ZERO`) is set to 1 when running the `test/e2e-tests.sh`, the chaosduck deployment scales the corresponding pod down to 0.
```release-note
```
**Docs**
=> Enable to scale chaosduck down to zero for prow test

test/rekt/features/broker/control_plane.go, test/rekt/features/trigger/client.go, test/rekt/features/trigger/control_plane.go, test/rekt/trigger_test.go
Fixes #
- :gift: Add trigger defaulting webhook tests
- Move some Trigger related reusable code into trigger features package (first 2 commits)
- Check if the filter is defaulted to empty filter
- Check if subscriber namespace is defaulted to trigger namespace
- **Don't** check if [the label](https://github.com/knative/eventing/blob/d8265bb5b08f1bebe61fdecd166f43962b01a0e2/pkg/apis/eventing/v1/trigger_defaults.go#L44) is set. I can't find any usages for that label in the code.
Found some issues in the spec:
- https://github.com/knative/specs/pull/22 --> Default value of `broker` cannot exist as the field is required.
- https://github.com/knative/specs/pull/23 --> There's no mention of Trigger delivering all events if no `filter` defined.
```release-note
```
**Docs**
=> Trigger defaulting webhook tests

test/e2e-common.sh
The current location of checking `$SCALE_CHAOSDUCK_TO_ZERO` is wrongly placed.  If the env variable is set to 1, an error occurs during the test as follows:
```
Error from server (NotFound): deployments.apps "chaosduck" not found
```
This PR is to relocate the code to get called after the `chaosduck` is deployed. The change is tested via the local `phaino` test. If the env variable is set to 1, the `chaosduck` gets scaled to 0 and the following messages are logged as expected.
```
deployment.apps/chaosduck created
deployment.apps/chaosduck scaled
```
- Relocate the code after the `chaosduck` is deployed
```release-note
```
**Docs**
=> Check SCALE_CHAOSDUCK_TO_ZERO after the chaosduck is deployed

pkg/apis/config/defaults_test.go, pkg/apis/messaging/config/channel_defaults_test.go
Increase defaulting test coverage a little for apis/config and apis/messaging/config
Fixes #
- Increase defaulting test coverage a little for apis/config and apis/messaging/config
-
-
```release-note
```
**Docs**
=> Increase defaulting test coverage a little bit for api config

config/core/resources/trigger.yaml
fixes https://github.com/knative/eventing/issues/4932
Minor leftover config that is invalid for the trigger CRD.
=> Triggers do not have conversion webhooks, drop config from CRD

config/core/resources/broker.yaml
fixes https://github.com/knative/eventing/issues/4922
We do not serve any version aside from v1 in the current api. The CRD has extra config that is not used.
=> Brokers do not have conversion webhooks.

cmd/in_memory/channel_controller/main.go, cmd/webhook/main.go, config/channels/in-memory-channel/100-config-event-dispatcher.yaml, config/channels/in-memory-channel/100-namespace.yaml, config/channels/in-memory-channel/200-addressable-resolver-clusterrole.yaml, config/channels/in-memory-channel/200-channelable-manipulator-clusterrole.yaml, config/channels/in-memory-channel/200-controller-clusterrole.yaml, config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml, config/channels/in-memory-channel/200-dispatcher-service.yaml, config/channels/in-memory-channel/200-imc-controller-serviceaccount.yaml, config/channels/in-memory-channel/200-imc-dispatcher-serviceaccount.yaml, config/channels/in-memory-channel/300-in-memory-channel.yaml, config/channels/in-memory-channel/500-controller.yaml, config/channels/in-memory-channel/500-dispatcher.yaml, config/channels/in-memory-channel/README.md, config/channels/in-memory-channel/configmaps/observability.yaml, config/channels/in-memory-channel/configmaps/tracing.yaml, config/channels/in-memory-channel/deployments/controller.yaml, config/channels/in-memory-channel/resources/in-memory-channel.yaml, config/channels/in-memory-channel/roles/controller-clusterrole.yaml, config/channels/in-memory-channel/roles/webhook-role.yaml, config/channels/in-memory-channel/webhooks/defaulting.yaml, config/channels/in-memory-channel/webhooks/placeholder.go, config/channels/in-memory-channel/webhooks/resource-validation.yaml, config/channels/in-memory-channel/webhooks/secret.yaml, hack/generate-yamls.sh, test/e2e-common.sh
Fixes to https://github.com/knative/eventing/issues/4926
- Move webhook for IMC out of core eventing and into the controller for IMC.
- Add a demo for solo demo of IMC without eventing core.
```release-note
InMemoryController can be used independent of Eventing Core.
To downgrade InMemoryController from release 0.23 to 0.22,  the new to v0.23 webhook configuration:
- `kubectl delete ValidatingWebhookConfiguration validation.inmemorychannel.eventing.knative.dev`
- `kubectl delete MutatingWebhookConfiguration inmemorychannel.eventing.knative.dev`
```
=> IMC should work independently of core knative eventing

.github/workflows/kind-e2e.yaml, go.mod
The reconciler-test package is moving to rely on the [1.16 embed package](https://golang.org/pkg/embed/), so we'll need to update to bring in those changes.
- :broom: Update go to 1.16
xref
https://github.com/knative-sandbox/reconciler-test/pull/196
https://github.com/knative-sandbox/.github/pull/108
=> Bump go to 1.16

cmd/webhook/main.go, config/core/resources/apiserversource.yaml, config/core/resources/channel.yaml, config/core/resources/containersource.yaml, config/core/resources/eventtype.yaml, config/core/resources/parallel.yaml, config/core/resources/sequence.yaml, config/core/resources/subscription.yaml
It turns out there was still some config in the webhook that was preventing it from starting after I dropped the conversion config from SinkBinding. This PR just does a pass and cleans just the extra conversion problems up for the release.
Thanks to Ben for finding the problem while writing e2e tests 😄 
/assign @benmoss
=> Drop unused conversion webhook config

config/core/resources/channel.yaml, pkg/apis/duck/v1/channelable_types.go, pkg/apis/eventing/v1/broker_types.go, pkg/apis/messaging/v1/channel_types.go
Fixes https://github.com/knative/eventing/issues/4923
- Update the schema of Channel to the (mostly) unedited version of the schema tool.
- Drop conversion webhook config (an oversight), Channels no longer have conversion webhooks at v1.
=> Update schema of Channel via the schema tool.

cmd/schema/main.go, config/core/resources/subscription.yaml, pkg/apis/messaging/v1/subscription_types.go
Fixes https://github.com/knative/eventing/issues/4943
- Update schema based on schema tool output
- Validated the webhooks are as expected.
=> Subscription resource API validation.

pkg/duck/channel_test.go, pkg/duck/listable_test.go
Fixes https://github.com/knative/eventing/issues/4961
- :gift: Add initial tests for pkg/duck
```release-note
NONE
```
**Docs**
=> duck/test: add initial tests for missing functions

test/conformance/main_test.go, test/e2e/main_test.go
Current conformance and e2e test always collect and upload logs even when tests passed.
It takes long time to report "Test Passed!" and use a lot of strage.
This patch fixes it.
=> Collect logs for knative-eventing-logs only when test failed

test/lib/test_runner.go
Current TearDown() calls runCleanup() before collecting logs.
This could miss some logs and event logs will contains the deletion
logs.
This patch changes to call runCleanup() after collecting logs.
=> Call runCleanup() after collecting logs

test/upgrade/prober/forwarder.go
Serving had deprecated this label in 0.18 and finally dropped it in 0.21, so this is now wrong. We should probably backport this until 0.21.
/assign @cardil
=> Use new label for defining a cluster-local Knative Service

config/channels/in-memory-channel/deployments/controller.yaml, config/core/deployments/pingsource-mt-adapter.yaml, config/sugar/500-controller.yaml
Fixes: #5347
Add podAntiAffinity to:
```release-note
Remaining HA Control Plane pods (via the operator) are now labelled with podAntiAffinity to ensure there isn't a single point of failure.
```
=> Add podAntiAffinity labels to remaining HA control plane pods

config/core/resources/subscription.yaml, pkg/apis/messaging/v1/subscribable_channelable_validation.go, pkg/apis/messaging/v1/subscribable_channelable_validation_test.go, pkg/apis/messaging/v1/subscription_types.go, pkg/apis/messaging/v1/subscription_validation.go, pkg/apis/messaging/v1/subscription_validation_test.go, pkg/reconciler/broker/resources/subscription.go, pkg/reconciler/broker/resources/subscription_test.go, pkg/reconciler/parallel/resources/subscription.go, pkg/reconciler/sequence/resources/subscription.go, pkg/reconciler/subscription/subscription.go, pkg/reconciler/testing/v1/subscription.go, test/lib/resources/eventing.go
Fixes #5411
- :broom: Subscription.Spec.Channel now uses KReference.
- :bug: Now the spec.channel CRD schema is less permissive and matches the supported usage of KReference fields.
```release-note
- :broom: Subscription.Spec.Channel now uses KReference and the spec.channel CRD schema is less permissive and matches the supported usage of KReference fields. Subscription's users creating their resources with YAMLs are not affected.
```
=> Subscription.Spec.Channel now uses KReference

test/config/chaosduck/chaosduck.yaml
Serving has done this as well, the chaosduck killing the webhook causes errors being tracked in https://github.com/knative/pkg/issues/1509
ref: https://github.com/knative/serving/pull/8772
Fixes #5416, probably lots of others 😄
=> Disable chaosduck on the webhook

pkg/adapter/v2/cloudevents.go, pkg/adapter/v2/cloudevents_test.go, pkg/adapter/v2/test/test_client.go
Fixes #5421
- :bug: Fix NPE in the cloudevents adapter
We were testing whether this `protocol.Result` was a `*http.Result` but then even if it wasn't still calling `res.StatusCode`, resulting in a NPE. I don't have enough context on this to understand how this happens *in the wild*, but we are at least seeing it in CI envs.
=> Fix cloudevent adapter panic

test/lib/test_runner.go
Fixes #5388
- :broom: Only upload pod logs on test failures
=> Only upload pod logs logs on failure

.github/workflows/kind-e2e.yaml, config/400-config-experimental-features.yaml, config/core/configmaps/experimental-features.yaml, pkg/apis/experimental/api_validation.go, pkg/apis/experimental/api_validation_test.go, pkg/apis/experimental/features.go, pkg/apis/experimental/features_test.go, pkg/apis/experimental/store.go, pkg/apis/experimental/store_test.go, pkg/apis/experimental/testdata/config-experimental-features.yaml, test/experimental/main_test.go
Details: https://docs.google.com/document/d/1AoH0FyLeuHIg5snrlCKzELQv-NEA6bbjTU2Qv3zlW5k/edit?usp=sharing
- :gift: Store to read the experimental features flags from a specific config map
- :gift: Validator for APIs when using experimental features
- :gift: Scaffolded the directory to add experimental features e2e/conformance tests
```release-note
```
**Docs**
=> Experimental features configuration and validation

docs/experimental-features.md
This is a transcript of https://docs.google.com/document/d/1AoH0FyLeuHIg5snrlCKzELQv-NEA6bbjTU2Qv3zlW5k/edit?usp=sharing.
Blocked by https://github.com/knative/eventing/pull/5214, because it contains some technical details I want to specify in the doc and link the appropriate code. 
- :gift: Experimental features process documentation
=> Experimental features process documentation

pkg/adapter/apiserver/adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go
(Hopefully) fixes a flakiness we have been seeing in the apiserversource rekt tests where the apiserversource receives 0 events.
My theory is that the apiserversource will report ready when the Deployment is ready, but that is no guarantee that the pod has started watching for events, just that it has started. Therefore there's a race where we might trigger an event in our tests (via creating a dummy pod) and expect to see it, but it might have been missed by the source.
By inserting a sleep in the beginning of the main method of the apiserver adapter I'm able to reproduce what we're seeing on GitHub Actions, and this fix works with the sleep in place, so I'm hoping that's faithfully reproducing the issue we're seeing in CI.
```release-note
Fix a race condition with …
```
=> Use a readiness probe to check apiserver adapter readiness

.github/workflows/knative-downstream.yaml
Fixes failing downstream tests from #5447
- :broom: bump go in downstream test job to 1.16
=> Bump downstream job to go 1.16

.github/workflows/knative-downstream.yaml
https://github.com/knative-sandbox/eventing-camel/pull/97
=> Remove camel as a downstream now that is deprecated

test/upgrade/prober/sut/broker.go, test/upgrade/prober/sut/broker_e2e_test.go
Fixes #5441 
- Fixes a #5441 bug, that was hidden by buggy behavior of triggers (#5442)
=> [QE] Don't wait on triggers, before deploying their subscriber

docs/roadmap-2021.md
We have completed this task #4836 (removal of v1beta1 for {eventing, flows, messaging}), so remove it from the roadmap
-
-
-
```release-note
```
**Docs**
=> remove v1beta1 task as it has been done

test/rekt/features/broker/control_plane.go
We realized there was no test that makes use of the DLQ defined in the trigger delivery spec, this adds that variation.
=> add conformance test for trigger delivery DLQ

test/rekt/apiserversource_test.go
Fixes #5375
- remove skip, to see if still flaky
```release-note
```
**Docs**
=> Removing the skip on PingSource rek-test

pkg/channel/fanout/fanout_message_handler.go, pkg/channel/stats_reporter.go
- Expose the func for parsing dispatch execution info to be used by other channel implementations
- Rename metric description for Event dispatch metrics to be more generic
For more check [here](https://github.com/knative-sandbox/eventing-kafka/pull/688) why these changes are needed.
This does not add new func its basically a refactoring.
/cc @slinkydeveloper @matzew
=> Make eventing channel metrics generic enough to be used by other impl

pkg/channel/fanout/fanout_message_handler.go
Expose the dispatch result info struct to be able to be used externally.
Not applicable.
=> Expose dispatch result to be used by other implementations

pkg/broker/filter/filter_handler_test.go, pkg/duck/listable_test.go, pkg/duck/subscriber_test.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/trigger/trigger_test.go, pkg/reconciler/channel/channel_test.go, pkg/reconciler/containersource/containersource_test.go, pkg/reconciler/eventtype/eventtype_test.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go, pkg/reconciler/parallel/parallel_test.go, pkg/reconciler/pingsource/pingsource_test.go, pkg/reconciler/sequence/sequence_test.go, pkg/reconciler/source/crd/crd_test.go, pkg/reconciler/source/duck/controller_test.go, pkg/reconciler/source/duck/duck_test.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/sugar/namespace/namespace_test.go, pkg/reconciler/sugar/trigger/trigger_test.go, pkg/reconciler/testing/listers.go, pkg/reconciler/testing/scheme/scheme.go, pkg/reconciler/testing/v1/factory.go, pkg/reconciler/testing/v1/listers.go, pkg/reconciler/testing/v1beta1/factory.go, pkg/reconciler/testing/v1beta1/listers.go
I also removed some unnecessary `init` functions that modified the k8s global `scheme.Scheme` 
This should help when bumping K8s libs to 1.20
=> setup proper schemes in the fake dynamic client used in unit tests

.github/workflows/kind-e2e.yaml, test/experimental/config/features.yaml, test/experimental/main_test.go
See https://github.com/knative/eventing/pull/5440#discussion_r646951480 for more details
- :broom: Now experimental features main code doesn't modify the feature CM anymore, but the action does it instead
=> Modify experimental features e2e test setup

test/rekt/resources/account_role/role.go, test/rekt/resources/apiserversource/apiserversource.go, test/rekt/resources/broker/broker.go, test/rekt/resources/channel/channel.go, test/rekt/resources/channel_impl/channel_impl.go, test/rekt/resources/containersource/containersource.go, test/rekt/resources/deployment/deployment.go, test/rekt/resources/eventlibrary/eventlibrary.go, test/rekt/resources/flaker/flaker.go, test/rekt/resources/parallel/parallel.go, test/rekt/resources/pingsource/pingsource.go, test/rekt/resources/pod/pod.go, test/rekt/resources/sequence/sequence.go, test/rekt/resources/sinkbinding/sinkbinding.go, test/rekt/resources/subscription/subscription.go, test/rekt/resources/svc/service.go, test/rekt/resources/trigger/trigger.go
This gets us a little closer to being able to make redistributable test binaries. I think what remains is a better story around producing test images, since that's still tied to shelling out to `ko` and relative filepath references.
- :broom: Switch to using Go 1.16's `embed` package for including yaml templates in the rekt suite
=> Use embed package for rekt resource templates

test/e2e-common.sh
Fixes #5482
- :broom: Retry installing eventing when we encounter 502 errors from GitHub
We seem to have been getting a fair number of these. Wget by default does a linear retry starting from 1 second and going up to a maximum of 10 seconds, for a total of 25 retries.
=> Retry install_knative_eventing on 502 errors from GitHub

pkg/channel/fanout/fanout_message_handler.go, pkg/channel/message_dispatcher.go
In https://github.com/knative-sandbox/eventing-kafka/pull/688 the Kafka message needs to be copied to in order to extract the event type (used for labeling metrics) with a transformer. Transformers can be used though in DispatchWithRetries via the execute method, so with this PR we can touch the msg only when we write it and get the info we need back efficiently. 
Implementation example of this can be found [here](https://github.com/openshift-knative/eventing-kafka/pull/234) downstream.
/cc @matzew
=> Use transformers efficiently for extracting info for metrics in Kafka Channel 

test/rekt/features/broker/source_to_sink.go, test/rekt/features/channel/features.go
Lots of flakiness recently, which hopefully this can address.
The idea of this change being that `prober.ReceiverDone()` will poll for the receiver to have received all the sender's events, whereas before we were just doing `prober.AssertReceivedAll`. The latter works fine as long as the time between `SenderDone` and `ReceiverDone` is close to 0, which it seems to be on my machine. However if there's enough of a delay (as I think might be the case in a GitHub Action kind env), the assert will kick in before the receiver and it immediately will fail.
https://github.com/knative/eventing/runs/2817796102?check_suite_focus=true#step:12:4213
https://github.com/knative/eventing/runs/2818732715?check_suite_focus=true#step:12:5736
https://github.com/knative/eventing/runs/2820524189?check_suite_focu …
=> Try to fix more flaky tests

pkg/adapter/v2/cloudevents_test.go
It was not really testing anything but the library. I tried to make it less flaky but couldn't, I don't totally understand something about the way the http listener behaves.
Fixes #5474
=> Remove flaky test

pkg/channel/message_dispatcher.go
Continues #5505 
/assign @slinkydeveloper
=> Pass transformers to executeRequest

config/core/roles/webhook-clusterrole.yaml
Fixes #
(similar to https://github.com/knative/serving/pull/11517)
This patch adds the permission to update `namespaces/finalizers`.
Since knative/pkg#2098 added ownerRef refers to namespace for webhook,
we need this permission. Without it, cluster which has a stricter RBAC
rules gets the following error:
```
cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on:
```
```release-note
knative-eventing-webhook cluster role has update permission for namespaces/finalizers.
```
/cc @markusthoemmes @nak3 
**Docs**
=> Add permission to update namespaces/finalizer

test/conformance/main_test.go, test/e2e/main_test.go, test/e2e_flags.go, test/flags/eventing_environment.go, test/lib/test_runner.go
Fixes #2776
- Append numeric suffix to a common namespace name so as to make the namespace names predictable
- Skip namespaces that already exist until we find a free one (similar to what is used in knative-client repo)
- If ReuseNamespace flag is passed re-use the next namespace which is supposed to exist
The individual tests still create some resources that require admin privileges. This would be resolved in the next PR. Related discussion in https://github.com/knative/eventing/issues/5357
```release-note
```
**Docs**
=> Use test namespaces with numeric suffix

test/conformance/helpers/channel_spec_test_helper.go, test/conformance/helpers/channel_status_subscriber_test_helper.go, test/conformance/helpers/channel_status_test_helper.go
client should be scoped only to the specific subtest, otherwise the generated failures will fail the wrong `*testing.T` object generating a failure like:
```
testing.go:110*: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```
- :bug: Fix bad testing client scoping
- :broom: Name `*testing.T` always `t` to avoid scoping confusion
- :broom: Use `t` when possible for logging, instead of `client.T`
=> Fix subtest client scope

config/core/resources/subscription.yaml, pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/v1/subscription.go, test/experimental/features/kreference_group/sub_channel.go, test/experimental/kreference_group_test.go
Fixes #5086
- :gift: `KReference.Group` now can be used in `Subscription.Spec.Channel` as well
```release-note
:gift: `KReference.Group` now can be used in `Subscription.Spec.Channel` as well
```
**Docs**
=> Support `KReference.Group` in `Subscription.Spec.Channel`

config/channels/in-memory-channel/resources/in-memory-channel.yaml, config/core/configmaps/features.yaml, config/core/resources/broker.yaml, config/core/resources/channel.yaml, config/core/resources/parallel.yaml, config/core/resources/sequence.yaml, config/core/resources/subscription.yaml, docs/eventing-api.md, pkg/apis/duck/v1/delivery_types.go, pkg/apis/duck/v1/delivery_types_test.go, pkg/apis/duck/v1/zz_generated.deepcopy.go, pkg/apis/duck/v1beta1/delivery_conversion.go, pkg/apis/duck/v1beta1/delivery_types.go, pkg/apis/duck/v1beta1/delivery_types_test.go, pkg/apis/duck/v1beta1/zz_generated.deepcopy.go, pkg/apis/feature/flag_names.go
Fixes #5148
- :gift: Added `DeliverySpec.Timeout`
```release-note
Added `DeliverySpec.Timeout`
```
**Docs**
I'm going to create the docs as soon as we implement this in our components 
Spec PR: https://github.com/knative/specs/pull/15
=> Delivery timeout

config/channels/in-memory-channel/roles/controller-clusterrole.yaml
Fixes #
Issues in e2e tests like https://github.com/knative/eventing/runs/2829340913#step:12:5268
Same as https://github.com/knative/eventing/pull/5501 but for IMC, which now is a separate component with its own webhook and stuff.
```release-note
imc-controller cluster role now has update permission for namespaces/finalizers.
```
**Docs**
=> Add IMC webhook the permission to update namespaces/finalizers

pkg/kncloudevents/message_sender.go, pkg/kncloudevents/message_sender_test.go, pkg/kncloudevents/retries.go
Part of https://github.com/knative/eventing/issues/5148
- :gift: Add `RetryConfig.RequestTimeout` to configure the timeout of a single request when using `kncloudevents.HTTPMessageSender`
=> RetryConfig.RequestTimeout to configure the timeout of a single request

config/channels/in-memory-channel/resources/in-memory-channel.yaml, config/core/resources/channel.yaml, pkg/channel/fanout/fanout_message_handler.go, pkg/kncloudevents/message_sender_test.go, pkg/kncloudevents/retries.go, pkg/kncloudevents/retries_test.go, pkg/reconciler/subscription/subscription.go, test/experimental/config/features.yaml, test/experimental/delivery_timeout_test.go, test/experimental/features/delivery_timeout/channel.go
Part of https://github.com/knative/eventing/issues/5148
Depends on #5149 and #5503
- :gift: Glue Delivery.Timeout to RetryConfig.RequestTimeout
- :gift: e2e test for delivery.timeout
=> Glue Delivery.Timeout to RetryConfig.RequestTimeout

pkg/adapter/mtping/pingsource.go, pkg/adapter/mtping/pingsource_test.go, pkg/reconciler/pingsource/pingsource.go, pkg/reconciler/pingsource/pingsource_test.go
- :broom: The PingSource adapter now generates a normal event instead of a warning when the source is not ready. Rename event to PingSourceSkipped 
- :broom: The PingSource adapter now generates a normal event when it has been synchronized 
-
```release-note
- :broom: The PingSource adapter now generates a normal event instead of a warning when the source is not ready. Rename the event to PingSourceSkipped 
- :broom: The PingSource adapter now generates the normal event PingSourceSynchronized when it has been synchronized. 
```
**Docs**
=> [PingSource] Degrade warning to normal event

test/rekt/features/channel/data_plane.go
Fixes #
- `knativehistory` was removed https://github.com/knative/eventing/pull/4366
-
-
see also: https://github.com/knative/specs/pull/27
=> Knativehistory was removed

test/upgrade/prober/configuration.go, test/upgrade/prober/prober.go, test/upgrade/prober/prober_test.go
Fixes #5554
- :broom: Clean up deprecated code from `test/upgrade` package
=> [QE] Removing deprecated code from test/upgrade

pkg/inmemorychannel/message_dispatcher.go, pkg/inmemorychannel/message_dispatcher_test.go
There was a race where the dispatcher was not ready to receive messages
by the time we sent the request. Surfacing the message receiver's Ready
channel helps solve this.
The default quiet period for draining the receiver is 45s, this means
that the TestDispatcher_close test always took 45s.
=> Fix flakiness & slowness of imc dispatcher test

test/rekt/features/apiserversource/data_plane.go
It seems like there's a race in pod creation and the apiserversource listening for it that we sometimes miss it, but we'll always get subsequent update events.
Fixes #5562
=> Make apiserversource test watch for update events

pkg/adapter/apiserver/events/events.go, test/rekt/apiserversource_test.go, test/rekt/features/apiserversource/data_plane.go
Signed-off-by: XinYang <xinydev@gmail.com>
Fixes https://github.com/knative/eventing/issues/2980
* apiServerSource now retries sending events using exponential backoff, 5 times. same as [PingSource](https://github.com/knative/eventing/blob/main/pkg/adapter/mtping/runner.go#L88)
```release-note
```
**Docs**
=> apiServerSource now retries sending events

pkg/broker/filter/stats_reporter.go, pkg/broker/filter/stats_reporter_test.go, pkg/broker/ingress/stats_reporter.go, pkg/broker/ingress/stats_reporter_test.go, pkg/broker/metrics.go, pkg/channel/metrics.go, pkg/channel/stats_reporter.go, pkg/channel/stats_reporter_test.go, pkg/metrics/metrics.go
Part of: https://github.com/knative/pkg/issues/608
- :broom: moves eventing metric constants in knative.dev/pkg to here
~- [ ] **At least 80% unit test coverage**~ N/A
~- [ ] **E2E tests** for any new behavior~ N/A
~- [ ] **Docs PR** for any user-facing impact~ N/A
~- [ ] **Spec PR** for any new API feature~  N/A
~- [ ] **Conformance test** for any change to the spec~ -  N/A
```release-note
NONE
```
**Docs**
=> drop use of upstream knative.dev/pkg/metric eventing keys

pkg/apis/sources/v1/ping_validation.go, pkg/apis/sources/v1/ping_validation_test.go, pkg/apis/sources/v1beta2/ping_validation.go, pkg/apis/sources/v1beta2/ping_validation_test.go
Fixes https://github.com/knative/eventing/issues/5584
-  :bug: reject non-standard @every schedule.
-
-
```release-note
:bug: PingSource schedules starting with `@every` are now properly rejected.
```
**Docs**
=> [PingSource] disable @every

pkg/adapter/v2/cloudevents.go, pkg/adapter/v2/cloudevents_test.go
Fixes #
Due to some refactoring in the v2.4 of cloudevents go sdk, traces were not being generated because of the method thats used to generate the ceClient. I noticed the issue after eventing's v0.22 release when the changes were also done in the cloudevents sdk.
Reference: cloudevents/sdk-go#682
In cloudevents go sdk, opencensus dependencies are removed from v2 (and future releases), so I am using here a method suggested in the issue linked above,  to generate a client with the tracing options.
https://github.com/cloudevents/sdk-go/blob/main/observability/opencensus/v2/client/client.go#L14
- :bug:
This is an example of a scenario when the cloudevent flow is: pingsource -> imc channel -> a ksvc which sends back 503 -> goes to deadletter sink which gives 200:
=> tracing fix for APIServerSource and PingSource

test/lib/client.go
If no kubeconfig is specified, try to use inclusterconfig.
-
-
-
```release-note
```
**Docs**
=> if no kubeconfig use inclusterconfig test

cmd/event_display/main.go, cmd/event_display/main_test.go
- :gift: Adds a health HTTP handler to `event_display` on the `/healthz` endpoint.
This handler responds with "204 No Content" to any request, regardless of the HTTP method. It is meant to be used for probing liveness/readiness.
Background: I observed race conditions on several occasions downstream, in e2e tests that rely on event_display. E.g. an event is sent as soon as the Pod starts, but the CE client isn't started yet 🤷.
I purposely avoided using something from k8s/knative to avoid large imports ("fat binary").
```release-note
Add a health endpoint to `event_display` for enabling readiness probes.
```
**Docs**
=> Add health endpoint to event_display server

README.md
Fixes #5609 README: Link to the working-groups page is wrong
- :bug: Fix bug
Update a link in the README
This is a simple link update in the README.  No code was harmed in the creation of this PR.
```release-note
The link in the README to the Working Groups page was fixed.
```
**Docs**
N/A
=> Fix the link to the Working Group page.

config/core/deployments/controller.yaml, config/core/deployments/pingsource-mt-adapter.yaml, config/core/deployments/webhook.yaml
Just a few security-related tidy-ups from running a [linting tool](https://github.com/stackrox/kube-linter) against the config.
- :broom: set runAsNonRoot=true and allowPrivilegeEscalation=false where missing
- :broom: set readOnlyRootFilesystem=true where possible
- :broom: Add limits to controller (copied the limits from serving controller)
=> Improve security-related config in yaml files

test/lib/client.go
Reverts knative/eventing#5603
We shouldn't need this now that https://github.com/knative/pkg/pull/2197 is in place. The call to `test.BuildClientConfig(configPath, clusterName)` will handle using an in-cluster config if present.
=> Revert "if no kubeconfig use inclusterconfig test"

test/conformance/README.md, test/conformance/broker_tracing_test.go, test/conformance/channel_addressable_resolver_cluster_role_test.go, test/conformance/channel_channelable_manipulator_cluster_role_test.go, test/conformance/channel_crd_metadata_test.go, test/conformance/channel_tracing_test.go, test/conformance/create-namespace-rbac.sh, test/conformance/main_test.go, test/conformance/source_crd_metadata_test.go, test/conformance/source_crd_rbac_test.go, test/conformance/source_crd_registry_test.go, test/lib/creation.go, test/lib/recordevents/resources.go, test/lib/setupclientoptions/sources.go, test/lib/test_runner.go
This partially fixes https://github.com/knative/eventing/issues/5357 but the user is able to run only conformance tests so far.
With the current changes, and by following the readme below, there are 48 tests passing in the conformance test suite.
* move RBAC creation to a common place
* use RBAC that is named according to the test namespace (one set for event logger, and one set for tests using ApiServerSource)
* add `!project_admin` build tag to tests that require cluster-admin permissions (this is mostly because they manipulate CRDs or read configs from knative-eventing namespace and try to do port-forwarding to a pod in Knative Eventing namespace (Tracing))
* helper script for creating NS, SA, Role, RoleBinding
* instructions in readme
* remove unused CreateRBACResourcesForBrokers …
=> Run conformance tests as project admin

pkg/reconciler/source/crd/controller.go
- :bug: Fix bug where we would reconcile non-duck-labelled CRDs on controller startup and controller promotion
On controller promotion (which happens on installation) the source controller is attempting to reconcile all CRDs. This change will do in-memory filtering to exclude those that do not match the filter.
Fixes #5543
xref https://github.com/knative/pkg/pull/2180
=> Only reconcile CRDs labeled with the duck key/value

test/upgrade/prober/prober.go
Fixes #5623
- Tear down test resources only when the test is successful
```release-note
```
**Docs**
=> Prevent teardown in ugprade tests on failure

cmd/event_display/main.go, cmd/event_display/main_test.go, cmd/heartbeats/main.go
- :gift: Event Display and Heartbeats sample programs will emit traces to a trace endpoint if it's configured
```release-note
Event Display and Heartbeats sample programs will emit traces to a trace endpoint if it's configured
```
I refactored the healthz endpoint that @antoineco added to the event display as well, since now `next` is an `ochttp.Handler` and not a `http.ServeMux`. It seems cleaner this way.
=> Add tracing support to eventdisplay and heartbeats

pkg/reconciler/broker/controller.go, pkg/reconciler/broker/controller_test.go
The MT Broker controller wasn't exporting traces, so downstream components would get trace span parents that never show up in your tracing system. 
- :bug: Export traces generated by the mtbroker controller
```release-note
Traces are exported by the mtbroker controller
```
Before:
After:
=> Add trace exporting to mt broker

docs/spec/sources.md
- Make it explicit in the source spec that ceOverrides cannot override required CE attribute. Optional attributes can be specified/overridden. 
-
```release-note
:broom: Clarify the semantic of `ceOverrides`
```
**Docs**
=> Be more explicit about the semantic of ceOverrides

config/core/resources/trigger.yaml, docs/eventing-api.md, pkg/apis/eventing/v1/trigger_types.go, pkg/apis/eventing/v1/zz_generated.deepcopy.go, pkg/reconciler/broker/trigger/trigger.go, pkg/reconciler/testing/v1/trigger.go
I mistakenly hadn't added it to the CRD, so it was just getting dropped by the apiserver as an unknown field.
Semi-fixes #5639, I think there still remains the problem that Broker doesn't have a `status.deadLetterSinkUri` as referenced by the spec
- :bug: Fix DeadLetterSinkURI not persisting to Trigger status
```release-note
:page_facing_up: Fix DeadLetterSinkURI not persisting to Trigger status
```
=> Fix DeadLetterSink on Trigger status

test/lib/client.go
The tests still try to fetch `apiextensions/v1beta1` which is dropped in K8s 1.22 and makes all CRD related tests fail there. That's unnecessary since all our CRDs are `apiextensions/v1` anyway, so let's use the appropriate clients.
/assign @matzew
=> Use v1 CRD clients in tests

pkg/duck/listable.go, pkg/duck/listable_test.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/trigger/controller.go, pkg/reconciler/broker/trigger/trigger_test.go, pkg/reconciler/channel/channel_test.go, pkg/reconciler/channel/controller.go, pkg/reconciler/parallel/controller.go, pkg/reconciler/parallel/parallel_test.go, pkg/reconciler/sequence/controller.go, pkg/reconciler/sequence/sequence_test.go, pkg/reconciler/subscription/controller.go, pkg/reconciler/subscription/subscription_test.go
I noticed in a few places downstream that reconcilers were creating multiple trackers, which seems superfluous. As part of examining the way we use the tracker, I'm experimenting with changing this to just take a tracker.
/kind cleanup
```release-note
NewListableTracker is deprecated, use NewListableTrackerFromTracker instead.
```
**Docs**
=> Create a new ListableTracker ctor taking a tracker.Interface

pkg/reconciler/apiserversource/controller.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/trigger/controller.go, pkg/reconciler/channel/controller.go, pkg/reconciler/eventtype/controller.go, pkg/reconciler/parallel/controller.go, pkg/reconciler/pingsource/controller.go, pkg/reconciler/sequence/controller.go, pkg/reconciler/sinkbinding/controller.go, pkg/reconciler/subscription/controller.go
This tries to make everything that can use the tracker set up on the `controller.Impl`.  In the most extreme case, I think this will consolidate 3 trackers used by one reconciler down to just one.
/kind cleanup
```release-note
```
**Docs**
=> Plumb through using the `controller.Impl` tracker.

pkg/apis/messaging/v1/in_memory_channel_lifecycle.go, pkg/apis/messaging/v1/in_memory_channel_lifecycle_test.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Related to: https://github.com/knative/serving/issues/8004
- :broom: consider `ObservedGeneration` for readiness
```release-note
```
**Docs**
=> [IMC] Always consider ObservedGeneration to determine readiness

pkg/adapter/mtping/controller.go, pkg/adapter/v2/main_injection_test.go, pkg/apis/sources/v1/sinkbinding_lifecycle_test.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/controller.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/trigger/controller.go, pkg/reconciler/broker/trigger/trigger_test.go, pkg/reconciler/channel/controller.go, pkg/reconciler/containersource/controller.go, pkg/reconciler/eventtype/controller.go, pkg/reconciler/inmemorychannel/controller/controller.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/parallel/controller.go, pkg/reconciler/pingsource/controller.go, pkg/reconciler/pingsource/pingsource_test.go, pkg/reconciler/sequence/controller.go, pkg/reconciler/sinkbinding/controller.go, pkg/reconciler/source/crd/controller.go, pkg/reconciler/source/duck/controller.go, pkg/reconciler/subscription/controller.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/sugar/namespace/controller.go, pkg/reconciler/sugar/trigger/controller.go
This spiraled a bit, but overall didn't seem to grow big enough to warrant breaking it up.  The changes:
1. `controller.NewImpl[Full]` -> `controller.NewContext`
1. `resolver.NewURIResolver` -> `resolver.NewURIResolverFromTracker`
1. Remove a dumb log statement we've been copy/pasting around forever.
1. Use `GK` instead of `GVK` filter because it's more versioning tolerant
1. Replace more `GK`-based filters with new-ish strongly typed variant
/kind cleanup
```release-note
```
**Docs**
=> Handful more cleanups

pkg/apis/eventing/v1/broker_lifecycle.go, pkg/apis/eventing/v1/broker_lifecycle_test.go, pkg/reconciler/broker/trigger/trigger.go, test/rekt/features/broker/control_plane.go
Related to: https://github.com/knative/serving/issues/8004
- :broom: consider `ObservedGeneration` for readiness
-
-
```release-note
```
**Docs**
=> [Broker] Always consider ObservedGeneration to determine readiness

config/core/resources/trigger.yaml, test/experimental/delivery_timeout_test.go, test/rekt/features/broker/readyness.go, test/rekt/resources/broker/broker.go, test/rekt/resources/broker/broker.yaml, test/rekt/resources/delivery/delivery.go, test/rekt/resources/trigger/trigger.go, test/rekt/resources/trigger/trigger.yaml
Fixes #5654
- Preserve unknown fields on `trigger.spec.delivery`
- Add test for broker and trigger using `spec.delivery.timeout`
```release-note
Trigger accepts a timeout field in its delivery parameters `spec.delivery.timeout`
```
=> DeliverySpec.Timeout on Broker and Trigger

.github/workflows/kind-e2e.yaml
Trying to reduce our GitHub Action job queue times.
=> drop scheduled github action e2e tests

config/core/configmaps/default-broker.yaml
- :bug: Fix inaccurate description of `default-br-config` inside the `config-br-defaults` ConfigMap.
Rationale: it seems to me like this comment was copied from somewhere else (something related to defaulting Channel objects, maybe)
=> Fix inaccurate description of `default-br-config`

config/core/configmaps/default-broker.yaml
A simple rewording requested by @snneji in https://github.com/knative/docs/pull/4182.
We want the docs and the actual config to be in sync, so I'm submitting this here as well.
/assign @matzew 
(sorry for requiring two PRs for this simple change)
=> Clarify meaning of `default-br-config`

test/e2e_flags.go
as per title
/assign @pierDipi
=> Remove outdated GCP channel from test flag example listing text

test/lib/test_runner.go
The error was:
```
test_runner.go:163: Couldn't initialize clients: unable to find available namespace
```
Changes tested in https://github.com/knative-sandbox/eventing-kafka-broker/pull/1227
Fixes #5700
- Increase MaxNamespaceSkip in test runner
=> Increase MaxNamespaceSkip in test runner

config/post-install/storage-version-migrator.yaml
- :broom: Like Serving, using the `generatedName` for the upgrade job. See: https://github.com/knative/serving/pull/8514/files#r447739231.  Also updating the job name and the labels, like: https://github.com/knative/serving/pull/8580
-
-
```release-note
The post job is now having a generated name, instead of an unmaintained versioned name.
```
**Docs**
=> [post jobs] Like serving use generatedName

.github/workflows/kind-e2e.yaml
Fixes #
- via https://github.com/knative/pkg/pull/2283
-
-
```release-note
```
**Docs**
=> Dropping k8s 1.19 as that is unsupported

.github/workflows/kind-e2e.yaml
- adding k8s 1.22 to CI (similar to https://github.com/knative/serving/pull/11981)
```release-note
```
**Docs**
=> [main] adding 1.22 k8s to GH Actions

pkg/channel/attributes/knative_error.go, pkg/channel/attributes/knative_error_test.go, pkg/channel/message_dispatcher.go, pkg/channel/message_dispatcher_test.go
Fixes #5726 
- :gift: Enhance DLQ CloudEvents with `destination` or `reply` URL in new `knativeerrordest` extension attribute.
```release-note
Dead Letter Sink CloudEvents from certain Channels will include the "ce-knativeerrordest" extension attribute indicating the original destination URL of the failed event.
```
**Docs**
See documentation [PR #4228](https://github.com/knative/docs/pull/4228)
=> Enhance DLQ CloudEvents with destination

config/post-install/clusterrole.yaml, config/post-install/storage-version-migrator.yaml
- adding all resources for NOOP migration - similar to servng
-
-
/hold
wait untl #5664 is merged 
```release-note
```
**Docs**
=> Adding all resources for NOOP migrator

config/channels/in-memory-channel/roles/channelable-manipulator-clusterrole.yaml, config/core/roles/channelable-manipulator-clusterrole.yaml, pkg/reconciler/sequence/sequence.go, pkg/reconciler/sequence/sequence_test.go, test/conformance/helpers/channel_channelable_manipulator_cluster_role_test_helper.go, test/rekt/features/channel/control_plane.go
Fixes #2005
Sequence reconciliation now checks for owned and not deleting channels and subscriptions:
- If a channel is found that is not part of the current used ones, it is deleted.
- If a subscription is found that is not linked to any of the used channels, it is deleted.
- :bug: Fix leaking resources when updating Sequence.
- `channelable-manipulator` roles aggregated using `duck.knative.dev/channelable` need to add `delete` verb so that eventing controller can remove Sequence's non used Channels.
```release-note
Fix issue with Sequence updates leaked resources. In order for the fix to work the provided Channel must include the `delete` verb at the ClusterRole labeled `duck.knative.dev/channelable`.
```
=> Delete non used Step resources at Sequence

pkg/apis/duck/v1/delivery_defaults.go, pkg/apis/duck/v1/delivery_defaults_test.go, pkg/apis/eventing/v1/broker_defaults.go, pkg/apis/eventing/v1/broker_defaults_test.go, pkg/apis/eventing/v1/trigger_defaults.go, pkg/apis/eventing/v1/trigger_defaults_test.go, pkg/apis/messaging/v1/channel_defaults.go, pkg/apis/messaging/v1/in_memory_channel_defaults.go, pkg/apis/messaging/v1/in_memory_channel_defaults_test.go, pkg/apis/messaging/v1/subscription_defaults_test.go
Dead letter sink namespace is not defaulted to the object namespace for:
- Broker
- Trigger
- Channel
- Subscription
Forcing every implementation to define the logic:
"If `spec.delivery.deadLetterSink.ref.namespace` is empty, use `metadata.namespace`"
Fixes #5747
- Default dead letter sink namespace to the object namespace
```release-note
The field `spec.delivery.deadLetterSink.ref.namespace` for Broker, Trigger, Channel and Subscription if not specified is defaulted to `metadata.namespace`.
```
=> Default dead letter sink namespace to the object namespace

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go
Fixes #5771
:gift: Add new feature
- Forward `Prefer: reply` header by default from the broker filter
```release-note
By default, the `Prefer: reply` header is forwarded to Broker Triggers' subscribers
```
**Docs**
=> Forward prefer: reply header for brokers

pkg/apis/messaging/v1/channel_validation.go, pkg/apis/messaging/v1/channel_validation_test.go, pkg/apis/messaging/v1/subscription_validation.go, pkg/apis/messaging/v1/subscription_validation_test.go
Fixes #5776
- :bug: Added missing validation of `DeliverySpec` to Channel and Subscription.
I don't see any mention of what is/isn't validated in the [Specs](https://github.com/knative/specs/blob/main/specs/eventing/overview.md) and would assume that having consistent validation of the DeliverySpec would just be expected?
```release-note
Channel and Subscription will now enforce validation of the "delivery" field.
```
**Docs**
n/a
=> Validate DeliverySpec in Channels & Subscriptions

config/post-install/clusterrole.yaml
Following up on comment here: https://github.com/knative-sandbox/eventing-kafka/pull/903#pullrequestreview-766564824
- remove the `delete` permission, as pointed out in linked PR
```release-note
```
**Docs**
=> [Post-Install] Go with a more minimal set of permissions

config/post-install/clusterrole.yaml
related to https://github.com/knative-sandbox/eventing-kafka/pull/908
- :broom: Adding finalizers and status subresources for storage-version migrator
-
-
```release-note
```
**Docs**
=> Adding finalizers/status subresources to NOOP migrator

config/channels/in-memory-channel/deployments/dispatcher.yaml, pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go, pkg/inmemorychannel/message_dispatcher.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go, pkg/reconciler/inmemorychannel/dispatcher/readiness.go, pkg/reconciler/inmemorychannel/dispatcher/readiness_test.go
Fixes #5422
In-memory Channels are losing messages during dispatchers scaling under load. The cause - dispatcher [goroutine](https://github.com/knative/eventing/blob/release-0.26/pkg/reconciler/inmemorychannel/dispatcher/controller.go#L137-L142) starts a few commands before actual message handlers [reconciliation](https://github.com/knative/eventing/blob/release-0.26/pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go#L90-L102). IMC dispatcher deployment scale up operation creates new pods that are receiving events but cannot handle them as handlers are not ready yet; events are lost with following log message:
```
{"level":"info","ts":"2021-05-20T14:57:34.332Z","logger":"inmemorychannel-dispatcher","caller":"multichannelfanout/multi_channel_fanout_message_handler.go:118","msg":"U …
```
=> IMC dispatcher custom readiness probe

config/core/resources/sequence.yaml, docs/eventing-api.md, pkg/apis/flows/v1/sequence_types.go
Fixes #5069 
- :bug: Sequence's `subscriptionStatuses` and `channelStatuses` status fileds are not required and can be empty when object from `spec.channelTemplate` is not available for any reason.
```release-note
```
**Docs**
=> Sequence: Omit empty channels and subscriptions statuses

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml, config/brokers/mt-channel-broker/deployments/controller.yaml, config/channels/in-memory-channel/deployments/controller.yaml, config/channels/in-memory-channel/deployments/dispatcher.yaml, config/core/deployments/controller.yaml, config/core/deployments/pingsource-mt-adapter.yaml, config/core/deployments/webhook.yaml, config/post-install/storage-version-migrator.yaml, config/sugar/500-controller.yaml, config/tools/appender/appender.yaml, config/tools/event-display/event-display.yaml, config/tools/heartbeats/heartbeats.yaml, config/tools/recordevents/recordevents.yaml, config/tools/websocket-source/websocket-source.yaml
- :broom: Set SecurityContext on all resources installed by core or in-memory controllers.
- This should allow running pods under the `restricted` [Pod Security Standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/)
- [na] **At least 80% unit test coverage**
- [na] **E2E tests** for any new behavior
- [na] **Docs PR** for any user-facing impact
- [na] **Spec PR** for any new API feature
- [na] **Conformance test** for any change to the spec
```release-note
All core Knative Eventing Pods should now be able to run in the restricted pod security standard profile.
```
**Docs**
No docs impact
=> Add securityContext to Knative Eventing core objects

config/channels/in-memory-channel/configmaps/tracing.yaml, config/core/configmaps/tracing.yaml, hack/update-checksums.sh
https://github.com/knative/pkg/pull/2183 followup.
- Remove mentions of stackdriver in config-tracing. 
-
-
```release-note
```
**Docs**
=> Remove unsupported stackdriver tracing backend

go.mod, go.sum, vendor/modules.txt
Fixes #
- Known vulnerabilities in the github.com/miekg/dns package contains Denials of Service vulnerability
- Known vulnerabilities in the github.com/dgrijalva/jwt-go package.
- Both packages are reported to have vulnerabilities by snyk vulnerabilities DB.
```release-note
Upgrade dependencies that contains vulnerabilities in snyk DB
```
**Docs**
=> upgrade miekg and jwt-go to resolve vulnerabilities

pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go
Fixes #5860 
- :broom: When using its Channel DeadLetterSink Ref, Subscriptions are re-resolving the Channels `spec.delivery.deadLetterSink` instead of using the already resolved Channel's `status.deadLetterSinkURI` directly
=> Fix subscription re-resolving channel dlsuri when using it's channel DLS

pkg/apis/messaging/v1/channel_defaults_test.go
See https://github.com/knative/eventing/pull/5906#pullrequestreview-805953656
Fixes https://github.com/knative/eventing/pull/5906#pullrequestreview-805953656
- Add test for default deadLetterSink namespace in generic Channel
```release-note
None
```
**Docs**
```
None
```
/assign @odacremolbap
=> Add test for default deadLetterSink namespace in generic Channel

pkg/utils/headers.go, pkg/utils/headers_test.go
Tracing events using Zipkin/Istio "B3" headers is not possible via the `MessageReceiver` (pkg/channel) which relies on the `PassThroughHeaders()` function (pkg/utils).  This function is filtering them out which makes end-to-end tracing impossible when using Istio/Zipkin.
- :gift: Pass all Zipkin `x-b3-` tracing headers through.
I'm wondering how much of the above might apply as this is internal logic that makes the headers available to Channels/Brokers to choose if/how to handle....
- I think we might want to add it to `SingleEventWithKnativeHeaderHelperForChannelTestHelper()` in `test/conformance/helpers/channel_header_single_event_helper.go` similar to the "knative-xxx" headers?  I've never worked on the Conformance Tests before, though and could use some guidance ; )
- I didn't see …
=> Pass through b3 tracing headers

pkg/kncloudevents/message_sender_test.go
Fixes #5937 
(hopefully - unable to reproduce locally - deducing timing mismatch root cause indirectly ; )
- 🐛 Refactor the `RetryAfterValidationServer` used in test for tracking request intervals.
**Dev Notes**
The test/cases in question have never been seen to fail locally so the root cause is not 100% certain.  The changes to the test are an attempt to address the timing concerns in a more robust manner.
The test case in question involves returning the `Retry-After` headers in the `RFC850` date format.  This formatting drops/truncates milliseconds and thus requires special handling in the test.
The prior implementation was rounding the request receipt times in an effort to work around this.  This is risky as either request (current/previous) might round towards or away from each other …
=> Fix flaky Retry-After Header Test

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go
Fixes #5935
I'm new to the Broker / Trigger / Filter implementations (first PR) so someone with more familiarity should confirm whether the proposed changes are acceptable in the context of the larger ecosystem.  I'm hoping this is an easy net-win, but don't know whether there could be downstream impacts on various channels.  I've tested with the IMC to verify it's working as expected.
The fact that the Filter was not already returning the headers was surprising to me, as it is effectively placing limitations and assumptions on Channel implementations ability to consider headers in a non-broker use case.  Seems very presumptuous to do so - unless it's somewhere in the Channel Spec that I've not seen?  (something like - _"...when you build a Channel you are not allowed to use the response …
=> Enhance Broker Filter to proxy Response Headers

pkg/adapter/apiserver/adapter.go, pkg/adapter/apiserver/adapter_test.go, pkg/adapter/apiserver/delegate.go, pkg/adapter/apiserver/events/events.go, pkg/adapter/apiserver/events/events_test.go
Fixes https://github.com/knative/eventing/issues/5942
- add `apiServerSourceName` in the `resourseDelegate` struct
- using this new field to replace the value of `name` label in the metrics from the objects name to CR's name
=> CR's name in metrics' label for APIServerSource

config/core/resources/sequence.yaml, pkg/reconciler/parallel/parallel.go, pkg/reconciler/sequence/sequence.go, pkg/reconciler/sequence/sequence_test.go, test/rekt/features/parallel/readyness.go, test/rekt/features/sequence/readyness.go, test/rekt/resources/delivery/delivery.go, test/rekt/resources/parallel/parallel.go, test/rekt/resources/parallel/parallel.yaml, test/rekt/resources/parallel/parallel_test.go, test/rekt/resources/sequence/sequence.go, test/rekt/resources/sequence/sequence.yaml, test/rekt/resources/sequence/sequence_test.go, test/rekt/smoke_test.go
Cherry-pick of #5955
```
The Sequence type accepts any Channel spec field in the `spec.channelTemplate.spec` field.
```
=> [release-0.26] Fix channel template spec type for Sequence channel template field

config/core/resources/sequence.yaml, pkg/reconciler/parallel/parallel.go, pkg/reconciler/sequence/sequence.go, pkg/reconciler/sequence/sequence_test.go, test/rekt/features/parallel/readyness.go, test/rekt/features/sequence/readyness.go, test/rekt/resources/delivery/delivery.go, test/rekt/resources/parallel/parallel.go, test/rekt/resources/parallel/parallel.yaml, test/rekt/resources/parallel/parallel_test.go, test/rekt/resources/sequence/sequence.go, test/rekt/resources/sequence/sequence.yaml, test/rekt/resources/sequence/sequence_test.go, test/rekt/smoke_test.go
Cherry-pick of #5955
```
The Sequence type accepts any Channel spec field in the `spec.channelTemplate.spec` field.
```
=> [release-0.25] Fix channel template spec type for Sequence channel template field

pkg/kncloudevents/message_sender_test.go
Fixes #5967 #5968 #5969
The original implementation used a test http server to validate the timing between successive requests in order to validate the correct backoff calculation.  This is rather heavy-weight, and as we've seen is very timing dependent.  Overall the test is sound and on consistent/fast hardware runs reliably, but was complicated to understand and brittle on slower/inconsistent hardware.
This most recent flakiness could easily be resolved by adjusting the test's timings to provide a larger buffer to allow for slower runtimes, but there will always be an inherent "limit" at which test slowness will cause a failure.  Further this results in the tests themselves taking longer.
Therefore, I am rewriting the test in a (hopefully) simpler fashion.  The new test is directly …
=> Refactor Retry-After backoff tests

config/core/resources/sequence.yaml, pkg/reconciler/parallel/parallel.go, pkg/reconciler/sequence/sequence.go, pkg/reconciler/sequence/sequence_test.go, test/rekt/features/parallel/readyness.go, test/rekt/features/sequence/readyness.go, test/rekt/resources/delivery/delivery.go, test/rekt/resources/parallel/parallel.go, test/rekt/resources/parallel/parallel.yaml, test/rekt/resources/parallel/parallel_test.go, test/rekt/resources/sequence/sequence.go, test/rekt/resources/sequence/sequence.yaml, test/rekt/resources/sequence/sequence_test.go, test/rekt/smoke_test.go
Cherry-pick of #5955
```
The Sequence type accepts any Channel spec field in the `spec.channelTemplate.spec` field.
```
=> [release-1.0] Fix channel template spec type for Sequence channel template field

test/lib/client.go, test/lib/test_runner.go
* Makes it possible to run tests in a container within cluster without
specifying/mounting extra kubeconfig
Fixes #5996
-
-
-
```release-note
```
**Docs**
=> Use in-cluster kube config as a fallback

test/rekt/features/channel/features.go
Fixes: #6046
- :bug: Set missing event type on CloudEvent in a test helper
-
-
```release-note
```
**Docs**
=> Set missing event type on CloudEvent in a test helper

test/rekt/channel_test.go, test/rekt/features/channel/features.go
Fixes #
- Test helpers in Rekt features use Subscription's `spec.reply` as `spec.subscriber`. There's a discussion about that here: #5756
- Because these test helpers abuse `spec.reply`, the tests in KafkaChannel repository fail when I run the same tests against KafkaChannel.
- I did these:
- Made the test helpers accept a function that either uses `spec.reply` or `spec.subscriber`
- Test functions (which call helpers) decide which field to use
- Renamed the test functions that abuse `spec.reply` to denote that this is problematic
- When #5756 is enabled, the abusing tests will fail and then we can actually convert them to regression tests that we make sure they fail
This PR will unblock me since when this is merged I can call the helpers with `spec.subscriber` in KafkaChannel repository. …
=> Fix test helpers for subscription that abuse Subscription's `spec.reply`

test/e2e-rekt-tests.sh
A recent run failed with this error:
```
panic: test timed out after 30m0s
```
Fixes #6064
=> Increase timeout for rekt tests

config/core/configmaps/default-broker.yaml, go.mod, test/rekt/broker_test.go, test/rekt/features/broker/control_plane.go, test/rekt/features/broker/delivery.go, test/rekt/resources/broker/broker.go, vendor/modules.txt
Our Broker delivery spec is unset by default, which means that it has literally a
fire-and-forget delivery guarantee because with don't retry.
To make our defaults stronger, we should set a reasonable delivery spec
by default when no delivery spec is specified.
**Default Delivery Spec**
The following delivery spec isn't perfect for every use case by at least
prevents events loss for normal networking errors (eg connection resets, etc)
or during upgrades.
```yaml
delivery:
retry: 10
backoffPolicy: exponential
backoffDelay: PT0.2S
```
The retry period with the above configuration is ~200 seconds long
Fixes #5936
- Change default Broker delivery spec
```release-note
Change default Broker delivery spec
```
**Docs**
```
None
```
=> Change default Broker delivery spec

test/upgrade/prober/wathola/config/logger.go
Change format of logs in wathola-receiver and related components so that we can read timestamps properly and compare them with the ones in wathola-fetcher.
Initial format:
```
{"level":"info","ts":1642064145.2131953,"caller":"event/services.go:102","msg":"finish event received, expecting 1548 event ware propagated"}
```
New format:
```
{"level":"info","ts":"2022-01-13T13:34:20.075868487Z","caller":"event/services.go:102","msg":"finish event received, expecting 38560 event ware propagated"}
```
-
-
-
```release-note
```
**Docs**
=> Use time encoder with human-readable timestamps for upgrade tests

test/upgrade/prober/sender.go
Deleting a deployment doesn't guarantee that the pods associated
with it will be deleted in a reasonable time.
By setting foreground deletion, grace period seconds to 0,
and waiting for the top-level resource to be deleted we effectively know
that the sender is actually stopped.
=> Upgrade test waits for sender deletion

test/config/monitoring/monitoring.yaml
See https://github.com/openzipkin/zipkin/releases/tag/2.23.16
=> Update zipkin image to :2 version to fix the CVE

.github/workflows/kind-e2e.yaml
Fixes #
As per title, remove the CI hook for 1.20 - since we have min of 1.21, as per:
https://github.com/knative/eventing/pull/6065/files
-
-
-
```release-note
```
**Docs**
=> Remove k8s 1.20 APIs

test/upgrade/prober/configuration.go, test/upgrade/prober/prober.go, test/upgrade/prober/verify.go, test/upgrade/prober/wathola/receiver/services.go
Fixes #6045
- do not use FinishedSleep before fetching the report but rather wait for the report to be complete/inactive or eventually time out
- shorter jobWaitTimeout for a single "fetcher" job - the job takes just a couple of seconds to complete, and use 5*jobWaitTimeout for waiting for the complete report
The successful run can be seen [here](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_eventing/6074/pull-knative-eventing-upgrade-tests/1484423708683538432
)
The failed run (with "active" report and timeout) is [here](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_eventing/6074/pull-knative-eventing-upgrade-tests/1484177429432897536)
```release-note
```
**Docs**
=> Prober waits until receiver state != active or timeout

cmd/broker/filter/main.go, pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/eventfilter/subscriptionsapi/all_filter.go, pkg/eventfilter/subscriptionsapi/any_filter.go
MT broker filter pod wasn't correctly populating the context with enabled features.
- :bug: Enable features ConfigMap watching and handle new trigger filters correctly.
=> Enable features configmap watching and fix mt broker filter subscriptions API implementation

config/post-install/storage-version-migrator.yaml
Related to this: https://github.com/knative-sandbox/eventing-kafka/pull/967
also this aligns to what other repositories, like serving do too!
(e.g.: https://github.com/knative/serving/pull/11229 )
=> Fixing the golang path for the migrator

config/core/deployments/controller.yaml
A typo was introduced in #5628.
This PR simply fixes it.
=> Fix value of "component" label for the Eventing Controller

pkg/apis/eventing/v1/trigger_validation.go
- :bug: If parsing the CE SQL expression panics, treat it as an invalid expression.
```release-note
When the `new-trigger-filters` experimental feature is enabled, a bug was fixed where some invalid CE SQL expressions caused a crash eventing webhook. Now those expressions will be considered invalid and the webhook will continue functioning normally. 
```
=> Handle CESQL parsing panics gracefully

pkg/apis/messaging/v1/subscription_validation.go, pkg/apis/messaging/v1/subscription_validation_test.go
Just by creating a subscription in v0.24 and upgrading the cluster to
0.26, the webhook starts throwing errors like this:
```
admission webhook "validation.webhook.eventing.knative.dev" denied the request: validation failed: Immutable fields changed (-old +new): spec
{v1.SubscriptionSpec}.Delivery.DeadLetterSink.Ref.Namespace:
-: ""
+: "kc-broker-v1-dlq"
```
In addition, Subscription.Spec.Delivery wasn't meant to be immutable,
in fact, TriggerSpec.Spec.Delivery is mutable.
Fixes #6138
```release-note
SubscriptionSpec.Delivery is now mutable
```
=> SubscriptionSpec.Delivery is now mutable

.github/workflows/knative-downstream.yaml
Some downstream repositories require Go 1.17.
=> Use Go 1.17 for downstream tests

pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
- State info like `FreeCap[]`, `PodSpread` etc are dependent on placements stored temporarily in `StatefulSetScheduler.reserved`. Reserved must be cleared when new placements are calculated BUT there aren't enough pod replicas (`scheduler.ErrNotEnoughReplicas`) to schedule on. This is because all vreplicas will be re-placed during the next schedule cycle (not just the `pending`) for the new HA scheduler based on the predicates/priorities.
=> Clearing out Scheduler state info when there aren't enough Pods for placements

test/upgrade/prober/sender.go
* There may be blocking calls in the sender which can take longer than
the default period. This prevents the infinite loop from handling the
SIGTERM, resulting in not sending a Stop event.
Fixes #6191
- :bug: Fix bug
- Change the termination grace period from 30 seconds (default) to 5 minutes as there's a vital logic that needs to be executed during shutdown (sending the Stop event)
```release-note
```
**Docs**
=> Set TerminationGracePeriodSecond for wathola-sender to 300 seconds

pkg/scheduler/statefulset/autoscaler.go
Randomly noticing two consecutive calls of syncAutoscale() when there are pending vreplicas. This removes the second trigger.
/cc @lionelvillard
=> Remove a second trigger of the autoscaler

config/core/resources/channel.yaml, docs/eventing-api.md, pkg/apis/messaging/v1/channel_template_types.go, test/rekt/channel_test.go, test/rekt/features/channel/features.go, test/rekt/resources/channel/channel.go, test/rekt/resources/channel/channel_test.go, test/rekt/resources/channel_impl/channel_impl.go
We were dropping the dead letter sink URI in the status of the
`Channel`.
- Set dead letter sink URI in the `Channel` status
```release-note
Set dead letter sink URI in the `Channel` status
```
**Docs**
=> Set dead letter sink URI in the `Channel` status

pkg/reconciler/broker/trigger/controller.go, pkg/reconciler/broker/trigger/controller_test.go, pkg/reconciler/broker/trigger/trigger.go
- :bug: MTChannelBroker was reconciling all triggers, not just triggers pointing to MTChannelBrokers
```release-note
MTChannelBroker can now co-exist with other broker implementations.
```
=> only reconcile triggers that point to the MTChannelBroker class

test/test_images/utils.go
Fixes the comment from https://github.com/knative/eventing/pull/6219#discussion_r837432218
The function `config.JSONToTracingConfig(tracingEnv)` can process empty string in which case it returns a NoopConfig.
-
-
-
```release-note
```
**Docs**
=> Process empty tracing config in test images

test/config/monitoring/monitoring.yaml, test/upgrade/README.md, test/upgrade/prober/config.toml, test/upgrade/prober/configuration.go, test/upgrade/prober/verify.go, test/upgrade/prober/wathola/event/services.go, test/upgrade/prober/wathola/event/tracing.go, test/upgrade/prober/wathola/event/tracing_test.go, test/upgrade/prober/wathola/sender/services.go
This builds on top of https://github.com/knative/eventing/pull/6219
Fixes point 3. from https://github.com/knative/eventing/issues/6145#issuecomment-1039506502
- Add a new Tag called "target" to the Traces that helps differentiate traces from different tests running in parallel.
- Search Zipkin endpoint for traces for Events that were not delivered. Store each trace in a json file separately.
- Step events are stored in `step-<num>.json`. Finished event is stored in `finished.json` under `traces/missed-events/`
- Readme with instructions on how to vizualize saved traces
- Increase memory limits for Zipkin Pod. Increase -Xmx settings for gathering more traces from upgrade tests
```release-note
```
**Docs**
=> Print traces for missed events in upgrade tests

test/e2e-upgrade-tests.sh, test/upgrade/prober/verify.go
Prevent failures such as [this one](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_operator/1018/eventing-upgrade-tests_operator_main/1510363836996128768) when monitoring/tracing is not configured in the system. The problem was recently hit in knative/operator repo.
- log warning when setting up tracing for the upgrade framework and Zipkin is not configured, do not fail the tests
- log warning when downloading traces but Zipkin is disabled
```release-note
```
**Docs**
=> Do not fail upgrade tests if tracing is not configured

test/upgrade/prober/verify.go, test/upgrade/upgrade.go
Fixes #6330
- Do not cleanup Zipkin port-forwarding in every test but only do it once
```release-note
```
**Docs**
=> Cleanup Zipkin tracing only once in upgrade test suite

pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
Fixes #6285
Vreplicas count was not being updated in `s.reserved` map when existing placements vrep count matched the number of vreps in new placement
=> Fix for pod overcommit by one in HA Scheduler

pkg/scheduler/scheduler.go, pkg/scheduler/state/state.go, pkg/scheduler/state/state_test.go, pkg/scheduler/testing/vpod.go
The state accessor is keeping track of nodes and zones based on
the `topology.kubernetes.io/zone` label.
This label isn't always set and there might be clusters that don't
set it, which leads to a non-functional scheduler because it ends
up with `0` nodes and zones.
Instead of using the zone label, we can use node tains to
discard control unschedulable nodes and when there is no zone information
for a _worker_ node, we can assign a default `unknown` zone, which
means that a cluster without zone labels on nodes is considered as
a single-zone cluster (which makes sense since the administrator
doesn't care about availabily zones or failure domains).
PS: while I was doing this, I made a few clean ups
to extract common functions for checking whether a node or a pod
is `"unschedulable"`. …
=> [scheduler] Use node taints for keeping track of available nodes and zones

config/core/deployments/pingsource-mt-adapter.yaml
- :bug: Fix pingsource-mt-adapter crash when initial replica is more than 0
-
-
```release-note
:bug: Fix pingsource-mt-adapter crash when the initial replicas is set to a value other than 0
```
**Docs**
=> Fix pingsource-mt-adapter crash when initial replica is more than 0

pkg/kncloudevents/retries.go, pkg/kncloudevents/retries_test.go
Fixes https://github.com/knative/specs/issues/96
- Adding retry for the `408 - Request Timeout` status code
```release-note
```
**Docs**
=> Adding retry for 408 (Request Timeout) http status code

test/rekt/resources/account_role/role_test.go, test/rekt/resources/apiserversource/apiserversource_test.go, test/rekt/resources/broker/broker_test.go, test/rekt/resources/channel/channel_test.go, test/rekt/resources/channel_impl/channel_impl_test.go, test/rekt/resources/containersource/containersource_test.go, test/rekt/resources/delivery/delivery_test.go, test/rekt/resources/deployment/deployment_test.go, test/rekt/resources/eventlibrary/eventlibrary_test.go, test/rekt/resources/flaker/flaker_test.go, test/rekt/resources/parallel/parallel_test.go, test/rekt/resources/pingsource/pingsource_test.go, test/rekt/resources/pod/pod_test.go, test/rekt/resources/sequence/sequence_test.go, test/rekt/resources/sinkbinding/sinkbinding_test.go, test/rekt/resources/subscription/subscription_test.go, test/rekt/resources/svc/service_test.go, test/rekt/resources/trigger/trigger_test.go
- :broom: remove deprecated api calls
-
-
```release-note
```
**Docs**
=> Remove calling 'ExecuteLocalYAML', b/c it is deprecated

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go
Fixes: https://github.com/knative/eventing/issues/6276
Related: https://github.com/knative-sandbox/eventing-kafka-broker/issues/2122
Multiple `Content-Length` headers were set when there's a reply used.
Specifically, we added support for proxying headers from replies here: https://github.com/knative/eventing/pull/5946
However, not every header is good for proxying.
One example is `Content-Length`.  Having multiple `Content-Length` headers somehow exploitable (not a security expert here).
This PR prevents having multiple `Content-Length` headers. There might be other headers that we shouldn't proxy. I will ask this in a PR comment.
This is very hard to test because when I tell the mock http server to send a specific `Content-Length` with the reply for checking, it responds with `502`. …
=> Only proxy some headers from the reply in MTBroker filter

pkg/reconciler/source/config_watcher.go, pkg/reconciler/source/config_watcher_test.go
- :gift: Propagate `config-logging`'s per-component logging level to sources' adapters
Until now, the `ConfigWatcher` inside `pkg/reconciler/source` was always returning the _global_ `zap-config-logging` from the observed configmap, without taking into account `loglevel.<component>` keys inside that same configmap.
As a user, I would like e.g. 
```yaml
loglevel.pingsource: debug
```
to propagate to the PingSource adapter(s) when the `ConfigWatcher` is initialized with
```go
// https://github.com/knative/eventing/blob/v0.24.0/pkg/reconciler/pingsource/controller.go#L71
WatchConfigurations(ctx, "pingsource", cmw)
```
```release-note
Propagate per-component logging levels to source receive adapters.
```
**Docs**
=> Propagate log level to env var in sources `ConfigWatcher`

test/upgrade/prober/wathola/event/services.go, test/upgrade/prober/wathola/event/types.go, test/upgrade/prober/wathola/sender/services.go
The generic error `event #%d had unavailable period %v which is over down time limit of %v`
doesn't include an actual error that was causing the downtime. 
=> Upgrade test reports last error for unavailability periods

test/markdown-lint-config.rc, test/presubmit-tests.sh
Addresses https://github.com/knative/hack/issues/200
Markdown linting is no longer performed in the presubmit tests, remove lingering related variables and config
=> 🧹 Remove dead variables & config for presubmit markdown checking

pkg/kncloudevents/message_receiver.go, pkg/kncloudevents/message_receiver_test.go
- adds HTTPMessageReceiverOptions for setting read/write timeouts on the HTTPMessageReceiver
=> Adds receiver options for configuring read and write timeouts message receiver

pkg/adapter/apiserver/events/events.go
Partial fix for https://github.com/knative/eventing/issues/5888
This PR is to add some k8s trace attributes to ApiServerSource.
```release-note
Traces generated by ApiServerSource includes some k8s attributes  (`k8s.namespace`, `k8s.name`).
```
=> add k8s trace attribute to ApiServerSource

pkg/broker/ingress/ingress_handler.go, pkg/broker/ingress/ingress_handler_test.go
Fixes #6467
- Ignore trailing slashes for Broker requests
```release-note
MT Broker ignores a trailing slash in the HTTP path.
```
=> Ignore trailing slashes for Broker requests

config/core/configmaps/sugar.yaml
This change updates the `config-sugar` ConfigMap's example.
It suggested to use an empty object `{}` instead of the string `"{}"` which fails to apply correctly on the cluster.
=> chore: update sugar controller ConfigMap example

config/core/configmaps/features.yaml, test/rekt/delivery_timeout_test.go
Part of #5148
- Promote delivery timeout to beta
- Enable feature by default
```release-note
The delivery timeout feature is now beta and enabled by default.
```
=> Promote delivery timeout to beta

config/core/configmaps/features.yaml, docs/eventing-api.md, pkg/apis/messaging/v1/subscription_types.go, test/experimental/config/features.yaml, test/rekt/channel_test.go
Part of #5756
- Promote strict subscriber to beta
- Enable feature by default
```release-note
The strict subscriber feature for Subscription API is now beta and enabled by default.
When the reply field is specified without a subscriber, the reply field won't be used as a subscriber by default.
```
=> Promote strict subscriber to beta

pkg/apis/eventing/v1/trigger_validation.go, pkg/apis/eventing/v1/trigger_validation_test.go
Fixes #6201 
- :bug: Remove the filter restriction of only containing exactly one attribute to align with latest filter specifiction
=> Remove the filter restriction of only containing exactly one attribute

test/e2e/source_sinkbinding_v1_test.go, test/rekt/features/sinkbinding/feature.go, test/rekt/resources/deployment/deployment.go, test/rekt/resources/deployment/deployment.yaml, test/rekt/resources/deployment/deployment_test.go, test/rekt/resources/sinkbinding/sinkbinding.go, test/rekt/sink_binding_test.go, test/rekt/smoke_test.go
- Port SinkbindingV1Deployment test to rekt 
```release-note
Port SinkbindingV1Deployment test to rekt, and fix some complie errors
```
=> Knative port sink binding v1 deployment test to rekt

test/lib/test_runner.go
We're sometimes getting `unable to find available namespace`
in the Kafka repo.
=> Increase max namespace count for e2e test runner

pkg/reconciler/broker/broker.go
- Remove the check for `v1` as that's the main API version
```release-note
```
**Docs**
=> nit: Remove v1 check for ConfigMap

test/rekt/features/broker/control_plane.go, test/rekt/features/broker/topology.go
Fixes #
- Make some broker conformance tests decoratable with broker options
- Added options as variadic so that existing code is not broken
- Motivation: in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2603, I need to create and update the broker with a specific `spec.config`. Here I make some cases accept broker options so that I can pass options that set the `spec.config`.
```release-note
```
**Docs**
=> Make some broker conformance tests decoratable with broker options

pkg/channel/message_receiver.go, pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go, test/rekt/features/channel/data_plane.go
IMC didn't run validation of the received events.
-  Validate events received by InMemoryChannels
- Add conformance test
- [N/A] **Docs PR** for any user-facing impact
- [N/A] **Spec PR** for any new API feature
```release-note
InMemoryChannel receiver validates received events
```
**Docs**
=> InMemoryChannel receiver validates received events

pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority.go, pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority_test.go, pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority.go, pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
Fixes #6523 
- Removed strict check for at least one pod per zone/node in priority plugins: `AvailabilityZonePriority` and `AvailabilityNodePriority`. Reason: Some worker/control nodes may or may not be assigned to any particular zone topology and so will not have pod replicas created in them...
- Return "Requeue" request to controller when there are more vreplicas to place that need autoscaler to scale up, instead of throwing a Scheduler failed error
```release-note
Remove strict check in scorer plugins and respect max skew parameter. Requeue request when no pods available rather than fail scheduler.
```
=> Remove strict check in scorer plugins and respect maxskew, requeue when no pods available rather than fail Scheduler

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml, config/brokers/mt-channel-broker/deployments/controller.yaml, config/channels/in-memory-channel/deployments/controller.yaml, config/channels/in-memory-channel/deployments/dispatcher.yaml, config/core/deployments/controller.yaml, config/core/deployments/pingsource-mt-adapter.yaml, config/core/deployments/webhook.yaml, config/post-install/storage-version-migrator.yaml, config/tools/appender/appender.yaml, config/tools/event-display/event-display.yaml, config/tools/heartbeats/heartbeats.yaml, config/tools/recordevents/recordevents.yaml, config/tools/websocket-source/websocket-source.yaml
Fixes #6532
- :broom:  replacing `all` with `ALL`, since this is the only acceptable string check [here](https://github.com/kubernetes/kubernetes/blob/6dbec8e25592d47fc8a8269c86d4b5fa838d320b/staging/src/k8s.io/pod-security-admission/policy/check_capabilities_restricted.go#30) and [here](https://github.com/kubernetes/kubernetes/blob/6dbec8e25592d47fc8a8269c86d4b5fa838d320b/staging/src/k8s.io/pod-security-admission/policy/check_capabilities_restricted.go#L94).
* :broom: adding seccompProfile to avoid `must set securityContext.seccompProfile.type to "RuntimeDefault"` warnings
-
-
```release-note
:broom: Fixing PodSecurity Policy warnings for restricted environments 
```
**Docs**
=> Enhance PodSecurityPolicy for restricted namespace

test/lib/creation.go
Fixes #6538
- :broom: Update test creation library to also use the `v1` API of CronJob
```release-note
- :broom: Update test creation library to also use the `v1` API of CronJob
```
**Docs**
=> Do not use v1b1 from Cronjobs

pkg/channel/message_dispatcher.go, pkg/channel/message_dispatcher_various_response_benchmark_test.go
Signed-off-by: Teresaliu [changyan.liu@intel.com](mailto:changyan.liu@intel.com)
Fixes #6215 
- Add a benchmark test to test the latency of different responses, including 3 conditions:
1)  ResponseAccepted(2xx) and contained a body
2)  ResponseAccepted(2xx) and body length is 0
3)  ResponseStatusInternalServerError(5xx) and contained a body
In these three testcases, we could see when a 2xx response contains a body, the number of responses is smaller than those body-free 2xx responses and 5xx responses with a body at a same period of time .
- This PR modify the code of executeRequest() to read the body when a 2xx response with a body comes.
And after that, the speed of those three conditions is almost same.
```release-note
The benchmark test construct 3 MessageHander:
1. …
```
=> Fix error bodyofMessage in executeRequest not read

go.mod, go.sum, vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/client.go, vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/observability_service.go, vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/observable.go, vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/reporter.go, vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/trace_attributes.go, vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/http/http.go, vendor/github.com/cloudevents/sdk-go/v2/alias.go, vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go, vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go, vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go, vendor/modules.txt
=> Bump cloudevents/sdk-go to v2.12

.github/workflows/kind-e2e.yaml, config/brokers/mt-channel-broker/deployments/hpa.yaml, config/core/deployments/webhook-hpa.yaml
Fixes #6332
- Using HorizontalPodAutoscaler `v2`, since `v2beta2` is being _deprecated_ in k8s 1.23 (our next min-version)
```release-note
The HorizontalPodAutoscaler manifests have been updated to v2, which is available with k8s 1.23+
```
**Docs**
=> Using HorizontalPodAutoscaler v2

pkg/reconciler/sugar/namespace/namespace_test.go, pkg/reconciler/sugar/resources/broker.go, pkg/reconciler/sugar/resources/broker_test.go, pkg/reconciler/sugar/trigger/trigger_test.go, pkg/reconciler/testing/v1/factory.go, pkg/reconciler/testing/v1/reactor.go
- 🐛 Fixes issue where sugar controller was forcing Broker class.
To reproduce:
- Update the defaults ConfigMap `config-br-defaults` to use `RabbitMQBroker` along with an appropriate broker config.
- Enable sugar controller
- Create a new namespace or trigger with the appropriate label
Expected:
- default broker is created with configuration and class matching the defaults config map
Actual:
- default broker is created with the RabbitMQ broker config but with the class still set to `MTChannelBasedBroker`
```release-note
Fixes issue with sugar controller always setting the broker class to MTChannelBasedBroker instead of using the defaults ConfigMap
```
Relies on [this](https://github.com/knative/pkg/pull/2585) pkg PR to be merged and integrated for tests to pass
/hold until pkg merge
=> Sugar controller doesn't enforce Broker class

cmd/controller/main.go, config/core/deployments/controller.yaml
Partial fix for https://github.com/knative/pkg/issues/1048
Having both readiness and liveness probes is good kube practice.
For now the implementation relies on a simple http server we can improve later as needed.
-  :gift: Add readiness and liveness probes in Knative Eventing controller
-
-
- [x ] **At least 80% unit test coverage**
- [x ] **E2E tests** for any new behavior
- [x ] **Docs PR** for any user-facing impact
- [ x] **Spec PR** for any new API feature
- [x ] **Conformance test** for any change to the spec
```release-note
:gift: Add readiness and liveness probes in Knative Eventing controller
```
**Docs**
=> Add readiness and liveness probes in controller

pkg/channel/message_dispatcher.go, pkg/channel/message_dispatcher_test.go, test/rekt/channel_test.go, test/rekt/features/channel/features.go
Fixes #6547 
Signed-off-by: Teresaliu [changyan.liu@intel.com](changyan.liu@intel.com)
- Avoiding "invalid" HTTP header values for CE extension to encode channel's response body
- Update unit and e2e tests
- Add corresponding rekt test
```release-note
```
**Docs**
=> Doing base64 encode in channel's responseBody

pkg/scheduler/OWNERS
Ansu is the initial contributor of the scheduler and every time
I need to patch this component, I can't think of a better person
to ask for a review.
=> Add Ansu as scheduler approver

pkg/scheduler/state/state.go, pkg/scheduler/state/state_test.go, pkg/scheduler/statefulset/scheduler.go
When the autoscaler tries to scale up the number of the statefulset
pods but some pods are unschedulable due to missing resources
in the cluster, the scheduler ends up bringing every already
scheduled resource (vpod) to Ready=False since pending pods have
no nodes assigned (Pod.Spec.NodeName is empty), so when the
scheduler tries to build the state of the system, it will try
to get the empty name node which doesn't ever exist.
To reproduce this issue, we can use this command on a small
cluster (on KinD is consistently reproducible since it's
very unlikely that KinD locally can schedule hundreds of pods):
```
seq 100 | xargs -I{} sh -c "kubectl create ns {}; kubectl apply -f ../kafka-source-example.yaml -n {}"
```
where `kafka-source-example.yaml` is:
```
apiVersion: …
```
=> [Scheduler] Handle permanent pending pods

test/upgrade/prober/verify.go
Exporting too many traces may lead to test suite timeouts and the root cause should be common and visible with fewer event traces.
```release-note
```
**Docs**
=> Decrease exportTraceLimit to 100

pkg/broker/err_extension.go, pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/channel/message_dispatcher.go, pkg/inmemorychannel/message_dispatcher_test.go, test/rekt/broker_test.go, test/rekt/channel_test.go, test/rekt/features/broker/feature.go, test/rekt/features/channel/features.go
Fixes #6541  
- Add Reconciler Test of Channel to test failer extensions metadata
- Add failed events extensions `knativeerrordest, knativeerrordata,knativeerrorcode` to MTChannelBroker and corresponding Reconciler Test to Broker
```release-note
Add contextual information on why the message landed in deadletter sink of the MTChannel-based Broker or its Triggers.
```
**Docs**
=> Knative enhance failed events extensions in mt channel broker

.github/workflows/kind-e2e.yaml
- :broom: Remove the 1.23 test runs, due to bump to 1.24: https://github.com/knative/eventing/pull/6611/files#diff-ebd3ca3b212bf9c35533ed0560979731f6b03dff9cc1128554bb37f6453c07b7R36
**NEXT:** In a _separate_ PR I will update the `kind` itself to latest, but to keep PRs small and focused, this just removes the old k8s version
```release-note
```
**Docs**
=> Remove k8s 1.23 kind

cmd/mtping/main.go, pkg/adapter/v2/configurator_configmap.go, pkg/adapter/v2/main.go
The PingSource was not exporting metrics on the advertised port
on the Deployment (metrics, 9090) but it was using 9092 (the 
eventing default).
In addition, any component using the adapter/v2 code suffers
from unexported metrics because the exporter was created
only after an update to `config-observability` since
the watcher was started before the observer was registered as
side effect of calling `CreateLogger`.
Fixes #
- Fix PingSource adapter metrics
```release-note
Fix PingSource adapter metrics
```
=> Fix PingSource adapter metrics

cmd/webhook/main.go, cmd/webhook/main_test.go, config/core/roles/webhook-clusterrole.yaml, pkg/reconciler/sinkbinding/controller.go
Fixes #6399
* :bug: Register schemas in webhooks too (d6f5a7183121643cce3e365cba3182dc751f77d3)
* :bug: Setup event recorder in sinkbinding controller to use watches (97f44368f40fa9042ef5dca60b4bd6e0aba5ada7)
```release-note
```
**How to verify:**
* Follow the steps from https://github.com/knative/eventing/issues/6399#issuecomment-1323638543 with the changes from this PR
* Check the webhook logs for not reporting the `Could not construct reference to` error
```
$ k -n knative-eventing logs eventing-webhook-7588fd57c9-jc687 | grep -i "construct"
$
```
* Check the event got created instead:
```
$k -n foobar get event -w | grep -i address                                         
0s          Warning   InternalError            sinkbinding/sender            address not set for …
```
=> Register schemas in webhooks too

test/upgrade/prober/configuration.go, test/upgrade/prober/verify.go
The number of exported Zipkin traces for each test is now configurable. The default value is 100 but can be configured in this way: 
```
export EVENTING_UPGRADE_TESTS_TRACEEXPORTLIMIT=XX
```
When there are multiple upgrade tests running in parallel and there are duplicate events in each of them collecting traces might take too long and cause test suite timeouts.
-
```release-note
```
**Docs**
=> Configurable trace export limit for upgrade tests

test/rekt/resources/trigger/trigger.go
- :broom: Removes deprecated `WithAnnotation` from `Trigger` reconciler test lib, generally better option here to use is `WithAnnotations` which does honor `ceOverrides` anyways
```release-note
Removes deprecated `WithAnnotation` from `Trigger` reconciler test lib, generally better option here to use is `WithAnnotations` which does honor `ceOverrides` anyways
```
**Docs**
=> Removing deprecated and broken code for WithAnnotation

test/rekt/resources/broker/broker.go, test/rekt/resources/broker/broker.yaml, test/rekt/resources/broker/broker_test.go
- Enhancing broker test framework for allowing different namespace for the config
```release-note
```
**Docs**
=> Allowing an override of the namespace for the brokers config type

test/upgrade/upgrade_test.go
Projects are now supposed to use Configuration.LogConfig, see [link](https://github.com/knative/pkg/blob/main/test/upgrade/types.go#L120)
I would like to remove Configuration.Log in the upcoming https://github.com/knative/pkg/pull/2663
-
-
-
```release-note
```
**Docs**
=> Do not use deprecated Configuration.Log in upgrade tests

test/upgrade/prober/verify.go
* Print "Fetching trace ..." at DEBUG level because we already print another message "Exporting trace into /file/path/step-XXXX.json" at INFO level which is sufficient.
* Print "Duplicate events: event #XXXX received X times, but should be received only once" at INFO level to get rid of the stacktrace that is printed at WARN level. This stack trace is really noisy and not useful at all. And with tens to hundreds of duplicate events it makes the logs really long.
This will reduce the log in the following way for each duplicate event:
Before:
```
2023-01-19T09:54:40.013-0500	WARN	prober/verify.go:99	Duplicate events: event #4278 received 2 times, but should be received only once
knative.dev/eventing/test/upgrade/prober.(*prober).Verify …
```
=> Reduce log noise in upgrade tests

test/lib/logexporter.go, test/upgrade/prober/continual.go, test/upgrade/upgrade_test.go, vendor/knative.dev/pkg/test/logstream/v2/interface.go, vendor/knative.dev/pkg/test/logstream/v2/stream.go, vendor/modules.txt
Enables a log stream for pods from the system namespace. For upgrade tests it is important to have logs from pods "before" and "after" upgrade, not just after upgrade.
This will also be reused in [eventing-kafka-broker](https://github.com/knative-sandbox/eventing-kafka-broker/pull/2884)
- Stream logs from system namespace pods and store them in files under "knative-eventing-logs" directory
- Re-use logstream stuff from knative.dev/pkg
```release-note
```
**Docs**
=> Log stream from system namespace in upgrade tests

config/core/resources/apiserversource.yaml, docs/eventing-api.md, pkg/adapter/apiserver/adapter.go, pkg/adapter/apiserver/adapter_test.go, pkg/adapter/apiserver/config.go, pkg/apis/sources/v1/apiserver_types.go, pkg/apis/sources/v1/zz_generated.deepcopy.go, pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/controller.go, pkg/reconciler/apiserversource/controller_test.go, pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go, pkg/reconciler/testing/v1/apiserversouce.go, test/rekt/apiserversource_test.go, test/rekt/features/apiserversource/data_plane.go, test/rekt/resources/apiserversource/apiserversource.go, test/rekt/resources/apiserversource/apiserversource.yaml, test/rekt/resources/apiserversource/apiserversource_test.go, test/rekt/resources/namespace/namespace.go, test/rekt/resources/namespace/namespace.yaml, test/rekt/resources/namespace/namespace_test.go, test/rekt/resources/pod/pod.go, test/rekt/resources/pod/pod.yaml, test/rekt/resources/pod/pod_test.go
Fixes #6644 
- 🎁 ApiServerSource can specify a selector to target one or more namespaces. If the selector is missing, it will default to targeting the namespace in which the source resides
API changes (additive):
- `spec.namespaceSelector`: A label selector to identify namespaces to track
-  `status.namespaces`: A list of namespaces currently being tracked by the source
```release-note
📄 ApiServerSource can specify a selector to target one or more namespaces. If the selector is missing, it will default to targeting the namespace in which the source resides
```
**Docs**
Docs to follow once the behaviour is finalized and approved.
=> APIServerSource with selector to target namespaces

pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/v1/subscription.go
Fixes #6636 
In `Subscription`'s reconcile loops, physical channel is updated by `PATCH` logic. It occurs broken sync between the channel and subscriptions.
For ensuring a resource version which can check whether conflict occurred or not, change to `Update` with RetryOnConflict.
- Change Patch to Update
- Use RetryOnConflict
- Change condition when sync failed
```release-note
```
**Docs**
If there are some users who are already affected by the bug related to this issue, this PR cannot fix them. What should we do?
=> Change subscription patch logic to ensure resource version

pkg/scheduler/statefulset/scheduler.go
- set the logging for schedule failung to fetch resource (e.g. statefulset) to debug.
In downstream usage on "kafka broker", I am seeing lots of log info msgs, like these:
```
kafka-controller-6699c67795-scdkn controller {"level":"info","ts":"2023-01-26T07:44:09.549Z","logger":"kafka-broker-controller","caller":"state/state.go:178","msg":"failed to get statefulset","commit":"1199efa-dirty","knative.dev/pod":"kafka-controller-6699c67795-scdkn","error":"statefulsets.apps \"kafka-source-dispatcher\" not found"}
kafka-controller-6699c67795-scdkn controller {"level":"info","ts":"2023-01-26T07:44:09.549Z","logger":"kafka-broker-controller","caller":"statefulset/autoscaler.go:122","msg":"error while refreshing scheduler state (will …
```
=> Set scheduler logging to debug

go.mod, go.sum, pkg/apis/messaging/v1/subscription_defaults.go, pkg/apis/messaging/v1/subscription_defaults_test.go, pkg/reconciler/subscription/subscription.go, vendor/knative.dev/pkg/apis/duck/v1/destination.go, vendor/modules.txt
Default the subscriptions subscriber and reply in webhook. This will set (with the current implementation of `destination.SetDefaults()`) the namespace of the subscriber/reply to the namespace of the subscription.
WIP, as we can switch to nil safe `destination.SetDefaults()` method in [pkg/apis/messaging/v1/subscription_defaults.go](https://github.com/creydr/knative-eventing/blob/439006fcb60ba9d5ba11364f31f87b15201453b3/pkg/apis/messaging/v1/subscription_defaults.go#L38-L44), after knative/pkg#2670 merged
=> Default a subscriptions subscriber and reply in webhook

pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/v1/subscription.go
This reverts commit 4d6e1fc98d1a98c304566fa19843bcbb3fdea658.
It has the side effect of dropping channel spec fields, so even immutable
fields are dropped, hence channels will fail to get updated.
We need to re-evalute the approach to fix the orginal issue:
https://github.com/knative/eventing/issues/6636, patch will always
have edge cases that will lead the original bug because subscriptions
are reconciled independently from each other (and potentially by 
multiple controller replicas), so update is the only way of having
concurrency control at the resource level but we should make sure
that we're preserving unknown fields when updating channelables.
=> Revert "Change subscription patch logic to ensure resource version (#6670)

pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/v1/subscription.go
This reverts commit https://github.com/knative/eventing/commit/4d6e1fc98d1a98c304566fa19843bcbb3fdea658.
It has the side effect of dropping channel spec fields, so even immutable
fields are dropped, hence channels will fail to get updated.
We need to re-evalute the approach to fix the orginal issue:
https://github.com/knative/eventing/issues/6636, patch will always
have edge cases that will lead the original bug because subscriptions
are reconciled independently from each other (and potentially by
multiple controller replicas), so update is the only way of having
concurrency control at the resource level but we should make sure
that we're preserving unknown fields when updating channelables.
=> [release-1.9] Revert "Change subscription patch logic to ensure resource version (#6670)

config/core/resources/broker.yaml
Fixes #6721 
- :gift: Add new feature
- `kubectl get -o wide` now also shows `CLASS` for broker
```
» kubectl -n knative-eventing apply -f test-broker.yaml
broker.eventing.knative.dev/my-default-broker created
» kubectl -n knative-eventing get brokers.eventing.knative.dev -o wide 
NAME                URL   AGE   READY   REASON                  CLASS
my-default-broker         13s   False   ChannelTemplateFailed   MTChannelBasedBroker
```
test-broker.yaml
```yaml
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
name: my-default-broker
spec: {}
```
```release-note
```
**Docs**
=> Added Broker class in `kubectl get -o wide`

pkg/scheduler/state/state.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
To detect whether scheduling is already done, it uses the
existing placements fields, however, if one or more placements
are for unschedulable pods, it won't reschedule them.
See added unit tests for example scenarios.
=> Scheduler doesn't reschedule vpods that are scheduled on unscehdulable pods

test/rekt/resources/broker/broker.go
- :gift: Add a function for the broker rekt tests to check if a broker has a `NotReady` condition
=> Add function to check if a broker resource is `NotReady`

pkg/scheduler/statefulset/autoscaler.go, pkg/scheduler/statefulset/autoscaler_test.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
In order to make https://github.com/knative/eventing/issues/6732 we need a way of injecting more configuration down to the scheduler and autoscaler, so in this PR I'm extracting a new function to create a scheduler with `statefulset.New` but with a single `Config` parameter, this will allow us adding configurations without making breaking API changes.
=> Extract scheduler config in a dedicate struct instead of many parameters

cmd/event_display/main.go, cmd/event_display/main_test.go
This allows debugging deserialization issues for services.
When `REQUEST_LOGGING_ENABLED` is set to true, we get a log line like:
```
2023/02/21 12:19:08 {
"method": "POST",
"URL": {
"Scheme": "https",
"Opaque": "",
"User": null,
"Host": "localhost",
"Path": "",
"RawPath": "",
"OmitHost": false,
"ForceQuery": false,
"RawQuery": "",
"Fragment": "",
"RawFragment": ""
},
"proto": "HTTP/1.1",
"protoMajor": 1,
"protoMinor": 1,
"headers": {
"Content-Type": [
"application/json"
]
},
"body": "hello",
"contentLength": 5,
"host": "localhost",
"remoteAddr": "",
"requestURI": ""
}
```
The feature is explicitly discouraged for production usage with a log line due to the possibility of logging sensitive information, even though event display is not that useful for production
=> Allow event display to log requests

pkg/channel/message_dispatcher.go, pkg/channel/message_dispatcher_test.go, test/rekt/broker_test.go, test/rekt/features/broker/feature.go
- 🐛 Fixes an issue where a Cloud Event in a response from a sink was truncated to 1024 bytes
```release-note
🐛 Fixes an issue where a Cloud Event in a response from a sink was truncated to 1024 bytes
```
Before the changes in #6521, the response was being truncated when an error occurred. That felt wrong as well, so with these changes, response body isn't truncated regardless of status.
=> Fixes issue where a CE response is truncated

docs/eventing-api.md, pkg/apis/duck/v1/channelable_types.go, pkg/apis/duck/v1/zz_generated.deepcopy.go
Fixes #6720 
-  :wastebasket: Remove feature or internal logic
- removes deprecated `DeadLetterChannel` https://github.com/knative/eventing/blob/main/pkg/apis/duck/v1/channelable_types.go#L70-L74
```release-note
removes deprecated DeadLetterChannel in favor of DeliveryStatus
```
**Docs**
=> Removes the deprecated DeadLetterChannel in ChannelableStatus

pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go
The reasoning as per the comment was that you cannot have istio
sidecar when it needs to talk with the API Server but that is not
true, pods can talk to the API Server even with istio sidecar
injected.
For example, I'm injecting a sidecar in eventing-istio for
PingSource adapter or Kafka controller and they both work
fine.
Part of #6596 
- Set sidecar.istio.io/inject to true for API Server Source adapters
```release-note
Set sidecar.istio.io/inject to true for API Server Source adapter pods.
```
=> No reason for API ServerSource adapter to not inject istio sidecar

pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Fixes #6787
- similar to our static manifests we set the required SC bits (see: https://github.com/knative/eventing/pull/6533), except SeccompProfile
```release-note
SecurityContext settings for ApiServerSource's Receive Adapter's container/deployment 
```
**Docs**
=> SC settings for ApiServerSource's Receive Adapter's container/deployment 

test/rekt/features/containersource/features.go, test/rekt/resources/containersource/containersource.yaml
It was sending 
```
apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
name: containersource-zktkstuz
namespace: test-rtirtpit
spec:
ceOverrides:
extensions:
wow: so extended
sink:
ref:
kind: Service
namespace: test-rtirtpit
name: sink-rematrro
apiVersion: v1
template:
metadata:
annotations:
sidecar.istio.io/inject: true
sidecar.istio.io/rewriteAppHTTPProbers: true
spec:
containers:
- name: heartbeats
image: quay.io/pierdipi/heartbeats@sha256:41da51559b82b577372291ca8b63efc5529b14e00d0d988440986d55eb0d8f05
imagePullPolicy: IfNotPresent
args:
- <no value>
env:
- name: POD_NAME
value: heartbeats
- name: POD_NAMESPACE
value: test-rtirtpit
```
which produces:
```
mutation failed: cannot decode incoming new object: json: cannot unmarshal bool into Go struct field …
```
=> Fix pod annotations in containersource template

test/rekt/features/broker/control_plane.go
In the "old" conformance tests for the broker, we had a check to ensure that the `broker.spec.config` is immutable:
https://github.com/knative/eventing/blob/df2287d3c4198aa7c275e174cc494226763c0ddd/test/conformance/helpers/broker_control_plane_test_helper.go#L74-L76
This is missing in the rekt based conformance tests for the broker. This PR addresses it and adds a test to the rekt base conformance tests.
- :gift: Add rekt based broker conformance test to test `broker.spec.config` of a ready broker is immutable
=> Add rekt based broker conformance test to ensure `broker.spec.config` is immutable

cmd/heartbeats/main.go, test/rekt/features/sinkbinding/feature.go
When running with an istio sidecar and
within a job, the job never completes until
all containers shutdown successfully.
=> Heartbeats: quit istio proxy when running in a job

pkg/scheduler/statefulset/autoscaler.go, pkg/scheduler/statefulset/autoscaler_test.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
Fixes #6732 
The autoscaler runs in every controller replica [1], it tries
to scale down on every replica after the given refresh period,
and sometimes the 2 replicas don't agree on which value to use
for the new replicas since the state is lister/cache based,
leading to a too fast scale up or down behavior or sometime
not converging.
(also because of https://github.com/knative/eventing/issues/6733)
Implementations should be using https://github.com/knative/pkg/issues/2675
for enabling leader-aware autoscaler. (PR https://github.com/knative/pkg/pull/2688)
[1]
https://github.com/knative/eventing/blob/1092472f440586099d6a5cbf1d3234bb36431af4/pkg/scheduler/statefulset/autoscaler.go#L85-L103
=> Make autoscaler leader aware

pkg/apis/doc.go
Context https://github.com/ahmetb/gen-crd-api-reference-docs/issues/61
This fixes the `knative/pkg` downstream tests (which is using go1.20)
=> fix api docs generation with go1.20

config/core/configmaps/features.yaml, pkg/apis/feature/features.go, pkg/apis/feature/flag_names.go
Fixes #6836 
-
-
-
```release-note
```
**Docs**
=> Add transport-encryption feature flag

test/rekt/features/channel/features.go
Channel must be ready before starting to send events. 
Subscription must be ready before starting to send events.
=> Fix ChannelChain test lifecyle

.github/workflows/kind-e2e.yaml, go.mod, pkg/adapter/v2/cloudevents.go, pkg/adapter/v2/cloudevents_test.go, pkg/adapter/v2/config.go, pkg/adapter/v2/config_test.go, pkg/eventingtls/eventingtls.go, pkg/eventingtls/eventingtls_test.go, pkg/eventingtls/eventingtlstesting/eventingtlstesting.go, pkg/kncloudevents/message_receiver.go, vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/fake/fake.go, vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/fake/fake.go, vendor/modules.txt
This patch adds support for the `K_CA_CERTS` environment variable for the source adapter library.
This will enable the APIServerSource data plane and other sources leveraging adapter/v2 to work with the Eventing TLS feature.
Fixes: #6847
=> Eventing TLS: support `K_CA_CERTS` in adapter/v2

.github/workflows/kind-e2e.yaml, .github/workflows/knative-downstream.yaml
As per title, similar to: https://github.com/knative-sandbox/reconciler-test/commit/8e242fe2239f0bfff31bee0ca15b962c8c0987df
=> Bump Go to 1.20 in GH workflows

pkg/adapter/mtping/adapter.go, pkg/adapter/mtping/runner.go, pkg/adapter/mtping/runner_test.go, pkg/adapter/v2/cloudevents.go, pkg/adapter/v2/cloudevents_test.go, pkg/adapter/v2/main.go, pkg/adapter/v2/test/test_client.go, pkg/metrics/source/stats_reporter.go
This is just a refactoring to make it easier to implement Eventing TLS
Part of #6879
=> Refactor PingSource adapter client creation

pkg/channel/message_dispatcher.go, pkg/channel/message_dispatcher_test.go, test/rekt/features/channel/features.go
Sanitizing the HTTP body was added as a measure to try to handle as many HTTP body as possible, now that we're base64 encoding the error body [1], it is not necessary anymore, it just breaks any consumer trying to use such info.
[1] https://github.com/knative/eventing/pull/6542
=> Remove sanitize HTTP body for `knativeerrordata` extension

cmd/webhook/main.go, config/core/resources/eventtype.yaml, pkg/apis/eventing/v1beta1/eventtype_conversion.go
Fixes https://github.com/knative/eventing/issues/6891 
Fixes https://github.com/knative/eventing/issues/6892
- Adding v1beta2 version for EventType and type conversion
```release-note
Adding v1beta2 version for EventType and type conversion
```
**Docs**
=> More EventType v1beta2 work

.github/workflows/knative-downstream.yaml
eventing-natss tests are always failing.
=> Remove eventing-natss from downstream tests

pkg/adapter/v2/config.go, pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Fixes #6894
The ApiServerSource controller now sets the K_CA_CERTS environment variable when creating the adapter and the sink has CACerts defined.
- Added K_CA_CERTS env variable support
- Updated tests
```release-note
The ApiServerSource controller now sets the K_CA_CERTS environment variable when creating the adapter and the sink has CACerts defined.
```
**Docs**
=> Eventing TLS: Added Support for setting K_CA_CERTS in the ApiServerSource controller for the adapter

.github/workflows/kind-e2e.yaml
- 🎁 Install `ko` using `ko-build/setup-ko@v0.6`
- ⚡ This will ensure you use the latest and greatest version of `ko`
- 🗑️ Currently you're using [`v0.6.0`](https://github.com/ko-build/ko/releases/tag/v0.6.0), which is 2 1/2 years old
```release-note
NONE
```
**Docs**
=> Install ko using setup-ko in kind e2e tests

pkg/apis/feature/features.go, pkg/eventingtls/servermanager.go, pkg/eventingtls/servermanager_test.go, pkg/kncloudevents/message_receiver.go, pkg/kncloudevents/message_receiver_test.go
Fixes #6899 
ServerManager takes a http receiver, https receiver, handler and a config map watcher. 
The handle will be invoked when the respective server should be available. Otherwise, the handler is swapped to one that returns a 404 (retryable error in case the request is made during a configuration switch)
=> Adds ServerManager. Supports http/https message receivers

pkg/eventingtls/servermanager.go, pkg/eventingtls/servermanager_test.go
In https://github.com/knative/eventing/pull/6908#pullrequestreview-1414364902 we discussed an improvement of the servermanager to return the error directly instead of waiting for the 2nd receiver to finish too, before being able to handle the error.
- Return error directly when one receiver from servermanager fails and send a context cancel to the remaining receiver
@gab-satchi @pierDipi @matzew: fyi
=> Return error directly if one receiver of servermanager fails

pkg/adapter/v2/cloudevents.go, pkg/eventingtls/eventingtls.go
Not having CA certs with an HTTPS sink is valid and expected when the sink URL is using a public CA.
In addition, the eventingtls package correctly handles `nil` or `""` CA certs correctly: https://github.com/knative/eventing/blob/5c6fe572143c8b15a3bbcfe65dc1bed38ef27f79/pkg/eventingtls/eventingtls.go#L188-L190 and it will also enforce the minimum TLS version for the connection.
=> Remove CA certs empty and non nil check, use URL scheme only

cmd/heartbeats/main.go
Fixes #6917
The cmd/heartbeats component now supports Eventing TLS by using the K_CA_CERTS environment variable in client.
- Added K_CA_CERTS env variable support
- Added support for eventingtls in heartbeats
```release-note
The ApiServerSource controller now sets the K_CA_CERTS environment variable when creating the adapter and the sink has CACerts defined.
```
**Docs**
=> Added Support for K_CA_CERTS in the heartbeats

pkg/apis/eventing/v1/broker_lifecycle.go, pkg/apis/eventing/v1/broker_lifecycle_test.go, pkg/eventingtls/eventingtls.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/controller_test.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel.go, pkg/reconciler/testing/v1/broker.go
Fixes #6918 
- Exposes endpoints based on the Feature Flag 
-	when the feature flag (see https://github.com/knative/eventing/issues/6836) is set to permissive
expose 
- both http and https endpoints in the new status.addresses (see https://github.com/knative/pkg/issues/2711) field
- the existing status.address will continue to have the existing http endpoint
- when the feature flag (see https://github.com/knative/eventing/issues/6836) is set to strict
- expose only the https endpoints in both the new status.addresses and the existing status.address
```release-note
```
**Docs**
=> Eventing TLS: support exposing https address in Broker controller

pkg/apis/sources/v1/sinkbinding_lifecycle.go, pkg/apis/sources/v1/sinkbinding_lifecycle_test.go, pkg/apis/sources/v1/sinkbinding_types.go, pkg/reconciler/sinkbinding/controller.go
Fixes #6915
Now sets the K_CA_CERTS environment variable in sinkbinding
- Added K_CA_CERTS env variable support
```release-note
```
**Docs**
=> Eventing TLS: Support K_CA_CERTS env variable injection for SinkBinding subjects

pkg/reconciler/eventtype/controller.go, pkg/reconciler/eventtype/controller_test.go, pkg/reconciler/eventtype/eventtype.go, pkg/reconciler/eventtype/eventtype_test.go, pkg/reconciler/testing/v1/eventtype.go, pkg/reconciler/testing/v1/listers.go
Fixes #6948
- EventType reconciler/controller is using v1b2 APIs
```release-note
EventType v1beta2 usage on the reconciler
```
**Docs**
=> Using v1b2 in the reconciler

config/brokers/mt-channel-broker-tls/broker-filter-tls-certificate.yaml, config/channels/in-memory-channel-tls/imc-dispatcher-tls-certificate.yaml, config/tls/issuers/eventing-selfsigned-issuer.yaml, config/tls/issuers/selfsigned-ca-issuer.yaml, config/tls/issuers/selfsigned-issuer.yaml
This PR is refactoring how we provision certificates with cert-manager
in a way that is much easier for organizations to plug their own
root CA or even use a different issuer.
=> Improve cert-manager resources for Eventing TLS certs provisioning

pkg/reconciler/source/crd/crd_test.go, pkg/reconciler/source/duck/controller.go, pkg/reconciler/source/duck/controller_test.go, pkg/reconciler/source/duck/duck.go, pkg/reconciler/source/duck/duck_test.go, pkg/reconciler/source/duck/resources/eventtype.go, pkg/reconciler/source/duck/resources/eventtype_test.go, pkg/reconciler/testing/v1beta2/factory.go, pkg/reconciler/testing/v1beta2/listers.go
Fixes #6963
- use EventType v1b2 on sources `duck` controller/reconciler
- updating reconciler testing for v1b2, adding listers/factory
```release-note
EventType v1b2 on sources `duck` controller/reconciler used
```
**Docs**
=> Adding source duck type to v1b2

DEVELOPMENT.md, config/core/resources/apiserversource.yaml, test/rekt/apiserversource_test.go, test/rekt/features/apiserversource/data_plane.go, test/rekt/features/apiserversource/readiness.go, test/rekt/features/apiserversource/webhook_validation_smoke.go, test/rekt/resources/apiserversource/apiserversource.go, test/rekt/resources/apiserversource/apiserversource.yaml, test/rekt/resources/apiserversource/apiserversource_test.go
Fixes #6913
- Test ApiServerSource with eventshub TLS receiver as sink
```release-note
ApiServerSource supports sending events to TLS endpoints, minimum TLS version is v1.2
```
**Docs**
=> Eventing TLS: Test ApiServerSource with eventshub TLS receiver as sink

docs/eventing-api.md, pkg/apis/duck/v1/subscribable_types.go, pkg/apis/duck/v1/zz_generated.deepcopy.go, pkg/apis/messaging/v1/subscription_types.go, pkg/apis/messaging/v1/zz_generated.deepcopy.go, pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/v1/subscription.go, pkg/reconciler/testing/v1/unstructured.go
- :gift: Add `subscriberCACerts` & `replyCACerts` fields to `SubscriberSpec`
- :gift: Add `subscriberCACerts` & `replyCACerts` fields to `SubscriptionStatusPhysicalSubscription`
=> Add field for subscribers & replys CA certs to `SubscriberSpec` and `SubscriptionStatusPhysicalSubscription`

pkg/apis/feature/features.go, test/rekt/features/featureflags/featureflags.go
When we will implement Broker and Channel tests we can use the added prerequisite step go guard TLS tests.
=> Add transport-encryption prerequisite for Addressable tests

.github/workflows/kind-e2e.yaml, test/conformance/main_test.go, test/e2e-tests.sh, test/e2e/main_test.go, test/e2e_flags.go, test/flags/eventing_environment.go, test/upgrade/upgrade.go, test/upgrade/upgrade_test.go
Provides better flexibility for reusing in downstream repositories. It is now possible to initialize flags from this repo and any additional flags from downstream repositories and then call flag.Parse explicitly to fill the flags. Then it's possible to run RunMainTest independently.
This is especially useful when we want to combine REKT tests with upgrade test suite.
Fixes #
- Remove BrokerClass flag and make it a const, there's only one possible value anyway.
- Pull `flag.Parse()` out of InitializeEventingFlags.
- It is now possible to do something like this in downstream repos and combine tests with REKT framework:
```
func TestMain(m *testing.M) {
// Initialize any Eventing flags here.
eventingtest.InitializeEventingFlags()
restConfig, err := pkgTest.Flags.ClientConfig.GetRESTConfig() …
```
=> Do not parse flags in InitializeEventingFlags

test/rekt/features/channel/features.go
Running the test twice will cause the test to fail due to name conflicts
=> Use random names in Channel tests

DEVELOPMENT.md
When following `DEVELOPMENT.md` to get set up to develop on this project, I noticed that the section on setting up a kubernetes cluster linked to a page which didn't seem to cover how to set up a kubernetes cluster.
- Update `DEVELOPMENT.md` to provide more helpful links to setting up a kubernetes cluster locally
As this PR only updates the development setup docs, I don't think these requirements apply to it.
```release-note
```
**Docs**
=> Updated DEVELOPMENT.md to provide better instructions on setting up kubernetes

pkg/eventingtls/servermanager.go, pkg/eventingtls/servermanager_test.go
Currently the eventingtls package depends on the kncloudevents package. This leads to circular dependencies, when using eventingtls for testing in kncloudevents.
This PR removes the dependency from eventingtls to kncloudevents.
- :broom: Remove dependency from `eventingtls` to `kncloudevents` package
=> Make ServerManager independent from kncloudevents package

config/core/resources/pingsource.yaml, test/rekt/features/apiserversource/data_plane.go, test/rekt/features/pingsource/features.go, test/rekt/features/pingsource/readyness.go, test/rekt/features/sequence/feature.go, test/rekt/features/trigger/feature.go, test/rekt/pingsource_test.go, test/rekt/resources/pingsource/pingsource.go, test/rekt/resources/pingsource/pingsource.yaml, test/rekt/resources/pingsource/pingsource_test.go
Fixes #6914
- Test PingSource with eventshub TLS receiver as sink
```release-note
PingSource supports sending events to TLS endpoints, minimum TLS version is v1.2
```
**Docs**
=> Test PingSource with eventshub TLS receiver as sink

cmd/broker/filter/main.go, config/brokers/mt-channel-broker/200-filter-role.yaml, config/brokers/mt-channel-broker/201-filter-rolebinding.yaml, config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/roles/filter-role.yaml, config/brokers/mt-channel-broker/roles/filter-rolebinding.yaml, pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/broker/filter/server_manager.go, pkg/eventingtls/eventingtls.go, test/rekt/features/trigger/feature.go, test/rekt/resources/trigger/trigger.go, test/rekt/resources/trigger/trigger.yaml, test/rekt/trigger_test.go
Fixes #6877
Currently includes 98a98cd815a964a20b19edb329c61130322e2a43 as a cherry-pick from #6983.
- :gift: Add TLS support for mt-broker-filter
```release-note
Add TLS support for mt-broker-filter
```
=> Add TLS support for mt-broker-filter

pkg/reconciler/eventtype/eventtype_test.go, pkg/reconciler/testing/v1/eventtype.go, pkg/reconciler/testing/v1beta2/eventtype.go
- nit: rename test func, to better reflect that we work with a Resource, and not just a broker
```release-note
```
**Docs**
=> Rename more to Resource, instead of broker

pkg/apis/feature/flag_names.go, pkg/resolver/kresource_resolver.go, test/rekt/features/apiserversource/data_plane.go, test/rekt/features/containersource/features.go, test/rekt/features/featureflags/featureflags.go, test/rekt/features/pingsource/features.go, test/rekt/features/sinkbinding/feature.go, test/rekt/features/trigger/feature.go
Currently the TLS e2e tests run, even when Istio is enabled. This PR addresses it, and adds a prerequisite to the TLS tests to run only, if the istio feature flag is not enabled.
=> Run TLS e2e tests only when Istio is not enabled

DEVELOPMENT.md
Fixes #7037 
The command to redeploy is shown as 
`ko apply -f config/controller.yaml`
`ko apply -f config/500-controller.yaml`
```release-note
```
**Docs**
=> update the redeployment script

pkg/reconciler/source/duck/duck.go, pkg/reconciler/source/duck/duck_test.go
We should not limit the EventType creation from the Sources Duck to just brokers
If we do create those for all, we have much better visibility into our system on what events are being emitted
Fixes #7033
- Do not restrict Source duck to just broker for event type creation
```release-note
Source duck compliant source now create EventTypes for KResources, not just brokers
```
**Docs**
=> We should not limit the EventType creation from the Sources Duck to just brokers

pkg/adapter/mtping/runner.go, pkg/adapter/v2/cloudevents.go, pkg/apis/http.go, pkg/broker/filter/filter_handler.go, pkg/channel/fanout/fanout_message_handler.go, pkg/channel/message_dispatcher.go, test/rekt/features/broker/feature.go, test/rekt/features/channel/features.go, test/rekt/features/matchers.go, test/rekt/features/pingsource/features.go
When running MT components [1] in mesh mode with Istio, 
we lose the ability to define fine grained policies since we
don't know the resource namespace that originated such
request, therefore, by having a `Kn-Namespace` header, 
in mesh mode, users case define fine-grained policies and
isolate namespaces.
[1] IMC, MTChannelBasedBroker, and PingSource
=> Send namespace header in MT components

test/rekt/broker_test.go, test/rekt/features/broker/feature.go, test/rekt/main_test.go, vendor/knative.dev/reconciler-test/pkg/tracing/tracing.go, vendor/modules.txt
For debugging [flaky tests](https://github.com/knative/eventing/issues?q=is%3Aissue+is%3Aopen+label%3Aauto%3Aflaky).
As described here: https://github.com/knative-sandbox/reconciler-test#inspecting-zipkin-traces-for-failed-tests
=> Add tracing for TestBrokerWithManyTriggers

.golangci.yaml
It might have prevented this bug from happening: https://github.com/knative/eventing/pull/7077/commits/a6498b6ad2d05ff45cb096d33ad7acb8947a0790
=> Add loopclosure linter

pkg/broker/filter/server_manager.go, pkg/broker/ingress/server_manager.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/controller_test.go, pkg/reconciler/broker/trigger/trigger.go, pkg/reconciler/broker/trigger/trigger_test.go
Follow up on https://github.com/knative/eventing/pull/6986#discussion_r1255363753:
Moved the tls secret names for mt-broker-ingress & mt-broker-filter into constants
=> Move ingress & filter TLS secret names into constants

.golangci.yaml
Reverts knative/eventing#7079
It causes
```
Running [/home/runner/golangci-lint-1.52.0-linux-amd64/golangci-lint run --out-format=github-actions --new-from-patch=/tmp/tmp-1767-brlK8gkkRq5N/pull.patch --new=false --new-from-rev= --go=1.20] in [] ...
level=error msg="Running error: unknown linters: 'loopclosure', run 'golangci-lint help linters' to see the list of supported linters"
```
Maybe the version we use in CI doesn't support this linter
=> Revert "Add loopclosure linter"

pkg/broker/filter/server_manager.go, pkg/broker/ingress/server_manager.go, pkg/eventingtls/eventingtls.go, pkg/reconciler/broker/trigger/trigger.go, pkg/reconciler/broker/trigger/trigger_test.go, pkg/reconciler/inmemorychannel/controller/controller.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go
Fixes #7084 
- Refactor the hardcoded tls secret names in the in memory channel into the `eventingtls` package
- Refactor the hardcoded tls secret names in the broker into the `eventingtls` package
=> Convert tls secret names to constants

pkg/utils/secret.go
Supports https://github.com/knative-sandbox/eventing-kafka-broker/issues/3133 which is being implemented in https://github.com/knative-sandbox/eventing-kafka-broker/pull/3134 and requires these changes in knative eventing.
-
-
-
```release-note
```
**Docs**
=> Function CopySecretWithName for creating secrets with specific name

config/brokers/mt-channel-broker-tls/broker-filter-tls-certificate.yaml, config/brokers/mt-channel-broker-tls/broker-ingress-tls-certificate.yaml, config/channels/in-memory-channel-tls/imc-dispatcher-tls-certificate.yaml
As per title, without this configuration the private key is not rotated
=> Eventing TLS: Configure certificates to force rotate private keys

config/channels/in-memory-channel/resources/in-memory-channel.yaml, config/core/resources/broker.yaml, config/core/resources/channel.yaml, config/core/resources/parallel.yaml, config/core/resources/sequence.yaml, config/core/resources/subscription.yaml
This adds addresses and CA certs to every CRDs
=> Eventing TLS: Configure CRDs to have addresses and CA certs

DEVELOPMENT.md, hack/install.sh
You can now just run:
```
hack/install.sh
```
to install Eventing for development.
It reuses the CI build process, so that's minimal maintenance
=> Introduce a script to build and deploy Eventing for local development

pkg/reconciler/broker/controller.go
This will allow updating Brokers' addresses based on transport-encryption feature flag
=> Global resync brokers on config-features changes

test/experimental/features/retry_after/channel.go
After https://github.com/knative-extensions/reconciler-test/pull/535 and thus distinguishing between received/rejected events, the ReplyAfter e2e test needs to be adjusted.
Currently it fails due to 
```
- Match errors -
0 - event kind don't match. Expected: 'Sent', Actual: 'Rejected'
1 - event kind don't match. Expected: 'Sent', Actual: 'Rejected'
2 - event kind don't match. Expected: 'Sent', Actual: 'Rejected'
``` 
and later 
```
- Match errors -
0 - response received at 2023-08-03 14:33:17.338149413 +0000 UTC, it should have waited until 2023-08-03 14:33:41.369616997 +0000 UTC
```
as it is not differentiated between received and rejected events.
This PR addresses it and adjust the event matchers.
=> Fix retryAfter experimental e2e test

test/e2e-common.sh
Currently we have in the e2e Test setup phase the following issue:
```
...
./test/e2e-common.sh: line 297: kail: command not found
...
```
This is, because the install script (`https://raw.githubusercontent.com/boz/kail/master/godownloader.sh`) is not available anymore.
This PR addresses it and installs kail from source for a given version.
=> Install Kail from source in test_setup

.gitignore
Using telepresence creates *.env files which can be annoying to remember to not commit
- Add `*.env` to the gitignore
=> Added .env files to the gitignore

config/core/configmaps/features.yaml, pkg/apis/feature/features.go, pkg/apis/feature/flag_names.go
Fixes #7174 
- 🎁 Add OIDC Authentication flag
```release-note
```
**Docs**
=> Add OIDC Authentication feature flag

.github/workflows/kind-e2e.yaml, hack/create-kind-cluster.sh
Update Kubernetes version for KinD e2e test to 1.25.11 and add 1.27.3.
/hold
Needs to have #7138 merged first (and then needs rebase)
=> Add kind e2e tests for Kubernetes v1.27.3

test/experimental/features/new_trigger_filters/filters.go
Currently the `TestMTChannelBrokerNewTriggerFilters` e2e test creates an invalid trigger (wrong indention of filter):
```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
name: via-trigger-fjzslcdv
namespace: test-aylqfghe
spec:
broker: default
filters:
- cesql: "type = 'com.example.FullEvent' AND source = 'http://example.com/source'" 
...
```
This is because we changed the indention for the filter in the trigger template. This PR addresses fixes it and uses the in #7135 introduced `WithNewFilters()` function.
=> Switch to trigger.WithNewFilters() to set trigger filter

test/rekt/features/apiserversource/data_plane.go, test/rekt/features/pingsource/features.go, test/rekt/resources/eventtype/eventtype.go
Fixes #7167 
- Change the deprecated `sets.String` to `sets.Set`
=> change the deprecated string

pkg/eventfilter/benchmarks/any_filter_benchmark_test.go
Fixes #7112 
- Benchmark the overhead of using the any filter with a single nested filter
- Benchmark performance when there is an early match
- Benchmark performance when there is no early match
The benchmark results are:
```
goos: linux
goarch: amd64
pkg: knative.dev/eventing/pkg/eventfilter/benchmarks
cpu: Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
BenchmarkAnyFilter
BenchmarkAnyFilter/Creation:_Any_filter_with_exact_filter_test
BenchmarkAnyFilter/Creation:_Any_filter_with_exact_filter_test-8         	14015557	        72.60 ns/op
BenchmarkAnyFilter/Run:_Any_filter_with_exact_filter_test
BenchmarkAnyFilter/Run:_Any_filter_with_exact_filter_test-8              	 1592767	       647.1 ns/op
BenchmarkAnyFilter/Creation:_Any_filter_match_all_subfilters …
```
=> Added benchmark for any filter

test/experimental/config/features.yaml, test/experimental/eventtype_autocreate_test.go, test/experimental/features/eventtype_autocreate/features.go
Fixes #7197 
- Add experimental test for eventtype autocreate on IMC
=> Added rekt test for channel event autocreate

cmd/broker/ingress/main.go, pkg/broker/ingress/ingress_handler.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
This is a cherry pick of #7161 onto release-1.11
=> [release-v1.11] Cherry pick eventtype autocreate fixes

test/experimental/eventtype_autocreate_test.go, test/experimental/features/eventtype_autocreate/features.go
Part of #7196 
- Add a rekt test which sends events to a broker and verifies that they are created
=> Added rekt test for broker eventtype autocreate

pkg/scheduler/state/state.go, pkg/scheduler/state/state_test.go, pkg/scheduler/statefulset/autoscaler.go, pkg/scheduler/statefulset/autoscaler_test.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
Fixes https://github.com/knative/eventing/issues/6733
- Make autoscaler leader aware
- Add grace period for scaling down
=> Autoscaler considers reserved and pending replicas

pkg/eventfilter/benchmarks/all_filter_benchmark_test.go
Fixes #7113 
1. **All Filter with Exact Filter Test**:
- Tests a single exact filter that matches.
2. **All Filter Match All Subfilters**:
- Uses an exact filter, prefix filter, and suffix filter; all are set to match.
3. **All Filter No 1 Match at End of Array**:
- Arranges filters so that two initial ones don't match, but the last one does.
4. **All Filter No 1 Match at Start of Array**:
- Sets the first filter to match but follows it with two non-matching filters.
5. **All Filter with Multiple Exact Filters that Match**:
- Tests with three exact filters that all match different attributes of the event.
6. **All Filter with One Non-Matching Filter in the Middle**:
- Inserts a non-matching filter between two matching filters.
7. **All Filter with All Non-Matching Filters**:
- Uses only …
=> Add more benchmark test for All filter

config/channels/in-memory-channel/resources/in-memory-channel.yaml, config/core/resources/broker.yaml, config/core/resources/channel.yaml, config/core/resources/parallel.yaml, config/core/resources/sequence.yaml
Fixes #7189 
-
-
-
```release-note
Add Audience field in CRDs
```
**Docs**
=> Add Audience field in CRDs

pkg/apis/eventing/v1/broker_lifecycle.go, pkg/apis/eventing/v1/broker_lifecycle_test.go, pkg/apis/eventing/v1/test_helper.go, pkg/auth/audience.go, pkg/auth/audience_test.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/testing/v1/broker.go, test/experimental/auth_test.go, test/experimental/config/features.yaml, test/experimental/features/auth/features.go, test/rekt/resources/addressable/addressable.go
Fixes #7184
- :gift: Expose audience in Broker status
**Hints:**
* Actually `auth.GetAudience()` should have only accepted a `kmeta.Accessor` (includes `metav1.TypeMeta` and `metav1.ObjectMeta`), to construct the audience string. Anyhow `broker.ReconcileKind()` does not always get a broker object with provisioned `TypeMeta`, so I had to pass the `Group` and `Kind` directly.
```release-note
Expose OIDC audience of a Broker in its status
```
=> Expose a Brokers audience in its status

pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/pingsource/pingsource.go, pkg/reconciler/pingsource/pingsource_test.go, pkg/reconciler/source/duck/duck.go, pkg/reconciler/source/duck/duck_test.go, test/rekt/features/apiserversource/data_plane.go
Fixes #7236 
It appears that the eventtypes KReference in the default namespace were being retrieved with `Namespace: ""`, while the eventtypes KReference they were being compared to had `Namespace: "default"`. This caused the deep equality to fail, so they were continually deleted and recreated in the duck reconciler.
- Set `Namespace = "default"` if `Namespace == ""`
```release-note
Fixed bug where eventtypes for builtin sources were created and deleted in a loop
```
=> Fixed eventtype create-delete loop on built in sources

config/brokers/mt-channel-broker-tls/broker-filter-tls-certificate.yaml, config/brokers/mt-channel-broker-tls/broker-ingress-tls-certificate.yaml, config/channels/in-memory-channel-tls/imc-dispatcher-tls-certificate.yaml
Fixes #7209 
- Add dns name to broker ingress certificate
- Add dns name to broker filter certificate
- Add dns name to imc dispatcher certificate
=> Added hostnames to tls certificates

test/rekt/resources/containersource/containersource.yaml, test/rekt/resources/delivery/delivery.go, test/rekt/resources/delivery/delivery.yaml, test/rekt/resources/pingsource/pingsource.yaml, test/rekt/resources/pingsource/pingsource_test.go, test/rekt/resources/source/source.go, test/rekt/resources/subscription/subscription.go, test/rekt/resources/subscription/subscription.yaml
Affects ContainerSource, PingSource, Subscription.
The resources might point to Sinks that are in a different namespace than the current resource. It is especially useful for testing cross-namespace communication.
The changes do not affect current behaviour. By default the current/test namespace is used but the user can specify another namespace by passing extra properties.
Fixes #
-
-
-
```release-note
```
**Docs**
=> Option to specify different namespace for resources

pkg/adapter/apiserver/adapter.go
This fixes the issue when istio proxy is injected and the adapter starts before it is ready:
```
{"level":"error","ts":"2023-09-21T13:29:17.711Z","caller":"apiserver/adapter.go:91","msg":"Could not retrieve information about resource /v1, Resource=events: Get \"[https://172.30.0.1:443/api/v1](https://172.30.0.1/api/v1)\": dial tcp 172.30.0.1:443: connect: connection refused","commit":"a16b045-dirty","stacktrace":"knative.dev/eventing/pkg/adapter/apiserver.(*apiServerAdapter).start\n\t/go/src/github.com/openshift/origin/pkg/adapter/apiserver/adapter.go:91\nknative.dev/eventing/pkg/adapter/apiserver.(*apiServerAdapter).Start\n\t/go/src/github.com/openshift/origin/pkg/adapter/apiserver/adapter.go:58\nknative.dev/eventing/pkg/adapter/v2.MainWithInformers\n\t/go/src/github.com/openshift/origin/ …
```
=> Fail when ApiServerSource adapter can't retrieve resources

pkg/kncloudevents/event_dispatcher.go
Clone the event since:
- we mutate the event and the callers might not expect this
- it might produce data races if the caller is trying to read the event in different go routines
Fixes #7193 
- Fix dispatcher data race
```release-note
```
**Docs**
=> Fix event dispatcher library data race

pkg/scheduler/state/state.go, pkg/scheduler/statefulset/autoscaler.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
There are extensive comments in the actual code changes on the why of each individual change.
- Properly handle overcommitted pods
- Don't block the scheduler on triggering the autoscaler if the autoscaler is active
- Additional fix for https://github.com/knative/eventing/issues/6733
- various logging improvements (leader, state, actions and context)
=> Scheduler: fix reserved replicas handling, blocking autoscaler and overcommitted pods

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/eventfilter/attributes/filter.go, pkg/eventfilter/filter.go, pkg/eventfilter/subscriptionsapi/all_filter.go, pkg/eventfilter/subscriptionsapi/all_filter_test.go, pkg/eventfilter/subscriptionsapi/any_filter.go, pkg/eventfilter/subscriptionsapi/cesql_filter.go, pkg/eventfilter/subscriptionsapi/exact_filter.go, pkg/eventfilter/subscriptionsapi/filters_map.go, pkg/eventfilter/subscriptionsapi/filters_map_test.go, pkg/eventfilter/subscriptionsapi/no_filter.go, pkg/eventfilter/subscriptionsapi/no_filter_test.go, pkg/eventfilter/subscriptionsapi/not_filter.go, pkg/eventfilter/subscriptionsapi/prefix_filter.go, pkg/eventfilter/subscriptionsapi/suffix_filter.go
Fixes https://github.com/knative/eventing/issues/7210
- Add filters map to make managing existing filters easy
- Update filters interface to include cleanup method (needed for optimizations)
- use the filters map with the events handler to remove the need to create filters on every use
```release-note
New Event Filters are now only created once, rather than on each event
```
**Docs**
=> Filters created once

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go
Currently, the logic to select whether to use the `trigger.Spec.Filter` vs. `trigger.Spec.Filters` is not correct. If I have provided a `trigger.Spec.Filter`, and no `trigger.Spec.Filters`, then currently we would still apply the `trigger.Spec.Filters` and return `filter.NoFilter`, instead of applying my `trigger.Spec.Filter`. This leads to incorrect event processing.
- Fix the logic used to apply the filter vs. the filters field
-
-
```release-note
:bug: The filters field now only overrides the filter field on a trigger if there are filters in the filters field.
```
**Docs**
=> Fixed logic to choose whether to use filter or filters for a trigger

config/channels/in-memory-channel/resources/in-memory-channel.yaml, config/core/resources/channel.yaml, config/core/resources/subscription.yaml, docs/eventing-api.md, pkg/apis/duck/v1/subscribable_types.go, pkg/apis/duck/v1/zz_generated.deepcopy.go, pkg/apis/messaging/v1/subscription_types.go, pkg/apis/messaging/v1/zz_generated.deepcopy.go, pkg/reconciler/subscription/subscription.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/v1/subscription.go
Fixes #7293
As we need to provide the Audiences of the Subscriber and Reply in the Subscription, this PR adds the Audience of Subscriber and Reply to SubscriberSpec and SubscriptionStatusPhysicalSubscription.
=> Add audience field for Subscriber and Reply to `SubscriberSpec` and `SubscriptionStatusPhysicalSubscription`

pkg/auth/serviceaccount.go, pkg/auth/serviceaccount_test.go
Fixes #7277
- :gift: Helpers to work with service accounts for OIDC
**Hints for reviewers:**
* the naming pattern can be adjusted (e.g. if we see they get too long), but this should help to get started with tasks like #7222 or #7227.
=> Add helpers to work with service accounts for OIDC

pkg/eventfilter/subscriptionsapi/suffix_filter.go
Fixes #7306 
- Don't copy strings if not needed when evaluating the suffix filter.
After these changes, the performance difference is:
```
benchmark                                                                                 old ns/op     new ns/op     delta
BenchmarkSuffixFilter/Creation:_Pass_with_suffix_match_of_id-8                            53.3          54.4          +2.08%
BenchmarkSuffixFilter/Run:_Pass_with_suffix_match_of_id-8                                 556           445           -19.95%
BenchmarkSuffixFilter/Creation:_Pass_with_suffix_match_of_all_context_attributes-8        90.1          91.6          +1.73%
BenchmarkSuffixFilter/Run:_Pass_with_suffix_match_of_all_context_attributes-8             1755          1298          -26.04% …
```
=> Improved suffix benchmark performance

pkg/eventfilter/benchmarks/all_filter_benchmark_test.go, pkg/eventfilter/benchmarks/common_benchmark_test.go, pkg/eventfilter/subscriptionsapi/all_filter.go
Fixes #7147 
- Dynamically optimize the ordering of the All filter so that it fails faster when possible
The results of this optimization are:
```
benchmark                                                                                        old ns/op     new ns/op     delta
BenchmarkAllFilter/Creation:_All_filter_with_exact_filter_test-8                                 86.2          553           +541.31%
BenchmarkAllFilter/Run:_All_filter_with_exact_filter_test-8                                      892           847           -5.04%
BenchmarkAllFilter/Creation:_All_filter_match_all_subfilters-8                                   117           659           +461.41%
BenchmarkAllFilter/Run:_All_filter_match_all_subfilters-8                                        2416          2117 …
```
=> All filter optimization

pkg/apis/eventing/v1/trigger_lifecycle.go, pkg/apis/eventing/v1/trigger_lifecycle_test.go, pkg/auth/serviceaccount.go, pkg/auth/serviceaccount_test.go, pkg/reconciler/broker/trigger/controller.go, pkg/reconciler/broker/trigger/controller_test.go, pkg/reconciler/broker/trigger/trigger.go, pkg/reconciler/broker/trigger/trigger_test.go, pkg/reconciler/testing/v1/trigger.go
Fixes #7222
- :gift: Expose the name of the OIDC service account in the Triggers `.status.auth.serviceAccountName`
- :gift: Create the OIDC service account of the Trigger
```release-note
Expose the Triggers OIDC service account name in the Triggers .status.auth.serviceAccountName
```
=> Trigger create and expose OIDC service account

config/core/resources/apiserversource.yaml, config/core/resources/containersource.yaml, config/core/resources/pingsource.yaml, config/core/resources/sinkbindings.yaml, config/core/resources/subscription.yaml, config/core/resources/trigger.yaml
Since https://github.com/knative/pkg/issues/2796 we have the `Audience` in `duckv1.Destination`. This should be reflected in the CRDs too.
- :broom: Add `Audience` field Destinations in CRDs
=> Add audience field in Destinations to CRDs

pkg/apis/eventing/v1/trigger_lifecycle.go, pkg/apis/eventing/v1/trigger_lifecycle_test.go, pkg/reconciler/testing/v1/trigger.go
In #7299 we introduced a new Trigger condition type ( `OIDCIdentityCreated`) to mark if the Triggers OIDC identity was created successfully. 
Anyhow not all broker classes support the OIDC authentication yet and mark their Triggers `OIDCIdentityCreated` as true as they either created the identity or didn't create it as the feature is disabled.
These broker classes could mark their Triggers `OIDCIdentityCreated` condition as ready, but with the message "OIDC feature not supported yet".
This PR addresses it and adds helper methods to set the condition accordingly.
=> Add marker for Trigger to mark `OIDCIdentity` condition as not supported

pkg/reconciler/broker/trigger/trigger.go, pkg/reconciler/broker/trigger/trigger_test.go
Fixes #7292
- :gift: Use `mt-broker-filter` as the Audience of a Triggers Subscriptions Subscriber (pointing to the broker-filter)
=> Use `mt-broker-filter` as the Audience of a Triggers Subscriptions Subscriber

.github/workflows/kind-e2e.yaml
Since https://github.com/knative/pkg/pull/2832 the K8s min version for Knative is 1.26. This leads to failing KinD e2e tests in CI.
This PR remove the 1.25 jobs and updates it to 1.26 to have jobs testing the min version.
- :broom: Remove KinD e2e tests on Kubernetes 1.25
- :gift: Add KinD e2e tests for Kubernetes 1.26
=> Update Kubernetes min version in KinD e2e tests to 1.26.6

pkg/eventfilter/filter.go, pkg/eventfilter/subscriptionsapi/prefix_filter.go
Fixes #7305 
Fixes #7308 
- Only copy the event attribute into a string with Sprintf if that attribute needs to be converted to a string
- Only loop over the event attributes once, instead of twice
- use int instead of string for eventfilter result types
Performance improvements after these changes:
```
benchmark                                                                                 old ns/op     new ns/op     delta
BenchmarkPrefixFilter/Creation:_Pass_with_prefix_match_of_id-8                            53.5          54.1          +1.07%
BenchmarkPrefixFilter/Run:_Pass_with_prefix_match_of_id-8                                 558           439           -21.34%
BenchmarkPrefixFilter/Creation:_Pass_with_prefix_match_of_all_context_attributes-8        89.6          89.7 …
```
=> Prefix filter optimizations

pkg/eventfilter/subscriptionsapi/exact_filter.go
Fixes #7307 
Currently, we use the attributes filter internally when running the exact filter. However, the attributes filter supports cases which the exact filter does not allow. Specifically, the current implementation of the exact filter requires that all filters have a non-empty string value for both the attribute and the desired value, while the attributes filter checks if the desired value is "", and treats that as a special "allow anything" case. By rewriting the exact filter with these more strict requirements, we see a speed up in terms of performance.
To see the current creation-time validation logic, look here: https://github.com/knative/eventing/blob/44aa15e9584bcedf12126d2f892fb185e8b41bb6/pkg/eventfilter/subscriptionsapi/exact_filter.go#L39-L44
- Instead of using the …
=> Optimized the exact filter performance

pkg/auth/token_provider.go
Fixes #7331
- Use the k8s apimachinery expiring cache to keep the tokens and evict them when they expire
```release-note
OIDC tokens are now cached to improve performance.
```
=> Use expiring cache with the OIDC tokens

cmd/broker/filter/main.go, cmd/broker/ingress/main.go, pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/broker/ingress/ingress_handler.go, pkg/broker/ingress/ingress_handler_test.go, pkg/channel/fanout/fanout_event_handler.go, pkg/channel/fanout/fanout_event_handler_test.go, pkg/channel/multichannelfanout/multi_channel_fanout_event_handler.go, pkg/channel/multichannelfanout/multi_channel_fanout_event_handler_test.go, pkg/inmemorychannel/event_dispatcher_test.go, pkg/kncloudevents/event_dispatcher.go, pkg/kncloudevents/event_dispatcher_test.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
- :gift: Update kncloudevents.Dispatcher to include add token from #7315
=> Update `kncloudevents.Dispatcher` to add a JWT

pkg/auth/token_provider.go
…ers cache to 5 minuets
Fixes #7351 
- Increased OIDC token expiration time to 5 minuets
```release-note
```
**Docs**
=> Increase expiration buffer time of OIDCTokenProviders cache to 5 minutes

pkg/apis/feature/features.go, pkg/apis/feature/features_test.go
Fixes #7254 
- Don't override default values when applying partial features.yaml configmap 
```release-note
It is now possible to specify a subset of features in `config-features` without overriding default values
```
**Docs**
=> Don't override default values when applying partial features.yaml configmap 

pkg/adapter/mtping/adapter.go, pkg/apis/sources/v1/ping_validation.go, pkg/apis/sources/v1/ping_validation_test.go, pkg/apis/sources/v1beta2/ping_validation.go, pkg/apis/sources/v1beta2/ping_validation_test.go, test/rekt/features/pingsource/features.go, test/rekt/pingsource_test.go, test/rekt/resources/pingsource/pingsource_test.go
- :gift: Allows PingSource to fire at sub-minute intervals. Enabled by constructing [cron](https://github.com/robfig/cron) with a custom parser as detailed in the cron package's [README](https://github.com/robfig/cron#readme). Screenshot from this README is shown below. Their README explains that this is backwards compatible. The standard cron format will still continue to work whilst also allowing for the additional cron format used by [the Quartz Scheduler](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html) which supports a seconds field.
```release-note
:page_facing_up: PingSource `schedule` supports optional seconds field
```
=> Support for seconds field in PingSource schedule

test/rekt/features/pingsource/features.go, test/rekt/pingsource_test.go, test/rekt/resources/pingsource/pingsource.go
Fixes #6932 
- A rekt-based e2e test for PingSource TLS support when using Broker as sink
-
-
```release-note
Added a rekt-based e2e test for PingSource TLS support when using Broker as sink
```
**Docs**
=> Adding the rekt test for pingsource with broker as sink

config/core/configmaps/features.yaml, pkg/apis/feature/flag_names.go, test/auth/config/features.yaml
Correct the OIDC auth feature flag name is inconsistent as it uses a dot while other feature flags use - to separate words, In this pr change it to authentication-oidc instead of authentication.oidc.
#7420
=> fix: Inconsistent OIDC auth feature flag name

pkg/apis/flows/v1/parallel_lifecycle_test.go, test/auth/features/oidc/parallel.go, test/auth/oidc_test.go, test/rekt/resources/parallel/parallel.go
Fixes #7295
A Parallel will have the same audience as its input channel. As this is [already implemented](https://github.com/knative/eventing/blob/e3b797031d76bbca6a18e7e576b14cd543fe86c6/pkg/apis/flows/v1/parallel_lifecycle.go#L199), this PR adds tests to ensure it gets set correctly.
=> Use input channels audience as audience of Parallel

test/rekt/channel_test.go
The default 2-minute timeout might not be enough in some scenarios where deploying takes longer (like with Istio).
-
-
-
```release-note
```
**Docs**
=> Increase Ready timeout for TestChannelConformance to 4 minutes

hack/install.sh
- Running the test_setup within hack/install.sh
```release-note
When running hack/install.sh, all the related testing environments will be set up as well.
```
As per discussion [here](https://cloud-native.slack.com/archives/C04LMU33V1S/p1698418291758539?thread_ts=1698417895.463839&cid=C04LMU33V1S) 
**Docs**
=> Add the test setup in the install script

pkg/channel/fanout/fanout_event_handler.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, test/rekt/broker_test.go, test/rekt/features/broker/data_plane.go
To try to improve the consistency of the system when using the IMC, this PR is testing switching to using the sync handler
- Use the sync handler instead of the async handler
-
-
```release-note
The InMemoryChannel now sends a 202 response only after successfully delivering the event to all subscribers
```
**Docs**
=> Don't use async handler

config/core/resources/pingsource.yaml
Fixes #
- add deprecation warnings to v1b2 and change the structore of the CRD, so that we have _only_ on v1b2 those deprecation warnings
```release-note
V1Beta2 is deprecation, we now issue warnings when the type is created
```
**Docs**
=> Add deprecation warnings for v1b2

docs/eventing-api.md, pkg/apis/eventing/v1beta1/eventtype_types.go
- Deprecate EventType v1b1 API in favor of EventType v1b2 API, in release 1.12
```release-note
- EventType.v1b1 API is deprecated. Instead use the v1b2 version. In a future release the version will be removed
```
**Docs**
=> Deprecate EventType v1b1 API

pkg/apis/flows/v1/sequence_lifecycle.go, pkg/apis/flows/v1/sequence_lifecycle_test.go, pkg/reconciler/sequence/controller.go, pkg/reconciler/sequence/controller_test.go, pkg/reconciler/sequence/sequence.go, pkg/reconciler/sequence/sequence_test.go, pkg/reconciler/testing/v1/sequence.go
Fixes #7224
- 🎁 Expose the name of the OIDC service account in the Sequence .status.auth.serviceAccountName
- 🎁 Create the OIDC service account of the Sequence
```release-note
Expose the Sequence OIDC service account name in the Sequence .status.auth.serviceAccountName after created Service Account.
```
=> support auto generation of Sequence identity service account [OIDC]

config/core/resources/eventtype.yaml
Fixes #
- Add deprecation warnings for EventType v1beta1
- change structure of the CRD (so that we have only on the old v1b1 the deprecation merged in)
-
```release-note
EventType v1beta1 is deprecated. We now issue warning when those CRs are being created. V1beta1 will be removed in a future release.
```
**Docs**
=> Add deprecation warnings for EventType v1beta1

pkg/apis/config/defaults.go, pkg/apis/config/zz_generated.deepcopy.go, pkg/apis/eventing/v1/broker_validation.go, pkg/apis/eventing/v1/broker_validation_test.go
Instead of always allowing to specify cross namespace configuration references for Broker allow users to configure whether to disallow such references as it might be problematic in multi tenant environments.
- Allow configuring whether to allow cross namespaces Brokers configuration references
```release-note
Allow configuring whether to allow cross namespaces Brokers configuration using the `config-br-defaults` ConfigMap.
For example, to disallow cross namespaces Brokers configuration references cluster wide, the following ConfigMap can be applied:
`
apiVersion: v1
kind: ConfigMap
metadata:
name: config-br-defaults
namespace: knative-eventing
labels:
app.kubernetes.io/version: devel
app.kubernetes.io/name: knative-eventing
data:
default-br-config: |
clusterDefault: …
```
=> Allow configuring whether to allow cross namespaces Brokers configuration references

test/rekt/channel_test.go, test/rekt/features/channel/features.go
Adds debugging information to figure out https://github.com/knative/eventing/issues/7440
Traces can be investigated as described [here](https://github.com/knative-extensions/reconciler-test#inspecting-zipkin-traces-for-failed-tests)
Fixes #
- Gather traces for TestChannelDeadLetterSinkExtensions
- Make sure that a dead letter sink is resolved for channel before the source actually sends the event (moving this check from Requirement phase to Setup).
```release-note
```
**Docs**
=> Gather traces for TestChannelDeadLetterSinkExtensions

test/upgrade/prober/wathola/event/services.go, test/upgrade/prober/wathola/event/types.go, test/upgrade/prober/wathola/sender/services.go
Fixes #7446
- Fix reporting the index of the failed step
- Record if sending the last event was interrupted. In that case, tolerate one more event on receiver side because there's no way for the sender to know if the event was successfully sent (as the sender was interrupted and can't properly wait for confirmation)
```release-note
```
**Docs**
=> Upgrade tests account for last event being interrupted

pkg/apis/flows/v1/sequence_lifecycle.go, pkg/apis/flows/v1/sequence_lifecycle_test.go, test/auth/features/oidc/sequence.go, test/auth/oidc_test.go, test/rekt/resources/sequence/sequence.go
Fixes #7294 
- Use channel audience in sequence `status.Address.Audience `
```release-note
Use underlying input channels audience as sequence audience
```
=> provision sequence audience using channel audience

hack/e2e-debug.sh
Fixes #7204
- Added command to run single test
```release-note
```
**Docs**
=> Add command to run single rekt test in the e2e-debug script

config/brokers/mt-channel-broker/200-ingress-serviceaccount-oidc.yaml, config/brokers/mt-channel-broker/roles/ingress-serviceaccount-oidc.yaml, pkg/apis/eventing/register.go, pkg/broker/ingress/ingress_handler.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/testing/v1/broker.go
Fixes #7472
- :gift: authenticate requests from mt-broker-filter to underlying channel (uses dedicated `mt-broker-ingress-oidc` service account and audience of channel)
=> Authenticate requests from mt-broker-ingress to underlying channel

test/rekt/features/broker/topology.go
Fixes #7463 
This change was tested by editing the vendor directory on https://github.com/knative-extensions/eventing-kafka-broker/pull/3464, and the broker conformance rekt routing tests passed, when they were failing before (there is still some flaky CI there, but that is failing kafka source stuff as normal)
- Don't compare CE extensions when evaluating the routing spec
=> Don't compare CE extensions when checking routing spec

config/brokers/mt-channel-broker/roles/filter-clusterrole.yaml, config/core/resources/trigger.yaml, docs/eventing-api.md, pkg/apis/eventing/v1/trigger_types.go, pkg/apis/eventing/v1/zz_generated.deepcopy.go, pkg/broker/filter/filter_handler.go, pkg/reconciler/broker/trigger/trigger.go, test/auth/features/oidc/broker.go, test/rekt/resources/trigger/trigger.go, test/rekt/resources/trigger/trigger.yaml
Fixes #7475
- :gift: Add OIDC authentication to mt-broker-filter, so it adds the OIDC token to request to the subscriber
=> Add OIDC authentication to mt-broker-filter

config/channels/in-memory-channel/resources/in-memory-channel.yaml, config/core/resources/broker.yaml, config/core/resources/channel.yaml, config/core/resources/parallel.yaml, config/core/resources/sequence.yaml
The original message says that the target/Addressable audience takes precedence but it's not true. The Destination's audience takes precedence, i.e. the "audience" element being described in the CRD takes precedence.
The current behavior can be seen in code [here](https://github.com/knative/eventing/blob/main/vendor/knative.dev/pkg/resolver/addressable_resolver.go#L264)
Fixes #
-
-
-
```release-note
```
**Docs**
=> Fix description for audience in CRD.

cmd/broker/filter/main.go, config/brokers/mt-channel-broker/roles/filter-clusterrole.yaml, config/channels/in-memory-channel/resources/in-memory-channel.yaml, config/core/resources/broker.yaml, config/core/resources/channel.yaml, config/core/resources/subscription.yaml, config/core/resources/trigger.yaml, docs/eventing-api.md, pkg/apis/duck/v1/delivery_types.go, pkg/apis/duck/v1/zz_generated.deepcopy.go, pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/broker/filter/stats_reporter.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/resources/subscription.go, pkg/reconciler/broker/resources/subscription_test.go, pkg/reconciler/broker/trigger/trigger.go, pkg/reconciler/broker/trigger/trigger_test.go, pkg/reconciler/sugar/trigger/path/path.go, pkg/reconciler/sugar/trigger/path/path_test.go, test/auth/features/oidc/broker.go, test/auth/oidc_test.go, test/rekt/resources/broker/broker.yaml, test/rekt/resources/delivery/delivery.go, test/rekt/resources/delivery/delivery.yaml
Fixes #7480 
- :gift: Use triggers OIDC identity in Reply & DLS requests
- Route mt-brokers Reply & DLS requests via the broker-filter, as this has the trigger object to get the used OIDC identity
=> Add triggers OIDC identity to Reply & DLS requests

test/rekt/features/new_trigger_filters/feature.go, test/rekt/features/new_trigger_filters/filters.go, test/rekt/new_trigger_filters_test.go, test/rekt/resources/broker/broker.go
Fixes #7396 
- Pass in a function which installs a broker in a given feature instead of installing it in the environment
- Put all of the features into one feature set so that future dependency sync PRs to ekb will add them to the ekb tests automatically
=> Refactor new filters tests to use single feature set

pkg/eventfilter/attributes/filter.go, pkg/eventfilter/attributes/filter_test.go, pkg/eventfilter/subscriptionsapi/exact_filter_test.go
Fixes #7465 
Currently, we are seeing some inconsistency on time comparisons with filters. This is because we are using a string representation of the time which is explicitly marked as:
> The returned string is meant for debugging; for a stable serialized representation, use t.MarshalText, t.MarshalBinary, or t.Format with an explicit format string. 
CloudEvents spec states that we should use RFC-3339 for encoding timestamps as strings:
https://github.com/cloudevents/spec/blob/130ba0d183f5e45c1d141f5c1f272cf71d898623/cloudevents/spec.md?plain=1#L244
This PR switches our `time.Time.String` calls with code that converts the `time.Time` to RFC-3339 compliant strings.
- Use RFC 3339 encoding for all time strings in filter comparisons
-
-
```release-note
Filters now use …
```
=> Switch filters to use rfc-3339 for time string encoding

config/core/resources/sequence.yaml, pkg/reconciler/sequence/resources/subscription.go, test/auth/features/oidc/sequence.go, test/auth/oidc_test.go, test/rekt/resources/sequence/sequence.go, test/rekt/resources/sequence/sequence.yaml
Fixes #7489
Fixes #7490
- :bug: Add audience field to sequence reply
- :bug: Fix sequence reconciler to set audience of reply and steps
- :gift: Add e2e tests for sequence flow
=> Fix provisioning of sequences reply and steps audience

test/auth/features/oidc/containersource.go, test/auth/oidc_test.go, test/rekt/features/containersource/features.go
Currently the OIDC test feature for the containersource is in the rekt/features directory. All other test features for OIDC tests are under auth/features.
This is nothing tragic, but by having all OIDC related features in auth/, this can make migration later more straight forward as all of them are in the same place.
/assign @mgencur
=> Move containersource OIDC feature to test/auth

pkg/reconciler/parallel/resources/subscription.go, test/rekt/features/parallel/features.go, test/rekt/features/parallel/readyness.go, test/rekt/parallel_test.go, test/rekt/resources/parallel/parallel.go, test/rekt/resources/parallel/parallel.yaml, test/rekt/resources/parallel/parallel_test.go
Add rekt TLS test for Parallel
/area test-and-release
=> Eventing TLS: Add E2E TLS test for Parallel

test/auth/features/oidc/parallel.go, test/auth/oidc_test.go, test/rekt/resources/parallel/parallel.go, test/rekt/resources/parallel/parallel.yaml
Fixes #7491
- Add E2E test for Parallel with OIDC support
```release-note
```
**Docs**
=> Test Parallel with OIDC support

pkg/broker/ingress/ingress_handler.go
Fixes #7474 
```release-note
fix mt-broker-ingress  watch Broker
```
**Docs**
=> fix mt-broker-ingress  watch Broker

test/rekt/resources/addressable/addressable.go, test/rekt/resources/broker/broker.go, test/rekt/resources/channel_impl/channel_impl.go, test/rekt/resources/parallel/parallel.go
Fixes the build issues seen in https://github.com/knative/eventing/pull/7509
- Backport addressable.ValidateAddress
- Backport parallel.ValidateAddress
=> Fix build issues for backports to release-v1.11

test/rekt/resources/parallel/parallel.go
Fixes the build issues on https://github.com/knative/eventing/pull/7508
- Add the missing parallel.ValidateAddress method to fix the build problems
=> Add parallel.ValidateAddress so that release-1.12 backports work

pkg/auth/serviceaccount.go, pkg/auth/serviceaccount_test.go
Fixes #7470 
```release-note
Use kmeta.ChildName() to generate OIDC service account name
```
**Docs**
=> Use kmeta.ChildName() to generate OIDC service account name

.github/workflows/kind-e2e.yaml
Remove Kubernetes 1.26 e2e tests, as Knative 1.13 requires at least 1.27
https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md
In #7524 we add 1.29 support
=> Remove Kubernetes 1.26 from KinD e2e tests

pkg/eventfilter/subscriptionsapi/cesql_filter_test.go, pkg/eventfilter/subscriptionsapi/exact_filter_test.go, test/rekt/features/new_trigger_filters/feature.go, test/rekt/features/new_trigger_filters/filters.go
Fixes #7488 
- Add unit tests for filters with missing attributes
- Add rekt test for filters with missing attributes
-
```release-note
```
**Docs**
=> Add missing attribute filter tests

.github/workflows/kind-e2e.yaml
Add Kubernetes 1.29.0 for KinD e2e tests
/hold
until #7523 merged and this PR rebased
=> Add Kubernetes 1.29.0 for KinD e2e tests

pkg/reconciler/eventtype/eventtype_test.go
Fixes #7031
- A test showing an `EventType` reconciling properly with a Broker reference
- A test showing an `EventType` reconciling properly with a Channel reference
```release-note
```
**Docs**
=> Add reconciler test for EventType references

config/core/resources/pingsource.yaml, pkg/apis/sources/v1/ping_lifecycle.go
Currently we're missing the sinks audience in the PingSource status. This PR addresses it and sets `.status.sinkAudience` of the PingSource.
=> Provision PingSources sink OIDC audience in PingSource status

pkg/adapter/v2/cloudevents.go, pkg/eventingtls/trust_bundle.go, pkg/kncloudevents/http_client.go
This allows administrators to dynamically add trust-bundles that are picked by clients when creating new TLS connections.
=> Reload trust-bundle on new connections

.github/workflows/kind-e2e.yaml
Follow up on https://github.com/knative/eventing/pull/7580#issuecomment-1893225565
- Increase the timeout in KinD tests to 90 minutes
/cc @creydr
=> Increase KinD test timeout to 90 minutes

pkg/reconciler/broker/broker.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
Currently the audience is not set in .status.addresses field (only in .status.address) of a Broker and IMC. This PR addresses it.
/cc @pierDipi @Leo6Leo
=> Set audience in .status.addresses fields too

test/experimental/features/eventtype_autocreate/features.go, test/rekt/resources/eventtype/eventtype.go
Fixes #7196 
- Assert that there is exactly one eventtype created, rather than just checking that all required types were created
=> rekt test to verify only one EventType created for MTBroker

pkg/apis/flows/v1/sequence_lifecycle.go
Currently a Sequences CACert is not provided in its `.status.address`. This PR addresses it
/cc @pierDipi @Leo6Leo
=> Provision sequences CA cert in its status

test/rekt/features/sequence/feature.go, test/rekt/sequence_test.go
As we're missing a test for the sequences TLS functionality (discussed in todays eventing WG meeting).
=> Add TLS test for sequence

config/core/resources/sequence.yaml, pkg/reconciler/sequence/resources/subscription.go, test/rekt/features/sequence/feature.go, test/rekt/resources/sequence/sequence.go, test/rekt/resources/sequence/sequence.yaml, test/rekt/sequence_test.go
Manual backport of #7600 (f4b83c201db501a3f1b8015e679e73c212ecb757) and add fixes to support TLS in sequence (754d7e30c1c0ac6a3da4a37845928e30497d30f6).
=> [release-1.12] Fix Sequence TLS support

pkg/auth/serviceaccount.go, pkg/auth/serviceaccount_test.go
Fixes #7459 
- Added `DeleteOIDCServiceAccountIfExists` function that checks whether service account exists or not when `authentication-oidc` feature is disabled. If they exist they are deleted.
```release-note
```
**Docs**
=> Remove OIDC service account, when OIDC feature is disabled again

test/rekt/features/featureflags/featureflags.go
Allows to add a Prerequiste check in an e2e test, so the test runs only in case the `authorization-oidc` feature flag is enabled.
Usage:
```
f.Prerequisite("OIDC authentication is enabled", featureflags.AuthenticationOIDCEnabled())
```
=> Add a Prerequisite helper to check if the OIDC authentication feature flag is enabled

config/core/resources/eventtype.yaml, test/e2e-common.sh, test/upgrade/installation/git_head.go
Based on Slack thread: https://cloud-native.slack.com/archives/C04LMU33V1S/p1705560044668329.
- Enable storage of EventType v1b2
```release-note
Enable storage of EventType `v1beta2` instead of `v1beta1`
```
=> Enable storage of EventType v1b2

config/core/resources/eventtype.yaml
EventType is now compatible with other resources as well, not just Broker.
Fixes #
- Fix description in CRD.
```release-note
```
**Docs**
=> Generalize description of EventType in CRD.

pkg/apis/feature/features.go, pkg/apis/feature/features_test.go, pkg/apis/feature/flag_names.go, pkg/apis/feature/testdata/config-features.yaml, pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/resources/receive_adapter.go
Fixes #7360 
Users can now configure nodeSelector via ```config-features``` by adding key-value pair in the format ```apiserversources.nodeselector.<key>: <value>```
```release-note
Feature: Added the ability for users to configure `nodeSelector` when deploying `apiserversource` , Users can now configure nodeSelector via config-features by adding key-value pair in the format apiserversources.nodeselector.<key>: <value>
```
**Docs**
=> support: nodeselector in apiserversource

pkg/apis/sources/v1/sinkbinding_lifecycle_test.go, pkg/eventingtls/eventingtls.go, pkg/eventingtls/trust_bundle.go
When there are multiple trust bundle ConfigMaps the only option to mount on the same directory is to use projected volumes.
=> Use projected volumes for sinkbinding trust bundles

DEVELOPMENT.md
https://github.com/knative/eventing/pull/7532/files#diff-76c1ad91357799de2676fe0c7c47b6ab6c6e491149a0813719d239ec344079f4R14
As updated in this PR, helm is used.
https://github.com/knative/eventing/pull/7532/files#r1471800554 explains why 3.14
=> Add helm as one of the development requirement

pkg/scheduler/scheduler.go, pkg/scheduler/state/state.go, pkg/scheduler/state/state_test.go, pkg/scheduler/statefulset/autoscaler.go, pkg/scheduler/statefulset/autoscaler_test.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
Helps to fix the consumergroup issues we are seeing in ekb. At least some of the slow reconciliation is due to errors such as: 
```
failed to schedule consumers: failed to unschedule consumer group: failed to schedule consumers: Get \"[https://10.88.0.1:443/apis/apps/v1/namespaces/knative-eventing/statefulsets/kafka-broker-dispatcher/scale](https://10.88.0.1/apis/apps/v1/namespaces/knative-eventing/statefulsets/kafka-broker-dispatcher/scale)\": context canceled
```
When we increased the client rate limit, these error logs were no longer present
- Cache the scale of statefulsets whenever we get/update them, reusing the cached value where possible
- Expire the keys in the cache to force refresh every once in a while
-
```release-note
StatefulSet scheduling now makes fewer …
```
=> Cache statefulset scale update/get requests

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml, config/channels/in-memory-channel/deployments/controller.yaml, config/channels/in-memory-channel/deployments/dispatcher.yaml, config/channels/in-memory-channel/roles/controller-clusterrole.yaml, config/core/deployments/pingsource-mt-adapter.yaml, config/core/deployments/webhook.yaml, config/core/resources/eventtype.yaml, config/core/resources/parallel.yaml, config/core/resources/pingsource.yaml, config/core/roles/controller-clusterroles.yaml, config/core/roles/sources-controller-clusterroles.yaml, config/core/roles/webhook-clusterrole.yaml
Fixes #
Merge keys are not officially supported in YAML according to its specifications. These keys are associated with an older version of YAML (1.1), which is now considered obsolete. Additionally, these merge keys haven't been updated or included in the current YAML version (1.2), so there's no guarantee that they will function as expected or be supported. In summary, using merge keys in YAML might not work reliably and is not recommended due to these limitations and lack of support in the latest YAML version.
I attempted to install the YAML mentioned using Kustomize, but the installation failed because Kustomize couldn't properly interpret or render the YAML file.
Similar merged proposal [PR for eventing-kafka-brokfer](https://github.com/knative-extensions/eventing-kafka-broker/pull/36 …
=> feat: replace yaml merge tags

pkg/scheduler/scheduler.go
=> Set default value for scale cache config values

test/upgrade/prober/wathola/receiver/services.go
- :broom: annotate received span by step number, to help debugging upgrade tests
=> wathola receiver, annotate span by step number

test/experimental/eventtype_autocreate_test.go, test/experimental/features/eventtype_autocreate/features.go
Fixes #7621
- Added a function `AutoCreateEventTypesOnContainer` in `features.go`
- Added a function `TestContainerSourceEventTypeAutoCreate` in`eventtype_autocreate_test.go`
```release-note
```
**Docs**
=> Add rekt test for containersource autocreate

pkg/graph/lineage.go, pkg/graph/lineage_test.go, pkg/graph/types.go
Fixes #7676 
- Add graph types
- Add method to calculate lineage from a single vertex (this helps validate the types, and is useful for figuring out the full lineage graph - which will be added in #7677 )
- Add unit tests for lineage from a single vertex on a graph which will test that transform functions are propagated properly, and cycles are handled properly
=> Add graph types

test/e2e-common.sh, test/e2e-conformance-tests.sh, test/e2e-rekt-tests.sh, test/e2e-tests.sh, test/e2e-upgrade-tests.sh
This reverts commit fcadaaa335b161e443759af36cded525de5e03dc.
As we have https://github.com/knative/hack/pull/370 and default the GKE version for all repos, we don't need to define it explicitly in eventing anymore.
=> Revert "Run Prow tests on K8s 1.28 (#7714)"

pkg/graph/constructor.go, pkg/graph/constructor_test.go, pkg/graph/types.go
Fixes #7681 
- Create graph method to add a broker to the graph
- Add some comparable types and conversion functions to use in testing, as edges aren't comparable
-
```release-note
Brokers are now supported in the event lineage graph
```
**Docs**
=> feat: brokers can be added to event lineage graph

pkg/apis/feature/flag_names.go, pkg/apis/feature/testdata/config-features.yaml, pkg/reconciler/apiserversource/apiserversource_test.go, test/rekt/resources/configmap/config-features.yaml
- Instead of using `.`, we use `-`, otherwise it might cause error when using yq
```release-note
```
**Docs**
=> Fix the naming convention in the config-features.yaml

pkg/graph/constructor.go, pkg/graph/constructor_test.go
Fixes #7682 
- Add channel to event lineage graph as a vertex
- Add another vertex and edge to the graph if there is a DLS for the channel
- Unit tests for both scenarios
=> feat: add channels to event lineage graph

pkg/adapter/mtping/runner_test.go, pkg/adapter/v2/main.go, pkg/scheduler/state/helpers.go, pkg/scheduler/state/state.go, pkg/scheduler/statefulset/autoscaler.go, pkg/scheduler/statefulset/scheduler_test.go, test/lib/await.go, test/lib/duck/resource_checks.go, test/lib/duck/serving_checks.go, test/lib/recordevents/event_info_store.go, test/lib/test_runner.go, test/lib/tracker.go, test/rekt/features/broker/control_plane.go, test/rekt/features/channel/control_plane.go, test/rekt/features/channel/data_plane.go, test/rekt/features/knconf/control_plane.go, test/rekt/resources/addressable/addressable.go, test/rekt/resources/broker/broker.go, test/rekt/resources/eventtype/eventtype.go, test/upgrade/prober/sender.go, test/upgrade/prober/verify.go, test/upgrade/prober/wathola/receiver/services_test.go, test/upgrade/prober/wathola/sender/services_test.go
…ilContextTimeout
Fixes #7730
-
-
-
```release-note
NONE
```
**Docs**
=> Replace all usages of deprecated wait.PollImmediate with wait.PollUntilContextTimeout

config/core/webhooks/config-validation.yaml
The webhook is currently handling all ConfigMaps in the cluster.
- Reduce the scope for the Config validation webhook to only the `knative-eventing` namespace.
```release-note
Reduce the scope for the Config validation webhook to only the `knative-eventing` namespace.
```
**Docs**
/kind bug
=> Reduce the scope for the Config validation webhook to only the `knative-eventing` namespace.

config/core/resources/subscription.yaml, docs/eventing-api.md, pkg/apis/messaging/v1/subscription_types.go
Fixes #7796
- :gift: Updated channel namespace field for subscriptions
Notes: I used the namespace field in kreference for channels instead of having a separate field channelNamespace.
```release-note
```
**Docs**
=> CrossNamespace: updated namespace for subscription

.github/workflows/knative-downstream.yaml
Note: this is not eventing-kafka-broker
=> Remove eventing-kafka from downstream tests as it's deprecated

pkg/eventingtls/trust_bundle.go, pkg/reconciler/apiserversource/apiserversource_test.go, pkg/reconciler/apiserversource/controller.go, pkg/reconciler/containersource/controller.go, pkg/reconciler/sinkbinding/controller.go
- Add suffix to user's namespace trust bundles
- Only delete trust bundles we're owners
- Improve queue logic to re-reconcile objects based on which trust bundle changes and in which namespace
=> Improve trust bundle propagation

pkg/reconciler/sinkbinding/sinkbinding.go
- :bug: Remove sinkbindings OIDC token secret when not needed
- :bug: Set Sinkbindings .status.oidcTokenSecretName always (prevent empty oidcTokenSecretName field in case we had a reconcile issue before)
=> Remove sinkbindings OIDC token secret when not needed and fix status setting

pkg/graph/lineage.go, pkg/graph/lineage_test.go, pkg/graph/types.go
Fixes #7677 
Originally, I had planned to de-duplicate paths in the lineage graph on the backend, but I realized we may want to use some of the duplicated info when displaying on the frontend. As such, this PR adds an implementation that will find every possible path in the graph starting at the source vertices, but it won't de-duplicate repeated paths between two or more source vertices
- Add method to find all source vertices in a graph
- Calculate lineage from each source vertex
=> feat: add initial pathfinding algorithm

config/channels/in-memory-channel/configmaps/observability.yaml, config/channels/in-memory-channel/configmaps/tracing.yaml
Fixes https://github.com/knative/eventing/issues/7809
- :bug: remove redundant `config-observability` and `config-tracing` config maps for `in-memory-channel`.
No
**Docs**
No documentation changes required I think.
=> fix: remove duplicate configMaps

pkg/channel/fanout/fanout_event_handler.go
Fixes #7869
We were always recording the metrics once, and then if there was http or https we were recording the metric a second time. This fixes that to only do the recording of metrics once with the scheme set.
- Remove the extra call to record the metrics
```release-note
:bug: The IMC dispatcher metrics now correctly record the metrics once per event when there is only one request scheme, instead of twice
```
=> fix: imc dispatcher doesn't have duplicate reporting of metrics

pkg/apis/sources/v1/container_lifecycle.go, pkg/apis/sources/v1/container_lifecycle_test.go, pkg/reconciler/containersource/containersource.go, pkg/reconciler/containersource/containersource_test.go, pkg/reconciler/containersource/controller.go, pkg/reconciler/containersource/controller_test.go, pkg/reconciler/testing/v1/containersource.go
Backport of #7890 (without e2e tests, as they require a reconciler-test update)
=> [release-1.14] Containersource use OIDC identity of corresponding SinkBinding

test/experimental/features/eventtype_autocreate/features.go, test/rekt/features/apiserversource/data_plane.go, test/rekt/features/pingsource/features.go
Fixes #7629 
Add check for EventType Reference in tests
=> EventType tests verify the type under spec.reference 

pkg/apis/sources/v1/container_lifecycle.go, pkg/apis/sources/v1/container_lifecycle_test.go, pkg/reconciler/containersource/containersource.go, pkg/reconciler/containersource/containersource_test.go, pkg/reconciler/containersource/controller.go, pkg/reconciler/containersource/controller_test.go, pkg/reconciler/testing/v1/containersource.go
Backport of #7890 (without e2e tests, as they require a reconciler-test update).
Manual backport, as of https://github.com/knative/eventing/pull/7892#issuecomment-2096536952
=> [release-1.13] Containersource use OIDC identity of corresponding SinkBinding

test/rekt/features/broker/oidc_feature.go, test/rekt/features/channel/oidc_feature.go, test/rekt/features/pingsource/oidc_feature.go, test/rekt/resources/subscription/subscription.go
Adding some e2e tests to verify, that the senders identity from `.status.auth` was used for authenticating the request.
=> Add e2e test to verify used sender identity is correct

test/rekt/features/trigger/feature.go, test/rekt/resources/trigger/trigger.go, test/rekt/resources/trigger/trigger.yaml
Locally, this patch fixes the bug seen in https://github.com/knative-extensions/eventing-kafka-broker/pull/3819. It looks like we weren't setting the annotation correctly on the trigger in the tests, so the ordered config was not applied.
- Set the trigger annotation properly
=> fix: trigger tests set annotations correctly now

test/rekt/features/broker/oidc_feature.go, test/rekt/features/channel/oidc_feature.go, test/rekt/features/containersource/oidc_feature.go, test/rekt/features/pingsource/oidc_feature.go
As per title, as they tend to flake. E.g.
```
TestContainerSourceSendsEventsWithOIDC/SendsEventsWithSinkRefOIDC/Assert/containersource_as_event_source_uses_containersources_identity_for_OIDC
=== PAUSE TestContainerSourceSendsEventsWithOIDC/SendsEventsWithSinkRefOIDC/Assert/containersource_as_event_source_uses_containersources_identity_for_OIDC
=== CONT  TestContainerSourceSendsEventsWithOIDC/SendsEventsWithSinkRefOIDC/Assert/containersource_as_event_source_uses_containersources_identity_for_OIDC
event_info_store.go:181: Assert in range failed: expected <= 1 events, saw 7
knative.dev/reconciler-test/pkg/eventshub.(*Store).AssertInRange
/go/src/github.com/openshift-knative/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go:181 …
```
=> Update e2e tests for OIDC sender identity matching to be a bit more resilient

pkg/reconciler/testing/v1/factory.go
This should fix the issues with subject access reviews we are seeing in unit tests
- Add a reactor that  handles create requests for subject access reviews
Note: this can probably be improved upon (for example also looking at clusterroles/clusterrolebindings), but this should be good enough for what we are testing now so I would like to merge this first before making improvements
=> feat: added fake client reactor for subject access reviews

test/experimental/eventtype_autocreate_test.go, test/experimental/features/eventtype_autocreate/features.go
This is a follow-up to https://github.com/knative/eventing/pull/7888
All of the tests should be asserting the eventtype's reference.
- Assert eventtype reference for InMemoryChannel
- Remove TestContainerSourceEventTypeAutoCreate as automatic EventType creation for ContainerSource is not supported
```release-note
```
**Docs**
=> Assert EventTypes references for IMC test

pkg/channel/fanout/fanout_event_handler.go, pkg/kncloudevents/event_dispatcher.go
Rather than reporting metrics (and scheme tag) as an aggregate for all subscriptions, we will report them for each individual subscription with the correct subscriber's scheme.
=> Fix IMC metrics for transport encryption

config/core/configmaps/features.yaml
it will still be disabled by default as we can't really enable it automatically
given that it depends on the cert-manager installation and a few more
setup prerequisites.
```release-note
`transport-encryption` is now a Beta feature.
```
**Docs**
https://github.com/knative/docs/pull/5967
=> Make transport-encryption a Beta feature

pkg/crossnamespace/validation.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/v1/factory.go
Fixes how we create the Resources field in a SubjectAccessReview. The SAR expects this in a form like `brokers`, but we currently pass it `Broker`. This leads to it not working.
- Update the crossnamespace validation code to create a RBAC resources field from an object Kind
- Update the test factory to validate that the resources field is correct
=> SubjectAccessReviews resources correction

pkg/eventingtls/trust_bundle.go, pkg/reconciler/apiserversource/apiserversource_test.go
Fix TLS-related flaky tests
Fix update conflict and already exists errors:
```
wait.go:200: test-yxfagqey/sinkbinding-yilpeqdr condition is {"type":"Ready","status":"False","lastTransitionTime":"2024-05-15T13:29:09Z","reason":"TrustBundlePropagation","message":"failed to update ConfigMap test-yxfagqey/trust-bundle-pvxfnqkskne-bundle: Operation cannot be fulfilled on configmaps \"trust-bundle-pvxfnqkskne-bundle\": the object has been modified; please apply your changes to the latest version and try again"}
```
=> Fix trust bundle propagation

pkg/kncloudevents/event_dispatcher.go
Currently we see the `TestEventTransformationForTriggerV1BrokerV1` e2e test failing, when the `eventtype-auto-create` FF is enabled. This is because we're not copying the message at the right place.
From the docs:
> CopyMessage **reads m** once and creates an in-memory copy depending on the encoding of m. The returned copy is not dependent on any transport and can be visited many times. When the copy can be forgot, the copied message must be finished with Finish() message to release the memory. transformers can be nil and this function guarantees that they are invoked only once during the encoding process
This means, that `m` gets read by `buffering.CopyMessage()` and thus is "used" for further usages.
/cherry-pick release-1.14
=> Copy message before passing it to eventtype autocreate handler

config/core/resources/eventtype.yaml
Currently we see on some eventtype tests the following warnings in the dispatcher:
```
{"level":"warn","ts":"2024-05-22T17:19:09.574Z","logger":"inmemorychannel-dispatcher","caller":"logging/warning_handler.go:32","msg":"API Warning: unknown field \"spec.reference.address\"","commit":"0e14da4-dirty","knative.dev/pod":"imc-dispatcher-59cb79846b-vbsgx"}
```
This PR addresses it and adds the `address` field to the CRD, as described in https://github.com/knative/pkg/blob/99e1685a799787390ad8cb32bce249173cfda7a6/apis/duck/v1/knative_reference.go#L29-L56
=> Update eventtype CRD to include `.spec.reference.address`

test/config/config-features.yaml
Enabling the `eventtype-auto-create` feature flag for e2e tests.
=> Enable `eventtype-auto-create` feature flag for e2e tests

.github/workflows/kind-e2e.yaml
Removing the rekt tests from the Github actions KinD e2e tests, as they are pretty unstable in our tier and we run them in Prow anyhow as a required job.
/cc @pierDipi
=> Remove rekt test from GH actions e2e test run

cmd/jobsink/main.go
Remove second call to `StartInformers(ctx.Done(), informers...)`
=> JobSink: don't start informers twice

config/200-crossnamespace-clusterrole.yaml, config/channels/in-memory-channel/roles/crossnamespace-clusterrole.yaml, config/core/200-eventing-serviceaccount.yaml, config/core/roles/controller-clusterroles.yaml, config/core/roles/crossnamespace-clusterrole.yaml
Fixes the clusterrole for the cross namespace feature to work
- Add knsubscribe for imc to eventing controller
- Add knsubscribe for broker to eventing controller
=> fix: eventing clusterrole has correct knsubscribe permissions

cmd/jobsink/main.go
Signed-off-by: babugeet <abhinandhbg@gmail.com>
Fixes #
https://github.com/knative/eventing/issues/7963
Adding the mount path as Environment variable for container of pod spawned by the Job
-
-
-
=> Adding mount path as env variable in container

config/brokers/mt-channel-broker/deployments/broker-filter.yaml, config/brokers/mt-channel-broker/deployments/broker-ingress.yaml, config/brokers/mt-channel-broker/deployments/controller.yaml, config/channels/in-memory-channel/deployments/controller.yaml, config/channels/in-memory-channel/deployments/dispatcher.yaml, config/core/deployments/controller.yaml, config/core/deployments/pingsource-mt-adapter.yaml, config/core/deployments/webhook.yaml
This will remove the circular dependency with the SinkBinding webhook and the system components
=> Exclude core deployments from SinkBinding webhook injection

pkg/graph/transforms.go
Follow up on review comments in #7909 
- Make regex more closely match the allowed values in the cloudevents spec
- Add comments explaining the complicated parts of the code
- Handle malformed variables
=> fix: add comments and improve regex for attribute filter transform function

test/rekt/resources/configmap/config-features.yaml, test/rekt/resources/configmap/configmap.go, test/rekt/resources/configmap/configmap_test.go
This will help with testing the CA trust bundle rotation.
=> Support arbitrary data for rekt configmap package

cmd/webhook/main.go, config/core/roles/webhook-clusterrole.yaml, docs/sink/jobsink-invalid.yaml, pkg/apis/sinks/register.go, pkg/apis/sinks/v1alpha1/job_sink_validation.go
Validate `spec.job` using a dry-run create of the given job.
=> JobSink: add webhook validation for spec.job

config/core/configmaps/features.yaml, pkg/apis/feature/features.go, pkg/apis/feature/features_test.go, pkg/apis/feature/flag_names.go, pkg/apis/feature/testdata/config-features.yaml
Fixes #7974 
- Add `default-authorization-mode` feature flag
```release-note
```
**Docs**
=> Add `default-authorization-mode` feature flag

pkg/apis/eventing/v1alpha1/eventpolicy_validation.go, pkg/apis/eventing/v1alpha1/eventpolicy_validation_test.go
`*` is only allowed as suffix glob
=> Add validation for EventPolicy sub suffix matching

pkg/auth/event_policy.go, pkg/auth/event_policy_test.go
Fixes #7985
Add library to support on AuthZ work
- :gift: `GetEventPoliciesForResource(eplister, gvk, meta)` returns a list of EventPolicies which apply for a given resource (gvk & meta)
- :gift: `ResolveSubjects(resolver, eventPolicy)` returns a list of resolved subjects of an EventPolicy
- :gift: Function `SubjectContained(sub, allowedSubs)` to check if a given subject is part of a list of allowed subjects (includes `*` matching)
Requires https://github.com/knative/pkg/pull/3056 to be merged
/hold
=> Add authz library

cmd/jobsink/main.go, pkg/apis/feature/store.go, test/rekt/features/jobsink/jobsink.go, test/rekt/job_sink_test.go
Fixes #
- Test JobSink's OIDC support (success and failure case)
- Validate returned status codes for various cases (202, 401)
```release-note
```
**Docs**
=> JobSink: Test OIDC support

config/post-install/clusterrole.yaml, config/post-install/storage-version-migrator.yaml
This is not necessary as we only have one version but it's better to have it from the start
=> Add JobSink to storage version migration

test/rekt/features/broker/topology_test.go
`TestCreateExpectedEventPatterns` will start to fail with go 1.22 (see https://github.com/knative/eventing/pull/8019#issuecomment-2182882142):
```
$ go test ./test/rekt/features/broker/... -run TestCreateExpectedEventPatterns
ok      knative.dev/eventing/test/rekt/features/broker  0.015s
$ GOEXPERIMENT=loopvar go test ./test/rekt/features/broker/... -run TestCreateExpectedEventPatterns
--- FAIL: TestCreateExpectedEventPatterns (0.00s)
--- FAIL: TestCreateExpectedEventPatterns/t1,_one_retry,_one_failure,_both_t0_/_t1_get_it,_t1dlq_gets_it_too (0.00s)
topology_test.go:227: t1, one retry, one failure, both t0 / t1 get it, t1dlq gets it too: Maps unequal: want:
map[brokerdlq:{Success:[] Interval:[]} t0:{Success:[true] Interval:[0]} t0dlq:{Success:[] Interval:[]} t1:{Success:[false true] …
```
=> Fix test case in TestCreateExpectedEventPatterns

test/rekt/features/broker/topology_test.go
Similar to #8022 fixing an error in a unit test (`TestCreateExpectedEventDeliveryMap`)
=> Fix test case in `TestCreateExpectedEventDeliveryMap`

test/rekt/resources/eventpolicy/eventpolicy.go, test/rekt/resources/eventpolicy/eventpolicy.yaml, test/rekt/resources/eventpolicy/eventpolicy_test.go
Fixes #8009
Adding helpers for rekt test to work with EventPolicies.
=> Add EventPolicy resource for rekt tests

config/core/resources/channel.yaml, config/core/roles/controller-clusterroles.yaml, docs/eventing-api.md, pkg/apis/duck/v1/channelable_types.go, pkg/apis/duck/v1/zz_generated.deepcopy.go, pkg/apis/messaging/v1/channel_lifecycle.go, pkg/apis/messaging/v1/channel_lifecycle_test.go, pkg/apis/messaging/v1/in_memory_channel_types.go, pkg/apis/messaging/v1/zz_generated.deepcopy.go, pkg/auth/event_policy.go, pkg/reconciler/channel/channel.go, pkg/reconciler/channel/channel_test.go, pkg/reconciler/channel/controller.go, pkg/reconciler/channel/controller_test.go, pkg/reconciler/channel/resources/eventpolicy.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go, pkg/reconciler/subscription/subscription_test.go, pkg/reconciler/testing/v1/channel.go, pkg/reconciler/testing/v1/eventpolicy.go
Fixes #8013
- :gift: List `EventPolicies` in the channels `.status.policies`, which apply for it
- :gift: Add the `EventPoliciesReady` condition to indicate, if the referenced policies are Ready
- :gift: Create a copy of the EventPolicies applying for the Channel, to target the backing channel
```release-note
List applying EventPolicies in Channels status and propagate EventPolicies to backing channel
```
=> List applying policies in Channel and propagate EventPolicies to underlying channel

.github/.dependabot.yaml
As per title
(The [update-actions](https://github.com/knative-extensions/knobots/actions/runs/9278824473/job/25530427713) job seems to do this only for some specific worklows)
=> Update Github actions automatically

pkg/reconciler/channel/channel_test.go, pkg/reconciler/channel/resources/eventpolicy.go
We see sometimes the following error in the eventing-controller:
```
{"level":"info","ts":"2024-06-25T10:56:58.973Z","logger":"controller.event-broadcaster","caller":"record/event.go:364","msg":"Event(v1.ObjectReference{Kind:\"Channel\", Namespace:\"channel-ns\", Name:\"my-channel\", UID:\"41401bb0-d09f-45ca-b1cf-9ded4ea2bf78\", APIVersion:\"messaging.knative.dev/v1\", ResourceVersion:\"13158\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' could not reconcile backing channels (channel-ns/my-channel) event policies: could not reconcile EventPolicy channel-ns/event-policy for backing channel channel-ns/my-channel: could not create EventPolicy channel-ns/event-policy-my-channel: EventPolicy.eventing.knative.dev \"event-policy-my-channel\" is invalid: …
```
=> Set APIVersion and Kind of EventPolicy manually in OwnerReference of backing channels policy

.codecov.yaml
Instead of failing every PR, check for coverage drop. In this way, the coverage can only raise naturally.
- :bug: Codecov reject any coverage drop
/kind bug
=> :bug: Codecov reject any coverage drop

config/core/resources/jobsink.yaml, docs/eventing-api.md, pkg/apis/sinks/v1alpha1/job_sink_lifecycle.go, pkg/apis/sinks/v1alpha1/job_sink_lifecycle_test.go, pkg/apis/sinks/v1alpha1/job_sink_types.go, pkg/apis/sinks/v1alpha1/test_helpers.go, pkg/apis/sinks/v1alpha1/zz_generated.deepcopy.go, pkg/reconciler/jobsink/controller.go, pkg/reconciler/jobsink/jobsink.go, pkg/reconciler/jobsink/jobsink_test.go, pkg/reconciler/sequence/sequence.go, pkg/reconciler/testing/v1/factory.go, pkg/reconciler/testing/v1/listers.go, pkg/reconciler/testing/v1alpha1/jobsink.go
Fixes #8062 
- 🎁 List EventPolicies in the JobSink .status.policies, which apply for it.
- 🎁 Add the EventPoliciesReady condition to indicate, if the referenced policies are Ready
- 🎁 Add unit and integration tests
```release-note
List applying EventPolicies in JobSink status
```
**Docs**
=> List applying policies in job sink

pkg/apis/eventing/v1/broker_lifecycle.go, pkg/apis/eventing/v1/broker_lifecycle_test.go, pkg/apis/eventing/v1/test_helper.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/controller.go, pkg/reconciler/broker/controller_test.go, pkg/reconciler/testing/v1/broker.go
Fixes #7976 
- :gift: List `EventPolicies` in the Brokers `.status.policies`, which apply for it
- :gift: Add the `EventPoliciesReady` condition to indicate, if the referenced policies are Ready
```release-note
List applying EventPolicies in Brokers status
```
=> List applying EventPolicies in Brokers status

config/brokers/mt-channel-broker/roles/filter-clusterrole.yaml, config/brokers/mt-channel-broker/roles/ingress-clusterrole.yaml, config/channels/in-memory-channel/roles/dispatcher-clusterrole.yaml, config/core/roles/job-sink-clusterrole.yaml, config/core/roles/webhook-clusterrole.yaml, pkg/auth/event_policy.go, pkg/auth/token_verifier.go, pkg/broker/filter/filter_handler_test.go, pkg/broker/ingress/ingress_handler_test.go, pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
Updates the TokenVerifier to verify AuthZ too
* providing `VerifyRequest()` which bundles AuthN and AuthZ checks
* deprecating `VerifyJWTFromRequest()` which only checks AuthN (switch to `VerifyRequest()` will be done in #7980 and #7981)
=> Update TokenVerifier to verify AuthZ too

hack/check_k8s_version.go, hack/install.sh, test/version_check/check_k8s_version.go
Fixes #7813 
Please categorize your changes:
- :gift: Added a minimum Kubernetes version check in `install.sh`.
- `check_k8s_version.go` connects to a Kubernetes cluster using the kubeconfig file, then checks if the cluster's version is compatible with the minimum required version specified by Knative. If the version is compatible, it prints a success message; otherwise, it logs an error and exits.
- When using k8s v1.27.0:
- When using k8s v1.28.0: (minimum specified version)
```release-note
```
**Docs**
=> Add Kubernetes Version Check to Installation Script

test/e2e-common.sh
Currently, re-running the `./hack/install.sh` script fails because the knsubscribe clusterrolebinding was already created.
- Delete the clusterrolebinding each time the script is run, ignoring not found errors
=> fix(test): creating the knsubscribe clusterrolebinding does not cause install script to fail

config/300-eventpolicy.yaml
Should we add this symbolic link, for consistency?
/cc @pierDipi
=> Adding symbolic link for event policy type. 

docs/eventing-api.md, pkg/apis/duck/v1/delivery_types.go, pkg/apis/duck/v1/delivery_types_test.go, pkg/apis/duck/v1/zz_generated.deepcopy.go
Fixes #8073 
added format flag to deliverytype struct to support more destination of cloudevents
-
-
-
```release-note
```
**Docs**
=> feat:added format flag

docs/eventing-api.md, pkg/apis/duck/v1/delivery_types.go, pkg/apis/duck/v1/delivery_types_test.go, pkg/apis/duck/v1/zz_generated.deepcopy.go
Removes the delivery format option we had before, and aligns the code with the approach used for other similar fields in the delivery spec.
- remove the ingress option from the format type
- create a type alias and some constants for the format type options
=> fix: remove ingress option from delivery format

pkg/apis/eventing/v1beta1/eventtype_defaults.go, pkg/apis/eventing/v1beta1/eventtype_defaults_test.go
Fixes #8045
- Remove the default broker logic from the v1beta1 defaulting logic since that is still being run for every eventtype object (even though we store v1beta2 currently)
```release-note
:bug: EventType v1beta3 resources no longer have a default broker reference set, as they can have no reference.
```
=> fix: et v1beta3 does not have broker set by default

pkg/kncloudevents/event_dispatcher_test.go
Fixes #7955 
- Use a different port for each receiver in the tls dispatcher tests so that they don't fail due to a port being in use
=> fix: tls dispatcher tests all use different ports

config/core/resources/eventtype.yaml, pkg/apis/eventing/v1beta3/eventtype_lifecycle.go, pkg/reconciler/eventtype/controller.go, pkg/reconciler/eventtype/controller_test.go, pkg/reconciler/eventtype/eventtype.go, pkg/reconciler/eventtype/eventtype_test.go, pkg/reconciler/testing/v1/eventtype.go, pkg/reconciler/testing/v1/listers.go
This lets us reconcile eventtype v1beta3 resources with the updated eventtype v1beta3 logic.
- If no reference is set, reconcile to ready
- Reconcile on v1beta3 struct, not v1beta2
```release-note
EventTypes no longer need a reference to be set on them
```
=> feat: reconcile eventtype v1beta3 resources

config/core/resources/eventtype.yaml
Fixes a typo from https://github.com/knative/eventing/pull/8087 
- as per title
```release-note
```
**Docs**
=> EventType V1B3: Use proper jsonpath for additional column printer

pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/broker/resources/eventpolicy.go, pkg/reconciler/broker/resources/eventpolicy_test.go, pkg/reconciler/testing/v1/eventpolicy.go
Fixes #7982 
- 🎁 Reconcile Event Policies for MT-Broker
- 🎁 Create EventPolicy for underlying Channel in case OIDC Authentication is enabled
- 🎁 Delete orphaned EventPolicies.
```release-note
Reconcile Event Policies for MT-Broker
```
**Docs**
=> Reconcile event policies for mt-broker

pkg/apis/flows/v1/parallel_lifecycle.go, pkg/apis/flows/v1/parallel_lifecycle_test.go, pkg/reconciler/parallel/controller.go, pkg/reconciler/parallel/controller_test.go, pkg/reconciler/parallel/parallel.go, pkg/reconciler/parallel/parallel_test.go, pkg/reconciler/testing/v1/parallel.go
Fixes #7979 
🎁 List EventPolicies in the Parallel .status.policies, which apply for it.
🎁 Add the EventPoliciesReady condition to indicate, if the referenced policies are Ready
```release-note
List applying EventPolicies in Parallel status
```
**Docs**
=> List applying policies in Parallel

cmd/webhook/main.go, pkg/apis/eventing/v1alpha1/eventpolicy_validation.go, pkg/apis/eventing/v1alpha1/eventpolicy_validation_test.go, pkg/reconciler/channel/channel_test.go
Fixes #7972 
- :gift: Added EventPolicy Webhook
```release-note
Added EventPolicy Webhook
```
=> Added EventPolicy Webhook

pkg/broker/ingress/ingress_handler.go
Fixes #7980 
-  Replace the logic of deprecated function `VerifyJWTFromRequest` with `VerifyRequest`  in ingress_handler
- Handle both AuthN and AuthZ in the request
- Check `broker.Status.Address.audience` before proceeding verification
```release-note
```
**Docs**
=> mt-broker ingress: Reject unauthorized requests

.github/workflows/weekly-office-hours-slack-reminder.yaml
This PR adds a github action that sends a reminder one hour before the weekly office hours to slack (similar to the TOC review messages and Knative UX messages)
- Send a slack message one hour before the office hours with a link to the zoom meeting
=> feat: add github workflow to send slack reminder for office hours

.github/workflows/weekly-office-hours-slack-reminder.yaml
Fixes the syntax error in the weekly reminder workflow
=> fix: workflow syntax for weekly reminder

pkg/reconciler/sequence/controller.go, pkg/reconciler/sequence/sequence.go
In the sequence reconciler `feature.FromContext(ctx)` always returns the default feature flags as the context is not populated with the `ConfigStore`
=> Sequence reconciler reads and watch the config-features configmap

hack/update-cert-manager.sh, third_party/cert-manager/02-trust-manager.yaml
The support for trust manger s390x images are available from version 0.12.0 of trust manager. Hence upgrading the trust manager to 0.12.0.
=> update trust-manager to version 0.12.0

pkg/apis/eventing/v1alpha1/eventpolicy_defaults.go, pkg/apis/eventing/v1alpha1/eventpolicy_defaults_test.go
Defaulting the `.spec.from[].namespace` to the event policy namespace as written in the docs
https://github.com/knative/eventing/blob/32f849105ca5c37454079607b91b11ba61e91662/pkg/apis/eventing/v1alpha1/eventpolicy_types.go#L122-L126
=> Default EventPolicy `.spec.from[].namespace` to EventPolicies namespace

test/e2e-rekt-tests.sh, test/rekt/broker_test.go, test/rekt/features/broker/authz_feature.go, test/rekt/resources/eventpolicy/eventpolicy.go, test/rekt/resources/eventpolicy/eventpolicy_test.go
Fixes #8131
- :gift: Run authorization tests as part of e2e test suite (test with `AuthZ` in their name)
- :gift: Add e2e tests for Broker authorization
=> Add e2e test for Broker authorization

pkg/reconciler/broker/resources/eventpolicy.go
Currently seeing the following error in the controller logs:
```
failed to reconcile EventPolicy for Broker broker-iinpthqx: failed to create EventPolicy for Broker broker-iinpthqx-ep-broker-iinpthqx-kne-trigger: EventPolicy.eventing.knative.dev \"broker-iinpthqx-ep-broker-iinpthqx-kne-trigger\" is invalid: metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty
```
This PR addresses it and sets the UID in the Owner reference.
- :bug: Set UID in Brokers backing channels EventPolicies OwnerReference
=> Set UID in Brokers backing channels EventPolicies OwnerReference

pkg/duck/listable.go, pkg/reconciler/subscription/subscription.go
Helps reduce flakes in the cross namespace feature by letting the tracker track references in a different namespace than the object.
- Add methods that track references in a provided ns, rather than that of the object.
=> fix: tracker can track resources in different ns

cmd/broker/filter/main.go, config/brokers/mt-channel-broker/roles/filter-clusterrole.yaml, pkg/auth/token_verifier.go, pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/reconciler/broker/resources/subscription.go
Fixes #7989
- :gift: Update mt-broker-filter to allow only requests from the triggers subscription OIDC id
```release-note
mt-broker-filter: Allow only requests from Triggers Subscriptions OIDC ID
```
=> mt-broker-filter: Allow only requests from Triggers Subscriptions OIDC ID

pkg/eventfilter/subscriptionsapi/all_filter.go, pkg/eventfilter/subscriptionsapi/any_filter.go
The filters field is implicitly an `AllFilter`, which means that even if a user only creates a single filter two filters will get created. Similarly, if for some reason a user creates an all filter or any filter with only a single subfilter, we should not create the extra "wrapper" filter.
- Only create an all or any filter if the filters list is > 1
=> feat: reduced unnecessary creation of filters

pkg/reconciler/channel/channel_test.go, pkg/reconciler/channel/resources/eventpolicy.go, pkg/reconciler/parallel/parallel_test.go, pkg/reconciler/parallel/resources/eventpolicy.go, pkg/reconciler/sequence/resources/eventpolicy.go, pkg/reconciler/sequence/sequence_test.go, pkg/reconciler/testing/v1/eventpolicy.go
The filters of the parent policy of Channels/Parallels & Sequences are not propagated to the underlying channels EventPolicies.
This PR fixes it.
Found on adding e2e tests in #8162
=> Fix: propagate EventPolicy filter to underlying Channels EventPolicy

pkg/channel/event_receiver.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, test/rekt/channel_test.go
Fixes #7981
Follow up on #8123
- :gift: Verify authorization in Channel ingress
- :gift: Add support for authorization in InMemoryChannel
```release-note
InMemoryChannel ingress: Reject unauthorized requests
```
=> Support authorization in Channel ingress

test/rekt/features/authz/addressable_authz_conformance.go
Fix to use the correct readyness check in the AuthZ e2e tests
=> Fix: Use correct readyness check in AuthZ conformance tests

config/core/resources/jobsink.yaml, test/rekt/features/jobsink/jobsink.go
Currently the JobSinks CRD does not have a field for the ObservedGeneration in its status, while having the duck.status:
https://github.com/knative/eventing/blob/bf945f909e685d4e26c83afe5a32f00fabccb3e8/pkg/apis/sinks/v1alpha1/job_sink_types.go#L63
which has this field:
https://github.com/knative/pkg/blob/89743d9bbf7cc691f156b945bb29f96989da4e03/apis/duck/v1/status_types.go#L42
This leads to the rekt jobsinks.IsReady() check to not succeed.
This PR addresses it and adds the field in the CRD.
=> Fix JobSink to have ObservedGeneration in status

cmd/jobsink/main.go, test/rekt/job_sink_test.go, test/rekt/resources/jobsink/jobsink.go
Fixes #8166
- :gift: Reject unauthorized requests in the JobSink
```release-note
JobSink: Reject unauthorized requests
```
WIP, as it needs the following before:
=> JobSink: Reject unauthorized requests

test/rekt/features/authz/addressable_authz_conformance.go
Currently the authz e2e conformance tests, test all authz features. This includes also to respect the filters.
Anyhow not all AuthZ supporting implementations implement the full feature set yet. For example EKB should support basic AuthZ - but no filtering yet. Anyhow it would be great to already have the possibility to enable the AuthZ e2e tests.
This PR addresses it and splits the AuthZ e2e tests and thus allows more fine grained tests.
=> Split AuthZ e2e tests

pkg/auth/event_policy.go
Add another function to auth package to allow updating a resources `AppliedEventPoliciesStatus` based on a given list of applying policies.
=> AuthZ: Provide function to update AppliedEventPoliciesStatus based on a given list of applying policies

cmd/in_memory/channel_dispatcher/main.go
The IMC dispatcher is using the same server receiving events for k8s readiness and liveness probes, so we don't need the controller internal health server to be running.
The controller internal health server is using the same port which leads to this error:
```
2024-07-31T15:58:53.582Z	error	inmemorychannel-dispatcher	sharedmain/main.go:334	Error while running server	{"commit": "b7bfc92", "knative.dev/pod": "imc-dispatcher-696d94588d-j7fr5", "error": "listen tcp :8080: bind: address already in use"}
knative.dev/pkg/injection/sharedmain.MainWithConfig
knative.dev/pkg@v0.0.0-20240716082220-4355f0c73608/injection/sharedmain/main.go:334
knative.dev/pkg/injection/sharedmain.MainWithContext
knative.dev/pkg@v0.0.0-20240716082220-4355f0c73608/injection/sharedmain/main.go:209
main.main …
```
=> Disable controller default health probes in the IMC dispatcher

test/rekt/features/broker/feature.go, test/upgrade/upgrade.go, test/upgrade/upgrade_test.go
- Refactor broker transformation test so that it can be used in upgrade tests (this will also be reused in knative-extensions/eventing-kafka-broker, see [WIP pull request](https://github.com/knative-extensions/eventing-kafka-broker/pull/4095) )
- Include Broker transformation test in upgrade test suite
- Fix `DurableFeature`. The `FeatureF` must be a function that can be called multiple times on demand, and it will create a new feature every time - with different resources to prevent clash with existing resources.
```release-note
```
**Docs**
=> Add broker transformation test to upgrade tests

cmd/broker/filter/main.go, cmd/broker/ingress/main.go, cmd/jobsink/main.go, pkg/auth/token_verifier.go, pkg/auth/verifier.go, pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/broker/ingress/ingress_handler.go, pkg/broker/ingress/ingress_handler_test.go, pkg/channel/event_receiver.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Currently the pkg/auth package depends on the eventpolicy informer (through the tokenverifier), requiring everything what imports `knative.dev/eventing/pkg/auth` to have permissions to read&list EventPolicies.
This leads to the following issues e.g. for PingSource (which does not need the TokenVerifier):
```
W0916 14:29:26.690900       1 reflector.go:547] k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: failed to list *v1alpha1.EventPolicy: eventpolicies.eventing.knative.dev is forbidden: User "system:serviceaccount:knative-eventing:pingsource-mt-adapter" cannot list resource "eventpolicies" in API group "eventing.knative.dev" at the cluster scope
E0916 14:29:26.690991       1 reflector.go:150] k8s.io/client-go@v0.30.3/tools/cache/reflector.go:232: Failed to watch …
```
=> Make auth package indepent from eventpolicy informer

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/scheduler/state/helpers.go, pkg/scheduler/state/state.go, pkg/scheduler/state/state_test.go, pkg/scheduler/statefulset/autoscaler.go, pkg/scheduler/statefulset/autoscaler_test.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/statefulset/scheduler_test.go
Currently, the scheduler and autoscaler are single threads and use a lock to prevent multiple scheduling and autoscaling decision from happening in parallel; this is not a problem for our use cases, however, the multiple `wait` currently present are slowing down recovery time.
From my testing, if I delete and recreate the Kafka control plane and data plane (sort of simulates an upgrade), without this patch it takes hours to recover when there are 400 triggers or 20 minutes when there are 100 triggers; with the patch it is immediate (only a 2/3 minutes with 400 triggers).
- Remove `wait`s from state builder and autoscaler
- Add additional debug logs
- Use logger provided through the context as opposed to gloabal loggers in each individual component to preserve `knative/pkg` resource aware …
=> Remove scheduler `wait`s to speed up recovery time

config/post-install/storage-version-migrator.yaml, pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go, test/config/monitoring/monitoring.yaml, test/upgrade/prober/forwarder.go, test/upgrade/prober/receiver.go, test/upgrade/prober/sender.go, test/upgrade/prober/verify.go
Ref: https://github.com/knative/eventing/issues/8204
=> Add Istio inject label

pkg/auth/serviceaccount.go, pkg/auth/serviceaccount_test.go
The DeepDerivative does not treat the default value of CreationTimestamp (metav1.Time{}) as a "null" value, so it will always compare to actual CreationTimestamp of the existing ServiceAccount.
The proposed changes to the serviceaccount_test.go were originally written by @pierDipi 
- :broom: Fix unnecessary updates of auth ServiceAccounts
=> workaround DeepDerivative CreationTimestamp comparison

cmd/broker/filter/main.go, cmd/broker/ingress/main.go, pkg/eventtype/eventtypes.go, pkg/eventtype/eventtypes_test.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go, pkg/reconciler/inmemorychannel/dispatcher/controller_test.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, pkg/reconciler/testing/v1beta3/eventtype.go, pkg/reconciler/testing/v1beta3/factory.go, pkg/reconciler/testing/v1beta3/listers.go
Fixes #8098 
- Autocreate v1beta3 eventtypes
- Create v1beta3 test reconciler package
- Update autocreate handlers to use appropriate v1beta3 interfaces
```release-note
EventType autocreate now creates v1beta3 EventTypes
```
=> feat: autocreate v1beta3 eventtypes

pkg/eventtype/eventtypes.go
Follow up on https://github.com/knative/eventing/pull/8276#discussion_r1816527630
- EventTypes autocreated have the `id` attribute required
=> fix: et autocreate makes eventtype id required

config/channels/in-memory-channel/roles/controller-clusterrole.yaml
This is required otherwise MTChannelBasedBroker backed by IMC channel can't forward events to JobSink. The error on ImMemoryChannel is following:
```
failed to get lister for sinks.knative.dev/v1alpha1, Resource=jobsinks:
jobsinks.sinks.knative.dev is forbidden:
User "system:serviceaccount:knative-eventing:imc-controller" cannot list
resource "jobsinks" in API group "sinks.knative.dev" at the cluster
scope
```
Fixes #
-
-
-
```release-note
```
**Docs**
=> Allow imc-controller to list JobSinks

config/channels/in-memory-channel/roles/controller-clusterrole.yaml, config/core/roles/addressable-resolvers-clusterrole.yaml
This will ensure that all ServiceAccounts that are bound to "addressable-resolver" ClusterRole can read JobSinks.
This replaces https://github.com/knative/eventing/commit/2e4d353d579cfafad62d42b585b9a4b96b194ffb because it's more general. The fix was suggested in [PR for Eventing Kafka Broker](https://github.com/knative-extensions/eventing-kafka-broker/pull/4155#issuecomment-2453971704)
Fixes also issues like this for SinkBindings:
```
{"level":"error","ts":"2024-11-04T08:06:16.160Z","logger":"eventing-webhook","caller":"sinkbinding/sinkbinding.go:87",
"msg":"Failed to get Addressable from Destination:
%!w(*fmt.wrapError=&{failed to get lister for
sinks.knative.dev/v1alpha1,
Resource=jobsinks: jobsinks.sinks.knative.dev is forbidden:
User …
```
=> Add jobsinks-addressable-resolver cluster role

test/rekt/features/jobsink/jobsink.go
This allows using Knative Service as the sink in tests simply by adding an option to enviroment for reconciler-test: eventshub.WithKnativeServiceForwarder.
The URL will change from `http://sink-jouanbaf` to `http://sink-jouanbaf.test-ynyxtcbf.svc.cluster.local` in most cases.
Before this change, the sender was getting 404.
Fixes #
-
-
-
```release-note
```
**Docs**
=> Use GetServiceHostname when passing URL to JobSink

pkg/reconciler/integrationsource/resources/containersource.go
Fixes #
- :broom: Update the access/secret key on the K8S secret to be not tied to AWS S3, but be more generic
```release-note
```
**Docs**
=> [chore] Use a generic access/secret key in the secret for AWS connections

pkg/reconciler/integrationsource/resources/containersource.go, pkg/reconciler/integrationsource/resources/containersource_test.go
- just call the generation of `SSL` env-vars once, not for each provided property
```release-note
```
**Docs**
=> [chore] Do not generate SSL env vars for each struct entry, just once per containersource/image

config/core/resources/jobsink.yaml
This PR removes the duplicated observedGeneration in jobsinks.sinks.knative.dev. This was intoduced in https://github.com/knative/eventing/pull/8297
- :bug: Fix duplicated observedGeneration in jobsinks.sinks.knative.dev
=> fix: remove duplicated observedGeneration from jobsinks.sinks.knative.dev

pkg/apis/messaging/v1/in_memory_channel_types.go, pkg/channel/fanout/fanout_event_handler.go, pkg/reconciler/broker/broker.go, pkg/reconciler/broker/broker_test.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go, pkg/reconciler/testing/v1/broker.go, test/rekt/broker_test.go, test/rekt/channel_test.go, test/rekt/features/broker/feature.go, test/rekt/features/channel/features.go, test/rekt/resources/broker/broker.go, test/rekt/resources/broker/broker.yaml, test/rekt/resources/broker/broker_test.go, test/rekt/resources/channel_impl/channel_impl.go, test/rekt/resources/channel_impl/channel_impl.yaml
We switched to use the sync handler by default, however, it was
reported that in some cases, this is not wanted as it slows down
the source event senders since it needs to wait for all subscribers
to receive events.
While sync handler is the best default behavior since reduces lost events in
InMemoryChannel, we want to allow configuring this behavior, while
documenting the downsides (follow up to docs repo)
- Allow configuring (opt-in) IMC async handler 
- Propagate annotations and labels from MTChannelBasedBroker to underlying channel
-
```release-note
Allow configuring (opt-in) IMC async handler 
```
**Docs**
=> Allow configuring (opt-in) IMC async handler 

cmd/jobsink/main.go, cmd/jobsink/main_test.go, hack/e2e-debug.sh, test/rekt/features/jobsink/jobsink.go, test/rekt/job_sink_test.go
As reported in https://github.com/knative/eventing/issues/8323 old
JobSink secrets lead to processing old events again while new events
are lost, even though this _should_ not happen because distinct events
must have different id or source, it's a valid issue as it leaves orphan
secrets.
Using OwnerReference and k8s garbage collection, now a secret created
for a given event is bound to a given Job lifecycle, so that when a job is
deleted, the associated secret will be deleted.
Fixes https://github.com/knative/eventing/issues/8323
- JobSink: Delete secrets associated with jobs when jobs are deleted
- Create Job before Secret to bind the secret to the Job lifecycle via owner reference
-
```release-note
JobSink: bind secrets lifecycle to associated jobs lifecycle. Using …
```
=> JobSink: Delete secrets associated with jobs when jobs are deleted

config/core/resources/integrationsource.yaml, docs/eventing-api.md, pkg/apis/sources/v1alpha1/integration_types.go, pkg/apis/sources/v1alpha1/integration_types_test.go, pkg/apis/sources/v1alpha1/integration_validation.go, pkg/apis/sources/v1alpha1/integration_validation_test.go, pkg/reconciler/integrationsource/resources/containersource.go, pkg/reconciler/integrationsource/resources/containersource_test.go
- starting with custom tags for complicated camel properties, to make the source spec easier to read 
```release-note
```
**Docs**
=> Update Integration API and use custom tags on structs for better readability

pkg/apis/sources/v1alpha1/integration_lifecycle.go
- Fix/correct comments and avoid merge conflicts with Sink PR
```release-note
```
**Docs**
=> chore: correct comments

cmd/jobsink/main.go
Fixes #8296 
Rename the JobSink component from 'job-sink' to `job_sink` to make the generated metrics meet the 
Prometheus naming requirement.
ref: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
- :bug: Fix bug
```release-note
JobSink: all related metrics will start with prefix `job_sink` instead of `job-sink`
```
**Docs**
=> fix: rename `job-sink` to `job_sink`

test/rekt/resources/integrationsink/integrationsink.yaml
Fixes #
- as per title
```release-note
```
**Docs**
=> IntegrationSink: rek-test templating support for bool annotations

cmd/jobsink/main.go, pkg/apis/sinks/v1alpha1/job_sink_defaults.go, pkg/apis/sinks/v1alpha1/job_sink_defaults_test.go, pkg/apis/sinks/v1alpha1/job_sink_types.go, pkg/reconciler/jobsink/jobsink_test.go
To support long running functions in Knative Functions, we will inject a `KNATIVE_EXECUTION_MODE` environment variable with value `batch` so that function can change it's runtime behavior to read the event file rather than starting a long-running server.
Part of: https://github.com/knative/func/issues/2586
Fixes #
- inject a `KNATIVE_EXECUTION_MODE` environment variable with value `batch` to Jobs for JobSink
```release-note
JobSink: Inject a `KNATIVE_EXECUTION_MODE` environment variable with value `batch`
```
**Docs**
=> JobSink: Inject a `KNATIVE_EXECUTION_MODE` environment variable with value `batch`

pkg/apis/common/integration/v1alpha1/aws.go, pkg/reconciler/integration/sink/resources/container_image.go, pkg/reconciler/integration/source/resources/containersource.go
Fixes #
- as per title
```release-note
```
**Docs**
=> Avoid using twice hardcoded strings for the names of the Kube Secret keys, for AWS access/secret key vals

pkg/apis/sinks/v1alpha1/job_sink_defaults_test.go, pkg/apis/sinks/v1alpha1/job_sink_types.go, pkg/reconciler/jobsink/jobsink_test.go
=> Change JobSink execution mode variable to `K_EXECUTION_MODE`

config/core/roles/addressable-resolvers-clusterrole.yaml
This will ensure that all ServiceAccounts that are bound to "addressable-resolver" ClusterRole can read IntegrationSinks.
relates to thir pr: https://github.com/knative/eventing/pull/8298
=> Add integrationsinks-addressable-resolver cluster role

pkg/reconciler/integration/sink/resources/container_image.go, pkg/reconciler/integration/source/resources/containersource.go
- move image look up to map. will eventually be a config map
```release-note
```
**Docs**
=> Move image to map

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/broker/ingress/ingress_handler.go, pkg/broker/ingress/ingress_handler_test.go
The ingress or filter deployments were returning 400 even in the case where a given resource (like trigger, broker, subscription) wasn't found, however, this is a common case where the lister cache hasn't caught up with the latest state.
Fixes #
- MT-Broker: return appropriate status code based on the state to leverage retries
-
-
```release-note
MT-Broker: return retriable status code based on the state to leverage retries
```
**Docs**
=> MT-Broker: return retriable status code based on the state to leverage retries

config/core/resources/integrationsink.yaml, config/core/resources/integrationsource.yaml, pkg/apis/common/integration/v1alpha1/aws.go
Fixes #
- Clean up remove session token and credential profile name 
```release-note
```
**Docs**
=> Clean up remove session token

pkg/apis/sinks/v1alpha1/integration_sink_validation.go, pkg/apis/sinks/v1alpha1/integration_sink_validation_test.go, pkg/apis/sources/v1alpha1/integration_validation.go, pkg/apis/sources/v1alpha1/integration_validation_test.go
Fixes #
-- :broom: We renamed those fields to , and we reflect that now in validation
```release-note
```
**Docs**
=> Chore: field semantic correction 

pkg/adapter/apiserver/adapter.go, pkg/adapter/apiserver/adapter_test.go, pkg/adapter/apiserver/delegate_test.go, pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go, pkg/eventfilter/subscriptionsapi/create.go
In the apiserversource receive adapter for 1.15 (not on main), we see the following errors
```
W1204 13:41:06.207735       1 reflector.go:539] k8s.io/client-go@v0.29.2/tools/cache/reflector.go:229: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:default:api-src-user" cannot list resource "secrets" in API group "" in the namespace "knative-eventing"
E1204 13:41:06.207756       1 reflector.go:147] k8s.io/client-go@v0.29.2/tools/cache/reflector.go:229: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:default:api-src-user" cannot list resource "secrets" in API group "" in the namespace "knative-eventing"
```
This is because of the dependency of the adapter package to brokerfilters which use the secret …
=> [release-1.15] Make adapter pkg independent from brokerfilter package

pkg/apis/eventing/v1alpha1/requestreply_defaults.go, pkg/apis/feature/features.go, pkg/apis/feature/flag_names.go
_
Fixes #8338
- Add feature flag for default timeout on RequestReply resources
- Use feature flag in webhook
```release-note
Made request reply timeout configurable through config-features
```
**Docs**
=> RequestReply: Added feature flag for default timeout

cmd/broker/filter/main.go, cmd/broker/ingress/main.go, cmd/jobsink/main.go, pkg/auth/token_verifier.go, pkg/broker/filter/filter_handler_test.go, pkg/broker/ingress/ingress_handler_test.go, pkg/reconciler/inmemorychannel/dispatcher/controller.go
Manual backport of #8195 (without renaming `OIDCTokenVerifier` -> `Verifier`) to make auth package independent of eventpolicy informer.
This will avoid the following error in the apiserversource receiver
```
W1204 13:41:05.334187       1 reflector.go:539] k8s.io/client-go@v0.29.2/tools/cache/reflector.go:229: failed to list *v1alpha1.EventPolicy: eventpolicies.eventing.knative.dev is forbidden: User "system:serviceaccount:default:api-src-user" cannot list resource "eventpolicies" in API group "eventing.knative.dev" at the cluster scope
E1204 13:41:05.334209       1 reflector.go:147] k8s.io/client-go@v0.29.2/tools/cache/reflector.go:229: Failed to watch *v1alpha1.EventPolicy: failed to list *v1alpha1.EventPolicy: eventpolicies.eventing.knative.dev is forbidden: User …
```
=> [release-1.15] Make auth package independent of eventpolicy informer

cmd/controller/main.go, config/brokers/mt-channel-broker/deployments/controller.yaml, config/core/deployments/pingsource-mt-adapter.yaml, pkg/adapter/apiserver/adapter.go, pkg/adapter/v2/context.go, pkg/adapter/v2/main.go, pkg/adapter/v2/main_test.go, pkg/reconciler/apiserversource/resources/receive_adapter.go, pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Fixes #8192
- :bug: Add the missing health check config.
- :broom: Remove the duplicated health check since it's already defined here: https://github.com/knative/pkg/blob/25f6002b00f3562c48e4fa6f18882829c61cc73f/injection/sharedmain/main.go#L320-L325
```release-note
```
**Docs**
=> Add health check config and clean up duplicated code

config/core/resources/eventpolicy.yaml
As we don't have multiple EP versions yet, we don't need the conversion webhook configuration in the EventPolicy CRD
/cherry-pick release-v1.16
/cherry-pick release-v1.15
=> Remove conversion webhook config in EventPolicy CRD

config/post-install/storage-version-migrator.yaml
While this is not strictly needed right now, this prevents issues we could run into eventually with version migrations.
Fixes #
- Add EventPolicy to storage version migrator
-
-
```release-note
```
**Docs**
=> Add EventPolicy to storage version migrator

test/rekt/resources/jobsink/jobsink.go
The package must be registered so that ImageProducer can map it to the right image and replace it in the final yaml.
So far the JobSink E2E test was passing because another step (which runs in parallel) registered the eventshub package in the same context earlier. However, if the JobSink step runs first it fails to replace the image and the final Yaml includes: `"image": "ko://knative.dev/reconciler-test/cmd/eventshub"`
Fixes #
-
-
-
```release-note
```
**Docs**
=> Register eventshub image for JobSink

pkg/scheduler/scheduler.go, pkg/scheduler/state/state.go, pkg/scheduler/state/state_test.go, pkg/scheduler/statefulset/autoscaler.go, pkg/scheduler/statefulset/autoscaler_test.go
When scaling down and compacting, basing the last ordinal on the free capacity structure leads to have a lastOrdinal off by one since `FreeCap` might contain the free capacity for unschedulable pods.
We will have to continue including unschduelable pods in FreeCap because it might happen that a pod becomes unscheduleble for external reasons like node gets shutdown for pods with lower ordinals and the pod need to be rescheduled and during that time period we want to consider those when compacting; once all vpods that were on that pod that is gone get rescheduled, FreeCap will only include scheduleable pods.
Fixes #
- Scheduler: LastOrdinal based on replicas instead of FreeCap
```release-note
```
**Docs**
=> Scheduler: LastOrdinal based on replicas instead of FreeCap

pkg/graph/constructor.go
Fixes #
- Lineage constructor to accept clients instead of creating them
- Motivation
- Otherwise it is impossible to test the callers of the lineage package
- Now, I can pass fake clients and essentially mock the lineage package
```release-note
:page_facing_up: "Action required" for the callers of the `knative.dev/eventing/pkg/graph` package. The constructor that has previously accepted a `rest.RestConfig` is now accepting clients (Kubernetes clients) directly instead of creating them in the package.
```
**Docs**
=> Lineage constructor to accept clients instead of creating them

pkg/graph/constructor.go
Fixes #
- Don't swallow errors in Lineage package
- I was having hard time understanding why the Backstage backend was returning 200 with corrupt auth
- Introduced a field called `Lenient:bool` (wanted to have the default to `false`, thus, a positive field name versus `FailFast`). If this field is set to false, there will be no behavior changes, except one place (noted below).
```release-note
:page_facing_up: The event lineage package does not swallow the 400 and 401 errors anymore. Callers should handle those errors themselves.
```
**Docs**
=> Don't swallow errors in Lineage package

pkg/graph/constructor.go
Fixes #
-
-
-
```release-note
```
**Docs**
=> Event lineage builder should accept client interfaces

pkg/graph/types.go
=> Include inEdges in Graph String()

test/rekt/features/parallel/oidc_feature.go, test/rekt/features/sequence/feature.go, test/rekt/features/sequence/oidc_feature.go, test/rekt/parallel_test.go, test/rekt/sequence_test.go
- Run AuthZ conformance tests for Sequence and Parallel
- Use fully functional Sequence and Parallel as otherwise they return status code 500 when events are sent to them while EventPolicy is configured to allow the traffic through it (the happy/successful path). This is different from other resources like Broker or Channel - these return 202 even if no sink is connected to them.
```release-note
```
**Docs**
=> Add authorization conformance tests for Sequence and Parallel

.github/workflows/kind-e2e.yaml, hack/create-kind-cluster.sh
Fixes #
-
-
-
```release-note
The minimum Kubernetes version is now 1.30.x
```
**Docs**
=> Update KinD e2e workflow

pkg/reconciler/broker/controller.go
Currently, the mt-broker-controller is using a cluster-wide endpoints
informer but it actually only uses endpoints in the "SYSTEM_NAMESPACE".
Using the namespaced informer factory ensures that the watcher
is only watching endpoints in the `knative-eventing` (also known as
`SYSTEM_NAMESPACE`) namespace.
The secret informer is already using a namesapced watcher. 
The only one which is cluster-wide is the configmap watcher but
we can't remove that one since broker configurations could
exist in any namespace.
Fixes #
- Reduce mt-broker-controller memory usage with namespaced endpoint informer
```release-note
Reduce `mt-broker-controller` memory usage with namespaced endpoint informer.
```
**Docs**
=> Reduce mt-broker-controller memory usage with namespaced endpoint informer

pkg/graph/constructor.go, pkg/reconciler/testing/factory.go, pkg/reconciler/testing/listers.go
Fixes #
- Took me quite some time to understand why Kube API server was returning 404s when I wanted the event lineage to fetch sources
-
```release-note
```
**Docs**
=> Rename `apiextentions` to `apiextensions`

config/core/roles/clusterrole-namespaced.yaml
These are roles that users can use to give their developers access to Knative Eventing resources and we're missing the sinks group.
Fixes #
- Add `sinks.knative.dev` to namespaced ClusterRole
```release-note
Add `sinks.knative.dev` to namespaced ClusterRoles
```
**Docs**
=> Add `sinks.knative.dev` to namespaced ClusterRole

pkg/scheduler/scheduler.go, pkg/scheduler/statefulset/scheduler.go, pkg/scheduler/testing/vpod.go
Add resyncReserved removes deleted vPods from reserved to keep the state consistent when leadership changes (Promote / Demote).
`initReserved` is not enough since the vPod lister can be stale.
Fixes #
- Resync reserved periodically to keep state consistent
```release-note
```
**Docs**
=> Scheduler: Resync reserved periodically to keep state consistent

cmd/schema/main.go
Fixes #
- as per title
```release-note
```
**Docs**
=> chore: Adding missing sinks and sources to schema file

pkg/scheduler/state/state.go, pkg/scheduler/statefulset/autoscaler.go
Improve logging for troubleshooting
=> Scheduler: log expected vreplicas by vpod

pkg/apis/sinks/v1alpha1/integration_sink_types.go, pkg/reconciler/integration/sink/integrationsink.go, pkg/reconciler/integration/sink/resources/certificate.go, pkg/reconciler/integration/sink/resources/container_image.go, pkg/reconciler/integration/sink/resources/names.go
Fixes #
- before moving code, aligning some issues and make code different
```release-note
```
**Docs**
=> IntegrationSink prefactors

third_party/eventing-integrations-latest/eventing-integrations-images.yaml, third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Fixes #
- Add initial iteration of eventing-integration resources
@matzew we need an initial commit of the files, otherwise nightlies bump won't work. :)
=> Add initial iteration of eventing-integration resources

test/rekt/features/trigger/feature.go, test/rekt/resources/trigger/trigger.go
Fixes #7896
- :broom: add step function in setup phase to verify that the trigger is not ready because the pingsource dependency doesn't exist yet
=> fix: verify trigger is not ready before pingsource dependency exists

config/400-config-eventing-integrations-images.yaml, config/400-config-eventing-transformations-images.yaml, config/core/configmaps/eventing-integrations-images.yaml, config/core/configmaps/eventing-transformations-images.yaml, config/core/deployments/controller.yaml, config/core/resources/eventtransform.yaml, test/rekt/eventtransform_test.go, test/rekt/features/eventtransform/eventtransform.go, test/rekt/resources/eventtransform/eventtransform.go, test/rekt/resources/eventtransform/eventtransform.yaml, test/rekt/resources/eventtransform/eventtransform_test.go, third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Waiting for https://github.com/knative-extensions/eventing-integrations/pull/72 to be merged and built
=> Jsonata Event transform e2e tests

pkg/scheduler/statefulset/scheduler_test.go
=> Guard reserved access with lock and create vpods in tests

pkg/apis/sources/v1/sinkbinding_lifecycle.go, pkg/apis/sources/v1/sinkbinding_lifecycle_test.go, pkg/apis/sources/v1/sinkbinding_types.go, pkg/reconciler/sinkbinding/sinkbinding.go
Instead of setting the ready condition during reconciliation steps, set specific conditions since the ready condition is managed and set according to the state of other conditions.
Fixes #
- SinkBinding: Set specific conditions for reconciler steps
```release-note
SinkBinding: Set specific conditions for reconciler steps: `SinkBindingAvailable` and `TrustBundlePropagated`
```
**Docs**
=> SinkBinding: Set specific conditions for reconciler steps

config/post-install/storage-version-migrator.yaml
Fixes #8415 
- Set the the `IGNORE_NOT_FOUND` environment variable to true in the storage-version-migrator.yaml file
```release-note
Allow storage-version-migration job to successfully run when optional CRDs are not installed (inmemorychannels, etc).
```
**Docs**
=> Allow storage-version-migration job to successfully run when optional CRDs are not installed (inmemorychannels, etc)

cmd/controller/main.go, pkg/certificates/certificate.go, pkg/certificates/certificate_test.go, pkg/reconciler/integration/sink/controller.go, pkg/reconciler/integration/sink/integrationsink.go, pkg/reconciler/integration/sink/integrationsink_test.go, pkg/reconciler/integration/sink/resources/container_image.go, test/rekt/integration_sink_test.go
Fixes #
- in sink controller we create the cert-mgr informer based on the fact if TLS is enabled
```release-note
TLS / Cert Manager integration for IntegrationSink
```
**Docs**
=> Enable Cert Manager

pkg/certificates/certificate.go, pkg/reconciler/eventtransform/controller.go, pkg/reconciler/eventtransform/eventtransform.go, pkg/reconciler/eventtransform/eventtransform_test.go, pkg/reconciler/integration/sink/controller.go, pkg/reconciler/integration/sink/integrationsink.go
Fixes #
-
-
-
```release-note
```
**Docs**
=> Add dynamic cert-manager certificates informer

pkg/reconciler/integration/sink/integrationsink.go, pkg/reconciler/integration/sink/integrationsink_test.go
Fixes #
- Improve CM Cert reconcile and deletion if feature is turned off
```release-note
```
**Docs**
=> Improve CM Cert reconcile and deletion if feature is turned off

hack/release.sh
This prevents releasing `knative-nightly` references for transformations and integrations images.
This means that eventing-integrations needs to be released before eventing
=> Prevent knative-nightly integrations image references from being released

pkg/reconciler/eventtransform/resources_jsonata.go, test/rekt/features/eventtransform/eventtransform.go
The test wasn't actually running do to OIDC prerequisite (which is not needed / or enabled in test/config-transport-encryption)
=> Fix EventTransform with TLS Sink test

pkg/eventingtls/trust_bundle_test.go
Adding little func that generated the invalid PEM data, instead of a hard-coded string, that may look like a real one...
Fixes #
- :broom: Adding little func that generated the invalid PEM data, instead of a hard-coded string, that may look like a real one...
```release-note
```
**Docs**
=> Adding little func that generated the invalid PEM data

pkg/broker/filter/filter_handler.go, pkg/broker/filter/filter_handler_test.go
If no subscriber uri is present we return 404, instead of 400 which means the request from the client itself would have had isssues
Fixes #8552
-
-
-
```release-note
```
**Docs**
=> If no subscriber uri is present we return 404, instead of 400

.golangci.yaml
=> [release-1.17] Migrate golanglint-ci config to v2

.golangci.yaml
=> [release-1.16] Migrate golanglint-ci config to v2

pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Adding a nil check for `Auth.ServiceAccountName`, since it might not be reconciled yet, when the OIDC feature flag is switched on, quickly before
Fixes #8581
-
-
-
```release-note
```
**Docs**
=> Check for Auth.ServiceAccountName when the OIDC feature flag is switched on to avoid potential nil 

pkg/apis/sources/v1/sinkbinding_lifecycle.go, pkg/apis/sources/v1/sinkbinding_lifecycle_test.go, pkg/eventingtls/trust_bundle.go, pkg/reconciler/apiserversource/apiserversource.go, pkg/reconciler/sinkbinding/controller.go, pkg/reconciler/sinkbinding/sinkbinding.go, test/rekt/apiserversource_test.go, test/rekt/channel_test.go, test/rekt/features/apiserversource/data_plane.go, test/rekt/features/channel/eventing_tls_feature.go, test/rekt/features/pingsource/features.go, test/rekt/features/trigger/feature.go, test/rekt/pingsource_test.go, test/rekt/trigger_test.go
This adds new tests for testing when CA trust bundles are dynamically added to the clients trust stores
=> Eventing TLS: add tests for dynamically added CA trust bundles

pkg/adapter/mtping/runner_test.go, pkg/adapter/v2/cloudevents_test.go, pkg/eventingtls/eventingtlstesting/eventingtlstesting.go, pkg/kncloudevents/event_dispatcher_test.go, pkg/kncloudevents/event_receiver.go
This allows to pass 0 as the port and thus let the OS chose a free port for the server. This helps to fix flaky tests which can occur, when we use the same port number in different tests which might run in parallel.
Fixes #7393 
Fixes #8408
=> Return assigned port for HTTPEventReceiver

pkg/requestreply/correlation_id.go, pkg/requestreply/correlation_id_test.go
For the RequestReply resource to securely figure out that a new event is a reply to an earlier event it saw, it needs to encrypt the event id and set that in a correlation id attribute. For the reply event, that correlation id attribute will have been copied into the reply id attribute.
This PR adds helper functions to set and verify these IDs, to be consumed in various places later as the RequestReply implementation continues.
- Add function to set correlation id
- Add function to verify that a reply id is from this RequestReply resource
=> feat: add package to set and verify correlation/reply ids for RequestReply

pkg/requestreply/cesql.go, pkg/requestreply/cesql_test.go, pkg/requestreply/correlation_id.go, pkg/requestreply/correlation_id_test.go
Fixes #8318 
- Add a CESQL function for verifying correlation ids
- Add unit tests for trigger filters with the CESQL function registered
- Change the VerifyCorrelationId interface to allow the CESQL function definition to be more idiomatic
```release-note
Knative now supports the KN_VERIFY_CORRELATION_ID CESQL function, allowing you to verify knative correlation ids in your trigger filters.
```
**Docs**
=> feat: add request reply cesql function

cmd/jobsink/main.go, pkg/tracing/populate_ce_distributed_tracing.go, pkg/tracing/populate_ce_distributed_tracing_test.go
Fixes #8607 
Hey! I finally got around to implementing what we talked about in the issue above.
Please tell me if I should move the implementation of PopulateCEDistributedTracing. I just looked around until I found something similar enough, and put the code right next to it.
This currently only injects the headers into Jobsink events, are there any other places where events are propagated without http, and could benefit from this?
Let me know if you need any more changes 😄 
- :gift: Inject tracing headers into cloudevent according to [the spec](https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md)
```release-note
Event files received by Jobsinks will now include the Distributed Tracing extension
```
**Docs**
=> Injected tracing headers into jobsink event file

pkg/auth/verifier.go, pkg/broker/ingress/ingress_handler.go, pkg/channel/event_receiver.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/rekt/features/authz/addressable_authz_conformance.go
=> Fix mt-broker-ingress auth to work with structured event too

config/300-requestreply.yaml, config/500-requestreply.yaml
With #8701 merged I was trying to deploy the resource locally & realized that the symlinks for some of the request reply config files were missing
=> fix: add symlinks to request reply config

pkg/channel/event_receiver.go, pkg/channel/event_receiver_test.go, pkg/channel/references.go, pkg/channel/references_test.go, pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go, pkg/reconciler/inmemorychannel/controller/resources/service.go, pkg/reconciler/inmemorychannel/controller/resources/service_test.go, pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go, test/conformance/helpers/channel_tracing_test_helper.go
When OIDC is enabled and https is disabled (i.e. http requests are used) the event receiver is using the host name to determine the name of the channel and fails to do so. An example host name is `broker-kne-trigger-kn-channel.namespace-1.svc.cluster.local`. The channel name here is `broker-kne-trigger` without the suffix
`-kn-channel` which was hardcoded in the logic which was creating the channel owned k8 service.
The constant `-kn-channel` is now extracted into a common constant in the `channel` package. A conditional check in `ParseChannelFromHost` now checks for the suffix in the host name and removes it if needed. 
An additional test case was added and existing tests were updated.
:bug: Fixes #8705.
- :broom: Extract channel owned k8 service suffix into constant.
- :test_tube: Add …
=> Fix MT Channel based broker when OIDC is enabled

DEVELOPMENT.md
Also add a reference to the function in the `e2e-common.sh` which shows how the Cert-manager is deployed by the `run.sh` script.
Fixes #8740
- :book: Update `DEVELOPMENT.md` [_Install Cert-manager_](https://github.com/knative/eventing/blob/main/DEVELOPMENT.md#install-cert-manager) section.
```release-note
Correct guide on how to install Cert-manager manually in DEVELOPMENT.md
```
=> Docs: fix cert-manager manual deploy guide in `DEVELOPMENT.md`.

config/core/resources/integrationsink.yaml, config/core/resources/integrationsource.yaml, pkg/apis/common/integration/v1alpha1/auth.go, pkg/apis/sinks/v1alpha1/integration_sink_validation_test.go, pkg/apis/sources/v1alpha1/integration_validation_test.go, pkg/reconciler/integration/sink/resources/container_image.go, pkg/reconciler/integration/sink/resources/container_image_test.go, pkg/reconciler/integration/source/resources/containersource.go, pkg/reconciler/integration/source/resources/containersource_test.go, test/rekt/integrationsource_test.go
Fixes #8437 
This PR adds support for using the pod AWS default credentials for IntegrationSource and IntegrationSink resources. It adds an optional property `.spec.aws.auth.serviceAccountName` to specify the ServiceAccount the pod should run as. The ServiceAccount applies the desired role to the pod as the default credentials.
This change requires the latest images from `aws-*-source` in order for the Camel `useDefaultCredentialsProvider` property to be loaded from the environment variable.
-
-
-
```release-note
Add support for using Pod default credentials in AWS IntegrationSource and IntegrationSink resources by specifying a ServiceAccount.
```
**Docs**
https://github.com/knative/docs/pull/6394
=> feat: Supporting using pod default credentials for Integration Source and Sink
