knative/eventing

- test/conformance/helpers/broker_data_plane_test_helper.go
> broker conf tests -- add wait on pod resource ready

- pkg/utils/cache/persisted_store_test.go
Fixes #
- addresses comments from https://github.com/knative/eventing/pull/3976#issuecomment-684106090
/hold
/assign @lionelvillard 
Let's see that we get this executed a few times, w/o failure!
> Increase timeout for fake CM 

- pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
> Fix race condition #3960

- pkg/reconciler/mtbroker/trigger/trigger_test.go
- pkg/reconciler/parallel/parallel_test.go
- pkg/reconciler/sequence/sequence_test.go
- pkg/reconciler/source/duck/duck_test.go
as suggested by @mattmoor [here](https://github.com/knative/eventing/pull/3989#pullrequestreview-481421836)
/assign @vaikas @n3wscott
> Use helpers, rather than manual resource ctor

- pkg/adapter/mtping/pingsource.go
-
-
-
```release-note
```
**Docs**
> remove useless scope test

- docs/personas.md
- docs/source/README.md
- docs/spec/channel.md
- support/COMMUNITY_CONTACTS.md
Manual fix for #4014
- Added ignore instruction for a block, that was causing problems
- See #4014 for more details
> Format markdown manually

- .golangci.yaml
- cmd/mtbroker/ingress/main.go
- pkg/adapter/mtping/runner_test.go
- pkg/adapter/v2/main.go
- pkg/apis/configs/v1alpha1/configmappropagation_validation.go
- pkg/apis/eventing/v1/trigger_validation_test.go
- pkg/apis/flows/v1/parallel_defaults.go
- pkg/apis/flows/v1/sequence_defaults.go
- pkg/apis/flows/v1beta1/parallel_defaults.go
- pkg/apis/flows/v1beta1/sequence_defaults.go
- pkg/reconciler/channel/channel_test.go
- pkg/reconciler/mtbroker/broker.go
- pkg/reconciler/mtbroker/broker_test.go
- pkg/reconciler/mtbroker/trigger/trigger.go
- pkg/reconciler/mtbroker/trigger/trigger_test.go
- pkg/reconciler/pingsource/pingsource_test.go
- pkg/reconciler/source/crd/controller.go
- pkg/reconciler/source/crd/crd_test.go
- pkg/reconciler/subscription/subscription_test.go
- test/conformance/helpers/sources/source_status_test_helper.go
- test/conformance/main_test.go
- test/lib/creation.go
- test/performance/infra/aggregator/aggregator.go
As per title. Prep work to roll out golangci-lint actions across the board.
> Add linting config and fix issues.

- hack/update-checksums.sh
- hack/update-codegen.sh
- use the separate script, so you don't have to run the whole codegen just to patch one number
- use it in update-codegen
/cc @julz 
/assign @n3wscott @vaikas
> Upgrade checksum generator for eventing

- pkg/adapter/v2/cloudevents_test.go
- test/lib/nodes/nodes.go
Removes all usages of `master` where we can help it, adding tracking issues and context to places where we can't yet.
> Remove 'master' where not necessary and add tracking issues.

- pkg/utils/headers.go
Per my `grep`, this is the last offender for now.
> Remove unnecessary whitelist terminology.

- .github/workflows/knative-downstream.yaml
- Added downstream build/unit test for knative-sandbox/eventing-kafka-broker
cc @n3wscott @pierDipi
> Added downstream test with eventing-kafka-broker

- pkg/utils/cache/persisted_store_test.go
Fixes #
- we sometimes see failures on this test, due to timeout w/ the fake CM.... Increasing it here
```release-note
```
**Docs**
> Increase timeout for persisted store test

- pkg/reconciler/subscription/subscription_test.go
Fixes #
-
-
-
```release-note
```
**Docs**
> Moving constant

- test/e2e/channel_chain_test.go
- test/e2e/channel_dls_test.go
Fixes #
- making test name more explicit
```release-note
```
**Docs**
> Reflecting API caller on the name of the test

- test/e2e/channel_event_transformation_test.go
Fixes #
- making test func name more explicit 
-
-
```release-note
```
**Docs**
> Reflect versions on test func

- pkg/reconciler/testing/listers.go
- pkg/reconciler/testing/v1/listers.go
Add core secretlister for unit tests.
-
-
-
```release-note
```
**Docs**
> add secret lister

- go.mod
- go.sum
- vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
- vendor/knative.dev/pkg/configmap/hash-gen/main.go
- vendor/knative.dev/pkg/kmeta/names.go
- vendor/knative.dev/pkg/metrics/config.go
- vendor/knative.dev/pkg/metrics/exporter.go
- vendor/knative.dev/pkg/metrics/opencensus_exporter.go
- vendor/knative.dev/pkg/webhook/conversion.go
- vendor/knative.dev/pkg/webhook/webhook.go
- vendor/modules.txt
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc n3wscott grantr matzew
/assign n3wscott grantr matzew
> [Automated] Upgrade to latest dependencies

- go.mod
- go.sum
- hack/update-deps.sh
- vendor/knative.dev/pkg/hack/update-deps.sh
- vendor/modules.txt
Pin upstreams for release 0.18
> [Release] Pin upstreams for release 0.18

- OWNERS
Criteria from https://github.com/knative/community/blob/master/ROLES.md#approver
> Reviewer of the codebase for at least 3 months:
First review:
https://github.com/knative/eventing/pull/2936, Apr 8, 2020
Substantial PRs reviewed (size/L, size/XL and size/XXL): https://github.com/knative/eventing/pulls?q=is%3Apr+-author%3Aaliok+reviewed-by%3Aaliok+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM
14
(Github query not possible for "primary reviewer", thus handpicked)
https://github.com/knative/eventing/pull/3214
https://github.com/knative/eventing/pull/3363
https://github.com/knative/eventing/pull/3372
https://github.com/knative/eventing/pull/3417
https://github.com/knative/eventing/pull/3507 …
> Add aliok to approvers

- OWNERS
I'd like to help out with reviews :)
FYI @grantr
> Add tommyreddad to reviewers

- pkg/adapter/mtping/adapter_test.go
- pkg/adapter/v2/util/crstatusevent/eventsstatus_test.go
- pkg/channel/fanout/fanout_message_handler_test.go
- pkg/channel/message_dispatcher_test.go
- remove unused params
- use io.Copy
- remove fake empty impls, where possible
- etc
/assign @grantr @n3wscott
> Some final touches for today in fakes, etc

- OWNERS
I would love to be a reviewer to contribute to the project. Please add me in the reviewer list. Thank you.
> Add zhongduo (Jimmy Lin) as a reviewer

- docs/spec/spec.md
Produced via:
```shell
prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github | grep -v docs/cmd/)
```
/cc n3wscott grantr matzew
/assign n3wscott grantr matzew
> [Automated] Format markdown

- pkg/apis/flows/v1/sequence_validation.go
- pkg/apis/flows/v1/sequence_validation_test.go
- pkg/apis/flows/v1beta1/sequence_types_test.go
- pkg/apis/flows/v1beta1/sequence_validation.go
- pkg/apis/flows/v1beta1/sequence_validation_test.go
Fixes https://github.com/knative/eventing/issues/3862
- Added tests to sequence_validation.go
Thank you for your review!
> Add tests to sequence validation

- pkg/reconciler/apiserversource/resources/lavels_test.go
Fixes https://github.com/knative/eventing/issues/3864
- Added tests to knative.dev/eventing/pkg/reconciler/apiserversource/resources/labels.go
Thank you for your review!
> Add tests to labels

- pkg/reconciler/apiserversource/apiserversource.go
- pkg/reconciler/mtbroker/trigger/trigger.go
- pkg/reconciler/sugar/filters_test.go
- pkg/reconciler/sugar/labels_test.go
- pkg/reconciler/sugar/resources/broker_test.go
- pkg/reconciler/sugar/resources/labels_test.go
Signed-off-by: runzexia <root@junwuhui.cn>
Fixes #3865
-
-
-
```release-note
```
**Docs**
> Increase code coverage for reconciler/sugar

- config/core/deployments/controller.yaml
- config/core/deployments/pingsource-mt-adapter.yaml
- pkg/adapter/mtping/runner.go
- pkg/adapter/v2/cloudevents.go
- pkg/adapter/v2/cloudevents_test.go
- pkg/adapter/v2/config.go
- pkg/adapter/v2/config_test.go
- pkg/adapter/v2/main.go
- pkg/reconciler/pingsource/pingsource.go
- pkg/reconciler/pingsource/pingsource_test.go
- pkg/reconciler/pingsource/resources/receive_adapter.go
- pkg/reconciler/pingsource/resources/receive_adapter_test.go
Fixes #
https://github.com/knative/eventing/issues/4056
-
-
-
```release-note
```
**Docs**
> SinkTimeout#4056

- test/lib/duck/resource_inspectors.go
Fixes #4153
Possibly fixes other flaky tests using `GetAddressableURI`
- Use v1 instead of v1alpha1 in `GetAddressableURI`
See also #4182
> Use v1 to get addressable URI in tests

- config/core/deployments/webhook.yaml
Fixes #4165 
- Backport #4168 ( Thanks @ian-mi ) to 0.18
-
-
```release-note
- 🐛 Fix bug
Backport #4168 which fixed #4165 
```
**Docs**
> [0.18] backport 4168

- config/core/deployments/webhook.yaml
Fixes #4165 
- Backport #4168 ( Thanks @ian-mi ) to 0.18
-
-
```release-note
- 🐛 Fix bug
Backport #4168 which fixed #4165 
```
**Docs**
> [0.17] backport 4168 to .17

- config/core/deployments/webhook.yaml
Fixes #4165 
- Backport #4168 ( Thanks @ian-mi ) to 0.18
-
-
```release-note
- 🐛 Fix bug
Backport #4168 which fixed #4165 
```
**Docs**
> [0.16] backport 4168 to .16

- config/core/deployments/controller.yaml
- config/core/deployments/pingsource-mt-adapter.yaml
- pkg/adapter/mtping/runner.go
- pkg/adapter/v2/cloudevents.go
- pkg/adapter/v2/cloudevents_test.go
- pkg/adapter/v2/config.go
- pkg/adapter/v2/config_test.go
- pkg/adapter/v2/main.go
- pkg/reconciler/pingsource/pingsource.go
- pkg/reconciler/pingsource/pingsource_test.go
- pkg/reconciler/pingsource/resources/receive_adapter.go
- pkg/reconciler/pingsource/resources/receive_adapter_test.go
Back port PR https://github.com/knative/eventing/pull/4126
> SinkTimeout#4056 Backport PR4126

- .codecov.yaml
- Enable codecov action to run by having the file present that will execute the action.
```release-note
Use github action to run codecov.
```
**Docs**
> enable codecoverage reports

- OWNERS
Fixes #
-
-
-
```release-note
```
**Docs**
> Add tayarani as reviewer

- .github/workflows/knative-downstream.yaml
Fixes #
- Added downstream test with eventing-kafka
-
-
```release-note
```
**Docs**
> Added downstream test with eventing-kafka

- .github/workflows/knative-downstream.yaml
> Removed downstream check for eventing-contrib

- cmd/mtbroker/ingress/main.go
- pkg/adapter/v2/main_message.go
- pkg/channel/message_dispatcher.go
- pkg/inmemorychannel/message_dispatcher_benchmark_test.go
- pkg/inmemorychannel/message_dispatcher_test.go
- pkg/kncloudevents/message_sender.go
- pkg/mtbroker/filter/filter_handler.go
- pkg/mtbroker/ingress/ingress_handler_test.go
minor typo on HTTP refactor, too many TTT
> HTTTP -> HTTP

- test/e2e/source_container_v1alpha2_test.go
- test/e2e/source_container_v1beta1_test.go
- test/e2e/source_sinkbinding_v1alpha1_test.go
- test/e2e/source_sinkbinding_v1alpha2_test.go
- test/e2e/source_sinkbinding_v1beta1_test.go
- test/lib/recordevents/resources.go
- test/lib/resources/kube.go
- test/lib/sender/resources.go
- 🐛 Fix bug
This is needed for environments like KinD where the images may be side-loaded instead of published to a registry.
> Use the IfNotPresent pull policy.

- go.mod
- go.sum
- vendor/knative.dev/pkg/configmap/store.go
- vendor/knative.dev/pkg/metrics/config_observability.go
- vendor/knative.dev/pkg/tracing/config/tracing.go
- vendor/knative.dev/pkg/tracing/setup.go
- vendor/modules.txt
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc n3wscott grantr matzew
/assign n3wscott grantr matzew
> [master] Upgrade to latest dependencies

- test/e2e/source_sinkbinding_v1_test.go
Fixes #
- For the e2e tests, use PullIfNotPresent so it works with kind.
```release-note
- 🐛 Fix bug
Change the image pull policy so sinkbinding source tests work with kind.
```
**Docs**
> use PullIfNotPresent so works with kind

- pkg/tracing/attributes_test.go
Signed-off-by: runzexia <root@junwuhui.cn>
Fixes #3866
-
-
-
```release-note
```
**Docs**
> tracing ut

- pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go
- pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go
Signed-off-by: RyderXia <ryder.xia@sap.com>
Fixes #3700
-
-
-
```release-note
```
**Docs**
> imc dispatcher securitycontext

- test/e2e/helpers/parallel_test_helper.go
- test/lib/resources/kube.go
Removed filterevents usages and replaces with recordevents
- Removed filterevents usages and replaces with recordevents
- Removed filterevents helper
> Remove filterevents usages

- pkg/adapter/mtping/runner.go
- pkg/apis/duck/v1/fuzzer.go
- pkg/reconciler/source/duck/resources/eventtype.go
1. they must be right after //
2. If they are on top of the line they apply to the block below, so move them next to the line
3. Other nits along the way, e.g. reducing visibility of objects.
/assign @n3wscott @vaikas
> Fix the nolint thingies

- test/test_images/filterevents/main.go
- test/test_images/filterevents/pod.yaml
- test/test_images/sequencestepper/main.go
- test/test_images/sequencestepper/pod.yaml
- test/test_images/transformevents/main.go
- test/test_images/transformevents/pod.yaml
Reverts knative/eventing#4348
Most of the downstream eventing repos use these images.
> Revert "Cleanup test_images"

- go.mod
- go.sum
- vendor/knative.dev/pkg/injection/config.go
- vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
- vendor/knative.dev/pkg/test/clients.go
- vendor/knative.dev/pkg/test/e2e_flags.go
- vendor/knative.dev/pkg/test/flags/e2e_flags.go
- vendor/knative.dev/pkg/test/request.go
- vendor/knative.dev/pkg/test/tinterface.go
- vendor/modules.txt
Replaces https://github.com/knative/eventing/pull/4343
> update pkg to latest Oct-20

- pkg/apis/eventing/v1/trigger_validation_test.go
- pkg/apis/eventing/v1beta1/trigger_validation_test.go
- pkg/channel/fanout/fanout_message_handler_test.go
- pkg/reconciler/apiserversource/apiserversource_test.go
- pkg/reconciler/containersource/containersource_test.go
- pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
- pkg/reconciler/mtbroker/trigger/trigger_test.go
- pkg/reconciler/subscription/subscription_test.go
- test/e2e_flags.go
- test/flags/parsing.go
- test/lib/recordevents/event_info.go
Readability for `all`.
/assign @n3wscott @grantr
> Get rid of \" in favor of backticks

- pkg/mtbroker/filter/filter_handler.go
Adding a bunch of log lines to improve diagnostic of filter handler behaviour
> Improved logging at debug level in filter handler

- .github/workflows/kind-e2e.yaml
- test/conformance/helpers/broker_data_plane_test_helper.go
- test/conformance/helpers/tracing_test_helper.go
- test/lib/k8s_events.go
- test/lib/operation.go
- test/lib/recordevents/event_info.go
- test/lib/recordevents/event_info_store.go
Fixes #4275
- Enable the Conformance tests via GitHub Actions.
```release-note
NONE
```
> Enable the Conformance tests via GitHub Actions

- pkg/reconciler/sinkbinding/controller.go
related: #4374
cc/ @vaikas @n3wscott @tom24d
> Add status markers for sinkbinding in subresourcereconciler

- .github/workflows/kind-e2e.yaml
- Use a multiline YAML string to make viewing each individual flag clearer.
```release-note
NONE
```
> Use a multiline YAML string to make viewing each individual flag clearer

- test/lib/recordevents/observer/observer.go
- test/lib/recordevents/observer/reply.go
> Fix logger usage with proper zap.Error calls

- test/lib/recordevents/recorder_vent/constructor.go
- test/lib/recordevents/resources.go
* Manual publish of events to avoid event correlator
* Nit
(cherry picked from commit 3649b0dc34d5204871ff51f2369ab386cc4d70bc)
> [0.18] Publish manually events to avoid event correlator (#4373)

- test/lib/recordevents/recorder_vent/constructor.go
* Manual publish of events to avoid event correlator
* Nit
(cherry picked from commit 3649b0dc34d5204871ff51f2369ab386cc4d70bc)
> [0.17] Publish manually events to avoid event correlator (#4373)

- test/lib/dropevents/receiver.go
- test/lib/recordevents/event_info.go
- test/lib/recordevents/logger_vent/logger.go
- test/lib/recordevents/observer/observer.go
- test/lib/recordevents/recorder_vent/constructor.go
- test/lib/recordevents/recorder_vent/recorder.go
- test/lib/recordevents/resources.go
- test/lib/test_runner.go
- test/test_images/recordevents/main.go
Ported:
- #4393
- #4389
- #4385
> [0.18] Ported recent test infra improvements

- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
> [0.17] Fix #4425

- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
> [0.18] Fix #4425

- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
- Backport #4454
```release-note
- 🐛 Fix bug
Retry on network failures
```
> [release-0.17] Retry on network failures (#4454)

- cmd/mtbroker/ingress/main.go
- pkg/kncloudevents/http_client.go
- pkg/kncloudevents/http_client_test.go
- pkg/kncloudevents/message_sender.go
- pkg/mtbroker/filter/filter_handler.go
- pkg/reconciler/inmemorychannel/dispatcher/controller.go
> [0.17] Backport #4465

- cmd/mtbroker/ingress/main.go
- pkg/kncloudevents/http_client.go
- pkg/kncloudevents/http_client_test.go
- pkg/kncloudevents/message_sender.go
- pkg/mtbroker/filter/filter_handler.go
- pkg/reconciler/inmemorychannel/dispatcher/controller.go
> [0.18] Backport #4465

- pkg/mtbroker/filter/filter_handler.go
- pkg/mtbroker/filter/filter_handler_test.go
> [0.17] Backport #4466

- pkg/reconciler/apiserversource/resources/receive_adapter.go
- pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Fixes #
- [0.17] Backport #4475 (#4477)
-
-
```release-note
```
**Docs**
> [0.17] Backport #4475 (#4477)

- pkg/reconciler/apiserversource/resources/receive_adapter.go
- pkg/reconciler/apiserversource/resources/receive_adapter_test.go
- [0.18] Backport #4475 (#4477)
-
-
```release-note
```
**Docs**
> [0.18] Backport #4475 (#4477)

- config/core/deployments/pingsource-mt-adapter.yaml
Backport https://github.com/knative/eventing/pull/4472
> Backport https://github.com/knative/eventing/pull/4472

- config/brokers/mt-channel-broker/deployments/broker-filter.yaml
- config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
- pkg/mtbroker/ingress/ingress_handler.go
Fixes #4473
- Start readiness probe in code
- Yaml stuff
> [0.17] Readyness probe in broker ingress

- test/upgrade/prober/verify.go
Fixes #
-
-
-
```release-note
```
**Docs**
> Fix typo in verify.go

- docs/spec/overview.md
ref https://github.com/knative/eventing/pull/565
Fixes #
-
-
-
```release-note
```
**Docs**
> clean up out of date docs

- .github/workflows/kind-e2e.yaml
- Debugging #4496 by logging the actual state of the pod.
-
-
```release-note
```
**Docs**
> dump the actual state of the pod when waiting for readiness.

- pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
- pkg/channel/fanout/fanout_message_handler.go
- pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
> Some code optimization in the test

- test/e2e/namespace_default_channel_test.go
Fixes #4498
Reduce raciness.
- Refactor TestChannelNamespaceDefaulting and retry multiple times with a delay in between.
/cc @vaikas @n3wscott
> Refactor TestChannelNamespaceDefaulting

- config/channels/in-memory-channel/deployments/dispatcher.yaml
Signed-off-by: runzexi <root@junwuhui.cn>
Fixes #
-
-
-
```release-note
```
**Docs**
> add imc dispatcher probe

- .github/workflows/kind-e2e.yaml
- Run kind e2e tests every 2 hours.
```release-note
```
**Docs**
> run kind e2e every 2 hours

- pkg/adapter/mtping/controller_test.go
- pkg/apis/sources/v1/container_conversion_test.go
- pkg/apis/sources/v1alpha2/container_conversion_test.go
- pkg/apis/sources/v1beta1/container_conversion_test.go
- pkg/apis/sources/v1beta1/ping_conversion_test.go
> Various small test nits

- test/README.md
Fixes #4256 
-
-
-
```release-note
```
**Docs**
> Add gcp-project-id option to test/e2e-tests.sh command in test/README.md

- hack/generate-yamls.sh
Fixes #https://github.com/knative/eventing/pull/4341#discussion_r524295251
-
-
-
```release-note
```
**Docs**
> fix generate yaml comments

- hack/generate-yamls.sh
Signed-off-by: runzexi <root@junwuhui.cn>
Fixes #4545 
/cc @n3wscott @pierDipi 
```release-note
```
**Docs**
> fix eventing nightly release

- OWNERS
- Removing myself from approvers and reviewers as I'll be mainly working on other project(s).
```release-note
```
**Docs**
> Removing nachocano from approvers and reviewers

- pkg/apis/sources/v1beta2/ping_conversion_test.go
These have probably gotten in in parallel to me removing stuff.
/assign @matzew
> Remove some more woke warnings

- cmd/webhook/main.go
- pkg/logconfig/config.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #4530
- Use webhook name from common pkg 
```release-note
```
**Docs**
> Get webhook name from pkg

- test/e2e-tests.sh
Fixes #
- bump to 20
-
-
```release-note
```
**Docs**
> Increasing parallel runs

- pkg/logconfig/config.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #
Remove deprecated function `WebhookName`
```release-note
```
**Docs**
> Remove deprecated function WebhookName

- pkg/apis/sources/v1beta1/ping_conversion.go
- pkg/apis/sources/v1beta1/ping_conversion_test.go
Fixes https://github.com/knative/eventing/issues/4584
- :bug: fix inconsistency between versions when updating PingSource
-
-
```release-note
```
**Docs**
> fix inconsistency between versions when updating PingSource

- test/e2e-common.sh
-
-
-
```release-note
```
**Docs**
> fix illegal byte sequence on Mac when running e2e tests

- .github/workflows/kind-e2e.yaml
Fixes #
- test e2e with k8s 1.20
-
-
```release-note
- :gift: Add new feature: Run e2e kind tests with k8s 1.20
```
**Docs**
> add tests using k8s 1.20

- docs/spec/channel.md
- pkg/apis/duck/v1/channelable_types.go
> Fix spec issue as discussed in #4057

- config/brokers/mt-channel-broker/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/dispatcher.yaml
- config/core/deployments/controller.yaml
- config/core/deployments/webhook.yaml
- config/sugar/500-controller.yaml
> Remove the field spec.replicas=1 for deployments

- cmd/mtbroker/filter/main.go
- cmd/mtbroker/ingress/main.go
- go.mod
- go.sum
- pkg/reconciler/inmemorychannel/dispatcher/controller.go
- pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
- vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
- vendor/knative.dev/pkg/configmap/manual_watcher.go
- vendor/knative.dev/pkg/configmap/testing/configmap.go
- vendor/knative.dev/pkg/injection/sharedmain/main.go
- vendor/knative.dev/pkg/metrics/config.go
- vendor/knative.dev/pkg/metrics/exporter.go
- vendor/knative.dev/pkg/test/mako/config/slack.go
- vendor/knative.dev/pkg/tracing/setup.go
- vendor/modules.txt
> Prepare for splitting configmap package.

- test/e2e/helpers/channel_single_event_helper.go
As labelled in the TODO, update the sender method
> Channel single event helper, send events via sendeventtoaddressable

- test/upgrade/prober/configuration.go
- test/upgrade/prober/prober.go
Fixes #4612 
- Add BrokerOptions to probe configuration
> feat/upgrade-test: Add configurable broker deployment options

- OWNERS
Criteria from https://github.com/knative/community/blob/master/ROLES.md#approver
> Reviewer of the codebase for at least 3 months:
First review:
#4192 , Oct 2nd, 2020
Substantial PRs reviewed (size/L, size/XL and size/XXL): https://github.com/knative/eventing/pulls?q=is%3Apr+-author%3Azhongduo+commenter%3Azhongduo+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM
24
Examples:
#4519 
#4460 
#4474 
#4655 
#4192 
#4493 
#4517 
#4474 
#4233 
#4659 
> Reviewed at least 30 PRs to the codebase
49
https://github.com/knative/eventing/pulls?q=is%3Apr+-author%3Azhongduo+commenter%3Azhongduo
My own PRs (though not in the requirements): https://github.com/knative/eventing/pulls?q=is%3Apr+author%3Azhongduo
12
Nominated by an area …
> Add zhongduo (Jimmy Lin) as an approver

- OWNERS
I don't expect to review PRs at the moment.
Fixes #
-
-
-
```release-note
```
**Docs**
> Remove myself from reviewers

- OWNERS
Fixes #
-
-
-
```release-note
```
**Docs**
> Remove yolocs from reviewer

- support/COMMUNITY_CONTACTS.md
- oncall schedule for the first 4 months of 2021
-
-
```release-note
```
**Docs**
> update oncall schedule

- support/COMMUNITY_CONTACTS.md
- support/NON_ROSTER
- support/VOLUNTEERS
Add a NON_ROSTER file so those looking to avoid/decline community support
> Update community support roster, extend to eventing reviewers

- test/e2e/channel_defaults_webhook_test.go
Similar to https://github.com/knative/eventing/pull/4711
- Fix panic in the TestChannelNamespaceDefaulting
> Fix panic in the TestChannelNamespaceDefaulting

- config/brokers/mt-channel-broker/deployments/broker-filter.yaml
- config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
- config/brokers/mt-channel-broker/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/dispatcher.yaml
- config/core/deployments/controller.yaml
- config/core/deployments/pingsource-mt-adapter.yaml
- config/sugar/500-controller.yaml
- pkg/reconciler/apiserversource/resources/receive_adapter.go
- pkg/reconciler/apiserversource/resources/receive_adapter_test.go
- pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go
- pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go
Fixes #4696
- ServiceLinks is already disabled in the Webhooks by this PR: https://github.com/knative/eventing/pull/4672
- This PR disables in all the other components
> Disabling servicelinks in all the components

- docs/spec/helper.md
Fixes #4732 
- Make it explicit that helper.md accompanying spec only pertains to components in this repo.
-
-
```release-note
```
**Docs**
> Add a note about implementation helper.md that it only pertains to this repo.

- .github/workflows/kind-e2e.yaml
- change the `1.19.x`  to `1.19.4` 
- add `1.20.0` image
```release-note
```
**Docs**
> KIND: run with 1.19.4 and 1.20.0

- pkg/apis/sources/v1/roundtrip_test.go
Fixes #
add roundtrip tests for sources v1 types 
- :gift: add roundtrip tests for sources v1 types
-
-
```release-note
```
**Docs**
> test(sources): add roundtrip tests for sources v1 types

- test/e2e-upgrade-tests.sh
- test/test_images/wathola-fetcher/main_test.go
- test/upgrade/prober/verify.go
- test/upgrade/prober/wathola/config/defaults.go
- test/upgrade/prober/wathola/config/structure.go
- test/upgrade/prober/wathola/event/operations.go
- test/upgrade/prober/wathola/event/services.go
- test/upgrade/prober/wathola/event/services_test.go
- test/upgrade/prober/wathola/event/types.go
- test/upgrade/prober/wathola/event/types_test.go
- test/upgrade/prober/wathola/fetcher/operations.go
- test/upgrade/prober/wathola/receiver/services.go
- test/upgrade/prober/wathola/receiver/services_test.go
- test/upgrade/prober/wathola/receiver/types.go
- test/upgrade/prober/wathola/sender/operations.go
- test/upgrade/prober/wathola/sender/services.go
Fixes #4540 
- Record total request count in the sender and send it in the final event
- Add log to the prober report
-
> Add availability rate to upgrade test report

- pkg/apis/sources/v1/sinkbinding_types.go
Fixes #
-
-
-
```release-note
```
**Docs**
> sinkbinding implements bindable

- pkg/adapter/v2/main.go
Fixes #4819
- Call `Fatal()` instead of `Error()` at the end of the shared main when an error is returned by the adapter's `Start()` method.
- (strech) Fix all calls to `logger.Method` that should have been `logger.Methodw`, fix capitalization of error logs.
> Call Fatal in shared main to propagate error to exit code

- pkg/reconciler/testing/v1/broker.go
- pkg/reconciler/testing/v1beta1/broker.go
Fixes #
-  :broom: Remove unused test helper functions.
-
-
```release-note
```
**Docs**
> remove unused functions

- pkg/apis/eventing/v1beta1/broker_validation.go
Fixes #
-  reject changes to immutable fields for broker/trigger
```release-note
```
**Docs**
> Add immutable fields validation to v1beta1 broker

- support/COMMUNITY_CONTACTS.md
Fixes #
- Change community rotation support from Harwayne to antoineco. Thanks @antoineco!!
-
-
```release-note
```
**Docs**
> switch Harwayne with antoineco

- .github/workflows/kind-e2e.yaml
Fixes #
- updates to latest 1.20.x version for Github Actions e2e tests
-
-
```release-note
```
**Docs**
> Latest of kindst image for e2e tests w/ 1.20.2

- pkg/adapter/mtping/runner.go
- The code I removed only applies when events are sent using the structured mode. However, by default, CloudEvents are sent in binary mode and PingSource does allow changing the default. 
-
-
```release-note
:wastebasket: PingSource: remove special handling of JSON data since events are always sent in binary mode.
```
**Docs**
> Remove json-specific logic useless for binary mode

- OWNERS
- Remove @Harwayne from OWNERS.
```release-note
NONE
```
> Remove Harwayne from OWNERS.

- docs/spec/broker.md
Fixes #
- Update the spec as decided from the discussion [here](https://github.com/knative/eventing/pull/4816#issuecomment-771014943)
```release-note
```
**Docs**
> Change broker spec to indicate brokerclass should be immutable

- .github/workflows/kind-e2e.yaml
Fixes #
- more recent versions
```release-note
```
**Docs**
> Updates for kind (newer version and newer images)

- config/core/deployments/webhook-hpa.yaml
Fixes #
- removing PDB from the name, since it's already in the kind
```release-note
```
**Docs**
> Remove suffix, since it's already in the PDB kind

- DEVELOPMENT.md
- Add a section in `DEVELOPMENT` file: Debugging Knative controllers and friends locally with Intellij Idea
-
-
```release-note
```
**Docs**
> [doc] Debugging Knative controllers and friends locally with Intellij Idea

- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
Relates to https://github.com/knative-sandbox/eventing-kafka/issues/398
- move over a better retry function
```release-note
```
**Docs**
> Adding checkRetry from kafkaChannel

- config/core/configmaps/default-pingsource.yaml
Caught via previous github action
> [trivial] update default-pingsource configmap checksum

- pkg/apis/flows/v1/parallel_validation_test.go
- pkg/apis/flows/v1beta1/parallel_validation_test.go
Closes #3861 
- Add unit tests for parallel_validation_test
> Add unit tests for parallel_validation_test

- pkg/reconciler/mtbroker/config.go
- pkg/reconciler/mtbroker/config_test.go
Addresses #4968
- Add more UT for mtbroker config code.
-
-
```release-note
```
**Docs**
> add more ut coverage

- pkg/reconciler/mtbroker/trigger/controller.go
- pkg/reconciler/mtbroker/trigger/controller_test.go
Fixes #4968 
- Refactor controller code for testability, add ut.
-
-
```release-note
```
**Docs**
> refactor for better testability, add ut

- .github/workflows/kind-e2e.yaml
There is no need to repeat this logic.
- Use the common test script in GH Actions
/kind cleanup
> Use the common test script in GH Actions

- go.mod
- go.sum
- test/rekt/features/broker/source_to_sink.go
- test/rekt/resources/broker/broker.go
- test/rekt/resources/svc/service.go
- test/rekt/resources/trigger/trigger.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
- vendor/knative.dev/reconciler-test/pkg/feature/collapse.go
- vendor/knative.dev/reconciler-test/pkg/feature/feature.go
- vendor/knative.dev/reconciler-test/pkg/feature/t.go
- vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
- vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
- vendor/modules.txt
see https://github.com/knative-sandbox/reconciler-test/pull/105
> update to breaking change for feature.T in reconciler-test

- pkg/adapter/v2/cloudevents_test.go
- pkg/adapter/v2/config_test.go
- pkg/adapter/v2/main.go
- pkg/adapter/v2/main_injection_test.go
- pkg/adapter/v2/main_message.go
- pkg/adapter/v2/main_message_test.go
- pkg/adapter/v2/main_test.go
- pkg/adapter/v2/test/test_client.go
Fixes https://github.com/knative/eventing/issues/4960
- Adding coverage to adapter code.
> adding code coverage to adapters v2

- pkg/mtbroker/filter/filter_handler_test.go
Fixes #4964 
- Add more coverage for pkg/mtbroker/filter
-
-
```release-note
```
**Docs**
> add test for trigger having a wrong UID

- pkg/reconciler/source/config_watcher_test.go
Related to https://github.com/knative/eventing/issues/4972
- Adding unit test coverage for some of the edge cases not covered.
/assign @vaikas
> add unit tests to reconciler/source/config_watcher

- pkg/reconciler/inmemorychannel/controller/controller.go
- pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
- pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
Fixes #
- Delete unused fields in IMC controller reconciler
```release-note
```
**Docs**
> Delete unused fields in IMC controller reconciler

- cmd/mtbroker/filter/main.go
- pkg/duck/subscriber_test.go
- pkg/eventfilter/attributes/filter.go
- pkg/mtbroker/filter/filter_handler.go
- pkg/mtbroker/filter/filter_handler_test.go
- pkg/reconciler/channel/channel_test.go
- pkg/reconciler/sequence/controller.go
- pkg/reconciler/sequence/sequence_test.go
- pkg/utils/utils_test.go
Addresses #4836 
- :broom: Remove more of the v1beta usages and use v1 instead. 
-
-
```release-note
```
**Docs**
> Change more internal usages of v1beta1 to v1

- .github/workflows/kind-e2e.yaml
As per title. Prep work for the master -> main rename.
> Run kind actions on main branch as well

- pkg/reconciler/sequence/sequence_test.go
Fixes #4971
- Add UT for deleting / creating after delete failures.
```release-note
```
**Docs**
> add UT for subscription delete/create failures

- .github/workflows/kind-e2e.yaml
- test/e2e-common.sh
- test/presubmit-tests.sh
Fixes #5030
- For kind e2e tests, only build linux/amd64 images.
```release-note
```
**Docs**
> only build linux/amd64

- test/rekt/features/pingsource/readyness.go
- test/rekt/resources/pingsource/pingsource.go
- test/rekt/resources/pingsource/pingsource.yaml
- test/rekt/resources/pingsource/pingsource_test.go
- test/rekt/smoke_test.go
relates to https://github.com/knative/eventing/issues/4954
Adding more smoke tests for pingsource
> smoke test more variants of pingsource

- support/COMMUNITY_CONTACTS.md
Fixes #
- Swap lberk / slinkydeveloper in the oncall rotation.
-
-
```release-note
```
**Docs**
> swap lberk / slinkydeveloper

- DEVELOPMENT.md
copied other tools from https://github.com/knative/serving/blob/main/DEVELOPMENT.md#install-requirements
Fixes #
-
-
-
```release-note
```
**Docs**
> bash v4 is required

- test/rekt/features/channel/readyness.go
- test/rekt/resources/channel/channel.go
- test/rekt/resources/channel/channel.yaml
- test/rekt/resources/channel/channel_test.go
- test/rekt/smoke_test.go
relates to https://github.com/knative/eventing/issues/4947
> smoketest a channel

- pkg/adapter/mtping/runner.go
https://github.com/knative/eventing/issues/5058
> Timezone not added to schedule in runner.go #5058

- support/COMMUNITY_CONTACTS.md
> Add query for doc issues that eventing eng. attention

- support/COMMUNITY_CONTACTS.md
Fixes #
- Fix the link for the machine readable rotation.
-
-
```release-note
```
**Docs**
> Fix the rotation support file name

- pkg/reconciler/apiserversource/apiserversource_test.go
Related to #4966
- Adding unit test coverage for some of the edge cases not covered.
```release-note
```
**Docs**
> add unit tests to reconciler/apiserversource

- support/support.rotation
Switch slinkydeveloper and devguyio rotations due to timeoff
> Switch slinkydeveloper and devguyio rotations

- test/e2e-rekt-tests.sh
- Unblock https://github.com/knative/eventing/pull/5064
> [release-0.19] Add placeholder rekt test script

- test/e2e-rekt-tests.sh
- Unblock https://github.com/knative/eventing/pull/5065
> [release-0.18] Add placeholder rekt test script

- test/rekt/broker_test.go
- test/rekt/features/broker/data_plane.go
Fixes #
- :gift: Add conformance test for CE version 0.3 and 1.0.
-
-
```release-note
```
**Docs**
> add data plane for ce versions

- test/rekt/features/broker/data_plane.go
Fixes #
- Check the return code is 2XX instead of only 202. My bad.
-
-
```release-note
```
**Docs**
> statuscode 200-299

- support/COMMUNITY_CONTACTS.md
> Update community support instructions with ux issue template info

- go.mod
- go.sum
- test/rekt/features/broker/data_plane.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
- vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/dropevents/receiver.go
- vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/event_info.go
- vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/receiver/receiver.go
- vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
- vendor/modules.txt
Fixes #
- Use the eventshub correlation for lining up sent/response events into one combined one.
-
-
```release-note
```
**Docs**
> Use correlation between send / response events

- test/rekt/features/broker/data_plane.go
Fixes #
- :gift: Add a conformance test for trying to send an event with wrong CE version.
-
-
```release-note
```
**Docs**
> Conformance test for wrong ce version

- pkg/reconciler/pingsource/controller.go
- pkg/reconciler/pingsource/pingsource.go
- pkg/reconciler/pingsource/pingsource_test.go
> More unit tests for pingsource

- test/rekt/features/broker/data_plane.go
Fixes #
- :gift: Add test for using GET method, should be rejected by Broker.
-
-
```release-note
```
**Docs**
> add conformance test for checking GET method gets rejected

- test/rekt/features/broker/data_plane.go
Fixes #
- :gift: Add conformance test for malformed (missing ce-specversion) event.
-
-
```release-note
```
**Docs**
> add test for rejecting malformed CE

- cmd/schema/main.go
- config/channels/in-memory-channel/resources/in-memory-channel.yaml
- test/rekt/channel_test.go
- test/rekt/features/channel/control_plane.go
Related to https://github.com/knative/eventing/issues/4935
This just is the spec language to test stubs.
Adding CRD info for IMC.
> adding todo stubs for channel conformance tests

- config/core/roles/podspecable-binding-clusterrole.yaml
- Fix the comment on the podspecable-binding clusterrole since it has nothing to do with Addressables
> Fix comment on podspecable-binding clusterrole

- test/conformance/channel_addressable_resolver_cluster_role_test.go
- test/conformance/channel_channelable_manipulator_cluster_role_test.go
- test/conformance/helpers/channel_addressable_resolver_cluster_role_test_helper.go
- test/conformance/helpers/channel_channelable_manipulator_cluster_role_test_helper.go
- test/conformance/helpers/rbac.go
- test/rekt/features/channel/control_plane.go
- test/rekt/resources/account_role/role.go
- test/rekt/resources/account_role/role.yaml
- test/rekt/resources/account_role/role_test.go
Related to https://github.com/knative/eventing/issues/4935
> adding role and role selector test for channels

- test/rekt/features/broker/data_plane.go
Fixes #
- Add tests for making sure that we require all the CE events before accepting. Spoiler alert, we do not. So I filed: https://github.com/knative/eventing/issues/5143 but this is the skeleton for adding all those tests.
-
-
```release-note
```
**Docs**
> add tests for various missing required fields

- pkg/adapter/v2/main.go
- pkg/adapter/v2/main_injection_test.go
- pkg/adapter/v2/main_test.go
- Wait for the controller to gracefully terminate so that the lease can be properly released (when it's the leader)
-
-
```release-note
:bug: Fix PingSource adapter not always releasing the leader election lease when terminating
```
**Docs**
> fix lease not always being released

- test/rekt/channel_test.go
- test/rekt/features/channel/control_plane.go
- test/rekt/features/channel/readyness.go
- test/rekt/resources/broker/broker.go
- test/rekt/resources/channel/channel.go
- test/rekt/resources/channel_impl/channel_impl.go
- test/rekt/resources/delivery/delivery.go
- test/rekt/resources/delivery/delivery.yaml
- test/rekt/resources/delivery/delivery_test.go
- test/rekt/resources/delivery/doc.go
- test/rekt/resources/subscription/subscription.go
- test/rekt/resources/subscription/subscription.yaml
- test/rekt/resources/subscription/subscription_test.go
related to https://github.com/knative/eventing/issues/4943 and https://github.com/knative/eventing/issues/4935
Adding smoke tests for subscriptions pointing to Channel and ChannelImpl
> adding channel subscription smoke tests

- test/rekt/channel_test.go
- test/rekt/features/channel/control_plane.go
- test/rekt/features/channel/data_plane.go
- test/rekt/features/channel/helpers.go
> Channel Data Plane Conformance Template

- DEVELOPMENT.md
Fixes #
-
-
-
```release-note
```
**Docs**
> Add devl instructions on receiving traffic with telepresence

- go.mod
- go.sum
- vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
- vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
- vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
- vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
- vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
- vendor/modules.txt
related to https://github.com/knative-sandbox/eventing-kafka/pull/532
> update to new release of golang sdk for cloudevents 2.4.1

- go.mod
- go.sum
- test/rekt/features/broker/control_plane.go
- test/rekt/features/broker/control_plane_test.go
- vendor/modules.txt
Fixes #
- :gift: Add tests for making sure that events end up where they should. There are couple of TODO's since upstream work is required.
-
-
```release-note
```
**Docs**
> Do events end where they should

- test/rekt/features/broker/control_plane.go
- test/rekt/features/broker/control_plane_test.go
Fixes #
- :gift: Add test for reply being routed correctly.
-
-
```release-note
```
**Docs**
> add test with reply

- test/rekt/features/channel/control_plane.go
- test/rekt/features/channel/helpers.go
Fixes https://github.com/knative/eventing/issues/5270
We have to be very careful to think about what we poll...
> [Rekt] Add polling on inner channel subscriber status

- pkg/broker/ingress/ingress_handler_test.go
> Add tests for additional ingress error cases

- test/rekt/features/broker/control_plane.go
Fixes #
- Break Delivery and Routing tests from a single Feature into a set of features where each table test is a Feature. This is in preparation to be able to utilize:
https://github.com/knative-sandbox/reconciler-test/issues/180
Also, we should be more mindful of each Feature cleaning up the resources it creates, so our future selves should also thank for this.
-
-
```release-note
```
**Docs**
> Custom type and reply

- .github/pull-request-template.md
We'd like all PRs to meet minimum coverage requirements for tests, docs, and specs. Make them explicit in the template.
> Add pre-review checklist to PR template

- config/core/resources/eventtype.yaml
Signed-off-by: runzexia <root@junwuhui.cn>
Fixes # ref https://github.com/knative/eventing/pull/3494
The presence of the fields is causing noise in the webhook logs for some reason.
> event type v1beta1

- pkg/reconciler/channel/channel_test.go
Signed-off-by: Ansu Varghese avarghese@us.ibm.com
Fixes #4967
> Another unit test for channel to increase coverage

- pkg/apis/sources/v1/container_validation_test.go
- pkg/apis/sources/v1beta1/container_validation_test.go
- pkg/broker/filter/filter_handler_test.go
- pkg/reconciler/source/duck/duck_test.go
- test/e2e_flags.go
Fixes #
- :broom: Update the outdated versions
```release-note
```
**Docs**
> [v1] Doing version bumps for some files to v1

- pkg/apis/eventing/v1/trigger_validation_test.go
Part of #4932
- :broom: Increase test coverage for Trigger validation
-
-
```release-note
```
**Docs**
> Increase Trigger validation test coverage

- config/channels/in-memory-channel/resources/in-memory-channel.yaml
- :broom: IMC `v1beta1` clean up, following up on: #5201
```release-note
```
**Docs**
> [v1] Tidy up the InMemoryChannel CRD to remove the v1beta1

- pkg/apis/messaging/v1/subscription_validation_test.go
NIT: follow up on Ali's #5305 (post review)
- :broom: Update the versions and API groups r clean up current behavior
-
```release-note
```
**Docs**
> [V1] Fixing versions and api groups for subscription validation test

- test/lib/creation.go
Fixes #5312
- :bug: fix e2e test flake on "No API token found for service account" errors on test pod creation
> CreatePodOrFail retry on "No API token found"

- config/channels/in-memory-channel/resources/in-memory-channel.yaml
- config/core/resources/channel.yaml
As per title 
- :broom: Updating yaml to have type desc. for IMC/Channel CRDs
-
-
```release-note
```
**Docs**
> [V1] Adding API description (e.g. for k explain) for IMC and generic Channel

- pkg/apis/messaging/config/channel_defaults_test.go
- :broom: Update channel default tests for `IMC/v1`
-
-
```release-note
```
**Docs**
> [V1] Remove some vbeta1 IMC configs in tests

- config/core/resources/parallel.yaml
- config/core/resources/sequence.yaml
Fixes #
- :broom: Update the description for the flows apis (Sequence and Parallel)
-
-
```release-note
```
**Docs**
> [v1] Add flows yaml desc

- pkg/apis/sources/v1/apiserver_validation_test.go
Part of #4921
- :broom: Increase ApiServerSource validation coverage to 100%
-
-
```release-note
```
**Docs**
> Increase ApiServerSource validation coverage

- test/rekt/features/broker/control_plane.go
- test/rekt/features/broker/data_plane.go
- test/rekt/features/broker/topology.go
- test/rekt/features/broker/topology_test.go
- test/rekt/features/channel/data_plane.go
- test/rekt/features/channel/topology.go
- test/rekt/features/channel/topology_test.go
- test/rekt/features/knconf/event_patterns.go
- test/rekt/features/knconf/event_patterns_test.go
Also testing more full event shapes for event based loop tests.
/assign @vaikas
> [Rekt] Let Channel and Broker tests use a common test pattern

- pkg/apis/messaging/config/channel_template_types.go
Fixes #
- Nit: correcting note on original API, pointing to v1, since v1beta1 is no longer here
-
-
```release-note
```
**Docs**
> Pointing to the proper v1 api, as the copy

- test/rekt/features/containersource/readyness.go
- test/rekt/resources/containersource/containersource.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/smoke_test.go
> Add containersource smoke test

- test/rekt/apiserversource_test.go
- test/rekt/features/apiserversource/client.go
- test/rekt/features/apiserversource/readiness.go
- test/rekt/features/apiserversource/webhook_validation_smoke.go
- test/rekt/resources/account_role/role.go
- test/rekt/resources/account_role/role.yaml
- test/rekt/resources/account_role/role_test.go
- test/rekt/resources/apiserversource/apiserversource.go
- test/rekt/resources/apiserversource/apiserversource.yaml
- test/rekt/resources/apiserversource/apiserversource_test.go
Part of #4921
- :broom: Add tests that make sure webhook kicks in to validate ApiServerSource on creation and updates
-
-
```release-note
```
**Docs**
> [v1] Test to make sure webhook validates ApiServerSource

- test/rekt/container_source_test.go
- test/rekt/features/containersource/features.go
- test/rekt/resources/containersource/containersource.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
> More containersource e2es

- test/rekt/smoke_test.go
Part of #4945
- Add ApiServerSource smoke tests, similar to https://github.com/knative/eventing/pull/5331
- Only minimum smoke tests in this PR, per the first list item in the ticket.
- More e2e tests coming with this PR (still WIP): https://github.com/knative/eventing/pull/5348
```release-note
```
**Docs**
> ApiServerSource smoke tests

- cmd/schema/main.go
- config/core/resources/sinkbindings.yaml
Fixes https://github.com/knative/eventing/issues/4930
- Update schema based on schema tool output.
- Drop conversion config in CRD (not used)
> Update SinkBinding Schema from Schema tool

- pkg/reconciler/testing/v1/listers.go
> Adding node lister

- cmd/schema/main.go
- config/core/resources/apiserversource.yaml
Fixes https://github.com/knative/eventing/issues/4921
- Update ApiServerSource based on the output from the schema tool.
> Update schema for api server source based on schema generator tool

- cmd/schema/main.go
- config/core/resources/containersource.yaml
Fixes https://github.com/knative/eventing/issues/4924
Fixes https://github.com/knative/eventing/issues/5353
- Update container source with the output of the schema tool
> update containersource to use the output of the schema tool

- test/rekt/apiserversource_test.go
- test/rekt/features/apiserversource/data_plane.go
- test/rekt/features/apiserversource/webhook_validation_smoke.go
- test/rekt/resources/apiserversource/apiserversource.go
- test/rekt/resources/apiserversource/apiserversource.yaml
- test/rekt/resources/apiserversource/apiserversource_test.go
- test/rekt/resources/deployment/deployment.go
- test/rekt/resources/pod/pod.go
- test/rekt/resources/pod/pod.yaml
- test/rekt/resources/pod/pod_test.go
Part of #4945
- Add e2e tests for ApiServerSource
- 2 things missing in this PR (noted in the ticket as well)
- Testing if ApiServerSource is indeed not sending events from other resources when there's a label matching used
- Testing to see if all 3 events (add, update, delete) are received. Currently only 'add' event is checked.
```release-note
```
**Docs**
> ApiServerSource e2e tests

- test/rekt/apiserversource_test.go
Related to #5371 
- skipping flaky test
-
-
```release-note
```
**Docs**
> Skipping recently introduced API SERVER SOURCE test

- support/COMMUNITY_CONTACTS.md
I'm no longer actively monitoring community questions or test health.
> Remove myself from community contacts

- pkg/reconciler/testing/v1/listers.go
> Adding pod lister

- test/e2e/helpers/channel_chain_test_helper.go
My derp, in #5382 I only added back one of these removed helpers.
@lionelvillard @eclipselu @n3wscott @aavarghese
> Add the channel chain helper back

- test/rekt/features/sequence/readyness.go
- test/rekt/resources/sequence/sequence.go
- test/rekt/resources/sequence/sequence.yaml
- test/rekt/resources/sequence/sequence_test.go
- test/rekt/smoke_test.go
Related to https://github.com/knative/eventing/issues/4953
> [rekt ]adding sequence smoke test

- pkg/reconciler/sinkbinding/controller.go
Right now we don't have this tracking relationship, I think we just rely on the sink to exist around the same time the subject is created. In CI we've seen a bunch of failures that I think were caused by this, maybe due to slow environments.
https://github.com/knative/eventing/runs/2556532613?check_suite_focus=true#step:11:5265
https://github.com/knative/eventing/runs/2555512989?check_suite_focus=true#step:11:5263
https://github.com/knative/eventing/runs/2553609214?check_suite_focus=true#step:11:5292
https://github.com/knative/eventing/runs/2553609214?check_suite_focus=true#step:11:5292
https://github.com/knative/eventing/runs/2552732821?check_suite_focus=true#step:11:5262
https://github.com/knative/eventing/runs/2552732821?check_suite_focus=true#step:11:5262 …
> SinkBindings track their sinks

- pkg/broker/ingress/ingress_handler.go
Signed-off-by: runzexi <root@junwuhui.cn>
Fixes #
-
-
-
```release-note
```
**Docs**
> mt broker dispatch error log

- test/rekt/features/channel/features.go
Fixes a race condition where the event source could start producing events before the channel's subscribers had successfully reconciled and the events would be dropped.
Fixes #5431
> Fix ordering in EventTransformation test

- pkg/broker/ingress/ingress_handler.go
- pkg/channel/message_dispatcher.go
- pkg/channel/message_dispatcher_test.go
Fixes #5427
- :bug: Remove unprintable characters from the response body to avoid dead-letter sink request errors
```release-note
```
**Docs**
> Remove unprintable characters from Ce-Knativeerrordata header

- docs/experimental-features.md
- Fix a broken link in experimental-features.md
> Fix a broken link in experimental-features.md

- test/rekt/resources/trigger/trigger.go
- test/rekt/resources/trigger/trigger.yaml
- :gift: Now rekt/resources/trigger allows you to add a trigger annotation. This is a prerequisite for https://github.com/knative-sandbox/eventing-kafka-broker/issues/731
> rekt/resources: support trigger annotations

- test/rekt/resources/broker/broker.go
- test/rekt/resources/broker/broker_test.go
Followup of #5456, always in the context of https://github.com/knative-sandbox/eventing-kafka-broker/issues/731
> Added broker.WithConfig

- test/rekt/resources/broker/broker.go
Fixes the lint warning about using a deprecated version.
-
-
-
```release-note
```
**Docs**
> Fix lint: Use the non-deprecated version

- pkg/adapter/v2/cloudevents.go
- pkg/adapter/v2/cloudevents_test.go
- :broom: Receive Adapter's `StartReceiver()` method implemented,
- :broom: Cloudevents Client creation functions slightly refactored to able to test StartReceiver method.
To expand the Receive Adapter application scope, the client's `StartReceiver()` method should handle incoming Cloudevents. An example use case of this method may be a webhook source that is receiving Cloudevents from an external system. Besides, the receiver is not necessarily purposed for the sources only - it can be used in other components that may be responsible for internal events processing (integration, transformation, etc.) where everything is happening in CE data format.
```release-note
```
**Docs**
> Adapter's `StartReceiver()` method implemented

- .github/workflows/kind-e2e.yaml
Fixes #
- :broom: Adding k8s 1.21
- :wastebasket: drop 1.18 (see https://knative.dev/community/contributing/mechanics/release-versioning-principles/#knative-eventing-version-table)
- :broom:  updates to 1.19 and 1.20 line
-
-
```release-note
```
**Docs**
> KIND Updates

- pkg/reconciler/source/duck/controller_test.go
Fixes: https://github.com/knative/eventing/pull/5477#pullrequestreview-679246528
> clean up extra With call

- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
- pkg/kncloudevents/retries.go
- pkg/kncloudevents/retries_test.go
This is some reorganization of the code I've made while looking at how to implement delivery timeout. There are no code changes
- :broom: Just reorganized a bit the kncloudevents code
```release-note
```
**Docs**
> Reorganized kncloudevents retries code

- test/e2e-common.sh
> Drop --strict flag on ko

- go.mod
- go.sum
- vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
- vendor/modules.txt
Fixes #
Get in the fix at https://github.com/knative-sandbox/reconciler-test/pull/218
-
-
-
```release-note
```
**Docs**
> ./hack/update-deps.sh --upgrade

- support/COMMUNITY_CONTACTS.md
- support/NON_ROSTER
- support/ROSTER
- support/VOLUNTEERS
- support/support.rotation
Since OWNERS only contains aliases I replaced it with `support/ROSTER`.
> Extend rotation calendar

- pkg/apis/messaging/v1/subscription_types.go
:broom: Change references of Result to Reply that had been left in by accident.
-
-
-
```release-note
```
**Docs**
> Change Result->Reply in comments, left over cruft

- config/brokers/mt-channel-broker/deployments/broker-filter.yaml
- config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
- config/brokers/mt-channel-broker/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/dispatcher.yaml
- config/core/deployments/controller.yaml
- config/post-install/storage-version-migrator.yaml
- config/sugar/500-controller.yaml
Implements suggestions reported by [kube-linter tool](https://github.com/stackrox/kube-linter) outside of config/core package.
This applies similar changes to #5611 outside config/core. Also fixes https://github.com/knative/eventing/pull/5611#discussion_r677302453.
/assign @matzew @vaikas
> Improve security-related config in more yaml files

- support/ROSTER
Add myself to the support roster, still need to update the schedule but I think that's handled separately.
/assign @devguyio
> Add myself to support roster

- pkg/reconciler/source/crd/crd.go
This'll unblock https://github.com/knative/eventing/pull/5635
/assign @matzew
> Fix deprecation of controller.Run to controller.RunContext

- support/ROSTER
Fixes #
-
-
-
```release-note
```
**Docs**
> remove vaikas from roster

- support/COMMUNITY_CONTACTS.md
- support/ROSTER
- support/support.rotation
- Generate new rotation for the community contact
- Remove @n3wscott from roster. 
- Cleans up the support rotation docs to match the current roster.
> Generate new community contact table

- docs/eventing-api.md
- pkg/apis/messaging/v1/channel_types_test.go
- pkg/apis/messaging/v1/in_memory_channel_types.go
- pkg/apis/messaging/v1/in_memory_channel_types_test.go
- :broom: remove `_` underscore from test function name and correcting API docs
-
```release-note
```
**Docs**
> fixing minor things

- pkg/reconciler/source/duck/controller.go
/kind cleanup
```release-note
```
**Docs**
> Use `controller.NewContext`

- pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
Fixes #
- :broom: Make usage of `GetConditionSet`, instead of direct access
-
-
```release-note
```
**Docs**
> Make usage of GetConditionSet, rather than direct access

- config/tools/heartbeats/heartbeats.yaml
- hack/generate-yamls.sh
Fixes #5678
- :gift: Produce a heartbeats image as part of releases along with a sample ContainerSource manifest
> Add heartbeats image to released images

- pkg/apis/eventing/v1/broker_validation.go
- pkg/apis/eventing/v1/broker_validation_test.go
Fixes #5663 
- updates to `spec.config` should be impossible
```release-note
```
**Docs**
> Validate broker spec config immutable

- cmd/heartbeats/main.go
- :gift: Add ability to specify heartbeat durations as a time.Duration
This lets us be more granular than the previous assumption of a seconds integer.
```release-note
:page_facing_up: The heartbeats sample app now supports Golang-style time durations as the `period` interval
```
> Add ability to specify heartbeat durations as a time.Duration

- test/conformance/helpers/broker_control_plane_test_helper.go
Following up on code change via #5682 
- adding a new conformance test 
-
-
```release-note
```
**Docs**
> [1.0] Conformance test for Spec.Config being immutable

- docs/spec/sources.md
Fixes #
- updating the source spec to be clear on the CRD api shape to use )
-
-
```release-note
```
**Docs**
> [1.0] SPEC: Going w/ v1 API shape for CRDs

- test/lib/test_runner.go
Fixes #5700
- Increase MaxNamespaceSkip
-
-
```release-note
```
**Docs**
> Test runner: Increase MaxNamespaceSkip

- pkg/reconciler/resources/service_account_test.go
as per title
/assign @pierDipi
> Update resources test to use latest PingSource API

- test/e2e-common.sh
Fixes #
- :broom:  fixing error message
-
-
```release-note
```
**Docs**
> fixing error message

- config/tools/recordevents/recordevents.yaml
-  :gift: publish recordevents image 
-
-
```release-note
```
**Docs**
> Add record events to released images

- hack/generate-yamls.sh
https://github.com/knative/eventing/pull/5734 followup 
- Really publish recordevents image (and yaml)
-
-
```release-note
```
**Docs**
> add recordevents to the list of tools to publish

- support/COMMUNITY_CONTACTS.md
> Fixes eventing testgrid url on community contacts md file

- test/lib/duck/resource_getters.go
Since this library is used in any downstream project, 
we want to retry any webhook EOF error not only eventing core
webhooks.
- Retry on any webhook EOF error
```release-note
None
```
**Docs**
```
None
```
> Retry on any webhook EOF error

- test/lib/creation.go
We had 2 functions that were doing the same thing,
this patch removes one of them to reduce duplication.
- Deduplicate retry Webhook EOF error functions
```release-note
None
```
**Docs**
```
None
```
> Deduplicate retry Webhook EOF error functions

- test/conformance/helpers/broker_control_plane_test_helper.go
This patch adds the workaround for https://github.com/knative/pkg/issues/1509
to one of our (legacy) conformance tests.
Fixes (some flaky tests)
- Retry on Webhook EOF in conformance tests
```release-note
None
```
**Docs**
```
None
```
> Retry on Webhook EOF in Broker conformance tests

- docs/personas.md
- :gift: Add a description for the  "System Operator" persona
> Add System Operator persona

- test/lib/operation.go
We're seeing this error:
```
broker_test_helper.go:216: Error annotating namespace: Operation cannot be fulfilled on namespaces "eventing-e2e7": the object has been modified; please apply your changes to the latest version and try again
```
Fixes (some flaky tests)
- Retry on conflicts when labeling namespaces in tests
```release-note
None
```
**Docs**
```
None
```
> Retry on conflicts when labeling namespaces in tests

- test/e2e/helpers/broker_test_helper.go
- test/e2e/source_api_server_v1_test.go
- test/e2e/source_ping_v1_test.go
- test/e2e/source_ping_v1beta2_test.go
- test/e2e/trigger_dependency_annotation_test.go
nit: fix a confusing error message when labeling fails.
https://github.com/knative/eventing/pull/5925#pullrequestreview-812760471
> nit: when labeling replace annotating with labeling

- docs/broker/README.md
> Update MT Broker design doc link to public accessible doc

- .github/workflows/kind-e2e.yaml
Fixes #
-
-
-
```release-note
```
**Docs**
> Using k8s 1.23 for GH Action e2e workflow

- pkg/broker/filter/filter_handler_test.go
- :broom: Refactor and clean up of filter receiver tests in preparation for adding enhanced filters tests
> Refactor filter receiver tests

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
As per title, following the same pattern of `http.Handler` and 
`http.HandlerFunc` in the standard library, 
see code comments for more details.
- Add SchedulerFunc type implementing Scheduler as func
```release-note
None
```
**Docs**
```
None
```
> Add SchedulerFunc type implementing Scheduler as func

- docs/eventing-api.md
- hack/reference-docs-gen-config.json
Fixes #6029
- Fixed broken links by changing kubernetes document link from v1.18 to v1.19
```release-note
NONE
```
**Docs**
NONE
> Fix broken links in docs

- support/VOLUNTEERS
Add myself 😁 to support rotation
> Update support Volunteers

- support/support.rotation
Fixes #
-
-
-
```release-note
```
**Docs**
> fix wrong date.

- test/test_images/event-library/kodata/events
- test/test_images/event-library/kodata/events/doc.go
- test/test_images/event-library/kodata/events/three.ce
Fixes #6048
- :bug: Make event-library test image 'vendorable'
- Convert the symlink to an actual copy paste
- Go tool doesn't follow symlinks when vendoring
```release-note
```
**Docs**
> Make event-library test image 'vendorable'

- test/e2e-tests.sh
- test/lib/client.go
- test/lib/operation.go
This is useful for debugging failed tests.
> Dump resources when failed to wait for them to become ready

- docs/metrics.md
- docs/spec/broker.md
- docs/spec/channel.md
- docs/spec/helper.md
- docs/spec/interfaces.md
- docs/spec/spec.md
Fixes #5989 
- fixed broker links in the docs/broker and channel mds
- removed helper, interfaces and spec md files cause everything is now explained in the data plane
- rephrased metrics md in eventing
```release-note
```
**Docs**
> Fixing docs eventing spec details

- go.mod
- go.sum
- pkg/reconciler/broker/trigger/trigger_test.go
- pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
- pkg/reconciler/subscription/subscription_test.go
- pkg/reconciler/testing/v1/inmemorychannel.go
- vendor/knative.dev/pkg/resolver/addressable_resolver.go
- vendor/modules.txt
As per title, see individual commits for more details.
> Upgrade knative.dev/pkg@main and fix test errors

- .github/workflows/kind-e2e.yaml
Fixes #
- newer k8s versions for Github Action e2e
-
-
```release-note
```
**Docs**
> Updating to newer versions of k8s for GH Actions :dizzy:

- .github/workflows/knative-downstream.yaml
Fixes #
-  :broom: Remove deprecated and unmaintained repos from downstream action
-
-
```release-note
```
**Docs**
> Remove deprecated and unmaintained repos from downstream action

- test/config/chaosduck/chaosduck.yaml
- Reduce the frequency of terminating pods.
-
-
```release-note
```
**Docs**
> tame a bit the duck

- hack/update-codegen.sh
- pkg/apis/duck/v1alpha1/placement_types.go
- :bug: duck v1alpha1 DeepCopy functions are now properly generated. 
-
-
```release-note
```
**Docs**
> Generate duck v1alpha1 DeepCopy functions

- support/support.rotation
Updating the community contact rotation table. Holding to give time to review.
/hold
> Update community contact rotation

- pkg/scheduler/statefulset/scheduler.go
- Refactored some code into a helper method (for re-use later)
- Call addReplicas... with a new placements list (to allow for full re-balancing without placements history)
/cc @lionelvillard
> Make zero placements for rebalancing with fresh State

- docs/source/README.md
fixing links in docs/source.md
> fixing links in docs/source.md

- test/e2e-rekt-tests.sh
- test/rekt/broker_test.go
Fixes #
-
-
-
```release-note
```
**Docs**
/hold
> Increase rekt test timings and reduce concurrency

- test/e2e-rekt-tests.sh
- 🐛 adding min and max nodes annotation to rekt tests entrypoint
> Adding min and max nodes annotation to rekt tests entrypoint

- test/rekt/channel_test.go
- test/rekt/features/channel/features.go
> Test Channel as dead letter sink

- test/upgrade/prober/verify.go
Exporting traces for a large number of events can exceed the timeout of
the whole test suite, leading to all upgrade tests being reported as
failed.
- export only first 1000 events of each type
```release-note
```
**Docs**
> Limit the number of exported traces

- test/upgrade/prober/verify.go
- test/upgrade/prober/wathola/event/services.go
- test/upgrade/prober/wathola/event/services_test.go
- test/upgrade/prober/wathola/event/types.go
- test/upgrade/prober/wathola/sender/services.go
Fixes #6373
- Send information by the sender for events that were delivered after retries and exceeded the max. unavailable period
- Report such errors on receiver side
- Export trace for those events, similar to what we already do for missing/duplicate events
```release-note
```
**Docs**
> Export trace for events that exceed allowed unavailable period

- test/lib/resources/eventing.go
Fixes #
- :gift: adding util for adding custom annotation values to different broker implementation usage
-
-
```release-note
```
**Docs**
> adding util for adding custom annotation values to different broker implementation usage

- test/rekt/features/broker/data_plane.go
Partially addressed issue #5782 
- :bug: replace todo with real validation methods for ingress feature in broker conformance test
> Add validation methods for ingress feature in broker conformance test

- config/channels/in-memory-channel/deployments/controller.yaml
- config/core/deployments/webhook.yaml
- Increase the default value of update-initialDelaySeconds to 120, per the change in https://github.com/knative/pkg/pull/2391.
```release-note
```
**Docs**
> Increase initialDelaySeconds to 120 for webhooks

- test/e2e/source_ping_v1_test.go
- test/e2e/source_ping_v1beta2_test.go
- test/rekt/features/pingsource/features.go
- test/rekt/pingsource_test.go
- Port Pingsource workflow test to rekt
> Port Pingsource test to rekt

- .github/workflows/knative-downstream.yaml
- DEVELOPMENT.md
- go.mod
- go.sum
knative/pkg uses 1.18 features.
> use go 1.18 

- test/upgrade/prober/configuration.go
- test/upgrade/prober/wathola/sender/services.go
- test/upgrade/prober/wathola/sender/types.go
- Remove functions from the upgrade framework that were deprecated for some time
```release-note
```
**Docs**
> Remove deprecated functions from test/upgrade package

- cmd/broker/filter/main.go
- cmd/broker/ingress/main.go
- cmd/event_display/main.go
- cmd/heartbeats/main.go
- cmd/mtchannel_broker/main.go
- pkg/adapter/v2/config.go
- pkg/adapter/v2/configurator_configmap.go
- pkg/adapter/v2/configurator_environment.go
- pkg/adapter/v2/main.go
- pkg/adapter/v2/main_message.go
- pkg/channel/message_receiver_test.go
- pkg/inmemorychannel/message_dispatcher_test.go
- pkg/reconciler/broker/controller.go
- pkg/reconciler/inmemorychannel/dispatcher/controller.go
- test/test_images/event-sender/main.go
- test/test_images/recordevents/main.go
- test/test_images/utils.go
- test/test_images/wathola-forwarder/main.go
- test/test_images/wathola-receiver/main.go
- test/test_images/wathola-sender/main.go
- test/upgrade/prober/wathola/config/tracing.go
- test/upgrade/prober/wathola/forwarder/services.go
- test/upgrade/prober/wathola/receiver/services.go
- test/upgrade/prober/wathola/sender/operations.go
- test/upgrade/prober/wathola/sender/services.go
- test/upgrade/prober/wathola/sender/services_test.go
This is a follow-up on https://github.com/knative/pkg/pull/2566.
- Setup Trace publishing and return the tracer which is later shutdown at the end of the process.
```release-note
```
**Docs**
> Make sure tracer is shut down across components

- docs/planning/sprintplanning.md
Fixes knative/community#1096
- :broom: Quarterly release cadence
> :broom: Quarterly release cadence

- test/e2e/broker_redelivery_test.go
- test/e2e/helpers/broker_redelivery_helper.go
- test/rekt/broker_test.go
- test/rekt/features/broker/feature.go
- Port Broker redelivery e2e test to rekt
- Remove old e2e test
> Knative port broker redelivery test to rekt

- .github/workflows/kind-e2e.yaml
- Removing 1.22, since we have soon the [min-version of 1.23](https://github.com/knative/pkg/pull/2595/files)
```release-note
```
**Docs**
> Remove kind 1.22 testing, since we will min-version 1.23 soon

- docs/eventing-api.md
- pkg/apis/eventing/v1/trigger_types.go
- pkg/broker/filter/filter_handler.go
- pkg/eventfilter/subscriptionsapi/exact_filter.go
- pkg/eventfilter/subscriptionsapi/exact_filter_test.go
- pkg/eventfilter/subscriptionsapi/prefix_filter.go
- pkg/eventfilter/subscriptionsapi/prefix_filter_test.go
- pkg/eventfilter/subscriptionsapi/suffix_filter.go
- pkg/eventfilter/subscriptionsapi/suffix_filter_test.go
- test/experimental/features/new_trigger_filters/filters.go
Fixes #6201 
- :bug: Update exact, prefix and suffix filters to accept multiple entries
> Update exact, prefix and suffix filters to accept multiple entries

- go.mod
- go.sum
- vendor/knative.dev/reconciler-test/pkg/environment/images.go
- vendor/modules.txt
> [release-1.8] Upgrade dependencies

- .github/workflows/kind-e2e.yaml
Following up on #6616:
- bump kind to 0.17.0
- bump k8s to 1.25.3
```release-note
```
**Docs**
> Bump kind and k8s

- test/rekt/resources/broker/broker.go
- test/rekt/resources/broker/broker.yaml
- test/rekt/resources/broker/broker_test.go
Fixes #
- :gift: Adding WithAnnotations for the broker resource on rekt-testing
```release-note
Adding WithAnnotations for testing custom annotations on the broker resource
```
**Docs**
> Adding WithAnnotations for the broker resource on rekt-testing

- test/rekt/features/parallel/features.go
- test/rekt/parallel_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
- Port Parallel e2e to rekt
- Add a function to simulate filter service
```release-note
```
**Docs**
> Port Parallel e2e test to rekt

- DEVELOPMENT.md
Fixes #
- as per title
```release-note
```
**Docs**
> Fixing broken links on development doc

- DEVELOPMENT.md
Currently the development documentation about debugging seems to be based on Telepresence v1 whereas v2 has be out for a while. In addition it only covered debugging details for IntelliJ IDEA.
* :broom: Update debugging documentation to support Telepresence v2
* :gift: Add information about debugging with VSCode
```release-note
```
> Update debugging documentation and add details for VSCode

- test/rekt/broker_test.go
- test/rekt/features/broker/feature.go
Relates to #6648
- Adding large CE for testing the delivery
```release-note
```
**Docs**
> Adding a testcase with a long CE

- test/rekt/broker_test.go
- test/rekt/features/broker/feature.go
Porting #6666 to our 1.8 branch
> [release-1.8] Testcase for long message

- test/e2e/broker_channel_flow_test.go
- test/e2e/helpers/broker_channel_flow_helper.go
- test/rekt/broker_test.go
- test/rekt/features/broker/feature.go
Fixes #
- Port BrokerChannelFlowWithTransformation to reconciler test 
- Remove old e2e test
```release-note
```
**Docs**
> Knative port broker channel flow topology test to rekt

- test/e2e/broker_event_transformation_test.go
- test/e2e/helpers/broker_event_transformation_test_helper.go
- test/rekt/broker_test.go
- test/rekt/features/broker/feature.go
Fixes #
- Port BrokerWorkFlowWithTranformation test to rekt and code cleanup
```release-note
```
**Docs**
> Port BrokerWorkFlowWithTranformation test to rekt and code cleanup

- pkg/kncloudevents/message_sender.go
- :broom: Removing deprecated and unused func
```release-note
:broom: The deprecated NewHTTPMessageSender func has been removed
```
**Docs**
> Removing deprecated and unused func

- pkg/duck/listable.go
- as per title
```release-note
```
**Docs**
> Removing one more deprecated, unused func

- pkg/scheduler/scheduler.go
- pkg/scheduler/state/state.go
- pkg/scheduler/statefulset/scheduler.go
- Log collected state
- Log pending vpods
> Improve scheduler logging for state and pending vpods

- test/upgrade/prober/verify.go
Fixes https://github.com/knative-sandbox/eventing-kafka-broker/issues/2970
The issue in eventing-kafka-broker will be fixed when this change propagates to the repo.
It started to happen after integrating changes from knative.dev/pkg which run all the continual tests in parallel, including the "verify" phase which sets the zipkin.ZipkinTracingEnabled flag.
- Guard access to zipkin tracing flag by lock
-
-
```release-note
```
**Docs**
> Exclusive access to tracing flag for upgrade prober

- test/rekt/broker_test.go
Similar to the Prerequisite step one line above
> Pass EnvConfig to Broker conformance tests

- test/upgrade/prober/verify.go
Remove deprecated usage after upgrading dependencies via https://github.com/knative/eventing/commit/07e6d0c0c481afd1a2163b9aa5c9a2302551ef18
-
-
-
```release-note
```
**Docs**
> Remove deprecated usage of ZipkinTracingEnabled

- pkg/channel/message_dispatcher.go
- pkg/channel/message_dispatcher_test.go
- test/rekt/broker_test.go
- test/rekt/features/broker/feature.go
cherry-pick of #6758 
```release-note
🐛 Fixes an issue where a Cloud Event in a response from a sink was truncated to 1024 bytes
```
> [release-1.8] Fixes issue where a CE response is truncated #6782

- pkg/channel/message_dispatcher.go
- pkg/channel/message_dispatcher_test.go
- test/rekt/broker_test.go
- test/rekt/features/broker/feature.go
```release-note
🐛 Fixes an issue where a Cloud Event in a response from a sink was truncated to 1024 bytes
```
> [release-1.9] Fixes issue where a CE response is truncated

- cmd/heartbeats/main.go
Sometimes the delivery fails for networking errors by retrying we would have better expected results and be more resilient.
This is very common when running in a job with Istio sidercar injected.
> Add basic retry support for hearthbeats utility

- test/rekt/features/parallel/features.go
- test/rekt/features/sequence/feature.go
- test/rekt/resources/channel_template/channel_template.go
- test/rekt/resources/parallel/parallel.go
- test/rekt/resources/sequence/sequence.go
- test/rekt/sequence_test.go
- test/rekt/smoke_test.go
- Add sequence reconciler test
```release-note
```
**Docs**
> Add sequence reconciler test

- test/rekt/features/parallel/features.go
- test/rekt/parallel_test.go
- Parallel rekt test cleanup
```release-note
```
**Docs**
> parallel rekt test cleanup

- pkg/scheduler/statefulset/autoscaler.go
- pkg/scheduler/statefulset/scheduler.go
- as per title
```release-note
```
**Docs**
> less verbose logs on scheduler component 

- pkg/scheduler/statefulset/scheduler.go
- while porting the earlier PR over to a different branch, I noticed two more that could be just `debug`
```release-note
```
**Docs**
> two more for reducing to debug, instead of info

- pkg/reconciler/testing/v1beta2/eventtype.go
Fixes #6943
- adding new test file for v1b2
(will make use of that on the rebase of #6870) 
```release-note
```
**Docs**
> Adding testingv1b2 for eventtype

- test/rekt/resources/eventtype/eventtype.go
Fixes #6947
-
-
-
```release-note
```
**Docs**
> Updating rekt test resources for EventType v1b2

- pkg/adapter/mtping/runner_test.go
`TestSendEventsTLS` for PingSource is flaky
> Fix flaky PingSource TLS unit test

- pkg/reconciler/pingsource/controller_test.go
- minor upate: using latest EventType version on ping source test informers
```release-note
```
**Docs**
> test update to newest version

- test/rekt/features/sinkbinding/feature.go
- test/rekt/resources/sinkbinding/sinkbinding.go
- test/rekt/resources/sinkbinding/sinkbinding.yaml
- test/rekt/resources/sinkbinding/sinkbinding_test.go
- test/rekt/sink_binding_test.go
> test SinkBinding with eventshub TLS receiver as sink

- cmd/heartbeats/main.go
- test/test_images/wathola-fetcher/main.go
HTTP GET doesn't work.
-
-
-
```release-note
```
**Docs**
> Use HTTP POST when terminating istio proxy

- test/rekt/pingsource_test.go
Fixes #
- as per title
```release-note
```
**Docs**
> Skip ping source TLS rekt test, since extremely flaky

- config/channels/in-memory-channel/resources/in-memory-channel.yaml
The updates on the addressable/addressstatus should be reflected in the IMC CRD too.
> Update IMC CRD addressstatus to include `.name` and `.CACerts` fields

- pkg/kncloudevents/http_client_new.go
- pkg/kncloudevents/http_client_new_test.go
Fixes #6996 
- Add  an expiry time to each entry in the clients map, and extend it every time that client is accessed.
- Run a goroutine which periodically scans the clients map, and deletes any expired entries
-
```release-note
```
**Docs**
> Added basic gc loop to kncloudevents clients map

- pkg/apis/eventing/v1beta2/eventtype_defaults.go
- pkg/reconciler/eventtype/eventtype_test.go
- as per title
```release-note
```
**Docs**
> Adjust the Namespace reference to the one from the parent

- pkg/resolver/kresource_resolver.go
Fixes #
- as per commit log 
```release-note
```
**Docs**
> Remove check for empty Namespace on resolver

- pkg/adapter/mtping/runner_test.go
- pkg/channel/message_dispatcher_test.go
- pkg/eventingtls/eventingtlstesting/utils.go
> Fix flaky unit tests

- README.md
Fixes #7030
- catchy tag line
- better desc. of the project
```release-note
```
**Docs**
> Tag line proposal

- pkg/reconciler/inmemorychannel/controller/controller.go
- pkg/reconciler/inmemorychannel/controller/controller_test.go
This will allow updating IMC addresses based on transport-encryption feature flag
> Watch config-features in IMC controller

- .github/workflows/kind-e2e.yaml
> Update to kind v0.20.0

- pkg/eventtype/eventtypes.go
- pkg/eventtype/eventtypes_test.go
Fixes #7097
- :bug: Fix unique name generator for auto-created EventType)
```release-note
Fix unique name generator for auto-created `EventType`
```
/cc @Cali0707 @matzew
> Fix unique name generator for auto-created EventType

- test/rekt/features/sinkbinding/feature.go
- test/rekt/resources/sinkbinding/sinkbinding.go
- test/rekt/sink_binding_test.go
> Eventing TLS: Test SinkBinding with Broker as sink

- README.md
Part of https://github.com/knative/community/issues/1403
- Add a link to the README pointing users to the CLOTributor page for knative eventing
> Added clotributor link to readme

- config/core/resources/apiserversource.yaml
- config/core/resources/pingsource.yaml
- as per title: more metadata for existing event types
```release-note
```
**Docs**
> Adding description for the built-in event types of our duck sources

- test/rekt/resources/subscription/subscription.go
- test/rekt/resources/subscription/subscription.yaml
This is a bug fix. Some parts were missed in the previous commit.
Fixes some missing parts from https://github.com/knative/eventing/commit/81d8e965cc775b287aeb070d073b537bc96981b8
-
-
-
```release-note
```
**Docs**
> Subscription allows overriding namespace for Subscriber and Reply

- config/brokers/mt-channel-broker-tls/broker-filter-tls-certificate.yaml
- config/brokers/mt-channel-broker-tls/broker-ingress-tls-certificate.yaml
- config/channels/in-memory-channel-tls/imc-dispatcher-tls-certificate.yaml
I'm setting the fields to what cert-manager expects so that we don't run into this issue https://github.com/cert-manager/cert-manager/issues/6408
> Workaround for cert-manager update spec issue

- pkg/reconciler/sinkbinding/controller.go
- :broom: Remove an unneeded configmap informer in the sinkbinding controller (handled by the feature store config map watcher)
> Remove unneeded configmapinformer in sinkbinding controller

- test/rekt/features/new_trigger_filters/feature.go
- test/rekt/new_trigger_filters_test.go
Fixes #7241 
- Add a test with multiple triggers and multiple sinks
> Added test for multiple sinks, multiple triggers

- test/rekt/features/new_trigger_filters/feature.go
Part of #7396 
- Refactor the older tests for the new trigger filters to use the new helper functions
> Refactored new filter tests to all use the same helper functions

- pkg/kncloudevents/event_dispatcher.go
- :bug: Fix JWT header content
- :bug: Fix Serviceaccount check
> Fix OIDC token handling in event_dispatcher

- pkg/broker/filter/filter_handler.go
Manual backport of the fix to trigger coercion from https://github.com/knative/eventing/pull/7213
> [release-1.11] fix the type coercion of triggers in the broker filter

- cmd/heartbeats/main.go
- test/auth/oidc_test.go
- test/rekt/features/containersource/features.go
- test/rekt/resources/containersource/containersource.go
- test/rekt/resources/containersource/containersource.yaml
Fixes #7495
Also covers ContainerSource from #7494
- Test ContainerSource with OIDC authentication
- ContainerSource uses SinkBinding under the hood so this also covers the test for SinkBinding
```release-note
```
**Docs**
> ContainerSource test with OIDC

- hack/update-cert-manager.sh
- third_party/cert-manager/00-namespace.yaml
As discussed in https://cloud-native.slack.com/archives/C04LMU33V1S/p1704976362796359?thread_ts=1704936441.258519&cid=C04LMU33V1S
/cc @pierDipi
> Remove kubectl dependency in hack/update-cert-manager.sh

- go.mod
- go.sum
- vendor/github.com/coreos/go-oidc/v3/oidc/jwks.go
- vendor/github.com/coreos/go-oidc/v3/oidc/oidc.go
- vendor/github.com/coreos/go-oidc/v3/oidc/verify.go
- vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
- vendor/github.com/go-jose/go-jose/v3/symmetric.go
- vendor/modules.txt
As per title
/cc @pierDipi @Cali0707 @Leo6Leo
> Update coreos/go-oidc to 3.9.0

- DEVELOPMENT.md
Fixes #7576 
- Fixed broken link of pul request workflow in DEVELOPMENT.md
```release-note
```
**Docs**
> Fixed pull request workflow broken link in DEVELOPMENT.md

- test/rekt/features/new_trigger_filters/feature.go
Fixes #7242
- Added `MultipleFiltersFeature` function that tests for multiple filters in New Event Filtering.
> New Event Filtering: Add rekt test for multiple filters

- DEVELOPMENT.md
Fixes #7578 
- Added the actual test function instead of a hypothetical example.
```release-note
```
**Docs**
> Updated test example to use actual test instead of hypothetical example

- pkg/apis/flows/v1/sequence_lifecycle.go
Cherry-pick https://github.com/knative/eventing/pull/7590/files
> [release-1.12] Cherry-pick Provision sequences CA cert in its status

- pkg/apis/flows/v1/sequence_lifecycle.go
Cherry-pick https://github.com/knative/eventing/pull/7590/files
> [release-1.11] Cherry-pick Provision sequences CA cert in its status 

- .github/workflows/kind-e2e.yaml
- go.mod
- go.sum
> Bump Go to v1.21

- DEVELOPMENT.md
Fixes #7608
- Added a section at the bottom of `development.md` for linux FAQs
- Linked resources to install go using the .tar file method
```release-note
```
**Docs**
> Adding documentation and linking resources for go setup issues with Linux Ubuntu distribution (removed noisy commits)

- pkg/broker/filter/filter_handler.go
> Fix mtbroker-filter to proxy response headers

- pkg/eventingtls/trust_bundle.go
- pkg/reconciler/sinkbinding/controller.go
This is part of #7597.
Not fixing the issue, but some tiny improvements and using correct metadata in logs
> Tiny trustbundle improvements

- hack/teardown.sh
- test/e2e-common.sh
Fixes #7127
- Added a script to teardown installed Eventing component for local development using install.sh.
- Continuation of https://github.com/knative/eventing/pull/7555
> Create teardown script for local development

- config/core/configmaps/default-pingsource.yaml
Fixes #
- remove empty labels...
```release-note
```
**Docs**
> Remove empty labels

- .github/workflows/kind-e2e.yaml
> Update KinD for e2e tests to 0.21.0

- pkg/reconciler/sinkbinding/sinkbinding.go
> Create SinkBindings token-secret only if sink has an audience set

- .github/workflows/kind-e2e.yaml
- hack/create-kind-cluster.sh
> Update min K8s version to 1.28.x for KinD e2e tests

- test/experimental/features/eventtype_autocreate/features.go
- test/rekt/features/apiserversource/data_plane.go
- test/rekt/features/pingsource/features.go
- test/rekt/resources/eventtype/eventtype.go
This verifies that event types become ready, this will probably catch regressions like https://github.com/knative/eventing/commit/1160b459345e652e41f3d7480b3ece0a085c8e26
> Assert EventTypes are ready

- test/rekt/features/channel/data_plane.go
part of #5782 
I filled the todo's under ```f.Stable("Input")``` and removed 
```
May("When dispatching the event, the channel MAY use a different HTTP Message mode of the one used by the event.", todo).
May("The HTTP(S) endpoint MAY be on any port, not just the standard 80 and 443.", todo).
```
As part of the discussion https://cloud-native.slack.com/archives/C04LMU33V1S/p1706689184141499 I concluded these tests are reduntant from what our codebase is doing
```release-note
```
**Docs**
> e2e: channel/DataPlaneConformance

- config/core/configmaps/features.yaml
- pkg/apis/feature/features.go
- pkg/apis/feature/flag_names.go
Fixes #7739
- :gift: Added a feature flag to enable/disable cross-namespace referencing
```release-note
```
**Docs**
> CrossNamespace: adding feature flag

- test/rekt/features/broker/feature.go
- :broom: fix ManyTriggers timings, sometimes causing starvation when both broker/trigger creation and readiness waits are in the same Setup timing
> [e2e] fix ManyTriggers possible starvation of Setup features

- pkg/graph/constructor.go
- pkg/graph/constructor_test.go
- pkg/graph/transforms.go
Fixes #7683 
- Add a transform function to handle the CE Overrides from an event source
- Map the event source into the graph
- Add unit tests
> feat: added sources to event lineage graph constructor

- pkg/eventingtls/trust_bundle.go
As per title.
This should remove some Eventing TLS tests flakes
> Fix trust bundle propagation already exists error

- test/rekt/features/new_trigger_filters/feature.go
- test/rekt/features/new_trigger_filters/filters.go
- test/rekt/new_trigger_filters_test.go
- test/rekt/resources/broker/broker.go
Fixes #7910
- Run installation of Sink, Broker and Trigger sequentially where required so as to prevent resource starvation
```release-note
```
**Docs**
> Refactor NewFiltersFeatureSet to prevent starvation

- pkg/reconciler/subscription/subscription_test.go
- pkg/reconciler/testing/v1/rolebinding.go
- pkg/reconciler/testing/v1/roles.go
Fixes #7916
Changed the way parameters are passed in to create roles and role bindings.
- :gift: Add new feature
```release-note
```
**Docs**
> CrossNamespace: Testing Code Style

- config/brokers/mt-channel-broker/roles/controller-clusterrole.yaml
- config/channels/in-memory-channel/roles/controller-clusterrole.yaml
The eventing controller clusterroles are updated to have knsubscribe permissions for brokers and channels.
- :gift: Add new feature
```release-note
```
**Docs**
> CrossNamespace: Update knsubscribe permissions

- test/lib/recordevents/receiver/reply.go
- test/test_images/event-sender/main.go
> Fix log message for recordevents receiver

- cmd/webhook/main.go
- pkg/apis/eventing/v1beta2/eventtype_conversion.go
- pkg/apis/eventing/v1beta2/eventtype_conversion_test.go
Fixes #7265
- Add EventType v1beta3 conversion
```release-note
```
**Docs**
> Add EventType v1beta3 conversion

- go.mod
- go.sum
- vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
- vendor/modules.txt
> Bump rekt to main

- config/500-job-sink.yaml
> Add JobSink data plane symlink in config/

- pkg/kncloudevents/event_dispatcher.go
> Propagate read error correctly in event-dispatcher

- pkg/apis/eventing/v1beta2/eventtype_defaults_test.go
- pkg/apis/eventing/v1beta3/eventtype_defaults_test.go
- updated test name to avoid confusion, since empty broker was _before_ `broker: ""`, also added explicit expectation of `nil` reference.
```release-note
```
**Docs**
> Event Type API: updated test name to avoid confusion

- go.mod
- vendor/modules.txt
> Remove unneeded replaces in go.mod

- .github/workflows/kind-e2e.yaml
- .github/workflows/knative-downstream.yaml
> Use `knative/actions/setup-go` to be in sync with other projects

- pkg/apis/feature/features.go
Once backported fixes Upgrade test failures like https://prow.knative.dev/view/gcs/knative-prow/logs/continuous_eventing_main_periodic/1806130105928388608
```
Error initializing feature-flags config \"config-features\": \"cannot parse the feature flag 'default-authorization-mode' = 'allow-same-namespace'\"
```
- Avoid fatal errors for unknown features flags that can be added in a future release
```release-note
```
**Docs**
> Avoid fatal errors for unknown features flags that can be added in a future release

- pkg/reconciler/sequence/sequence.go
> fix: set resource version for subscription in sequence reconciler

- pkg/reconciler/sinkbinding/controller.go
Fixed an issue where the controller was incorrectly requeuing the wrong object type (Namespace), resulting in 'resource not found' log errors.
> SinkBinding wrongly enqueues namespaces

- pkg/apis/eventing/v1beta3/eventtype_validation_test.go
- :gift: Add test for v1b3 type validation
```release-note
```
**Docs**
> Enhance tests for v1b3 event type, new attrs

- pkg/reconciler/jobsink/jobsink.go
Fixes #
- as per title
-
-
```release-note
```
**Docs**
> update jobsink TLS comments

- pkg/apis/sinks/v1alpha1/job_sink_types.go
- as per title
```release-note
```
**Docs**
> Add Convertible interface to job sink

- config/core/resources/integrationsink.yaml
- docs/eventing-api.md
- reflect change API types
- remove job-sink references
```release-note
```
**Docs**
> Update integrationsink crd 

- test/rekt/features/integrationsource/features.go
- test/rekt/features/integrationsource/oidc_feature.go
- correct to new event type, as changed in https://github.com/knative-extensions/eventing-integrations/commit/d7ce98e80c260dc867fe79187c70ff3c4963449a
```release-note
```
**Docs**
> We changed the event type on the images

- config/post-install/storage-version-migrator.yaml
Fixes #
- :broom: add new integration CRDs to storage version migrator tool
```release-note
```
**Docs**
> add new integration CRDs to storage version migrator tool

- pkg/reconciler/integration/source/integrationsource_test.go
- pkg/reconciler/testing/v1alpha1/integrationsource.go
Fixes #
- :broom: adding unit test for the OIDC feature of the integration source
```release-note
```
**Docs**
> Adding reconciler test for OIDC of the Integration Source

- test/rekt/features/jobsink/jobsink.go
- test/rekt/resources/jobsink/jobsink.go
This is required for correct functioning of the test with Istio.
Fixes #
-
-
-
```release-note
```
**Docs**
> JobSink with Istio config for Job spec

- config/core/deployments/controller.yaml
- pkg/reconciler/integration/sink/integrationsink_test.go
- pkg/reconciler/integration/sink/resources/container_image.go
- pkg/reconciler/integration/source/integrationsource_test.go
- pkg/reconciler/integration/source/resources/containersource.go
- pkg/reconciler/integration/source/resources/containersource_test.go
As per title, this starts using specific SHA references of images
> Inject integration images from ConfigMap

- config/400-config-eventing-integrations-images.yaml
Fixes #
- as per title
```release-note
```
**Docs**
> Update to the correct file

- pkg/reconciler/eventtransform/controller.go
- pkg/reconciler/eventtransform/eventtransform.go
- pkg/reconciler/eventtransform/resources_jsonata.go
Inject tracing configurations to Jsonata deployment
> EventTransform: Inject tracing configurations

- pkg/apis/eventing/v1alpha1/eventtransform_lifecycle.go
- pkg/reconciler/eventtransform/eventtransform.go
- pkg/reconciler/eventtransform/eventtransform_test.go
- pkg/reconciler/testing/v1/listers.go
- pkg/reconciler/testing/v1alpha1/eventtransform.go
This adds reconciler unit tests for EventTransform.
> EventTransform: add reconciler unit tests

- cmd/controller/main.go
- pkg/apis/eventing/v1alpha1/eventtransform_lifecycle.go
- pkg/apis/eventing/v1alpha1/eventtransform_validation.go
- pkg/apis/eventing/v1alpha1/eventtransform_validation_test.go
- pkg/certificates/certificate.go
- pkg/certificates/certificate_test.go
- pkg/eventingtls/trust_bundle.go
- pkg/eventingtls/trust_bundle_test.go
- pkg/reconciler/eventtransform/controller.go
- pkg/reconciler/eventtransform/eventtransform.go
- pkg/reconciler/eventtransform/eventtransform_test.go
- pkg/reconciler/eventtransform/resources_jsonata.go
- pkg/reconciler/integration/sink/controller.go
- pkg/reconciler/integration/sink/integrationsink.go
- pkg/reconciler/testing/v1/factory.go
- pkg/reconciler/testing/v1/listers.go
- pkg/reconciler/testing/v1alpha1/eventtransform.go
- test/rekt/eventtransform_test.go
- test/rekt/features/eventtransform/eventtransform.go
Follow up to https://github.com/knative-extensions/eventing-integrations/pull/73
-
-
-
```release-note
```
**Docs**
> Event Transform JSONata TLS

- test/rekt/features/eventtransform/eventtransform.go
> Skip EventTransform TLS tests when Istio is enabled

- pkg/apis/sinks/v1alpha1/integration_sink_lifecycle.go
- pkg/apis/sinks/v1alpha1/integration_sink_lifecycle_test.go
- pkg/reconciler/integration/sink/integrationsink.go
Fixes #
- propagate cert status to integrationsink status
- refactoring of the `reconcileIntegrationSinkCertificate` and adding little create/update Certificate helpers 
```release-note
```
**Docs**
> Propagate Cert-Manager Certificate status to the one from the IntegrationSink

- pkg/apis/common/integration/v1alpha1/aws.go
- pkg/reconciler/integration/helper.go
- pkg/reconciler/integration/helper_test.go
Fixes #8511
- :bug: Remove the incorrect value of the tag and update the function that assembles the actual ENV_VARs
```release-note
```
**Docs**
> Fixing the way we render custom camel tags on go structs

- config/core/roles/controller-clusterroles.yaml
Fix reconciliation errors wrt permissions
> Allow setting finalizers for EventTransform reconciler

- pkg/reconciler/containersource/containersource.go
Fixes https://github.com/knative/eventing/issues/8547
- Compare the entire PodTemplateSpec, instead of just its PodSpec
```release-note
ContainerSource now compares the entire PodTemplateSpec, instead of just its PodSpec. This avoids loosing edits on metadata, like annotations
```
**Docs**
> Compare the entire PodTemplateSpec, instead of just its PodSpec

- docs/mt-channel-based-broker/README.md
> fix a typo in broker readme: kantive

- pkg/apis/messaging/v1/in_memory_channel_validation.go
- pkg/apis/messaging/v1/in_memory_channel_validation_test.go
- pkg/reconciler/broker/resources/eventpolicy.go
Fixes #8407 
- :broom: remove hard-coded knative-eventing namepsace in controller logic
```release-note
```
**Docs**
> Fix hardcoded knative-eventing namespace

- pkg/eventingtls/trust_bundle.go
Fixes #8588
- Lets order the source'd CMs on the projected volume
```release-note
```
**Docs**
> Try to ensure ordering of referenced source CMs, by name

- config/core/resources/integrationsource.yaml
- docs/eventing-api.md
- pkg/apis/sources/v1alpha1/integration_types.go
- pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
- pkg/reconciler/integration/source/resources/containersource.go
- 🎁  #8597 
```release-note
```
**Docs**
> feat: support for additional pod scheduling definition on IntegrationSource

- config/core/configmaps/observability.yaml
- config/core/configmaps/tracing.yaml
- go.mod
- pkg/observability/config.go
- pkg/observability/config_test.go
- pkg/observability/configmap/configmap.go
- pkg/observability/otel/otel.go
- Add new otel config
- Add function to setup observability for use in the adapter main functions
> feat: add new otel config

- cmd/jobsink/main.go
- pkg/observability/key.go
- pkg/observability/newcontext.go
- Setup OTel in the JobSink handler
- Record dispatch metrics in the JobSink handler
```release-note
The JobSink now reports metrics with OTel
```
> feat: instrument jobsink with otel

- pkg/auth/verifier.go
- Instrument the auth verifier with OTel
> feat: instrument auth verifier with OTel

- cmd/webhook/main.go
> drop use of tracing config map in webhook

- test/lib/client.go
- test/lib/creation.go
- test/test_images/recordevents/main.go
- test/test_images/utils.go
- test/upgrade/prober/config.toml
- test/upgrade/prober/configuration.go
- test/upgrade/prober/wathola/config/defaults.go
- test/upgrade/prober/wathola/config/structure.go
- test/upgrade/prober/wathola/config/tracing.go
Removes the usage of `knative.dev/pkg/tracing` from the test code
> cleanup: drop pkg/tracing from test code
